### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by Gimlao** [Nandaka/PixivUtil2#100]
PixivUtil2 seems to have difficulties with some files, while Chrome shows them fine, so I don't really know what's happening here...

Console : http://pastebin.com/bt2w5TGL
Log : http://pastebin.com/WD04wNDV

**Comment by Nandaka** [comment]
most likely you got network issue, I can download the image completely.

Can you check the image (53260666) and see what is the file size in your browser? It should show 82,524 bytes.
