### ISSUE TITLE
By Python official announcement, Python 3.9 is not support Windows 7 sp1.

### ISSUE THREAD

**Issue by SkyBaldr** [Nandaka/PixivUtil2#1000]
### Prerequisites

* [V ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [V ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [V ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

[Description of the bug or feature]

By official announcement, Python 3.9 is not support Windows 7 sp1.
https://www.python.org/downloads/release/python-390/

When I run Pixivutil2 on Winsows7 sp1, first get "api-ms-win-core-path-l1-1-0.dll not found" and console shown "FATAL ERROR: Could not load python library."

Get the  "api-ms-win-core-path-l1-1-0.dll" from somewhere, re-run Pixivutil, it shows dump:

Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'D:\pixivutil20210702\PixivUtil2.exe'
  isolated = 1
  environment = 0
  user site = 0
  import site = 0
  sys._base_executable = '\xc4C\ue7c0G\u0908\u0b0a\u0d0c\u0f0e\u1110\u1312\u1514
\u1716\u1918\u1b1a\u1d1c\u1f1e\u2120\u2322\u2524\u2726\u2928\u2b2a\u2d2c\u2f2e\u
3130\u3332\u3534\u3736\u3938\u3b3a\u3d3c\u3f3e\u4140\u4342\u4544\u4746\u4948\u4b
4a\u4d4c\u4f4e\u5150\u5352\u5554\u5756\u5958\u5b5a\u5d5c\u5f5e\u6160\u6362\u6564
\u6766\u6968\u6b6a\u6d6c\u6f6e\u7170\u7372\u7574\u7776\u7978\u7b7a\u7d7c\u7f7e\u
2080\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u20
20\u2020\u2020\ua1a0\ua3a2\ua5a4\ua7a6\ua9a8\uabaa\uadac\uafae\ub1b0\ub3b2\ub5b4
\ub7b6\ub9b8\ubbba\ubdbc\ubfbe\uc1c0\uc3c2\uc5c4\uc7c6\uc9c8\ucbca\ucdcc\ucfce\u
d1d0\ud3d2\ud5d4\ud7d6\ud9d8\U001069dc\udfde\u2020\u2020\u2020\u2020\u2020\u2020
\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\ufd20\ufffe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = '\xc4C\ue7c0G\u0908\u0b0a\u0d0c\u0f0e\u1110\u1312\u1514\u1716
\u1918\u1b1a\u1d1c\u1f1e\u2120\u2322\u2524\u2726\u2928\u2b2a\u2d2c\u2f2e\u3130\u
3332\u3534\u3736\u3938\u3b3a\u3d3c\u3f3e\u4140\u4342\u4544\u4746\u4948\u4b4a\u4d
4c\u4f4e\u5150\u5352\u5554\u5756\u5958\u5b5a\u5d5c\u5f5e\u6160\u6362\u6564\u6766
\u6968\u6b6a\u6d6c\u6f6e\u7170\u7372\u7574\u7776\u7978\u7b7a\u7d7c\u7f7e\u2080\u
2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u2020\u20
20\u2020\ua1a0\ua3a2\ua5a4\ua7a6\ua9a8\uabaa\uadac\uafae\ub1b0\ub3b2\ub5b4\ub7b6
\ub9b8\ubbba\ubdbc\ubfbe\uc1c0\uc3c2\uc5c4\uc7c6\uc9c8\ucbca\ucdcc\ucfce\ud1d0\u
d3d2\ud5d4\ud7d6\ud9d8\U001069dc\udfde\u2020\u2020\u2020\u2020\u2020\u2020\u2020
\u2020\u2020\u2020\u2020\u2020\u2020\u2020\ufd20\ufffe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'D:\\pixivutil20210702\\library.zip',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the file
system encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1353, in _path_importer_ca
che
KeyError: 'D:\\pixivutil20210702\\library.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 92, in __init__
KeyError: 'D:\\pixivutil20210702\\library.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1355, in _path_importer_ca
che
  File "<frozen importlib._bootstrap_external>", line 1331, in _path_hooks
  File "<frozen zipimport>", line 94, in __init__
  File "<frozen zipimport>", line 463, in _read_directory
  File "<frozen importlib._bootstrap_external>", line 99, in _path_join
SystemError: Negative size passed to PyUnicode_New

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]

If there is a chance to support Windows 7...

### Versions

V20210702

**Comment by Nandaka** [comment]
see #971

**Comment by SkyBaldr** [comment]
Thanks for your kindly comment. Sorry for bother you.

**Comment by Nandaka** [comment]
You still can run from source code using python 3.8.x for the latest version

I have compile win7 version in the release page https://github.com/Nandaka/PixivUtil2/releases/tag/v20210822
