### ISSUE TITLE
Fanbox downloading fails, "No images for Member"

### ISSUE THREAD

**Issue by Syampuuh** [Nandaka/PixivUtil2#1001]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Attempting to download from Fanbox by any method fails with an error claiming there are no images. Perhaps Pixiv may have changed something in just the last day or so, as I had no issues with it only yesterday. The fanbox API page that the tool uses indeed reports a generic error. An example: https://api.fanbox.cc/creator.get?userId=17145731
Relevant log: https://pastebin.com/i3360yv1

### Versions

PixivDownloader2 version 20210702

**Comment by bluerthanever** [comment]
should be fixed in #992.
please wait for the next release?

**Comment by Syampuuh** [comment]
Yep, that did the trick, thank you.
