### ISSUE TITLE
URLdump: Note post and *artist* for fanbox posts

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#1002]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Currently, if I want to find the Fanbox post from which I got URL from, I need to search through my email for post number.

Meanwhile, to get one from main pixiv, I need to only add post id to https://www.pixiv.net/artworks/<ID HERE>

To completely identify source for url dump, artist is needed for Fanbox.

### Steps to Reproduce

1. Enable URLDump
2. Download from Fanbox Favorites
3. Open urldump file and try to find where URL came from for context and/or password

**Expected behavior:** I have enough information to locate source post

**Actual behavior:** Pixiv needs author ID and post number for access

### Versions

20210702

**Comment by Nandaka** [comment]
any recommendation? based on https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L909, it only write something like this:
```
#90089706
http://skeb.jp/@shinashite
```

to something like this?
```
# Pixiv Author ID: 3255968 - Image ID: 90089706
http://skeb.jp/@shinashite
# Fanbox Author ID: <some id> - Post ID: <some id>
https://google.com/some-url
```

**Comment by NHOrus** [comment]
Well, I prefer minimalism, so leave first case as is, and make second as
   #<post id> f#<artist id>
