### ISSUE TITLE
[Feature Request] Resolve and download Pixiv by Fanbox "artist/creator" id

### ISSUE THREAD

**Issue by cglmrfreeman** [Nandaka/PixivUtil2#1005]
### Prerequisites

* [:heavy_check_mark: ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [:heavy_check_mark:  ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [:heavy_check_mark:  ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
Sometimes, browsing twitter, I want to see an artist's Pixiv. Sometimes to do this, I will have to visit their Fanbox, which may be the only link available, and they might have their Pixiv link in their Fanbox. Other times, the Fanbox may not have their Pixiv link, so I have to use twitter's search function "from:artist-twitter-handle pixiv" to find if they have posted any of their works int he past. Sometimes if I am really lucky and their Fanbox does not have their Pixiv link, their linked skeb might.

PixivUtil2 has built-in calls to resolve the proper number from a Fanbox username to the id, which will always be the same as their Pixiv id. I would love a feature where I can just plug in the Fanbox username and their free Pixiv works can be backed up.

### Steps to Reproduce

:no_entry_sign:

### Versions
20210822

**Comment by byjtje** [comment]
Doesn't really answer what you want, but instead of searching through their twitter you can just get the Artist's ID, which is the same for Booth/Pixiv/Fanbox etc. by looking at the json request in the Network tab or just right clicking inspect element on their avatar/banner:
![2021-09-17-15:49:53](https://user-images.githubusercontent.com/14181316/133793905-4ab4b3bf-bb21-4a0d-8bbd-ad8a3c3c1fd7.png)

**Comment by cglmrfreeman** [comment]
I remember back in the day there were no vanity Fanbox urls lol. Ever since they changed to that it's made things a little more miserable for me. 

The background image of the avatar is very good to know, however! I'll keep that in mind. I might fork PixivUtil2 and try to implement a check myself using the same check I think the fanbox module uses.

**Comment by byjtje** [comment]
> the same check I think the fanbox module uses.
It uses the same API call as above https://github.com/Nandaka/PixivUtil2/blob/e92b2a49d9618e5a41cfc04f3afc8f5c9e1e0975/PixivBrowserFactory.py#L920

**Comment by cglmrfreeman** [comment]
> It uses the same API call as above
That is not what I meant. 

Yes, it uses the same API call but it is not implemented within "Download by member_id". I would need to implement that portion myself, and yes, use that API call that is used in the fanbox check.

**Comment by Nandaka** [comment]
Assuming `user/userId` is the pixiv artist id.
![image](https://user-images.githubusercontent.com/836867/133985138-4128f63a-cdcd-41d0-b385-8c3ff9a2602b.png)

Implemented as option f6, need the creatorId as input.
![image](https://user-images.githubusercontent.com/836867/133985367-cd69df47-99f2-4d11-8a90-992bb2bd76b1.png)

**Comment by cglmrfreeman** [comment]
Heeeey! That'll work excellently! Thank you very much! Will try it out and report back!

**Comment by cglmrfreeman** [comment]
Well, it sort of works with a bit of a bug. 
`Processing images from -47 to XYZ of XYZ`

I was also kind of hoping this wouldn't be a fanbox feature but rather integrated into `Download by member_id` where it detects if it's not a numerical id, the program tries to parse the letters and check that string against the fanbox lookup.

**Comment by cglmrfreeman** [comment]
Was this fixed or removed? I would prefer it be removed if it's still in it's current implementation.

**Comment by cglmrfreeman** [comment]
@byjtje Ran into a situation where a Fanbox member has no icon, in which the system encodes a url as `data:image/png;base64,` and the pixiv id can't be resolved.

**Comment by bluerthanever** [comment]
hmm...??
i am a little confused when i recently updated all my scripts from master and found that there's a new option f6. and after browsing this thread i was like "did not i implement this on function f2 already?" you can input both user ids which are digits only or creator ids which contain alphabets and stuff.
even though i just tested and found out that the regular expression for f2 doesn't seem to work so well with urls like `https://{creatorId}.fanbox.cc`

**Comment by bluerthanever** [comment]
oh... sorry.. that was meant for pixiv contents... sorry...... was confused that it was under fanbox.... sorry.

**Comment by cglmrfreeman** [comment]
> oh... sorry.. that was meant for pixiv contents... sorry...... was confused that it was under fanbox.... sorry.

Haha yeah. Sometimes I just want to save a user's pixiv contents but they _only_ link their fanbox. I am now just inspecting their icons, as it's much faster to grab the id, shove it in a text file with other ids, and them grab them all at once instead of option f6. It should be removed in my opinion. I would have preferred the feature integrated with option 1, where numeric ids and fanbox (or pixiv.me ids) could be resolved together. Oh well.
