### ISSUE TITLE
ugoira -> gif

### ISSUE THREAD

**Issue by ArjixWasTaken** [Nandaka/PixivUtil2#1006]
So uhh, I saw in the config that I can convert an ugoira to a gif...but even if that option is set to "True" it still doesnt do it.
Maybe it plans to do it when its done downloading all the ugoira in the queue? I don't know.

In the mean time I wrote this script to do the job for me:
```python
from pathlib import Path
from PIL import Image
import shutil
import time
import os
import re

main_folder = "D:/Downloads/Compressed/pixivutil20210822"  # the folder where the downloads are saved in

while 1:
    print("Sleeping for 2 minutes...")
    time.sleep(60*2)
    print("Continuing...")
    artists = [
        os.path.join(main_folder, x).replace("\\", "/")
        for x in sorted([x[1] for x in os.walk(main_folder)][0])
        if (
            os.path.isdir(os.path.join(main_folder, x)) and
                re.match(r".*? \(\d+\)", str(x))  # the regex pattern that matches the artist folders
        )
    ]

    for folder_path in artists:
        folders = [
            os.path.join(folder_path, x)
            for x in sorted([x[2] for x in os.walk(folder_path)][0])
            if (os.path.isfile(os.path.join(folder_path, x)) and x.endswith(".zip"))
        ]

        for zip_ in folders:
            zip_ = zip_.replace("\\", "/")
            shutil.unpack_archive(zip_, zip_.replace(".zip", "").rstrip(".").strip())

            files = [
                os.path.join(zip_.replace(".zip", "").rstrip(".").strip(), x).replace("\\", "/")
                for x in os.listdir(zip_.replace(".zip", "").rstrip(".").strip())
            ]

            if len(files) == 0:
                continue

            filename = Path(zip_.replace(".zip", "").rstrip(".").strip()).parts[-1] + ".gif"

            Image.open(files[0]).save(
                os.path.join(Path(zip_.replace(".zip", "").rstrip(".").strip()).parent, filename),
                format='GIF',
                append_images=[Image.open(x) for x in files[1:]],
                save_all=True,
                duration=300, loop=0
            )

            try:
                shutil.rmtree(zip_.replace(".zip", "").rstrip(".").strip())
                os.remove(zip_)
            except OSError:
                pass
            print("Converted: {}".format(zip_.replace(".zip", "").rstrip(".").strip() + ".gif"))
```

Anyways, this was fun to write, posting it here for anyone that might find a use for it.

**Comment by ArjixWasTaken** [comment]
This requires for PILLOW (python image processing package) to be installed.

**Comment by ArjixWasTaken** [comment]
Oh yeah, the gif duration is not so great, I calculate it based on the frames of the gif, but uhh
It works great with some, and badly with others.

You might want to set it to a constant speed of 300 or smth along those lines.

**Comment by ArjixWasTaken** [comment]
If you are downloading a huge amount of ugoira (just like me) I suggest putting this in a while loop, and make it sleep for like a minute before each loop.

**Comment by ArjixWasTaken** [comment]
Oh yeah, this was tested with the default config.
(except for the option "convert to gif" that did nothing)

**Comment by Nandaka** [comment]
You need to configure the ffmpeg.exe location.

From readme:
```
creategif

Set to True to convert ugoira file to gif. Required createUgoira = True and ffmpeg executeable.
```

https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L921
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L949

**Comment by ArjixWasTaken** [comment]
> You need to configure the ffmpeg.exe location.
> 
> From readme:
> ```
> creategif
> 
> Set to True to convert ugoira file to gif. Required createUgoira = True and ffmpeg executeable.
> ```
> 
> https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L921
> https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L949

But since you already have PILLOW as a dependency, why not use that?
Why depend on a non-pythonic approach?

**Comment by Nandaka** [comment]
See https://github.com/Nandaka/PixivUtil2/issues/802

**Comment by ArjixWasTaken** [comment]
> See #802

Now it makes sense.
Although, one thing I did not mention was that I already have ffmpeg installed and it's on path, so the default config should have worked, no?

And btw, making a feature not work unless ffmpeg is installed is not optimal, you could for example use Pillow as a backup method in case ffmpeg is not found.

**Comment by Nandaka** [comment]
or I can just terminate if it is not found, currently it will set the flags to False.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1339
