### ISSUE TITLE
Artist's sketch page when downloading with list.txt?

### ISSUE THREAD

**Issue by ghost** [Nandaka/PixivUtil2#1007]
Downloading with member ID (option 1) asks you whether you want to download the sketch page as well or not, what about downloading with list.txt (option 4)? What happens to the artist's sketch page when downloading with option 4? Can this option be added to the config file?

### Versions
20210702

**Comment by Nandaka** [comment]
implemented in latest commit. It will ask if you want to also download Pixiv Sketch for option 4
