### ISSUE TITLE
Malwarebytes detects PixivUtil2 as Malware.AI

### ISSUE THREAD

**Issue by yul-oh895** [Nandaka/PixivUtil2#1008]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I already about issue #972 in the past but I never experienced any virus alert with Windows Defender, even when trying it right now.

However, today i tried running PixivUtil and Malwarebytes detected it as a Malware.AI.2836008354 More info [here](https://blog.malwarebytes.com/detections/malware-ai/).

![2021-09-05_13-53-19](https://user-images.githubusercontent.com/64549167/132139844-7d5868f1-8c4d-43d9-9cad-938bf8b31b3b.png)

![2021-09-05_13-39-30](https://user-images.githubusercontent.com/64549167/132139616-4c2dde96-3708-4160-b977-136f1a8c4194.png)

I ran the [file through VirusTotal ](https://www.virustotal.com/gui/file/1a3d55723798dcd35be80ecac2cc5e9f7a539fb35778ccb2da05e7d0923d56c4/detection)and it was detected by other antiviruses except Malwarebytes. 

As this is related to Malwarebytes and not Windows Defender, I decided to create a new issue. If the cause of it the same as with the previous Windows Defender's issue, this can be closed.

### Steps to Reproduce

1. Open PixivUtil2.exe file.
2. Malwarebytes automatically quarantines the file and alerts of the detection.

**Expected behavior:** 
Run and open PixivUtil2.exe

**Actual behavior:**
PixivUtil2.exe is quarantined.

### Versions
20210822

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
see #972
