### ISSUE TITLE
[Feature Request] Set separate download folders for Pixiv and Fanbox

### ISSUE THREAD

**Issue by yul-oh895** [Nandaka/PixivUtil2#1009]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I would like to request the option to set different folders in `config.ini`.

Currently, I have set `rootdirectory` with my Pixiv folder (e.g C:/Pictures/Pixiv) but when I need to download Fanbox posts, I need to manually change it to my Fanbox folder (e.g. C:/Pictures/Fanbox). Ideally, I would like to set both folders on config file so when it detects I'm downloading Pixiv pictures or Fanbox posts it will download them to their correct location without me manually changing the setting.

### Steps to Reproduce

1. Open config.ini and confirm the `rootdirectory` is set to Pixiv folder.
2. Open PixivUtil2.exe and download any picture or artist from main Pixiv website.
3. Close PixivUtil2
4. Open config.ini and change `rootdirectory` to Fanbox folder
5. Open PixivUtil2.exe and download any Fanbox post.

**Expected behavior:** [What you expected to happen]

PixivUtil2 detects if I'm trying to download a Pixiv gallery (post or manga) and downloads it to the Pixiv folder. If It detects I'm downloading a Fanbox post, It downloads the files to the Fanbox folder.

**Actual behavior:** [What actually happened]

I have to manually change the folders before each download type (Pixiv gallery or Fanbox) so the files are downloaded in the correct location.

### Versions
20210822

**Comment by Nandaka** [comment]
change your filenameformats in config.ini

**Comment by yul-oh895** [comment]
Thank you.
