### ISSUE TITLE
How can I use list.txt to download illust_id?

### ISSUE THREAD

**Issue by g4269159** [Nandaka/PixivUtil2#101]
I want to batch download a lot of illust_id using list.txt, but PixivUtil2 doesn't recognize the full URL. What can I do to batch download a lot of links at once?

**Comment by Nandaka** [comment]
no feature for that, but you can try to run it from console and supply the image ids separated by space.

``` PixivUtil2.exe -s 2 imageid1 imageid2 imageid3 ```
