### ISSUE TITLE
user ID does not exist and breaks the download v20210822 

### ISSUE THREAD

**Issue by SnakeEve** [Nandaka/PixivUtil2#1011]
### Prerequisites

* [V] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [V] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [V] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
First i use version 20210822 from master branch. I have a long download list which i always repeat every 2-3 days, some of artist happened to deactivate their account, eventually reactivate, or some were just banned, not mentioning their artworks often get removed.

I use a new computer and i pulled the master branch, sometimes if the downloader reaches a suspended / not found user, the download breaks.

### Steps to Reproduce

1. download from list
2. pixiv sketch yes
3. stumbled upon a dead user
4. error and breaks the download

**Expected behavior:** Move on to the next download

**Actual behavior:** shows this error message and break the download

```
Error at process_list(): (<class 'PixivException.PixivException'>, PixivException('User has left pixiv or the user ID does not exist.'), <traceback object at 0x0105E788>)
Failed
User has left pixiv or the user ID does not exist.
```

### Versions
20210822

**Comment by SnakeEve** [comment]
Thanks, I've tried it again, with the exact steps to reproduce, and it gives me this error when it reached a removed account, i think as far as i remember, it is the very same account which caused this issue #1011 

```
Processing Member Id: 2446302
Page
Member Url: https://www.pixiv.net/ajax/user/2446302/profile/all
Member ID (2446302): PixivException(1003 User has left pixiv or the user ID does not exist., hasDumpPage=Y)
User has left pixiv or the user ID does not exist.
Member Url: https://www.pixiv.net/ajax/user/2446302/profile/all
Something wrong, retrying after 2 second (1) ==> PixivException(1003 User has left pixiv or the user ID does not exist., hasDumpPage=Y)
Error at process_list(): (<class 'AttributeError'>, AttributeError("type object 'datetime.time' has no attribute 'sleep'"), <traceback object at 0x01727EC8>)
Failed
Traceback (most recent call last):
  File "D:\Python\PixivUtil2\PixivListHandler.py", line 70, in process_list
    (artist_model, _) = br.getMemberPage(item.memberId)
  File "D:\Python\PixivUtil2\PixivBrowserFactory.py", line 768, in getMemberPage
    artist = PixivArtist(member_id, response, False, offset, limit)
  File "D:\Python\PixivUtil2\PixivArtist.py", line 42, in __init__
    raise PixivException(payload["message"], errorCode=PixivException.OTHER_MEMBER_ERROR, htmlPage=page)
PixivException.PixivException: PixivException(1003 User has left pixiv or the user ID does not exist., hasDumpPage=Y)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1395, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args, options)
  File "PixivUtil2.py", line 1091, in main_loop
    menu_download_from_list(op_is_valid, args, options)
  File "PixivUtil2.py", line 478, in menu_download_from_list
    PixivListHandler.process_list(sys.modules[__name__],
  File "D:\Python\PixivUtil2\PixivListHandler.py", line 85, in process_list
    time.sleep(2)
AttributeError: type object 'datetime.time' has no attribute 'sleep'
Unknown Error, please check the log file: (<class 'AttributeError'>, AttributeError("type object 'datetime.time' has no attribute 'sleep'"), <traceback object at 0x01727AA8>)
press enter to exit.
```

**Comment by Nandaka** [comment]
updated, due to wrong import. change to use helper method instead :P

**Comment by SnakeEve** [comment]
It works perfectly! Thanks a lot! I will post some new issue if i found some during the download run later on
