### ISSUE TITLE
"error in demjson setup command: use_2to3 is invalid."

### ISSUE THREAD

**Issue by BassOfBass** [Nandaka/PixivUtil2#1012]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
While updating my `virtualenv` setup to 3.8, I've stumbled upon aforementioned error.
It looks like [the latest version of `setuptools` is incompatible with the package used by `demjson`](https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0).

There is a [`demjson3` package](https://pypi.org/project/demjson3/) and it installs just fine and at glance seems to have the same API as the old version. So maybe replacing the package in `requirements.txt` and replacing module references to `demjson3` will be enough.
### Steps to Reproduce
Just have the latest `setuptools` I guess.
But the `virtualenv` steps are like this:
1. clone repo
2. `virtualenv --python 3.8 venv`
3. `source venv/Scripts/activate`
4. `pip install --requirement requirements.txt`
5. error out

### Versions
latest

**Comment by Nandaka** [comment]
hmm, looks fine in Windows with Python 3.8.10 32bit

![image](https://user-images.githubusercontent.com/836867/133438441-c581ff77-2514-4574-8d51-898b6e06d88e.png)
![image](https://user-images.githubusercontent.com/836867/133438647-27601a53-5172-4363-9fe1-d609c90ffc2a.png)

**Comment by BassOfBass** [comment]
What version of `setuptools` is used in your setup?
```sh
pip list
```

**Comment by Nandaka** [comment]
![image](https://user-images.githubusercontent.com/836867/133450337-1d708acd-7bbe-4ecf-831c-6f10333fd479.png)
![image](https://user-images.githubusercontent.com/836867/133450390-925e633a-d969-4a6f-8c76-1b682716ff0b.png)

**Comment by BassOfBass** [comment]
`setuptools` is `56.0.0`, that's why it works for you. For now at least.

**Comment by BassOfBass** [comment]
So what are you going to do? It won't fix itself and the problem will only get worse as more tools start using `58.0.0`.

**Comment by Nandaka** [comment]
nothing as I don't have the issue yet, you can send me a pull request though,

**Comment by BassOfBass** [comment]
Closing because it got merged.
