### ISSUE TITLE
[Question] Downloading image descriptions?

### ISSUE THREAD

**Issue by MarqFJA87** [Nandaka/PixivUtil2#1016]
I've tried looking for how to do this in the readme and even searched the issues for it, but couldn't find anything relevant. Is there a way to download the descriptions that Pixiv posts may have? I tried writeimageinfo, but it seems to be irrelevant.

**Comment by Baa14453** [comment]
`writeimageinfo` is the right one, it creates a text file containing the info. The description is labelled as Caption

```
ArtistID      = 1096811
ArtistName    = チャイ
ImageID       = 82726962
Title         = ソフトクリームの日
Caption       = ひんやりキャットタワー
Tags          = original, Sweets Bird, まぎれるこねこ, いきものごはん, 素晴らしきほっこりの世界, ちょこーとり, ミックスキャット, happy baby birds, ここに巣を作ろう, 密かに紛れるチョコトゥーリ
Image Mode    = big
Pages         = 1
Date          = 2020-07-03 11:30:04+00:00
Resolution    = 1200x2000
BookmarkCount = 6367
Link          = http://www.pixiv.net/en/artworks/82726962
```

**Comment by MarqFJA87** [comment]
Thank you.
