### ISSUE TITLE
The filenameFormat is completely ignored by some files

### ISSUE THREAD

**Issue by user4302** [Nandaka/PixivUtil2#1018]
### Prerequisites

* [✔] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [✔] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [✔] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

the filenameFormat is completely ignored by some files,
the format is
"filenameFormat": "%artist% (%member_id%)/%works_date%--%urlFilename%--[%artist% (%member_id%)]--%title%",
my entire batch script is this
![image](https://user-images.githubusercontent.com/32593782/135078472-21ebca8f-604b-4f71-8a59-37a405ef10d6.png)

i renamed all my images and also edited the format string to match the format that i renamed the images to
i ran the batch command and it skipped 2 files (as expected), but started downloading the file after that, and the file name was not the name that i specified, as shown in the images below
![PixivUtil Downloading](https://user-images.githubusercontent.com/32593782/135077059-5965d681-e8c4-4261-b5d2-a57a14ec6886.png)
![Currently downloading image](https://user-images.githubusercontent.com/32593782/135076921-c5352516-b111-499e-9020-7d90847ee7be.png)

i also confirmed that the file that it is attempting to download, does already exist, so my guess is that the filename being ignored is causing a re download.
![image](https://user-images.githubusercontent.com/32593782/135078114-e0b558cb-2562-4341-80c9-70d9300694a9.png)

i also moved the files out of the normal download folder and used "Clean up database", as i was planning to re download all images, before i found a way to rename the files.

### Steps to Reproduce

1. rename files
2. edit batch file to match renamed name scheme
3. run batch (b) command in pixiv util

**Expected behavior:** [What you expected to happen]
the downloaded images will be skipped and any new (un downloaded) images will be downloaded with the specified file name format

**Actual behavior:** [What actually happened]
some downloaded images were skipped, and an image started downloading with an unspecified file name format

### Versions
20210822

**Comment by Nandaka** [comment]
because it is a manga? You need to set `filenamemangaformat` too.
![image](https://user-images.githubusercontent.com/836867/135100633-263b627d-c19b-48da-9e46-e6e8b6a0c138.png)

**Comment by user4302** [comment]
> because it is a manga? You need to set `filenamemangaformat` too. ![image](https://user-images.githubusercontent.com/836867/135100633-263b627d-c19b-48da-9e46-e6e8b6a0c138.png)

i replaced filenameFormat with filenamemangaformat
and also tried adding both filenamemangaformat as well as filenameFormat with their naming schemas.

but the outcome was the same for that file in all cases.
this is the image https://www.pixiv.net/en/artworks/91649300
there seems to be 2 images, im guessing that means its classified as a manga.

**Comment by Nandaka** [comment]
yes, refer to https://github.com/Nandaka/PixivUtil2/wiki/Using-Batch-Job-(Experimental)

also check your config.ini

**Comment by user4302** [comment]
i edited the config.ini file and it seems to be working as expected now,
i did add it into the batch job itself like this 
![image](https://user-images.githubusercontent.com/32593782/135184507-002bc053-c3b5-4844-9d38-d707b9e82a8a.png)

but it did not change anything, what did i do wrong?
but everything is ok now, after editing the config.ini file.

**Comment by Nandaka** [comment]
case sensitive, try to use `filenameMangaFormat`

**Comment by user4302** [comment]
oh ok, i was confused cos the;
'filenamemangaformat' in https://github.com/Nandaka/PixivUtil2#filename
and 'filenameMangaFormat' in https://github.com/Nandaka/PixivUtil2/wiki/Using-Batch-Job-(Experimental)
are not the same case
so the variables are not always the same between the config.ini and the batch.json?

**Comment by Nandaka** [comment]
the config.ini is not case sensitive due to how .ini works in python, but json file is case sensitive, so always refer to the wiki one
