### ISSUE TITLE
need multiple tags support

### ISSUE THREAD

**Issue by TimeCompass** [Nandaka/PixivUtil2#102]
I tried option 3 with more than 1 tag and get "0 results"(or sth means this). After that I tried to link the url which PixivUtil2 uses in Chrome and get same result.

Looks like that "s_tag_full" should not be using in this situation.I changed it into "s_tag" and now I've got the right(I think it's right) result.

While I'm trying to use the tag "榛名 艦これ"  to get images that both have tag "榛名" and tag "艦これ", I found that pixiv also supports "-" tag to remove the images which has a tag that I don't want it to be display. Just add a Hyphen like “榛名 -艦これ” would be OK.

I hope if you could add this support, thank you.

this two links shows the difference between s_tag and s_tag_full when search with one more tags
http://www.pixiv.net/search.php?s_mode=s_tag&word=%E6%A6%9B%E5%90%8D%20%E8%89%A6%E3%81%93%E3%82%8C&scd=2015-10-05&ecd=2015-10-05
http://www.pixiv.net/search.php?s_mode=s_tag&word=%E6%A6%9B%E5%90%8D%20%E8%89%A6%E3%81%93%E3%82%8C&scd=2015-10-05&ecd=2015-10-05

**Comment by Nandaka** [comment]
try using partial math = Y on the console
