### ISSUE TITLE
Keyboard interrupt; Continue to next image doesn't work in fanbox mode.

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#1020]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Start downloading Supported Artists from Fanbox with `f1`
2. Press Ctrl-C in the middle of the process
3. PixivUtil2 reports "Keyboard interrupt detected, continue to next post (y/n) ?
4. Press n

**Expected behavior:** [What you expected to happen]
PixivUtil2 doesn't continue to next post and goes to next supported artist, similar to download from list.

**Actual behavior:** [What actually happened]
Download of the post resumes.

### Versions

20210822

**Comment by bluerthanever** [comment]
hmm... there does seem to be something logically wrong, now that i look at it.
i think if you enter "n" now, it goes to next page.
