### ISSUE TITLE
feature: auto generate tag name to what is in the tag.txt list

### ISSUE THREAD

**Issue by Lawrence575** [Nandaka/PixivUtil2#1021]
### Prerequisites

* [yes ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [yes ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [yes ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

[feature: auto generate tag title name to what is in the tag.txt list / change folder to auto rename to tag instead of author for "tags"]
feature
### Steps to Reproduce

**Expected behavior:** [auto generate tag name to translate to what is in the tag.txt list for example: 
![cCUaWTO 1](https://user-images.githubusercontent.com/53096166/135899033-6a033538-e90b-46e9-9d0f-f4f20d7829a6.png)
]

**Actual behavior:** [n/a]

### Versions
Latest
You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
not quite understand what you want, but you can use `%searchTags%` in the filename formats so it will add the search tag into filename.

**Comment by Lawrence575** [comment]
Thank you :)
