### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by z0z0r4** [Nandaka/PixivUtil2#1022]
why I can't login? The password and username was true...

Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 464, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x04230AC8>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x04098608>)
Cannot Login!

![image](https://user-images.githubusercontent.com/78744121/136213992-5f95be27-84ca-4249-9662-686a8daba480.png)

**Comment by z0z0r4** [comment]
I try to login on the pixiv,it's ok?
Maybe I should change my password？
![image](https://user-images.githubusercontent.com/78744121/136218581-d14d869b-3daf-4c4b-85e8-7d7c6745f039.png)

**Comment by Nandaka** [comment]
No, you cannot login from the application anymore since Pixiv add the captcha.

check the readme.
```
Q3. I cannot login to Pixiv!
    - Check your password.
    - Try to login to the Pixiv Website.
    - Try to use the config.ini on the [Authentication] section.
    - Check your date and time setting (e.g.: https://www.timeanddate.com/)
    - Disable Daylight Saving Time and try again.
    - Copy your session values from browser:
      1. Open Firefox.
      2. Go to Pixiv website and login, remember to enable [Remember Me]
          check box.
      3. Right click the page and select View Page Info.
      4. Click the Security tab.
      5. Click the View Cookies button.
      6. Look for Cookie named = PHPSESSID.
      7. Copy the content value.
      8. Open config.ini, go to [Authentication] section, paste the value
          to cookie, set keepsignedin = 1.
```

**Comment by z0z0r4** [comment]
Maybe there isn't keepsignedin in config.ini?
I didn't find it....add “keepsignedin = 1”?

**Comment by z0z0r4** [comment]
hmmmm，wittout this, I still login the pixiv succesed!
Thanks your help!
