### ISSUE TITLE
[Feature Request] Add Bookmark Count Option to Option 5, 8

### ISSUE THREAD

**Issue by YukihoAA** [Nandaka/PixivUtil2#1027]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I cannot find limit bookmark count (eg. >200) when i use options 5, 8

**Comment by Nandaka** [comment]
Because it is not available from the images list directly, but need to drill down to the image page level directly.
Let me see what I can do.
