### ISSUE TITLE
There is a problem with downloading the new illustration.

### ISSUE THREAD

**Issue by cocokakao** [Nandaka/PixivUtil2#1028]
### Prerequisites

* [ y] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [y ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

There is a problem with downloading the new illustration.

Other tasks fine and I tried reinstalling them, but the problem was the same.

I haven't checked with another account or other desktop.

The error was printed out like this.

Input: 8
Start Page (default=1):
End Page (default= 0, 0 for no limit): 1
Processing New Illust from bookmark
Page #1
Source URL: https://www.pixiv.net/bookmark_new_illust.php?p=1
Error at process_new_illust_from_bookmark(): (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'"), <traceback object at 0x0449C2C8>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1388, in main
  File "PixivUtil2.py", line 1092, in main_loop
  File "PixivUtil2.py", line 604, in menu_download_new_illust_from_bookmark
  File "PixivBookmarkHandler.pyc", line 123, in process_new_illust_from_bookmark
  File "PixivBookmark.pyc", line 108, in __init__
  File "PixivBookmark.pyc", line 126, in __ParseNewIllustBookmark
AttributeError: 'NoneType' object has no attribute 'findAll'
Unknown Error, please check the log file: (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'"), <traceback object at 0x04B0EDC8>)
press enter to exit.

I wrote it in Google translation. Thank you for reading it.

**Comment by Nandaka** [comment]
which version do you use? can you use other option? Latest version in https://github.com/Nandaka/PixivUtil2/releases/

There should be a file named `Dump for New Illust from bookmark.html` in the application folder, can you upload it here?

I don't have issue in my pc.

**Comment by Nandaka** [comment]
Hmm, looks like the layout is quite different with what I have when accessing from https://www.pixiv.net/bookmark_new_illust.php?p=1

Clicking the See all from Works by users you are following in the front page.
![image](https://user-images.githubusercontent.com/836867/137921029-f9e89d14-d08f-41ce-a627-a2d45b69e1b6.png)

will give me this page
![image](https://user-images.githubusercontent.com/836867/137920014-4d90fc3d-47d9-48ef-ac5a-4892f51af3c7.png)

**Comment by Nandaka** [comment]
pls check latest release

**Comment by zoram999** [comment]
Sorry for not replying afterwards but I wanted to first test the new version with several acocunts. All smooth now, thanks!

Just a small thing there may have been already for a while but I notice only now, is it normal that the software counts pages of 60 pictures, even if the layout has got only 20 for every page? I noticed that now, for example, after 600 pictures it's page 11 (previously it would have been page 31).
