### ISSUE TITLE
Allow local files with different sizes than the server

### ISSUE THREAD

**Issue by chronometric** [Nandaka/PixivUtil2#103]
I realize that most people like to maintain the integrity of downloaded images, and that's fine. But this is something that has been troubling me since the program came out, so I'd ask for at least a quick consideration ;)

I have well over a million images. As I browse through (rather quickly sometimes) in XnViewMP, I mark them with the star and color systems to denote quality and general usefulness. Now, this data can be saved externally for each image, or internally to the XnView database. But saving it to the image it self is instant, cannot be lost, and does not alter the quality of the picture.

#### Therefore, I would dearly love to see what strikes me as a very simple option: _do not overwrite the image if the *filename* already exists in the folder_. 

Which is to say: do not check the database, do not check the file size, or the checksum. If the file exists as named, implement a simple option to assume it is complete, and leave it alone.

The program has a series of options that might appear to cover this: `overwrite`, `alwaysCheckFileSize`, and `backupOldFile.` My surmise is that these were intended for use when the DB was not available, or an artist altered one of their uploads.

But this brings me to the option **`checkUpdatedLimit`**. The suggestion is if that in an existing directory with images, the program downloads and overwrites X number of images that match the database Once satisfied these files match the server's, it will proceed to the next artist/folder. *However, I have noted the exact opposite behavior*. When no database is present (or doesn't include the current artist), the program will proceed as normal through the entire directory, even if the requisite number of consecutively "perfect" images are found.Not only does this overwrite my changes, but wastes server time.

**`alwaysCheckFileSize`** frequently checks all or most file sizes even if turned off, as well.

Even if it makes sense to you and many others to insist on unaltered copies, I would beg for the seeming simple and time-saving option I suggested, whereby the filename is the final word in whether to download or no. If I'm combining these options wrong and what I'm asking for is somehow possible, you can be certainly I would humbly like to learn how this could work.

Thank you so much for this amazing program <3

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/PixivUtil2/releases/tag/v20160127-beta1

ensure Overwrite = False and AlwaysCheckFilesize = False.

**Comment by chronometric** [comment]
Nandaka! Thank you sooo much for taking the time to add this features for me! I can't tell you how much it has streamlined my downloading process, and simplified my entire collection. Am very touched and impressed that you're willing to put work in for just one or two people who have a feature request that no one else may even use....it's truly inspiring that you have this much passion for your program, and I thank you most sincerely!

(sorry I didn't respond to your beta test...I tend to download in bouts every few weeks, and I can't seem to get the github notifications to a useful balance ^^; )
