### ISSUE TITLE
Option 8 from commandline is broken

### ISSUE THREAD

**Issue by GerhardSauer** [Nandaka/PixivUtil2#1034]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
same problem like issue #1031
in this case for option 8

Traceback (most recent call last):
  File "PixivUtil2.py", line 1456, in main
  File "PixivUtil2.py", line 1158, in main_loop
  File "PixivUtil2.py", line 628, in menu_download_new_illust_from_bookmark
TypeError: object of type 'int' has no len()
Unknown Error, please check the log file: (<class 'TypeError'>, TypeError("object of type 'int' has no len()"), <traceback object at 0x0375DFA8>)

### Steps to Reproduce
running via command line, it fails with above error
pixivutil.exe -s 8 --sp 1 --ep 10 -x
pixivutil.exe -s 8 -n 10 -x

### Versions
version 20211020

**Comment by Nandaka** [comment]
should be in the latest release https://github.com/Nandaka/PixivUtil2/releases
