### ISSUE TITLE
Ugoira Error

### ISSUE THREAD

**Issue by curya** [Nandaka/PixivUtil2#1035]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

processing ugoira to animated gif...
Start encoding L:\Pixiv\モモの水道水 (482367)\91008556_ugoira1920x1080 - ゴルドバァン♡.gif
Failed when converting, ffmpeg command used: ffmpeg -y -i "C:/Users/USER~1/AppData/Local/Temp/ugoira2webm3r8bzbky/i.ffconcat" -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" "C:/Users/USER~1/AppData/Local/Temp/ugoira2webm3r8bzbky/temp.gif"
Traceback (most recent call last):
  File "shutil.pyc", line 806, in move
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/Users/USER~1/AppData/Local/Temp/ugoira2webm3r8bzbky/temp.gif' -> 'L:\\Pixiv\\モモの水道水 (482367)\\91008556_ugoira1920x1080 - ゴルドバァン♡.gif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 329, in process_image
  File "PixivDownloadHandler.pyc", line 364, in handle_ugoira
  File "PixivHelper.pyc", line 930, in ugoira2gif
  File "PixivHelper.pyc", line 1012, in ugoira2webm
  File "shutil.pyc", line 826, in move
  File "shutil.pyc", line 435, in copy2
  File "shutil.pyc", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/USER~1/AppData/Local/Temp/ugoira2webm3r8bzbky/temp.gif'
Error at process_image(): 91008556
Exception: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0415B7A8>)
Dumping html to: Error medium page for image 91008556.html
Stuff happened, trying again after 2 second (1)

### Steps to Reproduce

1. Download by member ID: 482367
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
looks like folder access permission or something else deleting the temp folder access? I tried to download the same image `91008556` and it successfully converted.

Check if the temp folder `C:/Users/USER~1/AppData/Local/Temp/ugoira2webm3r8bzbky` exists?

**Comment by HydroHydro** [comment]
It does not exist. Instead I see this folder: ugoira2webmskl9345a

**Comment by Nandaka** [comment]
> ugoira2webmskl9345a

the folder will be automatically created with random name using python function.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L961

any antivirus or something else blocking the access?
![image](https://user-images.githubusercontent.com/836867/139533386-64f5fecf-05bb-4cc4-a73e-efeba218c335.png)

**Comment by curya** [comment]
Tried it with Windows antivirus turned off. Same error.

**Comment by Nandaka** [comment]
even using latest version? https://github.com/Nandaka/PixivUtil2/releases/tag/v20211020

also, can you check it is created in the correct folder: `C:/Users/USER1/AppData/Local/Temp/ugoira2webm3r8bzbky/` or `C:/Users/USER~1/AppData/Local/Temp/ugoira2webm3r8bzbky`

> Log file: [Attach the pixivutil.log file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]
also upload the log file?

**Comment by curya** [comment]
The folder is never created. And yes I'm on the newest version.

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/7446628/pixivutil.log)

**Comment by Nandaka** [comment]
just asking, you have the `ffmpeg.exe` in the same folder as the application, right?
![image](https://user-images.githubusercontent.com/836867/139534718-7be55c58-b09d-4562-a7f5-cd15d997974a.png)

**Comment by curya** [comment]
Yes.

**Comment by Nandaka** [comment]
can you update the ffmpeg? looks like it is because the gif conversion is failed, that's why it cannot find the generated file.

Alternatively, you can try to convert to webp/webm.

**Comment by curya** [comment]
Updated ffmpeg. Same issue.

**Comment by Nandaka** [comment]
can you try to convert to other format?

**Comment by curya** [comment]
I tried all of them one by one by changing the config file. All of them failed.

**Comment by Nandaka** [comment]
updated checking and temp folder generation, if it still failed, 
https://github.com/Nandaka/PixivUtil2/releases/tag/v20211030

also this is my ffmpeg.exe https://www.mediafire.com/file/jn5nskve330diw3/ffmpeg-20201220.7z/file
