### ISSUE TITLE
Indicate the default value of the options y/n, a/i/m

### ISSUE THREAD

**Issue by RubenGarcia** [Nandaka/PixivUtil2#1037]
### Prerequisites

* [Y ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [Y ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ Y] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

In 
the various variations of 
    input('Include Pixiv Sketch [y/n]? ').rstrip("\r") or 'n'
do not indicate which is the default option to the user.

I'd like to change all these to either
```
    input('Include Pixiv Sketch [y/N]? ').rstrip("\r") or 'n'
```
or
```
   input('Include Pixiv Sketch [y/n, default n]? ').rstrip("\r") or 'n'
```
Which option do you prefer? I'll create a merge request once this is decided.
### Steps to Reproduce

1. Press 1
2. Answer the questions from the program.

**Expected behavior:** [What you expected to happen]
Default behaviour shown to the user.
**Actual behavior:** [What actually happened]
Default behaviour hidden from the user
**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]
N/A
### Versions
v202111031-beta3

**Comment by Nandaka** [comment]
`input('Include Pixiv Sketch [y/n, default is no]? ').rstrip("\r") or 'n'` is preferable.

**Comment by RubenGarcia** [comment]
https://github.com/Nandaka/PixivUtil2/pull/1039

**Comment by Nandaka** [comment]
merged
