### ISSUE TITLE
Error at updateMemberName()

### ISSUE THREAD

**Issue by Link5261** [Nandaka/PixivUtil2#1038]
### Prerequisites

* [√] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [√] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [√] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Trying to download by member ID, I get:
`Error at updateMemberName(): (<class 'sqlite3.OperationalError'>, OperationalError('attempt to write a readonly database'), <traceback object at 0x02FDDC68>)`

### Steps to Reproduce

1. Load PixivUtil2.exe
2. Select Option 1 (memberID download) and enter member ID on prompt (44790602)
3. Continue with settings to download all images + Sketch and commit run cycle.

**Expected behavior:** I expect, as usual, all of said member's content to download.

**Actual behavior:** It successfully downloaded the first image, but then threw this error after, when updating to check the second image.

**Log file:** [pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/7458120/pixivutil.log)

### Versions
20211030

**Comment by Nandaka** [comment]
no write access to the `db.sqlite`, check if it has write permission?

**Comment by Link5261** [comment]
All Group/User entries have "Full control" permissions for `db.sqlite`.
![image](https://user-images.githubusercontent.com/43685379/139793285-acf97912-f049-4146-89e6-7b9b284394df.png)
I am running this program as the sole user, and running in admin mode makes no difference.

**Comment by Link5261** [comment]
Update: Member entered makes no difference. I have tested with another memberID (1197677) and get the same result; successful first download, same error on 2nd.

**Comment by MarqFJA87** [comment]
I suffer the same problem as well ever since I updated to the beta (which weirdly was **required** whenever I tried to start the program under the latest stable version), so it's not specific to Link5261.

**Comment by Nandaka** [comment]
> 'attempt to write a readonly database'

well, there is no changes on db access at all from the latest stable to beta3
https://github.com/Nandaka/PixivUtil2/compare/v20211030...v20211031-beta3

Most likely there is another application also accessing the db file and locking it (dropbox? antivirus? backup?)

**Comment by Link5261** [comment]
Even if I disable my antivirus (Avast) and spyware detection (Spybot S&D), it gives the same behavior. What's most puzzling to me is that this behavior on version 20210421 is what prompted me to update, but for many months prior to this behavior showing up, it was working perfectly fine for memberID downloads on said older version.

**Comment by Nandaka** [comment]
well, no change on db access code wise https://github.com/Nandaka/PixivUtil2/compare/v20210421...v20211031-beta3

maybe it is because the python update if you running from executable version because Python drop support for Windows 7.

You can try to run it from source code?

**Comment by Link5261** [comment]
I run the executable version via Python 3.8.2rc2, on a Windows 7 PC. Prior to this error showing up, I was running the older version mentioned before on a different version of Python, but it worked fully fine with no changes made (to my knowledge) before it suddenly "broke". Gets a same `readonly database` error when trying to download via tags as well.

**Comment by MarqFJA87** [comment]
For my part, I've been running the executable on Windows 10 for several months without incident, and only when I performed the mandatory update to the newest beta version did the error manifest.

**Comment by Nandaka** [comment]
works fine in my pc using executable from beta3 (fresh install).
![image](https://user-images.githubusercontent.com/836867/140011403-271745ef-1515-400a-820b-d4b8a135b33f.png)

Only windows defender is running Win10 Home 20H2

**Comment by MarqFJA87** [comment]
Okay, I tried downloading a different artist today, and I think I isolated where the problem happens on my end: everything was okay up until the program tried to download an Ugoira animation. It downloads the individual frames just fine, but when it tries to combine them into a gif, it gives this error message (last string of characters is variable):

`Exception: (<class 'AttributeError'>, AttributeError("module 'PixivException' has no attribute 'MISSING_CONFIG'"), <traceback object at 0x013B0348>)`

I tried it with both the most up to date ffmpeg and the one recommended earlier in this thread, to no avail.

**Comment by Nandaka** [comment]
upload the log file?

**Comment by MarqFJA87** [comment]
... I don't know which file that is.

**Comment by Link5261** [comment]
New version with running from source code works. Thank you, @Nandaka. 👍🏻
