### ISSUE TITLE
Error with saving image using %artist%

### ISSUE THREAD

**Issue by TimeCompass** [Nandaka/PixivUtil2#104]
when download with member ID 
http://www.pixiv.net/member.php?id=1039353
artist name should be "Mika Pikazo|委託中"
either %artist% or %original_artist% saves image with "igix" (maybe the registered account name)
other artists shows the same problem

it seems only appear with Linux build (I tried Arch and Debian),Windows didn't appear this problem.

**Comment by Nandaka** [comment]
I don't have linux/unix to test.

igix is the member token (from the avatar url. You can also check from http://www.pixiv.net/stacc/igix).

Looks like the parser failed to get the element containing the member name (see https://github.com/Nandaka/PixivUtil2/blob/master/PixivModel.py#L73)
![image](https://cloud.githubusercontent.com/assets/836867/12807582/f571163a-cb4a-11e5-977f-1ebb56423c52.png)

and it will fallback to the member token.

by right, it should not use different class. Can you confirm?

**Comment by TimeCompass** [comment]
[root@Maidzuru PixivUtil2]# python2 PixivUtil2.py 
PixivDownloader2 version 20160127-beta1
https://nandaka.wordpress.com/tag/pixiv-downloader/
Reading /root/PixivUtil2/config.ini ...
done.
Creating database... done.
Using Username: timecompass
Trying to log with saved cookie 
Login successfull. 
PixivDownloader2 version 20160127-beta1


Input: 1
Member ids: 1039353
Start Page (default=1): 
End Page (default=0, 0 for no limit): 
Processing Member Id: 1039353 
Reading /root/PixivUtil2/config.ini ...
done.
Page  1
Member Url: http://www.pixiv.net/member_illust.php?id=1039353&p=1 
Member Name  : igix 
Member Avatar: http://i1.pixiv.net/img35/profile/igix/10176306.png
Member Token : igix
Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?id=1039353&p=1 
	File exist! (Identical Size) 
#1
Processing Image Id: 54969473
Title: 叢雲改二 
Tags : 艦隊これくしょん, 艦これ, 落書き, 叢雲, まったく、駆逐艦は最高だぜ!!, 黒インナーという武器/黒スト/パンスト越しのパンツ, 叢雲かわいい, パンツ!パンツです!, 艦ぱい, 艦これ5000users入り 
Date : 2016-01-29 19:53:00 
Mode : bigNew
Image URL : http://i2.pixiv.net/img-original/img/2016/01/29/19/53/10/54969473_p0.png
Filename  : /root/PixivUtil2/[1039353] [igix]/[2016年1月29日] [54969473] [叢雲改二] [1039353] [igix].png 
Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=54969473 
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=54969473                                            1421833 of   1421833 Bytes  Completed in 1.492728s (930.18 KiB/s)
 Image verified. 



#2
Processing Image Id: 54652001
^CKeyboard Interrupt detected, continue to next image (Y/N)

**Comment by TimeCompass** [comment]
I "git clone" a new copy and tried again today, maybe I should also upload my "config.ini" ?

**Comment by Nandaka** [comment]
what is your python and library version?

here is mine:
```
Python 2.7.10
BeautifulSoup (3.2.1)
beautifulsoup4 (4.3.2)
mechanize (0.2.5)
Pillow (3.0.0)
SocksiPy-branch (1.2)
```

**Comment by TimeCompass** [comment]
Python 2.7.11
BeautifulSoup (3.2.1)
beautifulsoup4 not installed
mechanize (0.2.5)
Pillow (3.1.0)
SocksiPy-branch (1.1)

maybe beautifulsoup4 ‘s problem？ I’ll try install it now and commit the result later.

**Comment by Nandaka** [comment]
Also, what is your useragent?

I'm using ```Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36```

**Comment by TimeCompass** [comment]
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36

I have never changed this part since first running.

**Comment by Nandaka** [comment]
Crap, it is my fault. got indentation error in one of the py model. Will fix.
