### ISSUE TITLE
WrtieXMP Metadata Broken

### ISSUE THREAD

**Issue by Baa14453** [Nandaka/PixivUtil2#1040]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

The WriteXMP feature that downloads metadata and adds it to an .XMP sidecar file is not working.

### Steps to Reproduce

1. Enable WriteXMP in the config file.
2. Download an image

**Expected behavior:** [What you expected to happen]
Metadata is saved to the XMP sidecar file.

**Actual behavior:** [What actually happened]
Python throws the error:
```
Traceback (most recent call last):
  File "/PixivUtil2/PixivImageHandler.py", line 287, in process_image
    image.WriteXMP(info_filename + ".xmp")
  File "/PixivUtil2/PixivImage.py", line 531, in WriteXMP
    info.close()
AttributeError: 'ImageMetadata' object has no attribute 'close'
Error at process_image(): 93896333 
Exception: (<class 'AttributeError'>, AttributeError("'ImageMetadata' object has no attribute 'close'"), <traceback object at 0x7f2750b11c80>) 
Dumping html to: Error medium page for image 93896333.html 
Error at process_new_illust_from_bookmark(): (<class 'AttributeError'>, AttributeError("'ImageMetadata' object has no attribute 'close'"), <traceback object at 0x7f2750af3600>) 
Traceback (most recent call last):
  File "/PixivUtil2/PixivUtil2.py", line 1462, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args, options)
  File "/PixivUtil2/PixivUtil2.py", line 1158, in main_loop
    menu_download_new_illust_from_bookmark(op_is_valid, args, options)
  File "/PixivUtil2/PixivUtil2.py", line 631, in menu_download_new_illust_from_bookmark
    PixivBookmarkHandler.process_new_illust_from_bookmark(sys.modules[__name__],
  File "/PixivUtil2/PixivBookmarkHandler.py", line 140, in process_new_illust_from_bookmark
    result = PixivImageHandler.process_image(caller,
  File "/PixivUtil2/PixivImageHandler.py", line 287, in process_image
    image.WriteXMP(info_filename + ".xmp")
  File "/PixivUtil2/PixivImage.py", line 531, in WriteXMP
    info.close()
AttributeError: 'ImageMetadata' object has no attribute 'close'
Unknown Error, please check the log file: (<class 'AttributeError'>, AttributeError("'ImageMetadata' object has no attribute 'close'"), <traceback object at 0x7f2750aebb40>)
```
### Versions
20211031-beta3

**Comment by Baa14453** [comment]
I'll look into this later just noting it down

**Comment by Nandaka** [comment]
related to #1004 and 73a0a82

I rewrite the pyexiv2 part to support pyexiv2-2.7.0, else it won't work at all in windows

**Comment by Baa14453** [comment]
pyexiv2-2.7.0 works on Linux and Windows, the one I used is py3exiv2 which only works on Linux.

I reckon just remove support for py3exiv2? It should be fine, pyexiv2 looks better anyway

**Comment by Nandaka** [comment]
ok, then only need to change the `requirements.txt`, I think?
