### ISSUE TITLE
[Question] Is there a way to re-encode webm?

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#1042]
The new default encoding param for webm is a lot smaller, around 20x in some cases. I want to be able to delete my old webm's and re-encode it. Just deleting it and redownloading doesn't help if it's been deleted. I have the zip and ugoira files but I don't have the time/knowledge to code something quick. If someone could help, that would be nice.

**Comment by Nandaka** [comment]
you can delete the webm file and then do the re-download again. The application will check if the .ugoira still exists, then it will skip downloading and do the conversion again.

else you can write your own script and call this function
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L991-L1093

**Comment by PatrickL546** [comment]
It doesn't convert if the original post is deleted. If you could provide a basic script it would be nice cause I have no idea how to use python but I might figure it out.
