### ISSUE TITLE
[Feature Request] Raise bookmark paging limit to 100

### ISSUE THREAD

**Issue by somebody1234** [Nandaka/PixivUtil2#1046]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Set bookmark `limit=100` when choosing option 5. Line to change is here:
https://github.com/Nandaka/PixivUtil2/blob/e0be95345ee39b13a317cf2c9e3b2927ce8c8fbe/PixivBookmarkHandler.py#L288

### Steps to Reproduce

1. Select option 5

**Expected behavior:** page limit = 100

**Actual behavior:** page limit = 48

**Log file:** n/a

### Versions
20211104

**Comment by somebody1234** [comment]
supposedly `--bcl` should do something but it seems like it doesn't. also if this shouldn't be default then at least add a setting in config.ini or something

**Comment by Nandaka** [comment]
any reason why? the default given is following what the pixiv website uses, especially limit not supposed to be changeable from the website.
![image](https://user-images.githubusercontent.com/836867/140783041-9898f87b-633c-4dfa-80f9-517e8e9649e5.png)

I don't know if changing the default to different number will cause the account to be banned. 
Also the maximum post you can bookmark doesn't change at all.

**Comment by somebody1234** [comment]
1. for artist bookmarks i believe page size is 24. so pixivutil's already been using the wrong limit for years...
2. at twice the size, it takes half as long to get all bookmarks.

**Comment by somebody1234** [comment]
:pensive: it would have been great if there was at least a config.ini option...
