### ISSUE TITLE
Fanbox can't download

### ISSUE THREAD

**Issue by ghost** [Nandaka/PixivUtil2#1049]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I can download from “8”， but I can't download fanbox"f1", after paste the "code", it shows me error. I'm using proxy, both http and sock5 are tested, not working.

### Steps to Reproduce

1.run program, type"f1", enter ... ,
then shows me"1. This will open a new browser to login to Pixiv site to get the code.
1b. In case the browser will not open, or you are using an headless server, use this link: blablabla
2. Open dev console (F12) and switch to network tab.
3. Enable persistent logging ("Preserve log").
4. Type into the filter field: 'callback?'.
5. Proceed with Pixiv login.
6. After logging in you should see a blank page and request that looks like this:
   'https://app-api.pixiv.net/web/v1/users/auth/pixiv/callback?state=...&code=...'
7. Copy value of the code param into the prompt and hit the Enter key."

I followed steps, after I paste the code value, it show error and exit the program.

###log file.
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/7505941/pixivutil.log)

Thank you.

**Comment by Nandaka** [comment]
running from source code or exe? win7 or win10? are you using proxy?

**Comment by Nandaka** [comment]
update your proxy config, you need to add `http://`, check the readme
![image](https://user-images.githubusercontent.com/836867/141108612-9c8c5897-81dc-4ce1-bb7d-4d2ed8ca5afc.png)

**Comment by fortxysifjvc** [comment]
> running from source code or exe? win7 or win10? are you using proxy?

Running windows 10 21h1 x64 with exe, and I'm using proxy, tried http and socks5, both are the same, download from bookmark works fine, but fanbox after paster the request code shows error.

Config confirmed, it was "http://" I tired proxy begining with "socks5://" or "http://".

I tired with 20211104 first, not working with fanbox, but 20211020 didn't show error after I paste the code and it works.

**Comment by bluerthanever** [comment]
I think.... it's because in `PixivOAuthBrowser.py`, no proxy options are used.

**Comment by Nandaka** [comment]
the logging use wrong format for the proxy, need to append `http://` or `https://` else it wont work.

`ValueError: check_hostname requires server_hostname`  ==> https://stackoverflow.com/a/67000726

**Comment by bluerthanever** [comment]
strangely the main process got login status just fine...
but also i think in `PixivOAuthBrowser.py`, none of requests are made with proxies...
i think i have run into similar problems as well, after my config file and database had been erased somehow and i had to get a new refresh token... i just changed the `py` and added a proxy parameter to all `post` and `get` methods.
but i didn't keep the log file, so not sure if it's the same problem.

**Comment by Nandaka** [comment]
maybe because it use `mechanize.Browser` https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L37 and oauth uses `requests` https://github.com/Nandaka/PixivUtil2/blob/master/PixivOAuthBrowser.py#L10

**Comment by bluerthanever** [comment]
but since no proxy is used in `PixivOAuthBrowser.py`, i think it's not because of missing of "http" in config?
unless the user had done something else... i suppose. like setting a global proxy for python, or changing the scripts.

**Comment by fortxysifjvc** [comment]
> I think.... it's because in `PixivOAuthBrowser.py`, no proxy options are used.

I don't know, I tried everything, but option "8" works fine.

**Comment by fortxysifjvc** [comment]
> but since no proxy is used in `PixivOAuthBrowser.py`, i think it's not because of missing of "http" in config? unless the user had done something else... i suppose. like setting a global proxy for python, or changing the scripts.

I didn't change the scripts and I don't have a python installed on my computer.

**Comment by Nandaka** [comment]
@bluerthanever  ah ya, need to add `proxies` parameter from the `config.proxy` in the request call below
https://github.com/Nandaka/PixivUtil2/blob/master/PixivOAuthBrowser.py#L82
https://github.com/Nandaka/PixivUtil2/blob/master/PixivOAuthBrowser.py#L102

proxy from config
https://github.com/Nandaka/PixivUtil2/blob/master/PixivConfig.py#L214

reference
https://stackoverflow.com/a/30694179

**Comment by bluerthanever** [comment]
Pulled a new request to use proxies in `PixivOAuthBrowser`, but not sure how the issue in this thread happened still.

**Comment by fortxysifjvc** [comment]
Thank you so much
