### ISSUE TITLE
When downloading bookmarks, possible option to download from a specific tag

### ISSUE THREAD

**Issue by aensaro** [Nandaka/PixivUtil2#105]
I have a small request, if possible:

When using **6. Download from online user bookmark** please offer, before selecting which pages, an option of choosing which particular tag (if any) one wants to download from. It can be disregarded by leaving it blank and thus the program would run as usual.
The URL would change from `pixiv.net/bookmark.php?p=` to `pixiv.net/bookmark.php?tag=t&p=` where _t_ would be the previously typed tag name.

Thank you for PixivUtil2!

**Comment by Nandaka** [comment]
updated in https://github.com/Nandaka/PixivUtil2/releases/tag/v20160211
