### ISSUE TITLE
What does 'Bookmark Count' do?

### ISSUE THREAD

**Issue by Baa14453** [Nandaka/PixivUtil2#1051]
When I choose option 8, it asks me to input the start and End Page but recently also asks me for 'Bookmark Count'.

I'm not sure what this is asking for or what it does
![image](https://user-images.githubusercontent.com/9057997/141483819-53fd7b58-0c1c-40af-a378-ed6eac22f223.png)

**Comment by Nandaka** [comment]
see #1027, basically it is to skip any post below the bookmark count.

**Comment by Baa14453** [comment]
ahh ok, thanks
