### ISSUE TITLE
[Question] Placement of info text file for multi-image folder

### ISSUE THREAD

**Issue by MarqFJA87** [Nandaka/PixivUtil2#1053]
Multi-image posts are always put into folders, but their info text files are placed in the artist root folder rather than the post's folder. Is there a way to make it so the text file is put into the latter?

**Comment by Baa14453** [comment]
There is a config option for defining where the info and image files are saved, if you have these the same then they should save in the same place, these are mine:
```
filenameFormat     = %R-18%/Pixiv/%artist% (%member_id%)/%urlFilename% - %title%
filenameInfoFormat = %R-18%/Pixiv/%artist% (%member_id%)/%urlFilename% - %title%
```

**Comment by MarqFJA87** [comment]
They are, although you did draw my attention to the filenameMangaInfoFormat option right below them, which was **not** set to the same destination as the filenameMangaFormat option. Fixing that will cut down on the workload to some variable extent, but doesn't completely solve the problem.

**Comment by MarqFJA87** [comment]
I think I have solved it. I tried the following, and so far it worked the way I hoped it would.

```
filenameMangaFormat = %artist% (%member_id%)\%image_id% - %title%\%urlFilename%
filenameMangaInfoFormat = %artist% (%member_id%)\%image_id% - %title%\%image_id%_t
```
