### ISSUE TITLE
Sketch download not working

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#1054]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Sketch download not working

### Steps to Reproduce

1. Run PixivUtil2.py
2. Use s1 option
3. Type user ID. ex.30763940 (has sketch account)

**Expected behavior:** Downloads

**Actual behavior:** HTTPError 404: 'Not Found'

**Log file:** [pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/7576065/pixivutil.log)
### Versions
Using https://github.com/Nandaka/PixivUtil2/commit/42e675f065af2addd74968d0bac59cd09fef9a7e

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by PatrickL546** [comment]
Also, I had to manually 'pip install lxml'. Can that be added to the requirements?

**Comment by SnakeEve** [comment]
After receiving an email about this issue, I pulled the new branch and run PixivUtil again, i got a similar error but only to several artists. After my download is finished i will check my latest download log and find the whole error message, also i will check to the specific artist which I used for the issue #1019.
