### ISSUE TITLE
Python Delayed write failed

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#1057]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

XMP and JSON; Data has been lost. Never had this problem before because this is the first time I've saved JSON and XMP data.
I have multiple errors of only XMP and JSON files being lost. This could be a problem with having multiple instances making my HDD have a massive response time in between. But if it's a HDD drive problem shouldn't the image and ugoira have problems as well?

### Steps to Reproduce

1. Have multiple instances of pixivutil2 running. Haven't tested it with just 1 instance running.
2. Download by user-id
3. wait..

**Expected behavior:** Downloads without problem

**Actual behavior:**

![zzzzz](https://user-images.githubusercontent.com/75874561/142974132-0dd92ba8-1d2d-4bb7-b772-7d6b7adf4061.png)
![zzzz](https://user-images.githubusercontent.com/75874561/142974137-1428333c-399d-446a-ac54-4c8bcd1d96bc.png)

**Log file:** Checked the 10mb log file with the error that happened and didn't show anything different than normal.

### Versions
Latest 'Some optimizations (#1052)'
https://github.com/Nandaka/PixivUtil2/commit/d09bf5f25a844f0e5e67fa266d0f22e7196d33f1

**Comment by Nandaka** [comment]
looks like your harddisk failing? better backup and replace your drive
![image](https://user-images.githubusercontent.com/836867/142999461-7891ee1d-5df6-4439-8804-d6f3d29789ef.png)

**Comment by PatrickL546** [comment]
Maybe a bit hot cause it's an external drive but everything looks fine I think. Maybe windows just buggin out on me. Had a slow sign-in screen when that happened but I fixed it. I'll try again to see what happens

![image](https://user-images.githubusercontent.com/75874561/143008918-2129df8b-3c90-4a53-a754-13f212d63b3f.png)

**Comment by Nandaka** [comment]
the delayed write is managed by the operating system itself. Usually I will disable this for external drives.
![image](https://user-images.githubusercontent.com/836867/143024812-1f8953f2-2885-4323-a8f3-2343cb84c328.png)

**Comment by PatrickL546** [comment]
My best guess is it's being timed out

![1](https://user-images.githubusercontent.com/75874561/143090512-e86e644b-963a-468a-aa8f-3c5cec1ebf72.png)
![2](https://user-images.githubusercontent.com/75874561/143090514-41f22cb3-c73a-46e4-9354-2c98aac905e9.png)
![3](https://user-images.githubusercontent.com/75874561/143090520-1cd22cc3-55d3-4d01-a82b-7eccaa4ba120.png)


Idk if it's relevant but

![4](https://user-images.githubusercontent.com/75874561/143090526-ac682977-8ab7-4a04-b9b9-d791f38057ac.png)
I have a 4gb page file and my windows after I closed python is using more ram and I can't find what's using it.
![5](https://user-images.githubusercontent.com/75874561/143090531-55e92612-11d1-48c7-95a1-3ee085ada886.png)

I'll try it out


> the delayed write is managed by the operating system itself. Usually I will disable this for external drives. ![image](https://user-images.githubusercontent.com/836867/143024812-1f8953f2-2885-4323-a8f3-2343cb84c328.png)

**Comment by PatrickL546** [comment]
Looks like this fixed it. It can't keep up with the I/O without caching and windows timing it out.

![image](https://user-images.githubusercontent.com/75874561/143177981-8beb36df-5215-410f-b87c-4f7b18e5039a.png)
