### ISSUE TITLE
<urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions> 

### ISSUE THREAD

**Issue by oluapris** [Nandaka/PixivUtil2#1058]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Error shows up when I open the program, counts 
`1 1

2 1

3 1

4 1`
 and repeats twice before crashing.
### Steps to Reproduce

1. Open piivutil2.exe

**Expected behavior:** 
Programs logs in after I open it.

**Actual behavior:** 
Programs shows an error and crashes.

**Log file:**
 [pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/7606412/pixivutil.log)

### Versions
v20211104

**Comment by Nandaka** [comment]
Looks like blocked by firewall.
