### ISSUE TITLE
[Feature Request] Toggle R-18 options in Batch Processing

### ISSUE THREAD

**Issue by YukihoAA** [Nandaka/PixivUtil2#1059]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Is it possible to implement toggle function of r-18 feature on batch mode?

R-18 mode is  forced to R-18 Only, but what I want is non R-18 Only with specific tags. (other tags works norm: non R-18 + R-18)

**Comment by Nandaka** [comment]
no direct feature for that, but you can use `"useBlacklistTags" : true ` to the batch job option json file and add R-18 in the `blacklist_tags.txt`
![image](https://user-images.githubusercontent.com/836867/145811047-99ce0f5c-3bfc-4990-93ef-00a35dc1e703.png)
