### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by danthonywalker** [Nandaka/PixivUtil2#106]
I got this error while processing one of my final tags.

Looping... for http://www.pixiv.net/search.php?s_mode=s_tag_full&word=%E6%9D%B1%E6%96%B9project&p=425&ecd=2015-02-15&order=date_d
Error at process_tags(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x039ADE68>)
Dumping html to: Error page for search tags %E6%9D%B1%E6%96%B9project.html
Error at process_tags_list(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has
no attribute 'findAll'",), <traceback object at 0x039ADD50>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1823, in main
  File "PixivUtil2.py", line 1623, in main_loop
  File "PixivUtil2.py", line 1481, in menu_download_from_tags_list
  File "PixivUtil2.py", line 884, in process_tags_list
  File "PixivUtil2.py", line 746, in process_tags
  File "PixivModel.pyc", line 808, in parseTags
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.

**Comment by Nandaka** [comment]
Is there any html page generated for the error? It should be in the same folder with the program.

Also, can you try to retry again straight to the page 425?

**Comment by danthonywalker** [comment]
I can't skip to that particular page since I'm not aware of a way to select a specific date.
https://drive.google.com/open?id=0B9sysGP4FUlyR3VfelUyOXhrUzQ

**Comment by Nandaka** [comment]
try:

```
Input: 3
Tags: 東方project
Bookmark Count:
Use Partial Match[y/n]: n
Oldest first[y/n]: n
Start Page (default=1): 425
End Page (default=0, 0 for no limit):
Start Date [YYYY-MM-DD]:
End Date [YYYY-MM-DD]: 2015-02-15
```

It will generate the url to page 425 directly

**Comment by danthonywalker** [comment]
Nothing happened

**Comment by Nandaka** [comment]
then most likely got incomplete reply/empty response.
