### ISSUE TITLE
Skipping post: 1790068 due to restricted post.

### ISSUE THREAD

**Issue by minecraftkiller006** [Nandaka/PixivUtil2#1061]
This is my first time using this -- does it only download posts with covers? Or is this able to download "through" the paywall. If it is supposed to be able to download through the paywall, is this post restricted for another reason?
Edit: I set downloadCoverWhenRestricted to be true, only posts that have covers have been downloading..

**Comment by Nandaka** [comment]
no, you need to be subscribed to the fanbox artist to get the whole post.
