### ISSUE TITLE
[Suggestion] Fetch PHPSESSID automatically with login and password

### ISSUE THREAD

**Issue by Petersuib** [Nandaka/PixivUtil2#1062]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Currently, to use the app the user has to go and get their PHPSESSID in their browser, but it is possible to fetch it automatically using tools like selenium and their login/password (that are useless since Pixiv's new authentication method if I am not mistaken). Has this ever been considered ?

### Steps
1- Put login and password in config.ini
2- The client fetches the PHPSESSID and writes it to config.ini
3- The client logs in using the PHPSESSID
4- Whenever the PHPSESSID is invalid, we go through step 2

**Comment by Nandaka** [comment]
Sure, it if can be integrated and compiled with py2exe. You can send a pull requests.
It is nice to have, but not a must since the cookie is last for quite a long time (at least I haven't update it since I change my password)

**Comment by Petersuib** [comment]
From the top of your head, do you know which file/methods I should look to modify ?

**Comment by Petersuib** [comment]
> From the top of your head, do you know which file/methods I should look to modify ?

Nevermind, I think I found it (loginUsingCookie in PixivBrowserFactory)

**Comment by Petersuib** [comment]
I forgot that the client must have the webdriver (a .exe file) corresponding to the version of the browser they have on their pc, how should it be handled ?

**Comment by Nandaka** [comment]
I don't think I can bundle the webdriver with the compiled release, also there is potential security risk for the normal user, as normally selenium is used for automated testing, not for production use.

I think it is better for you to create a separate script that will update the cookie value to the `config.ini` and then call the main script from your script (assuming you are running from source code directly).
