### ISSUE TITLE
Cannot download all novels from a Pixiv member with member id

### ISSUE THREAD

**Issue by gotoAndDie** [Nandaka/PixivUtil2#1067]
### Prerequisites

* [☑] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [☑] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [☑] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Currently, only the options 14 and 15 can download novels, and neither option is able to download all novels from a single Pixiv member. #706 implements downloading novels, but there is no handling for novels when downloading all images for a member id.

The API endpoint at https://www.pixiv.net/ajax/user/%member_id%/profile/all includes a list of Novel Ids by a member at body["novels"].

### Steps to Reproduce

1. Attempt to download novel from member with option 1 or option 5

**Expected behavior:** Novels downloaded like images, 

**Actual behavior:** No novels are downloaded.

### Versions

Latest committ

**Comment by Nandaka** [comment]
Duplicate with #1083
