### ISSUE TITLE
Add ranking.php?

### ISSUE THREAD

**Issue by z0z0r4** [Nandaka/PixivUtil2#1068]
Maybe we can add [Ranking.php](https://www.pixiv.net/ranking.php) 
It's useful. And mode daily monthly weekly
They don't need login except r18 mode
Thanks!

**Comment by Nandaka** [comment]
looks like possible using their api 
`https://www.pixiv.net/ranking.php?p=1&format=json`
`https://www.pixiv.net/ranking.php?mode=daily&date=20220104&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=daily_r18&p=1&format=json`
`https://www.pixiv.net/ranking.php?mode=daily&date=20220104&p=2&format=json`

Filtering need to be done on application, not sure if needed as the UI doesn't expose this yet.
![image](https://user-images.githubusercontent.com/836867/148484787-e5b63bd9-7671-4311-8353-4d82c5c88fd5.png)
![image](https://user-images.githubusercontent.com/836867/148484953-9e36b1bf-d816-4b87-97bf-cc899e46eacc.png)

**Comment by Nandaka** [comment]
looks like normal daily ranking is limited to 500 post (5 pages) and R-18 daily ranking is limited to 100 posts (2 pages).

**Comment by Nandaka** [comment]
`https://www.pixiv.net/ranking.php?mode=weekly&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=monthly&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=rookie&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=original&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=male&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=female&p=2&format=json`

`https://www.pixiv.net/ranking.php?mode=weekly_r18&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=male_r18&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=female_r18&p=2&format=json`

**Comment by Nandaka** [comment]
additional information:
![image](https://user-images.githubusercontent.com/836867/148485680-01869665-06b2-4204-ad9f-2bb8365ba8de.png)

**Comment by Nandaka** [comment]
`https://www.pixiv.net/ranking.php?mode=daily&content=illust&date=20220105&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=daily&content=ugoira&date=20220105&p=2&format=json`
`https://www.pixiv.net/ranking.php?mode=daily&content=manga&date=20220105&p=2&format=json`
