### ISSUE TITLE
Add option to ignore DB duplicate download history

### ISSUE THREAD

**Issue by chronometric** [Nandaka/PixivUtil2#107]
This is sort of a flip-side or extension of feature #103 which you implemented in the latest build. While the program will now ignore file size differences, thus allowing the files on the hard drive to act as a "permanent database" of downloaded files even if altered...

**The database still keeps track of the files downloaded, and prevents one from downloading more than one copy of a given picture to different locations**. This can be checked by downloading a very small member gallery, changing the root download folder, and downloading again. The program will instantly skip the images, saying "Already Downloaded."

This is very useful in an instance where one uses the DB to manage a single download library, as it is a very fast function. **But what if I want to download all the images with a certain tag, or all the bookmarks of a certain artist? The more images I have downloaded "normally," the more holes will appear in these other download instances.**

Now, this can be bypassed by deleting the database, using different program instances, etc. But I think it would dovetail nicely with feature #103 if there was an option to temporarily suspend the DB oversight of duplicate downloads...either as a menu item (more temporary) or a config.ini option (for those who are doing larger projects like tag or bookmark libraries).

**Comment by NHOrus** [comment]
I do it with a script that swaps main db with temporary dbs for centrain tag(s) or setting(s), together with configuration file.

**Comment by chronometric** [comment]
@NHOrus That's interesting, what kind of script? I have a number of program instances for regular artist downloading, tags, bookmarks, etc, and a clean instance with no DB at all. 

Maintaining a single program directory with a script to alter config files seems fairly complicated, given that the DB of the "temporary" program will be disposed of after this project, so I'm not clear what advantage this has over creating a new instance and just copying over the config.ini? ^^

**Comment by NHOrus** [comment]
Note: I do things on linux, so bash script. But batch script on windows is also quite trivial.

It begins with check for updates to PixivUtil and download of new version if available.
DB and config are two files, so script does swap of new, needed files, lets PixivUtil to download images by tag, swaps to different set of settings, lets PixivUtil to download into different directory by artist ID, backs up of old config/DB/downloaded list for both settings and exits. Completely unattended.

It could be set up to, say, download all new images by selected artists, then download all new images in specified tag, then dispose or defer for later management DB of tagged images while preserving knowledge of everything you downloaded earlier.

Again, DB and config are two files, shell scripts are perfectly fine for moving files around and starting PIxivUtil unattended.

**Comment by Hamuko** [comment]
>DB and config are two files, so script does swap of new, needed files

If you are talking about using two different config files by changing which of them is at a certain filepath at a certain time, you could also use `-c [PATH]` or `--config [PATH]` command-line option to specify a custom config file location. There's however not such an option to specify database path.

**Comment by Nandaka** [comment]
add new option in config.ini in Settings section = dbPath

combine with -c [PATH] to specify different config.ini.
