### ISSUE TITLE
Manga (multi-page) works should be able to store which pages I want to keep

### ISSUE THREAD

**Issue by microwaver24** [Nandaka/PixivUtil2#1070]
### Prerequisites

* [ X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Feature request.

My normal usage is to download images and then delete the ones i don't like. Sometimes that means I have deleted part of the images (pages?) in a manga (multi-image) work. This information is not stored in the database at all, so if I ever lose my download folder, I wouldn't be able to redownload just the saved images. The redownload would also include deleted images.

Request that there would be a way for PixivUtil2 to parse the downloaded images and update the database with which ones are still there. Then future downloads using that database file would not need to download the ignored images. Added bonus idea: if a work or artist has no remaining images, it could automatically remove that from the database entirely. If it is a favorite list, then the work could be unfavorited.

The big gain is that I could back up my database file and recreate all the image data later without having to parse every image again.

**Comment by Nandaka** [comment]
If the image is downloaded, it should be stored in the db.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L344
https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L348
https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L351


assuming the image is recorded in the db, then it should be skipped if you didn't enable overwrite or alwaysCheckFileSize in config.ini
https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L67

No feature to ignore specific image id planned.
