### ISSUE TITLE
sometimes it only download the first image from a user, why

### ISSUE THREAD

**Issue by bloodypala** [Nandaka/PixivUtil2#1077]
### Prerequisites

* [*] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [*] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [*] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

v20211104

**Comment by cglmrfreeman** [comment]
You didn't seem to fill out the information in the first post, so we can't reproduce the issue. Option 5 downloads from your bookmarked artist. I just tried it (for the first time) and never ran into any issue.

If you frequently use this option, chances are you are adding the older images to your database. As such, only one "new" image will be downloaded, and the rest will be skipped as you already have those images saved according to your database.

**Please include the pixivutil.log file to allow us to verify the behavior you are describing**.
