### ISSUE TITLE
Download artist profile description and their twitter url to a text file

### ISSUE THREAD

**Issue by glassho** [Nandaka/PixivUtil2#1079]
Is it possible to store the artist's profile description and the url to their twitter account within a text file?

**Comment by cglmrfreeman** [comment]
That might fall out of the scope of the program. I don't think the API provides that information and would require an html scrape. There are also artists who, while they have a twitter account, may not link them with their pixiv account.

Storing metadata into a text file, however, I feel would be a useful feature.
