### ISSUE TITLE
More Human-Readable Download Stream/Download Progress Indicator?

### ISSUE THREAD

**Issue by photonometric** [Nandaka/PixivUtil2#108]
@Wictim mentioned this in his long tips thread #75. In recent builds, the text stream has become more or less unreadable, at least to me.

A year ago, the DOS download box wasn't an elegant user readout by any means, but the text stream was fairly slow (one or two pages of text for each file), and when it paused to download, salient information such as artist, image number, entry date, etc were clearly visible for a duration long enough to skim over. 

In the current build, I find half a dozen or more pages of headers and alphanumeric strings flying by for each (sub)image, and when the screen pauses long enough for me to absorb some of the text, barely any of the headers mean anything to me.

I wouldn't suggest that the data stream should be revamped to make it a user-friendly UI displaying all possible helpful info at all times; that would take a lot of programming, and be too much for realistic use. However, it would be nice if, say, when the stream paused to download a file, some information like the artist, image number (n out of X for their gallery), image date, etc was visible for a few minutes. 

As it stands, when I run a download batch on a list.txt containing several artists, I have literally no clue if it's downloading what I intended, or where in the list it is currently, unless I pause and resume many times looking for an image or artist ID.

This isn't a terribly high priority issue, as it does not improve the actual functioning of this already excellent download utility, but it would be great if any simple modifications could be made that would indicate what was being downloaded, and some kind of estimate of completion (at least within the current user's gallery, unless a pre-fetch of the list.txt's total gallery count could be implemented).

**Comment by Nandaka** [comment]
well, I'm using windows cmd and I can pause the output by clicking the screen (enable quick edit mode in properties). I'm not sure about dosbox

**Comment by NHOrus** [comment]
... Why you need to see output data stream?
Also, all that data is seen as the name of PixivUtil window.

**Comment by chronometric** [comment]
Sorry, by "dosbox" I meant the command prompt window...I forgot dosbox was an actual program ;)

As for why I need to see the output....the last list.txt of artists I made took over 24 hours to download, and it wasn't even that many (probably large galleries). It's nice to see where the progress is, and the information in the title bar only shows info on a gallery page view basis. Perhaps a better question would be, why do I need to see half a dozen pages of headers for each image?

Anyway, like I said, I can press pause and sometimes pick out a piece of information that tells me something about what's being downloaded. But it used to be a lot easier to read, and with some scan-ahead for each gallery, it would be possible to give a true progress meter.

Again, obviously not a priority enhancement, but it is a fairly common feature of most download programs ^^

**Comment by NHOrus** [comment]
How many artists are in your list.txt?

For 3100 in mine, update each two days causes ~1000k images and takes about 5 hours. This is why I want PixivUtil to check updates from artists and download new images independently, parallel with each other.

Full deep check of all images takes about... a week? Hard to say.
Are you sure you are using PixivUtil correctly?

**Comment by Hamuko** [comment]
>This is why I want PixivUtil to check updates from artists and download new images independently, parallel with each other.

Isn't that exactly what the _Download new illust from bookmark_ feature is for?

**Comment by chronometric** [comment]
> Are you sure you are using PixivUtil correctly?

Well, I've been using it since it came out, and have a database of well over 100gb. But I'm not sure what a simple request for a download progress meter has to do with using this program correctly. It's just a simple usability idea, and has nothing to do with how much any of us download.

**Comment by Nandaka** [comment]
>  progress meter

might be difficult, because pixivutil didn't check what is the maximum images to download. It just iterate on each page until it hit the termination condition (e.g. last page, exceed the update image limit, etc).

**Comment by chronometric** [comment]
Sure, that makes sense. However, when you're on an artist's main page, it has a link under the image submissions that says "View More (n)," and on the Works page itself, it has  something that says "N results." That doesn't count the multi-page submissions, but might help with a ballpark figure.

To be honest, I wasn't really hoping for a precise download progress bar. Even just something like "5 of 45 galleries downloaded" would give one some idea. ^^

**Comment by Nandaka** [comment]
enhance the image count parser.

you can check the total image on the console title:
![image](https://cloud.githubusercontent.com/assets/836867/13899772/30e10df2-ee31-11e5-93bc-e074034538c8.png)

**Comment by NHOrus** [comment]
Ok, but if you order to download starting from page X, it doesn't subtracts skipped images.
So, if there's start page, you need to subtract number of pages * number images on page ( currently 20, I think), and if there's additional stop page, you need to put lesser  number out of ((stop-start) * 20) and (all - start * 20)

**Comment by Nandaka** [comment]
subtract from the total available images?

**Comment by NHOrus** [comment]
Yes.

**Comment by Arujei** [comment]
When I pulled the latest changes I started getting errors:

> Reading C:\pixiv\PixivUtil2\config.ini ...
> done.
> Error at process_tags(): (<type 'exceptions.TypeErro
> operand type(s) for *: 'NoneType' and 'int'",), <tra
> )
> Error at process_tags_list(): (<type 'exceptions.Typ
> rted operand type(s) for *: 'NoneType' and 'int'",),
> 80F8>)
> Traceback (most recent call last):
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 184
>     np_is_valid, op_is_valid, selection = main_loop(
> ction, np_is_valid, args)
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 164
>     menu_download_from_tags_list(mode, op_is_valid,
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 150
> s_list
>     process_tags_list(mode, filename, page, end_page
> _first=oldest_first, bookmark_count=bookmark_count)
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 903
>     use_tags_as_dir=__config__.useTagsAsDir, oldest_
> _count=bookmark_count)
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 736
>     stop_offset = end_date * 20
> TypeError: unsupported operand type(s) for *: 'NoneT
> press enter to exit.


From what I saw it was related to the commit (8c6d76b9e256ae4e3cebe2a79e7eaeec187f1156)

**Comment by Nandaka** [comment]
Crap, got typo. Supposed to be end_page

**Comment by Arujei** [comment]
Just pulled it and everything looks good now.

**Comment by NHOrus** [comment]
It appears to be broken again.
20160421, Windows, constantly shows 0 instead of total number of pages.

**Comment by photonometric** [comment]
Has been working great for a long time, so I guess I'll close. Thanks a lot for the meter in the title bar; it makes it a lot easier for people who do manual batch downloads instead of putting every artist in list.txt. n_n
