### ISSUE TITLE
Filter r-18 images

### ISSUE THREAD

**Issue by weypro** [Nandaka/PixivUtil2#1080]
Hi. Please help me how to filter or even not to download r-18 images.

**Comment by Nandaka** [comment]
go to the pixiv website and disable it from there, then update the cookie value.
![image](https://user-images.githubusercontent.com/836867/152346470-58b08467-950b-4eb5-967d-71ad514cda65.png)

**Comment by weypro** [comment]
Maybe the method doesn't fit my need. I want to browse all images at any time, but I just don't want to download r-18 images for my own data research.

**Comment by Nandaka** [comment]
enable 'useblacklisttags' in config.ini (check readme for details).
