### ISSUE TITLE
Cannot Download : Unknown Error, please check the log file: (<class 'PermissionError'>, PermissionError(13, 'Access denied'), <traceback object at 0x000001A36129FC00>)

### ISSUE THREAD

**Issue by Dragondepierre** [Nandaka/PixivUtil2#1085]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Cannot download images

### Steps to Reproduce

Start "download from bookmarked images"

#### Expected behavior:

Program start downloading after importing all bookmarks

#### Actual behavior:

After all the bookmarks have been imported properly, downloading doesn't work 👍 

Image # 1
Processing Image Id: 95438094
Member Name  : 白男川ふたば™
Member Avatar: https://i.pximg.net/user-profile/img/2021/06/23/22/26/39/20923693_32bd83b2de505fa948b1aca78cb60d12.jpg
Member Token : shiraotogawafutaba
Member Background : https://i.pximg.net/c/1920x960_80_a2_g5/background/img/2020/11/24/22/02/09/23473552_ca7bb5c5c3f6cd0d509182b30c01106c.jpg
Title: ＼祝成人／
Tags : 3DCG, DAZ
Date : 2022-01-10 10:04:36+00:00
Mode : big
Bookmark Count : 1134
Image URL : https://i.pximg.net/img-original/img/2022/01/10/19/04/36/95438094_p0.jpg
Filename  : C:\WINDOWS\System32\白男川ふたば™ (23473552)\95438094_p0 - ＼祝成人／.jpg
Creating directory: C:\WINDOWS\System32\白男川ふたば™ (23473552)
Traceback (most recent call last):
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivImageHandler.py", line 251, in process_image
    (result, filename) = PixivDownloadHandler.download_image(caller,
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivDownloadHandler.py", line 52, in download_image
    PixivHelper.makeSubdirs(filename_test)
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivHelper.py", line 733, in makeSubdirs
    os.makedirs(directory)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access denied: 'C:\\WINDOWS\\System32\\白男川ふたば™ (23473552)'
Error at process_image(): 95438094
Exception: (<class 'PermissionError'>, PermissionError(13, 'Access denied'), <traceback object at 0x000001A3612AB4C0>)
[Errno 13] Permission denied: 'Error medium page for image 95438094.html'
Dump File created: Error medium page for image 95438094.html
Dumping html to: Error medium page for image 95438094.html
Error at process_image_bookmark(): (<class 'PermissionError'>, PermissionError(13, 'Access denied'), <traceback object at 0x000001A36121BD80>)
Traceback (most recent call last):
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivUtil2.py", line 1532, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args, options)
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivUtil2.py", line 1220, in main_loop
    menu_download_from_online_image_bookmark(op_is_valid, args, options)
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivUtil2.py", line 557, in menu_download_from_online_image_bookmark
    PixivBookmarkHandler.process_image_bookmark(sys.modules[__name__],
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivBookmarkHandler.py", line 90, in process_image_bookmark
    result = PixivImageHandler.process_image(caller,
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivImageHandler.py", line 251, in process_image
    (result, filename) = PixivDownloadHandler.download_image(caller,
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivDownloadHandler.py", line 52, in download_image
    PixivHelper.makeSubdirs(filename_test)
  File "E:\PixivUtil2-master\PixivUtil2-master\PixivHelper.py", line 733, in makeSubdirs
    os.makedirs(directory)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access denied: 'C:\\WINDOWS\\System32\\白男川ふたば™ (23473552)'
Unknown Error, please check the log file: (<class 'PermissionError'>, PermissionError(13, 'Access denied'), <traceback object at 0x000001A36129FC00>)
press enter to exit.

[Error Log !](https://github.com/Nandaka/PixivUtil2/files/8075252/pixivutil.log)

### Versions

v20211104

**Comment by Dragondepierre** [comment]
SOLVED !

**Comment by PatrickL546** [comment]
Looks like you're trying to save them in system32. Try running it in admin or change the directory where you save them.

**Comment by Nandaka** [comment]
Remember to extract the zip file too and run directly by clicking the application directly.

**Comment by Dragondepierre** [comment]
> Remember to extract the zip file too and run directly by clicking the application directly.

So yeah I extracted it before using it.

> Looks like you're trying to save them in system32. Try running it in admin or change the directory where you save them.

Yeah I see that it wants to download it in system32 ... Don't know why ! Didn't see an option to change de download directory in the config ...how can I do that ?
