### ISSUE TITLE
"Folder" image will continue to find different file size + Pixiv Sketch error

### ISSUE THREAD

**Issue by curya** [Nandaka/PixivUtil2#1086]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Getting images from this user (65619146) will result in a few problems. If you try to download multiple times, it will constantly redownload the "folder" image because of a file size issue.

Note: After running it about 3 times, the 4th time finally said the file size was accurate.

Also, if you select "y" to include Pixiv Sketch, you get this error:

> Processing Artist Id: user_wxgx2788 for PixivSketch
> Traceback (most recent call last):
>   File "PixivSketchHandler.pyc", line 46, in process_sketch_artists
>   File "PixivBrowserFactory.pyc", line 1054, in sketch_get_posts_by_artist_id
>   File "PixivBrowserFactory.pyc", line 1092, in getPixivSketchPage
>   File "PixivBrowserFactory.pyc", line 209, in open_with_retry
>   File "mechanize\_mechanize.pyc", line 257, in open
>   File "mechanize\_mechanize.pyc", line 313, in _mech_open
> mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found
> Error at process_sketch_artists(): user_wxgx2788
> Exception: (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0xf96a90 whose wrapped object = <HTTPError 404: 'Not Found'>>, <traceback object at 0x04EEC7E8>)

### Steps to Reproduce

1. Choose option 1 with user 65619146. Select "y" to include Pixiv Sketch
2. When it finishes. Run the same options again and the "folder" image will redownload.
3. Run it as many times as you want and it will make a new "folder" image each time.

**Expected behavior:** "Folder" image should only download once.

**Actual behavior:** "Folder" image downloads a new image each time.

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
either the downloaded folder.jpg is corrupted so it try to redownload again, or you can set `alwaysCheckFileSize = False` in config.ini

```
- alwaysCheckFileSize

Check the file size, if different then it will be downloaded again, set False to disable. This will override the image_id checking from db (always fetch the image page to check the remote size).

``
