### ISSUE TITLE
[Fanbox] `url_embed` not detected

### ISSUE THREAD

**Issue by shinonomeme** [Nandaka/PixivUtil2#1087]
`url_embed` blocks within the bodies of Fanbox posts are not currently detected.

*Example post:* https://yellowbea.fanbox.cc/posts/3143003 (warning, NSFW)
<details>
    <summary><em>Example data:</em> <code>https://api.fanbox.cc/post.info?postId=3143003</code></summary>
    <pre>
        <code>
{
  "id": "3143003",
  "title": "Request : Jillllll",
  "coverImageUrl": "https://pixiv.pximg.net/c/1200x630_90_a2_g5/fanbox/public/images/post/3143003/cover/pW7K0YQtAREnHt8sWmnyBu8d.jpeg",
  "feeRequired": 0,
  "publishedDatetime": "2021-12-17T19:20:39+09:00",
  "updatedDatetime": "2021-12-17T19:20:39+09:00",
  "type": "article",
  "body": {
    "blocks": [
      {
        "type": "p",
        "text": ""
      },
      {
        "type": "url_embed",
        "urlEmbedId": "iQFvdxCmxDJOvvRHcrOTEGn0"
      },
      {
        "type": "p",
        "text": "Everybody in this is over 2000 years old."
      },
      {
        "type": "p",
        "text": "Please tell me if link is dead."
      }
    ],
    "imageMap": {},
    "fileMap": {},
    "embedMap": {},
    "urlEmbedMap": {
      "iQFvdxCmxDJOvvRHcrOTEGn0": {
        "id": "iQFvdxCmxDJOvvRHcrOTEGn0",
        "type": "html.card",
        "html": "&lt;div class=&quot;iframely-card iframely-small iframely-embed&quot;&gt;&lt;div class=&quot;iframely-responsive&quot; style=&quot;height: 140px; padding-bottom: 0;&quot;&gt;&lt;iframe src=&quot;https://cdn.iframe.ly/JHU5cCv?language=ja-JP&amp;app=1&quot; allowfullscreen&gt;&lt;/iframe&gt;&lt;/div&gt;&lt;/div&gt;"
      }
    }
  },
  "tags": [],
  "excerpt": "Everybody in this is over 2000 years old.\nPlease tell me if link is dead.",
  "isLiked": false,
  "likeCount": 13,
  "commentCount": 0,
  "restrictedFor": null,
  "isRestricted": false,
  "user": {
    "userId": "1386751",
    "name": "YellowBea",
    "iconUrl": "https://pixiv.pximg.net/c/160x160_90_a2_g5/fanbox/public/images/user/1386751/icon/Ihpja1OUHjFtjlqA29wIB487.jpeg"
  },
  "creatorId": "yellowbea",
  "hasAdultContent": true,
  "commentList": {
    "items": [],
    "nextUrl": null
  },
  "nextPost": {
    "id": "3145546",
    "title": "Request : Ellie Ellie",
    "publishedDatetime": "2021-12-18 11:32:33"
  },
  "prevPost": {
    "id": "3138816",
    "title": "Request : Jilllll",
    "publishedDatetime": "2021-12-16 17:42:25"
  },
  "imageForShare": "https://pixiv.pximg.net/c/1200x630_90_a2_g5/fanbox/public/images/post/3143003/cover/pW7K0YQtAREnHt8sWmnyBu8d.jpeg"
}</code>
    </pre>
</details>

---

Thank you in advance for the fix.

**Comment by Nandaka** [comment]
I can modify so it will shown in the html page:
![image](https://user-images.githubusercontent.com/836867/155275946-58c51854-012b-4807-b0c4-2a882ff4f102.png)

and  listed in the `descriptionUrlList`
![image](https://user-images.githubusercontent.com/836867/155275486-c99e6650-129a-4a90-bae3-199e5f348b5e.png)

I cannot do auto download the content in the iframe.
