### ISSUE TITLE
Can't login due to an infinite loop.

### ISSUE THREAD

**Issue by Deejay85** [Nandaka/PixivUtil2#1088]
I tried to update to the most recent build, delete the config file, and past back in the username/password/cookie/oauth, but no matter what I do, I keep getting this error message.

Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x43fe268 whose wrapped object = <HTTPError 302: 'The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nFound'>>, <traceback object at 0x043FD808>)
Cannot Login!

Since I've tried everything I could think of I'm relatively sure the issue is program side.

**Comment by Nandaka** [comment]
ensure the `useragent` value also matching with the browser you used to get the cookie from.

**Comment by WhiteSp1rit** [comment]
I have exact same problem. Cannot login due to redirect error that would lead to an infinite loop

**Comment by WhiteSp1rit** [comment]
for me the problem was that the cookie value in the config was old, got the new one from the browser and it worked

**Comment by Nandaka** [comment]
might be useful for reference #814
