### ISSUE TITLE
No Executable Files

### ISSUE THREAD

**Issue by Dunimon1313** [Nandaka/PixivUtil2#1089]
I downloaded the program, but it has no executables and I can't figure out how to run it.

**Comment by PatrickL546** [comment]
https://github.com/Nandaka/PixivUtil2/releases/download/v20211104/pixivutil20211104.zip
You can run PixivUtil2.exe
Or run PixivUtil2.py if you're running from source code

**Comment by Verycool121** [comment]
"VCRUNTIME140.dll" was not found

> https://github.com/Nandaka/PixivUtil2/releases/download/v20211104/pixivutil20211104.zip You can run PixivUtil2.exe Or run PixivUtil2.py if you're running from source code

**Comment by PatrickL546** [comment]
> "Could not load Python Library"
> 
> > https://github.com/Nandaka/PixivUtil2/releases/download/v20211104/pixivutil20211104.zip You can run PixivUtil2.exe Or run PixivUtil2.py if you're running from source code

Have you checked requirements in readme?
