### ISSUE TITLE
[v20160308-beta1] Image titles are not longer processed properly

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/PixivUtil2#109]
Since yesterday (2016.03.18), all downloads do not have image names/titles in filenames. When trying to download any image, this is what PixivUtil2 displays:
<pre>Title:</pre>

Example, downloaded: <pre>55891306_p0 -.jpg</pre>Should have downloaded: <pre>55891306_p0 - ドゥーチェ.jpg</pre>

**Comment by acrox999** [comment]
It seems that Pixiv might have changed something. Even the meta info file generated by the tool no longer shows the title.

**Comment by reyaz006** [comment]
I'm closing this as it has been properly fixed, as far as I can see. Thank you, @Nandaka.
