### ISSUE TITLE
Downloading by tags stopped with unknow reason

### ISSUE THREAD

**Issue by polujm9** [Nandaka/PixivUtil2#1090]
I'm trying to download images with tag "ウマ娘 or 赛马娘 or 賽馬娘" but it always stop at page 36.

I did search the string on Pixiv and the result is over 1000 pages.

Then I tried start  download from page 37 but it stopped immediately.

I tried another tag and it stopped at page 223 and it should have over 1000 pages too.

Last message in log :
 `2022-02-24 13:32:57,217 - PixivUtil20211104 - INFO - Last page: 223`

program version : v20211104

**Comment by Nandaka** [comment]
It will download R18 only if `r18mode = True` is set in `config.ini`

![image](https://user-images.githubusercontent.com/836867/155481304-3818e4d6-f8e0-4ed6-80c3-dc8e203d59dd.png)

https://github.com/Nandaka/PixivUtil2/blob/2a149364ac60838e549f91cf5c0d63aa474f814f/PixivHelper.py#L890
https://github.com/Nandaka/PixivUtil2/blob/2a149364ac60838e549f91cf5c0d63aa474f814f/PixivTagsHandler.py#L72

```
from pixiv website:
https://www.pixiv.net/ajax/search/artworks/%E3%82%A6%E3%83%9E%E5%A8%98%20or%20%E8%B5%9B%E9%A9%AC%E5%A8%98%20or%20%E8%B3%BD%E9%A6%AC%E5%A8%98?word=%E3%82%A6%E3%83%9E%E5%A8%98%20or%20%E8%B5%9B%E9%A9%AC%E5%A8%98%20or%20%E8%B3%BD%E9%A6%AC%E5%A8%98&order=date_d&mode=all&p=1&s_mode=s_tag&type=all&lang=en

&order=date_d
*&mode=all*
&p=1
&s_mode=s_tag
&type=all
&lang=en

from the script
https://www.pixiv.net/ajax/search/artworks/%E3%82%A6%E3%83%9E%E5%A8%98%20or%20%E8%B5%9B%E9%A9%AC%E5%A8%98%20or%20%E8%B3%BD%E9%A6%AC%E5%A8%98?word=%E3%82%A6%E3%83%9E%E5%A8%98%20or%20%E8%B5%9B%E9%A9%AC%E5%A8%98%20or%20%E8%B3%BD%E9%A6%AC%E5%A8%98&s_mode=s_tag&type=all&mode=r18&order=date_d

&order=date_d
*&mode=r18*
&s_mode=s_tag
&type=all

```

**Comment by polujm9** [comment]
> https://www.pixiv.net/ajax/search/artworks/%E3%82%A6%E3%83%9E%E5%A8%98%20or%20%E8%B5%9B%E9%A9%AC%E5%A8%98%20or%20%E8%B3%BD%E9%A6%AC%E5%A8%98?word=%E3%82%A6%E3%83%9E%E5%A8%98%20or%20%E8%B5%9B%E9%A9%AC%E5%A8%98%20or%20%E8%B3%BD%E9%A6%AC%E5%A8%98&order=date_d&mode=all&p=1&s_mode=s_tag&type=all&lang=en
> 
> &order=date_d
> *&mode=all*
> &p=1
> &s_mode=s_tag
> &type=all
> &lang=en

But my "r18mode" setting in config.ini is "False"

**Comment by polujm9** [comment]
I tried to update cookie PHPSESSID, now one of them is downloading, but another only run one page then stopped.

**Comment by Nandaka** [comment]
upload the pixivutil.log?

**Comment by Nandaka** [comment]
also do you run with partial tag match = y?

**Comment by polujm9** [comment]
Here's the log.
Line 1~10 is the one stopped at page 1.
Line 11+ is I chage PHPSESSID back to old one.

I download with "s_tag = y" and "search type = a (all)"



[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/8132546/pixivutil.log)

**Comment by Nandaka** [comment]
uploaded new releases https://github.com/Nandaka/PixivUtil2/releases/tag/v20220224-beta1

can you try to use that version? if it still have issue, please upload the log file here again.

**Comment by polujm9** [comment]
Still stopped
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/8137436/pixivutil.log)

**Comment by Nandaka** [comment]
Looks like pixiv server will return empty result if it detect too many download from the script at random page.

![image](https://user-images.githubusercontent.com/836867/155644224-1796af6e-ee48-4afa-9f29-c7a24dce8f90.png)

I think need to add back off timer to wait for few minutes until the server can return more posts.

**Comment by Nandaka** [comment]
rerun the same query and this time stopped at page 198

![image](https://user-images.githubusercontent.com/836867/155644678-d403ca30-4655-4866-9de7-086d0edd0c4b.png)

![image](https://user-images.githubusercontent.com/836867/155644624-84a0507d-4766-481d-b6d0-ee859322a94c.png)

**Comment by Nandaka** [comment]
adding delay and retry for 180s still doesnt help...
![image](https://user-images.githubusercontent.com/836867/155649503-ebc76579-d2ca-4e89-a403-59dc05d16738.png)

**Comment by Nandaka** [comment]
setting some `downloadDelay` in config.ini might help. Looks like pixiv does return empty result if it detect too many request to its api.

**Comment by polujm9** [comment]
Setting downloadDelay from 2 to 10 works fine for now, don't know will it stopped again.

**Comment by polujm9** [comment]
Setting downloadDelay works for those not downloaded ,
but still stopped when most images are already downloaded.

**Comment by Nandaka** [comment]
if that the case, then you need wait a while and manually start from the stopped page. I can't do anything, as the server itself doesn't return the result back.

**Comment by NewUserHa** [comment]
https://github.com/Nandaka/PixivUtil2/blob/8cabbbe07d453e1bf244296eff91f38d1a69550f/PixivTagsHandler.py#L91
why commit in this issue add random wrong user agents which are used by all search-tag related functions?
