### ISSUE TITLE
Files and images inside Fanbox Posts don't download

### ISSUE THREAD

**Issue by esserius** [Nandaka/PixivUtil2#1095]
### Description
Images and other files that are inside posts in Fanbox won't download.
### Steps to Reproduce

1. Connect to Fanbox
2. Use F2 and enter the ID to download an artist's posts.

**Expected behavior:** Images, PSDs, MP4s, etc. download from posts successfully

**Actual behavior:** Images, PSDs, MP4s, etc. failed to download
The PSD in this post does not download: https://hironi3.fanbox.cc/posts/2376628

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/8228835/pixivutil.log)

This happened with the latest release: https://github.com/Nandaka/PixivUtil2/releases/tag/v20220311-beta2

**Comment by Nandaka** [comment]
if you key in the post id directly, does it able to download the additional files?

**Comment by Nandaka** [comment]
can try the beta release
