### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by feiguizz** [Nandaka/PixivUtil2#1097]
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x043670C8>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x043C82A8>)
Cannot Login!

**Comment by Nandaka** [comment]
https://github.com/Nandaka/PixivUtil2/issues/814
