### ISSUE TITLE
[Request] Additionally check filenames with old naming scheme when checking for duplicates

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/PixivUtil2#110]
I've started a mass re-check of the whole database of my lists, as a result of https://github.com/Nandaka/PixivUtil2/issues/109 by enabling **alwayscheckfilesize** (I also forgot to use **numberofpage** for decreasing the time needed for the whole operation, but it's not relevant).

Now I discovered that tons of files got re-downloaded even though they were already on disk. For example, I had downloaded<pre>3950203 - 東方四漫画.jpg</pre>and newly downloaded duplicate was named<pre>3950203_p0 - 東方四漫画.jpg</pre>

The first one was downloaded in 2015, possibly when "_p0" was not being used for single images. I'd like PixivUtil2 to check if the file was already downloaded in that manner before deciding it's not exist.

**Comment by Nandaka** [comment]
not going to implement this. You can use Easy Duplicate Finder (or similar application) to remove the duplicated files.
