### ISSUE TITLE
[Code improvement] Identical fonction in test_PixivHelper.py

### ISSUE THREAD

**Issue by Toyem** [Nandaka/PixivUtil2#1100]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I recently went through the test code for test_PixivHelper.py and realized a strange detail.
On the TestPixivHelper class, is it normal for the two functions testSanitizeFilename and testSanitizeFilename2 to be identical or not ?
If it's normal maybe add a little comment to explain the usefulness of the second function.
In any cases, this has no impact on the proper functioning of the code so it's not a critical issue.

### Version

PixivDownloader2 version 20220311-beta3

**Comment by Nandaka** [comment]
oits, I think it was copy paste error from beginning :P
