### ISSUE TITLE
Large images getting flagged as DOS bombs.

### ISSUE THREAD

**Issue by GitErHubb** [Nandaka/PixivUtil2#1103]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Upon grabbing an image (～10MB), the program flags it as a decompression bomb and refuses to download it, closing the application. I've downloaded bigger files and images before this without any issue, but now it no longer works. 

### Steps to Reproduce

1. Open and run PixivUtil2 (in my case f1).
2. Sit back and wait.
3. DOS bomb error on the same image.

**Expected behavior:** For PixivUtil2 to archive my supported creators.

**Actual behavior:** Returns "Error at download_image(): (<class 'PIL. Image.DecompressionBombError'>, DecompressionBombError(' Image size (212548263 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack. ') and forces me to close the program.

### Versions
PixivDownloader 20220311-beta3

**Comment by Nandaka** [comment]
try to set 'verifyimage  = False' in config.ini?

**Comment by GitErHubb** [comment]
Excuse the late response, but that seemed to do the trick! A bit strange, but in any case, thanks!
