### ISSUE TITLE
[Feature req] Downloading from new_illust

### ISSUE THREAD

**Issue by ScrewThisNoise** [Nandaka/PixivUtil2#1106]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

What it says on the tin. Option to download from new_illust.

**Comment by Nandaka** [comment]
api endpoints, no promises though

```
https://www.pixiv.net/ajax/illust/new?lastId=0&limit=20&type=illust&r18=false&lang=en
https://www.pixiv.net/ajax/illust/new?lastId=97098030&limit=20&type=illust&r18=false&lang=en
https://www.pixiv.net/ajax/illust/new?lastId=0&limit=20&type=illust&r18=true&lang=en
https://www.pixiv.net/ajax/illust/new?lastId=97097963&limit=20&type=illust&r18=true&lang=en
```
