### ISSUE TITLE
problems downloading lists

### ISSUE THREAD

**Issue by smokeofc** [Nandaka/PixivUtil2#1107]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

option E (export online bookmark) and M (export online user bookmark) does the same thing.

### Steps to Reproduce

1. run app
2. select option e and/or d
3. same lists gets generated

**Expected behavior:** 
one exporting the list of bookmarked works, the other exporting a list of bookmarked artists.
**Actual behavior:** [What actually happened]
Same list is generated for both (both generate a list of followed artists)

### Versions

20211104 and 20220311-beta3

**Comment by Nandaka** [comment]
you means `e` and `m` ? `d` should be opening DB manager.

but, yeah, option `e` is calling the wrong api, it should use:
`https://www.pixiv.net/ajax/user/189816/illusts/bookmarks?tag=&offset=0&limit=48&rest=hide&lang=en`

and option `m` should use:
`https://www.pixiv.net/ajax/user/189816/following?offset=0&limit=24&rest=show&tag=&lang=en`

**Comment by Nandaka** [comment]
ah I just remembered,.. actually the `e` is to export your own followed artists and option `m` is to export other members followed artist (that's why it asked for the member id).

no feature to export the bookmarked images, only download the bookmarked images (option `6`).

**Comment by Nandaka** [comment]
from https://github.com/Nandaka/PixivUtil2/commit/19a4e84fe82eb89c412ddd27f20e0bdbb2744b31

**Comment by ScrewThisNoise** [comment]
> ah I just remembered,.. actually the `e` is to export your own followed artists and option `m` is to export other members followed artist (that's why it asked for the member id).
> 
> no feature to export the bookmarked images, only download the bookmarked images (option `6`).
> 
> Maybe I'll change the wording in the menu.

In which case, count this as a feature request then. Was sure that one was to export following users, the other exporting bookmarks >P
