### ISSUE TITLE
Download automation

### ISSUE THREAD

**Issue by gotr3k** [Nandaka/PixivUtil2#1108]
Hi, I was just wondering if there is a way to automate the process so it automatically downloads stuff, e.g. if I want to monitor my bookmarks and loop over my bookmark list so that it downloads new artwork how would i go about doing it? I don't know if there is a built in way to do this and have no idea how to pass multiple arguments that the program would accept so scripting is out of the question. Any suggestions are much appreciated ^_^

**Comment by Hamuko** [comment]
Just make a script. I have my NAS download all new images from my followed artists (`pixivutil2 -s 8 --ep=3 -x`) every 10 minutes.

**Comment by gotr3k** [comment]
Thanks man, had no clue how to pass arguments to the program
