### ISSUE TITLE
Log of newly downloaded files

### ISSUE THREAD

**Issue by Lenmaer** [Nandaka/PixivUtil2#111]
Hello,
I'd like to know if it was possible to generate a log file of all the newly downloaded files when using "List.txt"?
Because I've lots of IDs in there, it's a bit hard to find out what's new.
For example:
```
Name (ID Number):
0 New pictures

Name (ID Number):
%urlFilename% - %title%
%urlFilename% - %title%
%urlFilename% - %title%

----------------------------------

Total New Pictures: Number
```
Thanks.

-Lenmaer

**Comment by Nandaka** [comment]
set createDownloadLists = true in config.ini
