### ISSUE TITLE
[Feature] Padded page_index and page_number formatting options

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#1116]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Some image viewing software doesn't support natural sorting order - with parsing numerals and ordering pictures. It makes ordering of manga pages when viewing them - in pathological case - go 0; 1; 10; 100; 11; 12... which is disorienting

Sadly, I'm not always able to use sane image viewer, so pixivutil2-side workaround would be useful for this cases.

Please implement padded_page_index formatting that makes numbers go 000; 001; 002;... 009; 010 and so on.

**Comment by Nandaka** [comment]
it should pad with `0` and start from 1 if you use `%page_number%`
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L233

**Comment by Nandaka** [comment]
example: 
`filenameMangaFormat = %searchTags%\%member_id% %member_token%\%R-18% %urlFilename% - %page_number% - %title%`

result:
![image](https://user-images.githubusercontent.com/836867/164156474-ef4ce385-bd74-432e-9fd7-c200b3f197f0.png)

**Comment by NHOrus** [comment]
Oh. Maybe correct readme? There's nothing about padding in there right now
