### ISSUE TITLE
Downloading from fanbox user that is active on fanbox but suspended on pixiv halts the program and asks for name

### ISSUE THREAD

**Issue by Zekira** [Nandaka/PixivUtil2#1117]
### Prerequisites

* [Y] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [Y] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

When I try to download from a user on fanbox that is suspended on pixiv, I will be asked for name, even if I already typed it before. The functionality seems to be that this should only happen once per user since it should now be on the database, but that doesn't seem to be case and I keep getting that halt for the same user:

Similar to this over a year old issue which was apparently fixed, but is still happening for me: https://github.com/Nandaka/PixivUtil2/issues/873

![image](https://user-images.githubusercontent.com/11051413/165818766-b9a327e9-cf72-4dd1-8f93-2227b18f327d.png)

Is it possible to just get the name from the fanbox data instead of the pixiv data?

### Steps to Reproduce

1. Use any fanbox command that will point to an active use in Fanbox but suspended in pixiv.
3. Input name when program asks. Not sure if it makes a difference but I input simple Hiragana here
4. Let it finish
5. Do same command for same user
6. Name is still asked

**Expected behavior:** Program halts and asks for name

**Actual behavior:** Name should not be asked; preferrably the name should be retrieved from fanbox data instead of pixiv data

**Log file:** 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/8585335/pixivutil.log)

### Versions
20220311-beta3
You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by PatrickL546** [comment]
As far as I know, Fanbox and Pixiv can have different names. ex. 

https://www.pixiv.net/en/users/12957613
https://kgt1125.fanbox.cc/

Sorry don't have more examples.

**Comment by Nandaka** [comment]
hmm, it is being validated because the fanbox filenameformats have `%artist%` or `%member_token%`.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivFanboxHandler.py#L27-L41

Maybe I can add new format called `%fanbox_name% and %fanbox_creator_id%' taken from `body.user.name` and `body.creatorid` instead?
![image](https://user-images.githubusercontent.com/836867/166154973-284d250b-6be8-42a6-a3e1-b47ee90ba816.png)
