### ISSUE TITLE
How to call pixivutil2 from python?

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#1118]
![image](https://user-images.githubusercontent.com/75874561/167281799-017a3f10-d4da-42f0-b0ab-d55e31cd4052.png)

but I'm getting
![image](https://user-images.githubusercontent.com/75874561/167281806-00ca2c47-d21d-4c21-8c58-006f0831e439.png)

Seems to only work with one option and no space

![image](https://user-images.githubusercontent.com/75874561/167281825-8dcf2e43-cba8-47ef-9558-26120b3e147d.png)

Sorry for noob question.

**Comment by PatrickL546** [comment]
![image](https://user-images.githubusercontent.com/75874561/167281876-41e3aa52-4380-42ed-9d8c-ed82683feb54.png)
![image](https://user-images.githubusercontent.com/75874561/167281885-deda72d4-2f23-4a60-9290-3bb6074f8013.png)

but with this, it works? kinda
![image](https://user-images.githubusercontent.com/75874561/167281890-87d73a04-64f2-4dbf-a604-1a1ecf2141ae.png)
![image](https://user-images.githubusercontent.com/75874561/167281914-ec240ec3-2313-4f3e-9d5d-0a3a6021c174.png)

**Comment by PatrickL546** [comment]
Does it need to be separated by a comma?

**Comment by Nandaka** [comment]
check the doc? https://docs.python.org/3/library/subprocess.html
![image](https://user-images.githubusercontent.com/836867/167282963-f6f24aa7-022c-4318-908c-5a4497922261.png)

**Comment by PatrickL546** [comment]
I figured that out quickly, my bad I was blind.

My problem now is working with configparser.py
I was reading a config file and returning it. I try to get the values like `PixivArg = config['Settings']['PixivArg']`
I can't get rid of the double quotes around it. I tried strip() and PixivArg [1:-1]
![image](https://user-images.githubusercontent.com/75874561/167283942-a90d5997-d946-4d0c-b2a3-806b28848cde.png)

Also, I'm trying to read without interpolation.
![image](https://user-images.githubusercontent.com/75874561/167283963-0bd69db4-3d56-4a36-a6fa-80a952fb0cee.png)

I have this in another function and returning it.
![image](https://user-images.githubusercontent.com/75874561/167284202-b7d6e104-2b65-451a-a25c-a3bcf78158e5.png)

If this is too out of place, I can close it.

**Comment by Nandaka** [comment]
create a list for the first 2 arguments and then extend it with the splitted FanboxArs?

``` python
args = list()
args.append('python.exe')
args.append('yourscript.py')
fanbox_args = FanboxArg.split(' ')
args.extend(fanbox_args)
subprocess.run(args)
```

**Comment by cglmrfreeman** [comment]
I'm genuinely curious why you would do it this way instead of importing directly from the python scripts themselves...

**Comment by PatrickL546** [comment]
Think I finally found a solution. I made the config file have `PixivExportArg = -s, e, -p, y, -x, "Pixiv ID.txt"`
use configparser to get it with `PixivExportArg = config['Settings']['PixivExportArg']`
And to run it.
```Python
        args = list()
        args.append('python.exe')
        args.append(r'../PixivUtil2/PixivUtil2.py')
        PixivExportArg = PixivExportArg.split(", ")
        args.extend(PixivExportArg)
        subprocess.run(args, cwd=r'../PixivUtil2')
```
