### ISSUE TITLE
Going past page 100 ends download on next page.

### ISSUE THREAD

**Issue by Arujei** [Nandaka/PixivUtil2#112]
1. Start PixivUtil
2. Select download mode (Ex: 8)
3. Set start page to 99 or anything 100 or above.
4. Set end page to a number several pages higher or 0.
5. Observe.

Result:
Set page downloads, but does not continue onto next page in sequence past 100.
99 > 100 > stop
101 > stop
104 > stop
ect.

Expected Result:
Continue to next page until the limit set is reach or until running out of pages whichever comes first.

Notes:
Windows 7 64bit
PixivDownloader2 version 20160319

**Comment by Nandaka** [comment]
it is hardcoded to max page = 100 when I create this option
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1067

Did they changed the limit?

**Comment by Nandaka** [comment]
It is still limited to 100
http://www.pixiv.net/bookmark_new_illust.php?p=100

**Comment by jrami** [comment]
@Nandaka,
I'm a premium member so the limit isn't there. http://screencast.com/t/Jiv8t7w6r7M
Not sure if there is a clear flag for premium members, but it could just easier be a config setting that disables this hard coded stop at 100.

**Comment by Nandaka** [comment]
no real limit? can you try to hit page 1000 manually?

http://www.pixiv.net/bookmark_new_illust.php?p=1000

**Comment by jrami** [comment]
I don't have enough bookmarked to view 1000, but it does load.
http://www.pixiv.net/new_illust.php?type=all&p=1000 I can load. 
1000 does appear to be the limit at least when viewing new ones.

**Comment by Arujei** [comment]
I just confirmed a higher limit of 5000 via search: 
http://screencast.com/t/7V4NMN9rqF

Really does look like this one might be the highest point. No matter what I search for I can't go past 5000.

**Comment by Nandaka** [comment]
ok, then I will hardcode to stop at 5000 just in case.

Actually, the parser have checking if next page is available or not based on button state, but I still need to add hard limit in case they change the page layout.

**Comment by Arujei** [comment]
Yeah, that is a good idea. Though maybe just having it as a custom variable in the config for those that want it or don't want it higher since not everyone has premium. Well, thanks for getting back so quickly.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/20160414-beta1

**Comment by Arujei** [comment]
That works just fine.

**Comment by Arujei** [comment]
This has been working well for me. Thanks.
