### ISSUE TITLE
[Feature/Enhancement] Is there a way to add automatically illustrations that are always fail to download to the Blacklist?

### ISSUE THREAD

**Issue by halcatt** [Nandaka/PixivUtil2#1122]
When some illustrations may be deleted by the author, they would not be able to be downloaded. I wonder if it is possible to set a failure counter, that records how many times an illustration failed to download. When it reaches the limit set, the illustration will be added automatically to the blacklist.

**Comment by cglmrfreeman** [comment]
Can you provide an example? This has not happened to me in my 12 year use of this tool...

**Comment by halcatt** [comment]
> Can you provide an example? This has not happened to me in my 12 year use of this tool...

Oh! 12 years! 
Im new here, just have used this tool for half a year
I set this tool as a routine  everyday runs, it will be finished more quickly if it can skip those illustrations that cannot be downloaded

**Comment by cglmrfreeman** [comment]
I don't know which option you are using to download, because the download by artist id does not see deleted images, but if you use the database, you can simply add a fake entry for that image id, no?

**Comment by PatrickL546** [comment]
If it is looking at your image bookmarks should the deleted images be not in there then? A log file would be nice

**Comment by Nandaka** [comment]
or you can just set the `retry = 0` in config.ini?

**Comment by halcatt** [comment]
> or you can just set the `retry = 0` in config.ini?

I tried it but it didn't seem to work. 

I noticed the program will ALWAYS wait to download the next illustration in a random time period

```
....
Image # 1946
Processing Image Id: xxx
Giving up image_id (medium): xxx
Image ID (xxx): PixivException(9005 Failed to get page: https://www.pixiv.net/en/artworks/xxx=> HTTP Error 404: Not Found, hasDumpPage=N)
Stack Trace: (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net/en/artworks/xxx=> HTTP Error 404: Not Found'), <traceback object at 0x00729B68>)
Wait for 1.31s
Image # 1947
.....
```

## My solution
set the `downloadDelay=0`

but Im worried pixiv will block my IP at some point 'cause it's very like a robot

**Comment by Nandaka** [comment]
delete the image from your bookmark then? You can check the log file using keyword: `Giving up image_id (medium): ` using notepad++

**Comment by halcatt** [comment]
> delete the image from your bookmark then? You can check the log file using keyword: `Giving up image_id (medium): ` using notepad++

Sure, deleting the image from the bookmark is one way...
