### ISSUE TITLE
Option 2 is limited to finding 95 values

### ISSUE THREAD

**Issue by Baa14453** [Nandaka/PixivUtil2#1125]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

When using Image ID Option 2 I am pasting in some 235 URLs, but PixivUtil only detects 95 IDs, this happens with any list I paste in over 95.

### Steps to Reproduce

1. Gather 100 or so Pixiv Image URLs or IDs
2. Open PixivUtil and select Option 2
3. Paste in the URLs
4. PixivUtil will say `Found 95 ids`

**Expected behavior:** PixivUtil should find every ID pasted in.

**Actual behavior:** Pixiv only seems to find a maximum of 95 IDs

### Versions
PixivDownloader2 version 20220311-beta3

**Comment by PatrickL546** [comment]
On Windows here, found all the id's. Used image id's not url's, I don't have url's to test
![image](https://user-images.githubusercontent.com/75874561/170895628-99539112-fb19-452c-9e0c-82ee6e8f2863.png)

This is the max 22,867 characters I can fit in the windows python terminal

**Comment by Nandaka** [comment]
If there are duplicates, then it will remove the duplicates.
Else you can always try to use batch job for multi-images https://github.com/Nandaka/PixivUtil2/wiki/Using-Batch-Job-(Experimental)
