### ISSUE TITLE
getting a error when i try to download on fanbox

### ISSUE THREAD

**Issue by hunterinawheelchair** [Nandaka/PixivUtil2#1127]
Hello sorry to bother but i'm getting a error when i'm trying to download the content of a fanbox  then it close the app i hope  the log will help thank in advence for the solution!!

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/8826750/pixivutil.log)

**Comment by hunterinawheelchair** [comment]
after re-reading the log it seems that the software canno't fing the fanbox page but it's strange his pixiv account is not banned so i dont understand why it doesn't work.

**Comment by Nandaka** [comment]
I think you need to key in just `mohokuruko`, not the full url.

**Comment by hunterinawheelchair** [comment]
It worked thanks for the help!!
