### ISSUE TITLE
Saving with windows reserved name restrictions

### ISSUE THREAD

**Issue by Arujei** [Nandaka/PixivUtil2#113]
1. Start PixivUtil
2. Select any download mode (Ex: 1)
3. Use a member id  6028918 or of someone that has (CON, PRN, AUX, NUL, COM1-9,LPT1-9 ) in their name.
4. Set everything else default.
5. Observe.

Results:
The application errors out due to being unable to create the filename and windows returning an error to it likely one that the file already exist.

Expected Results:
Folder/File naming takes into consideration Windows reserved name restrictions and adjust accordingly.

Notes:
I ran into an issue where I was letting it run on some tags and then it couldn't save the file and errored out (included at the end). This was due to the Artist named Con.C mainly the "Con." part of it. 
Ref: https://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/
CON, PRN, AUX, NUL, COM1-9,LPT1-9 will error out in this manner if they are the whole name or just the start of it with a period as in the Con.C example. 

Well, I didn't spend too much time on this once I saw what was the cause. There are a few examples by searching about it mostly specific to their situation. Which may or not be helpful.

```
import re
badchars= re.compile(r'[^A-Za-z0-9_. ]+|^\.|\.$|^ | $|^$')
badnames= re.compile(r'(aux|com[1-9]|con|lpt[1-9]|prn)(\.|$)')

def makeName(s):
    name= badchars.sub('_', s)
    if badnames.match(name):
        name= '_'+name
    return name
```

> WindowsError: [Error 267] The directory name is invalid: u'X:\\pixivutil\\Con.C (6028918)'
> Error at process_image(): (<type 'exceptions.WindowsError'>, WindowsError(267, '
> The directory name is invalid'), <traceback object at 0x035C9B98>)
> Dumping html to: Error medium page for image 41714962.html
> Error at process_tags(): (<type 'exceptions.WindowsError'>, WindowsError(267, 'T
> he directory name is invalid'), <traceback object at 0x035C9648>)
> Dumping html to: Error page for search tags %E6%9C%A8%E4%B9%8B%E6%9C%AC%E6%A1%9C
> .html
> Error at process_tags_list(): (<type 'exceptions.WindowsError'>, WindowsError(26
> 7, 'The directory name is invalid'), <traceback object at 0x035C95A8>)
> Traceback (most recent call last):
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 1831, in main
>     np_is_valid, op_is_valid, selection = main_loop(ewd, mode, op_is_valid, sele
> ction, np_is_valid, args)
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 1629, in main_loop
>     menu_download_from_tags_list(mode, op_is_valid, args)
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 1487, in menu_download_from_tag
> s_list
>     process_tags_list(mode, filename, page, end_page, wild_card=wildcard, oldest
> _first=oldest_first, bookmark_count=bookmark_count)
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 890, in process_tags_list
>     use_tags_as_dir=__config__.useTagsAsDir, oldest_first=oldest_first, bookmark
> _count=bookmark_count)
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 783, in process_tags
>     process_image(mode, None, item.imageId, search_tags=search_tags, title_prefi
> x=title_prefix, bookmark_count=item.bookmarkCount, image_response_count=item.ima
> geResponse)
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 639, in process_image
>     result = download_image(img, filename, referer, overwrite, __config__.retry,
>  __config__.backupOldFile, image_id, page)
>   File "C:\pixiv\PixivUtil2\PixivUtil2.py", line 126, in download_image
>     downloadedSize = PixivHelper.downloadImage(url, filename, res, file_size, ov
> erwrite)
>   File "C:\pixiv\PixivUtil2\PixivHelper.py", line 503, in downloadImage
>     os.makedirs(directory)
>   File "C:\Python27\lib\os.py", line 157, in makedirs
>     mkdir(name, mode)
> WindowsError: [Error 267] The directory name is invalid: u'X:\\pixivutil\\Con.C (6028918)'
> press enter to exit.

**Comment by Nandaka** [comment]
weird, I'm using the codes already:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L68

maybe because that code is case-sensitive? Will check.

**Comment by Nandaka** [comment]
ah, give me your filenameformat in config.ini

**Comment by Arujei** [comment]
Ah, ok awesome.
I was using the default format in the config.
filenameformat = %artist% (%member_id%)\%urlFilename% - %title%

Thanks for the fast fix. Will pull the changes to test tonight.

**Comment by Arujei** [comment]
Ran through several sets of tags and including the one that caused the issue before everything looks good.
