### ISSUE TITLE
Error at pixiv_login_ssl() & doLogin()

### ISSUE THREAD

**Issue by Gimlao** [Nandaka/PixivUtil2#114]
```
PixivDownloader2 version 20160415-beta2
https://nandaka.wordpress.com/tag/pixiv-downloader/
Reading config.ini ...
done.
using default DB Path: db.sqlite
Creating database... done.
Only process member where day last updated >= 7
Username ? gimlao
Password ?
Log in using secure form.
Error at pixiv_login_ssl(): (<class 'urllib2.URLError'>, URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),), <traceback object at 0x02C446C0>)
Error at doLogin(): (<class 'urllib2.URLError'>, URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),), <traceback object at 0x02C54530>)
Cannot Login!
press enter to exit.
```

=/

**Comment by really-need-an-api-key** [comment]
I was about to press submit in another tab but checked the issues again for some reason.

Same here. Anything users can do on their end, something wrong with the certificate pixiv uses for https, or something else?

**Comment by Nandaka** [comment]
try to login from browser and copy the PHPSESSIONID cookie value to config.ini
![image](https://cloud.githubusercontent.com/assets/836867/14680999/e9b7a3b6-0751-11e6-8746-8e4144a5867d.png)

I'm not sure what is the root cause.

**Comment by really-need-an-api-key** [comment]
Copying the cookie val works for me.
I'm thinking maybe urllib uses an outdated certificate bundle, but then again I wouldn't see why it wouldn't use the system default used by the browser.

**Comment by Nandaka** [comment]
check the new release, it should fix the thing. root cause most likely is because of the different login url

**Comment by really-need-an-api-key** [comment]
>different login url

Oh. Didn't even notice it used to be secure.pixiv.net before. Works for me now.
