### ISSUE TITLE
strange error on a very specific ugoira image

### ISSUE THREAD

**Issue by Butterfly-Dragon** [Nandaka/PixivUtil2#1141]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I get an error on a very specific ugoira image

### Steps to Reproduce

1. try and download image id 98652280

**Expected behavior:** 
download and conversion of ugoira

**Actual behavior:** 
it stops with a `The process cannot access the file because it is being used by another process` on one of the images of the ugoira. PixivUtil gives out a 9999 error and then quits.

it only every happens on this *very specific* image.

**Log file:** 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9189920/pixivutil.log)
[Error medium page for image 98652280.zip](https://github.com/Nandaka/PixivUtil2/files/9189922/Error.medium.page.for.image.98652280.zip)

### Versions
PixivDownloader2 version 20220701

**Comment by Toyem** [comment]
This is an error that occurs in the latest version of the program. It occurs only on ugoira that alternates between black and white and color images.
A fix was applied a short time ago following similar feedback on the #1132 issue.

To enjoy the program without this error you need to download the latest version with the latest patches.
To do this, go to the "Code" tab of the GitHub page of the project then click on the green "Code" button, finally download the zip of the project by clicking on the "Download ZIP" pull-down menu.

<img width="1680" alt="Capture d’écran 2022-07-26 à 21 07 43" src="https://user-images.githubusercontent.com/36408240/181091690-141c8f92-7a19-4e35-a581-8dfa3bb1f8b2.png">

If you are using Git, just do the `git pull` command to get the latest modifications.

I hope that this explanation was clear and will allow you to not have this issue anymore. 
Don't hesitate to send back a mesasge if it happens again.

**Comment by Butterfly-Dragon** [comment]
Oh! Thanks! If it gets really annoying now i know what to do.

Will that work with the windows executable or only with the python version?

Otherwise i'll just deal with it until the new version comes out, i don't want to set up everything again and change execution environment just to solve 1 problem on 1 image.

**Comment by Toyem** [comment]
Unfortunately, the zip archive of the project does not contain a Windows executable, only the python code of the program. 
The improvements I mentioned are for the moment only available on the python program for the moment and the executable seems to be produced only with each new version created by Nandaka.

I have no workaround for you if you use the exe file. I can only invite you to wait for the next version of the program or to find a way to generate your own executable from the python program.

**Comment by Butterfly-Dragon** [comment]
thanks, it's no problem, i will wait.

**Comment by Butterfly-Dragon** [comment]
error persists in v20220804

**Comment by Toyem** [comment]
It's a pretty confusing situation. To make myself feel better I just ran the new version with the id you gave on my Windows 10 virtual machine, both the python code and the executable version. In both cases, the code runs perfectly and no errors occur. [log.txt](https://github.com/Nandaka/PixivUtil2/files/9262334/log.txt)

I will have to ask you for your config.ini and the version of Windows you are using.
Then I could try to reproduce the error in an environment as close as possible to yours

**Comment by Toyem** [comment]
Ok i got it, I managed to reproduce your error ([log.txt](https://github.com/Nandaka/PixivUtil2/files/9262724/log.txt)).  I had some suspicions when I saw your post but now I am 99% sure.

The error comes from the path that is called for your `ffmpeg.exe` file.
I thought the "!" at the beginning of the path was weird and when I did some tweaking I found the same error.
So your path for your ffmepg `D:\Downloads\Downloader\!downloader\ffmpeg.exe` must be wrong. Nothing too serious

**Comment by Butterfly-Dragon** [comment]
?!?!

![image](https://user-images.githubusercontent.com/33538906/183048507-6068f1da-86c9-4971-b51f-e3e469436573.png)

no? it is correct.

Also, that is the only ugoira that has any problem whatsoever, all other ugoiras get processed normally.

**Comment by Butterfly-Dragon** [comment]
apologies for the delays i am double checking some stuff to see if i am about to send sensitive info.

**Comment by Butterfly-Dragon** [comment]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9267465/pixivutil.log)
[config.zip](https://github.com/Nandaka/PixivUtil2/files/9267492/config.zip)

**Comment by Toyem** [comment]
I didn't manage to reproduce the error on my computer, but I may have an idea.
Can you modify in your `config.ini`, the line:
```
ffmpeg = "D:\Downloads\Downloader\!downloader\ffmpeg.exe"
```
By
```
ffmpeg = "D:\\Downloads\\Downloader\\!downloader\\ffmpeg.exe"
```

If it works, let us know so I can look more into it.

**Comment by Butterfly-Dragon** [comment]
No change.

Let me try `D:\\Downloads\\Downloader\\\!downloader\\ffmpeg.exe`

Nada,

Hmmm.... what if... i just put `ffmpeg.exe` and i make an hard link of the file in the same directory as pixiv?

Okay, that woked.

**Comment by yhtojy** [comment]
> No change.
> 
> Let me try `D:\\Downloads\\Downloader\\\!downloader\\ffmpeg.exe`
> 
> Nada,
> 
> Hmmm.... what if... i just put `ffmpeg.exe` and i make an hard link of the file in the same directory as pixiv?
> 
> Okay, that woked.

This solved my same problem on Win7 64bit.
Thank you.
