### ISSUE TITLE
[Fanbox] serviceProvider error

### ISSUE THREAD

**Issue by cglmrfreeman** [Nandaka/PixivUtil2#1142]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
There might be a new type of embed in Fanbox? This post certainly looks different than any I've encountered. Thankfully a lot of "all users" posts for the [yuichihiiragi](https://www.fanbox.cc/@yuichihiiragi) account. The post in question that seems to fail is [this one](https://www.fanbox.cc/@yuichihiiragi/posts/3998179).

EDIT: Issue may be related to #1133 but I was not 100% confident to post this there.

### Steps to Reproduce

1. Download by `yuichihiiragi` Fanbox artist (f2)
2. Should fail reaching [this post](https://www.fanbox.cc/@yuichihiiragi/posts/3998179)

**Expected behavior:**
Continue to other posts

**Actual behavior:**
Failure

**Log file:**
[pixivutil-31-07-22-fanbox.log](https://github.com/Nandaka/PixivUtil2/files/9229497/pixivutil-31-07-22-fanbox.log)
And console output: [fanbox-error.log](https://github.com/Nandaka/PixivUtil2/files/9229499/fanbox-error.log)

### Versions
Latest commit 19525f03ac537be2ee808aa2e917a3140a387fba

**Comment by aksskl** [comment]
I just started getting this error on posts that have embedded links, using the latest release.

**Comment by Nandaka** [comment]
do you have log file? might need to update https://github.com/Nandaka/PixivUtil2/blob/master/content_provider.json

**Comment by aksskl** [comment]
Sure, one sec

**Comment by Miyuutsu** [comment]
It's happening to me as well. I'll go ahead and attach a log too in case more sample sizes can help since it seems to be happening with multiple artists. 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9378571/pixivutil.log)

**Comment by Nandaka** [comment]
Can you try this: https://github.com/Nandaka/PixivUtil2/releases/tag/v20220825

It should be fixed on latest release

**Comment by Miyuutsu** [comment]
Yup, it's fixed now! Thanks a lot Nandaka!
