### ISSUE TITLE
"Couldn't find a tree builder with the features you requested: lxml" Errors preventing most image downloads (Windows Binary only)

### ISSUE THREAD

**Issue by Drakonas** [Nandaka/PixivUtil2#1146]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

When using the latest Windows binary, tons of images fail with a bs4 error "bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?".

When running from source after installing requirements and lxml, bs4, and html5lib packages, it runs fine.

Installing these packages did not affect the binary in any way. It still had issues even after I got the source build working.

### Steps to Reproduce

1. Download Windows binary, extract to folder. Run PixivUtil2.exe, then kill it, so configuration is generated.
2. Use the attached config, configuring the Username, Password, and Cookie as needed (stripped before upload).
3. Install the requirements, and also try installing lxml, bs4, and html5lib packages with pip from 3.10.
4. Run PixivUtil2.exe again, choose option 1, and download member ID 3665673.

**Expected behavior:** [What you expected to happen]
Complete as normal.

**Actual behavior:** [What actually happened]
Lots of these errors in the log and on output. Images failed to download.
```
2022-08-16 00:09:29,451 - PixivUtil20220804 - ERROR - Stack Trace: (<class 'bs4.FeatureNotFound'>, FeatureNotFound("Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?"), <traceback object at 0x0491CF28>)
2022-08-16 00:09:29,451 - PixivUtil20220804 - ERROR - Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 80, in process_image
  File "PixivBrowserFactory.pyc", line 626, in getImagePage
  File "PixivImage.pyc", line 163, in __init__
  File "PixivImage.pyc", line 257, in ParseInfo
  File "bs4\__init__.pyc", line 243, in __init__
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9348046/pixivutil.log)
[Example-config.ini.txt](https://github.com/Nandaka/PixivUtil2/files/9348052/Example-config.ini.txt)

### Versions
PixivUtil2 v20220804
Windows 10 21H2
Python 3.10.6

**Comment by Nandaka** [comment]
yap, look like missed some code that still reference lxml when processing the caption.
