### ISSUE TITLE
[feature request] Add date option when downloading rankings

### ISSUE THREAD

**Issue by xuejianxianzun** [Nandaka/PixivUtil2#1147]
### Prerequisites

* [✓ ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [✓ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [✓ ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I use the latest version of PixivUtil2.exe to download the ranking, there is no place to set the date. Does it download the latest rankings? What should I do if I want to download the previous day's ranking (20220816)?

### Steps to Reproduce

Input: 16
Valid Modes are: daily, weekly, monthly, rookie, original, male, female
Mode: daily
Valid Content Types are: all, illust, ugoira, manga
Type: illust
Start Page (default=1): 1
End Page (default= 0, 0 for no limit):

![20220818_181310.png](https://s2.loli.net/2022/08/18/YvnsudX1m7P95KF.png)
https://s2.loli.net/2022/08/18/YvnsudX1m7P95KF.png

**Expected behavior:** [What you expected to happen]

i want to set the date

**Actual behavior:** [What actually happened]

without this step

**Log file:** 

Attachment upload failed.

### Versions

PixivDownloader2 version 20220804

**Comment by Toyem** [comment]
There doesn't seem to be an option to manage the ranking date (correct me if I'm wrong). But it looks like that coding an option to customize the date is possible. The code seems to be already arranged for this kind of modification.

**Comment by xuejianxianzun** [comment]
Yes, it would be better to provide date options in the CLI.
