### ISSUE TITLE
convert to gif no such filter

### ISSUE THREAD

**Issue by anon1593** [Nandaka/PixivUtil2#1148]
### Prerequisites

* [ y] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [y ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

New FFmpeg error

Invalid argument
Failed when converting image using ffmpeg -y -safe 0 -i C:\Users\01\AppData\Local\Temp\convert_ugoira6yp80p7p\i.ffconcat -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" C:\Users\01\AppData\Local\Temp\convert_ugoira6yp80p7p\temp.gif ==> ffmpeg return exit code=1, expected to return 0.

[AVFilterGraph @ 000001e686916f40] No such filter: '"'

### Steps to Reproduce

convert ugoira to gif

**Expected behavior:** [What you expected to happen]
successful conversion
**Actual behavior:** [What actually happened]
convert to gif fails, continues to webm, which is [successful
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9377718/pixivutil.log)

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest commits pulled.

**Comment by Nandaka** [comment]
try to updating to the latest full ffmpeg package? you can get it from https://www.gyan.dev/ffmpeg/builds/

**Comment by Nandaka** [comment]
looks like found the issue, need to remove the `"` from `config.ini`
![image](https://user-images.githubusercontent.com/836867/185521520-73025ed1-d4c2-4c46-a199-c78e0aaf1689.png)

@Toyem #1145 cause the problem?

**Comment by anon1593** [comment]
Will test in a few minutes.

**Comment by anon1593** [comment]
ok, that fixed it.
Do I just run Ugoira re-encode option to fix the downloaded files?

**Comment by Nandaka** [comment]
you can try that
