### ISSUE TITLE
How to get all post (title, text, file) from an artist?

### ISSUE THREAD

**Issue by qin-yu** [Nandaka/PixivUtil2#1151]
### Description

I do see this `fanboxGetPostsFromArtist` function but not sure how to make it work.. Is it possible to use it by launching the `.exe` file? Or is there an example of using it to generate a list of (title, date, text, file) from an artist?

**Comment by cglmrfreeman** [comment]
PixivUtil2 is more of a downloading application. If you are looking to retrieve data, pixivpy might be a better option. However if you are looking to use an .exe out of the box and not Python that may not be an option at all. Else you can use PixivUtil2 to download all the fanbox posts from an artist and parse the log file yourself, though I am unfamiliar with how to grab all the text metadata from a fanbox post. 

I am unsure if gallery-dl supports fanbox, but if it does you can run the program with a dryrun and pass the fields to a post-processor to generate the list for you.

**Comment by qin-yu** [comment]
Thanks! I'll check out pixivpy. Also, it turned out there is an indirect way of getting the list:

1. Download all post (with file and bg image) from the artists you follow;
2. Export the csv file by `d` > `f1. Export FANBOX post list` option.

Now I have a table listing the URLs.
