### ISSUE TITLE
Fanbox: Crash on twitter community link/embed

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#1152]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I was downloading illustrations of artists I follow on pixiv and fanbox crashed 

### Steps to Reproduce

1. Start downloading from post https://yanokake.fanbox.cc/posts/3511703

**Expected behavior:**

Pixiv does the right thing with embedded link, as configured

**Actual behavior:**

Pixiv crashes

**Log file:** 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9418321/pixivutil.log)

### Versions

20220804

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20220825?

**Comment by NHOrus** [comment]
Fixed!
