### ISSUE TITLE
Can't make Gif files

### ISSUE THREAD

**Issue by BBandit18** [Nandaka/PixivUtil2#1153]
### Prerequisites

* [ ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I keep getting this, what am I doing wrong?

### Steps to Reproduce

1.  used command 10 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9421011/pixivutil.log)

2. added the member id and tag Ugoira
3. Waited

**Expected behavior:** To created gif file 

**Actual behavior:** got that this error C:\Users\Bandit\AppData\Local\Temp\convert_ugoiratabq9b0l\i.ffconcat: No such file or directory
Failed when converting image using ffmpeg.exe -y -safe 0 -i C:\Users\Bandit\AppData\Local\Temp\convert_ugoiratabq9b0l\i.ffconcat -filter_complex [0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle C:\Users\Bandit\AppData\Local\Temp\convert_ugoiratabq9b0l\temp.gif ==> ffmpeg return exit code=1, expected to return 0. 

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions
v20220825

**Comment by Nandaka** [comment]
do you update the config.ini as per instruction in https://github.com/Nandaka/PixivUtil2/releases/tag/v20220825

![image](https://user-images.githubusercontent.com/836867/186626015-252a8002-09d8-41ca-9bc9-6167b1917a16.png)

**Comment by BBandit18** [comment]
> do you update the config.ini as per instruction in https://github.com/Nandaka/PixivUtil2/releases/tag/v20220825
> 
> ![image](https://user-images.githubusercontent.com/836867/186626015-252a8002-09d8-41ca-9bc9-6167b1917a16.png)

Yes I did, and I still have that error
![image](https://user-images.githubusercontent.com/19337517/186738283-406cf8fb-347e-4c76-8a58-9c32641bcb38.png)
![image](https://user-images.githubusercontent.com/19337517/186739365-ed5d3cdd-816a-4fb7-818b-937b9d385a2a.png)

**Comment by Nandaka** [comment]
Looks like file access issue? it says cannot find the temp folder. Is there any antivirus blocking the temp folder creation?

Can you try to run it from source code?

**Comment by BBandit18** [comment]
how do I do that?

**Comment by Nandaka** [comment]
you can check the wiki here: https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

**Comment by BBandit18** [comment]
That didn't work

**Comment by Nandaka** [comment]
can you try to convert to webm only and see if it hit the same error? set `createWebm = True` in config.ini.

If it still return `No such file or directory` most likely something prevented the script to access the temp folder.

**Comment by BBandit18** [comment]
that didn't work either

**Comment by Nandaka** [comment]
i have no idea then.

**Comment by Toyem** [comment]
@BBandit18 Can you try to use an automatically generated `config.ini` file when the file is not present in the PixivUtils folder. Just modify the [Ugoira] and [Authentication] part in the newly generated file to allow generation of gifs.

**Comment by BBandit18** [comment]
@Toyem that didn't work either

**Comment by Toyem** [comment]
@BBandit18 The bug you have seems quite particular and I would like to target its origin a little more.
I'm going to ask you to do some tests to check where the problem can come from.

1. Can you download the [v20220825](https://github.com/Nandaka/PixivUtil2/releases/tag/v20220825) and [v20220804](https://github.com/Nandaka/PixivUtil2/releases/tag/v20220804) version of the program.
2. Launch the version [v20220825](https://github.com/Nandaka/PixivUtil2/releases/tag/v20220825). 
3. Generate the config file automatically and fill in the fields `[Ugoira]` and `[Authentication]` with your information.
4. Download a gif (for example [100684487](https://www.pixiv.net/en/artworks/100684487)) and check that you have the same bug as usual.
5. Launch the previous version [v20220804](https://github.com/Nandaka/PixivUtil2/releases/tag/v20220804). 
6. Generate another config file automatically and fill in the fields `[Ugoira]` and `[Authentication]` with your information.
7. Download the same gif ([100684487](https://www.pixiv.net/en/artworks/100684487)) and check if the bug is also present or not.

This will allow us to know if the bug comes from the new version or from your PC.

**Comment by BBandit18** [comment]
![image_2022-08-27_110356382](https://user-images.githubusercontent.com/19337517/187038237-1632d991-d89d-4e1a-b765-08368048c51a.png) New Version

![image_2022-08-27_110855241](https://user-images.githubusercontent.com/19337517/187038444-b2d0cd6b-2727-485c-bf0d-5f4a15589b99.png)
Previous Version 
@Toyem

**Comment by Toyem** [comment]
To begin with, it seems that the gif has been created in the new version of the script and that your initial problem solved itself (somehow):

![187038237-1632d991-d89d-4e1a-b765-08368048c51a](https://user-images.githubusercontent.com/36408240/187039997-c4e7a3b4-e557-4ea3-8773-e74cb7a974f8.png)

But an error occurred when using the database.
Judging by all the errors you have, there seems to be permission issues on your PC.
Are you maybe logged in with a guest session?

To be sure, I will ask you to open a command terminal and type the following commands:

```
dir C:\Users\Bandit\Pictures\pixivutil20220825
ls -l
```
Make a screenshot of the line where you can see the `db.sqlite` database.
Then type:

```
dir C:\Users\Bandit\AppData\Local\
ls -l 
```

And make a screenshot of the line where the `Temp` folder appears
Then type the following commands:

```
dir Temp
ls -l 
```

And if there is by any chance a folder starting by `convert_ugoira`, then type the following commands and replace <folder> by the complete name of the folder you may see beginning by `convert_ugoira`:

```
dir <folder>
ls -l 
```

And make a last screenshot of the lines that have appeared.

If you can show us these screenshots, it would allow us to check if it is a permission error.

**Comment by BBandit18** [comment]
![image_2022-08-27_204124224](https://user-images.githubusercontent.com/19337517/187053927-29e46fb1-58b1-46b3-b512-2c0d7e723e95.png)
![image_2022-08-27_204242194](https://user-images.githubusercontent.com/19337517/187053946-dd8c5af3-8afb-4168-b440-8487e7e5570f.png)
![image_2022-08-27_204419558](https://user-images.githubusercontent.com/19337517/187053978-cbcf37e3-2b51-41ae-87bb-49db1067410e.png)
@Toyem

**Comment by Revemohl** [comment]
I only just noticed this was happening here even for webms as well, but judging by two quick tests, updating ffmpeg fixed it for me. 

I'll have to clean up my database to find all the missing ugoiras but that's fine...

**Comment by Toyem** [comment]
I forgot that `ls -l` doesn't show permissions on Windows...

I'm a bit short of options for you. Apart from manually changing the properties of the PixivUtil folder, I don't see what else I can do.

(maybe update ffmpeg like Revemohl suggests, idk)

**Comment by BBandit18** [comment]
I think I'll just make it easier and just stick with the previous version, thanks for trying

**Comment by DisasterInbound** [comment]
I experienced this same issue when creating a webm but I can confirm that updating ffmpeg to the latest stable version fixed it.

**Comment by Uraratan** [comment]
alright thanks for linking me , 

i create 3 kinds of files from  ugoira 

![image](https://user-images.githubusercontent.com/112405829/187221415-eca761a7-66c5-4624-a046-7aab3f29fca3.png)

**Comment by Uraratan** [comment]
alright the videos works but not the gif and apng 

![image](https://user-images.githubusercontent.com/112405829/187223211-9bf7f256-35ae-47a9-ab83-45edcb9ea9fc.png)

**Comment by fdsa1538** [comment]
I still can't create webp with latest version=v20221029 ([No such file or directory] issue), so I just use v20220804.

**Comment by hkight** [comment]
Same here. v20220804 works for apng, but the latest version (v20221029) does not. (No such file or directory)
