### ISSUE TITLE
creating ugoira failed

### ISSUE THREAD

**Issue by Uraratan** [Nandaka/PixivUtil2#1154]
hello Nandaka

after i updated pixiv until to lateest version i get an error when creating gif from pixiv, it down;loads them but then i gt the error 

C:\Users\Vanilla\AppData\Local\Temp\convert_ugoirankadqhy3\i.ffconcat: No such file or directory
Failed when converting image using ffmpeg -y -safe 0 -i C:\Users\Vanilla\AppData\Local\Temp\convert_ugoirankadqhy3\i.ffconcat -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" C:\Users\Vanilla\AppData\Local\Temp\convert_ugoirankadqhy3\temp.gif ==> ffmpeg return exit code=1, expected to return 0.

it always worked fine  and i have no clue what this means

**Comment by Nandaka** [comment]
looks like same issue with https://github.com/Nandaka/PixivUtil2/issues/1153

**Comment by Nandaka** [comment]
try to update the ffmpeg to the latest version from https://www.gyan.dev/ffmpeg/builds/ (you can get the full one)
