### ISSUE TITLE
Question: Can I build a databse of Artists?

### ISSUE THREAD

**Issue by korason7117** [Nandaka/PixivUtil2#1155]
Is it possible to build a database of my followed Artists?
Info like:

- Author name
- referral links such as Twitter and others
- Description
- Users Following the author

Kind of like as if you saved the pixiv author page with something like the joplin extension which can save notes as *HTML* and among others

**Comment by Nandaka** [comment]
not really, the main purpose for this tool is just to help you to download the images.

It can dump the json file from each post if you enable it in config.ini
`writeRawJSON = True`

maybe you can refer to https://github.com/Nandaka/PixivUtil2/issues/1151
