### ISSUE TITLE
[pixivFANBOX] Embed raises an unsupported url provider 'fanbox.creator' error

### ISSUE THREAD

**Issue by AgentThirteen** [Nandaka/PixivUtil2#1156]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Unsupported embed type ``fanbox.creator`` which is not even a valid URL.
The post contains a ZIP file, is it a pixivFANBOX change? This did not happen before.

### Steps to Reproduce

1. Run PixivUtil2 with ``f3``
2. Attempt to download example post 4384185 (NSFW, public post)

**Expected behavior:** Getting post cover, pictures, ZIP file and HTML.
**Actual behavior:** PixivUtil2 throws a fatal error and stops. If using ``f2`` with the creator, it stops and exits upon reaching the post.

**Log:**
``Error processing FANBOX post: 4384185 ==> Unsupported url embed provider = fanbox.creator for post = 4384185, please update content_provider.json.``

### Versions
20220804
20220825

**Comment by Nandaka** [comment]
updated https://github.com/Nandaka/PixivUtil2/blob/master/content_provider.json

You can just replace your copy with the updated one.

**Comment by AgentThirteen** [comment]
Working as intended with the provided file additions. Closing, thanks a lot for the quick reply!
