### ISSUE TITLE
Create directory for image infomation files?

### ISSUE THREAD

**Issue by SamsonTKG** [Nandaka/PixivUtil2#1161]
Can I create a folder like "jsons" or "info" and export image information files to there?
i'd like to change to different location from image directory.

**Comment by Nandaka** [comment]
set the `filenameinfoformat` or `filenameSeriesJSON` with `\` as the path separator, e.g. `info\%member_id% %member_token%\%R-18% %urlFilename% - %title%` in the config.ini

**Comment by SamsonTKG** [comment]
Thank you, it worked!
