### ISSUE TITLE
Remove console clearing.

### ISSUE THREAD

**Issue by hikineet0** [Nandaka/PixivUtil2#1162]
Version: PixivUtil2-20220701

- I keyboard interrupt the code to look at what the red line that just flew by was, and the console clears.
- I want to note down who the current downloading artist is before stopping the script, I keyboard interrupt, now I have to start from the first artist in the list again.

A very impractical feature. I would like to see what had happened in the previous run when I interrupt the script. In fact, I would assume most people that interrupt the script would do it with the purpose of reading the output so far, which the screen clearing doesn't let one do.

Additionally, while we're on the topic of keyboard interrupting a running script, the Y/N prompt seems to never work, I always find myself spamming `Ctrl + C` instead. Please look into that as well.

**Comment by PatrickL546** [comment]
You can always check the logs after the fact. Or you can highlight the text from the console to 'pause' the program.
The Y/N prompt doesn't seem to work for me as well.

**Comment by hikineet0** [comment]
@PatrickL546 yes, but I would argue that checking the log is not very "user friendly" when you just want to look at what happened just now in the screen. Highlighting the text doesn't work for me, it's specific to Windows or some terminal emulator I guess?
