### ISSUE TITLE
After changing the PC and the Drive, downloader keep downloading in the same folder for Pixivutil

### ISSUE THREAD

**Issue by esotericer1** [Nandaka/PixivUtil2#1164]
After changing the PC, my local disk changed from 'E' to 'D'. And I think that might be the reason why using list only downloads the files to the same folder for PixivUtil, rather than downloading them neatly to all the subfolders.
Any ideas on how to change that using config and list? there's something about root directory and list directory, but was kinda confusing... 
also I tried using blacklist members but it doesnt seem to be working. any tips on that too?

**Comment by Nandaka** [comment]
check readme.md?

as for subfolder, maybe check the filename formats in config.ini

Below example will save the files in `D:\Temp\Pixiv2` directory, with each member with it's own directory
![image](https://user-images.githubusercontent.com/836867/190898456-13fa55e8-4ef5-4003-9b0f-684bc1b271e3.png)
