### ISSUE TITLE
Fanbox: Getting 'compression method is not supported' error for certain zip files

### ISSUE THREAD

**Issue by Zekira** [Nandaka/PixivUtil2#1165]
### Prerequisites

* [Y] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [Y] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

When going over certain zip files in fanbox, getting a 'That compression method is not supported' error for them.
I can only find one example right now though, but I'm not sure if I'm allowed to upload it. It's one of the files in this post: ttps://dikko.fanbox.cc/posts/4069313

### Steps to Reproduce

1. Do a fanbox download for a post with the offending zip file, in my case I do f2 (by artist) -> and then name, no limit on pages (download everything)
2. Attempt to download zip file

**Expected behavior:** Zip file should download properly

**Actual behavior:** Retry happens 20 times, but all with 'coimpression method is not suppored error', never proceeds to next posts and program is forced exited.

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9598279/pixivutil.log)

### Versions
20220825

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
try to set `verifyImage=False` in config.ini. Looks like python library cannot read the zip file format.

**Comment by Zekira** [comment]
> try to set `verifyImage=False` in config.ini. Looks like python library cannot read the zip file format.

Yeah looks like setting that to false worked.

**Comment by Nandaka** [comment]
fyi, the latest version will skip the checking automatically if it encounter format  not supported/NotImplementedError even with `verifyImage=True`

**Comment by Zekira** [comment]
> fyi, the latest version will skip the checking automatically if it encounter format not supported/NotImplementedError even with `verifyImage=True`

Nice, I'll be sure to grab it when I can, thanks for the update!
