### ISSUE TITLE
Save fanbox post as HTML regardless of settings

### ISSUE THREAD

**Issue by cglmrfreeman** [Nandaka/PixivUtil2#1166]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
I've recently supported an artist who uses passworded zip files as reward distribution within fanbox. These zip files passwords are in the posts of the rewards. However I can not alter `minTextLengthForNonArticle = 45` or `minImageCountForNonArticle = 3` to the point where the post with the passwords are saved as an html file.

Am I missing something?

### Versions
`PixivDownloader2 version 20220825 `

**Comment by Nandaka** [comment]
try this in config.ini?

```
writeHtml = True
minTextLengthForNonArticle = 0
minImageCountForNonArticle = 0
```

https://github.com/Nandaka/PixivUtil2/blob/master/PixivFanboxHandler.py#L223-L229

**Comment by cglmrfreeman** [comment]
Seems to have worked, thanks!
