### ISSUE TITLE
Error 429 at default settings.

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#1167]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

It seems even the default config setting is getting error 429, would this need a longer default downloadWait?

### Steps to Reproduce

1. Download from list

**Expected behavior:** No error

**Actual behavior:** Error 429
![image](https://user-images.githubusercontent.com/75874561/191166942-5428f654-4c2d-44b8-8bad-7e26b47bda8b.png)

### Versions

https://github.com/Nandaka/PixivUtil2/commit/b723feb4a72567746ab8696586fb3647a5d49334

**Comment by Toyem** [comment]
How many instances of PixivUtil were you running when you got that 429 error sequence?
Maybe it's because the account quota has been reached. 
Can you try to create a fake account and download via these new credentials.
If it doesn't change anything, try to see if using a vpn can get around the problem.

**Comment by PatrickL546** [comment]
I was just running a 1 pixivutil2 with my member list. I just looked and saw I'm getting errors

**Comment by Nandaka** [comment]
Looks like server side changed the connection limit, you can set the downloadDelay to 10 seconds (this is what I use).

**Comment by PatrickL546** [comment]
I've had it running for a while and I'm not seeing any error 429 in the logs, 5 second delay seems to be enough.
