### ISSUE TITLE
ImportError on _sylite3.pyd

### ISSUE THREAD

**Issue by slewantoski** [Nandaka/PixivUtil2#1170]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Today i've updated to the newest Windows binary release [v20220924](https://github.com/Nandaka/PixivUtil2/releases/tag/v20220924). Since this release PixiivUtil2 does no longer start. I've created a fresh installation with the same problem. Tried on a VM which has never seen any Python Installation with the same error.

### Steps to Reproduce

1. Download newest release
2. Extract release to a new, empty folder
3. Start pixivutil2.exe

**Expected behavior:** Program should start to the menu.

**Actual behavior:** Program crashes with error:
Traceback (most recent call last):
  File "PixivUtil2.py", line 18, in <module>
  File "PixivArtistHandler.pyc", line 10, in <module>
  File "PixivDownloadHandler.pyc", line 18, in <module>
  File "PixivDBManager.pyc", line 7, in <module>
  File "sqlite3\__init__.pyc", line 57, in <module>
  File "sqlite3\dbapi2.pyc", line 27, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed while importing _sqlite3: %1 is not a valid Win32 application.) 'c:\\2\\_sqlite3.pyd'

**Log file:** No Logfile is created.

### Versions

Happens since version v20220924. Older version works fine.
![Bild 2022-09-24 13 20 38](https://user-images.githubusercontent.com/50290847/192095084-096a2901-0719-45fa-a885-0ebc5f9598c7.png)

**Comment by Evaia** [comment]
Same thing happens to me too, OS is Windows 11 Pro

**Comment by YukihoAA** [comment]
I had same issue but is working fine with new compiled binary

**Comment by Nandaka** [comment]
recompile using 32-bit back, can you try?

**Comment by slewantoski** [comment]
> I had same issue but is working good now with updated binary

Where do i find the updated binary?

> recompile using 32-bit back, can you try?

sorry, i am not able to compile it.

**Comment by Nandaka** [comment]
I mean I have recompiled it using 32-bit python. You can check it in https://github.com/Nandaka/PixivUtil2/releases/tag/v20220924

**Comment by Evaia** [comment]
confirmed it fixed for me @Nandaka

**Comment by slewantoski** [comment]
yeah, fixed it for me too.
