### ISSUE TITLE
Typing error on release page (v20220924)

### ISSUE THREAD

**Issue by YukihoAA** [Nandaka/PixivUtil2#1171]
There is a typing error on contribution

my id is @YukihoAA  not @ yuki 

😂

**Comment by Nandaka** [comment]
updated :P
Somehow the Author name show up as Yuki in git log
![image](https://user-images.githubusercontent.com/836867/192098658-d4080c27-e276-49d6-9a37-c042db14fe48.png)

**Comment by YukihoAA** [comment]
Thanks you ><
