### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by Slyceth** [Nandaka/PixivUtil2#1172]
I get this error just by logging in: 

Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 488, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x03ACD7E8>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x029BFF68>)
Cannot Login!

I did make the account a short while ago.

**Comment by master117** [comment]
Getting the same error.

**Comment by Yurihellsin** [comment]
Not sure it's the same error but it keeps closing?

**Comment by Nandaka** [comment]
login related issue, please see #814
