### ISSUE TITLE
FANBOX: Filename too long causes Invalid Argument

### ISSUE THREAD

**Issue by shinji257** [Nandaka/PixivUtil2#1175]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? Release version
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

When the filename ends up being too long due to a really long title it causes Windows to throw error 22 (Invalid Argument) messages and it fails to continue.  I believe this is a return of an old bug from 2019 https://github.com/Nandaka/PixivUtil2/issues/525

### Steps to Reproduce

1. Run PixivUtil2
2. Choose F3 (specific post)
3. Enter post 2277564

Note that post is very much NSFW and require support to get.

**Expected behavior:** Filename either remove title or truncated

**Actual behavior:** Errors as logged.

**Log file:** 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9669355/pixivutil.log)

### Versions
PixivDownloader2 version 20220924

**Comment by Nandaka** [comment]
you can try to enable long filename/path support in win10
``https:// www.itprotoday.com/windows-10/enable-long-file-name-support-windows-10```

**Comment by Nandaka** [comment]
weird, it is working in when I try from python console.
Is your target drive formatted using NTFS? Long filename only supported if you are using NTFS, I think?
![image](https://user-images.githubusercontent.com/836867/192928461-488d0cba-8d99-41cc-80c8-9fc81800231a.png)
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L764

**Comment by Nandaka** [comment]
ok, it is kinda similar with my case, but the Z: drive is actually another win10 shared folder.

**Comment by shinji257** [comment]
Ok.  It works fine on a local NTFS formatted drive, but it won't copy to the network drive.

**Comment by shinji257** [comment]
So just a small update.  This is due to Linux path limitations since the SMB share is hosted there in the end.  Just to double check I had zipped the affected files up, uploaded to the server, then tried to unpack (via a shell -- not SMB) and same error.  The same issue may not present itself on a Windows based SMB share and is not a SMB issue.
