### ISSUE TITLE
Ignore or label tags by non-artist users

### ISSUE THREAD

**Issue by worsttested** [Nandaka/PixivUtil2#1180]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit")?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Does the script have a way to ignore or label "unlocked" tags added to images by users other than the artist? Since users can tag an image, many images have inaccurate or irrelevant tags added after the fact. I'm mostly interested in avoiding including those in the image info files, but I imagine it would also be useful to exclude them from the download-by-tag feature.

To be clear, I don't want to avoid any given tag entirely, just exclude unlocked instance of that tag from info files or metadata. The issue is whether a given tag was added/locked by the original artist for each image. Example tags below. I want to keep those first three "non-editable" tags, while leaving out the rest of that mess. Sometimes they're accurate, but often they're misleading, and sometimes they're complete garbage.

Is there a way to do this in the script as is? If not, is there any workaround I can apply myself?

![image](https://user-images.githubusercontent.com/116447972/197349042-751165a9-d63a-4460-8893-3f40993ecf03.png)

### Version

v20220924 running from terminal in Linux

**Comment by Nandaka** [comment]
> I'm mostly interested in avoiding including those in the image info files, 

Are you using the raw json or the .txt file? The raw json has `userId` attribute to differentiate the author.

> but I imagine it would also be useful to exclude them from the download-by-tag feature.

This one might not be possible, as the server doesn't differentiate the tags when searching.

**Comment by worsttested** [comment]
Ahh, you're correct, I had checked the info and basic json files, but didn't realized the raw json could differentiate. Perfect, I can use that to filter tags if I decide to be picky about it, but switching to the raw json solves my main problem. Appreciated!
