### ISSUE TITLE
[FANBOX] (<class 'KeyError'>, KeyError('coverImageUrl')

### ISSUE THREAD

**Issue by aksskl** [Nandaka/PixivUtil2#1182]
I've been running into a Fanbox error within the last six hours. Using f1 and f2 repeatedly reproduces the error. Downloading by f3 seems to work fine so far. In the pixivlog file provided below I first used f3 to demonstrate downloading a single post successfully, then using f2 on the same user which fails. 

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/9848668/pixivutil.log)

I tried running f2 on multiple Fanbox IDs but no luck yet.

While typing this issue out another user has also reported the same issue #1181

**Comment by Hecatom** [comment]
Something to take not is that downloading normal pixiv galleries work, so is only on the fanbox side that the error is happening

**Comment by Nandaka** [comment]
I think duplicated with #1181
