### ISSUE TITLE
Want to use venv but it's stored in .gitignore as a file not directory?

### ISSUE THREAD

**Issue by cglmrfreeman** [Nandaka/PixivUtil2#1184]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
I'm doing a fresh install of my operating system on a new drive and wanted to utilize Python3's `venv` to run PixivUtil2. While I could put the virtual environment anywhere, I noticed this:
https://github.com/Nandaka/PixivUtil2/blob/9faed1dd428b816b3ecac30b8806b638a6c2410b/.gitignore#L5

`venv` is in the ignore list as a file and not a directory? If that's the case, could I have clarification on what this ignore file actually is?

### Steps to Reproduce
N/A

**Expected behavior:** 
N/A

**Actual behavior:** 
N/A

**Log file:** 
N/A

### Versions
N/A

**Comment by cglmrfreeman** [comment]
Would docker be a preferred over `venv` in this case? :thinking:

**Comment by Nandaka** [comment]
hmm, I'm also not sure as it was added in https://github.com/Nandaka/PixivUtil2/pull/1015/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947 by @BassOfBass and I don't use virtual environment

**Comment by shinji257** [comment]
`.gitignore` is only used to determine files/folders that should not be added when submitting a commit to the git repository.  If you are wanting to use venv for running PixivUtil2 locally you can ignore that file as it won't apply in that case.

With that said....  I have not tried to do that (yet).  I run this on Windows and use the exe builds (and make my own when testing code).

**Comment by cglmrfreeman** [comment]
> `.gitignore` is only used to determine files/folders that should not be added when submitting a commit to the git repository. 

I am assuming when migrating from `demjson` to `demjson3`, python3's venv came in handy to make sure things worked right. What I would not understand is a file created named `venv`, but perhaps a folder where dependencies were installed named `venv` existed that they did not want uploaded, however that's not what the `.gitignore` is set up for in that case.

**Comment by Nandaka** [comment]
hmm, then it should be changed to `venv/*` instead?

**Comment by cglmrfreeman** [comment]
Perhaps it should be removed altogether, because in probably the only circumstance it was needed was in the use case by BassOfBass, in which anyone could create a `venv` outside the PixivUtil2 folder and use the scripts in it just fine. I was merely confused as it was set up as a folder.

**Comment by Nandaka** [comment]
not really, the venv folder should not be included into the main repo, right? If you remove it, the venv folder might accidentally added if someone use `git add .`. It should not affect your local repo.

**Comment by Hamuko** [comment]
Yeah, virtual environments should not be committed and it's a good practice to have some safeguards against it. [It's why the GitHub Python .gitignore includes it.](https://github.com/github/gitignore/blob/main/Python.gitignore#L126)

**Comment by shinji257** [comment]
With that in mind the venv entry should probably be replaced with this (taken from the previously mentioned link) in order to try and avoid venv from being committed in error.

```
# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/
```

**Comment by cglmrfreeman** [comment]
> not really, the venv folder should not be included into the main repo, right? If you remove it, the venv folder might accidentally added if someone use `git add .`. It should not affect your local repo.

The way it's currently setup, the .gitignore would only ignore venv if it was a file. As others are now pointing out, other .gitignores are properly safeguarding against these folders. I'd like to point out it has been lingering there for over a year without anyone noticing however, so I am doubting we, collectively as PixivUtil2 devs, are using venvs like this, lol.

**Comment by cglmrfreeman** [comment]
Done and done.
