### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by HellcatAisha** [Nandaka/PixivUtil2#119]
Not really an issue but, what happened to the [website](https://nandaka.wordpress.com/)? Looks like it got shut down for some ToS violation, which makes me worried about the actual projects here on GitHub.

**Comment by Nandaka** [comment]
I'm not sure, they said I create a backlink or whatever that violates the ToS, which is weird because I link only to GitHub and PayPal.

**Comment by kode54** [comment]
A backlink is when someone links back to your blog, not when you link out to something. They're basically telling you that you're being linked from places they don't like? Maybe ask them which backlink is violating their ToS, then tell them you're not responsible for people linking to you?

**Comment by Nandaka** [comment]
hmm, maybe. I'm asking them which post/comments causing this issue.

**Comment by Nandaka** [comment]
moved to http://nandaka.devnull.zone/
