### ISSUE TITLE
No retry on incompleted downloads?

### ISSUE THREAD

**Issue by mugi-jiichan** [Nandaka/PixivUtil2#1206]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I've noticed that PU2 seems to ignore the config.ini retry entries, so it doesn't retry to download an incompleted file. Instead, the *.pixiv file is simply deleted while download is continued with the next file on the list.

This occurs for me with all download modes, but I mainly use downloads through modes 1, 3, 5, 7, and 10.

I've attached config.ini and pixivutil2.log.

### Steps to Reproduce

1. Start download cue.
2. Have a short network timeout. (Pull the cable and put it back into the socket, or go to and undo flight mode for example)
3. [and so on...]

**Expected behavior:**
Retry download as specified in config.ini (in this case, 5 retries with a break of 15 seconds).

**Actual behavior:**
Incompleted download is deleted, PU2 continues with the next download.

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions

20221029 (cloned source to disk from master repository on Dec 8th to test #1191 )
[config.ini.txt](https://github.com/Nandaka/PixivUtil2/files/10218890/config.ini.txt)
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10218898/pixivutil.log)

**Comment by Nandaka** [comment]
weird, it does retry and download the image correctly.
![image](https://user-images.githubusercontent.com/836867/207759692-112e38ee-2269-4fb2-96a4-4d25c96824c0.png)
![image](https://user-images.githubusercontent.com/836867/207759736-3ec666ac-f562-4100-a84e-7d1d13eb0081.png)

**Comment by Nandaka** [comment]
hmm, I might found the cause due to #1201
need to recheck if the file successfully downloaded

**Comment by NewUserHa** [comment]
Does version 20221029 have this issue?

**Comment by Nandaka** [comment]
it is a bit of combination of and existing issue, somehow timeout error is skipping the retry
