### ISSUE TITLE
Error when i want to download using User_ID

### ISSUE THREAD

**Issue by animekazuto** [Nandaka/PixivUtil2#121]
`PixivDownloader2 version 20160513
https://nandaka.wordpress.com/tag/pixiv-downloader/
Reading C:\Users\Kazuto\Pictures\Pixiv\pixivutil20160513\config.ini ...
done.
using default DB Path: C:\Users\Kazuto\Pictures\Pixiv\pixivutil20160513\db.sqlite
Creating database... done.
Only process member where day last updated >= 7
Using Username: anime_kazuto
Trying to log with saved cookie
Cookie already expired/invalid.
Log in using secure form.
Logged in
new cookie value: <removed>
Writing config file... Backing up old config to config.ini.bak
done.
PixivDownloader2 version 20160513
https://nandaka.wordpress.com/tag/pixiv-downloader/
1. Download by member_id
2. Download by image_id
3. Download by tags
4. Download from list
5. Download from online user bookmark
6. Download from online image bookmark
7. Download from tags list
8. Download new illust from bookmark
9. Download by Title/Caption
10. Download by Tag and Member Id
11. Download Member Bookmark
12. Download by Group Id
------------------------
d. Manage database
e. Export online bookmark
m. Export online user bookmark
r. Reload config.ini
p. Print config.ini
x. Exit
Input: 1
Member ids: 1067404
Start Page (default=1): 1
End Page (default=0, 0 for no limit): 0
Processing Member Id: 1067404
Reading C:\Users\Kazuto\Pictures\Pixiv\pixivutil20160513\config.ini ...
done.
Page  1
Member Url: http://www.pixiv.net/member_illust.php?id=1067404&p=1
Traceback (most recent call last):
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
Error at process_member(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x03073C38>)
Dumping html to: Error page for member 1067404.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1850, in main
  File "PixivUtil2.py", line 1636, in main_loop
  File "PixivUtil2.py", line 1298, in menu_download_by_member_id
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.
`

**Comment by Nandaka** [comment]
It is working on my side. 
1. Try to delete the login information from config.ini, also ensure you can open the website. 
2. What is your language settings in the pixiv website?

**Comment by animekazuto** [comment]
my pixiv website language is English and...

this is my config.ini file
`[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
userobots = True
timeout = 60
retry = 3
retrywait = 5

[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = False

[IrfanView]
irfanviewpath = C:\Program Files\IrfanView
startirfanview = False
startirfanslide = False
createdownloadlists = False

[Settings]
filenameformat = %artist% (%member_id%)\%urlFilename% - %title%
filenamemangaformat = %artist% (%member_id%)\%urlFilename% - %title%
downloadlistdirectory = .
uselist = False
processfromdb = True
overwrite = False
tagsseparator = ,
daylastupdated = 7
rootdirectory = .
alwayscheckfilesize = False
checkupdatedlimit = 0
downloadavatar = True
createmangadir = False
usetagsasdir = False
useblacklisttags = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = False
datediff = 0
backupoldfile = False
writeugoirainfo = False
createugoira = False
deletezipfile = False
enableinfiniteloop = False
verifyimage = False
writeurlindescription = False
urlblacklistregex = 
urldumpfilename = url_list_%Y%m%d
dbpath = 

[Authentication]
username = anime_kazuto
password = 
cookie = 7487093_7d317618c59973e7f6cd18399742dac7
usessl = False
keepsignedin = 0

[Pixiv]
numberofpage = 0
r18mode = False
dateformat = 

`
whitch i can delete ?

**Comment by Nandaka** [comment]
remove the cookie value and set keepsignedin=True

**Comment by animekazuto** [comment]
Success
but when i try to download other page it come back again
`Member Url: http://www.pixiv.net/member_illust.php?id=1067404&p=2
Traceback (most recent call last):
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
Error at process_member(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x02F250D0>)
Dumping html to: Error page for member 1067404.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1850, in main
  File "PixivUtil2.py", line 1636, in main_loop
  File "PixivUtil2.py", line 1298, in menu_download_by_member_id
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.`

**Comment by Nandaka** [comment]
do you set keep signed in to True? Looks like pixiv keep on forgetting your login. Do you change your network?

**Comment by animekazuto** [comment]
i have change keep signed in to true... but when i open pixiv it change to "0" again

**Comment by Nandaka** [comment]
ah, sorry use value to 1.

**Comment by animekazuto** [comment]
error again -_-

`Member Url: http://www.pixiv.net/member_illust.php?id=1067404&p=11
Traceback (most recent call last):
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
Error at process_member(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x03011D28>)
Dumping html to: Error page for member 1067404.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1850, in main
  File "PixivUtil2.py", line 1636, in main_loop
  File "PixivUtil2.py", line 1298, in menu_download_by_member_id
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.`

**Comment by Nandaka** [comment]
even after setting ```keepsignedin = 1```? that's weird.

Are you using mobile networks? do you sometimes receive interstitial ads when browsing? I suspect something is replacing the pixiv website response with something. Can you upload Error page for member 1067404.html to pastebin?

**Comment by animekazuto** [comment]
yes im using mobile network, and sometime i receive interstitial ads too ... 
is my computer have virues

this is the eror member 1067404.html
`<!DOCTYPE HTML>
<html>
<head>
<noscript>
<meta http-equiv="refresh" content="0;URL=http://114.6.128.4/ads-request?t=3&amp;j=0&amp;i=180831459&amp;s=I4013146400956393099&amp;a=http://www.pixiv.net/member_illust.php%3fid%3d1067404%26p%3d9" />
</noscript>
<link href="http://114.6.128.4:8004/COMMON/css/ibn.css" rel="stylesheet" type="text/css" />
</head>
<body>
<script type="text/javascript">
		p={'t':'3', 'i':'180831459', 's':'I4013146400956393099'};
		d='';		
	</script>
<script type="text/javascript">
		var b=location;
		setTimeout(function(){
			if(typeof window.iframe=='undefined'){
				b.href=b.href;
			}
		},15000);
	</script>
<script src="http://114.6.128.4:8004/COMMON/js/ibnjs.v0.07.min.js"></script>
</body>
</html>`

**Comment by Nandaka** [comment]
that's the cause, cos your ISP replace the page with ads and causing the application to be confused (expecting the pixiv website).

And I cannot enforce the full https for the site, as it will always redirect to http version. 

Try to use vpn/socks proxy?

**Comment by animekazuto** [comment]
owh... ok 
i'll change my isp first 
thanks nandaka
