### ISSUE TITLE
loginUsingCookie fails with 403 Forbidden

### ISSUE THREAD

**Issue by KamenReader** [Nandaka/PixivUtil2#1210]
### Prerequisites

* [ x ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ x ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ x ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

***NOT A DUPLICATE ISSUE OF #814*** Since it appears the owner of the repository has disregarded #1209 as a duplicate issue that they do not intend to fix, I felt the need to clarify that the workaround itself is now broken.

### Steps to Reproduce

0. Change password again just to verify that isn't the problem again. (it isn't, so this step is optional)
1. Save cookies from browser into config.ini
2. Match user agent in config.ini to browser used
3. Attempt to start PixivUtil2

**Expected behavior:** Logging in succeeding

**Actual behavior:** It doesn't.  loginUsingCookie fails.

**Log file:**

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10253249/pixivutil.log)

**Comment by cocokakao** [comment]
still

**Comment by Osprey-Hawk** [comment]
I'm encountering the same issue.  I even cleared my cookies and tried putting in the new data with no luck.

![image](https://user-images.githubusercontent.com/45588123/208284838-662bf918-d5b7-4ce5-86ba-ebdc9f9b93e1.png)

**Comment by XetThe** [comment]
same issue here, i want to think they changed something in the backend
![image](https://user-images.githubusercontent.com/87451413/208285939-80853f3c-054d-440b-81de-363c60ef5769.png)

**Comment by baraghiffari** [comment]
I thought it's only me, i have similiar issue. Tried with and without vpn, changing dns, relogin and change the cookies again but no dice

**Comment by Terryble2** [comment]
This does seem to be a new issue that cannot be resolved on the user's end.

**Comment by smol-loli** [comment]
I have the exact same problem. Started around 2 days ago if i remember correctly

**Comment by mugi-jiichan** [comment]
Yet another "Same here" post from me. I'm also out cold for two days now on Manjaro Linux running the master after cloning to disk. :(

Followed https://github.com/Nandaka/PixivUtil2/wiki#pixiv-login-using-cookie which didn't work.
Followed also the other trick from #814 to change password and use the PHPSESSION cookie from the PW confirmation page - which didn't work either.

I can log in with any browser perfectly fine, but taking the credentials/PHPSESSION cookie into the config.ini won't do the trick anymore for me.

**Comment by NonaSuomi** [comment]
Another confirmation. Logged out, logged back in, even changed password. After updating settings.ini with the new password, session cookie, and useragent it still can't log in successfully.

**Comment by Wesley107772** [comment]
I identified the issue at https://github.com/Nandaka/PixivUtil2/issues/1209#issuecomment-1356844718.
