### ISSUE TITLE
Question about downloading Fanbox covers

### ISSUE THREAD

**Issue by MarqFJA87** [Nandaka/PixivUtil2#1213]
Does the downloadCoverWhenRestricted option require that the downloadCover one be set to True in order for the former to work? I've never been able to download a restricted post's cover without doing so, and that's a problem because an unrestricted Fanbox post's cover is AFAIK always a cropped version of one of the images contained within post, so I'm not interested in those.

**Comment by Nandaka** [comment]
yes, both flag need to be set to true.
![image](https://user-images.githubusercontent.com/836867/210209982-4cb0c418-fafc-4e2d-a69c-8d8e865c8f76.png)
