### ISSUE TITLE
Skipping Ai Tags working not properly

### ISSUE THREAD

**Issue by YukihoAA** [Nandaka/PixivUtil2#1219]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

if i set aiDisplayFilter = True, it just skips all images and shutdown

![image](https://user-images.githubusercontent.com/20253131/210398511-0e7d4400-fcda-45a3-9f5e-9454d0fb05a5.png)

**Log file:**

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10338188/pixivutil.log)

**Comment by Nandaka** [comment]
woopsie, forgot to add the check condition. should be fixed in latest commit
