### ISSUE TITLE
Error when trying to download via member ID

### ISSUE THREAD

**Issue by Aaeeschylus** [Nandaka/PixivUtil2#122]
Here is the link to what shows up in the pixivutil.log

http://pastebin.com/qxPJQWYC

**Comment by Nandaka** [comment]
Looks like the login failed, also can you upload Error page for member 119199.html to pastebin?

Check your username/password in config.ini.

**Comment by Aaeeschylus** [comment]
The username/password in config.ini is correct.

Here is the pastebin of the file. http://pastebin.com/4Vsk7HgY

Attached is a zip with the file in it (if it worked)

[Error page for member 119199.zip](https://github.com/Nandaka/PixivUtil2/files/288137/Error.page.for.member.119199.zip)

**Comment by Nandaka** [comment]
For some reason, the logon is failed, it should show `Logging in, return url: http://www.pixiv.net/` when login is successful. The uploaded page shows it (it is the login page).

I just tried with my client. Double check your username/password. If not successful, login in your browser and copy the cookie value (refer to readme.txt: Q3: Error at process_image(): (<type 'exceptions.AttributeError'>, )

**Comment by Aaeeschylus** [comment]
ooooh, i figured out the problem. Because in the readme.txt Q3 it says to login via firefox, i had to log in without remember my password/etc. It turns out i was writing my nickname instead of my email as the username. Thanks for the help!!!
