### ISSUE TITLE
Strange behavior after upgrade

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/PixivUtil2#1220]
Upgraded to v20230102 after not touching it for a long time.

Noticed the following issues:
- During the download it tries to access `C:\Program Files\Common Files\SSL\cert.pem` which doesn't exist.
- It spams the log with `
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Windows\\Temp\\_MEI
70242\\base_library.zip\\.\\Downloaded_on_2023-01-04.txt'
` - the `_MEI 70242` folder exists but `Downloaded_on_2023-01-04.txt` is nowhere to be found, and I want it in the app folder, not in %TEMP%.

**Comment by Nandaka** [comment]
> C:\Program Files\Common Files\SSL\cert.pem

updated how it resolve the cacert.pem

> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Windows\\Temp\\_MEI 70242\\base_library.zip\\.\\Downloaded_on_2023-01-04.txt'

I think you can to set the path using `downloadListDirectory` in `config.ini`

**Comment by Wryyyong** [comment]
> I think you can to set the path using `downloadListDirectory` in `config.ini`

```
downloadListDirectory = .\Root
```
```
Reading D:\Desktop\Other\PixivUtil\config.ini ...
Configuration loaded.
Traceback (most recent call last):
  File "PixivUtil2.py", line 1772, in <module>
  File "PixivUtil2.py", line 1645, in main
  File "os.py", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\AppData\\Local\\Temp\\_MEI109402\\base_library.zip\\./Root'
[12528] Failed to execute script 'PixivUtil2' due to unhandled exception!
```

**Comment by Nandaka** [comment]
use absolute path?

**Comment by Wryyyong** [comment]
> use absolute path?

Absolute path works, but it shouldn't be a requirement

**Comment by Nandaka** [comment]
well it is a side effect of pyinstaller as py2exe doesn't work (somehow it always return sqlite3 error when loading), else you need to run from source code.
