### ISSUE TITLE
FFMPEG error Ugoira

### ISSUE THREAD

**Issue by momoe** [Nandaka/PixivUtil2#1224]
Updated from Oct'22 version to latest and getting FFMPEG error while trying to convert ugoira... 

`[20 of 149] Processing Image Id: xxxxxxxxx
Title     : 催眠術【日焼け跡】
Tags      : R-18, うごイラ, ポケモン人間絵, マリィ(トレーナー), ユウリ(トレーナー), 催眠, スリーパー, 日焼け跡, 全裸
Date      : 2022-09-30 15:01:00+00:00
Mode      : ugoira_view
Bookmarks : 7935
[1/1] Image URL : https://i.pximg.net/img-zip-ugoira/img/2022/10/01/00/01/37/xxxxxxxxxx_ugoira1920x1080.zip
[1/1] Filename  : F:\Downloads\PixivUtil2\\xxxxxxxxxx_ugoira1920x1080 - 催眠術【日焼け跡】.zip
[━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━] 2.32 MiB            Completed in 5.003739s (474.27 KiB/s)
 Download done ==> F:\Downloads\PixivUtil2\\xxxxxxxxxx_ugoira1920x1080 - 催眠術【日焼け跡】.zip

Creating ugoira archive => F:\Downloads\PixivUtil2\\xxxxxxxxxx_ugoira1920x1080 - 催眠術【日焼け跡】.ugoira
Processing ugoira to webm...
Start encoding F:\Downloads\PixivUtil2\\xxxxxxxxxx_ugoira1920x1080 - 催眠術【日焼け跡】.webm
C:\Users\Momoe\AppData\Local\Temp\convert_ugoira2ukeoujj\i.ffconcat: No such file or directory
Failed when converting image using ffmpeg -y -safe 0 -i C:\Users\Momoe\AppData\Local\Temp\convert_ugoira2ukeoujj\i.ffconcat -c:v libvpx-vp9 -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p C:\Users\Momoe\AppData\Local\Temp\convert_ugoira2ukeoujj\temp.webm ==> ffmpeg return exit code=1, expected to return 0.

Stuff happened, trying again after 2 second (1)
Traceback (most recent call last):
  File "PixivArtistHandler.py", line 135, in process_member
  File "PixivImageHandler.py", line 359, in process_image
  File "PixivDownloadHandler.py", line 424, in handle_ugoira
  File "PixivHelper.py", line 1030, in ugoira2webm
  File "PixivHelper.py", line 1102, in convert_ugoira
PixivException.PixivException: PixivException(2007 Failed when converting image using ffmpeg -y -safe 0 -i C:\Users\Momoe\AppData\Local\Temp\convert_ugoira2ukeoujj\i.ffconcat -c:v libvpx-vp9 -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p C:\Users\Momoe\AppData\Local\Temp\convert_ugoira2ukeoujj\temp.webm ==> ffmpeg return exit code=1, expected to return 0., hasDumpPage=N)
Error at process_member(): (<class 'PixivException.PixivException'>, PixivException('Failed when converting image using ffmpeg -y -safe 0 -i C:\\Users\\Momoe\\AppData\\Local\\Temp\\convert_ugoira2ukeoujj\\i.ffconcat -c:v libvpx-vp9 -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p C:\\Users\\Momoe\\AppData\\Local\\Temp\\convert_ugoira2ukeoujj\\temp.webm ==> ffmpeg return exit code=1, expected to return 0.'), <traceback object at 0x000001F23BDCA400>) Member Id: 26452890
2 of 2s.`

**Comment by anon1593** [comment]
Having this issue as well.
Just updated to latest ffmpeg, 2023-02-27-git-891ed24f77-full_build
Processing ugoira to webm...
Start encoding C:\Users\Staranon\Pictures\gifs\04\うごイラ\未来みるく (10559523)\92644742_ugoira1920x1080 - セラさんと正常位えっち.webm
ffmpeg version 2023-02-27-git-891ed24f77-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      58.  3.100 / 58.  3.100
libavcodec     60.  5.100 / 60.  5.100
libavformat    60.  4.100 / 60.  4.100
libavdevice    60.  2.100 / 60.  2.100
libavfilter     9.  4.100 /  9.  4.100
libswscale      7.  2.100 /  7.  2.100
libswresample   4. 11.100 /  4. 11.100
libpostproc    57.  2.100 / 57.  2.100
-vsync is deprecated. Use -fps_mode
Passing a number to -vsync is deprecated, use a string argument as described in the manual.
Input #0, concat, from 'C:\Users\Staranon\AppData\Local\Temp\convert_ugoiraqkepurmv\i.ffconcat':
Duration: N/A, start: 0.000000, bitrate: N/A
Stream #0:0: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 384x400 [SAR 1:1 DAR 24:25], 25 fps, 25 tbr, 25 tbn
[vost#0:0/libvpx-vp9 @ 000001c874d7e7c0] One of -r/-fpsmax was specified together a non-CFR -vsync/-fps_mode. This is contradictory.
Failed when converting image using ffmpeg -y -safe 0 -i C:\Users\Staranon\AppData\Local\Temp\convert_ugoiraqkepurmv\i.ffconcat -c:v libvpx-vp9 -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p C:\Users\Staranon\AppData\Local\Temp\convert_ugoiraqkepurmv\temp.webm ==> ffmpeg return exit code=1, expected to return 0.

Error at process_tags() at page 1: (<class 'PixivException.PixivException'>, PixivException('Failed when converting image using ffmpeg -y -safe 0 -i C:\\Users\\Staranon\\AppData\\Local\\Temp\\convert_ugoiraqkepurmv\\i.ffconcat -c:v libvpx-vp9 -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p C:\\Users\\Staranon\\AppData\\Local\\Temp\\convert_ugoiraqkepurmv\\temp.webm ==> ffmpeg return exit code=1, expected to return 0.'), <traceback object at 0x000001761CFE1640>)
Dumping html to: Error page for search tags %E3%81%86%E3%81%94%E3%82%A4%E3%83%A9 at page 1.html
Failed when converting image using ffmpeg -y -safe 0 -i C:\Users\Staranon\AppData\Local\Temp\convert_ugoiraqkepurmv\i.ffconcat -c:v libvpx-vp9 -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p C:\Users\Staranon\AppData\Local\Temp\convert_ugoiraqkepurmv\temp.webm ==> ffmpeg return exit code=1, expected to return 0.
press enter to exit.

new error message after ffmpeg update
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10845890/pixivutil.log)
was getting error from above on older ffmpeg
seems to occur only on older gifs.

**Comment by Nandaka** [comment]
Try with older/stable version?

Like @anon1593 said, most likely a ffmpeg issue, as I also encounter no issue with that image id.

fyi, I'm using `ffmpeg version 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 12.1.0 (Rev2, Built by MSYS2 project)`

**Comment by Butterfly-Dragon** [comment]
thanks for the info. i'll be trying the october 31st build and the november 30 build

**Comment by Butterfly-Dragon** [comment]
I tried deleting both the ugoira and the zip file for good measure but i keep getting the same errors.

The version of ffmpeg i tried are the two above.

Microsoft Windows [Version 10.0.19045.2673]

Python 3.10 (do not think it is important since your package seems to be self-contained, but i never tried running your package without python as i need python for other stuff anyway)

**Comment by Nandaka** [comment]
fyi, this is the exact ffmpeg that I use https://www.mediafire.com/file/5eatd30cpmhn3ev/ffmpeg.zip/file

**Comment by Butterfly-Dragon** [comment]
> fyi, this is the exact ffmpeg that I use https://www.mediafire.com/file/5eatd30cpmhn3ev/ffmpeg.zip/file

let me try that... nope.

```
Member_id: 59841681 completed: last image_id: 84811435
32/48   66.666667 %
Processing Member Id: 27635062
Page 1 of 0
Member Url    : https://www.pixiv.net/ajax/user/27635062/profile/all
Member Name   : Nautilic
Member Avatar : https://i.pximg.net/user-profile/img/2021/01/19/20/45/48/20032811_2695392fe08624ab5839612643b5a9f7.png
Member Token  : user_tzvv4858
Member Backgrd: https://i.pximg.net/c/1920x960_80_a2_g5/background/img/2020/12/12/02/36/19/27635062_72b4a1b54880db0042cbc93c1d6292e2.png
Processing images from 1 to 108 of 108
[1 of 108] Processing Image Id: 105971878
Title     : Dark Samus Animation 2023
Tags      : Ugoira, サムス・アラン, rubber, suit, Samus, Metroid, zero, samus, Dark
Date      : 2023-03-06 11:08:00+01:00
Mode      : ugoira_view
Bookmarks : 547
[1/1] Image URL : https://i.pximg.net/img-zip-ugoira/img/2023/03/06/19/08/01/105971878_ugoira1920x1080.zip
[1/1] Filename  : D:\Downloads\Downloader\Manga\Files\Nautilic (27635062) - 105971878_ugoira1920x1080 - Dark Samus Animation 2023.zip
[━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━] 2.39 MiB            Completed in 4.134587s (591.88 KiB/s)
 Image verified.
 Download done ==> D:\Downloads\Downloader\Manga\Files\Nautilic (27635062) - 105971878_ugoira1920x1080 - Dark Samus Animation 2023.zip

Creating ugoira archive => D:\Downloads\Downloader\Manga\Files\Nautilic (27635062) - 105971878_ugoira1920x1080 - Dark Samus Animation 2023.ugoira
Processing ugoira to animated gif...
Start encoding D:\Downloads\Downloader\Manga\Files\Nautilic (27635062) - 105971878_ugoira1920x1080 - Dark Samus Animation 2023.gif
Stream #0:0: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 300x169 [SAR 1:1 DAR 300:169], 25 fps, 25 tbr, 25 tbn
[AVFilterGraph @ 0000017e9216c000] No such filter: '"'
Failed when converting image using ffmpeg.exe -y -safe 0 -i C:\Users\simon\AppData\Local\Temp\convert_ugoirahpau3r0e\i.ffconcat -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" C:\Users\simon\AppData\Local\Temp\convert_ugoirahpau3r0e\temp.gif ==> ffmpeg return exit code=1, expected to return 0.

Stuff happened, trying again after 2 second (1)
Traceback (most recent call last):
  File "PixivArtistHandler.py", line 135, in process_member
  File "PixivImageHandler.py", line 359, in process_image
  File "PixivDownloadHandler.py", line 410, in handle_ugoira
  File "PixivHelper.py", line 990, in ugoira2gif
  File "PixivHelper.py", line 1102, in convert_ugoira
PixivException.PixivException: PixivException(2007 Failed when converting image using ffmpeg.exe -y -safe 0 -i C:\Users\simon\AppData\Local\Temp\convert_ugoirahpau3r0e\i.ffconcat -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" C:\Users\simon\AppData\Local\Temp\convert_ugoirahpau3r0e\temp.gif ==> ffmpeg return exit code=1, expected to return 0., hasDumpPage=N)
Error at process_member(): (<class 'PixivException.PixivException'>, PixivException('Failed when converting image using ffmpeg.exe -y -safe 0 -i C:\\Users\\simon\\AppData\\Local\\Temp\\convert_ugoirahpau3r0e\\i.ffconcat -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" C:\\Users\\simon\\AppData\\Local\\Temp\\convert_ugoirahpau3r0e\\temp.gif ==> ffmpeg return exit code=1, expected to return 0.'), <traceback object at 0x000001509439F040>) Member Id: 27635062
2 of 2s.
```

i made sure to delete the ugoira and the zip filre beforehand in case it was something related to the file themselves.

![image](https://user-images.githubusercontent.com/33538906/227767684-53f78473-ecfc-4d12-8538-9897ffed12b1.png)

**Comment by Nandaka** [comment]
Try update your gifParam? this is the one I used.

```
[FFmpeg]
ffmpeg = .\ffmpeg.exe
ffmpegCodec = libvpx-vp9
ffmpegExt = mp4
ffmpegParam = -lossless 0 -crf 15 -b 0 -fps_mode passthrough
mkvCodec = copy
mkvParam = 
webpCodec = libwebp
webpParam = -lossless 0 -compression_level 5 -quality 100 -loop 0 -fps_mode passthrough
gifParam = -filter_complex [0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle -fps_mode passthrough
apngParam = -plays 0 -fps_mode passthrough
verboseOutput = False
```

**Comment by Butterfly-Dragon** [comment]
I never touched mine ever since i started using your program; I have:
```
[FFmpeg]
ffmpeg = ffmpeg.exe
ffmpegCodec = libvpx-vp9
ffmpegExt = webm
ffmpegParam = -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p
mkvCodec = copy
mkvParam = 
webpCodec = libwebp
webpParam = -lossless 0 -q:v 90 -loop 0 -vsync 2 -r 999
gifParam = -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle"
apngParam = -vf "setpts=PTS-STARTPTS,hqdn3d=1.5:1.5:6:6" -plays 0
verboseOutput = False
```
will try those settings immediately

**Comment by Butterfly-Dragon** [comment]
yep. that did it. Apparently one should update the FFMPEG setting every now and then. Makes sense, these were at least 4 y.o. 😂
```
Member_id: 59841681 completed: last image_id: 84811435
32/48   66.666667 %
Processing Member Id: 27635062
Page 1 of 0
Member Url    : https://www.pixiv.net/ajax/user/27635062/profile/all
Member Name   : Nautilic
Member Avatar : https://i.pximg.net/user-profile/img/2021/01/19/20/45/48/20032811_2695392fe08624ab5839612643b5a9f7.png
Member Token  : user_tzvv4858
Member Backgrd: https://i.pximg.net/c/1920x960_80_a2_g5/background/img/2020/12/12/02/36/19/27635062_72b4a1b54880db0042cbc93c1d6292e2.png
Processing images from 1 to 108 of 108
[1 of 108] Processing Image Id: 105971878
Title     : Dark Samus Animation 2023
Tags      : Ugoira, サムス・アラン, rubber, suit, Samus, Metroid, zero, samus, Dark
Date      : 2023-03-06 11:08:00+01:00
Mode      : ugoira_view
Bookmarks : 548
[1/1] Image URL : https://i.pximg.net/img-zip-ugoira/img/2023/03/06/19/08/01/105971878_ugoira1920x1080.zip
[1/1] Filename  : D:\Downloads\Downloader\Manga\Files\Nautilic (27635062) - 105971878_ugoira1920x1080 - Dark Samus Animation 2023.zip
Local file exists: D:\Downloads\Downloader\Manga\Files\Nautilic (27635062) - 105971878_ugoira1920x1080 - Dark Samus Animation 2023.zip

Processing ugoira to animated gif...
Start encoding D:\Downloads\Downloader\Manga\Files\Nautilic (27635062) - 105971878_ugoira1920x1080 - Dark Samus Animation 2023.gif
Stream #0:0: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 300x169 [SAR 1:1 DAR 300:169], 25 fps, 25 tbr, 25 tbn
Stream #0:0 (mjpeg) -> split:default
paletteuse:default -> Stream #0:0 (gif)
Stream #0:0: Video: gif, pal8(pc, gbr/unknown/unknown, progressive), 300x169 [SAR 1:1 DAR 300:169], q=2-31, 200 kb/s, 25 fps, 100 tbn
video:4543kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000430%
- Done with status = 0

Deleting zip file => D:\Downloads\Downloader\Manga\Files\Nautilic (27635062) - 105971878_ugoira1920x1080 - Dark Samus Animation 2023.zip
Deleting ugoira file => D:\Downloads\Downloader\Manga\Files\Nautilic (27635062) - 105971878_ugoira1920x1080 - Dark Samus Animation 2023.ugoira
Wait for 0.175s
```
