### ISSUE TITLE
Cannot get past "Using Username: ███████"

### ISSUE THREAD

**Issue by Ikkoru** [Nandaka/PixivUtil2#1227]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Haven't used the program in ages. DLed new release and this is what I get.

![Untitled](https://user-images.githubusercontent.com/58905922/214655412-35f46f9b-c127-4246-a57e-471b9c07546b.png)

I'm probably stupid, but pls help. How do I use the new version?

**Comment by PatrickL546** [comment]
Use cookie login. It was disabled in this commit https://github.com/Nandaka/PixivUtil2/commit/b65b3f62d78f5a7b805de95f946ee581f4291d42 if i was reading that correctly

**Comment by Ikkoru** [comment]
Thanks greatly!
