### ISSUE TITLE
Unknown Error: The read operation timed out

### ISSUE THREAD

**Issue by intelstellar** [Nandaka/PixivUtil2#1228]
### Prerequisites

* Yes
* Yes
* Yes

### Description

when I tried using the "Download from bookmarked images" feature to download all my favorite works, it started importing bookmarks from my pixiv account to a certain page that I had pre-filled and suddenly it stopped working and gave an error like the image below, sorry I used Google translate because my English is not very good, thanks for reading!

**Expected behavior:** download all my favorite works 

**Actual behavior:** it not worked

**Log file:**: 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10529171/pixivutil.log)

### Versions: v20230105

![image](https://user-images.githubusercontent.com/85721047/215307658-cfc2a780-2149-445d-983e-ff8f01162212.png)

**Comment by Nandaka** [comment]
similar like #1229, most likely the server reject the connection for whatever reason
