### ISSUE TITLE
URLError(TimeoutError(10060) on Pixiv and Fanbox

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#1229]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Don't know if it's just me, but I'm getting this error really fast on the default settings. Opened the sites on browser, I get error timed out as well. Could this be a change? or just me?
After waiting, it runs normally. Really hope they didn't decrease rate limit it again.

![image](https://user-images.githubusercontent.com/75874561/215739453-39dc7f09-3882-4259-9530-0e0df39a574f.png)
![image](https://user-images.githubusercontent.com/75874561/215739626-8e951430-9308-4bd4-8988-2baeb02f8dfa.png)

### Steps to Reproduce

1. download using member list
2. wait.

**Comment by Nandaka** [comment]
can you open the url listed in the error message using browser? Should have something like this.
![image](https://user-images.githubusercontent.com/836867/215928135-d8c865ac-c5cf-42bb-85ce-91686f0ec660.png)

**Comment by PatrickL546** [comment]
![image](https://user-images.githubusercontent.com/75874561/215994940-e6ab8a84-a76e-4cd6-9935-eff8cdc28a13.png)
it works now, but when i'm downloading after a while, I started getting errors

**Comment by Nandaka** [comment]
I suspect Pixiv Server temp-ban you IP Address. You might need to set `downloadDelay = 5` in config.ini

**Comment by PatrickL546** [comment]
I've tried it again and as of now, haven't gotten an error. If I get it again, I'll try another IP and another account. Also already using `downloadDelay = 5`

**Comment by PatrickL546** [comment]
> I suspect Pixiv Server temp-ban you IP Address. 

Might be the case since I haven't had an error for hours.

**Comment by Revemohl** [comment]
This issue has been plaguing me for a while as well and it's always annoying how the program locks up when it happens. Would it be possible to add a setting for automatically retrying to continue downloading your lists after some time has passed instead of waiting for the user to push either Enter or Ctrl+C?

**Comment by PatrickL546** [comment]
> This issue has been plaguing me for a while as well and it's always annoying how the program locks up when it happens. Would it be possible to add a setting for automatically retrying to continue downloading your lists after some time has passed instead of waiting for the user to push either Enter or Ctrl+C?

@Revemohl The thing is, it was like that before this [Handle OSErrors in a cleaner way](https://github.com/Nandaka/PixivUtil2/issues/1187)
 Implementation https://github.com/Nandaka/PixivUtil2/commit/e2db2b3574790c1f8d865277b78700fdee390ab0
 
 I just created a macro to press enter for me

**Comment by PatrickL546** [comment]
@Nandaka Could it be listed as UNSAFE option in config to disable it?
In my experience, it happens when the read operation timed out when my connection with Pixiv was blocked and the download didn't continue. The default random ~5 seconds between downloads still sometimes gets me blocked from Pixiv and when the download doesn't finish, I get the read operation timed out and have to press enter to continue.

**Comment by hehequya** [comment]
@PatrickL546 feel so bad, i still have error 429 when set downloadDelay = 5 or more(25), how to fix that

**Comment by PatrickL546** [comment]
> @PatrickL546 feel so bad, i still have error 429 when set downloadDelay = 5 or more(25), how to fix that

Can't really fix that since it's a server-side thing, I just deal with it and retry. A longer delay might help but I don't want it to be too long.

**Comment by Revemohl** [comment]
Wild idea here, but maybe if this is being caused by some sort of temporary ban from Pixiv's side, could a config setting to determine the minimum amount of time between downloads help? Given how as things have always been, even if you set downloadDelay to something like 60, the program will still generate something between 0 and that number, potentially hitting lows too often and triggering the temp-ban. 

So for example, if it's happening often to you then you could try downloadDelay = 20 and downloadDelayMin = 5 to see if it still happens.
