### ISSUE TITLE
how to download tags from pixiv?

### ISSUE THREAD

**Issue by naruhina2016** [Nandaka/PixivUtil2#123]
as the title says how can i download the tags from pixiv
and how does this program works?
please tell me...:(

**Comment by Nandaka** [comment]
no such feature, you cannot download tags from pixiv.

Unless you thinking download *by* tags.

1. Download the archive from the release page.
2. Check the readme.txt.
3. Key in your pixiv username/password.
4. follow the instruction in the screen.
