### ISSUE TITLE
i cant log in

### ISSUE THREAD

**Issue by classicalokaku** [Nandaka/PixivUtil2#1232]
### Prerequisites

* [yes] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [yes] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [yes] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

i cant log in

### Steps to Reproduce

enter username
enter password
press enter to exit

**Expected behavior:** [What you expected to happen]
log in

**Actual behavior:** [What actually happened]
press enter to exit.
![Screenshot 2023-02-07 004123](https://user-images.githubusercontent.com/124663496/217182128-ad9b9f6d-0cf2-49e2-9a33-d2b394f69a6d.png)

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]
[changelog.txt](https://github.com/Nandaka/PixivUtil2/files/10672648/changelog.txt)

### Version
newest

note: i have put my username and password into the config file in hopes that it would work. it did not

**Comment by PatrickL546** [comment]
Same as https://github.com/Nandaka/PixivUtil2/issues/1227. Username login doesn't work now. Use cookie login!

**Comment by Nandaka** [comment]
please refer to https://github.com/Nandaka/PixivUtil2/issues/1239
