### ISSUE TITLE
Fanbox Error

### ISSUE THREAD

**Issue by gnarf1975** [Nandaka/PixivUtil2#1233]
F2 Download by Artist ID
 
Error at download_image(): Cannot save https://downloads.fanbox.cc/images/post/XXXXX/XXXXXXXXXXX to D:\pixivutil\FANBOX XXXX (XXXX)\XXXXXXXXXXXX - XXXXXXXXX・11枚.png: (<class 'TimeoutError'>, TimeoutError('The read operation timed out'), <traceback object at 0x000001AD02397D00>)
Press enter to continue or Ctrl+C to abort.

Or just a "checking" and nothing else happens

The problem appears after downloading some images.

Is the problem with Pixiv?
The X's are just placeholders. It's nobody's business what I download.

**Comment by PatrickL546** [comment]
Probably same as https://github.com/Nandaka/PixivUtil2/issues/1228 and my error https://github.com/Nandaka/PixivUtil2/issues/1229. Sketch, Fanbox, Pixiv are getting timed outs for some reason. Serer side changes most likely
