### ISSUE TITLE
PixivUtil2 exits as soon as log in.

### ISSUE THREAD

**Issue by Schezuk** [Nandaka/PixivUtil2#1237]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

In interactive mode after logging in PixivUtil2 quits immediately before offering a chance to submit anything.

### Steps to Reproduce

1. Click on `PixivUtil2.exe`

**Expected behavior:** [What you expected to happen]

Asking what I want to download as the image shows.

![](https://user-images.githubusercontent.com/836867/183617442-1bc4ab26-3c65-4b87-9dc2-d4e6936235e6.png)

**Actual behavior:** [What actually happened]
```
┌──────────────────────────────────────────────────────────┐
│ PixivDownloader2 version 20230105                        │
│ https://github.com/Nandaka/PixivUtil2/releases           │
│ Donate at https://bit.ly/PixivUtilDonation               │
└──────────────────────────────────────────────────────────┘
Reading D:\pixivutil202305\config.ini ...
Configuration loaded.
Using default DB Path: D:\pixivutil202305\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Username ? me@mymailbox.com
Password ?
********press enter to exit.

```

Tried using console mode `PixivUtil2.exe -s 1 some_member_id` but failed.

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

```
2023-02-24 17:32:11,384 - PixivUtil20230105 - INFO - ###############################################################
2023-02-24 17:32:11,384 - PixivUtil20230105 - INFO - Starting with argument: [D:\pixivutil202305\PixivUtil2.exe].
2023-02-24 17:32:11,385 - PixivUtil20230105 - INFO - Setting log level to: DEBUG
2023-02-24 17:32:11,386 - PixivUtil20230105 - INFO - No default cookie jar available, creating... 
2023-02-24 17:32:11,388 - PixivUtil20230105 - INFO - Using Proxy: http://127.0.0.1:1080
2023-02-24 17:32:12,597 - PixivUtil20230105 - INFO - Using default DB Path: D:\pixivutil202305\db.sqlite
2023-02-24 17:32:12,600 - PixivUtil20230105 - INFO - Only process members where the last update is >= 7 days ago

```
### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by PatrickL546** [comment]
Same as https://github.com/Nandaka/PixivUtil2/issues/1227, please see it

**Comment by Schezuk** [comment]
> Same as #1227, use cookie login

No luck. It quit the same way.

**Comment by PatrickL546** [comment]
Maybe it's the proxy? also try using a new config.ini and use cookie login and see if you logs in.

**Comment by Nandaka** [comment]
Please refer to this: https://github.com/Nandaka/PixivUtil2/issues/1239
