### ISSUE TITLE
[Question] Fanbox updates

### ISSUE THREAD

**Issue by skulkexpert** [Nandaka/PixivUtil2#1238]
Does PixivUtil update fanbox posts that have been changed? If an image or an attachment has been added or changed?

Here is my config:
```
[FANBOX]
filenameFormatFanboxCover = FANBOX %artist% (%member_id%)\%urlFilename% - %title%
filenameFormatFanboxContent = FANBOX %artist% (%member_id%)\%urlFilename% - %title%
filenameFormatFanboxInfo = FANBOX %artist% (%member_id%)\%urlFilename% - %title%
writeHtml = True
minTextLengthForNonArticle = -1
minImageCountForNonArticle = -1
useAbsolutePathsInHtml = False
downloadCoverWhenRestricted = False
downloadCover = True
checkDBProcessHistory = True
listPathFanbox = listfanbox.txt
```
How reliable is `checkDBProcessHistory = True`? Should I set this to false if I want to ensure that no change is missed?

Another question: is it possible to output JSON metadata files for Fanbox posts like it is for normal pixiv posts?

**Comment by Nandaka** [comment]
![image](https://user-images.githubusercontent.com/836867/227749434-fc602ff2-a55b-4855-b235-559db218ff56.png)

should be quite reliable as long the update date is changed (which managed from fanbox server).

**Comment by Nandaka** [comment]
> is it possible to output JSON metadata files for Fanbox posts like it is for normal pixiv posts?

enhancement required, better post as separate issue? also accepting pull request.

maybe add the logic to save here:
![image](https://user-images.githubusercontent.com/836867/227749522-7dd01cf7-9ae3-4a79-84c1-303d01f7798f.png)

and save the jsPost to a file if enabled.
![image](https://user-images.githubusercontent.com/836867/227749547-06522e44-14a5-4649-ae62-90d70f20ad29.png)
