### ISSUE TITLE
returns error.

### ISSUE THREAD

**Issue by imjh11** [Nandaka/PixivUtil2#124]
returns error  ' 'ascii' codec can't encode character u'\ub144' in position 4: ordinal not in range(128)'.

seems to be language problem.

**Comment by Nandaka** [comment]
always return error? please give me more details (e.g. member id/image id/ stack trace).

Also, try to set the site language to English/Japanese and Language for non-unicode programs to Japanese in Control Panel->Regional Settings

**Comment by benidunt** [comment]
I'm having same error, too. 
For me, every attempt (trying different member_id/illust_id/tag search etc.) was giving me same 'ascii' codec can't encode character u'\ub144' in position 4: ordinal not in range(128)' error message.
I tried to set site language to English/Japanese and Language for non-unicode programs to Japanese in Control Panel -> Regional Settings but it did not work.

**Comment by Nandaka** [comment]
Try to delete the cookie value from config.ini after you change the language and try again?

**Comment by benidunt** [comment]
Sorry for the late response.
Straight to the point, deleting cookie value from config.ini actually worked, so it is downloading images from site well.
I setted site to **English** and **Language for non-unicode programs** to **Japanese** in _Control Panel -> Regional Settings_
