### ISSUE TITLE
Can't Logijnh

### ISSUE THREAD

**Issue by Hecatom** [Nandaka/PixivUtil2#1240]
### Prerequisites

* [Y ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Launch executable
2. Fail

**Expected behavior:** 
Login Noirmally

**Actual behavior:** 

Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x2a6c6899000 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x000002A6C28FED00>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 347, in loginUsingCookie
  File "PixivBrowserFactory.py", line 207, in open_with_retry
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by PatrickL546** [comment]
dupe with https://github.com/Nandaka/PixivUtil2/issues/1239

Also can confirm on my end the issue. HTTP Error 403: Forbidden

**Comment by Nandaka** [comment]
Some have success with https://github.com/Nandaka/PixivUtil2/issues/1241#issuecomment-1450739469
