### ISSUE TITLE
Cannot Login! 

### ISSUE THREAD

**Issue by gnarf1975** [Nandaka/PixivUtil2#1241]
Reading D:\pixivutil\config.ini ...
Configuration loaded.
Using default DB Path: D:\pixivutil\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: XXXXXX
Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x119cc0735b0 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x00000119CA904F80>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 347, in loginUsingCookie
  File "PixivBrowserFactory.py", line 207, in open_with_retry
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!
press enter to exit.

**Comment by Uraratan** [comment]
i got same probnlem, i also tried on a other windows pc, i also did a clean install of pixivuntil2 but same error

**Comment by shuuichilmc** [comment]
same problem here

Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x1be8fcc08b0 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x000001BE8E5C6A00>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 347, in loginUsingCookie
    self.clearCookie()
  File "PixivBrowserFactory.py", line 207, in open_with_retry
    while True:
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!

**Comment by Nanoka** [comment]
@gnarf1975 please check my comment at https://github.com/Nandaka/PixivUtil2/issues/1239#issuecomment-1448594330 and if that still doesn't work, mind sharing your config.ini? with the authentication removed of course

other people check https://github.com/Nandaka/PixivUtil2/issues/1239#issuecomment-1447705838 it may help until this is fixed

**Comment by gnarf1975** [comment]
> @gnarf1975 please check my comment at [#1239 (comment)](https://github.com/Nandaka/PixivUtil2/issues/1239#issuecomment-1448594330) and if that still doesn't work, mind sharing your config.ini? with the authentication removed of course
> 
> other people check [#1239 (comment)](https://github.com/Nandaka/PixivUtil2/issues/1239#issuecomment-1447705838) it may help until this is fixed
I only changed these settings. Now it seems to be working again.

[Network]
useProxy = False
proxyAddress = 
useragent = Mozilla/5.0
useRobots = True
timeout = 60
retry = 3
retryWait = 5
downloadDelay = 5
checkNewVersion = True
notifyBetaVersion = True
openNewVersion = True
enableSSLVerification = True

**Comment by KW-200-1316** [comment]
@gnarf1975 solution is working alright.

**Comment by superlaser97** [comment]
> > @gnarf1975 please check my comment at [#1239 (comment)](https://github.com/Nandaka/PixivUtil2/issues/1239#issuecomment-1448594330) and if that still doesn't work, mind sharing your config.ini? with the authentication removed of course
> > other people check [#1239 (comment)](https://github.com/Nandaka/PixivUtil2/issues/1239#issuecomment-1447705838) it may help until this is fixed
> > I only changed these settings. Now it seems to be working again.
> 
> [Network] useProxy = False proxyAddress = useragent = Mozilla/5.0 useRobots = True timeout = 60 retry = 3 retryWait = 5 downloadDelay = 5 checkNewVersion = True notifyBetaVersion = True openNewVersion = True enableSSLVerification = True

Changing the user agent to just "Mozilla/5.0" like mentioned did the trick for me as well

**Comment by YukihoAA** [comment]
> > > @gnarf1975 please check my comment at [#1239 (comment)](https://github.com/Nandaka/PixivUtil2/issues/1239#issuecomment-1448594330) and if that still doesn't work, mind sharing your config.ini? with the authentication removed of course
> > > other people check [#1239 (comment)](https://github.com/Nandaka/PixivUtil2/issues/1239#issuecomment-1447705838) it may help until this is fixed
> > > I only changed these settings. Now it seems to be working again.
> > 
> > 
> > [Network] useProxy = False proxyAddress = useragent = Mozilla/5.0 useRobots = True timeout = 60 retry = 3 retryWait = 5 downloadDelay = 5 checkNewVersion = True notifyBetaVersion = True openNewVersion = True enableSSLVerification = True
> 
> Changing the user agent to just "Mozilla/5.0" like mentioned did the trick for me as well

It worked to me too.
