### ISSUE TITLE
New Login Error as of 2023-03-06, different than the last error.

### ISSUE THREAD

**Issue by britefire** [Nandaka/PixivUtil2#1244]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Upon attempting to login using the fix that previously allowed the 403 forbidden login error to be bypassed, now a new error code is showing up.
HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.

This is a different error than before, which was a 403 forbidden, and isn't bypassed with **useragent = Mozilla/5.0** like the errors popping up last week.

### Steps to Reproduce

1. Add authentication cookie to config.ini
2. Change useragent to Mozilla/5.0
3. Launch PixivUtil2

**Expected behavior:** The program to launch and login.

**Actual behavior:** The following message:
`Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x17442bdcc10 whose wrapped object = <HTTPError 301: 'The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nMoved Permanently'>>, <traceback object at 0x000001743EBEE740>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 347, in loginUsingCookie
  File "PixivBrowserFactory.py", line 207, in open_with_retry
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Permanently

Cannot Login!`

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/10905352/pixivutil.log)

### Versions
PixivDownloader2 version 20230105

**Comment by britefire** [comment]
Was an issue on my end and restarting PC of all things fixed it, I'm sorry for the spam.

**Comment by hehequya** [comment]
@britefire i have this error too, restarting PC doesn't fix this, how can you do that
