### ISSUE TITLE
i face this problem

### ISSUE THREAD

**Issue by AyushNX** [Nandaka/PixivUtil2#1248]
![Screenshot (12)](https://user-images.githubusercontent.com/105802927/226106810-f5975deb-1c07-4328-8ba8-4ee2002a6ac0.png)

**Comment by PatrickL546** [comment]
dupe. https://github.com/Nandaka/PixivUtil2/issues/1239. A workaround by changing "useragent = Mozilla/5.0" in config.ini

**Comment by AyushNX** [comment]
thanks!
