### ISSUE TITLE
Cant start up

### ISSUE THREAD

**Issue by Aaeeschylus** [Nandaka/PixivUtil2#125]
Hello, I have been using this for a while now, love it!!! Today i started getting an error: http://pastebin.com/EGhXh28J

I havent changed any config or anything since i last used it.

**Comment by Nandaka** [comment]
I think they changed the login url/form, for now use cookie login method:
      1. Open Firefox.
      2. Login to your pixiv, remember to enable [Remember Me] check box.
      3. Right click the page and select View Page Info.
      4. Click the Security tab.
      5. Click the View Cookies button.
      6. Look for Cookie named = PHPSESSID.
      7. Copy the content value.
      8. Open config.ini, go to [Authentication] section, paste the value to 
         cookie, set 'keepsignedin = 1'.

**Comment by Nandaka** [comment]
related to #116

**Comment by Aaeeschylus** [comment]
Ah yes, that helped, thanks alot XD
