### ISSUE TITLE
Download from list not working...

### ISSUE THREAD

**Issue by momoe** [Nandaka/PixivUtil2#1255]
while inputing (4.  Download from list) menu option, the terminal asks for a "tag" and any subsequent entries just return to the menu. I have already created a list of artist profile urls in list.txt in the root directory and it doesn't seem working.

**Comment by momoe** [comment]
Still looking for some feedback if ` 4.  Download from list` is bugged or is `Tag :` supposed to have a specific input to read the `list.txt` file please.

**Comment by Nandaka** [comment]
No, it doesn't support tags in the list.txt, you need to pass it as parameter (so only 1 tag for whole list).

https://github.com/Nandaka/PixivUtil2#listtxt-format

![image](https://user-images.githubusercontent.com/836867/230803411-1a562fba-aa8e-4979-b337-d8bf5750bb56.png)

**Comment by momoe** [comment]
Apologies, I had to search through the config file and found `useList = True` to get list.txt to be read. I'll mark this as closed.
