### ISSUE TITLE
ugoira error breaks current operation...

### ISSUE THREAD

**Issue by momoe** [Nandaka/PixivUtil2#1256]
```

Stuff happened, trying again after 2 second (4)
Traceback (most recent call last):
  File "PixivArtistHandler.py", line 135, in process_member
  File "PixivImageHandler.py", line 359, in process_image
  File "PixivDownloadHandler.py", line 424, in handle_ugoira
  File "PixivHelper.py", line 1030, in ugoira2webm
  File "PixivHelper.py", line 1102, in convert_ugoira
PixivException.PixivException: PixivException(2007 Failed when converting image using ffmpeg -y -safe 0 -i C:\Users\USER\AppData\Local\Temp\convert_ugoiralpang0he\i.ffconcat -c:v libvpx-vp9 -lossless 0 -crf 15 -b 0 -vsync 0 C:\Users\USER\AppData\Local\Temp\convert_ugoiralpang0he\temp.webm ==> ffmpeg return exit code=1, expected to return 0., hasDumpPage=N)


C:\Users\USER\AppData\Local\Temp\convert_ugoira0kll4cwl\i.ffconcat: No such file or directory
Failed when converting image using ffmpeg -y -safe 0 -i C:\Users\USER\AppData\Local\Temp\convert_ugoira0kll4cwl\i.ffconcat -c:v libvpx-vp9 -lossless 0 -crf 15 -b 0 -vsync 0 C:\Users\USER\AppData\Local\Temp\convert_ugoira0kll4cwl\temp.webm ==> ffmpeg return exit code=1, expected to return 0.

Giving up image_id: XXXXXXXXXX
```

I don't know why it's trying to make a %APPDATA%\Temp directory but it doesn't exist, perhaps because I'm running PixivUtil2 off another disk drive. I already have ffmpeg.exe in the root directory and the vanilla ugoira webm suggested values.

**Comment by biggestsonicfan** [comment]
Well, PixivHelper attempts to create a temp path to convert the ugoira here:
https://github.com/Nandaka/PixivUtil2/blob/a6c278c2b5edb18ee3fd66db5eb9490cfe9afdf4/PixivHelper.py#L1127

And it _should_ fail if it can't create it. The exception is saying ffmpeg is returning 1, so the problem appears to be with ffmpeg itself. Have you tried downloading a new version?

**Comment by momoe** [comment]
I have just been migrating the same old FFMpeg and config and database to new PixivUtil2 downloads for a couple years, so that most likely sounds like the problem I'll give that a test and see if it still keeps failing this case.

**Comment by momoe** [comment]
Updating ffmpeg resolved this issue. TY and closing...

**Comment by biggestsonicfan** [comment]
Interestingly I am getting this error now...
