### ISSUE TITLE
Just had some End-User Questions

### ISSUE THREAD

**Issue by AugustusDraconus** [Nandaka/PixivUtil2#1258]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

1. Is it possible, when downloading the content of all the members you follow, to have each artist's content download to a separate folder titled after their account name?
2. I was downloading the content of the users I follow using the application, and I had to restart my router which interrupted the downloads. If I restart the downloads will it automatically pick up where I left off?
3. Lastly, this is probably stated somewhere, or simply known, but is the order in which things are downloaded the same order that they appear on my "Following" list or "Bookmarks" list?

**Comment by PatrickL546** [comment]
1. By default each user you follow gets their own folder. `filenameFormat = %artist% (%member_id%)\%urlFilename% - %title%`
2. When you start it again, it will first check the database if it's already downloaded and skip it if it is.
3. No, it downloads it from the smallest number to the largest. e.g. id 2000 > 12345 > 12346

Note on artist's name. If the artist changes their name, this will create a new folder with the new name. The post that is in the database will not be re-downloaded in the new folder unless the database is deleted. Then the program will not be able to find the old file with the old artist name, re-downloading the file again and creating duplicates.

If you want to keep using the same folder for the artist even if they change their name, It's best not to use their name in the folder, just use the pixiv ID as the folder name. 
See https://github.com/Nandaka/PixivUtil2/issues/1124

**Comment by AugustusDraconus** [comment]
Thank you for your help here bud. :-) I just had some follow up questions:

1. I see the setting entry you are referring to in the config.ini file, but I have `downloadListDirectory` and `rootDirectory` set to the same location on my SSD, and it seems they are overriding the default?
2. Is the database stored in the PixivUtil installation folder, i.e. the folder from which I would run PixivUtil?

At any rate, thank you again! Cheers!

**Comment by PatrickL546** [comment]
1. `downloadListDirectory` is the file used in option `Download from list (list.txt)`. `RootDirectory` is where the artist folder gets downloaded. e.g. `RootDirectory=C:\Pixiv`. It'll create `C:\Pixiv\%artistname% %pixivID%` folders. Do you have any problems?
2. Yes `db.sqlite` is the database file in the installation folder

**Comment by AugustusDraconus** [comment]
Thank you for the information! I really appreciate it! I think that is all I need for now. Cheers!

**Comment by AugustusDraconus** [comment]
Actually, when using option 5 (to download from Followed Users) one of the prompts asks for a 'bookmark count'. What does this  mean? Can I enter '0' for no limitations?

**Comment by PatrickL546** [comment]
> Actually, when using option 5 (to download from Followed Users) one of the prompts asks for a 'bookmark count'. What does this mean? Can I enter '0' for no limitations?

You can just press enter and put nothing. Just guessing but it could be the number of bookmarked items to download.

**Comment by AugustusDraconus** [comment]
> 1. `downloadListDirectory` is the file used in option `Download from list (list.txt)`. `RootDirectory` is where the artist folder gets downloaded. e.g. `RootDirectory=C:\Pixiv`. It'll create `C:\Pixiv\%artistname% %pixivID%` folders. Do you have any problems?
> 2. Yes `db.sqlite` is the database file in the installation folder
