### ISSUE TITLE
How can I use this program?

### ISSUE THREAD

**Issue by zoewl** [Nandaka/PixivUtil2#1259]
Forgive me for asking a very elementary and silly question
How do I use this program in the first place?
I downloaded and unzipped the following two programs; I also installed the latest version of Python.

[pixivutil202305.zip](https://github.com/Nandaka/PixivUtil2/releases/download/v20230105/pixivutil202305.zip)
https://github.com/Nandaka/PixivUtil2/archive/refs/tags/v20230105.zip

When I start PixivUtil2.exe with User ID and Pass in the Config file, I get this message and cannot proceed.

┌──────────────────────────────────────────────────────────┐
│ PixivDownloader2 version 20230105                        │
│ https://github.com/Nandaka/PixivUtil2/releases           │
│ Donate at https://bit.ly/PixivUtilDonation               │
└──────────────────────────────────────────────────────────┘
Reading C:\Users\U\Desktop\pixivutil202305\config.ini ...
Configuration loaded.
Using default DB Path: C:\Users\U\Desktop\pixivutil202305\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: my_username
press enter to exit.

I tried to use PixivUtil2.py on the command line, but I get an error like below.

C:\Users\U\Desktop\PixivUtil2>python PixivUtil2.py -h
Traceback (most recent call last):
  File "C:\Users\U\Desktop\PixivUtil2\PixivUtil2.py", line 16, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

Where am I going wrong, the readme had FAQs but no instructions.
Thank you in advance for your help.

**Comment by biggestsonicfan** [comment]
You do not need to download two versions of the program, one should be more than sufficient.

>Where am I going wrong, the readme had FAQs but no instructions.

Based on your statement "When I start PixivUtil2.exe with User ID and Pass in the Config file, I get this message and cannot proceed." you did not read the FAQ, as Section A Q3 in the FAQ explains this:

```
Q3. I cannot login to Pixiv!
    - Check your password.
    - Try to login to the Pixiv Website.
    - Try to use the config.ini on the [Authentication] section.
    - Check your date and time setting (e.g.: https://www.timeanddate.com/)
    - Disable Daylight Saving Time and try again.
    - Copy your session values from browser:
      1. Open Firefox.
      2. Go to Pixiv website and login, remember to enable [Remember Me]
          check box.
      3. Press F12 to open Developer Tools, and select the Storage tab.
      4. Click the Cookies and select for the pixiv.net.
      5. Look for Cookie named = PHPSESSID.
      6. Copy the content value. https://imgur.com/a/BppHOoQ
      7. Open config.ini, go to [Authentication] section, paste the value
         to cookie. https://imgur.com/VB2g3qn
```
These are indeed instructions on how to help you login to pixiv with PixivUtil2. There is also a pinned issue [Login cookie issue (update user agent to fix)](https://github.com/Nandaka/PixivUtil2/issues/1239)

The FAQ section B also answers your second issue about running PixivUtil2 as a script and not an executable binary:

```
Q5. I got '<library_name> module no found error'
    - Download the library from the source (see links from the Requirements
      section) and copy the file into your Lib\site-packages directory.
    - Or use pip install (google on how to use).
```

You also seemingly deleted the issue report template in which you were supposed to check-mark that you did read the FAQ section and that you did search through existing issues.

**Comment by zoewl** [comment]
First, thanks for the response.
The program did not give me any error codes. Therefore, I had no idea that "FAQ Q3" would apply to my case. In fact, I thought I was logged in.
This program should have let users know if there was some kind of error.
But anyways, my problem solved thanks to you.
