### ISSUE TITLE
pixivartist

### ISSUE THREAD

**Issue by 161424** [Nandaka/PixivUtil2#1275]
### Prerequisites

* [ ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

PixivArtist 的 40-41 和 91-92 感觉冲突了。我没有具体的链接，我是看test文件夹里面的数据判断的

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by biggestsonicfan** [comment]
![wtf](https://github.com/Nandaka/PixivUtil2/assets/9744201/c845de83-96f5-4cdf-9c89-3c949429e2ed)

Like, I assume they mean the [test](https://github.com/Nandaka/PixivUtil2/tree/master/test) folder? Are they objecting to the artists used in the tests?
