### ISSUE TITLE
New feature suggestion: download into archive

### ISSUE THREAD

**Issue by master117** [Nandaka/PixivUtil2#1277]
I used this tool a lot. I'm currently at about 1.5 million downloaded files (~2TB) and the amount of files creates a lot of work when moving stuff. I would love if we were able to download files directly into zip archives instead of folders. To save both space and make it easier to move stuff.

**Comment by PatrickL546** [comment]
You can do this with 7zip or other zip programs. I don't think this is suitable for this program personally.
[7z command line syntax](https://7-zip.opensource.jp/chm/cmdline/syntax.htm) , [7z add](https://7-zip.opensource.jp/chm/cmdline/commands/add.htm) , [7z update](https://7-zip.opensource.jp/chm/cmdline/switches/update.htm)
[examples, discussion](https://sourceforge.net/p/sevenzip/discussion/45797/thread/a41a8253/)

**Comment by master117** [comment]
Thank you for the fast reply. My main problem with that is what happens when the database dies. I feel like I had to clear it a few times in the past, but maybe that isn't a concern anymore? 

As far as I understand double downloads are avoided because they are in the database or in the file system. But if I move them into archives they will be no longer in the file system.

7zip surely can be adjusted to not create a copy in the archives but I would refer to not download them again.

**Comment by PatrickL546** [comment]
I haven't really needed to clear the DB, but I make backups pretty often.

> As far as I understand double downloads are avoided because they are in the database or in the file system. But if I move them into archives they will be no longer in the file system.

As long as it was downloaded, it gets saved in the database. It gets automatically skipped and not downloaded even if you remove the file.
