### ISSUE TITLE
Pixiv Download Stop

### ISSUE THREAD

**Issue by djscajsd1ajs** [Nandaka/PixivUtil2#1278]
When downloading an illustration photo as a tag, there is an empty part at the end of each schedule page.
When this empty part is met, the next page remains, but the download stops.
![ScreenShot_20230629004818](https://github.com/Nandaka/PixivUtil2/assets/138033481/9a81ba0d-0199-481b-b865-cf2742e2ea6c)

**Comment by biggestsonicfan** [comment]
Example id?

**Comment by djscajsd1ajs** [comment]
[image: image.png]

There are more pages behind, but in this situation, the download stops as
it is.

2023년 6월 29일 (목) 오전 9:07, biggestsonicfan ***@***.***>님이 작성:

**Comment by djscajsd1ajs** [comment]
![unnamed](https://github.com/Nandaka/PixivUtil2/assets/138033481/d4cfe9a1-3774-4c97-ac13-54dc5a91ef1b)
