### ISSUE TITLE
Cannot login SSL certificate verify failed

### ISSUE THREAD

**Issue by Corak667** [Nandaka/PixivUtil2#128]
Trying to login with the latest build of PixivDownloader2. But got an error only:
Log:
"
PixivDownloader2 version 20160613
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading d:\Soft\Network\Download\pixivutil\config.ini ...
done.
using default DB Path: d:\Soft\Network\Download\pixivutil\db.sqlite
Creating database... done.
Only process member where day last updated >= 7
Using Username: 13666999
Logging in...
Error at login(): (<class 'urllib2.URLError'>, URLError(SSLError(1, u'[SSL: CERT
IFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),), <traceback ob
ject at 0x01041698>)
Error at doLogin(): (<class 'urllib2.URLError'>, URLError(SSLError(1, u'[SSL: CE
RTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),), <traceback
object at 0x010514E0>)
Cannot Login!
"

**Comment by Nandaka** [comment]
I can login from my pc. Can you open the site from browser or other PC?

**Comment by Corak667** [comment]
Yes, I can login from browser in both my PC. But got this error and cannot login from Pixivutil2 on WIndows XP. Windows 7 seems login normally with PixivUtil2.

**Comment by Nandaka** [comment]
I don't have xp machine anymore, so I'm not sure why. I suspect the root certificate is not updated? Try to login using internet explorer in your xp machine?

**Comment by Corak667** [comment]
it's login normally on xp: http://f4.s.qip.ru/cMfvWyIA.png
Seems site even don't needs ssl certificate to login.

**Comment by Nandaka** [comment]
Nope, it requires https for the login part. I don't do any special handling for that.
One way of doing is by using cookie method for login.
