### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by SeraXZa** [Nandaka/PixivUtil2#1280]
I try to login like usual with my login credentials but I get the error message from the image attached.

I use the latest version and haven't had any issues until today. 

![Screenshot 2023-07-05 201451-fotor-20230705202347](https://github.com/Nandaka/PixivUtil2/assets/94391876/c110b19e-ee78-4183-88b7-014dbda13a1b)

**Comment by PatrickL546** [comment]
Please read other issues. https://github.com/Nandaka/PixivUtil2/issues/1239
