### ISSUE TITLE
txt file for Member_ID

### ISSUE THREAD

**Issue by Aaeeschylus** [Nandaka/PixivUtil2#129]
Is it possible to make a txt file, such as the tags list, filled with member ids and then tell the program to download images from all of those members? I would love to make a list of all my favourite members and then just run the program once a day, downloading all new images if there are any for those certain members. If this isnt possible, would this be something you would look into adding in the future?

**Comment by Nandaka** [comment]
It's already have it. You can use the list.txt feature, check the readme.txt for details.

**Comment by Aaeeschylus** [comment]
Oh thanks, do i just make a list.txt and put all the member ids in that? I read that it said put a directory next to each id, but i have a directory set in the config, so do i need to copy paste it for each id?

**Comment by Nandaka** [comment]
The directory is optional, in case you want to use different directory for each member.

**Comment by Aaeeschylus** [comment]
Alright, thanks alot!!!
