### ISSUE TITLE
Error medium page for image...

### ISSUE THREAD

**Issue by Darktrader** [Nandaka/PixivUtil2#130]
When I ran a programm and started to download by user ID, it showed me this on the console:

> 2016-06-29 19:46:32,125 - PixivUtil20160613 - INFO - Starting...
> 2016-06-29 19:46:32,134 - PixivUtil20160613 - INFO - Setting log level to: DEBUG
> 2016-06-29 19:46:32,134 - PixivUtil20160613 - INFO - No default cookie jar available, creating... 
> 2016-06-29 19:46:32,141 - PixivUtil20160613 - INFO - using default DB Path: D:\anime collection\PixivUtility\db.sqlite
> 2016-06-29 19:46:32,145 - PixivUtil20160613 - INFO - Only process member where day last updated >= 7
> 2016-06-29 19:46:46,835 - PixivUtil20160613 - INFO - Trying to log with saved cookie
> 2016-06-29 19:46:51,579 - PixivUtil20160613 - INFO - Login successfull.
> 2016-06-29 19:46:51,581 - PixivUtil20160613 - INFO - Logged in using cookie
> 2016-06-29 19:46:54,984 - PixivUtil20160613 - INFO - Member id mode.
> 2016-06-29 19:47:22,769 - PixivUtil20160613 - INFO - Processing Member Id: 92220
> 2016-06-29 19:47:22,793 - PixivUtil20160613 - INFO - Member Url: http://www.pixiv.net/member_illust.php?id=92220&p=1
> 2016-06-29 19:47:25,651 - PixivUtil20160613 - DEBUG - Sanitized Filename: D:\anime collection\PixivUtility\YUI_７＠GLF17 (92220)\folder.jpg
> 2016-06-29 19:47:29,227 - PixivUtil20160613 - INFO - Image ID (57641605): time data '6 29 2016, 04:01' does not match format '%Y-%m-%d %H:%M'
> 2016-06-29 19:47:29,227 - PixivUtil20160613 - DEBUG - Sanitized Filename: Error medium page for image 57641605.html
> 2016-06-29 19:47:29,289 - PixivUtil20160613 - ERROR - Dumping html to: Error medium page for image 57641605.html

And continue showing this -  _ERROR - Dumping html to: Error medium page for image_  for every next image of certain artist.

**Comment by Nandaka** [comment]
any artist? Also try to set the language in pixiv website to either english or japanese and then delete the cookie value in config.ini and try again?

**Comment by Darktrader** [comment]
So, yeah. Thanks. I do your recommendations and after it, pixiv downloader start downloaded it correctly. So, will be  pixiv downloader in the future to support downloading from site, when it has another language settings, except japanese and english?

**Comment by Nandaka** [comment]
the root cause is because different date/time format and currently I'm only supporting those languages.

You can override the format in config.ini.
dateformat   ==> Pixiv DateTime format, leave blank to use default format for 
                 English or Japanese. Refer to http://strftime.org/ for syntax.
		 Quick Reference:
		 %d = Day, %m = Month, %Y = Year (4 digit), %H = Hour (24h)
		 %M = Minute, %S = Seconds

from the log file:
```2016-06-29 19:47:29,227 - PixivUtil20160613 - INFO - Image ID (57641605): time data '6 29 2016, 04:01' does not match format '%Y-%m-%d %H:%M'```

So I think you need to set to %m-%d-%Y %H:%M'

**Comment by Darktrader** [comment]
Ok, I understood. Thanks.
