### ISSUE TITLE
This is in desperate need of a simple usage guide

### ISSUE THREAD

**Issue by BlepBlep** [Nandaka/PixivUtil2#1300]
Maybe I'm just a total noob when it comes to stuff like this, but I cannot figure this out for the life of me. I run the exe, it asks for my username, I put it in, it asks for my password, I try to type and it doesn't show up, hit enter, it tells me to press enter to exit, nothing. I manually put in my username and password into the config file, and it just says "Only process members where the last update is >= 7 days ago" (I have no idea what this means) and "press enter to exit".

Other parts link to other issue posts, talking about getting auth tokens, but apparently it doesn't work? Can we just get a simple step-by-step guide on how to use this? I really didn't think it'd be so complicated just to scrape a user on pixiv. Maybe I'm just really dumb.

**Comment by PatrickL546** [comment]
>  I run the exe, it asks for my username, I put it in, it asks for my password

It's currently broken, read login issues. Use cookie login, read other issues for info.
Cookie login works, Also 403 forbidden needs simple workaround with changing user-agent in config.ini. It's not been updated.   Other issues talk about it.

> Only process members where the last update is >= 7 days ago" 

After it process a member, it won't process it again if it's not been 7 days since last update. You can set it to 0 if you want the program to check every member every time you run the program.

**Comment by BlepBlep** [comment]
Yeah this is my point. This needs a guide on how to use, instead of requiring people to go through the 80+ issues reading through what is mostly outdated info on how to get it working. You can't even give me specifics other than "go read issues" lol

**Comment by PatrickL546** [comment]
[What does dayLastUpdated do?](https://github.com/Nandaka/PixivUtil2/issues/1158). It's still open
![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/9d58b489-6d25-4a5d-85ab-14b3198fe949)

[Login Problem](https://github.com/Nandaka/PixivUtil2/issues/1271) Open issue as well

![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/d77256be-1d90-4482-a081-a0932eff9d41)

[There's no application executable file](https://github.com/Nandaka/PixivUtil2/issues/1292) Similar problems you're having|
[Login cookie issue (update user agent to fix) ](https://github.com/Nandaka/PixivUtil2/issues/1239) Literally pinned issue
Plus my pull request to fix issues
![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/e2ff2ab1-04fd-48ef-a46a-eff9bbcbdbd4)

**Comment by PatrickL546** [comment]
I've been everywhere helping people and I just can't keep saying the same thing over and over again

**Comment by PatrickL546** [comment]
## My recent comments. 
![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/49f1a883-e73b-465c-bfd0-028f0c9b6992)

**Comment by PatrickL546** [comment]
Also it might help if you read the readme
https://github.com/Nandaka/PixivUtil2#downloadcontrol
![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/76300419-15ba-4298-b769-815140094642)

**Comment by BlepBlep** [comment]
> I've been everywhere helping people and I just can't keep saying the same thing over and over again

Again, my point exactly. You shouldn't have to go through here repeating yourself, there should be a guide readily available for everyone to read.

> Also it might help if you read the readme https://github.com/Nandaka/PixivUtil2#downloadcontrol ![image](https://user-images.githubusercontent.com/75874561/273520861-76300419-15ba-4298-b769-815140094642.png)
The readme explains what each and every little option does. It does not explain basic operation. I shouldn't have to dig this deep just to figure out how to use something. You can give me an extensive dissertation-length readme about features, but that means nothing if it doesn't explain how to use it in the first place.

**Comment by PatrickL546** [comment]
https://github.com/Nandaka/PixivUtil2/issues/1301

**Comment by BlepBlep** [comment]
> [Made a simple guide](https://github.com/Nandaka/PixivUtil2/issues/1301)

Awesome! I'm glad I know this exists. Now if only this could be linked on the main page, but I hope others will find it here when they come. Thanks for the work!
