### ISSUE TITLE
Login issue - may not be related to useragent

### ISSUE THREAD

**Issue by MasterKosa** [Nandaka/PixivUtil2#1302]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Unable to log in

### Steps to Reproduce

1. Run app with existing login

**Expected behavior:** 
Be able to log in and download files 

**Actual behavior:** 
I got following error:
<img width="664" alt="image" src="https://github.com/Nandaka/PixivUtil2/assets/9115644/12c906ab-9494-495a-97b3-ce0d4c798036">

**Log file:**
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/13127569/pixivutil.log)

### Versions latest from Jan 5

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by GerhardSauer** [comment]
same issue here, I also needed to re-login in the browser.
Therefore I copied the new cookie from the browser to the config and the login worked again.

**Comment by MasterKosa** [comment]
OK thanks, it worked. Closing as solved.
I apologize if this was duplicate of existing.

**Comment by biggestsonicfan** [comment]
Pixiv did something weird today and there seemed to be a full reset of all sessions.

**Comment by NHOrus** [comment]
Yeah, all sessions globally were flushed today.
Based on experience of weird, it was server update - cloudfare reported that pixiv servers weren't accessible to it to proxy out.

**Comment by Snkea** [comment]
This seem  fix doesn't work for me at all, i still getting the errors

**Comment by dioporcos** [comment]
still having this issue even with refreshed cookies

**Comment by PiPerson7472** [comment]
same here. tried changing the language to english (even though it was already set as such), logged out, logged back in, tried a different browser. nothing

**Comment by hamc09** [comment]
For Chrome, if you're still having an issue after logging out and logging back in, you can try this:

1. In Chrome's settings, delete all cookies for the sites pixiv.net, pixiv.help, and fanbox.cc, if applicable.
2. Close the browser.
3. Reopen the browser.
4. Log in at pixiv and fanbox.
5. On pixiv, attempt to browse to your account settings, and confirm the account you wish to continue with. If you don't do this, some account settings (specifically your set region, used for content filtering) may not function correctly until you do.
6. Fetch your new session ID cookies and place them into your config.ini file.
