### ISSUE TITLE
Use FFMPEG from PATH instead of PixivUtil2 root folder

### ISSUE THREAD

**Issue by AldebaraanMKII** [Nandaka/PixivUtil2#1304]
Why does the program needs to have FFMPEG.exe inside the root folder when it can use windows PATH to locate FFMPEG? I am running 4 instances of the program in parallel to speed up download speed (so far no issues) and keeping one copy on each it`s pretty annoying.

**Comment by PatrickL546** [comment]
It already uses your installed ffmpeg, I don't put ffmpeg inside PixivUtil2 root and it works fine.

**Comment by AldebaraanMKII** [comment]
> It already uses your installed ffmpeg, I don't put ffmpeg inside PixivUtil2 root and it works fine.

Then why didn`t it convert the ugoira to mkv? It downloaded them as .zip but no conversion. Here`s my .ini section:
[Ugoira]
writeUgoiraInfo = False
createUgoira = False
createMkv = True
createWebm = False
createWebp = False
createGif = False
createApng = False
deleteUgoira = False
deleteZipFile = False

and here`s the log:
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/13290706/pixivutil.log)

**Comment by AldebaraanMKII** [comment]
> You need to set `createUgoira = False` to `True` as well

Yes that fixed it. Thanks
