### ISSUE TITLE
[Question] Skip files already on database?

### ISSUE THREAD

**Issue by AldebaraanMKII** [Nandaka/PixivUtil2#1305]
What i do is download a artist gallery, pick the images i like and delete the rest. Problem is that when i re-run the program to download whatever new things the artist uploaded, the program downloads everything again. The main reason i started using this program was because of the database feature that i thought would skip files already downloaded. How do i skip the files inside the database (already downloaded)?

**Comment by PatrickL546** [comment]
It does skip already downloaded files, care to share logs?

**Comment by AldebaraanMKII** [comment]
> It does skip already downloaded files, care to share logs?

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/13290706/pixivutil.log)

**Comment by PatrickL546** [comment]
Perhaps you have `alwaysCheckFileSize = True`? That's one way I can make it download and check each file even if it's in the database

**Comment by AldebaraanMKII** [comment]
> Perhaps you have `alwaysCheckFileSize = True`? That's one way I can make it download and check each file even if it's in the database

Disabling it did nothing to end the issue.

Here`s my .ini minus the authentication part:

`[Network]
useProxy = False
proxyAddress = 
; useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
useragent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
useRobots = True
timeout = 60
retry = 5
retryWait = 10
downloadDelay = 5
checkNewVersion = True
notifyBetaVersion = True
openNewVersion = True
enableSSLVerification = True

[Debug]
logLevel = DEBUG
enableDump = True
skipDumpFilter = 
dumpMediumPage = False
dumpTagSearchPage = False
debugHttp = False
disableLog = False
disableScreenClear = False

[IrfanView]
IrfanViewPath = C:\Program Files\IrfanView
startIrfanView = False
startIrfanSlide = False
createDownloadLists = False

[Settings]
downloadListDirectory = .
useList = True
processFromDb = True
; rootDirectory = .
rootDirectory = H:\Pixiv
downloadAvatar = False
useSuppressTags = False
tagsLimit = -1
writeImageJSON = False
writeImageInfo = False
writeRawJSON = False
RawJSONFilter = id,title,description,alt,userIllusts,storableTags,zoneConfig,extraData,comicPromotion,fanboxPromotion
includeSeriesJSON = False
writeImageXMP = False
writeImageXMPPerImage = False
verifyImage = True
writeUrlInDescription = False
stripHTMLTagsFromCaption = False
urlBlacklistRegex = 
dbPath = 
setLastModified = True
useLocalTimezone = False
defaultSketchOption = 

[Filename]
; filenameFormat = %artist% (%member_id%)\%urlFilename% - %title%
filenameFormat = %artist% (%member_id%)\%member_id% %urlFilename%
filenameMangaFormat = %artist% (%member_id%)\%urlFilename% - %title%
filenameInfoFormat = %artist% (%member_id%)\%urlFilename% - %title%
filenameMangaInfoFormat = %artist% (%member_id%)\%urlFilename% - %title%
filenameSeriesJSON = %artist% (%member_id%)\%manga_series_id% - %manga_series_title%
filenameFormatSketch = %artist% (%member_id%)\%urlFilename% - %title%
filenameFormatNovel = %artist% (%member_id%)\%manga_series_id% %manga_series_order% %urlFilename% - %title%
avatarNameFormat = 
backgroundNameFormat = 
tagsSeparator = , 
createMangaDir = False
useTagsAsDir = False
urlDumpFilename = url_list_%Y%m%d
useTranslatedTag = False
tagTranslationLocale = en
customBadChars = 
customCleanUpRe = 


[Pixiv]
numberOfPage = 0
r18mode = False
r18Type = 0
dateFormat = 
autoAddMember = False
aiDisplayFewer = False

[FANBOX]
filenameFormatFanboxCover = FANBOX %artist% (%member_id%)\%urlFilename% - %title%
filenameFormatFanboxContent = FANBOX %artist% (%member_id%)\%urlFilename% - %title%
filenameFormatFanboxInfo = FANBOX %artist% (%member_id%)\%urlFilename% - %title%
writeHtml = False
minTextLengthForNonArticle = 45
minImageCountForNonArticle = 3
useAbsolutePathsInHtml = False
downloadCoverWhenRestricted = False
downloadCover = True
checkDBProcessHistory = False
listPathFanbox = listfanbox.txt

[FFmpeg]
ffmpeg = ffmpeg.exe
ffmpegCodec = libvpx-vp9
ffmpegExt = webm
ffmpegParam = -lossless 0 -crf 15 -b 0 -vsync 0
mkvCodec = copy
mkvParam = 
webpCodec = libwebp
webpParam = -lossless 0 -compression_level 5 -quality 100 -loop 0 -vsync 0
gifParam = -filter_complex [0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle -vsync 0
apngParam = -plays 0 -vsync 0
verboseOutput = False

[Ugoira]
writeUgoiraInfo = False
createUgoira = True
createMkv = True
createWebm = False
createWebp = False
createGif = False
createApng = False
deleteUgoira = False
deleteZipFile = False

[DownloadControl]
minFileSize = 0
maxFileSize = 0
checkLastModified = True
alwaysCheckFileSize = False
overwrite = True
backupOldFile = False
dayLastUpdated = 0
checkUpdatedLimit = 0
useBlacklistTags = False
useBlacklistTitles = False
useBlacklistTitlesRegex = False
dateDiff = 0
enableInfiniteLoop = False
useBlacklistMembers = False
downloadResized = False
skipUnknownSize = False
enablePostProcessing = False
postProcessingCmd = 
extensionFilter = 
downloadBuffer = 512

`
