### ISSUE TITLE
Incompatible with python 3.12?

### ISSUE THREAD

**Issue by bluerthanever** [Nandaka/PixivUtil2#1306]
### Prerequisites

* [ √ ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ √ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ √ ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I recently updated my python to 3.12, and when I tried to run PixivUtil2, initially I got the following error:
```
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```

Then I tried to run again after I had deleted the first line in 'PixivUtil.py'
https://github.com/Nandaka/PixivUtil2/blob/b7162b8bda1eaed0329459a8374406df4dce6871/PixivUtil2.py#L1C1-L1C23
I kept getting the following error while checking login status:
```
2023-11-07 10:10:33,673 - PixivUtil20230105 - ERROR - Error at doLogin().
Traceback (most recent call last):
  File "D:\coding\PixivUtil2\PixivBrowserFactory.py", line 207, in open_with_retry
    res = self.open(url, data, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\mechanize\_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\mechanize\_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\mechanize\_opener.py", line 193, in open
    response = urlopen(self, req, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\mechanize\_urllib2_fork.py", line 425, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\mechanize\_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\mechanize\_urllib2_fork.py", line 1283, in https_open
    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\mechanize\_urllib2_fork.py", line 1196, in do_open
    h = http_class(host_port, timeout=req.timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'
```

I tried again after I had installed python 3.10.11 back on my laptop again and it worked fine.

I didn't try a full clean reinstall, because I kinda got lazy when I was installing python 3.12. Like I didn't delete all the site packages, I just updated them after the installation.

### Steps to Reproduce

1. Uninstall python 3.10 on my laptop
2. Changed the folder name of site packages from 'python310' to 'python312'
3. Updated all packages using pip install -U
4. Run pixivutil2 and got the errors

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
As mentioned above

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions
20230105
But I run from python files, and I had updated since the version

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by NHOrus** [comment]
It's problem with Mechanize
https://github.com/python-mechanize/mechanize/issues/86

**Comment by bluerthanever** [comment]
hmm. any workarounds?

**Comment by NHOrus** [comment]
You are in luck! Three hours ago there was a release of mechanize 0.4.9 with the problem fixed!
update to it, enjoy

**Comment by PatrickL546** [comment]
I pretty much nuked all my python installs cause I thought some dependency was broken. Ended up with starting fresh with python 3.11.6 with minimal pip installs. And now it's fixed.
I'd probably just stick with 3.11 for a while.

**Comment by bluerthanever** [comment]
> You are in luck! Three hours ago there was a release of mechanize 0.4.9 with the problem fixed! update to it, enjoy

haha. thanks! good to know
