### ISSUE TITLE
Default FFMPEG params for WebM causing broken colors

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#1309]
Updated my pull request to have this fix https://github.com/Nandaka/PixivUtil2/pull/1281

              As I was testing, I there seems to be a bug with the current PixivUtil2 default WebM Params. 
Colors are not being done correctly. This is fixed by adding `-pix_fmt yuv420p`
![image](https://github.com/Nandaka/PixivUtil2/assets/75874561/8e75b1ef-811b-4e83-a245-c79a760be148)

_Originally posted by @PatrickL546 in https://github.com/Nandaka/PixivUtil2/issues/1308#issuecomment-1816642957_

**Comment by biggestsonicfan** [comment]
I will test on Linux here shortly.
