### ISSUE TITLE
Can´t download

### ISSUE THREAD

**Issue by eienkei** [Nandaka/PixivUtil2#131]
This appears after I try to download by member ID, and selecting the pages

Member Url: http://www.pixiv.net/member_illust.php?id=16891&p=1
Traceback (most recent call last):
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
Error at process_member(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x033141E8>)
Empty Html
Dumping html to: Error page for member 16891.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1851, in main
  File "PixivUtil2.py", line 1637, in main_loop
  File "PixivUtil2.py", line 1299, in menu_download_by_member_id
  File "PixivUtil2.py", line 320, in process_member
  File "PixivModel.pyc", line 51, in __init__
  File "PixivModel.pyc", line 104, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.

**Comment by Nandaka** [comment]
Looks like it return empty html so the application cannot get the images. Most likely network issue.

Can you try on different pc/internet connection?

**Comment by eienkei** [comment]
I tried on a different pc/connection but still I am getting the same error, then when  try to log in in the pixiv utility this appears: 
Trying to log with saved cookie
Error at doLogin(): (<class 'httplib.IncompleteRead'>, IncompleteRead(5680 bytes read), <traceback object at 0x02C8AD50>)
Cannot Login!
press enter to exit.

So I have to delete and unrar the content once again. Error remains

**Comment by Nandaka** [comment]
>> Error at doLogin(): (, IncompleteRead(5680 bytes read), )

This is due network connection interrupted.

Can you open the website on browser?

**Comment by eienkei** [comment]
Yes, I can open the website without problems, no matter the browser or pc.

**Comment by Nandaka** [comment]
do you use firewall or antivirus? from the log, it show connection issue, whether the site return empty or partial response.

also try to use the cookie login method?
Q3: Error at process_image(): (<type 'exceptions.AttributeError'>, 
    AttributeError ("'NoneType' object has no attribute 'find'",)
    - Usually this is because of login failed (cookie not valid). Try to change
      your password to simple one for testing, or copy the cookie from browser:
      1. Open Firefox.
      2. Login to your pixiv.
      3. Right click the page and select View Page Info.
      4. Click the Security tab.
      5. Click the View Cookies button.
      6. Look for Cookie named = PHPSESSID.
      7. Copy the content value.
      8. Open config.ini, go to [Authentication] section, paste the value to 
         cookie, set 'keepsignedin = 1'.

**Comment by eienkei** [comment]
Yes, I use antivirus (Eset Nod), I will try deactivating it or making an exemption to the downloader.

I have tried using the cookie login method but didn`t work. I will try again more carefully, and post later if I managed to reach a solution. I appreciate in advance for all the help you are giving me.
