### ISSUE TITLE
Smart cli like youtube-dl instead of menus

### ISSUE THREAD

**Issue by duarm** [Nandaka/PixivUtil2#1316]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Thanks for making PU2! (name too long)

I would be nice if PU2 acted more like youtube-dl, you give him a link and it guesses what you want, which is, most likely, to just download the image. You can then add more flags if you want more, like `youtube-dl LINK --write-description`

**Expected behavior:**

```shell
$ pixiv pixiv.net/artworks/123
Image at ./image.png

$ pixiv pixiv.net/users/111
Downloaded everything to ./

$ pixiv -h
pixiv
   -h help
   --by-rank download by rank
   --by-member download by member id
```

### Versions

 PixivDownloader2 version 20230105

**Comment by biggestsonicfan** [comment]
I mean you can send it command line arguments to bypass the menus to get exactly what you want. PRs are welcome if you want to implement it, else gallery-dl does exactly what you're suggesting

**Comment by duarm** [comment]
Guess we have a bug then?

Doesnt matter which command I run, I get the menus, I suspect the git error at beginning is the cause, I just ran the pixiv command after installing from AUR

```
[@USER]$ pixiv --help
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
┌──────────────────────────────────────────────────────────┐
│ PixivDownloader2 version 20230105                        │
│ https://github.com/Nandaka/PixivUtil2/releases           │
│ Donate at https://bit.ly/PixivUtilDonation               │
└──────────────────────────────────────────────────────────┘
Reading /home/USER/.local/share/PixivUtil2/config.ini ...
Configuration loaded.
Using default DB Path: /home/USER/.local/share/PixivUtil2/db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Username login is broken, use cookie to log in.
Trying to log in with saved cookie
Logging in, return url: https://www.pixiv.net/en/
Login successful.
My User Id: xxxxxxxxx.
Premium User: False.
┌──────────────────────────────────────────────────────────┐
│ PixivDownloader2 version 20230105                        │
│ https://github.com/Nandaka/PixivUtil2/releases           │
│ Donate at https://bit.ly/PixivUtilDonation               │
└──────────────────────────────────────────────────────────┘
── Pixiv ───────────────────────────────────────────────────
 1.  Download by member_id
 2.  Download by image_id
 3.  Download by tags
...
```

Indeed the source was changed
```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   PixivUtil2.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        pixiv_venv/
        "\343\202\265\343\202\244\343\203\263\343\201\223\343\201\231 (11229342)/"

```

PixivUtil2.py was given execute permission, restoring the file to HEAD we have this
```
.rw-r--r--  77k sakura sakura 16 Dec 00:41 PixivUtil2.py
```

My guess is that the script is not executable by default, and the AUR script tries to make it executable, which causes the git error at the beginning, PixivUtil2 drops whatever command it has, and opens the menu

**Comment by duarm** [comment]
Even after commiting it still always opens the menu `pixiv -h` , maybe the aur script is broken

**Comment by PatrickL546** [comment]
I'm on windows and It works. e.g. `PixivUtil2.py -s 4 -f list.txt --is -x`
To export followed artist `PixivUtil2.py -s  e  -p  y -x --ef export.txt`

**Comment by nicodoggie** [comment]
Looking at the `/usr/bin/pixiv` helper script in the arch package that loads the venv, it looks like the command line arguments aren't being passed onto `PixivUtil2.py`

Adding `$@` to the end of each `$HOME/.local/share/PixivUtil2/PixivUtil2.py` call will fix it.

**Comment by biggestsonicfan** [comment]
@nicodoggie Would this not be an issue for the arch package maintainer?

**Comment by duarm** [comment]
Totally, thanks for telling me @nicodoggie

**Comment by nicodoggie** [comment]
> Would this not be an issue for the arch package maintainer?

Most definitely. I suppose I wanted it to be on the record here, since I saw this thread before I tried to investigate myself. I fully intend to report it to the AUR
