### ISSUE TITLE
problem when writing files to disk

### ISSUE THREAD

**Issue by TimeCompass** [Nandaka/PixivUtil2#133]
what screen says:

Trying to log with saved cookie 
Login successfull. 
PixivDownloader2 version 20160613
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
1. Download by member_id
2. Download by image_id
3. Download by tags
4. Download from list
5. Download from online user bookmark
6. Download from online image bookmark
7. Download from tags list
8. Download new illust from bookmark
9. Download by Title/Caption
10. Download by Tag and Member Id
11. Download Member Bookmark
12. Download by Group Id

d. Manage database
e. Export online bookmark
m. Export online user bookmark
r. Reload config.ini
p. Print config.ini
x. Exit
Input: 1
Member ids: 104247
Start Page (default=1): 
End Page (default=0, 0 for no limit): 
Processing Member Id: 104247 
Reading /root/pixivutil2/config.ini ...
done.
Page  1
Member Url: http://www.pixiv.net/member_illust.php?id=104247&p=1 
Member Name  : 無言 
Member Avatar: http://i1.pixiv.net/img11/profile/gunhoguns/87063.jpg
Member Token : gunhoguns
Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?id=104247&p=1 
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?id=104247&p=1 
Creating directory: /root/data/[104247] [無言] 
Traceback (most recent call last):
  File "PixivUtil2.py", line 126, in download_image
    downloadedSize = PixivHelper.downloadImage(url, filename, res, file_size, overwrite)
  File "/root/pixivutil2/PixivHelper.py", line 503, in downloadImage
    os.makedirs(directory)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: '/root/data/[104247] [\xe7\x84\xa1\xe8\xa8\x80]'
Error at download_image(): (<type 'exceptions.OSError'>, OSError(22, 'Invalid argument'), <traceback object at 0x76192300>) at http://i1.pixiv.net/img11/profile/gunhoguns/87063.jpg (9000) 
Retrying [1]...
1 2 3 4 
Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?id=104247&p=1 
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?id=104247&p=1 
Creating directory: /root/data/[104247] [無言] 
Traceback (most recent call last):
  File "PixivUtil2.py", line 126, in download_image
    downloadedSize = PixivHelper.downloadImage(url, filename, res, file_size, overwrite)
  File "/root/pixivutil2/PixivHelper.py", line 503, in downloadImage
    os.makedirs(directory)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: '/root/data/[104247] [\xe7\x84\xa1\xe8\xa8\x80]'
Error at download_image(): (<type 'exceptions.OSError'>, OSError(22, 'Invalid argument'), <traceback object at 0x7617c490>) at http://i1.pixiv.net/img11/profile/gunhoguns/87063.jpg (9000) 
Retrying [2]...

I'm pretty sure that config.ini was UTF-8, and I mount disk with -w on /root/data
And also I've tried the same config.ini on windows and it works well(except there's no /root/data)
So I change the rootdirectory back to '.' and it worked, the problem disappeared 

I can't understand why, and one more thing, when I set rootdirectory to '/root/data', folder.jpg has been downloaded to my disk normally with error messages above. But no sub-folders like 'Creating directory: /root/data/[104247] [無言] ', it appears to be '/root/data/folder.jpg'.
When I change rootdirectory back to '.' and run python pixivutil2.py (I should have mentioned I usually runs on linux) , I got the right result '/root/pixivutil2/[104247] [無言]/folder.jpg'

**Comment by TimeCompass** [comment]
P.S.
I uesd list.txt and there is 
104247 /root/data

**Comment by Nandaka** [comment]
I'm not sure too, as I don't have linux.

what if you set the root dir from config.ini in ```rootdirectory = <path>```

**Comment by TimeCompass** [comment]
It's wired……and I found another problem
Let me tell what I have tried:

pixivutil2(.py) is in the folder  /root/pixivutil2

I edited config.ini and changed these:

uselist = True
rootdirectory = ./year/

and in list.txt
104247 /root/data

finally the image downloaded to (space for clear looking)
/root/pixivutil2/year/ (sub-folder what I set in config.ini) / filename.jpg

It seems to be that list.txt did't work though rootdirectory works perfectly.

**Comment by TimeCompass** [comment]
Oh Sorry I got that!
the disk I used is in vfat format and caused system error. I changed to ext4/xfs which usually linux system use and the problem solved!!

Now only remains list.txt 's problem.
