### ISSUE TITLE
Validate that previously downloaded file is present in filesytem

### ISSUE THREAD

**Issue by pandabuilder** [Nandaka/PixivUtil2#134]
Need an option to run PixivUtil to validate that files are still on the filesystem, and then delete or mark the database records that are no longer present, to force a redownload.

**Comment by Nandaka** [comment]
you can use alwaysCheckFileSize in config.ini

see readme.txt for more details

**Comment by NHOrus** [comment]
Alternatively, you can command d c - Manage Database and Clean Up Database from manage menu.

Then PixivUtil will go through all previously downloaded images and will delete from the database those that aren't there.

**Comment by pandabuilder** [comment]
Thank you, with this options I can do what I wanted.
