### ISSUE TITLE
Unable to login with py file

### ISSUE THREAD

**Issue by ytoaa** [Nandaka/PixivUtil2#1351]
C:\Users\gas\Downloads\PixivUtil2>python PixivUtil2.py
┌──────────────────────────────────────────────────────────┐
│ PixivDownloader2 version 20240703                        │
│ https://github.com/Nandaka/PixivUtil2/releases           │
│ Donate at https://bit.ly/PixivUtilDonation               │
└──────────────────────────────────────────────────────────┘
Reading C:\Users\gas\Downloads\PixivUtil2\config.ini ...
Configuration loaded.
Using default DB Path: C:\Users\gas\Downloads\PixivUtil2\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Username login is broken, use Cookies to log in.
See Q3. at https://github.com/Nandaka/PixivUtil2?tab=readme-ov-file#a-usage
Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x1bac6ce28f0 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x000001BAC6D0EE00>)
Traceback (most recent call last):
  File "C:\Users\gas\Downloads\PixivUtil2\PixivUtil2.py", line 1527, in doLogin
    result = __br__.loginUsingCookie()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gas\Downloads\PixivUtil2\PixivBrowserFactory.py", line 351, in loginUsingCookie
    res = self.open_with_retry('https://www.pixiv.net/en')  # + self._locale)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gas\Downloads\PixivUtil2\PixivBrowserFactory.py", line 207, in open_with_retry
    res = self.open(url, data, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gas\AppData\Local\Programs\Python\Python312\Lib\site-packages\mechanize\_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gas\AppData\Local\Programs\Python\Python312\Lib\site-packages\mechanize\_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!
press enter to exit.

------------------------------------------------------------------------------------------------------

I tried this on the source file of the July 3 update and the file built with exe.
It runs normally in exebuild, but errors occur when running as a py file.
The contents of config.ini are the same.

Attempted in Ubuntu 22.04 version of python 3.10.12.

Of course, I also changed the userobots option.

**Comment by pixtrix** [comment]
Was there a fix for this issue that you could pass on? I'm experiencing the same issue since yesterday when I exited PixivUtil2 and tried to restart it.

Now I get this same error message every time I try to restart PixivUtil2. I reset my config.ini and it wouldn't start, then put in cookie information and it went right back to this error message. I'm guessing it's a Cloudflare related issue, but I haven't dug into it.
