### ISSUE TITLE
Local files are deleted and redownloaded if remote size is -1

### ISSUE THREAD

**Issue by nomakewan** [Nandaka/PixivUtil2#1353]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Occasionally a remote file will not report its filesize correctly, returning -1. When this happens, if a file already exists, PixivUtil2 will treat this as if there is a mismatch and will delete the existing file and replace it with the remote file, even if in reality those two files are identical.

### Steps to Reproduce

1. Download a post you have already downloaded.
2. Cross your fingers that the remote fails to report filesize correctly.

**Expected behavior:** PixivUtil2 handles this error gracefully and does not redownload the file (either prefer local, or retry the request for the remote filesize)

**Actual behavior:** PixivUtil2 deletes the local copy and downloads the remote.

**Log file:** Cannot replicate this error in a log as it is non-deterministic (the filesize error part of the transaction happens randomly on Pixiv's end) but here is a screenshot where I caught it happening during a massive update:

![pixivutilfilecheckfail](https://github.com/user-attachments/assets/f485bd3c-d649-4afe-8eef-27d7adf9af43)

### Versions

Was running commit 5c902fd from source. Assuming the same bug is present in latest release as well.

**Comment by Nandaka** [comment]
what is your configuration? ensure `alwaysCheckFileSize` = `False`
![image](https://github.com/user-attachments/assets/a2f254b0-21d6-4b55-9dd4-9398175b8d52)

**Comment by nomakewan** [comment]
My downloader settings are:

```
[DownloadControl]
minFileSize = 0
maxFileSize = 0
checkLastModified = True
alwaysCheckFileSize = False
overwrite = False
backupOldFile = False
dayLastUpdated = 7
checkUpdatedLimit = 0
useBlacklistTags = False
useBlacklistTitles = False
useBlacklistTitlesRegex = False
dateDiff = 0
enableInfiniteLoop = False
useBlacklistMembers = False
downloadResized = False
skipUnknownSize = False
enablePostProcessing = False
postProcessingCmd = 
extensionFilter = 
downloadBuffer = 512
```

**Comment by Nandaka** [comment]
Hmm, the related code are here https://github.com/Nandaka/PixivUtil2/blob/abc588b96547ba3fbed1575497d0ebbf94353259/PixivHelper.py#L723-L738

I can add new condition if `overwrite` not enabled and new `file_size` == -1, then skip download?

**Comment by nomakewan** [comment]
That works. If a subsequent update returns the proper filesize and it ends up legitimately different it'll be updated normally anyway, so yeah.

**Comment by Nandaka** [comment]
It doesn't make sense to me if the `file_size > 0` as it means the file got changed already.

**Comment by nomakewan** [comment]
Going to assume this issue is resolved. If I run into it again I will reopen.
