### ISSUE TITLE
[request] Linux version?

### ISSUE THREAD

**Issue by Momoe** [Nandaka/PixivUtil2#136]
As the title suggests, it would be awesome if this could be released into an linux terminal version please? 

Thanks,

**Comment by Nandaka** [comment]
you can run the script version directly in linux, as long you install the python runtime and the required library.

**Comment by Momoe** [comment]
As a novice linux user, I wasn't able to simply run the PixivUtil.py script inside the PixivUtil2-master folder. I don't think I would be able to run the "pixivutil201607111" version because it looks like it has .dll and exe dependancies. 

I do have the python runtime, and was greeted with 

`~/PixivUtil2-master$ python PixivUtil2.py 
Traceback (most recent call last):
  File "PixivUtil2.py", line 18, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup
`

**Comment by Nandaka** [comment]
you need to install below library:
  - mechanize 0.2.5 (http://wwwsearch.sourceforge.net/mechanize/)
  - BeautifulSoup 3.2.1 (http://www.crummy.com/software/BeautifulSoup/)
  - socksipy-branch 1.02+ (https://socksipy-branch.googlecode.com/)
  - Pillow (https://python-pillow.github.io/)

you can use pip to do it.

**Comment by Momoe** [comment]
After installing 'pip' I was able to install all of the dependencies, PixivUtil2 now works. Thank you for the assistance here.

**Comment by amayra** [comment]
exe file work fine in wine i test it

**Comment by eromoe** [comment]
@Nandaka 
Hi, in requirements.txt requires `socksipy-branch>=1.2`  , which pip can't install .  The newest version in pip is 1.1.  I tried download that socksipy by hand,  but it doesn't contain a `setup.py` file, how do I install it ?

**Comment by Nandaka** [comment]
You can put the socks.py to the pixivutil folder?

**Comment by eromoe** [comment]
I remove `socksipy-branch>=1.2` from `requirements.txt` and works fine ,so it is only used for proxy, right ?

**Comment by Nandaka** [comment]
Yes, it is only for SOCKS proxy. Normal http proxy is supported from python out-of-the-box.
