### ISSUE TITLE
[ASK] Accidentally overwrite db.sqlite during the last update

### ISSUE THREAD

**Issue by baraghiffari** [Nandaka/PixivUtil2#1362]
This is more of a questions and ask for help, i don't know where should i ask this so i decide to do here instead. The title is self explanatory, I accidentally overwrite it after extracting the last update inside my installation. Is there a way for me to fill the database like before without re-downloading everything i had ? I mainly use it to track what i already download because i compress everything after downloading and organize it into a folder. Thanks

**Comment by biggestsonicfan** [comment]
db.sqlite stores a lot of metadata, if you don't have all that data per-post, you probably won't be able to recreate it. Depending on how your filenames are stored before you compress, you might be able to recreate a dummy db.sqlite just so the files are not redownloaded, but the metadata would not be stored, but unfortunately that would fall a little bit out of scope of the project.

My only advice for you would be trying to get a list of all the post ids you have and go from there. Granted not all of them will probably still be live on the site anymore.

**Comment by baraghiffari** [comment]
I use Caesium to compress the image, I keep their metadata and file names while replacing the originals. I think i might need to find a way to list every image ids and save it inside the db like you said
