### ISSUE TITLE
[Chrome?] Pixiv completely breaks/locks itself, requiring full Chrome wiping and reinstalls to work, then breaks again shortly after. PixivUtil2 found to cause.

### ISSUE THREAD

**Issue by Jatts-Art** [Nandaka/PixivUtil2#1364]
After spending hours all day long trying to find out what was going on with this damn website, whether it was the site itself or my computer or my internet, and then finally narrowed down the cause of it... PixivUtil2. Unknown if Pixiv made new changes to their site today or what which results in this new problem, but all I know is that the site completely "locks" itself and breaks, not allowing anything to load at all period. Just this morning it was working fine, as it always had for years, until suddenly this.

Its hard to explain what exactly I mean by things "breaking", other than showing these example images... profile galleries and image posts turn into this:
![image post](https://github.com/user-attachments/assets/e0859908-211c-458e-b401-2ba820bc7710)
![profile page](https://github.com/user-attachments/assets/c2eec866-8c8f-4565-822d-fe317d446408)

^ What you see here is basically what happens to Pixiv now, on Chrome, whenever activating PixivUtil2... starting today. It remains frozen like this, and does not even attempt loading anything properly at all. PixivUtil2 itself still works completely fine btw, surprisingly, but this bug requires me to go to all of the Chrome folders and manually deleting them, and then reinstalling (if i dont delete folders, it still doesnt work).

As you may imagine, this is extremely annoying to do every single time I want to use PixivUtil2, if this ends up staying this way. Deleting cookies does nothing, logging in and out does nothing, yes I've tried basically everything; only hard uninstalls and reinstalls work.

I have used this application for many many years, so long that I don't even remember how long ago... and yet I've never had issues with it until randomly starting today. Don't even know how to properly label this thread, due to how completely random this is and came out of no where. But I have tested quite a few times and, very consistently, Pixiv breaks specifically when using PixivUtil2 so yeah not sure wtf is going on.

**Comment by Nandaka** [comment]
Hmm, I'm not using Chrome anymore, but looks like no issue when I open it in Firefox after I run and download some images using the app. I'm not sure why it happens, but rather than reinstalling, try to open it on incognito mode first? or maybe run on different browser?

Fyi, Chrome doesn't allow to run uBlock Origin anymore.

**Comment by Jatts-Art** [comment]
Forgot to respond to this before, but I ended up switching to Edge as a direct result of this crap. So this can be closed I guess.
