### ISSUE TITLE
HTTP Error 403, can't login.

### ISSUE THREAD

**Issue by YeetElite** [Nandaka/PixivUtil2#1368]
### Prerequisites

* [Y] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [Y] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Error
```
Trying to log in with saved cookie 
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x7f924fdb0280 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x7f924fe01c80>) 
Traceback (most recent call last):
  File "/workdir/PixivUtil2.py", line 1527, in doLogin
    result = __br__.loginUsingCookie()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workdir/PixivBrowserFactory.py", line 351, in loginUsingCookie
    res = self.open_with_retry('https://www.pixiv.net')  # + self._locale)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workdir/PixivBrowserFactory.py", line 207, in open_with_retry
    res = self.open(url, data, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden
 
Cannot Login!
```

### Description
I've tried changing the useragent and setting useRobots = False.
I'm not sure what could be causing it.

### Steps to Reproduce
Clone and build/run with docker on Deb12.

**Log file:** [pixivutil.log](https://github.com/user-attachments/files/16788776/pixivutil.log)
**Config ini:** [config.ini](https://github.com/user-attachments/files/16788937/config.txt) (it's just the default generated)
**Version:** 20240703

**Comment by pva18** [comment]
I have the exact same issue with same error. I am on windows 11, I tried running the latest master version directly on windows and in a freshly built container, both produced the same error.

**Comment by pva18** [comment]
You should set the language of pixiv in the browser to something other than English (for example Japanese) when you copy the cookie like described [here](https://github.com/Nandaka/PixivUtil2/issues/1352#issuecomment-2227002669). This worked for me when I got the same error.

**Comment by YeetElite** [comment]
@pva18 that did it, thank you!
