### ISSUE TITLE
resume progress state from last exit 

### ISSUE THREAD

**Issue by eromoe** [Nandaka/PixivUtil2#137]
I found  every time I open `PixivUtil2` need enter password, and it do not remenber the artist last download, some artists have many pics which can't finish in one day.

I recomand:
1. Detect if there is a seesion cookie,  if yes use it without prompt else prompt username input.
2. Ctrl-c can exit and save current progress, and it can resume if there are a previous progress state

**Comment by Nandaka** [comment]
for 1st item:
you can set your username/password in config.ini

for 2nd item:
might be difficult, as pixivutil download from the newest to the oldest one, so it might not fetch the latest item when resuming.

**Comment by eromoe** [comment]
Maybe show an option for resuming if previous task is not completed yet?
Such as  `A: resume from previous   B: new task`
Because resume from previous state could save time and also reduce the newwork cost of pixiv.

**Comment by Nandaka** [comment]
I've looking around for suspending the execution for python, and looks like it require major changes (e.g. need to rewrite the code to store the execution state)...

If your target is just pausing the script (without closing the screen and assuming you are using windows), actually you can do so by enabling quick edit and clicking the screen to temporarily pause the execution.

Click the icon and select Defaults. Enable Quick Edit on Option Tabs.
![image](https://cloud.githubusercontent.com/assets/836867/17128299/3f19e6ba-533e-11e6-9359-39b4f145f19c.png)

**Comment by eromoe** [comment]
Agree that it is different to achieve resuming. 
I am not try to pause it, just want to resume the task from yesterday.
At first, I afraid I would be ban by pixiv due to too many pv.  
But it works fine to now, so, nevermind~

**Comment by Hamuko** [comment]
One way to implement it would be to save files with operation information, for example in JSON. You might have something like this.

```json
{
    "operation": 1,
    "id": [123456, 234567, 345678],
    "start_page": 1,
    "end_page": 0,
    "last_page": 23,
    "last_image_on_page": 12
}
```
So, when you start *Download by member_id* with the same input, it'd reference the folder where the states are saved, look up if anything matches and if a match can be found, just skip until it gets to the same position.

But then again, the current method of operation works well enough in my opinion.

**Comment by NHOrus** [comment]
I use list_full.txt, when I need it, I copy-paste and shuffle ordering of member IDs from it to list.txt. To resume, merely prune up to last finished member. Less convenient, more tunable and scriptable.
