### ISSUE TITLE
Still cannot log in

### ISSUE THREAD

**Issue by anna-s-h** [Nandaka/PixivUtil2#1372]
I was hoping Pixiv would undo whatever change was causing it so I was just going to wait it out, but I am still having the issue from #1368 or #1352. I updated, changed my language and region to japanese, and recopied the cookie (I later realized it didn't change anyway).

**Comment by beterhans** [comment]
same here

**Comment by blue-popsicle** [comment]
Same. I was thinking Nandaka might have just not been active since has been ongoing, but it looks like they've contributed to a few other repositories in the last couple of months. Maybe the fix is complicated.

**Comment by 4n0nh4x0r** [comment]
well okay, nvm, seems like it just started working again.  
What i just tried was once again, changing the language on pixiv to japanese, and also in PixivBrowserFactory.py on lines 351 from 
`https://www.pixiv.net/en` to `https://www.pixiv.net` 
and on 372 from `https://www.pixiv.net/` to `https://www.pixiv.net`

**Comment by icedstick** [comment]
@4n0nh4x0r Would you be willing to share your compiled files for those struggling to understand how to use Python. There's unfortunately no guide on how to do this.

**Comment by icedstick** [comment]
@4n0nh4x0r Thanks for replying to me 🙂. I tried doing the steps above and received the following error:
![image](https://github.com/user-attachments/assets/7270c2dc-92a1-47a7-94d7-6852c7456a56)

This was after manually downloading module "demjson3.py" to rectify an error received that this file was missing. I am unable to proceed. I couldn't successfully find where to download the mechanize module it is looking for. 😞

**Comment by blue-popsicle** [comment]
@icedstick 

With Python installed, open a Powershell window. 

Use the following command to navigate to your PixivUtil2-master directory: 
cd Z:\PixivUtil2-master

Run the following command to install all of the requirements from requirements.txt (which includes the "mechanize" module you're missing): 
pip install -r  requirements.txt

**Comment by icedstick** [comment]
@blue-popsicle Thank you, this is the furthest I've gotten so far! I now receive the following errors now that I can run "python PixivUtil2.py":
![image](https://github.com/user-attachments/assets/89474cc6-b1ce-4d7f-8e2e-3aaa8e487787)

I have triple-checked that everything login details and cookie-wise is entered correctly. **Any ideas on how to rectify these errors?**

**Comment by 4n0nh4x0r** [comment]
@icedstick that is the error i got while pixiv was set to english for me.  
it worked after setting it to japanese.  
yea, no clue why, but the language of the site is important, probably some api change that is only applied on a certain language...  
if that doesnt work, make sure you also have the cloudflare token set in your config.

**Comment by icedstick** [comment]
@blue-popsicle & @4n0nh4x0r THANK YOU!!! I replaced the cookie values in config.ini after placing pixiv and fanbox websites into japanese and used firefox to retrieve the cf_clearance token that doesn't appear in chrome. It is working for me now! Thank your for laying it out for a newbie like me to follow.

**Comment by anna-s-h** [comment]
I don't use fanbox, and already made those changes before the update, plus confirmed that they were there after the update.
I have also set my language to japanese
the only thing that's missing is the cf_clearance but I was under the impression that was just for fanbox
I am running this with linux by python, not exe (I guess I could try wine or something...)

**Comment by anna-s-h** [comment]
I found out that my problem was that I had to log out manually and log back in in japanese to refresh the cookie. I can now log in.
