### ISSUE TITLE
Attempts to download public images as /unlisted/ (404 errors)

### ISSUE THREAD

**Issue by wyatt8740** [Nandaka/PixivUtil2#1375]
revision 512687bd09798a7980bc5429cae2ffa4e8977dbd, current git head.
if I attempt downloading all images for a member ID, it tries to download them as if all images were unlisted. This causes 404 errors.
going hack to HEAD~1 (ddb99bf26ed344cf2037c780c027016e5083b341) avoids the issue.

OS is Debian Linux (Sid) with Python 3.12.

**Comment by OozoraHaruto** [comment]
Sorry for the inconvenience caused. Let me look into it and I will create a FIX over the weekend.
