### ISSUE TITLE
50%OFF 闘姫麗辱 緊縛のメヌエット | ＠OZアットオズ　ヒロピン3D #pixiv https://www.pixiv.net/artworks/123920748

### ISSUE THREAD

**Issue by park-dot** [Nandaka/PixivUtil2#1387]
### Prerequisites

* [ ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Log file:** [Attach the `pixivutil.log` file in the application folder, recommended to delete the old file, reproduce the issue, and upload the newly generated file here]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by biggestsonicfan** [comment]
Seven edits and not a single one explains the issue. Incredible.

**Comment by MadProbe** [comment]
It's just an ad if you put the title into a translator.
It'd be better if this issue was renamed, closed and locked
