### ISSUE TITLE
PixivUtil2 don't remmenber Member id 

### ISSUE THREAD

**Issue by eromoe** [Nandaka/PixivUtil2#139]
I select  `Download by member_id` and tried two menber id,  none of them is remmenbered.

I am using Windows 10 x64 and  PixivUtil2.exe.

**Comment by NHOrus** [comment]
Please, elaborate: What to you mean by "Remember member ID"?

**Comment by Nandaka** [comment]
check your config.ini, 
uselist        ==> set to 'True' to parse list.txt. 
                   This will update the DB content from the list.txt
                   (member_id and custom folder).
processfromdb  ==> Set 'True' to use the member_id from the DB.

**Comment by eromoe** [comment]
@Nandaka Sorry for absent these days and no reply soon.

I don't have a list.txt, I only use
``` 
1. Download by member_id
5. Download from online user bookmark
```

But after the images are all download,  I enter
```
d. Manage database >  1. Show all member
```

It show nothing. 

If this is only show when `uselist= True` , please close this issue.

**Comment by Hamuko** [comment]
Pretty sure *5. Download from online user bookmark* downloads from the bookmarks you have on the Pixiv site itself, not in PixivUtil2.

**Comment by Nandaka** [comment]
Option 1: it will not remember the member id to DB. It's by design.
Option 5: it will download images you bookmarked from the website.

You need to use list.txt

**Comment by eromoe** [comment]
Understand, thank you for explanation.
