### ISSUE TITLE
Blacklisting Artists

### ISSUE THREAD

**Issue by CatNeko** [Nandaka/PixivUtil2#140]
When downloading, I want to blacklist some members.
Could be blacklist_members.txt (similar to blacklist_tags.txt)
This would be a useful feature, because I dislike some artists.

**Comment by NHOrus** [comment]
When downloading by tags, you mean?

**Comment by Nandaka** [comment]
logically, it should by tags, or by image bookmarked by other member.

most likely, I will check on image level.
