### ISSUE TITLE
Wont download all the pictures from a specified user

### ISSUE THREAD

**Issue by Mikroft** [Nandaka/PixivUtil2#142]
In multiple situations i noticed that not all user works from the specified user have been downloaded. I think that the problem is in the works with the same name. I assume that whenever two or more works have the same name, only one is downloaded. Please fix this.
Best regards

**Comment by NHOrus** [comment]
Use something like `filenameformat = %artist% (%member_id%)'\%image_id% - %title%` in config.ini to make filenames unique, instead of `%artist% (%member_id%\%urlFilename% - %title%`.

Also, artist names can change, member_id is immutable, so you can have two folders for the same artist with default settings, instead of one.

**Comment by Mikroft** [comment]
Hmmmm.... tried that. Didnt solve the problem. Its not just the problem with the naming, because at the begining if e.g. there are 40 pictures the program says 37 pictures found. What could be the problem here? :/

**Comment by Nandaka** [comment]
which member id? Private images are excluded if you didn't have access to it.

**Comment by Mikroft** [comment]
I know. Pixiv id 1050942. 531 works, says 467 found.

**Comment by Nandaka** [comment]
Do you enable R-18 in pixiv website settings?
![image](https://cloud.githubusercontent.com/assets/836867/17455307/15ddd594-5be6-11e6-997f-ae61ca8d35d3.png)

After changing the pixiv settings, you need to delete the old cookie value in config.ini

**Comment by Mikroft** [comment]
Yes i did, still doesn't work. I noticed the same issue with smaller users(e.g. ~30 works, some of which had the same name).

**Comment by Nandaka** [comment]
Try the latest beta version?

![image](https://cloud.githubusercontent.com/assets/836867/17485736/1d677f0e-5dc1-11e6-86d1-79ad45da0f28.png)

**Comment by Mikroft** [comment]
Works, thx
