### ISSUE TITLE
only process new images compared to db

### ISSUE THREAD

**Issue by GerhardSauer** [Nandaka/PixivUtil2#144]
Is there a way to configure your tool to download only new images and stop processing the current member after it.
The db knows all files of each member and as soon as there are no new images then the next member could be processed.
At the moment all pages are scanned with the already downloaded message.
If there is no option for this, this is a feature request.

By the way thank you very much for this tool I like it very much and I'm happy about the many updates you give.

The reason behind it is, that i have more than 1600 members to be processed and it takes 8+ hours to process them all.

Thanks

**Comment by NHOrus** [comment]
`overwrite = False`
`alwayscheckfilesize = False`
`checkupdatedlimit = 5`

Then it will check that five images aren't in the DB and goes to the next member in the list.
Also, just 8+ hours? That's very fast. I got about 3800 members in the list, full reprocessing took a week...

**Comment by GerhardSauer** [comment]
yes that's it, thank you very much.
I run it every two days. If i add some new members or wait 1 week it will take much longer.
thanks

**Comment by Hamuko** [comment]
Wouldn't it just be easier to use *Download new illust from bookmark*?

**Comment by GerhardSauer** [comment]
I'm using the download from list feature.

**Comment by Hamuko** [comment]
Yeah, that's why it takes so much time.

*Download new illust from bookmark* uses the new images from your followed artists page on Pixiv, so it contains images from newest to oldest from all artists, so you wouldn't have to check each artist one-by-one for new images.

**Comment by GerhardSauer** [comment]
But it looks like, that I have to enter an end page otherwise it runs through all images.

**Comment by Hamuko** [comment]
It'll go to page 200 if you don't specify an end page. I have it going through pages 1-3 every 10 minutes. Works fine for my usage.

**Comment by GerhardSauer** [comment]
Thanks for the advice!
