### ISSUE TITLE
Downloading from multiple members fails if one id does not exist

### ISSUE THREAD

**Issue by greyspammer** [Nandaka/PixivUtil2#147]
When you enter a bunch of member ids to download from, and one of these does not exist (e.g. because the account has been deleted), PixivUtil2 will print a (rather cryptic) error message:

```
Member Url: http://www.pixiv.net/member_illust.php?id=9999&p=1
Traceback (most recent call last):
  File "PixivUtil2.py", line 321, in process_member
  File "PixivModel.pyc", line 52, in __init__
  File "PixivModel.pyc", line 105, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
Error at process_member(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x04115800>)
Dumping html to: Error page for member 9999.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1875, in main
  File "PixivUtil2.py", line 1656, in main_loop
  File "PixivUtil2.py", line 1318, in menu_download_by_member_id
  File "PixivUtil2.py", line 321, in process_member
  File "PixivModel.pyc", line 52, in __init__
  File "PixivModel.pyc", line 105, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.
```

This ends the entire download of all member ids, even if the remaining ones do exist. It is up to the user to identify the problem, remove the member id that does not exist and start the process again with the remainder of the ids.

I propose to:

1. Log the error and try to continue the download if there are member ids left to try.
2. If the process needs to be interrupted, print a more informative message and allow the user to acknowledge the error and then resume the download (see 1.)

**Comment by NHOrus** [comment]
Please, elaborate how do you invoke PixivUtil with multiple members. From command line? With list.txt? From terminal interface, download member?

**Comment by greyspammer** [comment]
Terminal interface, option '1' (download by member id), then enter a couple of ids.

**Comment by Nandaka** [comment]
can you upload the 'Error page for member 9999.html' page?

By right it should handle deleted member, unless they change something.

**Comment by greyspammer** [comment]
You mean this?

[error.zip](https://github.com/Nandaka/PixivUtil2/files/493723/error.zip)

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20160927

**Comment by greyspammer** [comment]
Ok, I tried several ways to break it again, but it just keeps working. Looks like you fixed it.
