### ISSUE TITLE
sometimes doesn't download in biggest size

### ISSUE THREAD

**Issue by Istargazed** [Nandaka/PixivUtil2#159]
![-](https://cloud.githubusercontent.com/assets/22893263/19447083/e6574a1e-9469-11e6-9c4c-72b9c8d39f60.jpg)
![58360084_p3 - c90](https://cloud.githubusercontent.com/assets/22893263/19447091/f0b71b6a-9469-11e6-8a32-3895c7c5ae72.jpg)

for example, I download a image using this program and it gives me 700 x 502 at 245kb. I donwload from another program it gives me a better and bigger image 1200 x 846 at 532kb

**Comment by Nandaka** [comment]
give me the image id? 

The app will only download the original size, not the resized version.

http://i2.pixiv.net/img-original/img/2016/10/11/00/30/01/59417201_p0.png
not  http://i2.pixiv.net/c/600x600/img-master/img/2016/10/11/00/30/01/59417201_p0_master1200.jpg

**Comment by Istargazed** [comment]
I'm downloading by member id, not image id  but here it is 58273991 
so in this case, the original size is the 700 x 502 at 245 kb right?

**Comment by Nandaka** [comment]
It should be 532 KB (545,685 bytes). What is the image url when it parse the page?
![image](https://cloud.githubusercontent.com/assets/836867/19450156/e4a05442-94da-11e6-9f80-fd3e60b0f6b4.png)

![image](https://cloud.githubusercontent.com/assets/836867/19450180/05c7fdd2-94db-11e6-9fcd-53ecfeac2b48.png)

**Comment by Istargazed** [comment]
![143](https://cloud.githubusercontent.com/assets/22893263/19450475/9ba96ac0-9477-11e6-8fda-fe63d90cdd90.PNG)
![capture2433](https://cloud.githubusercontent.com/assets/22893263/19450507/c938a6b8-9477-11e6-8e6a-8761516f5152.PNG)

**Comment by Nandaka** [comment]
rename ```db.sqlite``` to ```db.sqlite.bak``` and retry.

**Comment by Istargazed** [comment]
where is that?

**Comment by Istargazed** [comment]
srry I don't understand

**Comment by Nandaka** [comment]
on the app folder, filesize may vary.

![image](https://cloud.githubusercontent.com/assets/836867/19450706/10eb65da-94dd-11e6-9a33-0425d4dca17a.png)

**Comment by Istargazed** [comment]
yeah I just found it, srry

**Comment by Istargazed** [comment]
![143](https://cloud.githubusercontent.com/assets/22893263/19450855/1341dea4-9479-11e6-90f6-4a4f819c0902.PNG)
now it's fullsized 
but does it work for member id?

**Comment by Nandaka** [comment]
Should be the same, cos internally it will call the same function.
![image](https://cloud.githubusercontent.com/assets/836867/19451103/96766ca8-94de-11e6-8c12-d927e254dc27.png)

**Comment by Istargazed** [comment]
I'm downloading from member id but it's still the same :/

**Comment by Nandaka** [comment]
what is the image url? It should be something like ```http://i1.pixiv.net/img-original/img/2016/08/15/21/13/34/58462144_p5.png```

**Comment by Istargazed** [comment]
![243](https://cloud.githubusercontent.com/assets/22893263/19451973/04b4181c-947d-11e6-94eb-5d58c716678d.PNG)

**Comment by Nandaka** [comment]
hmm, url looks ok. I suspect your internet provider do the compression/resizing.

**Comment by Istargazed** [comment]
rip

**Comment by Nandaka** [comment]
are you using mobile as the internet? anyway, you can use socks5 proxy to avoid isp compression.

Edit config.ini using notepad and set the correct value. You can get free proxy from google search.
```
[Network]
useproxy       ==> Set 'True' to use proxy server, 'False' to disable it.
proxyaddress   ==> Proxy server address, use this format:
		   http://<username>:<password>@<proxy_server>:<port> or
                   socks5://<username>:<password>@<proxy_server>:<port> or
                   socks4://<username>:<password>@<proxy_server>:<port>
```

**Comment by Istargazed** [comment]
No, I'm using a desktop with Ethernet

**Comment by Istargazed** [comment]
can you help me set up one? I don't know how

**Comment by Nandaka** [comment]
Edit config.ini using notepad and set the correct value. You can get free proxy from google search.

[Network]
useproxy       ==> Set 'True' to use proxy server, 'False' to disable it.
proxyaddress   ==> Proxy server address, use this format:
           http://<username>:<password>@<proxy_server>:<port> or
                   socks5://<username>:<password>@<proxy_server>:<port> or
                   socks4://<username>:<password>@<proxy_server>:<port>
