### ISSUE TITLE
Sometimes pixiv doesn't download everything 

### ISSUE THREAD

**Issue by Istargazed** [Nandaka/PixivUtil2#160]
I tried running the member id multiple time (I even deleted the all the images before hand) but it just gives me the folder picture

**Comment by Nandaka** [comment]
1. check your pixiv website settings and delete the cookie value in config.ini, then retry.
![image](https://cloud.githubusercontent.com/assets/836867/19447348/ad3de858-94cf-11e6-99b9-ef2079cb0c85.png)
2.  Check the value of ```r18mode``` in config.ini. Setting it to True will *only* download R-18 images.

**Comment by Istargazed** [comment]
Thanks!

**Comment by chronometric** [comment]
Yay for simple solutions that make everyone happy! :+1: 

It's probably a feature of every artist-direct site API, but it might deserve a line in the first section of the FAQ just to make sure hoarding overachievers didn't miss that chapter xD
