### ISSUE TITLE
Error handling old method of image aquisition [not whitecube]

### ISSUE THREAD

**Issue by vampiricwulf** [Nandaka/PixivUtil2#161]
global name 'image_id' is not defined
I'm running from current source.
filenameformat = %image_id% - %artist% - %title%

**Comment by Nandaka** [comment]
Are you using whitecube ui? latest commit might have bug for whitecube.

**Comment by vampiricwulf** [comment]
Nope, and I'm using the same configs I have been for the past year. Haven't touched the cookie. Haven't had to.
```
[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
userobots = True
timeout = 60
retry = 3
retrywait = 5

[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = False

[IrfanView]
irfanviewpath = C:\Program Files\IrfanView
startirfanview = False
startirfanslide = False
createdownloadlists = False

[Settings]
filenameformat = %image_id% - %artist% - %title%
filenamemangaformat = %image_id% - %artist%/%image_id% - %artist% - %title% - %page_number%
downloadlistdirectory = C:\PixivUtil2\
uselist = True
processfromdb = True
overwrite = False
tagsseparator = ,
daylastupdated = 0
rootdirectory = .
alwayscheckfilesize = False
checkupdatedlimit = 0
downloadavatar = False
createmangadir = True
usetagsasdir = False
useblacklisttags = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = False
datediff = 0
backupoldfile = False
writeugoirainfo = False
createugoira = True
deletezipfile = True
enableinfiniteloop = False
verifyimage = False
writeurlindescription = False
urlblacklistregex = 
urldumpfilename = url_list_%Y%m%d
dbpath = 
creategif = True
useblacklistmembers = False

[Authentication]
username = vampiricwulf
password = master
cookie = 6872988_013f0cbf1e12ae340670c9fcf845fc7d
keepsignedin = 1

[Pixiv]
numberofpage = 0
r18mode = False
dateformat = ''
```

**Comment by vampiricwulf** [comment]
Thanks for the quick edit, was just doing that.

**Comment by Nandaka** [comment]
can you give the stacktrace or log file?

**Comment by vampiricwulf** [comment]
http://pastebin.com/VFVgnrTA
How would I produce a stacktrace?

**Comment by Nandaka** [comment]
just run the app and copy the console output. It should show which line of code is failing.

**Comment by vampiricwulf** [comment]
I run from the source (python PixivUtil2.py), I'm looking at it right now, no lines of output that provide any sort of error message other than what you already see.

**Comment by Nandaka** [comment]
ok, do you have the imageid, so I can test?

**Comment by vampiricwulf** [comment]
There's some located in the pastebin, and it's not limited to just those, it's all images that give me that error.

One of the image_ids: 59634164

**Comment by vampiricwulf** [comment]
I can confirm it works on commit e6d2beeaa7b04b4c8c115a700ce9a9e2829a27e4

**Comment by Nandaka** [comment]
hmm, it is because whitecube then. I'll check it.

**Comment by vampiricwulf** [comment]
I'm going to assume it to be this line:
https://github.com/Nandaka/PixivUtil2/commit/9d9f232b080a9e00508c1c7bb6fe93095c951f71#diff-30eb981ce68adac654c4cdeb81b2924cR272

**Comment by Nandaka** [comment]
try the latest commit, it should be fixed for non-whitecube

**Comment by vampiricwulf** [comment]
Looks like it works!
