### ISSUE TITLE
”5. Download from online user bookmark  ” not worked

### ISSUE THREAD

**Issue by eromoe** [Nandaka/PixivUtil2#166]
I am using pixivutil20161012 release.
```
Input: 5
Include Private bookmarks [y/n/o]:
Start Page (default=1):
End Page (default=0, 0 for no limit):
Importing Bookmarks...
Exporting page 1
Source URL: http://www.pixiv.net/bookmark.php?type=user&p=1
using default DB Path: E:\PixivUtil2\db.sqlite
Reading E:\PixivUtil2\config.ini ...
done.
No more data
Result:  0 items.
PixivDownloader2 version 20161012
```

I found there is a commit about bookmark e196e80cdd580de2d310342f2568b2022bb76aa8
Is it has some problem to release this version ? Do you need any help?

**Comment by Nandaka** [comment]
are you using the new ui (whitecube)? current release doesn't support it yet, but the latest commit have partial support for it.
