### ISSUE TITLE
Cannot parse tag in option 3 and 7

### ISSUE THREAD

**Issue by joshuaavalon** [Nandaka/PixivUtil2#167]
Version: v20161012

Output
```
Input: 3
Tags: ご注文はうさぎですか?
Bookmark Count: 1000
Use Partial Match[y/n]: n
Oldest first[y/n]: y
Start Page (default=1): 1
End Page (default=0, 0 for no limit): 5
Start Date [YYYY-MM-DD]: 2016-01-01
End Date [YYYY-MM-DD]: 2016-11-10
Reading C:\***\pixivutil20161012\config.ini ...
done.
Searching for: (ご注文はうさぎですか?) %E3%81%94%E6%B3%A8%E6%96%87%E3%81%AF%E3%81%86%E3%81%95%E3%81%8E%E3%81%A7%E3%81%99%E3%81%8B%3F
Looping... for http://www.pixiv.net/search.php?s_mode=s_tag_full&word=%E3%81%94%E6%B3%A8%E6%96%87%E3%81%AF%E3%81%86%E3%81%95%E3%81%8E%E3%81%A7%E3%81%99%E3%81%8B%3F&p=1&scd=2016-01-01&ecd=2016-11-10&order=date
Error at process_tags(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x03D55648>)
Dumping html to: Error page for search tags %E3%81%94%E6%B3%A8%E6%96%87%E3%81%AF%E3%81%86%E3%81%95%E3%81%8E%E3%81%A7%E3%81%99%E3%81%8B%3F.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1879, in main
  File "PixivUtil2.py", line 1664, in main_loop
  File "PixivUtil2.py", line 1397, in menu_download_by_tags
  File "PixivUtil2.py", line 784, in process_tags
  File "PixivModel.pyc", line 860, in parseTags
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by Nandaka** [comment]
can you upload the file: 'Error page for search tags
%E3%81%94%E6%B3%A8%E6%96%87%E3%81%AF%E3%81%86%E3%81%95%E3%
81%8E%E3%81%A7%E3%81%99%E3%81%8B%3F.html' to mediafire?

Are you using the new UI?

**Comment by joshuaavalon** [comment]
Yes, I am using the the UI. I have try to switch it back on Chrome but it does not seems to work.
[Error page for search tags.zip](https://github.com/Nandaka/PixivUtil2/files/583805/Error.page.for.search.tags.zip)

**Comment by Nandaka** [comment]
New UI not supported yet. Latest code only support option 1&2.

**Comment by joshuaavalon** [comment]
How do I fallback to old UI? I mean I tried to use the button in the bottom right which can revert back to old UI in Pixiv. But it still throws the same error.

**Comment by Nandaka** [comment]
Are you able to revert to the old ui in the website? If yes, then you might need to delete the cookie value in the config.ini using notepad

**Comment by joshuaavalon** [comment]
There is a button on the bottom right to switch between two UI. I will try it later today.

**Comment by Nandaka** [comment]
If possible, please take a screen shot for that button and upload it here :smile:

**Comment by joshuaavalon** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7152420/20208098/b6d50120-a826-11e6-9c61-587b5b9099ae.png)

**Comment by joshuaavalon** [comment]
Ok, It seems that it works. First, you have to switch back to old UI. Then, remove cookie from config.ini. It will works like a charm. But if you switch back to new UI, you have to go back to the first step again.
