### ISSUE TITLE
Error 9002 when downloading profile image

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#168]
Processing Member Id: 20584792
Reading /home/nho/workshop/PixivUtil2/config.ini ...
done.
Page  1
R-18 Mode only.
Member Url: http://www.pixiv.net/member_illust.php?id=20584792&p=1&tag=R-18
Member Name  : リーベーク
Member Avatar: http://i4.pixiv.net/user-profile/img/2016/10/27/09/25/57/11672299_262280998344ba788a7e1908a8038a16_170.jpg
Member Token : jolraseda
Checking local filename... Getting remote filesize...
Using Referer:
[download_image()] HTTP Error: HTTP Error 403: Forbidden at http://i4.pixiv.net/user-profile/img/2016/10/27/09/25/57/11672299_262280998344ba788a7e1908a8038a16_170.jpg
Traceback (most recent call last):
  File "PixivUtil2.py", line 79, in download_image
    res = __br__.open_novisit(req)
  File "build/bdist.linux-x86_64/egg/mechanize/_mechanize.py", line 199, in open_novisit
    return self._mech_open(url, data, visit=False, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 403: Forbidden
Error at download_image(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0x7f93064c26d0 whose wrapped object = <closeable_response at 0x7f930620fb48 whose fp = <response_seek_wrapper at 0x7f930620f950 whose wrapped object = <closeable_response at 0x7f930620f908 whose fp = <socket._fileobject object at 0x7f93067b4d50>>>>>, <traceback object at 0x7f930620fab8>) at http://i4.pixiv.net/user-profile/img/2016/10/27/09/25/57/11672299_262280998344ba788a7e1908a8038a16_170.jpg (9002)

**Comment by Nandaka** [comment]
Looks like it require Referer now.
