### ISSUE TITLE
Problem: global name 'PixivHelper' is not defined

### ISSUE THREAD

**Issue by Xylion** [Nandaka/PixivUtil2#170]
Hello,
I just downloaded the software and tried to do a research by member_id.
It worked but while processing the images I have that:

Processing Image Id: XXXX
Image ID (XXXX): global name 'PixivHelper' not defined

And then it process another image.

![error](https://cloud.githubusercontent.com/assets/23428075/20243746/b472c810-a964-11e6-9d2f-d703ceaace97.png)

**Comment by Nandaka** [comment]
Are you using custom datetime format in `config.ini`?

**Comment by Nandaka** [comment]
can you try: https://github.com/Nandaka/PixivUtil2/releases/tag/v20161113b

**Comment by Xylion** [comment]
Yes I use a custom datetime as the program didn't recognized the datetime used in the images I wanted.
I tried your new version and now I have this:

![error2](https://cloud.githubusercontent.com/assets/23428075/20246374/f1b4ced4-a9b5-11e6-8ffe-cc171f21add4.png)

**Comment by Nandaka** [comment]
What is the value for your custom datetime format?
Ensure it is matching with the datetime format in your current pixiv website.

```
dateformat   ==> Pixiv DateTime format, leave blank to use default format for
                 English or Japanese. Refer to http://strftime.org/ for syntax.
		 Quick Reference:
		 %d = Day, %m = Month, %Y = Year (4 digit), %H = Hour (24h)
		 %M = Minute, %S = Seconds
```

**Comment by Xylion** [comment]
Date format is for example 1 11 2016 8:34
I wrote that in config.ini

![dateformat](https://cloud.githubusercontent.com/assets/23428075/20247500/19b3cb34-a9ce-11e6-96ab-d4eb0c864e44.png)

**Comment by Nandaka** [comment]
January or November? also, try to remove the `-` as your sample doesn't have it. 

It should be matching with what pixiv use.

**Comment by Xylion** [comment]
Ah thank you it was the - that didn't work. I wrote it because in the message given by the program it was written.

Thank you very much.

**Comment by Nandaka** [comment]
Anyway, there is small typo on the error handling. I've updated the zip file. https://github.com/Nandaka/PixivUtil2/releases/tag/v20161113b
