### ISSUE TITLE
Excessive false positive R-18 tags when downloading in whitecube

### ISSUE THREAD

**Issue by Kilo19** [Nandaka/PixivUtil2#171]
I got R-18 tags for almost every all-age image I download.

**Comment by Kilo19** [comment]
![pixivutil](https://cloud.githubusercontent.com/assets/10566821/20447366/66cf846c-adac-11e6-81c5-d4e127e54687.png)

**Comment by Nandaka** [comment]
You need to disable the R-18 from your pixiv website configuration and delete the old cookie value in config.ini?

**Comment by Kilo19** [comment]
I still want to download R-18 at the same time as all-age, but have R-18 tags for R-18 images only.

**Comment by Nandaka** [comment]
hmm, r18mode=True in config.ini will only download R-18 tagged images, not the other way around.

If you want to enable/disable R-18, you need to change it from the website.
![image](https://cloud.githubusercontent.com/assets/836867/20457257/46d824b8-aec2-11e6-8446-58fc8fe2accf.png)

If you are using download by Tags, you can use `NOT R-18` in the query.

**Comment by Nandaka** [comment]
fixed in https://github.com/Nandaka/PixivUtil2/releases/tag/v20161124
