### ISSUE TITLE
R-18G toggle?

### ISSUE THREAD

**Issue by udw82145** [Nandaka/PixivUtil2#172]
I can respect why r18mode excludes all other "R-18'X'" tags, but could you please add a config mode to download these too? 

Alternatively, if you could add an option to download by 'list + tags', then this will solve similar requests.

Much love ❤👊

**Comment by Nandaka** [comment]
R18mode in config.ini will download only R-18* tagged images.

Check your configuration on the Pixiv website and delete your cookie value in config.ini after updating.
![image](https://cloud.githubusercontent.com/assets/836867/20457234/aee001ee-aec1-11e6-88b1-62ee8d41e34a.png)

**Comment by udw82145** [comment]
So I tested this again with a freshly-made account, a new zip of the latest release, corrected my view settings as above, reloaded my cookie by signing out and in, then double-checking the view settings.
I set r18mode to true, turned off processfromdb and set daylastupdated to 0, and no other changes except login u/p and the new cookie.

I picked at random this(19719856) user to test R-18G tags, and this(237010) user to test R-18? tags.
I tried with both modes 1 (by member id), and 4 (from list.txt). 

No matter what I did **only R-18 images were downloaded**. Even if they were double tagged as R-18 and R-18'X', they downloaded, but _only_ if they had an R-18 tag too.

Feel free to test this yourself, it takes about 20 mins to do everything 👍

**Comment by Nandaka** [comment]
> I set r18mode to true, turned off processfromdb and set daylastupdated to 0, and no other changes except login u/p and the new cookie.
> No matter what I did only R-18 images were downloaded.

Off course it will only download the R-18.

Like I said, if you set `r18mode=True`, it will only download R-18 images.
If you set `r18mode=False`, it will download all images (including R-18).

**Comment by udw82145** [comment]
Except, what I'm saying is that the R-18G images ARE NOT downloaded when r18mode=True

Only the R-18 images, and not the R-18G are being downloaded in this mode. See for yourself.

**Comment by Nandaka** [comment]
Ahh, no wonder. It is no supported by pixiv 
tried below query, it doesn't return any images.

- oldui
http://www.pixiv.net/member_illust.php?id=19719856&tag=R-18%20OR%20R-18G

- whitecube
https://www.pixiv.net/rpc/whitecube/index.php?mode=user_new_unified&id=19719856&offset_illusts=0&offset_novels=0&limit=50&tt=*yourtoken*&tag=R-18%20or%20R-18G

**Comment by udw82145** [comment]
So erm, could you please add an r18gmode, or make an option to download by 'list + tag(s)' ?

**Comment by Nandaka** [comment]
Modify the option 4. You can set the tag to be downloaded from the member id list.

If no tag given/empty string, it will download all image (older behaviour)

**Comment by udw82145** [comment]
Thanks ever so much!!

**Comment by NHOrus** [comment]
And this thing breaks my automation now...

**Comment by Nandaka** [comment]
```
4 - Download from list
(optional: followed by path to list and optional tag)
```

should be the same: ```PixivUtil2.py -s 4 -x``` or ```PixivUtil2.py -s 4 tag_here -x```

**Comment by NHOrus** [comment]
Ah. Missed that line.

It just didn't get that it needs to use default if there's no tag... But that's fixed now.

**Comment by NHOrus** [comment]
The tag feature interacts with r18mode = true.

**Comment by Nandaka** [comment]
yep, no changes for that as I'm using it 😄

**Comment by NHOrus** [comment]
No, I think it overwrote my pre-set tag? Will test tomorrow and, if doubts remains, elaborate in separate issue.

**Comment by Nandaka** [comment]
crap copy paste error 

whitecube ==> OK
https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L357

oldui ==> Not OK.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L376

**Comment by Nandaka** [comment]
updated on https://github.com/Nandaka/PixivUtil2/releases/tag/v20161207

**Comment by reyaz006** [comment]
How should I update my command line to make it stop asking for tags? My current line is "-s -4 -x".

**Comment by Nandaka** [comment]
Try PixivUtil2.py -s 4 tag_here -x

**Comment by reyaz006** [comment]
Do you mean it? I haven't found the "tag_here" in the code or readme. Do you mean that I should put some tag there or that any non-valid tag would make it not look for tags? I need the old behavior for now.

**Comment by Nandaka** [comment]
woops missing one argument, it is expecting the list.txt file as the first
argument, then followed by optional tag, else it will go to the "Tag : "
line and use the default list.txt location

try
- PixivUtil2.py -s 4 *list.txt* -x
- PixivUtil2.py -s 4 *list.txt* tag_here -x
- PixivUtil2.py -s 4 tag_here -x

**Comment by reyaz006** [comment]
Ok, so it seems "-s 4 list.txt -x" worked. Thanks.
