### ISSUE TITLE
Custom file name for avatar images?

### ISSUE THREAD

**Issue by dajrm89** [Nandaka/PixivUtil2#174]
Is it possible to add the ability to create a custom naming format for profile images (avatars) instead of the generic "folder.jpg" to the config.ini?

**Comment by Nandaka** [comment]
fixed name or using some formatting??

only below format make senses for custom format:
- %member_token%    ==> member token, doesn't change.
- %member_id%    ==> member id, in number.
- %artist%              ==> artist name, may change.
- %urlFilename%   ==> the actual filename stored in server without the file extensions.
- %date%              ==> current date in YYYYMMMDD format.

**Comment by dajrm89** [comment]
Formatting would be ideal.

**Comment by Nandaka** [comment]
set ```avatarNameFormat``` in config.ini. 

Refer to readme.txt for available format
