### ISSUE TITLE
Member folders no longer being created

### ISSUE THREAD

**Issue by Shinobikens** [Nandaka/PixivUtil2#175]
Before whitecube, the util would automatically create a folder called membername (member id) in the root directory when downloading images from that user for the first time (it would also automatically save all new downloaded images to their repsective folders). It's no longer doing this and instead just dumping all the images into the root directory without creating a folder. I've tried creating a list but that doesn't do anything either. Did updating for whitecube support break this or am I doing something wrong?

**Comment by Nandaka** [comment]
what is your filename format in config.ini? I tried to download image (option 2, image id=60107053) and the folder is created properly.

```
Input: 2
Image ids: 60107053
Processing Image Id: 60107053
Title: delicious♥
Tags : オリジナル, ハロウィン, 食べ物, 飲み物
Date : 2016-11-26 00:00:00
Mode : big
Image URL : https://i2.pixiv.net/img-original/img/2016/11/26/00/00/04/60107053_p0.png
Filename  : D:\Temp\Pixiv2\83739 blacklack-21\whitecube 60107053_p0 - delicious♥ - 83739 blacklack-21 オリジナル　ハロウィン　食べ物　飲み物.png
Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=60107053
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=60107053
Creating directory: D:\Temp\Pixiv2\83739 blacklack-21                                                                                                             2664057 of   2664057 Bytes  Completed in 4.698s (553.77 KiB/s)
 Image verified.
```

**Comment by Shinobikens** [comment]
filenameformat = %urlFilename%
filenamemangaformat = %urlFilename%

I guess that might be the issue if your worked fine

**Comment by Nandaka** [comment]
yep, you need to use the correct format, e.g. ```%member_token% (%member_id%)\%urlFilename%```.

Check the readme for more details.
