### ISSUE TITLE
Unable to run from source code

### ISSUE THREAD

**Issue by momoe** [Nandaka/PixivUtil2#176]
I've pulled the latest version from github, and when trying to run the usual 'python PixivUtil2.py' I get the following error...
``Traceback (most recent call last):
  File "PixivUtil2.py", line 25, in <module>
    import PixivConfig
  File "/mnt/windows/Downloads/Mozilla Firefox/Pictures/pixiv/pixivutil2-master/PixivUtil2/PixivConfig.py", line 7, in <module>
    import PixivHelper
  File "/mnt/windows/Downloads/Mozilla Firefox/Pictures/pixiv/pixivutil2-master/PixivUtil2/PixivHelper.py", line 17, in <module>
    import imageio
ImportError: No module named imageio
``

**Comment by Hamuko** [comment]
```
import imageio ImportError: No module named imageio
```
You're missing the `imageio` module. I suggest you read up on [virtual environments](http://docs.python-guide.org/en/latest/dev/virtualenvs/) and then use `pip install imageio` to install the missing module. I suggest using a virtual environment so all of your installs are contained in it and there's a much smaller chance of you messing up anything not relating to PixivUtil.

**Comment by Nandaka** [comment]
use ```pip install -r requirements.txt``` for the required libraries.

**Comment by Momoe** [comment]
Okay, I guess that is a new requirement since the previous version I was using. Will try that

**UPDATE** 
Installed the imageio applet and the script is running. I am able to loging and function, but am given a warning error before the login. Will paste that at my next oppertunity. Thanks @Hamuko @Nandaka  community.

**Comment by Hamuko** [comment]
I imagine it would make sense to rework `setup.py` at some point to also work on POSIX systems so that you can install PixivUtil using pip and automatically resolve new dependencies and their versions when upgrading with `pip install --upgrade`.

**Comment by Nandaka** [comment]
I don't have linux system, and the setup.py is more for py2exe usage. 

Not sure how to do it in linux system.

**Comment by Hamuko** [comment]
I could take a look if I could whip up a `setup.py` that works well with both pip and py2exe. I have a virtual Windows 10 installation I can test it out with. That way PixivUtil2 could be uploaded to PyPI in the future so installing it on POSIX systems could be as easy as `pip install PixivUtil2`.
