### ISSUE TITLE
Custom %date% options for Filenameformat and Filemanganameformat 

### ISSUE THREAD

**Issue by Arcadius34** [Nandaka/PixivUtil2#177]
Hello, the current %date% option for filenameformat and filemanganameformat can be a little difficult to read when there are many folders being made for sorting reasons.
 
Would it be possible to add a "-" between the YYYYMMDD so it's YYYY-MM-DD instead or YYYY_MM_DD. Either way is fine, though I prefer dashes instead of underscores.

**Comment by Nandaka** [comment]
use ```%date_fmt{format}% ```
```
   Current date using custom format.
   Use Python string format notation, refer: https://goo.gl/3UiMAb
   e.g. %date_fmt{%Y-%m-%d}%
```
