### ISSUE TITLE
Is there a way of downloading all the entries from a contest?

### ISSUE THREAD

**Issue by periflo90** [Nandaka/PixivUtil2#179]
For example, if I wanted to download all images from a contest, like [this one](http://www.pixiv.net/contest/persona20th) I want to know if it would be possible to download them all with the current version of the program and if not, if it would be possible to implement that function.

Thanks in advance.

**Comment by Nandaka** [comment]
use this tag: ペルソナシリーズイラコン

**Comment by LVNDSCAPE** [comment]
sorry to Ninja but I dont wanna create a new thread for asking a simple question.

How do I separate tags while using the download by member id and tags?

**Comment by NHOrus** [comment]
Elaborate, please? Different tags into different directories? You need something like `filenameformat = %member_id% - %tag%\%image_id% - %title%

**Comment by LVNDSCAPE** [comment]
![image](https://cloud.githubusercontent.com/assets/23572961/21504896/07e8e0de-cc91-11e6-9bc4-64ab08665025.png)
 number 10 option
I would type in member ID then can I use multiple tags to filter out?

**Comment by Nandaka** [comment]
Nope, it only support single tag.

It use the member_illust url, e.g. 
http://www.pixiv.net/member_illust.php?id=6996493&tag=VOCALOID

using 2 tag will return nothing, e.g.
http://www.pixiv.net/member_illust.php?http://www.pixiv.net/member_illust.php?id=6996493&tag=VOCALOID 初音ミク

**Comment by LVNDSCAPE** [comment]
Thank you!
![image](https://cloud.githubusercontent.com/assets/23572961/21523277/13301f7a-cd3b-11e6-8e71-966e7be43ef9.png)

Also, can the 2nd option download by image ID support multiple IDs?
I tried using comma but I got an error.
ID: ????? ,????? is not valid.

**Comment by Nandaka** [comment]
use space as separator

**Comment by periflo90** [comment]
Thank you, Nandaka! Worked like a charm.
