### ISSUE TITLE
Getting back to options menu?

### ISSUE THREAD

**Issue by LVNDSCAPE** [Nandaka/PixivUtil2#180]
Is there a way to go back to where you choose the download options by member_id,image_id, etc after choosing a wrong one?

for example I accidentally chose group id. How do I get back to the options without restarting the program? 

![iv3vow7](https://cloud.githubusercontent.com/assets/23572961/21475752/5619b3e8-cb5e-11e6-8c94-e86f2b59cbce.png)

**Comment by NHOrus** [comment]
Try Ctrl-C.

**Comment by LVNDSCAPE** [comment]
Thank you.
