### ISSUE TITLE
Can not login using password

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#181]
Using lastest release version.
With cookie:
`Trying to log with saved cookie
Error at doLogin(): (<class 'httplib.BadStatusLine'>, BadStatusLine("''",), <traceback object at 0x039DEE18>)
Cannot Login!`

Without cookie:
`Logging in...
Unknown login issue, please use cookie login method.`

**Comment by NHOrus** [comment]
Can you login on site?

**Comment by whinette** [comment]
Yeah, works correctly.

**Comment by Nandaka** [comment]
weird, I can login just fine in my pc.

Looks like the server returning empty response, that's why the app throws bad status line error.
If you are using antivirus/firewall, ensure the application has access to the internet.

**Comment by whinette** [comment]
Nice hunch, my av updated to a new version yesterday, I will check it out.

**Comment by whinette** [comment]
And that was it. Thanks.

**Comment by NHOrus** [comment]
Weirdly, I need to report that I suffer from second half - unable to login with password.  
Cookie method works.
