### ISSUE TITLE
Encoding issue with BeautifulSoup

### ISSUE THREAD

**Issue by lunusvir** [Nandaka/PixivUtil2#184]
Hi Nandaka, 

When I was downloading some images (for example, illust_id=59140460), in the function 'getImagePage' BeautifulSoup converted utf-8 encoded content (var 'response') to a mess with HTML entities (var 'parsed'). Likely BeautifulSoup was confused by some characters (have no idea what) and treated the page as other encoding. It only happened on some of my computers, so I am not sure if the problem is repeatable with the illust_id above. 

I tried adding 'Accept-Charset: utf-8' to request header and passing the content by 
`BeautifulSoup(response.decode('utf-8'))`. Then it ran well. Not sure if that solution is ugly (XD) or not, and looking for a official fix maybe either on your side or on BeautifulSoup's. 

Thanks.

**Comment by Nandaka** [comment]
try: https://github.com/Nandaka/PixivUtil2/releases/tag/v20170105-beta3 ?
