### ISSUE TITLE
Names decoding incorrectly

### ISSUE THREAD

**Issue by vampiricwulf** [Nandaka/PixivUtil2#186]
http://www.pixiv.net/member_illust.php?mode=medium&illust_id=59679440
🎃 decodes as `đ&Yuml;&#x17D;&fnof;`
According to the UTF page, it should decode as ` &#127875;`
This happens to a lot of this member's works.
Here's the page about the character: http://www.fileformat.info/info/unicode/char/1f383/index.htm

**Comment by vampiricwulf** [comment]
```python
>>> a = "������"
>>> a
'\xf0\x9f\x8e\x83'
>>> print a
🎃
```

**Comment by vampiricwulf** [comment]
Using http://stackoverflow.com/questions/701704/convert-html-entities-to-unicode-and-vice-versa/701722#701722

```python
>>> from BeautifulSoup import BeautifulStoneSoup
>>> import cgi
>>> def HTMLEntitiesToUnicode(text):
...     """Converts HTML entities to unicode.  For example '&amp;' becomes '&'."""
...     text = unicode(BeautifulStoneSoup(text, convertEntities=BeautifulStoneSoup.ALL_ENTITIES))
...     return text
...
>>> def unicodeToHTMLEntities(text):
...     """Converts unicode to HTML entities.  For example '&' becomes '&amp;'."""
...     text = cgi.escape(text).encode('ascii', 'xmlcharrefreplace')
...     return text
...
>>> text = "������"
>>> print text
🎃
>>> uni = HTMLEntitiesToUnicode(text)
>>> htmlent = unicodeToHTMLEntities(uni)>>> htmlent = unicodeToHTMLEntities(uni)
>>> print uni
🎃
>>> print htmlent
&#127875;
```

**Comment by Nandaka** [comment]
Weird, I tried the latest update and it able to name the file properly.

![image](https://cloud.githubusercontent.com/assets/836867/21674474/7bb27e78-d360-11e6-97a9-046e19df3685.png)

I'm using Win10 with language for non-unicode set to Japanese
![image](https://cloud.githubusercontent.com/assets/836867/21674515/a0ada450-d360-11e6-8ce4-aae9fc6ea20f.png)

**Comment by Nandaka** [comment]
might be related to #184

**Comment by vampiricwulf** [comment]
I see what it might be...
I swapped to using Bash for Windows but it installs Python 2.7.6 from apt-get and I can't get it to compile Python 2.7.13 because _hashlib keeps breaking for some reason (_ssl works fine...).
Guess I'll go back to running it through cmd...
