### ISSUE TITLE
Downloading avatar

### ISSUE THREAD

**Issue by brodycas3** [Nandaka/PixivUtil2#187]
Why does it also download an artists avatar?

**Comment by NHOrus** [comment]
Because it's enabled by default in config file. Try

    downloadavatar = False

**Comment by brodycas3** [comment]
Thanks, I was looking in the config.ini when I saw this, https://u.nya.is/xjmnkf.png

Does it just know what image viewer is using or is there some sort of integration going on?

**Comment by NHOrus** [comment]
As far as I know, it's hardcoded to use that one image viewer, because only it can open images from list.

Great ability, btw.

**Comment by brodycas3** [comment]
Yeah I actually use that image viewer
