### ISSUE TITLE
It is impossible to download pictures.

### ISSUE THREAD

**Issue by Shadow090102** [Nandaka/PixivUtil2#189]
It is impossible to download pictures. Everywhere there are mistakes. When downloading an album only the avatar is downloaded. What i do wrong?    ![image](https://cloud.githubusercontent.com/assets/25252455/22160116/cc0aec3c-df65-11e6-8a06-51a550a2b218.png)

**Comment by vampiricwulf** [comment]
Looks like you're trying to match MDY to YMD.

**Comment by Shadow090102** [comment]
And what should I do? I am not a programmer.

**Comment by vampiricwulf** [comment]
Post your config.ini (minus the authentication section)

**Comment by Nandaka** [comment]
update your config.ini on [pixiv] section.

```
dateformat   ==> Pixiv DateTime format, leave blank to use default format for
                 English or Japanese. Refer to http://strftime.org/ for syntax.
		 Quick Reference:
		 %d = Day, %m = Month, %Y = Year (4 digit), %H = Hour (24h)
		 %M = Minute, %S = Seconds
```

**Comment by Shadow090102** [comment]
Thank you very much!) ![image](https://cloud.githubusercontent.com/assets/25252455/22173276/665b85a2-dfdf-11e6-9d44-5dd96d862459.png)

**Comment by vampiricwulf** [comment]
You might wanna delete that image, a cookie can still be used to log in as you.

**Comment by Shadow090102** [comment]
What now not so? ( ![image](https://cloud.githubusercontent.com/assets/25252455/22174054/5a5759e0-dff6-11e6-992c-67e351fa352a.png)

**Comment by Shadow090102** [comment]
What should be written that he read also %d %m %Y, %H: % M and %m %d %Y, %H: % M ?

**Comment by Shadow090102** [comment]
dateformat =  %m %d %Y, %H:%M
