### ISSUE TITLE
Question on formating of rootdirectory

### ISSUE THREAD

**Issue by Grenaid** [Nandaka/PixivUtil2#191]
Thanks for help in advance, I'm pretty sure this is my own fault.

My goal is to have Pixiv Downloader in one folder, but downloading files into another, distant, folder named !Artist, on the same partition.  Until recently this worked, and I can't figure out what changed.  I'm using version 20161231.

PxivUtil.exe is in  `I:\Rip\ani\Tools\pixivutil`, and here is my rootdirectory as set in config:

`rootdirectory = I:\Rip\ani\CG\!Artist\`

I'd like Pixiv to save all artists from list.txt to that location.  However, if I use `1234 .\Rainbows` in list, it dumps it in pixiv.  And if I use `1234 %root%\Rainbows`,  it dumps it in I:\Rainbows.

How can I configure it to put it in "I:\Rip\ani\CG\!Artist\Rainbows\1234" short of using the full path every time?

Filename in case it's relevant:

```
filenameformat = %artist% (%member_id%)\%urlFilename% - %title%
filenamemangaformat = %artist% (%member_id%)\%urlFilename% - %title%
```
Thanks for the help.

**Comment by Nandaka** [comment]
just to clarify:

Your [list.txt]
1234 %root%\Rainbows
4567 %root%\Rainbows2


[config.ini]
rootdirectory = I:\Rip\ani\CG\!Artist\
filenameformat = %artist% (%member_id%)\%urlFilename% - %title%
filenamemangaformat = %artist% (%member_id%)\%urlFilename% - %title%

it should produce something like
I:\Rip\ani\CG\!Artist\Rainbows\artistName (1234)\urlFilename - title.jpg
I:\Rip\ani\CG\!Artist\Rainbows2\artistName2 (4567)\urlFilename2 - title2.jpg

Is that you want?

**Comment by Grenaid** [comment]
Yes.  Currently however, even with 

[config.ini]
rootdirectory = I:\Rip\ani\CG\!Artist\

1234 %root%\Rainbows

Produces the same thing as 

1234 \Rainbows

That is to say, they both make:

I:\Rainbows
