### ISSUE TITLE
Syntax error on Linux, PixivUtil2 does not start

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#192]
Using git-cloned 77c44a437936b4fa77cb535b7dbb5aa9a11464c1

```python
  File "PixivUtil2.py", line 350
    if list_page in not None:
                      ^
SyntaxError: invalid syntax
```

**Comment by Nandaka** [comment]
woopsss

**Comment by NHOrus** [comment]
Yes, patch is trivial, but still annoying.

**Comment by NHOrus** [comment]
>Showing  0 changed files  with 0 additions and 0 deletions.

I do not thing this patch does that you promise it does.

**Comment by NHOrus** [comment]
Was wrong. This issue is fixed. But now new one appears!

```python
File "PixivUtil2.py", line 1886
    if __name__ == '__main__' asd:
                                ^
SyntaxError: invalid syntax
```

**Comment by Nandaka** [comment]
aahahaha, forgot to remove that
