### ISSUE TITLE
Problems with py2exe under Linux

### ISSUE THREAD

**Issue by arisboch** [Nandaka/PixivUtil2#193]
I had the following problems with installing PixivUtil2 under Linux:

It demands the module py2exe, which won't install under python2.7 and when I install it with python3 and try to run the install script, it gives me the following error:

```
#Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import py2exe
  File "/usr/local/lib/python3.5/dist-packages/py2exe/__init__.py", line 9, in <module>
    patch_distutils()
  File "/usr/local/lib/python3.5/dist-packages/py2exe/patch_distutils.py", line 68, in patch_distutils
    from . import distutils_buildexe
  File "/usr/local/lib/python3.5/dist-packages/py2exe/distutils_buildexe.py", line 91, in <module>
    from . import runtime
  File "/usr/local/lib/python3.5/dist-packages/py2exe/runtime.py", line 3, in <module>
    from .dllfinder import Scanner, pydll
  File "/usr/local/lib/python3.5/dist-packages/py2exe/dllfinder.py", line 5, in <module>
    from . import _wapi
  File "/usr/local/lib/python3.5/dist-packages/py2exe/_wapi.py", line 4, in <module>
    _kernel32 = WinDLL("kernel32")
NameError: name 'WinDLL' is not defined
```
When I try to use python2.7, it of course continues to give the message about the non-existing modules, since it was installed under python3.5, not python 2.7.
So that means, that I can't install PixivUtil2 under Linxu (but I can use it). What is the solution to this problem?

**Comment by NHOrus** [comment]
Sorry, how do you run PixivUtil2? You should start with `pip install -r requirements.txt` and then `python2 PixivUtil2.py`.
I usually use not a content of release tarball, but directly cloned code.

Yes, one of the problems you experience is starting with python3 when PixivUtil is python2 program.

**Comment by arisboch** [comment]
@NHOrus I also use a cloned github repo, install the requirements and use program like you do, but I can't 
**install** it, since the install script demans to install py2exe, which isn't possible under Linux.

**Comment by Nandaka** [comment]
Install script is meant windows box, as py2exe is used to 'compile' the
script to executeable.

You can run the script directly in linux.

**Comment by arisboch** [comment]
@Nandaka I think being able to install the script on a Linux system is a feature worth adding, what do you think?

**Comment by Nandaka** [comment]
No idea how to do it as I only have windows box, you can send pull request
though: D

**Comment by NHOrus** [comment]
Why would you want to install it on Linux box?
There are many things wrong with that idea...
First, it's not a package, it's a script. It does not need to be build, it does not need to be installed, it runs as cloned, again, with
```bash
python2 PixivUtil2.py
```
from the folder you cloned the app into.

Second, it's a script, not a package, you can't install this correctly so your distro's package manager will not pick it up and manage it. You can instead write your own wrapper script to drive PixivUtil2, for example, to simplify startup and shutdown.

Third, you can't install the PixivUtil2 on Windows, it's zipped executable with dependencies that does not write anything beyond it's database and config file in same directory and so could be freely moved around with no need to mess with registry or other Windows systems.

**Comment by Comrade-Riley** [comment]
> Why would you want to install it on Linux box?
> There are many things wrong with that idea...
> First, it's not a package, it's a script. It does not need to be build, it does not need to be installed, it runs as cloned, again, with
> 
> ```shell
> python2 PixivUtil2.py
> ```
> 
> from the folder you cloned the app into.
> 
> Second, it's a script, not a package, you can't install this correctly so your distro's package manager will not pick it up and manage it. You can instead write your own wrapper script to drive PixivUtil2, for example, to simplify startup and shutdown.
> 
> Third, you can't install the PixivUtil2 on Windows, it's distributed as zipped executable with dependencies that does not write anything beyond it's database and config file in same directory and so could be freely moved around with no need to mess with registry or other Windows systems.

you'd on it on linux so someone that uses linux can port their project for linux users too?

**Comment by Nandaka** [comment]
you can download the latest code as @awiebe has made some changes in https://github.com/Nandaka/PixivUtil2/pull/335

Fyi, it is now requires python3
