### ISSUE TITLE
Updated recently and cant use pixiv now?

### ISSUE THREAD

**Issue by Aaeeschylus** [Nandaka/PixivUtil2#198]
So I updated recently cause I hadnt used the program for a while and the old version I had was not working anymore. So I tested it out by downloading all of one member that I follow. Worked perfectly.

However, now whenever I go onto pixiv; 
I cannot see what images look like through menus and in member's work lists (Examples: https://puu.sh/tZ1AE/4988ea4ccc.png and https://puu.sh/tZ1Bh/7c5786e906.png),  
I cannot click on images to make them full screen,
I cannot see manga once clicking to see all images fullscreen (they dont load like above)
I cannot follow anyone (it just takes me straight back to my profile's following list)

**Comment by Nandaka** [comment]
It should have anything to do with the application, as it doesn't modify anything on your system.

Try to clear your browser cache? Check your antivirus/firewall or try on different PC?

**Comment by Aaeeschylus** [comment]
Ah ok, thanks, clearing cache worked
