### ISSUE TITLE
Clarification on the meaning of 'class" Error (Pixiv Tags Translation feature related)

### ISSUE THREAD

**Issue by DevPaws** [Nandaka/PixivUtil2#200]
The program is not downloading select images with no specific error code displayed.
`Processing Image Id: 7575556
Image ID (7575556): 'class'
Image #31`
`Processing Image Id: 189902
Image ID (189902): 'class'
Image #32`

Some images will download just fine, but not these among many others.

I should add, viewing in a regular browser will still work.

**Comment by Nandaka** [comment]
Looks like they do something on the way the tags is being represented (something related to translation?)

**Comment by NHOrus** [comment]
Experiencing same error, multiple times. Say, [here](http://www.pixiv.net/member_illust.php?mode=medium&illust_id=61543467)

I got about 300 in log file from today's attempt to crawl 3700 artists.

**Comment by fredgido** [comment]
Getting that error too.
Nothing changed here, probably something changed on pixiv site side?

**Comment by naharamas** [comment]
Same issue here. I'm using last release.
A lot of images don't download because of this. 
Artist ids 2208819(SFW) or 15426672(NSFW) for instance misses a lot of pictures.

Pixiv website seems to have some issues currently tough. I'm unable to follow anyone right now, pressing the follow button redirects me on my bookmarks page.  This is not related of course, but there could be other similar issues preventing the downloading.

**Comment by pixtrix** [comment]
Tags must have changed yesterday or today. Not all of the tags are in class="text" links any more. I used the data-tooltip="Articles related to (tag_name)" links to pull the tag names that weren't in the old style links.

I changed the code in the ParseTags method in PixivImage in PixivModel.py to:
```
    def ParseTags(self, page):
        del self.imageTags[:]
        temp = page.find(attrs={'class': 'tags'})
        if temp is not None and len(temp) > 0:
            temp2 = temp.findAll('a')
            if temp2 is not None and len(temp2) > 0:
                for tag in temp2:
                    if tag.has_key('class'):
                        if tag['class'] == 'text' and tag.string is not None:
                            tag_name = unicode(tag.string)
                            if tag_name not in self.imageTags:
                                self.imageTags.append(tag_name)
                        elif tag['class'] == 'icon-pixpedia _ui-tooltip':
                            tag_name = unicode(re.sub('^Articles related to ', '', tag['data-tooltip']))
                            if tag_name not in self.imageTags:
                                self.imageTags.append(tag_name)
```

But I'm sure it could be fixed better. And if this new style of tag links is permanent, the old style links might need to be discarded. But their code was changing while I was working on this fix, so I think that these changes aren't set in stone yet.

**Comment by Nandaka** [comment]
Pixiv are doing a/b testing related to tags translation, for now I will take the japanese version.
