### ISSUE TITLE
Option to download images posted <= x number of days

### ISSUE THREAD

**Issue by nywilds** [Nandaka/PixivUtil2#204]
Is there a way (or could you add a way) to download only images that were posted within the last x days? The only option I've seen is dateDiff, but that is for images older than x days, not newer.

**Comment by Nandaka** [comment]
```dateDiff``` actually will skip the download if the image is older than x days (only for downloading New Illustration mode). so it will download only new image within the given range.

**Comment by nywilds** [comment]
Oh, I must have misunderstood the readme, then. Thanks for the help. :)

Could I suggest that some of the information about `dateDiff` be reworded? The way it is now, it seems like only older works get downloaded. Like maybe change the readme entry to `Gets only pictures that were posted within X days of the system date`?
