### ISSUE TITLE
[question]image folder

### ISSUE THREAD

**Issue by tempetahu0** [Nandaka/PixivUtil2#206]
can we download images without creating a folder for every images?

**Comment by Nandaka** [comment]
what is your filename format? 

Fyi, '\' is the folder separator, you can check the readme.txt

**Comment by tempetahu0** [comment]
this %artist% (%member_id%)\%urlFilename% - %title%
i think this is the default?

**Comment by Nandaka** [comment]
Should have the os separator between member id and urlFilename

refer to
https://github.com/Nandaka/PixivUtil2/blob/master/PixivConfig.py#L44

**Comment by tempetahu0** [comment]
so do i edit the one in config.ini or pixivconfig.py ?

**Comment by Nandaka** [comment]
config.ini

Just change those various filenameformat :D

**Comment by tempetahu0** [comment]
got it! thanks!
