### ISSUE TITLE
Provider DLL failed to initialize correctly

### ISSUE THREAD

**Issue by Revemohl** [Nandaka/PixivUtil2#207]
I just got v20170220, and I get this error when trying to run PixivUtil2.exe.

```
Traceback (most recent call last):

File "PixivUtil2.py", line 12, in <module>

File "urllib2.pyc", line 94, in <module>

File "httplib.pyc", line 80, in <module>

File "mimetools.pyc", line 6, in <module>

File "tempfile.pyc", line 35, in <module>

File "random.pyc", line 885, in <module>

File "random.pyc", line 97, in __init__

File "random.pyc", line 113, in seed

WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly
```

In fact, it looks like the last version I can run is pixivutil20160513, everything from 20160613 on gives me that error. I'm still running Windows XP on this machine, could that be the cause?

**Comment by Nandaka** [comment]
I think so. Someone from my blog also have the same issue and he/she uses windows Vista.

The only information that I know is from http://bugs.python.org/msg248951

It might related to your pc environment variable that SystemRoot is not set.
You can check by typing ‘SET’ on the cmd console and look for ‘SystemRoot=C:\WINDOWS’. I think you can set it by ‘SET SystemRoot=C:\WINDOWS’ before running the app in the console.

![image](https://cloud.githubusercontent.com/assets/836867/23574758/2b38edbc-00bd-11e7-8911-289b14b24683.png)

**Comment by Revemohl** [comment]
That's strange, I just checked that and SystemRoot=C:\WINDOWS seems to be properly set here.

**Comment by Nandaka** [comment]
Can you rename/delete ```crypt32.dll``` from the installation folder?

reference: http://stackoverflow.com/a/31222117

**Comment by Revemohl** [comment]
Sorry for the slow reply, after doing that PixivUtil2.exe just shows a blank screen for a few seconds and then I get a Windows error dialog.

**Comment by Nandaka** [comment]
can you copy winxp c:\Windows\System32\crypt32.dll to the pixiv downloader folder?

**Comment by Revemohl** [comment]
Nope, still a Windows error.

**Comment by Nandaka** [comment]
welp, then I have no other idea.

Maybe run it from source code?
1. Download and install latest Python 2.7 from http://www.python.org/
2. Download the source code and extract it on some folder (e.g. ```c:\pixivutil```)
3. Download the required library:
         a. Open ```cmd``` window and navigate to where you install the python, and go to the script folder (e.g. ```C:\Python27\Scripts```)
         b.  run: ```pip install -r c:\pixivutil\requirements.txt```
 4. Run the ```PixivUtil2.py``` by double clicking it or from ```cmd``` using ```python.exe c:\pixivutil\PixivUtil2.py```

**Comment by Revemohl** [comment]
Sorry for taking so long to reply back, after things happened I ended up installing Windows 7 on this same machine. Given how recent versions of pixivutil are still crashing for me (but now listing numpy.core.multiarray.pyd as the faulty module in Windows 7's error dialog), I find it likely that the reason might be something that's plagued me in trying to run many programs on this computer: the fact that its CPU is a very old Athlon XP, which doesn't have support for SSE2 instructions.

I'm not sure if anything more can be done at this point (and I can't even provide more assistance in regards to the original error), so please feel free to close this issue.

**Comment by ikasumi4u** [comment]
Removing `crypt32.dll` worked for me.  ✔
