### ISSUE TITLE
Downloading with member_ids from list.txt only

### ISSUE THREAD

**Issue by WhiteSp1rit** [Nandaka/PixivUtil2#208]
Is it possible to download images by member_ids from list.txt only, ignoring the other ones which are in the db?

By default, even if you select option 4 to use the list.txt, it just adds it to the database, and still checks every single member_id even if it isn't on the list.

And, what exactly happens when using option 4 "download by member_id" when processfromdb is set to false, while uselist = true? Readme doesn't really explain that

**Comment by NHOrus** [comment]
Have you tried setting `processfromdb` to false in config.ini? That should do it. Never seen downloads from remembered members with that option set to False.

**Comment by WhiteSp1rit** [comment]
> Have you tried setting processfromdb to false in config.ini?

Does the program still check which images were already downloaded in the db with this option?

**Comment by NHOrus** [comment]
Yes. It does.

**Comment by Nandaka** [comment]
also set ```alwayscheckfilesize = False``` to skip file size checking, and ```checkupdatedlimit = 5``` to make it to jump to next member id if already see 5 previously downloaded images.

**Comment by WhiteSp1rit** [comment]
Ah, now I understand how checkupdatedlimit works. 
From the readme I did not figure out what it does, it would probably be better to change the description to what you just written above.
