### ISSUE TITLE
Images fail to download, log shows Image ID : 'class'

### ISSUE THREAD

**Issue by WhiteSp1rit** [Nandaka/PixivUtil2#209]
For some artists large numbers of images fail to download, with the log showing entries like:

Image ID (48062945) : 'class'

For images which it doesn't download. Deleting the artist from db and downloading by member_id again doesn't change anything.

Example:
![untitled-1](https://cloud.githubusercontent.com/assets/7308007/23581446/a2d5c548-011c-11e7-99eb-a5a9bf23e286.png)

**Comment by NHOrus** [comment]
You have an old version, this bug is fixed in never release. Please update and try again.

**Comment by WhiteSp1rit** [comment]
Alright, new version seems to be working, this can be deleted
