### ISSUE TITLE
avatar download only in root folder

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#210]
I'm using latest master from repo.
Folder.jpg are downloaded only in main root folder:

Processing Member Id: 772547
Reading /PixivUtil2/config.ini ...
done.
Page  1
Member Url: http://www.pixiv.net/member_illust.php?id=772547&p=1
Member Name  : loundraw
Member Avatar: https://i.pximg.net/user-profile/img/2015/10/26/13/27/37/10040113_f5351110064281797872cabe956a8404_170.jpg
Member Token : kyoppy
Checking local filename... File exists: /mnt/Pixiv/folder.jpg
[...]
Creating directory: /mnt/Pixiv/772547 kyoppy/loundraw

**Comment by Nandaka** [comment]
check your ```avatarnameformat``` in config.ini?

**Comment by whinette** [comment]
It is void, but as far as I remember it worked before. Is there a format to put there? Can't find anything in the readme (only formating, but no positioning)

**Comment by Nandaka** [comment]
use ```%member_id% %member_token%\%artist%\folder.jpg```?

**Comment by whinette** [comment]
It works but as folder.jpg.jpg
As future note, there only the need to write the name without any extension. Want me to update the doc?

**Comment by Nandaka** [comment]
Sure :D
