### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by ohnoe** [Nandaka/PixivUtil2#214]
How do I fix an error like this?

Checking local filename... Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=1629
7949
[download_image()] URL Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] ce
rtificate verify failed (_ssl.c:590)> at https://i2.pixiv.net/img-original/img/2
011/01/31/01/40/17/16297949_p0.jpg
Traceback (most recent call last):
  File "PixivUtil2.py", line 84, in download_image
  File "mechanize\_mechanize.pyc", line 199, in open_novisit
  File "mechanize\_mechanize.pyc", line 230, in _mech_open
  File "mechanize\_opener.pyc", line 193, in open
  File "mechanize\_urllib2_fork.pyc", line 344, in _open
  File "mechanize\_urllib2_fork.pyc", line 332, in _call_chain
  File "mechanize\_urllib2_fork.pyc", line 1170, in https_open
  File "mechanize\_urllib2_fork.pyc", line 1118, in do_open
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fai
led (_ssl.c:590)>
Error at download_image(): (<class 'urllib2.URLError'>, URLError(SSLError(1, u'[
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),), <tra
ceback object at 0x0468D620>) at https://i2.pixiv.net/img-original/img/2011/01/3
1/01/40/17/16297949_p0.jpg (9002)
Retrying [3]...

**Comment by Nandaka** [comment]
can you open the page on browser without ssl warning? Looks like something causing SSL validation error (virus?).

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=16297949

**Comment by ohnoe** [comment]
yes, page opens normally

**Comment by Nandaka** [comment]
hmm weird, why the image url is using https.

It should be like this:
```
Input: 2
Image ids: 16297949
Processing Image Id: 16297949
Title: ポニテ早苗さん
Tags : 東方, 早苗, 東風谷早苗, 諏訪子, 下乳, 輪チラ, R-18, さなぱい, ポ苗
Date : 2011-01-31 01:40:00
Mode : bigNew
Image URL : http://i2.pixiv.net/img-original/img/2011/01/31/01/40/17/16297949_p0.jpg
Filename  : D:\Temp\Pixiv2\2625199 usubeniya\20110131 16297949_p0 - ポニテ早苗さん.jpg
Checking local filename... Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=16297949
Remote filesize = 1.00 MiB (1253070 Bytes)
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=16297949
Creating directory: D:\Temp\Pixiv2\2625199 usubeniya                                                                      1253070 of   1253070 Bytes  Completed in 2.211s (553.46 KiB/s)
 done.
```

Try to open image url directly (https/http)
http://i2.pixiv.net/img-original/img/2011/01/31/01/40/17/16297949_p0.jpg
https://i2.pixiv.net/img-original/img/2011/01/31/01/40/17/16297949_p0.jpg << should be 403

**Comment by ohnoe** [comment]
yes, bottom is 403

**Comment by ohnoe** [comment]
looks like it sometimes catches http or https


Image URL : http://i1.pixiv.net/img-original/img/2017/01/28/02/51/07/61146764_p4
.jpg
Filename  : C:\PixivDownloaded\psiroiarutu000 (179882)\61146764_p4.jpg
Checking local filename... Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=6114
6764
Remote filesize = 477.00 KiB (488829 Bytes)
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?mode=
medium&illust_id=61146764
    488829 of    488829 Bytes  Completed in 1.516s (314.89 KiB/s)
 Image verified.

Image URL : https://i1.pixiv.net/img-original/img/2017/01/28/02/51/07/61146764_p
5.jpg
Filename  : C:\PixivDownloaded\psiroiarutu000 (179882)\61146764_p5.jpg
Checking local filename... Getting remote filesize...
Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=6114
6764
[download_image()] URL Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] ce
rtificate verify failed (_ssl.c:590)> at https://i1.pixiv.net/img-original/img/2
017/01/28/02/51/07/61146764_p5.jpg

**Comment by Nandaka** [comment]
weird,  even so it shouldn't hit the ssl error. Are you using some antivirus/firewall? try to allow the program/disable temporarily?

**Comment by ohnoe** [comment]
no change

**Comment by Nandaka** [comment]
backup and then delete your cookie value in ```config.ini``` and relogin? 

Are you using WinXP/Vista?

**Comment by ohnoe** [comment]
Logging in...
Error at login(): (<class 'urllib2.URLError'>, URLError(SSLError(1, u'[SSL: CERT
IFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),), <traceback ob
ject at 0x04267B98>)
Error at doLogin(): (<class 'urllib2.URLError'>, URLError(SSLError(1, u'[SSL: CE
RTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),), <traceback
object at 0x0426C7B0>)
Cannot Login!
press enter to exit.

**Comment by Nandaka** [comment]
ok, can you login to pixiv using internet explorer (don't use chrome/ff) without warning? what is your os? can you try on another pc?

**Comment by ohnoe** [comment]
yes, I can login and log out at both my computers normally on ie and other browsers

**Comment by ohnoe** [comment]
pixivutil works normally on my other computer, login works
both computers can login to pixiv with ie

**Comment by Nandaka** [comment]
hmm, then I suspect something on one of your pc causing the problem then.

Usually this is due to some internet security suite acting as proxy and doing man-in-middle checking.

**Comment by ohnoe** [comment]
yeah i started trying other things since and somehow the problem went away after I ran a malware scanner on the other PC I wasn't using
hours have gone by and no errors now
the issue amazingly was not pixivutil related sorry

**Comment by Nandaka** [comment]
closing this then, also you better change password for all important account if it found a virus/malware, as it does https hijack.
