### ISSUE TITLE
ascii codec issue 

### ISSUE THREAD

**Issue by moistee** [Nandaka/PixivUtil2#216]
![image](https://cloud.githubusercontent.com/assets/24874632/24329419/956ccbb4-1241-11e7-8aad-760c079777f8.png)

Image ID (32340486): 'ascii' codec can't encode character u'\ub144' in position 4: ordinal not in range(128)

I can not download it T^T

**Comment by Nandaka** [comment]
Ok in my pc, can you set the the pixiv website language to either english or japanese, then remove the cookie value from config.ini, and retry.

**Comment by moistee** [comment]
I solved it. Thanks! 

The god of masturbation will be with you!
