### ISSUE TITLE
cannot dl bookmarked image

### ISSUE THREAD

**Issue by kalacodm** [Nandaka/PixivUtil2#220]
Hi,

I am getting these error even I am using the latest version, can you please check on the issue?

> Input: 6
> Include Private bookmarks [y/n/o]: n
> Tag (default=All Images):
> Start Page (default=1):
> End Page (default=0, 0 for no limit):
> Importing image bookmarks...
> Importing user's bookmarked image from page 1
> Source URL: http://www.pixiv.net/bookmark.php?p=1
> Error at process_image_bookmark(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x049A7A30>)
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 1867, in main
>   File "PixivUtil2.py", line 1658, in main_loop
>   File "PixivUtil2.py", line 1488, in menu_download_from_online_image_bookmark
>   File "PixivUtil2.py", line 924, in process_image_bookmark
>   File "PixivUtil2.py", line 967, in get_image_bookmark
>   File "PixivModel.pyc", line 799, in parseImageBookmark
> AttributeError: 'NoneType' object has no attribute 'findAll'
> press enter to exit.

**Comment by javsnt** [comment]
I have the same issue since April 3

**Comment by AtrusHB** [comment]
Exact same issue as well, identical message save for the traceback object's location in memory.

**Comment by antiglow** [comment]
same. probaby because they updated their website so the parsing no longer works

**Comment by antiglow** [comment]
same
a fix is to add js-legacy-mark-unmark-list to the temp var in PixivModel.py under parseImageBookmark(page)
`temp = page.find('ul', attrs={'class': '_image-items js-legacy-mark-unmark-list'})`
