### ISSUE TITLE
My password appears in the console

### ISSUE THREAD

**Issue by p-90** [Nandaka/PixivUtil2#222]
![password](https://cloud.githubusercontent.com/assets/7262313/25063647/b66269f6-21ea-11e7-9388-15334718398d.png)

**Comment by NHOrus** [comment]
Weird. I feel it's problem with Windows CMD, not woth PixivUtil, but not sure.
I have my pass in the cleartext in config.ini...

**Comment by p-90** [comment]
What should I do then? I don't feel comfortable storing my password in plain text.

I also don't think it's a problem of cmd, because I could input my password just fine in the command shell without echoing it in previous versions of PixivUtil.

**Comment by brodycas3** [comment]
It says before you use it that your password will/may be echoed, also as
far as I know it doesn't store your password just the cookie you use to log
in.

**Comment by Nandaka** [comment]
This is the limitation from `win_unicode_console` package. It is used to enable unicode (shows the japanese chars) in windows CMD.

And as @brodycas3 said, the password entered here will not stored to config.ini (only the cookie value).

Off course you can manually edit the config.ini if you want to store it (in cleartext) and saved it somewhere safe.

**Comment by p-90** [comment]
I see... Is the win_unicode_console package a new addition? I don't remember having this issue in previous versions.

Anyways, I'll bear with it. Better than storing a password in cleartext, at least for me.

Thanks everybody!

**Comment by p-90** [comment]
Hello again. I just saw that you solved my issue in the latest version of the program. Thanks a lot, @Nandaka.

If you don't mind, I'm going to close this issue.
