### ISSUE TITLE
Single/Stand-alone images categorized as "manga" aren't saved/are ignored. 

### ISSUE THREAD

**Issue by growinmatt** [Nandaka/PixivUtil2#224]
Usually, uploads categorized as "manga" have multiple images. Those obviously download easily - no issues. 

However, recently I realized that single images that an artist categorizes as "manga" will open differently from regular stand-alone images. Instead of opening the full-size image within the same page, it will open it in another tab - as it would when you want to see the full-size version of an image within a series of images categorized as "manga." 

That's not a problem in itself, but it's probably important regarding -why- the problem I'm going to point out is occurring. Like the post's/thread's title says, these images aren't saved. At all. 

Anyone with a similar issue? Even though I'm sure this is probably non-unique/not just on my side. Inwhichcasehopingforafixsoon!

**Comment by NHOrus** [comment]
can you please provide a link? I will test it.

**Comment by growinmatt** [comment]
Searched up something random for a quick example: 

http://i.imgur.com/EbcjyFN.png
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=62670665

Images like this one (marked as "manga," but a single image). I haven't tested it for the individual image itself (ONLY downloading an image like that), but since I've noticed the issue, it's happened with the last two or three galleries I've downloaded that contained images like that (all images, excluding those ones in particular, are saved).

**Comment by NHOrus** [comment]
Confirming. Getting
```
Image ids: 62670665
Processing Image Id: 62670665
Title: その名はVAPEフォグフォグ漫画(10) 
Tags : R-18, 漫画, ベイプ, vape 
Date : 2017-05-01 08:11:00 
Mode : big
Image URL : https://source.pixiv.net/www/images/sketch-icon.png

```
As output. And no image.

**Comment by whinette** [comment]
Full log in issue https://github.com/Nandaka/PixivUtil2/issues/226

**Comment by Nandaka** [comment]
Try latest releases
