### ISSUE TITLE
Not displaying Unicode text

### ISSUE THREAD

**Issue by brodycas3** [Nandaka/PixivUtil2#229]
![image](https://cloud.githubusercontent.com/assets/19770864/25978594/2eea5770-3691-11e7-8c46-4601f7d9143d.png)

**Comment by Nandaka** [comment]
do you have japanese supporting font installed in the console?

**Comment by turkSLO** [comment]
What version of python are you using?

**Comment by vampiricwulf** [comment]
What version of python are you using?

**Comment by Nandaka** [comment]
![image](https://cloud.githubusercontent.com/assets/836867/25982316/803d6762-36a9-11e7-890d-e154f3d60700.png)

set the console font to msgothic
![image](https://cloud.githubusercontent.com/assets/836867/25982321/8a437bd4-36a9-11e7-962b-9e2a64a3af50.png)

**Comment by brodycas3** [comment]
Thank you Nandaka
