### ISSUE TITLE
ascii decoding error

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#230]
At this and many others:
```
Processing Image Id: 60911646
Image ID (60911646): 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)
```
20170508-beta1
Many other images work, but there's more errors with `0xe2`, `0xe3` or `0xe4` as byte value.

Changing language to japanese and back to english with cookie removal from config and relogins did nothing.

**Comment by Nandaka** [comment]
added 
```
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
```

looks like fix the issue

**Comment by NHOrus** [comment]
Hopefully. Beta2, please? So I can test on Windows.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v201070515-beta2

**Comment by NHOrus** [comment]
Appears to be working correctly.
