### ISSUE TITLE
Error when Downloading Member Bookmark (11) with tags

### ISSUE THREAD

**Issue by Latias4Ever** [Nandaka/PixivUtil2#234]
It seems Pixiv's URL for a member's bookmarks with tag filtering uses a different keyword for the tag, using "&word=TagName*". PixivUtil still uses "&tag=TagName" on that option, which results in an "image not found" error.

This makes it impossible to download members' bookmarks if we're trying to filter a tag, so can the URL be updated to add "word" instead of "tag"?

**Comment by Nandaka** [comment]
Can you double check? Because when I tried, it still uses &tag

![image](https://cloud.githubusercontent.com/assets/836867/26382773/595e559a-4061-11e7-8c4a-801a52ca89b7.png)

**Comment by Latias4Ever** [comment]
...Oh, man, you're correct, I thought this was an error with the &tag part because I thought an user's bookmarks' tags used the pictures' tags, not the bookmarks themselves. I'm so sorry for my error.

As an example of what I mean, the user on this image has a lot of bookmarks of pictures that use the tag "C.C.", yet using that tag on their bookmarks didn't result in anything, that's what led to my error. Again, apologies for that.

![image](https://cloud.githubusercontent.com/assets/24550309/26384847/ccd7e794-4033-11e7-800d-681348e3fcb4.png)
