### ISSUE TITLE
Error on startup with proxy [beta]

### ISSUE THREAD

**Issue by MylekGrey** [Nandaka/PixivUtil2#235]
Error at startup with Beta1 and 2. It may be related to having the proxy enabled because I get a different error when I turn it off. 20170411 works without issues.

**config.ini**
>[Network]
>useproxy = True
>proxyaddress = socks5://127.0.0.1:1234

**Console Output**
>E:\pixiv>PixivUtil2.exe
>PixivDownloader2 version 20170515-beta2
>https://github.com/Nandaka/PixivUtil2/releases
>Donate at https://bit.ly/PixivUtilDonation
>Reading E:\pixiv\config.ini ...
>done.
Traceback (most recent call last):
>  File "PixivUtil2.py", line 1909, in <module>
>  File "PixivUtil2.py", line 1782, in main
>  File "PixivBrowserFactory.pyc", line 509, in getBrowser
>  File "PixivBrowserFactory.pyc", line 42, in __init__
>  File "PixivBrowserFactory.pyc", line 62, in _configureBrowser
>AttributeError: 'module' object has no attribute 'wrapmodule'

**Comment by Nandaka** [comment]
looks like compilation issue, will recompile

**Comment by MylekGrey** [comment]
Thanks. Working correctly now with 20170524-beta3.
