### ISSUE TITLE
Looks like member_token changes

### ISSUE THREAD

**Issue by jrdp18** [Nandaka/PixivUtil2#240]
Was downloading something when I kept looking for its supposed folder. I thought I might've accidentally deleted it or something. But it seems the member_token changed so it ended up in a new folder.

![Folders and settings I have](http://i.imgur.com/I5SRVPq.png)

**Comment by Nandaka** [comment]
which one is the new one? kumafromtaiwan should be the correct one if looking from the stacc link (https://www.pixiv.net/stacc/kumafromtaiwan)

**Comment by jrdp18** [comment]
Indeed, kumafromtaiwan is the new one.

**Comment by Nandaka** [comment]
Should not be a bug then?

Looks like new feature to change the pixiv id (member token):
![image](https://user-images.githubusercontent.com/836867/27813482-d40c614e-60a8-11e7-9243-9eb5f69b2210.png)

**Comment by jrdp18** [comment]
Yeah. Just mentioning it since it's still noted that **Member token, doesn't change**.

**Comment by Nandaka** [comment]
updated in 74b66c2e6ae184292d5da61195fb93d66be12dc7
