### ISSUE TITLE
download by >1 tags, how?

### ISSUE THREAD

**Issue by hatabbich** [Nandaka/PixivUtil2#241]
Hi, i cant download by more than one tags, or just make something wrong? (
later* tags list downloading doesnt work too 
what im do:
1. make a tags.txt
2.put tags in one line separeted by space
3. try to load and error

**Comment by Nandaka** [comment]
what is the error message? can you upload the log file (try to delete the old log first, and then replicate the issue, then upload that log file).

**Comment by Nandaka** [comment]
woops, supposed for #240

**Comment by Nandaka** [comment]
Try to set use partial match to Y

![image](https://user-images.githubusercontent.com/836867/27854704-61d25672-619a-11e7-941b-652c46566cd0.png)

I think I need to change the behaviour for tag list to always search by partial match
