### ISSUE TITLE
How Do You Use This Program?

### ISSUE THREAD

**Issue by Echo-Yggdrasil** [Nandaka/PixivUtil2#242]
I don't know how to use programs like this. I downloaded and installed Python, clicked everything, and nothing is working. My command prompt box flashes open for like half a second, then closes.

**Comment by NHOrus** [comment]
Weird.

Please, say what OS you are using and exactly what "everything" you clicked.  
On Windows, there's no need for Python, you got PixivUtil2.exe, clicking on it should bring you into interactive instance of command prompt. Black box with text and options.

**Comment by Echo-Yggdrasil** [comment]
I'm using windows 10. Without Python, the PixivUtil2 program itself still wanted me to search my computer to open it with a specific program.

I clicked every single file in the download. Nothing opened my console for more than half a second.

**Comment by Nandaka** [comment]
1. Redownload the latest release (https://github.com/Nandaka/PixivUtil2/releases/download/v20170705/pixivutil20170705.7z) and extract the archive using 7z (http://www.7-zip.org/download.html) or winrar.
2. Open explorer and navigate to the pixiv util folder.
3. Shift + Right Click -> Open Command Window here.
![image](https://user-images.githubusercontent.com/836867/28047831-7d2f65b6-661f-11e7-81c0-8b3ee01e8324.png)
4. Type ```PixivUtil2.exe``` and press enter. It should show the interactive prompt.
![image](https://user-images.githubusercontent.com/836867/28047890-d5b2d8a8-661f-11e7-8b7d-bf6e9a7c4ae9.png)

If it still unable to run, try to do virus scan?

**Comment by Echo-Yggdrasil** [comment]
There's no option to open the command prompt with windows 10, it's the "powershell" now. I'll try it through that and see how it works.

**Comment by Echo-Yggdrasil** [comment]
It said : 

"PixivUtil2.exe : The term 'PixivUtil2.exe' is not recognized as
the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
+ PixivUtil2.exe
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PixivUtil2.exe:Stri
   ng) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command PixivUtil2.exe was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\PixivUtil2.exe". See "get-help about_Command_Precedence" for more details.
PS C:\Users\Steven\Desktop\pixivutil20170705>"

**Comment by Nandaka** [comment]
Hmm, it is working in my pc and I can run it from PowerShell.
![image](https://user-images.githubusercontent.com/836867/28052300-e6a004c0-663c-11e7-9c55-ba0d578e3c96.png)

maybe try to unblock the archive first then extract the file?
![image](https://user-images.githubusercontent.com/836867/28052348-3df01b84-663d-11e7-8287-0d11469833e9.png)

**Comment by Echo-Yggdrasil** [comment]
Uninstalled Python and tried it that first time. I tried unblocking it, didn't work. There's another zip folder in the file - "library" - that I unzipped into the main folder and took the "library" zip file out. One of the 600+ files in "library" overwrote something in the original folder. Still didn't work.

**Comment by Nandaka** [comment]
No need to unzip the library.zip. It should be like this: 
![image](https://user-images.githubusercontent.com/836867/28053168-a5ada724-6641-11e7-98b6-3ffeaba0c461.png)
refer to [filelist.txt](https://github.com/Nandaka/PixivUtil2/files/1137843/filelist.txt) for filesize.

also, run the executables using ```.\PixivUtil2.exe``` in PowerShell.

If it still cannot run, then I have no idea. Try to run it on different PC? Try to turn off the antivirus?

**Comment by Echo-Yggdrasil** [comment]
It managed to work this time but when I get to the password portion, I cannot type anything in. This happened last time I tried to use a program like this a very long time ago; it wouldn't let me type my password in.

**Comment by Nandaka** [comment]
It is there, just not shown to the console 😄 

Just type it as usual and press enter.

**Comment by Echo-Yggdrasil** [comment]
Oh Jesus, really? The last one I used before this one, the password used to show up, but then one day it didn't, so I assumed... That, or I forgot. Damn it.

Working so far so good now, though! Thank you. I'll scream here again if something messes up!

**Comment by Echo-Yggdrasil** [comment]
Ah, one thing; is there any way for me to download the images into grouped folders like how they're uploaded?

**Comment by NHOrus** [comment]
`createmangadir` in config.ini?
Honeslty, I disabled it and just use:
```
filenameformat = %member_id%\%image_id% - %title%
filenamemangaformat = %member_id%\%image_id% - %title%_%page_index%
filenameinfoformat = %member_id%\%image_id% - %title%
``` 
to evade problems with authors renaming themselves.

**Comment by Echo-Yggdrasil** [comment]
createmangadir is already set to "false".

I should change the name/manga/info format to what you have listed, and it should sort everything into folders by itself, too?

**Comment by NHOrus** [comment]
I may not get what you want.

No, for my setup it dumps everything into one artist folder with just artist's ID for the folder name.
If you want grouped folders for manga/multipage uploads. you need to enable `createmangadir` and edit filenamemangaformat for something that suits you.

**Comment by Echo-Yggdrasil** [comment]
I'll check it out! Some artists aren't downloading, either; I'm downloading via member_id and it's... only downloading their icon and saying everything else is already downloaded when nothing is.

**Comment by NHOrus** [comment]
You may need to do a database cleanup. Or purge database file and start anew.

**Comment by Echo-Yggdrasil** [comment]
How do I do that? What database? I am moving the folders out of the PixivUtil2 folder after they finish downloading and I tried redownloading one again, and it still only downloaded the icon image.

**Comment by Nandaka** [comment]
Please read the readme.txt first...

**Comment by Echo-Yggdrasil** [comment]
Don't think I found anything in there that helped with my questions, except the password not showing up and that Pixiv may block your IP for a few hours if you overuse the program.

**Comment by NHOrus** [comment]
https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L45  
That's d (Enter) c (enter)

**Comment by ShiroTora** [comment]
i have a question, i use PixivUtil20180118 but it dont work anymore,  can you guys help me ?

**Comment by NHOrus** [comment]
There are two beta releases with bugfixes. They are perfectly usable.

**Comment by rachmadaniHaryono** [comment]
@ShiroTora see also `log message` section on front page.

>Q3: Error at process_image(): (<type 'exceptions.AttributeError'>,
    AttributeError ("'NoneType' object has no attribute 'find'",)

>    - Usually this is because of login failed (cookie not valid). Try to change
      your password to simple one for testing, or copy the cookie from browser:
