### ISSUE TITLE
If "create gif" is true, shouldn't there be an adjacent "delete ugoria(true/false)" rule?

### ISSUE THREAD

**Issue by Gandeloft** [Nandaka/PixivUtil2#243]
I should rephrase the title.
There **should** be such a rule. 
I have 50GB in ugoria files which have been converted into gifs.

**Comment by Gandeloft** [comment]
Checked, currently I have 50GB of unneeded ugoira files.

**Comment by Gandeloft** [comment]
I have 150GB in redundant ugoira by now..

**Comment by Nandaka** [comment]
try: https://github.com/Nandaka/PixivUtil2/releases/tag/v20180218

**Comment by Gandeloft** [comment]
I tried to make it apparent that I am (well) aware of there being no room for anything other than gratitude to you.
Thank you very much. :D
