### ISSUE TITLE
folder renaming for %artist% for name changes

### ISSUE THREAD

**Issue by eccdbbabcdeee** [Nandaka/PixivUtil2#246]
I am using filenameformat = %artist% (%member_id%)\%urlFilename% - %title%
Since some artists change their name like Name@event, would it be possible to rename the folder to just %member_id%, then download as %member_id%\..., then rename back according to config.ini?

**Comment by Nandaka** [comment]
Nope, try to use %member_token% instead (this might also change, but very rare).
