### ISSUE TITLE
Unable to use multiple tags

### ISSUE THREAD

**Issue by qazwsxdonjon** [Nandaka/PixivUtil2#247]
Windows 7

Using option 3 I'm unable to have more than one tag at a time, no matter how I parse it. (comma, space, etc) 
It's always saying there's 0 results

If you need me to post a log, please tell me how to generate it. Thanks.

**Comment by Nandaka** [comment]
Please refer to https://github.com/Nandaka/PixivUtil2/issues/241

**Comment by qazwsxdonjon** [comment]
I tried typing multiple English tags and that worked. Japanese doesn't work, even though my locale was already set to Japan.
 I'm trying to change the font in the console, but I only have two options, neither of which work. I guess I'll keep looking for now.

**Comment by Nandaka** [comment]
You can try to use Option 7. It will download from tags.txt.

from readme.
```
=================================================================================
= tags.txt Format                                                               =
=================================================================================
- This file will be used as source for Download from tags list (7)
- Separate tags with space, ensure to set Use Wildcard to 'y'.
- Each line will be treated as one search.
- Save the files with UTF-8 encoding.
```
