### ISSUE TITLE
Font Trouble

### ISSUE THREAD

**Issue by qazwsxdonjon** [Nandaka/PixivUtil2#248]
Windows 7

My locale is set to Japanese, but whenever I type or paste something in Japanese it shows up with tons of question marks. I think the problem is with fonts. 

Consolas, Lucida Console, Courier New, Raster Fonts, and MS ゴシック（Gothic) don't work.

I've also added Arial Unicode MS Regular, MS Gothic Regular, and a few others to Regedit. These ones don't show up as options in CMD or PixivUtil, however.

I just want a font I can search in Japanese with. If someone could point me to one, I would be grateful. Thanks.

![2017-07-24_1323](https://user-images.githubusercontent.com/26395800/28538441-e4118e9a-7073-11e7-91ee-faa23060f556.png)

![2017-07-24_1323_001](https://user-images.githubusercontent.com/26395800/28538455-ec09944e-7073-11e7-8dee-123511c00280.png)

Edit: Uhh. I think the problem was that was adding 1000入り as a tag, rather than using the bookmark option. I didn't realize they were the same thing.

**Comment by Nandaka** [comment]
You can use the '1000users入り' to search by tags.

![image](https://user-images.githubusercontent.com/836867/28551979-f5d27d06-711d-11e7-803b-582f9458d791.png)

I can type the tag or paste it from pixiv website to console.
Below is my regional setting for non-unicode and I'm using ms gothic for the cmd font.
![image](https://user-images.githubusercontent.com/836867/28552008-37c900cc-711e-11e7-85b1-fa56b43760ed.png)
