### ISSUE TITLE
[Request] Allowing download by tags list within set time frame

### ISSUE THREAD

**Issue by Reiji314** [Nandaka/PixivUtil2#250]
Hello and thank you for the best Pixiv program! May I suggest to add "Olders first", "Start date" and "End date" to "Download by tags list" option in future versions? When your favorite theme has a lot of different tags and you want to get all fanart from 2015 only, for example, it's not very handy to insert every tag manually.

**Comment by Nandaka** [comment]
this settings will be applicable for the whole tag list.

**Comment by Reiji314** [comment]
That would be perfect!
