### ISSUE TITLE
Failed to install requirements.

### ISSUE THREAD

**Issue by momoe** [Nandaka/PixivUtil2#251]
Getting the following error when trying to install requirements.txt
` sudo pip install -r requirements.txt
Collecting mechanize>=0.2.5 (from -r requirements.txt (line 1))
  Using cached mechanize-0.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    mechanize only works on python 2.x
`
Need assistence trying to either meet python 3's requirements or get python 2 up and running.

**Comment by Nandaka** [comment]
It doesn't support python 3.

Not sure how to install python 2 in linux as I don't use it. I think you need to check your linux package manager.

**Comment by NHOrus** [comment]
On that note, @Nandaka , as Python2 will go the way of dodo in the year 2020, will you port PixivUtil2 to Python3 or some other language?

I may try to do porting to Go in the next two weeks.

**Comment by Nandaka** [comment]
Maybe, see if the big companies will ask the py foundation to extends the support 😈

**Comment by momoe** [comment]
@NHOrus I'm on a Manjaro community release (deepin) version of linux. Python 3 and python 2 is installed. I did not know there was a pip2 rather than pip. I will attempt that from  your previous cited command. and report the results. Thanks.

**Comment by momoe** [comment]
**FOLLOWUP**
I was able to get pip2 to call up the requirements.txt and install, however I had to sudo in to start the python script and now all downloads are admin locked and have to chown the directories afterwards. Any suggestions?

**Comment by NHOrus** [comment]
Weird. Again, have you installed requirements as user?
Had you extracted pixivutils as root?
You may need to either start PixivUtil2.py with python2 command or set it as executable file.

**Comment by momoe** [comment]
@NHOrus After taking the day I've cleared out the admin installed versions and did a basic user command install. Was able to get it to install the requirements and runs fine now. Thank you for your help on this.
