### ISSUE TITLE
Failure on program start (20170813-beta1)

### ISSUE THREAD

**Issue by photonometric** [Nandaka/PixivUtil2#253]
On startup I get this and then immediate exit:

> ```
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 28, in <module>
>   File "PixivConfig.pyc", line 7, in <module>
>   File "PixivHelper.pyc", line 19, in <module>
>   File "imageio\__init__.pyc", line 20, in <module>
>   File "imageio\core\__init__.pyc", line 9, in <module>
>   File "imageio\core\util.pyc", line 18, in <module>
>   File "numpy\__init__.pyc", line 142, in <module>
>   File "numpy\add_newdocs.pyc", line 13, in <module>
>   File "numpy\lib\__init__.pyc", line 8, in <module>
>   File "numpy\lib\type_check.pyc", line 11, in <module>
>   File "numpy\core\__init__.pyc", line 25, in <module>
>   File "numpy\core\numeric.pyc", line 407, in <module>
> AttributeError: 'module' object has no attribute 'einsum'
> ```
> 

Running Windows 7. Never had a similar problem that wasn't caused by a Pixiv API update, but v20170705 is still working just fine.

Tried copying the config/db files from v20170705 into this version's directory (in case it was having trouble creating new ones), but no luck. Not sure what else to test on my own.

**Comment by Nandaka** [comment]
Looks like compilation issue, please download the new binary,

https://github.com/Nandaka/PixivUtil2/releases/tag/pixivutil20170813-beta1
