### ISSUE TITLE
TypeError trying to run exe from python

### ISSUE THREAD

**Issue by da3dsoul** [Nandaka/PixivUtil2#254]
I have set up the required config.ini stuff.
I have this in a python 3 script
```
subprocess.call(['C:\\Users\\da3ds\\Downloads\\pixivutil20170705\\PixivUtil2.exe', '-s', '6', 'y', '0', '4', '-x'])
```
When I run that, I get:
```
PixivDownloader2 version 20170705
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\Users\da3ds\Downloads\pixivutil20170705\config.ini ...
done.
Traceback (most recent call last):
  File "PixivUtil2.py", line 1910, in <module>
  File "PixivUtil2.py", line 1792, in main
  File "PixivHelper.pyc", line 313, in toUnicode
TypeError: unicode() argument 2 must be string, not None
```
Which makes absolutely no sense to me, seeing as argument 2 would be '6' if I'm not mistaken.
I have tried various other attempts, such as these, and I tried running it in python 2.7 as well
```
os.system('C:\\Users\\da3ds\\Downloads\\pixivutil20170705\\PixivUtil2.exe -s 6 y 0 4 -x')
```
```
subprocess.Popen(['C:\\Users\\da3ds\\Downloads\\pixivutil20170705\\PixivUtil2.exe', '-s', '6', 'y', '0', '4', '-x'])
```
with identical results.

I really don't want to grab deps and run it from python....
Any ideas how or why this isn't working? Thanks in advance

**Comment by Nandaka** [comment]
Python 3 is not supported, the script is coded in python 2.7.

**Comment by da3dsoul** [comment]
I'm aware. It was just being called from python3. I have 2.7 as well. 2.7 gave exactly the same result.

**Comment by da3dsoul** [comment]
Eh I gave up and am running it as a module. Copy and organize scripts can be a pain for no good reason sometimes. Thanks anyway

**Comment by Nandaka** [comment]
Weird, 

I'm running your codes and it does run properly...

![image](https://user-images.githubusercontent.com/836867/29494517-bf410ce6-85de-11e7-9796-34ca8c6229a0.png)
(ignore the folder name, as I just pasting it to existing pixivutil folder).

**Comment by da3dsoul** [comment]
Yeah I don't know. Sometimes weirdness just isn't worth it. I did get it working as a module, though. I set it up as an auto bookmark downloader on task scheduler.
