### ISSUE TITLE
Identifier naming conventions are inconsistent

### ISSUE THREAD

**Issue by awiebe** [Nandaka/PixivUtil2#255]
Some variables seem to use underscores while others are camel-cased, is there a convention/ is the project moving towards a convention?  Should I make an effort to name new code appropriately/ should I make an effort to convert names in old code.

**Comment by Nandaka** [comment]
ahahahah, cos I do C# too.

so far I'm using pyscripter, which doesn't have refactor/rename feature.

If you want, you can send a pull request.

**Comment by NHOrus** [comment]
If you don't break existing config files, then feel free to proceed with refactoring.

**Comment by awiebe** [comment]
@Nandaka I use pycharm it's quite bloated, but pretty feature rich.  Pycharm helpfully highlights all the PEP8 problems so I'll just be going through until I run out of warnings.
https://github.com/awiebe/PixivUtil2/tree/feature/PEP8

**Comment by Nandaka** [comment]
I'm using pyscripter with pep8 addons, but I purposely disabled some warnings :smile:

**Comment by Nandaka** [comment]
programming styles,  will not do for now. I'm open for pull request.
