### ISSUE TITLE
Download by a member bookmarks list enhancement

### ISSUE THREAD

**Issue by Biscoff** [Nandaka/PixivUtil2#256]
I have a size able number members who's bookmarks I like to downloaded and keep tabs on.
Rather than having to add them one at a time, can it be possible implement a member bookmarks list option, possibly reading from a member_bookmark_list.txt, so that multiple member bookmarks can queue and be downloaded consecutively?

**Comment by Nandaka** [comment]
You can ```m. Export online user bookmark```, then use ```4. Download from list```.

Or you can use ```8. Download new illust from bookmarked members (bookmark_new_illust.php)```
