### ISSUE TITLE
ugoira duplicate or impartial download improperly handled

### ISSUE THREAD

**Issue by NaruFGT** [Nandaka/PixivUtil2#258]
Under various conditions, os.rename() and os.delete() are called without error handling. If they fail (such as when the overwrite option is not enabled) The entire process will be retried, but fail each time. Once the configured retry attempts have been exhausted, the process will end. This is incredibly frustrating when downloading by member ID.
Also duplicate ugoira (file exists) is not handled properly as of yet.

Would you accept a PR for a configuration option that is a sortof on error resume next image?

**Comment by Nandaka** [comment]
sure, but if possible, make it configureable.

**Comment by Nandaka** [comment]
closed for now
