### ISSUE TITLE
Using %date_fmt{format}%  in filenameformat

### ISSUE THREAD

**Issue by moono** [Nandaka/PixivUtil2#259]
hello,

In my config.ini I changed to following to save images with current date in file name.

[Settings]
filenameformat = %date_fmt{%H-%M-%S}% - %urlFilename%

But it seems saved file names are always saved in format "00-00-00- %urlFilename%"

Could you check?

**Comment by moono** [comment]
Oh I forgot to mention that I'm using your latest stable release executable pixivutil20170705 .

**Comment by Nandaka** [comment]
Existing only support date, not the time 😄 
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L163

I can change to use ```datetime.today()```

**Comment by moono** [comment]
Thank you for the reply.
I will be nice if you could add time string support in future release.

**Comment by Nandaka** [comment]
Can you create separate issue findings so I can add the time formatting there :D
