### ISSUE TITLE
resume upon power on?

### ISSUE THREAD

**Issue by chaosrealm93** [Nandaka/PixivUtil2#260]
hey,  just curious

if the program is running and i accidentally put the computer to sleep, will it automatically pick up where it left off when i wake the computer?

thanks!

**Comment by NHOrus** [comment]
Sleep, not power on?  
It may fail or retry currently downloading image, and then continue like nothing happened.

**Comment by chaosrealm93** [comment]
yes sleep, not a shutdown.  sorry for the confusion

**Comment by Gandeloft** [comment]
Yes it will, at least regarding hibernation.
I always place my PC in hibernation mode if the pixivutil is working.
It normally resumes upon being woken up.

**Comment by chaosrealm93** [comment]
cool,  thanks!


________________________________
