### ISSUE TITLE
I can not log in suddenly.

### ISSUE THREAD

**Issue by WBWBWBS** [Nandaka/PixivUtil2#263]
This is about three days ago. In the meantime, my computer settings have not changed, and the Internet is working normally.

The following error message is displayed.

___________________________________________
Trying to log with saved cookie
Error at doLogin (): (<class 'urllib2.URLError'>, URLError (gaierror (11001, 'getaddrinfo failed'),), <traceback object at 0x03221300>
Can not Login!
press enter to exit.
___________________________________________

I tried the Q3 solution in the readme.txt, but the problem was not resolved.
I downloaded the pixiv downloader again and tried to log in from the beginning, but the same error is displayed. (I did not reuse log files or configuration files at all.)

I have two pixiv accounts, all tried sign-in, but display the same error message.

plz help me.
 sorry for my bad english :(

**Comment by Nandaka** [comment]
>> getaddrinfo failed

Meaning the application cannot get the pixiv server ip address.  If you can open the site on the browser, most likely either your antivirus or firewall block the connection.

**Comment by WBWBWBS** [comment]
I have entered Windows Safe Mode at all, but the same message is printed. I'm going to try it on a subcomputer with Windows XP installed.

However, when I used the latest version of the pixiv downloader on Windows XP, it turned off as soon as I ran the exe. Can you tell when the last version of pixiv downloader was supported on xp?

**Comment by Nandaka** [comment]
XP is not supported due to changes on pixiv website security (server side changes).

**Comment by WBWBWBS** [comment]
Thanks for your help. It works fine on other computers on the same network. I just have to retry the next time I format this computer on my current computer.
