### ISSUE TITLE
Filling prompts with piped data on Linux

### ISSUE THREAD

**Issue by hi117** [Nandaka/PixivUtil2#264]
When attempting to fill prompts with data from a pipe on linux, it hangs with the following error:
```
PixivDownloader2 version 20170813-beta1
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading /home/hi117/Pictures/PixivUtil2/config.ini ...
done.
Traceback (most recent call last):
  File "PixivUtil2.py", line 1918, in <module>
    main()
  File "PixivUtil2.py", line 1800, in main
    dfilename = PixivHelper.toUnicode(sys.path[0], encoding=sys.stdin.encoding) + os.sep + dfilename
  File "/home/hi117/Pictures/PixivUtil2/PixivHelper.py", line 313, in toUnicode
    obj = unicode(obj, encoding)
TypeError: unicode() argument 2 must be string, not None
```

The actual thing I'm trying to do is similar to #150, but this seems to require automatically filling in the prompts. I did not see a mention of anything that would seem useful for this in the readme or the help page. Is there a way to automatically fill fields to make the program completely runable without interaction?

**Comment by Nandaka** [comment]
The script is not designed to receive input via piping (or designed for linux, I don't use it).

You can try to use command line option? Refer to https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L176

**Comment by hi117** [comment]
So looking into it more, there appears to be an undocumented feature where the program can pull some of the options from the command line, but not all of them. This could be flushed out and documented or proper command line options can be added to fill in the information.
Also I looked into the error I posted and it appears that python2 does not specify an encoding for a pipe as shown below, but python3 does. I think its safe to assume that we can assume UTF-8 if no encoding is known since python3 does.

```
$ cat - | python3 -c 'import sys; print(sys.stdin.encoding)'
UTF-8
$ cat - | python2 -c 'import sys; print(sys.stdin.encoding)'
None
```

**Comment by Nandaka** [comment]
which option you talking about? I'm not really using the command line as I usually run it in interactive mode.

**Comment by NHOrus** [comment]
For me, invocation for command line (on linux) looks like this:  
`python2.7 PixivUtil2.py -s 4 lixt.txt TAG -x`  
`lixt.txt` is a placeholder, PixivUtil ignores it. Because file with user IDs is called list.txt and despite wrong letter in command, PixivUtil used correct file.  
TAG is a tag. I don't know how to skip it. `""` - empty list in that place - maybe? This is question to Nandaka.

**Comment by Nandaka** [comment]
> lixt.txt 

It will check if the file exists or not. If not, use the default ```list.txt```
Refer to: https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1434

> TAG

it will check if there is any trailing parameter, if yes, then use it as tag
Refer to: https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1437

Try to write ```python2.7 PixivUtil2.py -x -s 4 lixt.txt TAG```?
