### ISSUE TITLE
r18mode doesn't work.

### ISSUE THREAD

**Issue by YTOAA** [Nandaka/PixivUtil2#268]
[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
userobots = True
timeout = 60
retry = 3
retrywait = 5

[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = False

[IrfanView]
irfanviewpath = C:\Program Files\IrfanView
startirfanview = False
startirfanslide = False
createdownloadlists = False

[Settings]
filenameformat = (%searchTags%)(%R-18%)\%searchTags%[%artist%]%member_id%[%title%](%R-18%)(%tags%)[%image_id%]
filenamemangaformat = (%searchTags%)(%R-18%)\%searchTags%[%artist%]%member_id%[%title%](%R-18%)(%tags%)[%image_id%] %page_index%
filenameinfoformat = %artist% (%member_id%)\%urlFilename% - %title%
avatarnameformat = 
downloadlistdirectory = .
uselist = False
processfromdb = True
overwrite = False
tagsseparator = ,
daylastupdated = 7
rootdirectory = .
alwayscheckfilesize = False
checkupdatedlimit = 0
downloadavatar = True
createmangadir = False
usetagsasdir = False
useblacklisttags = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = False
writeimagejson = False
datediff = 0
backupoldfile = False
writeugoirainfo = False
createugoira = False
deletezipfile = False
enableinfiniteloop = False
verifyimage = False
writeurlindescription = False
urlblacklistregex = 
urldumpfilename = url_list_%Y%m%d
dbpath = 
creategif = False
useblacklistmembers = False
createapng = False

[Authentication]
username = 
password =
cookie = 
keepsignedin = 0

[Pixiv]
numberofpage = 0
r18mode = True
dateformat = 

r-18mode = true
only r-18 images should be downloaded but downloaded to the normal image
version pixivutil20170813-beta1

**Comment by Nandaka** [comment]
should be fixed in https://github.com/Nandaka/PixivUtil2/pull/261
