### ISSUE TITLE
Unknown Error: Decompressed Data Too Large

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/PixivUtil2#269]
Trying to download image 58286727.
 
> 2017-10-03 12:36:05,332 - PixivUtil20170813-beta1 - ERROR - Error at process_image(): (<type 'exceptions.ValueError'>, ValueError('Decompressed Data Too Large',), <traceback object at 0x03195120>)
> 2017-10-03 12:36:05,332 - PixivUtil20170813-beta1 - ERROR - Traceback (most recent call last):
>   File "PixivUtil2.py", line 686, in process_image
>   File "PixivUtil2.py", line 175, in download_image
>   File "PIL\Image.pyc", line 2439, in open
>   File "PIL\Image.pyc", line 2429, in _open_core
>   File "PIL\ImageFile.pyc", line 100, in __init__
>   File "PIL\PngImagePlugin.pyc", line 533, in _open
>   File "PIL\PngImagePlugin.pyc", line 131, in call
>   File "PIL\PngImagePlugin.pyc", line 314, in chunk_iCCP
>   File "PIL\PngImagePlugin.pyc", line 85, in _safe_zlib_decompress
> ValueError: Decompressed Data Too Large
> 
> 2017-10-03 12:36:05,332 - PixivUtil20170813-beta1 - ERROR - Error at process_image(): 58286727
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 686, in process_image
>   File "PixivUtil2.py", line 175, in download_image
>   File "PIL\Image.pyc", line 2439, in open
>   File "PIL\Image.pyc", line 2429, in _open_core
>   File "PIL\ImageFile.pyc", line 100, in __init__
>   File "PIL\PngImagePlugin.pyc", line 533, in _open
>   File "PIL\PngImagePlugin.pyc", line 131, in call
>   File "PIL\PngImagePlugin.pyc", line 314, in chunk_iCCP
>   File "PIL\PngImagePlugin.pyc", line 85, in _safe_zlib_decompress
> ValueError: Decompressed Data Too Large
> 2017-10-03 12:36:05,332 - PixivUtil20170813-beta1 - DEBUG - Sanitized Filename: Error medium page for image 58286727.html
> 2017-10-03 12:36:05,332 - PixivUtil20170813-beta1 - ERROR - Dumping html to: Error medium page for image 58286727.html
> 2017-10-03 12:36:05,332 - PixivUtil20170813-beta1 - ERROR - Traceback (most recent call last):
>   File "PixivUtil2.py", line 686, in process_image
>   File "PixivUtil2.py", line 175, in download_image
>   File "PIL\Image.pyc", line 2439, in open
>   File "PIL\Image.pyc", line 2429, in _open_core
>   File "PIL\ImageFile.pyc", line 100, in __init__
>   File "PIL\PngImagePlugin.pyc", line 533, in _open
>   File "PIL\PngImagePlugin.pyc", line 131, in call
>   File "PIL\PngImagePlugin.pyc", line 314, in chunk_iCCP
>   File "PIL\PngImagePlugin.pyc", line 85, in _safe_zlib_decompress
> ValueError: Decompressed Data Too Large
> 
> 2017-10-03 12:36:05,335 - PixivUtil20170813-beta1 - ERROR - Unknown Error: Decompressed Data Too Large
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 1884, in main
>   File "PixivUtil2.py", line 1663, in main_loop
>   File "PixivUtil2.py", line 1347, in menu_download_by_image_id
>   File "PixivUtil2.py", line 686, in process_image
>   File "PixivUtil2.py", line 175, in download_image
>   File "PIL\Image.pyc", line 2439, in open
>   File "PIL\Image.pyc", line 2429, in _open_core
>   File "PIL\ImageFile.pyc", line 100, in __init__
>   File "PIL\PngImagePlugin.pyc", line 533, in _open
>   File "PIL\PngImagePlugin.pyc", line 131, in call
>   File "PIL\PngImagePlugin.pyc", line 314, in chunk_iCCP
>   File "PIL\PngImagePlugin.pyc", line 85, in _safe_zlib_decompress
> ValueError: Decompressed Data Too Large
> 2017-10-03 12:36:41,440 - PixivUtil20170813-beta1 - INFO - EXIT: -1

**Comment by Nandaka** [comment]
Looks like it is a known issue on PIL (refer to https://stackoverflow.com/a/42682508).

I can either increase ```PIL.ImageFile.SAFEBLOCK``` to larger size, but increase the memory consumption or set the flag ```PIL.ImageFile.LOAD_TRUNCATED_IMAGES``` to true, but this will ignore the metadata.

The image itself looks like has ICC profile attached.

**Comment by reyaz006** [comment]
I see.
Do you think it's possible to use something else to download the images? I think the tool shouldn't look inside the files and process any metadata, at least for static images. Or is it trying to re-compress PNG?

**Comment by Nandaka** [comment]
I'm using the ImageFile to check the downloaded images whether the file is corrupted or not.

I can set the ```PIL.ImageFile.LOAD_TRUNCATED_IMAGES``` to True, it will download the file just fine, but it will ignore the metadata if it is too large.

**Comment by Nandaka** [comment]
check the new upload:
https://github.com/Nandaka/PixivUtil2/releases/tag/v20171004

**Comment by reyaz006** [comment]
> I'm using the ImageFile to check the downloaded images whether the file is corrupted or not.

How good does it work though? E.g. if there was 1 wrong byte transferred in a JPEG stream, it should still work as an image, from what I understand. Should be same for non-compressed PNG files.

> I can set the PIL.ImageFile.LOAD_TRUNCATED_IMAGES to True, it will download the file just fine, but it will ignore the metadata if it is too large.

Bad choice I think - removing the included color profile may affect the color quality (produce wrong or not intended colors), from my experience.

If it's possible to increase PIL.ImageFile.SAFEBLOCK only for cases when an error is detected or is it a global value?

**Comment by Nandaka** [comment]
it should not affect the downloaded file, as I only use it just to validate if the image is corrupted or not.
also, it is configurable.

Refer to https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L170

**Comment by reyaz006** [comment]
Oh, I see now. Thanks.
