### ISSUE TITLE
Can't download by tag

### ISSUE THREAD

**Issue by Shamanking24** [Nandaka/PixivUtil2#270]
I'm using pixivutil20170813 v2 and got an issue like this when trying to download by tag:

Input: 3
Tags: 1000users入り
Bookmark Count:
Use Partial Match (s_tag) [y/n]: y
Oldest first[y/n]: n
Start Page (default=1):
End Page (default=0, 0 for no limit):
Start Date [YYYY-MM-DD]:
End Date [YYYY-MM-DD]:
Reading G:\PX\config.ini ...
done.
Searching for: (1000users入り) 1000users%E5%85%A5%E3%82%8A
Using Partial Match (s_tag)
Looping... for https://www.pixiv.net/search.php?s_mode=s_tag&p=1&word=1000users%E5%85%A5%E3%82%8A&order=date_d
Error at process_tags(): (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x04996E90>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1884, in main
  File "PixivUtil2.py", line 1665, in main_loop
  File "PixivUtil2.py", line 1386, in menu_download_by_tags
  File "PixivUtil2.py", line 810, in process_tags
  File "PixivBrowserFactory.pyc", line 481, in getSearchTagPage
  File "PixivModel.pyc", line 956, in parseTags
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.

**Comment by lvl5mentalout** [comment]
Same problem :(

**Comment by Nandaka** [comment]
they randomized the css class now...
![image](https://user-images.githubusercontent.com/836867/31159804-4107e140-a8fe-11e7-85c2-8a6d70d583df.png)
