### ISSUE TITLE
Cannot process downloads - NameError: global name 'PIL' is not defined

### ISSUE THREAD

**Issue by Evaia** [Nandaka/PixivUtil2#272]
Error received is as follows: 
`Start downloading... Using Referer: https://www.pixiv.net/                                                                  23816 of     23816 Bytes  Completed in 0.002s (11.36 MiB/s)
 Image invalid, deleting...
Traceback (most recent call last):
  File "PixivUtil2.py", line 176, in download_image
NameError: global name 'PIL' is not defined
Error at download_image(): (<type 'exceptions.NameError'>, NameError("global name 'PIL' is not defined",), <traceback object at 0x04137A80>) at https://i.pximg.net/user-profile/img/2016/09/08/02/29/02/11466629_db44fce4505b7bb5e52ec3cf810ae289_170.jpg (9000)`
Error repeats and eventually gives up, attached is generated error page. 
[Error page for member 3406627.zip](https://github.com/Nandaka/PixivUtil2/files/1361142/Error.page.for.member.3406627.zip)

**Comment by Evaia** [comment]
Update: issue does not occur on 20170813-beta1v2

**Comment by Nandaka** [comment]
try latest releases

**Comment by Evaia** [comment]
can confirm that seems to have fixed it, cheers.
