### ISSUE TITLE
How to redownload image if not exists in file system?

### ISSUE THREAD

**Issue by eromoe** [Nandaka/PixivUtil2#274]
Hello, 

It looks like only check the id if exists in db now. Because I made a change to `PixivUtil2` (detect folder name at first before download, to make sure each artist only has one folder),  but my change is buggy now,  it caused some exception in  `makefilename` , and this exception  seems not affect db .
How can I make PixivUtil2 redownload image if it not exists on my file system ?

Futher more, I think it would be much useful if :

1. only save by image id ( manga add `p0` ~ `pxx` suffix)
2. so everytime you download can know if file exists , then redownload the not exists ones.
3. some time , user want to tag image with some info, it can use db's infomation,  bluk rename the file by file name(id) .

PS:  I found a werid file `54229127_p0.jpg.pixiv` , I remove `.pixiv` still can't open . Is it generate by `PixivUtil2` ?  If not, may be my change's fault ...

**Comment by eromoe** [comment]
OK , I find `alwayscheckfilesize = True`  .

> alwaysCheckFileSize   ==> Check the file size, if different then it will be
>                           downloaded again, set 'False' to disable.
>  		       -> Override the overwrite and image_id checking from db
>                           (always fetch the image page for checking the size)

 `Check the file size`   ?  Could you mind to explain how this work ? 

The ideal way I think is : 
1. get `ids` from db
2. get all filename, parse to `ids2`
3. if there is any `ids` not in `ids2` , redownload it

**Comment by NHOrus** [comment]
Look up "Clean DB" from DB page. It checks that each file in DB is actually on disk, if it's not, record is removed from DB.

**Comment by Nandaka** [comment]
> Check the file size ? Could you mind to explain how this work ?

It will compare the local file size in disk and the one from the server (it will issue HEAD command to get the remote size.

or you can do DB cleanup like NHOrus said (press 'd', then 'c')

**Comment by eromoe** [comment]
So `check file size`  would need grab all image link of an artist and send HEAD to query size . Hmm ... seems not so inefficient , fine.

Any idea about  `xxxxx_p0.jpg.pixiv`  file ?

**Comment by Nandaka** [comment]
well, if you want to compare the actual file size in server and in the local file, that is the only way.

> .pixiv

That one you can delete. It is a temporary file used when downloading.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L562
