### ISSUE TITLE
Remove illustration title/name from downloaded images name

### ISSUE THREAD

**Issue by Kira-20** [Nandaka/PixivUtil2#275]
Hye there, I just started using this tool today and I always download images using the tags option. And as such, I was wondering if there is a way to not make the downloaded images show the illustration's title/names in them. Like for example "1234567_p0 Morning Coffee". Is it possible to make the tool to download with just the "1234567_p0" and not with the "Morning Coffee". Thanks for your time.

**Comment by Nandaka** [comment]
Please check the readme.txt for filenameformat
