### ISSUE TITLE
Add random or configurable delay on each image download

### ISSUE THREAD

**Issue by UnforeseenOcean** [Nandaka/PixivUtil2#276]
I think this may be needed because Pixiv really doesn't like users rapidly downloading tons of images and it also makes site slower for others.

**Comment by NHOrus** [comment]
See comment in last commit, you forgot to change one enableDelay to downloadDelay, everything's not working.

**Comment by Nandaka** [comment]
updated

**Comment by NHOrus** [comment]
Appears to be working now. Can't say anything about usefulness yet.

**Comment by Nandaka** [comment]
well, you can set to 0 to disable.

As far as I know, I never hit error without setting any delay with Pixiv. 
I know some sites will throw 429 Too Many Request if you download too much imaged 😛

**Comment by NHOrus** [comment]
Ok, testing of this feature feels like it's  increased overall throughput of PixivUtil2. On the order of 30% less time taken to process my hueg list.txt

**Comment by NHOrus** [comment]
Prop delay between separate pages of manga?

**Comment by Nandaka** [comment]
no, it is only for each post.
