### ISSUE TITLE
Linux: File name sanitization

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#277]
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=55002535 for example, got slash ("/") in it's file name. As slash is file path separator, python created a directory where none were needed, mangling names in the process, too.

**Comment by Nandaka** [comment]
This is tricky as the sanitization is only done for the fullpath based on the filename format so I purposely exclude the '/' from sanitization, as I used it as folder separator.

https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L57

**Comment by NHOrus** [comment]
I don't have any solutions, except maybe run routine with '/' included on %title% and %artist% ?

**Comment by Nandaka** [comment]
I think I can always replace '/' on %title% and %artist% to '_'.

**Comment by NHOrus** [comment]
Thank you.

Will test and report results day after tomorrow or so.

**Comment by NHOrus** [comment]
Please also replace "\" in same with same.

Because it also causes folder creation T_T

**Comment by Nandaka** [comment]
linux treat both '/' and '\' for folder? no other valid path separator beside those two, right?

**Comment by NHOrus** [comment]
I think '\\' is more about python and file creation function, due to log output, and no more valid path separators that I know of.

**Comment by Nandaka** [comment]
updated

**Comment by NHOrus** [comment]
Works, thank you. Time to cut a new release?
