### ISSUE TITLE
Downloading by tags in batch

### ISSUE THREAD

**Issue by smokeofc** [Nandaka/PixivUtil2#278]
I've been trying to figure out how to go about downloading tagged bookmarks by tag using a batchfile, but can't find anything. I'd like to submit a feature request for that. 👍 

Love the app btw <3

**Comment by Nandaka** [comment]
use `7 - Download from tags list` ?

**Comment by smokeofc** [comment]
Well and good, but that's sitewide search, isn't it? I'm thinking about limited to bookmarks

**Comment by Nandaka** [comment]
currently no 'batch' feature for that, but you can do it manually from `6 - Download from image bookmark`

**Comment by smokeofc** [comment]
As far as I gather... If I start the app using the arguments '-s 6 y' it'll download all the bookmarks, but if I want it narrowed to only one tag in my bookmarks I'll need to launch the app manually and run the 6 option?

**Comment by Nandaka** [comment]
yap, currently it doesn't accept the tag parameter from command line

**Comment by smokeofc** [comment]
That did the trick! Thanks a bunch for your hard work (^_^)
