### ISSUE TITLE
Images downloaded in Self (0) when Download by member IDs.

### ISSUE THREAD

**Issue by Asurey** [Nandaka/PixivUtil2#279]

**Comment by Nandaka** [comment]
please upload the log file and member id?

**Comment by NHOrus** [comment]
And `filenameformat` strings from config.ini, just to be sure.

**Comment by Asurey** [comment]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/1504276/pixivutil.log)

Sorry I don't have the member ID's, I used may and I couldn't find a way to retrieve them. 

As for the filename strings, here they are:
filenameformat = %artist% (%member_id%)\%urlFilename% - %title%
filenamemangaformat = %artist% (%member_id%)\%urlFilename% - %title%
filenameinfoformat = %artist% (%member_id%)\%urlFilename% - %title%

Is there anything else you need?

**Comment by Nandaka** [comment]
Update your applications, looks like you still using the old version `PixivUtil20170411`

Latest version in https://github.com/Nandaka/PixivUtil2/releases
