### ISSUE TITLE
1000 Page Limit

### ISSUE THREAD

**Issue by LieXXX** [Nandaka/PixivUtil2#280]
Hello,

I am noticing that it stops grabbing images after page 1000 and no longer grabs images.

Thanks

**Comment by Nandaka** [comment]
which site? some site set a hard limit to 1000pages.

**Comment by LieXXX** [comment]
Pixiv

**Comment by Nandaka** [comment]
ah, mixed up with other project. You need Pixiv Premium.

**Comment by LieXXX** [comment]
What are the chances of getting an account banned? I use a backup account when I download from Pixiv.

**Comment by Nandaka** [comment]
No idea, no one told me yet that their account is banned.

I'm usually only ran single instance when downloading, so it won't hammer the server.

**Comment by LieXXX** [comment]
I will try my premium account tomorrow.

**Comment by LieXXX** [comment]
I logged in with my premium account and it still stopped at 1000 pages.

**Comment by Nandaka** [comment]
have you deleted the cookie value in config.ini before you relogin in pixivutil?

It should allow you to download up to 5000 pages.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1110

**Comment by LieXXX** [comment]
Looks like it is working now. Thank you.
