### ISSUE TITLE
How to download pictures by tag but not albums?

### ISSUE THREAD

**Issue by Ruriko** [Nandaka/PixivUtil2#281]
So I'm downloading pictures by tags but I don't want it to download if it's an album. How can I do this?

**Comment by Nandaka** [comment]
you mean manga pages? nope, it doesn't support that. It won't differentiate between single images and manga pages.

**Comment by Ruriko** [comment]
Ok then I would like to request this feature to be added

**Comment by Nandaka** [comment]
most likely I won't add it. I don't see a compelling reason to skip manga pages when you can use NOT operator when searching (e.g. `NOT 漫画`)
