### ISSUE TITLE
Error [ does not match format '%Y-%m-%d %H:%M' ]

### ISSUE THREAD

**Issue by Unknown2353** [Nandaka/PixivUtil2#283]
Error [ does not match format '%Y-%m-%d %H:%M' ]
Right-frequency extremity Language setting [日本語 English 한국어 简体中文 繁體中文 ]
Set language - > Specific country - > Error

I don't know if you know.
Just let me know.

**Comment by Nandaka** [comment]
Change the `dateformat` configuration in config.ini. You may need to delete the cookie value after updating.

Refer to:
```
dateformat   ==> Pixiv DateTime format, leave blank to use default format for
                 English or Japanese. Refer to http://strftime.org/ for syntax.
		 Quick Reference:
		 %d = Day, %m = Month, %Y = Year (4 digit), %H = Hour (24h)
		 %M = Minute, %S = Seconds
```

This is my datetime format: %m/%d/%Y %H:%M
![image](https://user-images.githubusercontent.com/836867/33590645-bf567596-d9bb-11e7-9f2a-14693bfe0494.png)
