### ISSUE TITLE
How do I check for new pics from an artist?

### ISSUE THREAD

**Issue by soli18** [Nandaka/PixivUtil2#284]
How do I let the client check and add new pictures to the already downloaded galleries from specified artists in the same folder?

Thanks in advance.

**Comment by NHOrus** [comment]
You run PixivUtil with same settings and artist id, it will skip all images it already downloaded.  
You can set `checkupdatedlimit` in `config.ini` to 5 so it would stop after encountering five consecutive images that already present in it's database.

**Comment by soli18** [comment]
Changing the `checkupdatelimit` to 5 would just stop the whole "updating" process wouldn't it?  Since all images beside the new ones are the same.

Also is there a way for me to list a few artists which it should check when the command runs. Like putting their ids in a txt file or something.

**Comment by NHOrus** [comment]
it's `list.txt` and option 4...

Read readme.

**Comment by soli18** [comment]
Sorry for answering late. Had to try what you suggested but didn't work. Below a few screenshots.

A few days ago I downloaded all pictures from an artist https://i.imgur.com/FBBCTJa.png

Today the artist uploaded a new set of pictures and I tried what you mentioned in your post to download the new pictures to the same old folder with the other pictures. 

This is my list.txt https://i.imgur.com/b8BE3p8.png
Here a pic of my config: https://i.imgur.com/6ICOj0L.png

When trying to run the client it gives me this error: https://i.imgur.com/sEckZsH.png
When setting `uselist` to false it gives me this: https://i.imgur.com/qRWcjmh.png

**Comment by Nandaka** [comment]
Set uselist = true and processFromDB = false?

try to use list.txt without directory first?
```
13134
```

**Comment by soli18** [comment]
Error: https://i.imgur.com/iqYwsJI.png

**Comment by Nandaka** [comment]
upload both list.txt and config.ini here, I cannot replicate the error.

**Comment by soli18** [comment]
config.ini

[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
userobots = True
timeout = 60
retry = 10
retrywait = 5
downloaddelay = 2

[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = False

[IrfanView]
irfanviewpath = C:\Program Files\IrfanView
startirfanview = False
startirfanslide = False
createdownloadlists = False

[Settings]
filenameformat = %artist% (%member_id%)\%urlFilename% - %title%
filenamemangaformat = %artist% (%member_id%)\%urlFilename% - %title%
filenameinfoformat = %artist% (%member_id%)\%urlFilename% - %title%
avatarnameformat = 
downloadlistdirectory = C:\Users\Soli\Desktop\Nieuwe map (3)
uselist = True
processfromdb = False
overwrite = False
tagsseparator = ,
daylastupdated = 0
rootdirectory = C:\Users\Soli\Desktop\Nieuwe map (3)
alwayscheckfilesize = False
checkupdatedlimit = 0
downloadavatar = False
createmangadir = True
usetagsasdir = False
useblacklisttags = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = False
writeimagejson = False
datediff = 0
backupoldfile = False
writeugoirainfo = False
createugoira = False
deletezipfile = False
enableinfiniteloop = False
verifyimage = False
writeurlindescription = False
urlblacklistregex = 
urldumpfilename = url_list_%Y%m%d
dbpath = 
creategif = True
useblacklistmembers = False
createapng = True

[Authentication]
username = * (Hide)
password = * (Hide)
cookie = *   (Hide)
keepsignedin = 1

[Pixiv]
numberofpage = 0
r18mode = False
dateformat = 

list.txt

# 水あさと
13134

**Comment by Nandaka** [comment]
Weird, it is working on my side.
![image](https://user-images.githubusercontent.com/836867/33826882-5b73af9a-dea1-11e7-8d4a-ab3f698094bf.png)

[list.txt](https://github.com/Nandaka/PixivUtil2/files/1547440/list.txt)

![image](https://user-images.githubusercontent.com/836867/33826917-7588a052-dea1-11e7-8dcf-e14b98bd6aad.png)

**Comment by soli18** [comment]
Tried uninstalling and reinstall but no success.

Client only works when `uselist is set to False and processfromdb set to True`

**Comment by soli18** [comment]
Just downloading the gallery works fine but updating it through the list.txt and 4th command doesn't.

**Comment by Nandaka** [comment]
what is the encoding type when you save the list.txt? I notice you put some kanji/kana. Ensure it is saved as UTF-8.

![image](https://user-images.githubusercontent.com/836867/33832695-0c5e8224-deb8-11e7-9de7-f450682534bb.png)

**Comment by soli18** [comment]
Oh lol now it works. It's downloading the whole gallery now. Will see if it works with updating the gallery when the artist does upload something new.

Thankyou very much for your time and help appreciate it.
