### ISSUE TITLE
DB in use error when one process finishes if multiple processes are open

### ISSUE THREAD

**Issue by LieXXX** [Nandaka/PixivUtil2#286]
If I use more than one PixivUtil2 process to download from Pixiv and one process finishes it's task. The other processes get a DB in use error. The finished process seems to lock the database file, preventing anything else from being downloaded.

EDIT: It does not seem to always happen.

**Comment by Nandaka** [comment]
It is not supported by sqlite, as it doesn't support concurrent DB write operation from different process.

**Comment by LieXXX** [comment]
I have been able to do multiple processes and they error but then continue when they get access. The issue is that when a process finishes and is asking me for input, it locks the DB for the other processes.

**Comment by Nandaka** [comment]
can you try to append -x on the command?

anyway, running multiple instance from the same folder is not supported

**Comment by LieXXX** [comment]
It runs so well from the same folder so well except for this one issue. The only thing I had to do was to increase the amount of retries when it errors out.

Where do you want me to add the -x command?

**Comment by Nandaka** [comment]
you can use it if you are not running the application in interactive mode (e.g. from command line)

refer to https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L178
