### ISSUE TITLE
Database entries use absolute path instead of relative to download root

### ISSUE THREAD

**Issue by awiebe** [Nandaka/PixivUtil2#287]
Looking in the database file it seems to store file paths as absolute path rather than a location relative to ```rootdirectory```

**Comment by Nandaka** [comment]
It shouldn't. It will check the current script path or use the path you are given from config.ini

https://github.com/Nandaka/PixivUtil2/blob/master/PixivDBManager.py#L21
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1845

**Comment by awiebe** [comment]
It might be because some of the entries I have are from a much older version of the utility, they seem to have been created by release 20160814. 

Is the purpose of
https://github.com/Nandaka/PixivUtil2/blob/7801e4c862780e105902c9c971ed077cd87dcd84/PixivDBManager.py#L637
To update these entries, and newer versions use relative path?

**Comment by awiebe** [comment]
Just ran a new download pass after manually updating path information for relative paths.
Using release **20171127**

It seems that pixivutil can tell whether a file already exists at either a relative or absolute path( obviously this should work because the OS handles it), but **absolute paths are still stored in** `pixiv_master_image.save_name`

e.g.
After having updated all my save names I ran task 5 (download artists).
Newly created entires include:
`/Users/awiebe/git/PixivUtil2/_data/<username>(<id>)/<fileName>`

Which should be

`_data/<username>(<id>)/<fileName>`

**Comment by Nandaka** [comment]
ah you means the downloaded filename. It will store absolute path for maximum compatibility in Windows (I'm using Windows, not linux)

I'm not sure how to write relative path if my download root is on different drive or on samba share (not mounted to a folder).

**Comment by awiebe** [comment]
I symlinked my data folder in the end, but still had issues because I moved where the pixiv util was on disk.

I see no reason why absolute path would be needed for compatibility, python is very good at resolving paths on many systems.

I'm not sure what windows based incompatibility you're talking about, according to python
https://docs.python.org/2/library/os.path.html

> os.path.abspath(path)¶
> Return a normalized absolutized version of the pathname path. On most platforms, this is equivalent to calling the function normpath() as follows: normpath(join(os.getcwd(), path)).
> 
> New in version 1.5.2.

> os.path.relpath(path[, start])¶
> Return a relative filepath to path either from the current directory or from an optional start directory. This is a path computation: the filesystem is not accessed to confirm the existence or nature of path or start.
> 
> start defaults to os.curdir.
> 
> Availability: Windows, Unix.
> 
> New in version 2.6.

> os.path.realpath(path)
> Return the canonical path of the specified filename, eliminating any symbolic links encountered in the path (if they are supported by the operating system).
> 
> New in version 2.2.
> 

I don't happen to have a nice python setup on a windows machine right now, but try running the following script(in any directory other than `C:\\` because it needs to go up at least one level) to test if relative paths work under your configuration.
```
import os
import os.path

cwd=os.getcwd()
#Basic checks print working directory
print(cwd)
print(os.path.abspath(cwd))

p=os.path.join(cwd,'..')
up_one_level=os.path.abspath(os.path.join(cwd,'..'))
print(p+"=>"+up_one_level)
print(os.path.exists(up_one_level))

if(os.path.exists(up_one_level)):
 this_path=os.path.join(up_one_level,os.path.basename(cwd)) #join up one level and the name of the working directory
 print(this_path) # should be cwd
 print(os.path.exists(this_path)) 
 print(os.path.relpath(up_one_level,start=cwd)) #should make ..
 print(os.path.relpath(cwd,start=cwd)) # should make .

```

**Comment by Nandaka** [comment]
I save my downloaded pics on different pc using hidden shared directory (e.g. //10.10.10.1/d$/somefolder) which mounted to a drive in local pc (e.g. z:).

I don't see why you need to move the root directory so often and I don't see the benefit of it. 
Replacing the root directory should be an exception not normal operation (at least you can do it from DB manager or sqlite browser).

**Comment by awiebe** [comment]
**I suppose you're right there are only three benefits**:
1. Convenience of not having to clean up the database if things get moved around on the local machine.
2. Convenience of not having to update paths if PixivUtil is copied or restored to a different machine.
3. https://github.com/Nandaka/PixivUtil2/issues/294 updating manga seems to be broken.

Well I've moved it several times now as my storage requirements/environment grew.
1. From my downloads to my git directory, so I could sync with the repo
2. To an external drive so it stopped taking so much space on my startup volume
3. To another small server I leave in the corner to run periodically
4. (Just the ``rootdirectory`` folder) to a new NAS I bought.

I've learned now that the best thing to do on *NIX machines is to symlink data, and point it to whatever you actually want.
The reason I think relative path is good is because any time I need to migrate to another server my paths could change as they did above.  I figured this would just work as I organized my files, but it didn't.

----
**I didn't know why pixivutil was unable to find my files until I looked in the DB**.  I have my ```rootdirectory=./data```, so maybe if nothing else there should be a note in the documentation that says 

> Even if rootdirectory is specified as a relative path, the corresponding absolute path will be used internally. If you move pixiv util use the **update root** tool in **manage database**.  

The following could also be added to the main menu printing at the top:
```
if __config__.rootdirectory != os.path.abspath(__config__.rootdirectory):
    #You can colorize print_warning text using the logic in setup.py
    print_warning('You have specified rootdirectory as a relative path, pixivutil does not support this.')
    print_warning('Absolute paths are used internally.  If you move pixivutil you will have to update the root directory using the database manager')
```
