### ISSUE TITLE
[enhancement] Modularize/Document Pieces of PixivUtil

### ISSUE THREAD

**Issue by awiebe** [Nandaka/PixivUtil2#288]
I like pixivutil because it means I don't have to write my own scraper whenever pixiv decides to change the layout- but I don't like that it's not easy to modify.

I tend to run it in batch mode but I would like to integrate it better into my server-ware.

I would fork it and modularize it myself, but I still want the benefit of the official maintainers changing the parsing logic if ```pixiv.net``` changes its layout.  So on that note, let me know how I can help or, if you want to keep it as is, I hope you'll try to keep it somewhat modular so it is easier to pull changes into forked projects.

Ideally I would like to see it clearly broken into the following pieces:

### Command Line Interface
- **Interactive Mode**: Currently this is how pixiv util runs, but it doesn't seem to be modular.
- **Batch mode**: Pixiv util can run in batch mode, but does not follow the ```getopt``` convention.

### Library
- **Model**: Currently ```PixivModel.py```
- **Session**: Seems to be part of  ```PixivUtil2.py```, confusingly mixed in with the menus. Ideally session should be separated, so it's obvious where login happened.

- **Task**: Seems to be part of  ```PixivUtil2.py```, clearly distinguishing a task from the utility would allow for some speed up in batch mode.  In interactive mode, tasks still have to be run synchronously for the progress reporting logic to work, but in batch mode, this could be converted to producer/consumer.  I understand the issue of making pixiv util faster has been raised before #231, it seems python can't do much in the way of threading if it's CPU bound, but it's I/O bound on HTTP requests, so threading downloads would speed things up considerably.

- **Database**: Support for multiple database adapters, I would for example like to connect to a MySql database.  I looked at the code and it looks like the CRUD is al the same, but it only supports SQLITE.  Apart from the fact that it hasn't been done yet, I don't see a reason why it couldn't support other databases.

SQLObject will automatically set up your connections for a variety of database engines using a url (which could be put in the config file) then you could switch to ORM or just send your current raw SQL.
http://www.sqlobject.org/SQLObject.html#declaring-a-connection

**Comment by Nandaka** [comment]
You can check https://github.com/Nandaka/PixivUtil2/blob/master/PixivModel.py for the main parsing logic.

You can check how I used it in the PixivBrowserFactory.py
for example, parsing artist page = https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L398

**Comment by Nandaka** [comment]
will not do, Open to pull request
