### ISSUE TITLE
Download new illust from bookmarked members isn't working

### ISSUE THREAD

**Issue by IPGxwcu** [Nandaka/PixivUtil2#290]
Downloader is returning no images from source url when selecting input 8.

I think pixiv may have changed their page format again.

**Comment by Revemohl** [comment]
It did, pixiv++ isn't working for bookmark_new_illust.php anymore either. That page looks just like the new search page now.

**Comment by Nandaka** [comment]
try latest version: https://github.com/Nandaka/PixivUtil2/releases

**Comment by IPGxwcu** [comment]
That fixed it for me. Thanks!
