### ISSUE TITLE
Problems updating tags.xml from Danbooru

### ISSUE THREAD

**Issue by JMM72** [Nandaka/PixivUtil2#292]
I've been a couple of weeks being practically unable to update tags.xml from Danbooru. After page 150 (they are like 320 now or so) I get error 500 from the server. There's no limit in the API for reading, only for updating posts and such things, so I don't know what could be happening on DD side. I've tried logging in with the cookies data, long pauses between retries (10 minutes), pauses between page downloads (8 seconds and it still happens).
Sometimes after a pause it continues for 10 pages before getting error 500 again, making the process pause for at least 10 minutes more. Of course at the end there are enough timeouts or I just get tired, and I have to wait like 30 minutes to retry, or I get error 500 immediately.
I don't know what exact method does DD use to retrieve the tag pages; if it's using the deprecated API, maybe the lack of restrictions only applies to using the new API. I don't know how hard is to update to the modern API, but sooner or later Danbooru will pull the plug for the old one again.
Anyone else is having this issue?
Note: sometimes it happens too during a normal batch download.

**Comment by Nandaka** [comment]
Have you tried to post this issue on their forum?

**Comment by Nandaka** [comment]
closed, as this is for pixivutil not danbooru
