### ISSUE TITLE
Database should store file integrity information.

### ISSUE THREAD

**Issue by awiebe** [Nandaka/PixivUtil2#295]
The database should store:
1. File_size
2. File MD5_checksum

Then the utility could verify the status of the collection.
## Quick verification
 - Check that the file size on disk equals the size in the database
 - Check that the file size equals the remote file size
## Long verification
 - Check that the file hash equals the stored hash
 - If a file is corrupt offer to download it again( this might involve going through the whole list of member posts until the desired filename is found).

**Comment by Nandaka** [comment]
will not do, open for pull request.
