### ISSUE TITLE
Slow download speed and/or no connection

### ISSUE THREAD

**Issue by KawKum** [Nandaka/PixivUtil2#298]
Problem happen in the latest release.
I try to use v20171127, and it works really well (normal). But with the latest release, download speed decrease significantly, sometimes no connection.

Nothing's wrong with my internet connection because i can use it normally.

**Comment by Nandaka** [comment]
That's weird, because I didn't touch anything on the download part.

Can you try with the older releases here: https://github.com/Nandaka/PixivUtil2/releases and see if it is not your pc problem?

**Comment by awiebe** [comment]
20171127 adds a throttle to the download, see the change log.
https://github.com/Nandaka/PixivUtil2/blob/9ce541406ebb96a44dbf5ffc8271f8f45f44068e/changelog.txt#L6

The blame log shows that nothing in the download logic has changed in anything more than 8 months, so it might be that pixiv just doesn't want to serve your requests.  If you set this throttle to zero for example, it might be that pixiv.net just starts dropping your connection (which is in theory why the throttle was put in in the first place).

**Comment by Nandaka** [comment]
That's on 20171127, not on the latest. He/she complaining on the latest.
![image](https://user-images.githubusercontent.com/836867/34557136-3627f760-f174-11e7-839a-5f4a300f368e.png)

Also, some isp are sharing the public ip for the subscribers, If it happens thats there are other users also using pixiv downloader (or similar programs), Pixiv might decides to throttle the connection.
