### ISSUE TITLE
Ability to Set Delay when looping?

### ISSUE THREAD

**Issue by LieXXX** [Nandaka/PixivUtil2#301]
Is it possible to set a delay with lopping?

**Comment by Nandaka** [comment]
Set ```downloaddelay = max_delay``` in config.ini. It will set a random delay between 0 to max_delay for each image post.

Setting it to 0 will disable the download delay.

**Comment by LieXXX** [comment]
I noticed now that the loop function is not working at all for me. I am trying a single tag search and recent  subscription updates.

**Comment by Nandaka** [comment]
Which version you are using? This feature is added on v20171127

Tag search should have wait between each image post.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L865
New image from Bookmarked artist
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1117

**Comment by LieXXX** [comment]
The wait works but the infinite loop does not work.

**Comment by Nandaka** [comment]
ensure ```enableInfiniteLoop = True``` and you downloading in descending order.
```
enableInfiniteLoop ==> Enable infinite loop for download by tags.
                       Only applicable for download in descending order (newest
                       first).
```

**Comment by LieXXX** [comment]
```enableinfiniteloop = True```

Here is my config file:

```[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
userobots = True
timeout = 60
retry = 100
retrywait = 10
downloaddelay = 5

[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = False

[IrfanView]
irfanviewpath = C:\Program Files\IrfanView
startirfanview = False
startirfanslide = False
createdownloadlists = False

[Settings]
filenameformat = H:\Pixiv Downloads\%tags%\%image_id%
filenamemangaformat = H:\Pixiv Managa Downloads\%tags%\%image_id% %page_index%
filenameinfoformat = Download\%tags%\%image_id%
avatarnameformat = 
downloadlistdirectory = .
uselist = False
processfromdb = True
overwrite = False
tagsseparator = ,
daylastupdated = 0
rootdirectory = .
alwayscheckfilesize = False
checkupdatedlimit = 0
downloadavatar = False
createmangadir = False
usetagsasdir = False
useblacklisttags = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = False
writeimagejson = False
datediff = 0
backupoldfile = False
writeugoirainfo = False
createugoira = True
deletezipfile = False
enableinfiniteloop = True
verifyimage = True
writeurlindescription = False
urlblacklistregex = 
urldumpfilename = url_list_%Y%m%d
dbpath = 
creategif = True
useblacklistmembers = False
createapng = False

[Authentication]
username = HellSPawning@gmail.com
password = MonkeyFox238587
cookie = 3507098_bde317704622f02f68afae501165c26d
keepsignedin = 1

[Pixiv]
numberofpage = 99999
r18mode = False
dateformat = 

```

**Comment by Nandaka** [comment]
Do you download the tags in descending order?

**Comment by LieXXX** [comment]
I download the files newest first, is that what you mean?

**Comment by Nandaka** [comment]
yep, can you upload the log file?

It should have contains ```Hit page 1000, trying to get workdate for last image id: <image_id>``` inside the log.

**Comment by LieXXX** [comment]
Maybe I am trying something I cannot loop. I am using option 8 to download new files from bookmarks. Does that option support looping? The other way I tried was using a tag and limiting the page to 250 or so and it also did not loop.

**Comment by Nandaka** [comment]
I don't think so, the looping uses ecd parameter (Timespan) which available when you do search by tags.

E.g. https://www.pixiv.net/search.php?s_mode=s_tag&word=vocaloid&scd=2017-12-01&ecd=2017-12-31

It is not available for new illustrations from followed members (https://www.pixiv.net/bookmark_new_illust.php). Appending the ecd parameters doesn't work.

**Comment by LieXXX** [comment]
So it will only loop at the default page end of tag searches?

**Comment by Nandaka** [comment]
at page 1000, it will check what is the last date of the image then it will restart from 1 with ecd defined from the last image.

This is a loophole from pixiv implementation. Pixiv website itself doesn't allow you to search more than 1000 page (unless you are premium member) or search more than 1 year.

**Comment by Nandaka** [comment]
Closed this issue as it supposed for the delay. if you have question for infinite loop, please open new issue.
