### ISSUE TITLE
[Enhancement] Optional page number for calling downloading bookmarked artist from command line

### ISSUE THREAD

**Issue by Kilo19** [Nandaka/PixivUtil2#304]
Option 5-"Download from bookmarked artists (bookmark.php?type=user)" supports page number interactively but the command line variant only supports a toggle to include bookmarks. I would like to have the page number option exposed on command line as well.

**Comment by Nandaka** [comment]
ah, it is already supported. I think I forgot to update the readme.txt

sample usage:
```PixivUtil2 -s 5 [y|n|o] <start_page> <end_page>
PixivUtil2 -s y 1 5"

**Comment by Nandaka** [comment]
readme update in e3fd9e7953ce5910311fed686cdd14567865af26
