### ISSUE TITLE
Invalid gif causes looping album download error

### ISSUE THREAD

**Issue by Evaia** [Nandaka/PixivUtil2#306]
Issue present starting with 20180118
Using download option "Download from list" with no tags specified; Album begins to download successfully but eventually encounters an issue stating `ValueError: tile cannot extend outside image` after which point it will loop a few times before terminating the download task.

full error below:

> Processing Image Id: 33997065
> Title: ドラクエ７落書き
> Tags : 漫画, ドラクエ7, アルマリ, 壁ドン, ようやく時代がマリベルにおいついた, キーファ離脱の真相, 壁パン, マリベル, DQ7, DQ500users入り
> Date : 2013-03-04 20:52:00
> Mode : manga
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=0
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p0.gif
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=1
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p1.gif
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=2
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p2.gif
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=3
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p3.gif
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=4
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p4.gif
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=5
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p5.gif
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=6
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p6.gif
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=7
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p7.gif
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=8
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p8.gif
> Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&illust_id=33997065&page=9
> Found:  https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p9.gif
> Page Count : 10
> Image URL : https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p0.gif
> Filename  : D:\pixiv\クール教信者 (463912)\33997065\_p0 - ドラクエ７落書き.gif
> Checking local filename... File exists: D:\pixiv\クール教信者 (463912)\33997065\_p0 - ドラクエ７落書き.gif
> 
> Image URL : https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p1.gif
> Filename  : D:\pixiv\クール教信者 (463912)\33997065\_p1 - ドラクエ７落書き.gif
> Checking local filename... File exists: D:\pixiv\クール教信者 (463912)\33997065\_p1 - ドラクエ７落書き.gif
> 
> Image URL : https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p2.gif
> Filename  : D:\pixiv\クール教信者 (463912)\33997065\_p2 - ドラクエ７落書き.gif
> Checking local filename... File exists: D:\pixiv\クール教信者 (463912)\33997065\_p2 - ドラクエ７落書き.gif
> 
> Image URL : https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p3.gif
> Filename  : D:\pixiv\クール教信者 (463912)\33997065\_p3 - ドラクエ７落書き.gif
> Checking local filename... File exists: D:\pixiv\クール教信者 (463912)\33997065\_p3 - ドラクエ７落書き.gif
> 
> Image URL : https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p4.gif
> Filename  : D:\pixiv\クール教信者 (463912)\33997065\_p4 - ドラクエ７落書き.gif
> Checking local filename... File exists: D:\pixiv\クール教信者 (463912)\33997065\_p4 - ドラクエ７落書き.gif
> 
> Image URL : https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p5.gif
> Filename  : D:\pixiv\クール教信者 (463912)\33997065\_p5 - ドラクエ７落書き.gif
> Checking local filename... Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=33997065
> [||||||||||||||||||||] 9.74 KiB of 9.74 KiB
>  Completed in 0.001s (9.51 MiB/s)
>  Image invalid, deleting...
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 227, in download_image
>   File "PIL\ImageFile.pyc", line 206, in load
> ValueError: tile cannot extend outside image
> Error at download_image(): (<type 'exceptions.ValueError'>, ValueError('tile cannot extend outside image',), <traceback object at 0x06880EB8>) at https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p5.gif (9000)
> Retrying [1]...
> 1 2 3 4
> Checking local filename... Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=33997065
> [||||||||||||||||||||] 9.74 KiB of 9.74 KiB
>  Completed in 0.001s (9.51 MiB/s)
>  Image invalid, deleting...
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 227, in download_image
>   File "PIL\ImageFile.pyc", line 206, in load
> ValueError: tile cannot extend outside image
> Error at download_image(): (<type 'exceptions.ValueError'>, ValueError('tile cannot extend outside image',), <traceback object at 0x068D8878>) at https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p5.gif (9000)
> Retrying [2]...
> 1 2 3 4
> Checking local filename... Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=33997065
> [||||||||||||||||||||] 9.74 KiB of 9.74 KiB
>  Completed in 0.001s (9.51 MiB/s)
>  Image invalid, deleting...
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 227, in download_image
>   File "PIL\ImageFile.pyc", line 206, in load
> ValueError: tile cannot extend outside image
> Error at download_image(): (<type 'exceptions.ValueError'>, ValueError('tile cannot extend outside image',), <traceback object at 0x06880EB8>) at https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p5.gif (9000)
> Retrying [3]...
> 1 2 3 4
> Checking local filename... Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=33997065
> [||||||||||||||||||||] 9.74 KiB of 9.74 KiB
>  Completed in 0.001s (9.51 MiB/s)
>  Image invalid, deleting...
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 227, in download_image
>   File "PIL\ImageFile.pyc", line 206, in load
> ValueError: tile cannot extend outside image
> Error at download_image(): (<type 'exceptions.ValueError'>, ValueError('tile cannot extend outside image',), <traceback object at 0x0687A508>) at https://i.pximg.net/img-original/img/2013/03/04/20/52/21/33997065_p5.gif (9000)
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 738, in process_image
>   File "PixivUtil2.py", line 227, in download_image
>   File "PIL\ImageFile.pyc", line 206, in load
> ValueError: tile cannot extend outside image
> Error at process_image(): (<type 'exceptions.ValueError'>, ValueError('tile cannot extend outside image',), <traceback object at 0x06152A30>)

**Comment by Evaia** [comment]
Correction: issue also present in 20171226

**Comment by Nandaka** [comment]
set ```verifyimage = False``` in config.ini

**Comment by Evaia** [comment]
That does allow it to progress as a workaround to the corrupt image. Thank you.

Is that the intended behavior to break the download operation when it encounters a single broken image during verification?

**Comment by Nandaka** [comment]
well, the assumption is more on corrupted download, rather than they purposely/unknowingly upload broke image in the first place.
