### ISSUE TITLE
Tags are too long for directory

### ISSUE THREAD

**Issue by LieXXX** [Nandaka/PixivUtil2#307]
Is there a setting that allows files with way too long tags to be downloaded as folder names? 

Specifically this post has very long tags and causes the downloader to error out.

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=30575441

**Comment by Nandaka** [comment]
Weird, it should cut the filename to 250
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L108

can you upload the log file?

**Comment by LieXXX** [comment]
I will get you the logs for this one and the other error as soon as I can. I have been downloading a lot and it generates a lot of log files.

**Comment by Nandaka** [comment]
you can delete/backup the old log file and rerun the download, then upload that one.

**Comment by LieXXX** [comment]
I have too many random files i my directory to know which file is the correct log file. (Accidentally got it to 150k files in the main folder)

However, I got around to trying it again, and it is working now... Which is annoying when trying to fix it.

When it worked I tried option 2, which was download by image_id.

I will see if I can find the specific log for this. Right now it is not giving an error.

**Comment by LieXXX** [comment]
It looks like I do not have the log file for that error. Are the logs only daily or do all logs get saved?

**Comment by Nandaka** [comment]
It is logged into single file, and will be rotated after reach 10MB.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivConstant.py#L23

**Comment by LieXXX** [comment]
I do not have the log with that error anymore and for some reason I cannot reproduce it.

I actually do have one other thing I can try to reproduce the error. I will see if I can.
