### ISSUE TITLE
Ability to make custom tag.txt files

### ISSUE THREAD

**Issue by LieXXX** [Nandaka/PixivUtil2#308]
I think it would be helpful if we had the ability to make custom tag.txt files. I specifically import these files into Hydrus and being able to customize the tag.txt file to fit what it needs would be great. Also the ability to change the name of the text file to include the file type within the file name.

An example would be the ability to tell it how to display the tags in the file and how they are separated. A way to make it look like something like the attached file. 
[27818816.png.txt](https://github.com/Nandaka/PixivUtil2/files/1663221/27818816.png.txt)

**Comment by Nandaka** [comment]
Will not do, open to pull request
