### ISSUE TITLE
[Enhancement]only show download progress , suppress other print

### ISSUE THREAD

**Issue by eromoe** [Nandaka/PixivUtil2#311]
I mean , it usually no need to show a lot of 
```
page xxx
Already downloaded
Downloading xxx
```
to user.

It is more intuitional that only show 
```
Downloading artist  45/235 (current/total)
Downloading  img 12/2000 from artist xxx
```

I think this would be more beautiful.

**Comment by NHOrus** [comment]
That's option, and I like verbose output, it helps dealing with probable bugs.

**Comment by eromoe** [comment]
Yeah, that's why I indicate "to user" . 
Though there is `logLevel` in config.ini,  which only controls the output log to file .

**Comment by Nandaka** [comment]
will not do.
