### ISSUE TITLE
[Enhancement]alwaysCheckFileSize&checkUpdatedLimit

### ISSUE THREAD

**Issue by soli18** [Nandaka/PixivUtil2#312]
Could you implement an option to let those 2 options work together because as of now `alwaysCheckFileSize` is not compatible with `checkUpdatedLimit`

If I delete the latest downloaded picture from an album for example  and run it again with only `checkUpdatedLimit` set to True, it won't grab the picture again and download it. But if you set `alwaysCheckFileSize` to True and `checkUpdatedLimit` to false, it will grab and redownload the latest picture but also check all the other pictures which can take quite a while.

Thanks in advance

**Comment by Nandaka** [comment]
`checkupdatedlimit` is supposed to be integer in value.

Current logic will only check `checkUpdatedLimit` if overwrite is disabled.

https://github.com/Nandaka/PixivUtil2/blob/9f2cfd7fd4368dac10910315ddc94c9082e72e76/PixivUtil2.py#L457
https://github.com/Nandaka/PixivUtil2/blob/9f2cfd7fd4368dac10910315ddc94c9082e72e76/PixivUtil2.py#L1971

need to know how to rearrange the checking/priority if ovewrite/checkUpdatedLimit/alwaysCheckFileSize are enabled/disabled.
