### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by Fanservicefan** [Nandaka/PixivUtil2#315]
Traceback (most recent call last):
  File "PixivUtil2.py", line 721, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found
Error at process_image(): (<type 'exceptions.TypeError'>, TypeError('coercing to
 Unicode: need string or buffer, NoneType found',), <traceback object at 0x03F03
760>)
Dumping html to: Error medium page for image 67354647.html
Error at process_new_illust_from_bookmark(): (<type 'exceptions.TypeError'>, Typ
eError('coercing to Unicode: need string or buffer, NoneType found',), <tracebac
k object at 0x03F03BE8>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1967, in main
  File "PixivUtil2.py", line 1755, in main_loop
  File "PixivUtil2.py", line 1622, in menu_download_new_illust_from_bookmark
  File "PixivUtil2.py", line 1142, in process_new_illust_from_bookmark
  File "PixivUtil2.py", line 721, in process_image
  File "PixivHelper.pyc", line 149, in makeFilename
TypeError: coercing to Unicode: need string or buffer, NoneType found

I don't understand. Before, I was on the December 26th 2017 update and fresh from nowhere, this happened when it was working perfectly a couple of days ago. I moved to the latest version, same problem. What went wrong?!

**Comment by Nandaka** [comment]
most likely something changed on their server, will look into it.

**Comment by Fanservicefan** [comment]
It'll cut majorly into my weekly bookmark roundup, but I'll keep watch for any updates.

**Comment by kingalexeon** [comment]
Yeah just had that problem pop up too guess I'll watch for updates too

**Comment by jrdp18** [comment]
Same.

**Comment by nekoalliancedesign** [comment]
Same here, i''ll keep watch for any updates

**Comment by Phenrei** [comment]
Slightly cleaner solution to this: Replace line 122 with
tab_feeds = page.findAll(href = re.compile('\/stacc\/[^\/\?]*$'))

The only instances of "/stacc/" are currently links like the following:

<a href="/stacc/my/setting" class="item">Auto Feed activity</a>

<a href="/stacc/?mode=unify" class=" js-click-trackable-later" data-click-category="header-menu-ref" data-click-action="stacc" data-click-label="/member_illust.php"<span class="menu-icon icon-feed"></span>Feed</a>

<a href="/stacc/[ARTIST NAME HERE]">Feed</a>

and the regex in question finds only the links with stacc in the href with the correct formatting.

Entire solution relies only on existing findAll code, no extra loops.

Note: Initially left this in a comment on the commit that I deleted, as my regex was incomplete. This version correctly handles all possible username token characters except clearly illegal ones.

**Comment by Nandaka** [comment]
I think I can use that, maybe I can add new unittest just in case pixic changes the layout again and for whatever reason it contains multiple valid stacc references.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20180219-beta1

**Comment by jrdp18** [comment]
Works for me
