### ISSUE TITLE
Error when %artist% contains a period.

### ISSUE THREAD

**Issue by HellcatAisha** [Nandaka/PixivUtil2#317]
A period (.) in %artist% seems to crash the script. I'm not sure if that's actually the cause or not, but removing %artist% from filenameformat and filenamemangaformat seemed to do the trick.

A few pictures seem to get saved to the script's root directory instead of to where they are supposed to go, but eventually the script ends up killing itself before iterating through the artist's gallery.

PixivUtil2 Version: v20180219-beta1

Artist ID: 330401 (A bit NSFW)

Sample error:

```#1
Processing Image Id: 66006128
Title: ボーグちゃん 
Tags : ゲーム, アズールレーン, ボーグ, ボーグ(アズールレーン), スパッツ, アズールレーン1000users入り, ノーブラ, スパッツレーン 
Date : 2017-11-23 09:22:00 
Mode : bigNew
Image URL : https://i.pximg.net/img-original/img/2017/11/23/09/22/18/66006128_p0.jpg
Filename  : /mnt/Images/Artists/Pixiv/(330401) AT2./66006128_p0 - ボーグちゃん.jpg 
Checking local filename... Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=66006128 
Error at download_image(): Cannot save https://i.pximg.net/img-original/img/2017/11/23/09/22/18/66006128_p0.jpg to /mnt/Images/Artists/Pixiv/(330401) AT2./66006128_p0 - ボーグちゃん.jpg: (<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x7f7e89670cf8>) 
File is saved to 66006128_p0.jpg 
[||||||||||||||||||||] 1.63 MiB of 1.63 MiB                                     
 Completed in 2.018978s (824.73 KiB/s)
 done. 
Traceback (most recent call last):
  File "PixivUtil2.py", line 741, in process_image
    os.utime(filename, (ts, ts))
OSError: [Errno 2] No such file or directory: '/mnt/Images/Artists/Pixiv/(330401) AT2./66006128_p0 - \xe3\x83\x9c\xe3\x83\xbc\xe3\x82\xb0\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93.jpg'
Error at process_image(): (<type 'exceptions.OSError'>, OSError(2, 'No such file or directory'), <traceback object at 0x7f7e89674758>) 
Dumping html to: Error medium page for image 66006128.html 
Stuff happened, trying again after 2 second ( 1 )
Traceback (most recent call last):
  File "PixivUtil2.py", line 491, in process_member
    result = process_image(artist, image_id, user_dir, bookmark, title_prefix=title_prefix)  # Yavos added dir-argument to pass
  File "PixivUtil2.py", line 741, in process_image
    os.utime(filename, (ts, ts))
OSError: [Errno 2] No such file or directory: '/mnt/Images/Artists/Pixiv/(330401) AT2./66006128_p0 - \xe3\x83\x9c\xe3\x83\xbc\xe3\x82\xb0\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93.jpg'
```

**Comment by Nandaka** [comment]
I'm using Windows, so the last `.` will be removed.

Can you create a folder ended with '.' in linux?

**Comment by with0out** [comment]
Yes you can create a folder like `test.` in linux.

**Comment by Nandaka** [comment]
Can you run this in the python console?

Ref: https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L565

``` python
import os
import sys

url = 'https://i.pximg.net/img-original/img/2017/11/23/09/22/18/66006128_p0.jpg'
filename = u"/mnt/Images/Artists/Pixiv/(330401) AT2./66006128_p0 - ボーグちゃん.jpg"

# try to save to the given filename + .pixiv extension if possible
try:
    directory = os.path.dirname(filename)
    if not os.path.exists(directory):
        print 'info', u'Creating directory: ' + directory
        os.makedirs(directory)
    save = file(filename + u'.pixiv', 'wb+', 4096)
except IOError:
    print 'error', u"Error at download_image(): Cannot save {0} to {1}: {2}".format(url, filename, sys.exc_info())
```

**Comment by HellcatAisha** [comment]
That test script works and fails. When it works, it creates 66006128_p0 - ボーグちゃん.jpg.pixiv in "*/Images/Artists/Pixiv/(330401) AT2./".

My Images directory is actually a Samba network share, so that I can access it from all of the computers on my LAN. When I do my usual Pixiv scrape, PixivUtil is run on a computer that has this directory mounted as a network share.

I played around with the test script, and here is what I found.

1) If I run it from a remote computer like how I usually run PixivUtil, it fails and returns the error below.

```
info Creating directory: /mnt/Images/Artists/Pixiv/(330401) AT2.
error Error at download_image(): Cannot save https://i.pximg.net/img-original/img/2017/11/23/09/22/18/66006128_p0.jpg to /mnt/Images/Artists/Pixiv/(330401) AT2./66006128_p0 - ボーグちゃん.jpg: (<type 'exceptions.IOERror'>, IOError(2, 'No such file or directory'), <traceback object at 0x7efe7cebc710>)
```
2) If I remove the period from the filename, **or** change the filename to point to a local path, the test script passes.

3) If I run the test script on the Samba server itself, it passes.

So, my best guess is that there's something about there being a period in %artist% that causes Samba to flip out. It's funny that something as innocuous as a period does this but it can handle Japanese and esoteric characters like ♥ just fine.

So yeah, I'm going to have to look to see if there's a Samba option that will fix this. It doesn't seem to be a problem with PixivUtil, but thank you for taking an interest and I apologize if you spent too much time looking into it.

**Comment by whinette** [comment]
I also use a smb share, but I run the scripts from linux subsystem and it does work as expected:

```Page  1
Member Url: https://www.pixiv.net/member_illust.php?id=330401&p=1
Member Name  : AT2.
Member Avatar: https://i.pximg.net/user-profile/img/2016/08/25/10/12/14/11404081_410d964d60abc81d7cebdd586454e54d_170.png
Member Token : zaoc0098
Start downloading... Using Referer: https://www.pixiv.net/
Creating directory: /mnt/z/Pixiv/330401 zaoc0098
[||||||||||||||||||||] 54.07 KiB of 54.07 KiB
 Completed in 0.257513s (209.97 KiB/s)
 done.
#1
Processing Image Id: 66006128
Title: ボーグちゃん
Tags : ゲーム, アズールレーン, ボーグ, ボーグ(アズールレーン), スパッツ, アズールレーン1000users入り, ノーブラ, スパッツレーン
Date : 2017-11-23 09:22:00
Mode : bigNew
Image URL : https://i.pximg.net/img-original/img/2017/11/23/09/22/18/66006128_p0.jpg
Filename  : /mnt/z/Pixiv/330401 zaoc0098/AT2./66006128_p0 - ボーグちゃん.jpg
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=66006128
Creating directory: /mnt/z/Pixiv/330401 zaoc0098/AT2.
[||||||||||||||||||||] 1.63 MiB of 1.63 MiB
 Completed in 2.657324s (626.61 KiB/s)
 done.```

**Comment by Nandaka** [comment]
Folder ended with period is illegal in Windows, so when I run it on Windows, python os.makedirs() will automatically remove the period. 

I suspect because you run it from linux os, it will not do it for you, but will fail anyway is the samba server didn't do something to the period?
