### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer. NoneType found

### ISSUE THREAD

**Issue by chaosrealm93** [Nandaka/PixivUtil2#319]
this error started popping up just today.  it pops up regardless of what im trying to download (image stacks).  it always gets to the last picture in the stack and gives this error

i tried downloading the latest version of pixivdownloader (20180218, i was on 20180118), but it didnt fix the problem

any help is appreciated !

![untitled](https://user-images.githubusercontent.com/31945748/36393326-101814a6-157d-11e8-953c-d2e71f3ccc65.png)

**Comment by NHOrus** [comment]
Look at fresh release. v20180219-beta1 Fixed just seven hours before.

**Comment by chaosrealm93** [comment]
noiceee

will give it a try

i usually dont download beta releases because well......... theyre beta lol

**Comment by chaosrealm93** [comment]
*update

bingooo~
whatever was in the beta fixed the problem!

thanks !
