### ISSUE TITLE
Ugorias causing an issue..?

### ISSUE THREAD

**Issue by Gandeloft** [Nandaka/PixivUtil2#320]
The moment the program comes across an ugoira to process, it fails somehow to finish the process, and ends up skipping the whole remainder of the artist's works.
My verification was checking several artists whose galleries I've begun downloading tonight, and seeing how the last files in each one of them are the in to gif converted ugoira, and the ugoira (which should've been deleted duo to the setting in place).

These are my settings:
[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
userobots = True
timeout = 60
retry = 3
retrywait = 5
downloaddelay = 2

[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = False

[IrfanView]
irfanviewpath = C:\Program Files\IrfanView
startirfanview = False
startirfanslide = False
createdownloadlists = False

[Settings]
filenameformat = %member_id%/%urlFilename%
filenamemangaformat = %member_id%/%urlFilename%
filenameinfoformat = %member_id%/%urlFilename%
avatarnameformat = 
downloadlistdirectory = .
uselist = False
processfromdb = True
overwrite = False
tagsseparator = ,
daylastupdated = 7
rootdirectory = .
alwayscheckfilesize = False
checkupdatedlimit = 0
downloadavatar = True
createmangadir = False
usetagsasdir = False
useblacklisttags = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = False
writeimagejson = False
datediff = 0
backupoldfile = False
writeugoirainfo = False
createugoira = True
deletezipfile = True
enableinfiniteloop = False
verifyimage = False
writeurlindescription = False
urlblacklistregex = 
urldumpfilename = url_list_%Y%m%d
dbpath = 
creategif = True
useblacklistmembers = False
createapng = False
deleteugoira = true

[Authentication]
username = <3
password = <3
cookie = <3
keepsignedin = 1

[Pixiv]
numberofpage = 0
r18mode = False
dateformat = 

" ...
Remote filesize = 18.14 MiB (19021914 Bytes)
        File exist! (Identical Size)
Traceback (most recent call last):
  File "PixivUtil2.py", line 741, in process_image
WindowsError: [Error 2] The system cannot find the file specified: u'D:\\pixivutil20180219-beta1\\13895186\\67365051_ugoira1920x1080.zip'
Error at process_image(): (<type 'exceptions.WindowsError'>, WindowsError(2, 'The system cannot find the file specified'), <traceback object at 0x061C90D0>)
Dumping html to: Error medium page for image 67365051.html
Giving up image_id: 67365051
Processing Member Id: 8237910
..."

**Comment by whinette** [comment]
This is fixed with the latest master :)
https://github.com/Nandaka/PixivUtil2/issues/318

**Comment by Gandeloft** [comment]
I'm sorry if I've indeed opened up a supposed new issue thread simply because of my own oversight. I think I've, just tonight, downloaded the freshest version there is.. But obviously, I should be mistaken.. I'm going to verify that now.

**Comment by Gandeloft** [comment]
I haven't figured out how to implement the fix..
