### ISSUE TITLE
Download images per image_id from list

### ISSUE THREAD

**Issue by MasterKosa** [Nandaka/PixivUtil2#321]
Hi
Is it possible to add feature/ability to download images by image_id from list? Like it is for member_id.
Thanks
JK

**Comment by Nandaka** [comment]
no image list freature, but you can run it from console using this command:

`PixivUtil2.exe -x -s 2 <imageid1> <imageid2> ... `

refer to readme for more details.

**Comment by MasterKosa** [comment]
Thanks for reply. I know about this option but it's not what I mean, now I
have to map PATH for PixivUtil2.exe, create and modify bat file every time
I want to use it. Sorry but opening 10 instances and pasting it directly
into them is much less hassle.
