### ISSUE TITLE
Expand to work with Deviantart? 

### ISSUE THREAD

**Issue by animeai** [Nandaka/PixivUtil2#323]
I love this tool and just rediscovered it after losing it during a format a few years ago and totally forgetting about it. I would love to have a similar tool to work with the English rival to Pixiv, Deviantart. Do you think this is something that would ever be on the roadmap for this project?

**Comment by Nandaka** [comment]
Unlikely, but you can use https://github.com/voyageur/dagr to download images from deviantArt.

Doing quick search on google, looks like there are others application that allows you to download images from DeviantArt.
