### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by bluerthanever** [Nandaka/PixivUtil2#324]
Hey, dear Nandaka san.
I'm getting this error lately:
Please check. Thank you very much.

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/1754303/pixivutil.log)

**Comment by Nandaka** [comment]
see #319 

Try the latest beta.

**Comment by bluerthanever** [comment]
ok. thanks for your reply!
