### ISSUE TITLE
use python3 print format

### ISSUE THREAD

**Issue by rachmadaniHaryono** [Nandaka/PixivUtil2#325]
hi, i'm trying to fork the program to python3.

download a single image was actually successful till this commit https://github.com/rachmadaniHaryono/PixivUtil2/commit/edcf06f301674f69799ac7f61d2705a782335e26

but with new update it is currently hard to track the change as the `print` is still mostly use python2 format

so i recommend `print` should be used as following

```python
# OLD
print 'Some text'
# NEW
print('Some text')
```
and `print` with trailing comma
```python
#OLD
print 'Some text',
#NEW
print('Some text', end='')
```
if you are okay with this, i can even create pr which consist only change for this

related #190

**Comment by Nandaka** [comment]
Any impact with the old 2.7x version? Looks like print and print() has different behaviour, especially handling unicode string.
Also, please note that python2.7 has different handling if you pass more than one parameter.
See below
```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print "hello", "world"
hello world
>>> print("hello", "world")
('hello', 'world')
>>>
```

**Comment by rachmadaniHaryono** [comment]
not quite sure why the newest commit is not registered on pr, but here is the fix

https://github.com/rachmadaniHaryono/PixivUtil2/commit/881b85e54a54cf2109b2d5a40eee823bf96b8fca

**Comment by rachmadaniHaryono** [comment]
result 

```python
Python 2.7.14 (default, Sep 23 2017, 22:06:14)                                      
[GCC 7.2.0] on linux2                     
Type "help", "copyright", "credits" or "license" for more information.              
>>> print "hello", "world"                
hello world                               
>>> print("hello", "world")               
('hello', 'world')                        
>>> from __future__ import print_function 
>>> print("hello", "world")                                                                                                                                             
hello world
```

**Comment by rachmadaniHaryono** [comment]
another test for print for trailing comma and future lib

```python
#Python 2.7.14 (default, Sep 23 2017, 22:06:14)
>>> print 'hello',
hello
>>> print('hello',)
('hello',)
>>> from __future__ import print_function
>>> print('hello',)
hello
>>>

#Python 3.6.3 (default, Oct  3 2017, 21:45:48)
>>> print('hello',)
hello

>>> print('hello', end='')
hello
>>>
```

here python2 and python3 have difference output for ```>>> print('hello',)```.
