### ISSUE TITLE
Error at process_image, related to member_token

### ISSUE THREAD

**Issue by hm8940** [Nandaka/PixivUtil2#327]
Processing Image Id: 67445994
Title: 初投稿 
Tags : オリジナル, 中性的, 筆ペン 
Date : 2018-02-24 22:29:00 
Mode : bigNew
Image URL : https://i.pximg.net/img-original/img/2018/02/24/22/29/39/67445994_p0.jpg
Traceback (most recent call last):
  File "PixivUtil2.py", line 674, in process_image
    filename = PixivHelper.makeFilename(filename_format, image, tagsSeparator=__config__.tagsSeparator, tagsLimit=__config__.tagsLimit, fileUrl=url, bookmark=bookmark, searchTags=search_tags)
  File "/home/user/Documents/PixivUtil2-master/PixivHelper.py", line 149, in makeFilename
    nameFormat = nameFormat.replace('%member_token%', artistInfo.artistToken)
TypeError: coercing to Unicode: need string or buffer, NoneType found
Error at process_image(): (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x7fc804113b90>) 
Dumping html to: Error medium page for image 67445994.html 
Traceback (most recent call last):
  File "PixivUtil2.py", line 1913, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, mode, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 1684, in main_loop
    menu_download_by_image_id(mode, op_is_valid, args)
  File "PixivUtil2.py", line 1361, in menu_download_by_image_id
    process_image(mode, None, int(image_id))
  File "PixivUtil2.py", line 674, in process_image
    filename = PixivHelper.makeFilename(filename_format, image, tagsSeparator=__config__.tagsSeparator, tagsLimit=__config__.tagsLimit, fileUrl=url, bookmark=bookmark, searchTags=search_tags)
  File "/home/user/Documents/PixivUtil2-master/PixivHelper.py", line 149, in makeFilename
    nameFormat = nameFormat.replace('%member_token%', artistInfo.artistToken)
TypeError: coercing to Unicode: need string or buffer, NoneType found
press enter to exit.

I tried to download some images today(about one and a half week spent from last use, which had worked properly) but faced this error. I just commented out
    **nameFormat = nameFormat.replace('%member_token%', artistInfo.artistToken)** 
part from PixivHelper.py, and than same error occured from 
    **nameFormat.replace('%original_member_token%',imageInfo.originalArtist.artistToken)**
part. So I commented out all codes doing something about member_token(3 lines in total), which finally led my download succeed.

I don't know why such an error occurs suddenly, maybe my python got some problems. However I just wanted to notice you and some other guy who may suffer from similar problem about my experience.

**Comment by NHOrus** [comment]
What version you are on?

**Comment by hm8940** [comment]
It says "PixivDownloader2 version 20171127". I think I should update mine more frequently..

**Comment by NHOrus** [comment]
Yes, it was fixed one beta release ago https://github.com/Nandaka/PixivUtil2/commit/b08b6933cffc15e0efe8e3361d611c85821d0f47

**Comment by hm8940** [comment]
Thank you. UPDATE FIRST WHEN SOMETHING WENT WRONG <- I'll remember.
