### ISSUE TITLE
download a single image from python

### ISSUE THREAD

**Issue by rachmadaniHaryono** [Nandaka/PixivUtil2#329]
can you give example how to download a single image from command prompt.

the best i can do is following

```python
import PixivUtil2
import PixivDBManager
import PixivHelper
import PixivBrowserFactory
try:
    PixivUtil2.__config__.loadConfig(path=PixivUtil2.configfile)
    PixivHelper.setConfig(PixivUtil2.__config__)
except BaseException:
    print('Failed to read configuration.')
    log.exception('Failed to read configuration.')
if PixivUtil2.__br__ is None:
    PixivUtil2.__br__ = PixivBrowserFactory.getBrowser(config=PixivUtil2.__config__)
PixivUtil2.__dbManager__ = PixivDBManager.PixivDBManager(
    target=PixivUtil2.__config__.dbPath, config=PixivUtil2.__config__)
PixivUtil2.__dbManager__.createDatabase()
username = PixivUtil2.__config__.username
password = PixivUtil2.__config__.password
PixivUtil2.doLogin(password, username)
PixivUtil2.start_iv = False
for image_id in image_ids:
    PixivUtil2.process_image(None, int(image_id))
```

what is left

- detect if download is success or not
- get info from download
- move the downloaded image

related branch: https://github.com/rachmadaniHaryono/PixivUtil2/tree/feature/server

related lines: https://github.com/rachmadaniHaryono/PixivUtil2/blob/a78a08b1dd668765cea8da565c591360c1ad8466/pixiv_util2/views.py#L45

**Comment by Nandaka** [comment]
You can check the main logic here:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L592

Assuming you have successfully login, you can get the image information here:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L616

Then depending the image type (manga/big image), you can get the actual url here:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L704

Then assuming you have the url, I just use my own file download here:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L756

**Comment by rachmadaniHaryono** [comment]
permalink for commit 0f3a8d5d8ab44524d3dda3cca18be2bb5a42c11e

- main logic: https://github.com/Nandaka/PixivUtil2/blob/0f3a8d5d8ab44524d3dda3cca18be2bb5a42c11e/PixivUtil2.py#L594
- image information: https://github.com/Nandaka/PixivUtil2/blob/0f3a8d5d8ab44524d3dda3cca18be2bb5a42c11e/PixivUtil2.py#L616
- actual url depending the image type(manga/big image): https://github.com/Nandaka/PixivUtil2/blob/0f3a8d5d8ab44524d3dda3cca18be2bb5a42c11e/PixivUtil2.py#L702
- file download: https://github.com/Nandaka/PixivUtil2/blob/0f3a8d5d8ab44524d3dda3cca18be2bb5a42c11e/PixivUtil2.py#L758
