### ISSUE TITLE
Unicode type error

### ISSUE THREAD

**Issue by username13459** [Nandaka/PixivUtil2#333]
![image](https://user-images.githubusercontent.com/36827093/36830803-2d7356dc-1cf3-11e8-8eb9-4c64c23555e4.png)

The program spits this traceback out any time I try to do anything (after it connects to pixiv for a few seconds).  It started suddenly, and persisted over a new install and a new version.  (With common config files)

**Comment by Nandaka** [comment]
Are you using the latest version? https://github.com/Nandaka/PixivUtil2/releases

**Comment by username13459** [comment]
Yeah, I tried the latest non-beta release

**Comment by Nandaka** [comment]
it is fixed in beta version. Can you try the latest beta?

**Comment by username13459** [comment]
Seems to have cleared everything up
