### ISSUE TITLE
New Version Not Starting

### ISSUE THREAD

**Issue by barkmoney** [Nandaka/PixivUtil2#336]
I'm a pleb and probably don't comprehend exactly what to do here, but the old code never gave me a hard time until the recent unicode error and I don't know why this version wont work for me.
I tried opening PixivUtil2.py from the command window and through python from my Program Files as shown in the first picture and then again from my downloads folder as shown in the second picture. I'm running Windows7. I read the readme and can't find a solution or instructions that help.

![capture](https://user-images.githubusercontent.com/36964956/36858234-d2684028-1d37-11e8-9960-20140c7a1e36.PNG)

![capture2](https://user-images.githubusercontent.com/36964956/36858240-d72e6af6-1d37-11e8-90d6-1ba48793c69e.PNG)

**Comment by Nandaka** [comment]
>> Python 2.7.11++ (http://www.python.org/) <<

**Comment by barkmoney** [comment]
Thank you! I thought the "++" meant 2.7.11 and up and I'd be fine with newer Pythons like 3.6. So I went back and downloaded Python 2.7.11 and tried "py -2.7 PixivUtil2.py" as well as "C:\Python27\python.ex PixivUtil2.py" in the command window and for both I'm getting:

Traceback (most recent call last):
  File "PixivUtil2.py", line 21, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup


I downloaded BeautifulSoup and don't know what to do with it, where to put it, or if it's really even necessary. I started thinking that maybe I should be running PythonUtil2.py directly from the Python 2.7.11 window and not from the command window using py -2.7, but I don't know how to do that or how to even change the path in py, so I'll study python more and reread the readme later tomorrow and try to fix this myself because I really don't want to bother you further with my ignorance, but it's really hard for me. :(

**Comment by Nandaka** [comment]
you can check the wiki page:

Run from source code:

- Download and install latest Python 2.7 from http://www.python.org/
- Download the source code and extract it on some folder (e.g. c:\pixivutil)
- Download the required library: Open cmd window and navigate to where you install the python, and go to the script folder (e.g. C:\Python27\Scripts) run: `pip install -r c:\pixivutil\requirements.txt`

**Comment by barkmoney** [comment]
Wow, That was really easy! Thank you so much, Nandaka!

**Comment by rachmadaniHaryono** [comment]
if possible @barkmoney, would you mind testing the pr #257
