### ISSUE TITLE
Have there been any recent changes to the "file exist" mechanic or is there an issue somewhere?

### ISSUE THREAD

**Issue by ikkion** [Nandaka/PixivUtil2#339]
Hello

I am not an expert but just an user, but I noticed in the last few days that whenever I add a new id and folder to list.txt it keeps constantly rechecking the files in the new folders every time i process the list. Before the behavior was that it would check the first time I added a new id and folder and give me a "file exist" message, the next time it would pass them just as every file that has been downloaded before and registered in the DB as downloaded. 

Suddenly any new folder that I added recently gets rechecked every time I run the list, and I get the "file exists" message every time as well. I do not know how long this has been going on but it is fairly recent. Normally it took about 3.5 to 4 hours the process the list, of course the time gets longer the more ids I add, but suddenly I takes 6 or more hours since the program keeps rechecking the new folders every time. I been adding new ids and folders to the list this way since the beginning and any older stuff I added to the list are being processed normally. I wonder if this new behavior it deliberate and if so is there any setting I have to change to make it behave like before. 

Please note that I have it set to only go back 3 pages when I process the list.txt, any user with more pages I first download completely and then just add them to the list later so it only rechecks 3 pages every time but it still takes along time.

**Comment by Nandaka** [comment]
can you upload your config.ini? also ensure `alwayscheckfilesize = False`

**Comment by ikkion** [comment]
I am at work right now so I do not have access to the config.ini but I am fairly certain I have alwayscheckfilesize = False set. I will upload it as soon as I get home from work.

**Comment by ikkion** [comment]
I will post my config file whitout the login information. As I said before until recently it worked with no issues and only the newly added ids and folder get rechecked:

[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
userobots = True
timeout = 60
retry = 3
retrywait = 5
downloaddelay = 0

[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = False

[IrfanView]
irfanviewpath = C:\Program Files\IrfanView
startirfanview = False
startirfanslide = False
createdownloadlists = False

[Settings]
filenameformat = %urlFilename%
filenamemangaformat = %urlFilename%
filenameinfoformat = %urlFilename% - %title%
avatarnameformat = 
downloadlistdirectory = .
uselist = False
processfromdb = False
overwrite = False
tagsseparator = ,
daylastupdated = 0
rootdirectory = .
alwayscheckfilesize = False
checkupdatedlimit = 0
downloadavatar = False
createmangadir = False
usetagsasdir = False
useblacklisttags = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = False
writeimagejson = False
datediff = 0
backupoldfile = False
writeugoirainfo = False
createugoira = True
deletezipfile = False
enableinfiniteloop = False
verifyimage = False
writeurlindescription = False
urlblacklistregex = 
urldumpfilename = url_list_%Y%m%d
dbpath = 
creategif = False
useblacklistmembers = False
createapng = False
deleteugoira = False
createwebm = False
setlastmodified = True

[Authentication]
username = 
password = 
cookie = 
keepsignedin = 1

[Pixiv]
numberofpage = 3
r18mode = False
dateformat = 

[FFmpeg]
ffmpeg = ffmpeg
ffmpegcodec = libvpx-vp9
ffmpegparam = -lossless 1

**Comment by Nandaka** [comment]
Weird, 

Can you do download by image id twice with the same id? Using your configuration (`overwrite = False`, `alwayscheckfilesize = False`), if it is already in the DB, it should shows:
`Already downloaded: <image_id>` rather than file exists messages.

https://github.com/Nandaka/PixivUtil2/blame/master/PixivUtil2.py#L479

There also another settings `checkupdatedlimit = <number_of_images>` that you can use to automatically move to next member_id after <number_of_images> previously downloaded images.

Unless the DB is corrupted or the member id is missing, then it should not skip the check.
https://github.com/Nandaka/PixivUtil2/blame/master/PixivUtil2.py#L477

**Comment by ikkion** [comment]
Yes I get `Already downloaded: <image_id>` message when I do the first thing. 

It is possible the DB is corrupted. Yesterday I got error messeges when I tried to `Clean Up Database`.

**Comment by ikkion** [comment]
The feeling I am getting is that the problem arises when the file is already there before the program tries to download it the first time. What used to happen is that the program would say the file exists and marks it in the DB as if the program just downloaded it the same way it does when the program actually downloads it. For some reason this is no longer happening. It is only marked as downloaded if it actually downloads it in that session otherwise it's not treated as downloaded and gets again rechecked the next time. That is the impression I get.

**Comment by Nandaka** [comment]
It should insert the image id to to DB if it is new image or duplicated images.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L819
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L134
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L153 (ugoira)
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L174 (others)
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L193 (old filename)

helper also will return OK or DUPLICATE, which will update the DB.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L513

Can you go to the DB Manage (press `d`) and then do Compact DB (press `c`), this will rebuilt the DB (may take times on big DB). Also backup the old db before you do this (copy sqlite.db file to other folder).

**Comment by Nandaka** [comment]
It should be showing like this if you already download the images/members (e.g. using option 1 with `alwayscheckfilesize = False` and `overwrite = False`

```
x. Exit
Input: 1
Member ids: 17775569
Start Page (default=1):
End Page (default=0, 0 for no limit):
Member IDs: [17775569]
Processing Member Id: 17775569
Reading D:\PixivUtil\config.ini ...
done.
Page  1
R-18 Mode only.
Member Url: https://www.pixiv.net/member_illust.php?id=17775569&p=1&tag=R-18
Member Name  : とけとう＠２日目東き13b
Member Avatar: https://i.pximg.net/user-profile/img/2016/12/12/19/35/00/11862754_172d9534226df57b099cbccb0d184e6f_170.png
Member Token : toketou
Checking local filename... File exists: C:\Temp\Pixiv2\17775569 toketou\folder.jpg
#1
Already downloaded: 67528342
#1
Already downloaded: 67242009
#1
Already downloaded: 66469229
#1
Already downloaded: 65579399
...
```

**Comment by ikkion** [comment]
I am aware of this. This is how it works for all the older ids and folders in list.txt, it just does not work for the ones I added recentl, and I added the older ones the same way I addad the recent ones.

**Comment by ikkion** [comment]
IMPORTANT UPDATE

I set up simple test environment using a clean setup with the same config.ini file. The first environment is based on version pixivutil20180227-beta3.

The environment is as follows:

Two folders exist: One is already populated with the correct files and one is empty. I create a new list.txt with the two ids and folders. 

Next I run command 4 and processes the list.txt

First Run:

First id: (prepopulated folder)

The files are checked and “file exists” message is displayed for every file

Second id: (empty folder)

Files are downloaded


Second Run:

First id: (prepopulated folder)

The files are checked again and “file exists” message is displayed for every file

Second id: (empty folder)

Files are skipped with message already downloaded.


Third Run:

First id: (prepopulated folder)

The files are checked again and “file exists” message is displayed for every file

Second id: (empty folder)

Files are skipped with message already downloaded.


In order to double-check this result I set up another test environment this time using version pixivutil20180219-beta1.

The environment is as follows:

Two folders exist: One is already populated with the correct files and one is empty. I create a new list.txt with the two ids and folders.

First Run:

First id: (prepopulated folder)

The files are checked and “file exists” message is displayed for every file

Second id: (empty folder)

Files are downloaded


Second Run:

First id: (prepopulated folder)

Files are skipped with message already downloaded.

Second id: (empty folder)

Files are skipped with message already downloaded.


Third Run:

First id: (prepopulated folder)

Files are skipped with message already downloaded.

Second id: (empty folder)

Files are skipped with message already downloaded.


CONCLUSION OF TEST

It is apparent the logic regarding the handling of existing files has been changed between versions  pixivutil20180219-beta1 and pixivutil20180227-beta3.

I do not know if this has been intentional of an oversight but I would like to know I can set the program to work the same way it was in the earlier version of Pixivutil2.

Also I used “compact database” on my main setup but the error message still appears when I try to use  “clean up database” so my DB still has issues.

As the situation stands now I will probably be forced to revert back to version  pixivutil20180219-beta1 and hope the situation will be resolved somehow in the future.

**Comment by Nandaka** [comment]
Yeah, that's weird. I tried to diff between v20180219-beta1 anc current master, but I don't see any big changes on the file/db handling.

main script
https://github.com/Nandaka/PixivUtil2/compare/v20180219-beta1...master#diff-7a612caa8f02f7c30e49d68a8c1ab43fL791

main download
https://github.com/Nandaka/PixivUtil2/compare/v20180219-beta1...master#diff-7a612caa8f02f7c30e49d68a8c1ab43fL119

helper (no changes)
https://github.com/Nandaka/PixivUtil2/compare/v20180219-beta1...master#diff-0ba8e05dd3dea6faaf75541a3ed46a24L512

as for the DB cleanup, I'll check it later. For now, you can use SQLite Browser (http://sqlitebrowser.org/) and perform `VACUUM` (https://sqlite.org/lang_vacuum.html) to rebuild the db.

Also, using sqlite browser, you can check if the existing file/image_id is in the db or not.

**Comment by Nandaka** [comment]
possibly insert operation failed here:
https://github.com/Nandaka/PixivUtil2/compare/v20180219-beta1...master#diff-7a612caa8f02f7c30e49d68a8c1ab43fL795

**Comment by ikkion** [comment]
Thank you for your response. I will look into SQLite Browser during the weekend when I have more time. Unfortunately I am not a programmer so the code does not tell me much but I am a low level IT technician so I am fairly good at finding problems.

**Comment by Nandaka** [comment]
Try: https://github.com/Nandaka/PixivUtil2/releases/tag/v20180309-beta4

You might need to run in once to update the DB with the image's filename.

**Comment by ikkion** [comment]
Tested it in my test environment and it works.
