### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by nekoalliancedesign** [Nandaka/PixivUtil2#341]
Hello this is the first time i post an error like this. So today i just opened the latest beta ver. And i got like this, "List index out of range" Last week there's no problem but today it is.
![screenshot 1086](https://user-images.githubusercontent.com/36616630/37443735-763b0682-2840-11e8-94a8-6bf3fb7f9f30.png)

**Comment by Nandaka** [comment]
looks like something changes on the server.

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/PixivUtil2/releases/tag/v20180314

**Comment by nekoalliancedesign** [comment]
Thank you so much

**Comment by chaosrealm93** [comment]
are these errors dumped to a file?

i noticed this error just today but is totally possible that it was going on for some time now.  i just entered in the picture id and hit enter and trust the program downloaded it properly....

**Comment by Nandaka** [comment]
I don't think it was logged, but it only happen 2 days ago.

**Comment by chaosrealm93** [comment]
i already downloaded and started using the latest version.  it seemed to have fixed the problem. i just dont know how much have not been downloaded properly lol

i found a file "db.sqlite" in the folder.  it seems to be a log of what was downloaded regardless of if it was done properly or not.  would this be a good place to start sorting through the picture ids?

**Comment by Nandaka** [comment]
The DB will only record the image id if it successfully downloaded.
