### ISSUE TITLE
UnicodeDecodeError "utf8" codec isn't decode byte 0xbl in position 24: invailid star byte

### ISSUE THREAD

**Issue by go08919** [Nandaka/PixivUtil2#342]
can't open pixivutil cause error occurred

================================================
Traceback (most recent call last):
  File "PixivConfig.pyc", line 116, in loadConfig
  File "PixivHelper.pyc", line 312, in OpenTextFile
  File "codecs.pyc", line 896, in open
UnicodeDecodeError "utf8" codec isn't decode byte 0xbl in position 24: invailid star byte
================================================

then window close

any other version(including 0314 version) was not opened
what should i do

**Comment by NHOrus** [comment]
Write the answers to the questions asked in the template. They were put for a cause.
What version of PixivUtil2 do you use?

**Comment by Nandaka** [comment]
Try to backup/delete the old config file and rerun the application?
