### ISSUE TITLE
Tags on Pixiv not being recognized (v20180314 White Day)

### ISSUE THREAD

**Issue by lulzkillergithub** [Nandaka/PixivUtil2#343]
Using version v20180314 White Day

I noticed an awful amount of images downloaded that should be blacklisted. I checked the images that I didn't want had the blacklisted tags. I also remember checking from my last download that I had blacklisted tags loaded.

Regardless, I re-started the client, verified that the 78 blacklisted tags were read by the program. I then deleted an imageid via database management, and attempted to redownload it.

The image was able to successfully download. The only tag noticed by PixivUtil2 was "R-18" despite there being 10 tags, at least one of which I have blacklisted.

The image in question (amongst many others) is definitely R-18 but can be found at 66956825. The tag blacklisted was ふたなり, but the issue seems to be PixivUtil2 didn't read any tag past "R-18".

**Comment by Nandaka** [comment]
Well, they changed the layout again....

**Comment by Nandaka** [comment]
welp some changes again, I think I will wait for 1 day until it stabilize.

**Comment by NHOrus** [comment]
Does this mean that this works if one does not use tags?

**Comment by Nandaka** [comment]
it still works, just some tag without translation will be parsed when reading the image info. Searching by tags still works.
![image](https://user-images.githubusercontent.com/836867/37527538-7ad2e700-28ef-11e8-8902-a329f81aad7b.png)

**Comment by lulzkillergithub** [comment]
This seems to be fixed (for now, hah). Successfully ignored my blacklisted tags.
