### ISSUE TITLE
change a way to check download oldest to newest

### ISSUE THREAD

**Issue by fookbuck** [Nandaka/PixivUtil2#351]
Hi

Could you made it check files from newest to oldest when do download by member or list?
Sometime I dont want to wasting time for checking from oldest and keep showing downloaded until do download newest one.

If I enable "checkupdatedlimit" at very low, it should skipped to next member without download the the newest one?

**Comment by Nandaka** [comment]
`checkUpdatedLimit` will allow you to set the number of images that already downloaded before it moves to the next member, setting it to 0 will disable this feature (e.g. it will check all available images). 
> you made it check files from newest to oldest when do download by member or list?

It is checking by newest images first. It will iterate from the 1st page (newest works) to the last page.
I don't think they changed the work ordering, right? Newest work always shown first in the website.
