### ISSUE TITLE
wont let me download by tag

### ISSUE THREAD

**Issue by shanedragonsteel** [Nandaka/PixivUtil2#353]
https://puu.sh/A4Tuq.png

i used the same tag i used to find the images that works in the browser no clue why it wont download , can i get some help

**Comment by Nandaka** [comment]
Try latest releases? https://github.com/Nandaka/PixivUtil2/releases

**Comment by shanedragonsteel** [comment]
yes that seems to have worked thats , didnt know i wasnt using the latest update sense it said on the startup last update 7 days ago , i was using pixivutil20170705
