### ISSUE TITLE
locking danbooru

### ISSUE THREAD

**Issue by EvangaL** [Nandaka/PixivUtil2#354]
Hello, I have such a problem, we are banned from danbooru in Russia because of this, that I would not do there is no connection to the server, how can I fix this?
Can use the browser with vpn.
Because leasing a proxy for a few dollars a month is not profitable for me. I've done it twice in 3 months by downloading artworks.

https://pp.userapi.com/c846417/v846417291/26e3b/Ho_mvvw1ByE.jpg
https://pp.userapi.com/c846417/v846417291/26e32/E97k2Ob3yDg.jpg

**Comment by Nandaka** [comment]
wrong issue tracker, use https://github.com/Nandaka/DanbooruDownloader/issues
