### ISSUE TITLE
Function 8 doesn't work on MyPixiv.

### ISSUE THREAD

**Issue by Fanservicefan** [Nandaka/PixivUtil2#356]
An artist I follow only makes some stuff available to those that he added to his MyPixiv, however that works. I ask, he accepts, and a bunch of pics are now accessible. A week later I batch download a bunch of recent works...and his stuff doesn't show up in the proper folder. Or any folder.

Now it DOES work if I use function 1 and download his entire gallery. It skips the stuff I already have and gets the other pics that function 8 missed. Is this intentional? Rather inconvenient.

**Comment by Nandaka** [comment]
Is the works visible in ```https://www.pixiv.net/bookmark_new_illust.php```? 

The application depends on that to resolve the new images from bookmarked user. No filtering is applied.
See: https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1157
