### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by tedechan** [Nandaka/PixivUtil2#358]
### Description

Pixiv maybe has been changed their code layout, and now utility can`t download images, and arguing about 'Attribute error'.

### Steps to Reproduce

1. Setup login and password in 'config.ini', or via utility.
2. Select the 6-th option to download from bookmarks.
3. Input parameters to not download private bookmarks.

**Expected behavior:** [What you expected to happen]

I was expected that it will be download images from my bookmarks.

**Actual behavior:** [What actually happened]

It`s arguing that it can`t find specific attribute ~'findAll'.

### Versions

20170619-beta4 and 20180414

### Log and dumps
[report.zip](https://github.com/Nandaka/PixivUtil2/files/1964263/report.zip)

**Comment by Nandaka** [comment]
check the beta version: https://github.com/Nandaka/PixivUtil2/releases/tag/v20180426-beta1
