### ISSUE TITLE
"list index out of range" error

### ISSUE THREAD

**Issue by crockpoot** [Nandaka/PixivUtil2#359]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Ever since March 21, 2018, all my attempts to download using member IDs has given me an error along the lines of:
"#XX
Processing Image ID: XXXXXXXX
Image ID (XXXXXXXX): list index out of range
wait for X.XXs"
(where X is an arbitrary number used for this example)
and the result has been a folder named after the user's name (and ID) and an empty folder except for their avatar as the only image. 

### Steps to Reproduce

1. Press "1" key for member ID
2. Right-click, select "Paste" to paste copied ID
3. Press "Enter" twice to select default settings for the next 2 options

**Expected behavior:** Images and animations download their respective folder

**Actual behavior:** What I wrote above

### Versions

Version 20180219

**Comment by crockpoot** [comment]
Looks something like this:
> Member IDs: [933885]
> Processing Member Id: 933885
> Reading F:\pixiv\config.ini ...
> done.
> Page  1
> Member Url: https://www.pixiv.net/member_illust.php?id=933885&p=1
> Member Name  : シグナル・グリーン
> Member Avatar: https://s.pximg.net/common/images/no_profile.png
> Member Token : signal-green
> #1
> Processing Image Id: 60843389
> Image ID (60843389): list index out of range
> Wait for 0.459s
> #2
> Processing Image Id: 58071108
> Image ID (58071108): list index out of range
> Wait for 1.36s
> #3
> Processing Image Id: 57370331
> Image ID (57370331): list index out of range
> Wait for 0.347s
> #4
> Processing Image Id: 57329226
> Image ID (57329226): list index out of range
> Wait for 0.541s
> ....

**Comment by NHOrus** [comment]
As current release is 20180503-beta2, have you tried updating?

**Comment by crockpoot** [comment]
I'll try that now; I thought I had the most recent version a moment ago.
