### ISSUE TITLE
Function 11 doesn't work

### ISSUE THREAD

**Issue by Skenomo** [Nandaka/PixivUtil2#360]
Function 11 doesn't work

* [y] Did you read FAQ section?
* [PixivDownloader2 version 20180503-beta2] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
Input: 11
Member id: 12583903

> #1
Processing Image Id: 67965929
Image ID (67965929):
Stack Trace: (<type 'exceptions.NotImplementedError'>, NotImplementedError(), <t
raceback object at 0x03FA1FA8>)
Wait for 0.484s
#2
Processing Image Id: 67548605
Image ID (67548605):
Stack Trace: (<type 'exceptions.NotImplementedError'>, NotImplementedError(), <t
raceback object at 0x03FAA9B8>)
Wait for 1.81s
#3
Processing Image Id: 67317757
Image ID (67317757):
Stack Trace: (<type 'exceptions.NotImplementedError'>, NotImplementedError(), <t
raceback object at 0x03FB1E90>)
Wait for 0.158s

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20180511-beta3
