### ISSUE TITLE
new file name when a file w/ same name exist

### ISSUE THREAD

**Issue by arts1983** [Nandaka/PixivUtil2#361]
When I download a image with the same name of a existing file, it create only a new file of the image and not a new info file.

**Comment by Nandaka** [comment]
can you give more information (e.g. logging/config)? by right, it should overwrite the old info file.

**Comment by arts1983** [comment]
Sorry, maybe I didn't explain myself well. I meant that if I download two or more images with the same name, I obtain two or more images with different names, but only one info file.

The version is the last, pixivutil20180503-beta2.

config.ini
[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
userobots = True
timeout = 60
retry = 3
retrywait = 5
downloaddelay = 2

[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = False

[IrfanView]
irfanviewpath = C:\Program Files\IrfanView
startirfanview = False
startirfanslide = False
createdownloadlists = False

[Settings]
filenameformat = %artist% (%member_id%)\%title%
filenamemangaformat = %artist% (%member_id%)\%title% %page_index%
filenameinfoformat = %artist% (%member_id%)\%title%
avatarnameformat = 
downloadlistdirectory = .
uselist = False
processfromdb = True
overwrite = True
tagsseparator = ,
daylastupdated = 7
rootdirectory = .
alwayscheckfilesize = False
checkupdatedlimit = 0
downloadavatar = True
createmangadir = False
usetagsasdir = False
useblacklisttags = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = True
writeimagejson = False
datediff = 0
backupoldfile = True
writeugoirainfo = True
createugoira = True
deletezipfile = False
enableinfiniteloop = False
verifyimage = False
writeurlindescription = False
urlblacklistregex = 
urldumpfilename = url_list_%Y%m%d
dbpath = 
creategif = True
useblacklistmembers = False
createapng = False
deleteugoira = False
createwebm = False
setlastmodified = True

[Pixiv]
numberofpage = 0
r18mode = False
dateformat = 

[FFmpeg]
ffmpeg = ffmpeg
ffmpegcodec = libvpx-vp9
ffmpegparam = -lossless 1

**Comment by Nandaka** [comment]
use `%image_id%` in your filename format. The image info will be always overwritten in case of the same name as the assumption that the same image is being downloaded.

**Comment by arts1983** [comment]
Ok, thank you.
I thought it was weird that in case of two images with the same name I obtain two images and one file info. Sorry
