### ISSUE TITLE
issue: Error at download_image(): (<type 'exceptions.OverflowError'>

### ISSUE THREAD

**Issue by PixivAddict** [Nandaka/PixivUtil2#362]
cannot download image:

Processing Image Id: 65962357
Title: レーシングカー
Tags : GTSports, コルベット, シボレー, クルマ
Date : 2017-11-19 21:01:00
Mode : manga
Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&
Found: https://i.pximg.net/img-original/img/2017/11/19/21/01/21/65962357_p0.jpg
Fetching big image page: https://www.pixiv.net/member_illust.php?mode=manga_big&
Found: https://i.pximg.net/img-original/img/2017/11/19/21/01/21/65962357_p1.jpg
Manga pages parsed.

Page Count : 2
Image URL : https://i.pximg.net/img-original/img/2017/11/19/21/01/21/65962357_p0
.jpg
Filename  : C:\PixivDownloaded\patoreiba (1778439)\65962357_p0.jpg
Local file exists: C:\PixivDownloaded\patoreiba (1778439)\65962357_p0.jpg

Image URL : https://i.pximg.net/img-original/img/2017/11/19/21/01/21/65962357_p1
.jpg
Filename  : C:\PixivDownloaded\patoreiba (1778439)\65962357_p1.jpg
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode
=medium&illust_id=65962357
 [||||||||||||||||||||] 347.43 KiB of 347.43 KiB  Completed in 0.874s (397.51 Ki
B/s)
C:\pixivutils\pixivutil(test2)\library.zip\PIL\TiffImagePlugin.py:725: UserWarni
ng: Possibly corrupt EXIF data.  Expecting to read 1703936 bytes but only got 0.
 Skipping tag 42
 Image invalid, deleting...
Traceback (most recent call last):
  File "PixivUtil2.py", line 252, in download_image
  File "PIL\Image.pyc", line 2572, in open
  File "PIL\Image.pyc", line 2562, in _open_core
  File "PIL\JpegImagePlugin.pyc", line 764, in jpeg_factory
  File "PIL\ImageFile.pyc", line 102, in __init__
  File "PIL\JpegImagePlugin.pyc", line 338, in _open
  File "PIL\JpegImagePlugin.pyc", line 123, in APP
  File "PIL\JpegImagePlugin.pyc", line 416, in _getexif
  File "PIL\JpegImagePlugin.pyc", line 475, in _getexif
  File "PIL\TiffImagePlugin.pyc", line 716, in load
OverflowError: cannot fit 'long' into an index-sized integer
Error at download_image(): (<type 'exceptions.OverflowError'>, OverflowError("ca
nnot fit 'long' into an index-sized integer",), <traceback object at 0x050743C8>
) at https://i.pximg.net/img-original/img/2017/11/19/21/01/21/65962357_p1.jpg (9
000)
Retrying [1]...

**Comment by Nandaka** [comment]
Looks like the uploaded images got corrupter.

set `verifyimage = False` in config.ini for time being.

**Comment by Nandaka** [comment]
PIL
