### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Daha225** [Nandaka/PixivUtil2#363]
PixivDownloader2 version 20180503-beta2
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading D:\Pixiv DLer\PIXIV APP\PIXIV\config.ini ...
done.
Using default DB Path: D:\Pixiv DLer\PIXIV APP\PIXIV\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: dahadekan
Trying to log in with saved cookie
Cookie already expired/invalid.
Logging in...
Error at login(): (<type 'exceptions.TypeError'>, TypeError("'NoneType' object h
as no attribute '__getitem__'",), <traceback object at 0x03518120>)
Error at doLogin(): (<type 'exceptions.TypeError'>, TypeError("'NoneType' object
 has no attribute '__getitem__'",), <traceback object at 0x03518A08>)
Cannot Login!
press enter to exit.

I have try all, copying cookies, delete cookies from chrome and Re-login on pixiv website, so cookies is not expired, try to edit the config.ini
Please help.

**Comment by Nandaka** [comment]
Weird, I can login just fine (both by cookie and username/password).

Can you open the website from browser? Do you have antivirus/firewall? Have you tried on different computer?
