### ISSUE TITLE
How to not make folders for manga files

### ISSUE THREAD

**Issue by redbirdx** [Nandaka/PixivUtil2#365]
Hey, I updated the pixiv downloader and realized that it automatically makes new folders for manga files. In older versions it wasn't like that, so I wanted to ask how can I avoid that? Thank you very much and keep up the good work!

**Comment by Nandaka** [comment]
Check your config.ini for filenamemangaformat? remove the folder separator `\` from the filename format.

Your old config.ini is backed up as config.ini.bak.
