### ISSUE TITLE
Feature Request: Consider Blacklisted Members and Tags Downloaded

### ISSUE THREAD

**Issue by lulzkillergithub** [Nandaka/PixivUtil2#366]
### Prerequisites
* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
Good afternoon. This is obviously not crucial at all.

When doing scraping, a lot of screen time is dedicated to checking previously blacklisted members and images with blacklisted tags. I don't know exactly how PixivUtil2 does this exclusion work, so this might not be possible.

But I'd like when I'm scraping and I have already excluded, say, Image ID 123456, that the utility remembers that. Or it remembers that Image ID 654321 was blacklisted because Member ID 543216 is on a blacklist.

I'd also like to be able to clear these, much like how you can clear images in various ways under the database options.

Again, obviously not crucial and sounds like a lot of work but if it sounds like a good feature I'd really appreciate it.

**Comment by Nandaka** [comment]
You can try to use `useBlacklistMembers` and `useblacklisttags` in config.ini, check readme for details.

`useBlacklistMembers ==> Skip image by member id.
                        Please create 'blacklist_members.txt' in the same folder
                        of the application.
useblacklisttags==> Skip image if containing blacklisted tags.
                    The list is taken from blacklist_tags.txt, each tags is
                    separated by new line.
`
no feature to blacklist specific image id from list, but you can use the DB manager to blacklist specific image id.
