### ISSUE TITLE
Pixiv sketch pictures

### ISSUE THREAD

**Issue by hatabbich** [Nandaka/PixivUtil2#367]
I have a quastion, when are using download by artist ID, it's consider pixiv.sketch pics too or this site is partly from main???

**Comment by Nandaka** [comment]
Is it visible in the works list from pixiv webpage? or is the link to the image follow the same pattern like `https://www.pixiv.net/member_illust.php?mode=medium&illust_id=<image_id>`

**Comment by truefdk** [comment]
Its a separate subdomain and structure, would need specific code to scrape.
Same as pixiv's other subdomains.
Example:
https://sketch.pixiv.net/items/4939758965177020715
I would say there's a possibility for it to be a menu option in the future
(or a fork) but right now I think the main site is probably higher priority.

**Comment by hatabbich** [comment]
ok, thanks for answers.. it's just many of nice pictures post only on sketch not on main site..

**Comment by LieXXX** [comment]
I am also for getting the abilityto download sketches at some point.

**Comment by Nandaka** [comment]
will not do, open to pull request
