### ISSUE TITLE
I confuse

### ISSUE THREAD

**Issue by WandererZero** [Nandaka/PixivUtil2#368]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.

**Comment by WandererZero** [comment]
So how to put password? pls...

**Comment by Nandaka** [comment]
you can just type it in the console (it won't be show as *, just type and press enter)

or, https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L252

**Comment by WandererZero** [comment]
i still confuse...

**Comment by Nandaka** [comment]
why you are still confused? please tell me what you tried?

1. Run the application (PixivUtil2.exe)
2. Key in your username is asked and press enter.
3. Key in your password (it won't be shown in the UI) and press enter.
4. Wait for the reply from the server.

**Comment by afuckingcat** [comment]
I a meme actually in need of answers, I made a brand new account installed pixivdownloader and tried my luck at typing in the password and username but it says that the pivix ID and Email Adress may be incorrect not the actual username nor password, I just want to know what I'm doing wrong.

**Comment by Nandaka** [comment]
try to key in you username/password in config.ini?

Or try: https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L69

**Comment by afuckingcat** [comment]
Yeah don't worry anymore nandaka, I checked your read me folder, it helped ALLOT, you're script is working wonders, I can finally get that loli porn 24/7 x)) ur the man
