### ISSUE TITLE
member token and member id are confused when dling by memberid or imageid

### ISSUE THREAD

**Issue by PixivAddict** [Nandaka/PixivUtil2#369]
when downloading images using download by image id, as an example, image 22202127 from memberid 606787, produce an output folder using the member name めらず
when downloading by using the member id, the program properly uses the member token smlzshift

in the config.ini I have 
filenameformat = %member_token% (%member_id%)\%image_id%

**Comment by PixivAddict** [comment]
example

Input: 2
Image ids: 22311876
Processing Image Id: 22311876
Member Name  : めらず
Member Avatar: https://i.pximg.net/user-profile/img/2013/06/21/02/57/03/6400663_
518bcf2cb6c67eb842de0543c3244cee.png
Member Token : めらず
Title: 妖精の国の幼き姫
Tags : オーディンスフィア, メルセデス
Date : 2011-10-10 15:30:05+00:00
Mode : big
Image URL : https://i.pximg.net/img-original/img/2011/10/11/00/30/05/22311876_p0
.png
Filename  : C:\PixivDownloaded\めらず (606787)\22311876.png
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode
=medium&illust_id=22311876
Creating directory: C:\PixivDownloaded\めらず (606787)
 [||||||||||||||||||||] 297.12 KiB of 297.12 KiB  Completed in 0.782s (379.95 Ki
B/s)
 Image verified.

**Comment by Nandaka** [comment]
The new ui doesn't have references to the member token.
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=22311876

The member page still uses the old ui, so it can resolve the member token (based on stacc feed).

if the application cannot resolve the token, it will uses the name as the token.

**Comment by whinette** [comment]
Is it possible to have an option to lookup the member token through `authorId` or `userId` ? It seriously badly hurts my management disposition :/

**Comment by Nandaka** [comment]
any api I can use? looks like https://www.pixiv.net/ajax/user/606787 doesn't have the token data.

worst case scenario, I need to parse the member page for each image if you trigger the download from option 2.

**Comment by Nandaka** [comment]
ok, looks like I can use app-api https://app-api.pixiv.net/v1/user/detail?user_id=606787

It does contains the member token
![image](https://user-images.githubusercontent.com/836867/41139873-04e1ded2-6b1d-11e8-9c29-a7eb8674e41f.png)

**Comment by whinette** [comment]
Thanks, no need for the compiled version I run it from source.
It works well! Until pixiv change it again ;)
