### ISSUE TITLE
Processing Image Id: [id] Image ID ([id]): 'NoneType' object has no attribute 'findAll' 

### ISSUE THREAD

**Issue by awiebe** [Nandaka/PixivUtil2#370]
### Prerequisites

* [y ] Did you read FAQ section?
* [y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When fetching images bookmark images (mode 5), fetching fails partway through due to an exception.  Even with debugging logging on I can't seem to trace where exactly it is, and I can't get a stack trace because it's caught, but the generic exception catcher doesn't print the stack trace.

````
Processing Image Id: [id] 
Image ID ([id]): 'NoneType' object has no attribute 'findAll' 
````

### Steps to Reproduce
1. Have new images to fetch for any user
2. Input: 5,y,[enter],[enter]

**Expected behavior:** 
Normal scraping of images, skipping users after 2 already have images.

**Actual behavior:** [What actually happened]
Gets half way through scraping an image then dies with message.
````
Processing Image Id: [id] 
Image ID ([id]): 'NoneType' object has no attribute 'findAll' 
````
Where [id] is the id of any image not already stored.
Then continues scraping images for usr, failing each time.

### Versions

20180316 (commit f3a99d4)

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20180511-beta3

**Comment by awiebe** [comment]
That seems to have fixed it, I guess the new pixiv layout broke the scraper..again.
Keep up the good work.
