### ISSUE TITLE
Where is "download history" saved at?

### ISSUE THREAD

**Issue by Sicigi** [Nandaka/PixivUtil2#371]
OK, so started getting the "AttributeError ("'NoneType' object has no attribute 'find'",)" error.

Already did what the FAQ says but it isn't working. Now, in the past whenever the utility starts failing I just download the new version and it works again, problem is I have to download all images again.

Is there any file/info I can copy to the new version so it "remembers" what I've already downloaded in this one?

**Comment by Nandaka** [comment]
it is stored in the db.sqlite file on the application folder.

It is using SQLite database file format.
You can just overwrite the old folder with the new releases as the packages doesn't include that file.
If you are not sure, you can always back up the `config.ini` and `db.sqlite` files.
