### ISSUE TITLE
[Feature request] Download background image for artist

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#373]
The logic would be the same as the folder picture.

Background image is foundable in member web page, in it's head.

Example: view-source:https://www.pixiv.net/member.php?id=198128

```
    <style>
    body {
        background: #EDF0F5 url('https://i.pximg.net/background/img/2015/10/25/08/45/27/198128_77ddf78cdb162e3d1c0d5134af185813.jpg') no-repeat fixed;
    }
    </style>
```

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20170726

**Comment by whinette** [comment]
It works well, thanks!

**Comment by whinette** [comment]
With the new redesign, it looks like it has changed.
I found an artist with the new header (ex-background) working as an example: https://www.pixiv.net/member.php?id=8021957

The json is different, but still indicate 'background' (for now):
user: { 8021957: {"userId":"8021957","name":"yuzu-aki","image":"https:\/\/i.pximg.net\/user-profile\/img\/2018\/09\/17\/11\/23\/44\/14786252_df3649c03d98c4d5dd655c5ef57f6f97_50.jpg","imageBig":"https:\/\/i.pximg.net\/user-profile\/img\/2018\/09\/17\/11\/23\/44\/14786252_df3649c03d98c4d5dd655c5ef57f6f97_170.jpg","premium":false,"isFollowed":false,"isMypixiv":false,"background":{"repeat":null,"color":null,"url":"https:\/\/i.pximg.net\/c\/1920x960_80_a2_g5\/background\/img\/2018\/10\/02\/14\/04\/52\/8021957_2328e2818081e71c25b3aabd82f23c48.jpg","isPrivate":false}
