### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by TheDoc69** [Nandaka/PixivUtil2#374]
### Prerequisites
[ x] Did you read FAQ section?
[ x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Everything was working well until wednesday, using the old 20180314 version, but it stopped downloading (using mode 7 or 1) giving the following message for all pictures :

> "Cannot parse artist info, dumping to Dump for ?Best IT Training Institute?/?navy
> agajjar?????? [pixiv] UnknownProfile for self.html
> Image ID (69130006): 'NoneType' object has no attribute 'findAll'

I saw that the interface on pixiv changed for me (I didn't have the new interface before) so I tried the more recent versions, and it still not working but the error message changed to "can't compare offset-naive and offset-aware datetimes". Here is the result in mode 7 with a test run :

> PixivDownloader2 version 201805011-beta3
> https://github.com/Nandaka/PixivUtil2/releases
> Donate at https://bit.ly/PixivUtilDonation
> Reading H:\MSOCache\Pixiv\pixivutil\config.ini ...
> done.
> Using default DB Path: H:\MSOCache\Pixiv\pixivutil\db.sqlite
> Creating database... done.
> Only process members where the last update is >= 4500 days ago
> Only process image where day last updated >= 4500
> Using Username: #######
> Trying to log in with saved cookie
> Login successful.
> My User Id: #######
> Start Page = 1
> End Page = 300
> Reading: pixivutil/TEST.TXT
> Reading H:\MSOCache\Pixiv\pixivutil\config.ini ...
> done.
> Save to each directory using query tags.
> Searching for: (test OR TEST) test+OR+TEST
> Using Partial Match (s_tag)
> Looping... for https://www.pixiv.net/search.php?s_mode=s_tag&p=1&word=test+OR+TE
> ST&order=date_d
> Image #1
> Image Id: 69132021
> Bookmark Count: 0
> Processing Image Id: 69132021
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 662, in process_image
> TypeError: can't compare offset-naive and offset-aware datetimes
> Error at process_image(): 69132021
> Exception: (<type 'exceptions.TypeError'>, TypeError("can't compare offset-naive
>  and offset-aware datetimes",), <traceback object at 0x03D7A120>)
> Dumping html to: Error medium page for image 69132021.html
> Error at process_tags() at page 1: (<type 'exceptions.TypeError'>, TypeError("ca
> n't compare offset-naive and offset-aware datetimes",), <traceback object at 0x0
> 3D71F08>)
> Dumping html to: Error page for search tags test+OR+TEST at page 1.html
> Error at process_tags_list(): (<type 'exceptions.TypeError'>, TypeError("can't c
> ompare offset-naive and offset-aware datetimes",), <traceback object at 0x03D716
> 20>)
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 2067, in main
>   File "PixivUtil2.py", line 1831, in main_loop
>   File "PixivUtil2.py", line 1668, in menu_download_from_tags_list
>   File "PixivUtil2.py", line 1014, in process_tags_list
>   File "PixivUtil2.py", line 936, in process_tags
>   File "PixivUtil2.py", line 662, in process_image
> TypeError: can't compare offset-naive and offset-aware datetimes
> press enter to exit.

Same thing with mode 1 also.

I don't know what is wrong at all...

**Comment by Nandaka** [comment]
Can you try to change your location to Tokyo in Pixiv's Profile settings?

![image](https://user-images.githubusercontent.com/836867/41169215-d782c628-6b7a-11e8-8f6d-81c930aff444.png)

I'm using option 1 and it is working for me.

**Comment by Nandaka** [comment]
ok, can you set `dateDiff` to 0 temporarily in `config.ini`?

I think I know ther reason.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L662

**Comment by TheDoc69** [comment]
I tested it and yes, it works (only) with dateDiff=0. 
Thanks for your help !

**Comment by whinette** [comment]
It works well with datediff=1 post fix

**Comment by TheDoc69** [comment]
Thanks !
