### ISSUE TITLE
object has no attribute 'findAll' on all images 56948918

### ISSUE THREAD

**Issue by adamus1red** [Nandaka/PixivUtil2#375]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When downloading from my bookmarked users, only the users avatar is being downloaded. 

For all other images I get the following

> Processing Image Id: 56385225
> Image ID (56385225): 'NoneType' object has no attribute 'findAll'
> Wait for 0.991s

### Steps to Reproduce

1. Start PixivDownloader with option `-s 5`

**Expected behavior:** Image is downloaded

**Actual behavior:** Image is not downloaded 

### Versions

PixivDownloader2 version 20180414

**Comment by Nandaka** [comment]
https://github.com/Nandaka/PixivUtil2/releases
