### ISSUE TITLE
Duplicates after Database Cleanup

### ISSUE THREAD

**Issue by moxynox** [Nandaka/PixivUtil2#377]
After running the cleanup function for the first time, I'm starting to download a bunch of duplicates. 
For each download, I use the naming convention:
 %works_date_fmt{%Y-%m-%d}%_%image_id%-%title%
Interestingly enough, while the image ID of the duplicate remains the same, I'm getting a different work date, always the day before the first download.

To clarify, the pre-existing download will have file name:
2018-06-18_11111111-HelloWorld.jpg
While the newly downloaded duplicate will have file name:
2018-06-17_11111111-HelloWorld.jpg
Is the issue on pixiv's end?

Edit:
I should also add that this database has been around for about a year and a half, going through multiple versions of PixivUtil2. I would also like to mention that not every file is duplicated. In a folder of 81 images, only 18 were duplicates.

**Comment by moxynox** [comment]
I should also add that this database has been around for quite some time and has been through many different versions of PixivUtil2.

**Comment by Nandaka** [comment]
I suspect because the datetime handling, as pixiv now returns utc datetime in the api, compared previous one based on local/settings.

**Comment by Nandaka** [comment]
migration issue to newer api. will not fix.
