### ISSUE TITLE
Can't run program

### ISSUE THREAD

**Issue by JarieSuicune** [Nandaka/PixivUtil2#378]
I don't know if it could be that I am on Vista (sad, I know), but when I try to run the program the window appears for a split second then closes immediately.
I've got a fresh install (I just came across this program), so I wonder if there's something about it I am not understanding?
(I am SO EXCITED for this! Since Nekopaw is now abandoned, I've been looking for a Pixiv bulk gallery downloader for so long! I haven't found any others and would so love to get my Pixiv collection up to date...)

**Comment by Nandaka** [comment]
open an command prompt (cmd) and see what is the error?

**Comment by JarieSuicune** [comment]
Huh. Tried it... no good. I type the path, hit enter, and instantly get a message saying "NijieDownlaoder.UI has stopped working. A problem caused the program to stop working correctly. Windows with close the program and notify you if a solution is available."

I don't know what else to look for...?

**Comment by Nandaka** [comment]
You on the wrong github. Go to https://github.com/Nandaka/NijieDownloader/issues.

Anyway, check the readme.txt on the installation.

**Comment by JarieSuicune** [comment]
... Whoops. Sorry! Ok, don't know how I got that mixed up, but getting same problem with Pixiv Util2. However I was able to get some info from Command Prompt:

C:\Users\~~~\Desktop\temp\PixivUtil2-master\PixivUtil2.exe
Traceback (most recent call last):
  File "PixivUtil2.py", line 21, in <module>
  File "urllib2.pyc", line 94, in <module>
  File "httplib.pyc", line 80, in <module>
  File "mimetools.pyc", line 6, in <module>
  File "tempfile.pyc", line 35, in <module>
  File "random.pyc", line 885, in <module>
  File "random.pyc", line 97, in __init__
  File "random.pyc", line 113, in seed
WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly

**Comment by Nandaka** [comment]
try to install https://www.microsoft.com/en-us/download/details.aspx?id=29 ?
