### ISSUE TITLE
Ugoira-to-WebM conversion fails on the last frame

### ISSUE THREAD

**Issue by hasawovow** [Nandaka/PixivUtil2#381]
There's a [long-standing bug using ffmpeg](https://trac.ffmpeg.org/ticket/6128) where it doesn't honor the duration of the last frame when using the concat demuxer. What this means is the last frame is usually displayed for much shorter then specified in the concat file.

Looking at the comments and some [stackexchange posts](https://video.stackexchange.com/questions/20588/ffmpeg-flash-frames-last-still-image-in-concat-sequence), there's a fix. Basically you just repeat an extra `file` directive of the last frame after the last `duration`, so something like
```
file path/to/001.png
duration 5
file path/to/002.png
duration 7
```
becomes
```
file path/to/001.png
duration 5
file path/to/002.png
duration 7
file path/to/002.png
```

This is also the fix listed in the [FFMPEG wiki](https://trac.ffmpeg.org/wiki/Slideshow#Concatdemuxer).

In the `ugoira2webm` function, it looks like you need to change
```
        for i in frames:
            ffconcat += "file " + i['file'] + '\n'
            ffconcat += "duration " + str(float(i['delay']) / 1000) + '\n'

        with open(d + "/i.ffconcat", "w") as f:
            f.write(ffconcat)
```
into
```
        for i in frames:
            ffconcat += "file " + i['file'] + '\n'
            ffconcat += "duration " + str(float(i['delay']) / 1000) + '\n'

        ffconcat += "file " + frames[-1]['file'] + '\n'

        with open(d + "/i.ffconcat", "w") as f:
            f.write(ffconcat)
```

**Comment by Nandaka** [comment]
updated in https://github.com/Nandaka/PixivUtil2/releases/tag/v20180702
