### ISSUE TITLE
[Feature request] DL by Group/folder ID News (prenium feature)

### ISSUE THREAD

**Issue by EivKnightOfIce** [Nandaka/PixivUtil2#383]
### Prerequisites

* [x] Did you read FAQ section?n yes
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? yes

### Description

Hi,
Sry for my english and my stupidity, can you add features:
"Download new illust from boukmarked memmbers by Group/folder ID "

Exemple by Personal link for group/folder: "AD"
https://www.pixiv.net/bookmark_new_illust.php?tag=AD

Cordialement,
Eiv

### Versions
PixivUtil20180607

**Comment by Nandaka** [comment]
I don't think https://www.pixiv.net/bookmark_new_illust.php?tag=AD has a **tag** parameter.

Do you means https://www.pixiv.net/bookmark.php?tag=AD? You can use option `6. Download from bookmarked images (/bookmark.php)`
![image](https://user-images.githubusercontent.com/836867/42297574-11e4d910-8033-11e8-801e-18ffb130fdb0.png)

**Comment by EivKnightOfIce** [comment]
Sorry, poorly expressed, I seek to download the new illustrations of my follow-ups. But only those in a folder, for not having rescan all the files that I already download and only retrieve the news.

and the option work see: https://i.imgur.com/y7tlcAC.png

**Comment by Nandaka** [comment]
I see, somehow I don't have it in my pixiv account. Is it premium feature?

**Comment by EivKnightOfIce** [comment]
Hooo yes is premium ^^" feature https://i.imgur.com/z8ya7JX.png
