### ISSUE TITLE
Completely New To GitHub, But I Was Wondering How Do I Transfer My "Database" Over To New Releases?

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [Nandaka/PixivUtil2#384]
I am currently using an older beta release `pixivutil20180503-beta2`, and I was wondering how can I use the newest release, `pixivutil20180702`?

Do I simply copy `db.sqlite` into the folder of the latest release, and all of my downloaded bookmarks and etc will transfer over?

**Comment by Nandaka** [comment]
yep.
