### ISSUE TITLE
[Question] Download by tag instruction/guide

### ISSUE THREAD

**Issue by Kira-20** [Nandaka/PixivUtil2#386]
Hello nandaka, and to anyone else reading this. I have a question regarding using the utility's download by tag function. It asks me to input Bookmark Count to which I have no idea what to put here as I'm trying to get the whole images under a tag without any specific bookmark count. Next it asks whether I want to download with oldest first and then start and end page. I have no problem understanding these ones but the next one, it asks me for start and end date.

So as you can see, I'm really confused here on what to input on bookmark count because I'm trying to get the whole images under one tag. And lastly for the start and end date, I mean what am I supposed to put there and why do I have to input the end and start date when it asked me earlier to download from oldest to newest and from start page  to end page. Help me out here

**Comment by Nandaka** [comment]
just leave it as empty if you dont use it.

- Bookmark count ==> filter out any images with bookmark count less than given value.
![image](https://user-images.githubusercontent.com/836867/43054816-ebdd191c-8e65-11e8-8d66-497bd2eba6db.png)
- Start/end date ==> This is used to replicate the timespan filter.
![image](https://user-images.githubusercontent.com/836867/43054831-07933696-8e66-11e8-8859-e912138cc975.png)

Please note, non-premium user is limited to 1000 search pages.

**Comment by Kira-20** [comment]
I see, I'll give this a try tomorrow!

**Comment by Kira-20** [comment]
Nandaka, I've tried downloading by tag and it works now. Although I have one more question. When downloading does the tool always categorize the illustration in respective author folders? I thought when downloading by tags, the tool will just grab the images and save it under one folder instead of categorizing and putting the images in folders of the authors making them.
