### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by dethkruzer** [Nandaka/PixivUtil2#393]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I added my info to the config.ini file, and ran the .exe as an admin, got the following text(minus somedetails for my privacy): 

PixivDownloader2 version 20180726
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\Users\[redacted]\Downloads\pixivutil20180726\config.ini ...
done.
Using default DB Path: C:\Users\[redacted]\Downloads\pixivutil20180726\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: [redacted]
Trying to log in with saved cookie
Error at doLogin(): (<class 'urllib2.URLError'>, URLError(gaierror(11001, 'getad
drinfo failed'),), <traceback object at 0x026D09B8>)
Cannot Login!
press enter to exit.

also gonna attach the log thing, if that helps 

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/2239153/pixivutil.log)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.

**Comment by Nandaka** [comment]
Can you open the website from your browser? Are you using firewall/antivirus?

Looks like the application failed to resolve the pixiv website ip address.

**Comment by dethkruzer** [comment]
I can visit pixiv via browser yet, both through Chrome and (a possibly outdated) Firefox. Also tried using the cookie information from both chrome and firefox. 

To answer the second, I do not have a firewall active, but I use Avast antivirus.  Though Avast did not say anything about stopping a connection, outbound or otherwise.

for additional steps, I tried turning off the daylight savings option on my system. That did not seem to contribute one way or the other.

**Comment by Nandaka** [comment]
Can you try to disable the firewall feature? Maybe Avast by default blocking the application?

**Comment by dethkruzer** [comment]
So turned out that avast did have a built-in firewall. Tried disabling it and then repeated the above steps. again no luck.

here's what I got. I can give the log as well if that helps.

PixivDownloader2 version 20180726
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\Users\[redacted]\Downloads\pixivutil20180726\config.ini ...
done.
Using default DB Path: C:\Users\[redacted]\Downloads\pixivutil20180726\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: [redacted]
Trying to log in with saved cookie
Error at doLogin(): (<class 'urllib2.URLError'>, URLError(gaierror(11001, 'getad
drinfo failed'),), <traceback object at 0x027509B8>)
Cannot Login!
press enter to exit.

**Comment by Nandaka** [comment]
Are you using socks proxy in config.ini?

**Comment by dethkruzer** [comment]
I have useproxy set to false if that's what you mean? Sorry, I really have minimal understanding of programming and the like.

**Comment by Nandaka** [comment]
I asking if your internet connection is using proxy server (if you don't know, most likely you don't). 

For whatever reason, the application cannot resolve the ip address. This is handled by the operating system, so I'm not sure why it fails.

When the application start, it will try to open https://www.pixiv.net/mypage.php to check the login validity, else it will open https://accounts.pixiv.net/login and use the given username/password to relogin.

Can you try on other pc?

**Comment by Nandaka** [comment]
Also I notice the gaierror(), so I thought you enable the socks proxy in the config.ini by setting `useproxy = True`.

**Comment by dethkruzer** [comment]
I gotta say I'm impressed by your tenacity to help me get this woking. That's a rare virtue to see.

Anyways, I'm not aware of my connection using a proxy server.

anyways, I tried setting usepproxy to True (don't know if I need to change anything else so I left everything else alone). Then I turned off my firewall, and ran it as an adminstrator. Again, no luck.

PixivDownloader2 version 20180726
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\Users\[redacted]\Downloads\pixivutil20180726\config.ini ...
done.
Using default DB Path: C:\Users\[redacted]\Downloads\pixivutil20180726\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: [redacted]
Trying to log in with saved cookie
Error at doLogin(): (<class 'urllib2.URLError'>, URLError('no host given',), <tr
aceback object at 0x02860850>)
Cannot Login!
press enter to exit.

Trying on other PCs is unfortunately not an option.

Should I be logged out from pixiv when I try to do this? And is it possible that some of my browser extensions could be interfering with this?

**Comment by Nandaka** [comment]
> Should I be logged out from pixiv when I try to do this? 

Nope

> And is it possible that some of my browser extensions could be interfering with this?

I don't think so.

Can you check Control Panel --> Internet Option --> Connections --> LAN Settings and see if the automatic configuration or the proxy is enabled?
![image](https://user-images.githubusercontent.com/836867/43407437-585d6452-9451-11e8-8d50-75481ec1252b.png)

Or changing the DNS server for your connection from `Control Panel\Network and Internet\Network Connections` -> open the wifi adapter or ethernet adapter -> Properties -> Networking -> TCP/IP v4 -> DNS server. Below are the dns server that I use (it is from Chaos Computer Club and dns.watch server)
![image](https://user-images.githubusercontent.com/836867/43407648-e634ade4-9451-11e8-8985-24957652ce38.png) and restart the computer?

Else I don't know why it failed to resolve the ip address...

**Comment by Nandaka** [comment]
remember to backup the old dns value, if any, before changing the dns settings
