### ISSUE TITLE
Download by Member ID returns error 1004

### ISSUE THREAD

**Issue by esserius** [Nandaka/PixivUtil2#394]
### Prerequisites

* [ Yes] Did you read FAQ section?
* [ Yes] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Whenever attempting to download via member_id, a 1004 error message occurs. Can still download images by using image_id, but member_id doesn't seem to work.

### Steps to Reproduce

1. Download by member_id
2. Enter member id #
3. 1004 error returns

**Expected behavior:** [What you expected to happen]
Download the images of the associated member_id
**Actual behavior:** [What actually happened]
returns 1004 error
### Versions
20180726
You can get this information from executing `PixivUtil2.py --help`.

**Comment by Nandaka** [comment]
1004 means NO_IMAGES.

Can you delete the `pixivutil.log`, rerun the application, and upload the generated log file?

Also, ensure you enable the R-18 mode from the website, if you set `r18mode = True` in config.ini. You need to delete the old cookie value if you change the settings from Pixiv website.

**Comment by esserius** [comment]
2018-07-30 20:42:04,559 - PixivUtil20180726 - INFO - ###############################################################
2018-07-30 20:42:04,559 - PixivUtil20180726 - INFO - Starting...
2018-07-30 20:42:04,561 - PixivUtil20180726 - INFO - Setting log level to: DEBUG
2018-07-30 20:42:04,561 - PixivUtil20180726 - INFO - No default cookie jar available, creating... 
2018-07-30 20:42:04,562 - PixivUtil20180726 - INFO - Using default DB Path: E:\pixivutil20180726\db.sqlite
2018-07-30 20:42:04,563 - PixivUtil20180726 - INFO - Only process members where the last update is >= 7 days ago
2018-07-30 20:42:04,563 - PixivUtil20180726 - INFO - Using Username: esserius
2018-07-30 20:42:04,563 - PixivUtil20180726 - INFO - Trying to log in with saved cookie
2018-07-30 20:42:07,960 - PixivUtil20180726 - INFO - Login successful.
2018-07-30 20:42:08,969 - PixivUtil20180726 - INFO - Logged in using cookie
2018-07-30 20:42:08,983 - PixivUtil20180726 - INFO - My User Id: 8839099.
2018-07-30 20:42:38,456 - PixivUtil20180726 - INFO - Member id mode.
2018-07-30 20:42:50,520 - PixivUtil20180726 - INFO - Member IDs: [14764274]
2018-07-30 20:42:50,520 - PixivUtil20180726 - INFO - Processing Member Id: 14764274
2018-07-30 20:42:50,539 - PixivUtil20180726 - INFO - Member Url: https://www.pixiv.net/member_illust.php?id=14764274&p=1
2018-07-30 20:42:52,532 - PixivUtil20180726 - INFO - Member ID (14764274): 1004 'No image found!'

**Comment by esserius** [comment]
Perhaps helpful or maybe not, but - when I attempt to download an image via image_id from that artist, such as https://www.pixiv.net/member_illust.php?mode=medium&illust_id=69941488

The download works.

**Comment by Nandaka** [comment]
It is working on my side:
```
x. Exit
Input: 1
Member ids: 14764274
Start Page (default=1): 1
End Page (default=0, 0 for no limit): 1
Member IDs: [14764274]
Processing Member Id: 14764274
End Page: 1
Reading D:\UserData\irawanad\Dropbox\PixivUtil\config.ini ...
done.
Page  1
Member Url: https://www.pixiv.net/member_illust.php?id=14764274&p=1
Member Name  : GAMBE@1日目東D-07a
Member Avatar: https://i.pximg.net/user-profile/img/2017/07/08/18/57/19/12825630_d3c63472a0e942039d64716f035c3f79_170.png
Member Token : seelunto
Member Background : https://s.pximg.net/common/images/bg/star02.png
Start downloading... Using Referer: https://www.pixiv.net/
Creating directory: D:\Temp\Pixiv2\14764274 seelunto
 [||||||||||||||||||||] 61.33 KiB of 61.33 KiB  Completed in 0.139s (441.24 KiB/s)
 Image verified.
Start downloading... Using Referer: https://www.pixiv.net/
 [||||||||||||||||||||] 1.51 KiB of 1.51 KiB  Completed in 0.002s (755.37 KiB/s)
 Image verified.
#1
Processing Image Id: 69941488
Title: 花嫁の乙女エリゴーネ
Tags : オリジナル, 刻のイシュタリア, 仕事絵
Date : 2018-07-30 15:30:00+00:00
Mode : big
```

This is what I see in the member page:

**Comment by esserius** [comment]
So I made a new account and for some reason that account works. But my other account doesn't.

**Comment by Nandaka** [comment]
Maybe they do A/B testing for possible new UI changes on your old account? 
Do you notice any differences on the website when loading the artist page using your previous account and the new account?

**Comment by esserius** [comment]
Ok, the default views do look different between the two accounts

**Comment by esserius** [comment]
One looks like what you posted, the other looks completely different

**Comment by esserius** [comment]
![untitled-1](https://user-images.githubusercontent.com/41933835/43439072-3070d240-9446-11e8-8455-5489a59df2ff.jpg)
Here's what the view looks like in the account that's not working.

**Comment by esserius** [comment]
Well, hopefully this will work
http://www.filedropper.com/gambeview

Here's a zip of the page.

**Comment by esserius** [comment]
Also, given that I'm not particularly attached to the account to begin with, if it's possible I'd be happy to give you access to the account if there's a way to PM the details to you.

**Comment by SushiFart** [comment]
I also want to report the same exact issue, I also have the new layout so maybe it has to do with that.

**Comment by GerhardSauer** [comment]
I have the same issue with the new design.
Is there any way I can help?

**Comment by Daha225** [comment]
Yeah, same with me, I hope it's fixed soon, thank you

**Comment by Nandaka** [comment]
I still got the old ui, most likely the ui changes is not stable yet.

**Comment by Nandaka** [comment]
I'm able to get the image list using the ajax API, but looks like they separate the illustration and manga ids using `https://www.pixiv.net/ajax/user/1039353/profile/all`.

This will cause a problem if you need to filter using tags (or enable the R-18 mode only), as it uses different api endpoint: `https://www.pixiv.net/ajax/user/1039353/illusts/tag/艦これ?offset=0&limit=24`  and `https://www.pixiv.net/ajax/user/1039353/manga/tag/艦これ?offset=0&limit=24`, as it will skew the counter.

**Comment by Nandaka** [comment]
got the proper api endpoint for both illust and manga: `https://www.pixiv.net/ajax/user/1113943/illustmanga/tag/%E6%A5%B5%E4%B8%8A%E3%81%AE%E4%B9%B3?offset=0&limit=24`

**Comment by Nandaka** [comment]
You can try to use https://github.com/Nandaka/PixivUtil2/releases/tag/v20180813-beta1

**Comment by GerhardSauer** [comment]
Thank you very much, works fine!

**Comment by GerhardSauer** [comment]
Update:
the ajax method runs in errors if the artist account is suspended (This user account has been suspended).

httperror_seek_wrapper: HTTP Error 403: Forbidden
Error at processing Artist Info: (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0xae8dfb8 whose wrapped object = <closeable_response at 0xaefed50 whose fp = <response_seek_wrapper at 0xaef30d0 whose wrapped object = <closeable_response at 0xaef31c0 whose fp = <socket._fileobject object at 0x0AF071F0>>>>>, <traceback object at 0x0AEFEAD0>)
Member Url: https://www.pixiv.net/ajax/user/3077920/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 428, in process_member
  File "PixivBrowserFactory.pyc", line 456, in getMemberPage
  File "PixivBrowserFactory.pyc", line 385, in getMemberInfoWhitecube
  File "mechanize\_mechanize.pyc", line 254, in open
  File "mechanize\_mechanize.pyc", line 310, in _mech_open
httperror_seek_wrapper: HTTP Error 403: Forbidden

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/PixivUtil2/releases/tag/v20180815-beta2

**Comment by GerhardSauer** [comment]
Suspended artists are recognized now.
Works so far, I will update this post later, when my list is through ( 700 artists remaining).
