### ISSUE TITLE
Using 8(bookmark_new_illust) , how to save all in one folder instead of many named by artist?

### ISSUE THREAD

**Issue by linbolaevateinn** [Nandaka/PixivUtil2#395]
The default setting is nice , but I just want such a feature for some reason . Sorry for my poor english that cant support a complete check of FAQ making sure if there has been such a feature . Apologize if this issue bothered you .

**Comment by Nandaka** [comment]
You can change the `filenameformat`/'filenamemangaformat'/'avatarNameFormat' in config.ini using notepad. You can remove the `\` from the format to make all the files in single folder.

See https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L389 for formatting
