### ISSUE TITLE
Modifier To Store Artist Name in "Author" Metadata?

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [Nandaka/PixivUtil2#397]
Hello I was wondering if we could get an option or modifier in the .ini file that will store the artist's name in the "Author" metadata if the file type is .jpg.

I'd also appreciate if we could store the Pixiv code in the "Comments" metadata or something.

**Comment by Nandaka** [comment]
no, as it will modify the file and it will cause problem with size detection for new/updated file.
