### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by panhartstuff** [Nandaka/PixivUtil2#398]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Is there a clean way to update to a new version without losing database, settings, downloaded images, etc.?

**Comment by Nandaka** [comment]
you can drop the new files from the archive to the existing installation.

If you are not sure, you can always backup `config.ini` and `db.sqlite` before updating. 
As for the downloaded images, depending on where do you save it, usually it won't be affected.
