### ISSUE TITLE
Number of images to be processed is wrong

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#399]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

After new update PixivUtil shows that it downloads more images that artist got. Most likely miscounting number of images

![what](https://user-images.githubusercontent.com/5390835/44218099-a40d7a80-a181-11e8-9264-a936f866d0a4.PNG)

### Steps to Reproduce
Start downloading new artist with option 4. Wait. Current number of downloaded image is less than total number of images to download

I expect that number of current image is always less or equal than total.
### Versions

v20180815-beta2

**Comment by NHOrus** [comment]
Em... I suggest testing on different artist, sorry, this one is NSFW.

**Comment by NHOrus** [comment]
Thank you, was quite fast.

**Comment by Nandaka** [comment]
for any option?

**Comment by NHOrus** [comment]
With tag set
