### ISSUE TITLE
Close Window After Operation Modifier?

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [Nandaka/PixivUtil2#401]
Hey there I was wondering if after we choose a main option like downloading bookmarked images, that we can have Y/N option on closing the window after it finishes downloading everything,

**Comment by Nandaka** [comment]
this one ==> https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L219

**Comment by NHOrus** [comment]
I think he wanted a switch, like a tag query for option 4. I think it's horrible for useability.

Better would be `closeAfterDone` option for `config.ini` with input either True/False, or, preferably, in number selector format, like `1,4-7,11` so PixivUtil2 gets to exit after completing only options 1, 4, 5, 6, 7 and 11.

`-x` works perfectly fine by itself, but not when you stop process with Ctrl-C, by the way,

**Comment by SakiSakiSakiSakiSaki** [comment]
> this one ==> https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L219

Question. Do I add -X at the very beginning before even doing anything?

**Comment by NHOrus** [comment]
No, you add it to startup line. Like, creating a shortcut to the program and then changing properties with `-x` added to object line.

**Comment by SakiSakiSakiSakiSaki** [comment]
That's what I mean. The first line when I boot it up.

Here right?

http://prntscr.com/km5ng5

**Comment by NHOrus** [comment]
No.

https://i.imgur.com/87mBnUM.png

**Comment by SakiSakiSakiSakiSaki** [comment]
Ohhh I remember that.

I mean yea I can do that but, wouldn't it be great as a feature?
