### ISSUE TITLE
How to change filenameformat etc.

### ISSUE THREAD

**Issue by IatnehRevol** [Nandaka/PixivUtil2#403]
I want to change  filenameformat etc to like ank pixiv tool how it downloads for me like this **?site-name?/(?member-id?) ?memoized-name?/?illust-year?-?illust-month?-?illust-day? (?illust-id?) ?title?** and can multiple images be in one folder ?

**Comment by Nandaka** [comment]
Check https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L389

Not sure about site-name, I don't think I have it. To save everything in single folder, just remove the folder separator `\`
