### ISSUE TITLE
Can't download 

### ISSUE THREAD

**Issue by IatnehRevol** [Nandaka/PixivUtil2#404]
so i can't download instant i'm getting this  
![image](https://user-images.githubusercontent.com/41537023/44745878-bc3eab80-ab2a-11e8-85fb-fb9bc418d970.png)

**Comment by Nandaka** [comment]
which version you are using? Ensure you get the latest releases here: https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
option 11?

**Comment by IatnehRevol** [comment]
sorry i don't understand what you mean?

**Comment by IatnehRevol** [comment]
@Nandaka I solved it I realized I download it pre-released version. Sorry for troubling you and thanks
