### ISSUE TITLE
[Feature Request] Write metadata to database

### ISSUE THREAD

**Issue by awiebe** [Nandaka/PixivUtil2#405]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Add tags and titles to the sqlite database, they can be written to JSON files but do not seem to be stored in the database.

```
pixiv_tag(id,name)
pixiv_master_image_tag(tag_id,master_image_id)
pixiv_manga_image_tag(tag_id,manga_image_id)
pixiv_master_image(...,title,...)
```

**Comment by jrdp18** [comment]
I'm interested in a text file containing:
```
pixiv id
title
description
tags
```
I use folders for manga/multiple images so the text file can go inside the folder. For single images, it would be collected in a single text file, each id separated by an empty space.

**Comment by Nandaka** [comment]
@jrdp18  set `writeimageinfo = True` in the config.ini
It will write 1 text file per post.
See readme for details.

**Comment by jrdp18** [comment]
Thanks.
