### ISSUE TITLE
[Feature Request] Download images by manga series

### ISSUE THREAD

**Issue by charzho** [Nandaka/PixivUtil2#406]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Artists can serialize their works into a Series. Currently, there is no way to exclusively download these images, only work-arounds such as using shared tags.

Example: https://www.pixiv.net/user/4412/series/6474

**Comment by Nandaka** [comment]
I notice that they haven't moved the ui to the new ajax series. Let see what I can do.

**Comment by awiebe** [comment]
I don't know if the unofficial API treats them differently, but display seems to let you tel an image to display either as `medium` or a `manga`.  But I guess since the post know to show that something is a collection if it returns multiple issues, I guess you could filter from that.

**Comment by Nandaka** [comment]
No specific API to collect the works related to the manga except by iterating from the 1st series.

Assuming the input will ask the member id and the mangaseries id.
E.g.
1. use https://www.pixiv.net/ajax/user/4412/profile/all as the mount point to validate and get the first work.  
  ![image](https://user-images.githubusercontent.com/836867/54534098-f74fe180-498b-11e9-845c-ef423ec78c1f.png)
2. Get the illust details https://www.pixiv.net/ajax/illust/37514989 to get the next series in the manga series.  
  ![image](https://user-images.githubusercontent.com/836867/54534190-22d2cc00-498c-11e9-9ffa-a7d360bf8376.png)
3. Stop until the next series is null.
  ![image](https://user-images.githubusercontent.com/836867/54534264-439b2180-498c-11e9-84a4-5a655822689f.png)

**Comment by Nandaka** [comment]
assuming memberId and mangaSeries are given, then we can use this API:

https://www.pixiv.net/ajax/series/6474?p=1&lang=en
![image](https://user-images.githubusercontent.com/836867/91008062-171f1680-e610-11ea-96db-93e2c9c49d99.png)

**Comment by Nandaka** [comment]
added in https://github.com/Nandaka/PixivUtil2/releases/tag/v20201009-beta1
