### ISSUE TITLE
bookmark all downloaded images by member id? Suggestion

### ISSUE THREAD

**Issue by EfronC** [Nandaka/PixivUtil2#407]
### Prerequisites

* [*] Did you read FAQ section?
* [*] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Is there an option to bookmark all downloaded images? I move in Pixiv by Bookamarking images i have already downloaded, that way, if i found an image, i can know if i have downloaded or no. With PixivUtil2 it's easier because i can download all the images from an artist, but the program doesn't bookmark the images it has already downloaded, meaning that if i download all the images of an artist with the program, i will need to go and Bookmark them manually. Could an option be added(And activated from config.ini) where, when active, bookmark the images it download? Or, in the case is hard to bookmark and Download, Another option to bookmark all the images from an artist from its member id? It would be great for the people that navigate pixiv and use the bookmarks as guides.

**Comment by Nandaka** [comment]
nope, and I think you got a limit on the number of bookmarked images.
