### ISSUE TITLE
Is there option to download by bookmark and member id?

### ISSUE THREAD

**Issue by IatnehRevol** [Nandaka/PixivUtil2#408]
is possible to do that? Its really pain in the ass the delete non bookmarked images.

**Comment by Nandaka** [comment]
I don't think it is available in the pixiv website. If there is a page in the site/api I can use, maybe I can do something.

**Comment by Nandaka** [comment]
You can try `6. Download from bookmarked images (/bookmark.php)` if you want to download the images that you have bookmarked.
