### ISSUE TITLE
The download by tag and member id didn't work

### ISSUE THREAD

**Issue by pongsatond** [Nandaka/PixivUtil2#409]
![image](https://user-images.githubusercontent.com/34614637/45590148-47f26d80-b95c-11e8-8478-f496f2334018.png)

**Comment by pongsatond** [comment]
![image](https://user-images.githubusercontent.com/34614637/45598910-1e454f00-ba0d-11e8-9578-6b42c4e8d4d0.png)
Didn't work either.

**Comment by Nandaka** [comment]
try R-18, it is case sensitive.

**Comment by pongsatond** [comment]
![image](https://user-images.githubusercontent.com/34614637/45639320-dccea580-bad9-11e8-9350-f3e5c8ae3528.png)

**Comment by Nandaka** [comment]
Try the BETA: https://github.com/Nandaka/PixivUtil2/releases

Looks like you have the update UI one.

**Comment by pongsatond** [comment]
![image](https://user-images.githubusercontent.com/34614637/45673336-a5e9a580-bb54-11e8-96ef-df1d13ad865b.png)
Nah. Not working.

**Comment by Nandaka** [comment]
ow shit, you are using option 10, not 1. No wonder it doesn't work. I'll update the program.

If you strictly only download R-18 images, try to use option 1 with `r18mode = True` set in the config.ini

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20180918

**Comment by pongsatond** [comment]
![image](https://user-images.githubusercontent.com/34614637/45709381-196bd100-bbae-11e8-87e7-1e7b8fc22c6d.png)
Thanks for the update and the tip.
