### ISSUE TITLE
image_id list support please

### ISSUE THREAD

**Issue by wankio** [Nandaka/PixivUtil2#412]
built-in feature only let you download one id at once, can it have support list of illust Urls? Ty

**Comment by Nandaka** [comment]
nope, but you can paste multiple image id in console, separated by space.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1483

**Comment by wankio** [comment]
oh ok it's enough,

**Comment by Nandaka** [comment]
Check wiki: https://github.com/Nandaka/PixivUtil2/wiki
