### ISSUE TITLE
accidentally have memberid 0 in database, how do i remove

### ISSUE THREAD

**Issue by PixivAddict** [Nandaka/PixivUtil2#414]
loops at 

Member Url: https://www.pixiv.net/ajax/user/0/profile/all
Traceback (most recent call last):
  File "PixivUtil2.py", line 428, in process_member
  File "PixivBrowserFactory.pyc", line 492, in getMemberPage
  File "mechanize\_mechanize.pyc", line 254, in open
  File "mechanize\_mechanize.pyc", line 310, in _mech_open
httperror_seek_wrapper: HTTP Error 400: Bad Request
Error at processing Artist Info: (<class 'mechanize._response.httperror_seek_wra
pper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0x47ab228 whose
wrapped object = <closeable_response at 0x3e21620 whose fp = <response_seek_wrap
per at 0x4bd7990 whose wrapped object = <closeable_response at 0x3e21b98 whose f
p = <socket._fileobject object at 0x03E37470>>>>>, <traceback object at 0x04BBA0
58>)

when I try to download by list (4)

**Comment by Nandaka** [comment]
use the Manage DB option (`d`) and delete the member id (`9`) before starting download by list.

**Comment by Nandaka** [comment]
Also https://github.com/Nandaka/PixivUtil2/blob/master/readme.txt#L92
