### ISSUE TITLE
DB cleanup throws exception

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#415]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Database cleanup fails with error:
```
Error at cleanUp(): (<type 'exceptions.TypeError'>, TypeError("object of type 'NoneType' has no len()",), <traceback object at 0x03DEF3F0>)
failed
Error:  (<type 'exceptions.TypeError'>, TypeError("object of type 'NoneType' has no len()",), <traceback object at 0x03DEF648>)
```
I suspect corrupt db

### Steps to Reproduce

Started db cleanup from interface

**Expected behavior:**

PixivUtil2 runs cleanup until no images in db without equivalent on disk remains
Alternatively, provides more information so DB can be repaired with external tools without too much pain.

**Actual behavior:**

Exception, cleanup stops halfway through the process.

### Versions

20180918

**Comment by Nandaka** [comment]
are you running from script or exe? Does it shows some image paths or just straight away shows error?
You can check the DB health by using Manage DB (`d`) then Compact DB (`p`). Backup first before running just in case.

**Comment by NHOrus** [comment]
From exe. 
Compaction said nothing about errors. After it cleanup ran into exception again.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20180928

**Comment by NHOrus** [comment]
Works, thank you.
