### ISSUE TITLE
Date doesn't start at current for some members

### ISSUE THREAD

**Issue by keeper0m3ga** [Nandaka/PixivUtil2#416]
Whenever downloading using a list,
and a member is being skipped due to no new post criteria,
and the number of new posts already downloaded for this member is 0,
the next member will continue scanning from the date where the previous member was when skipping rather than resetting to the current date.

**Comment by Nandaka** [comment]
Which settings in config.ini you are talking about?

**Comment by Nandaka** [comment]
Not sure If I understand, do you have the sample with screenshot? Give me more information to check.
Try to disable/enable these config `processfromdb`, `daylastupdated`, `checkUpdatedLimit`, `dateDiff`.
Ensure you are using the latest releases here: https://github.com/Nandaka/PixivUtil2/releases

The post work date is based on the value given by the javascript value.
Please note that the datetime is based on UTC and not converted to local time.
![image](https://user-images.githubusercontent.com/836867/46052059-30db2900-c16f-11e8-919c-b94b7c499d45.png)

https://github.com/Nandaka/PixivUtil2/blob/master/PixivModelWhiteCube.py#L235

**Comment by keeper0m3ga** [comment]
I set it all to disabled/0 and oddly when it reaches page 2 it jumps from 2009 to 2017

**Comment by keeper0m3ga** [comment]
it seemed to ignore the db setting so i wiped it here's the screenshot afterwards at the moment the date leaps
![pixivutil2](https://user-images.githubusercontent.com/43591090/46053054-8c8ebd80-c141-11e8-8994-c6b694ca18b4.png)

**Comment by keeper0m3ga** [comment]
after looking at the screenshot more carefully it would seem it goes by order of image id but sorted as a string rather than a number.

**Comment by Nandaka** [comment]
I see, I think it is because the API separate illust and manga. I think I need to sort it after I append the list together in descending order (latest image first)
![image](https://user-images.githubusercontent.com/836867/46134404-5bafa500-c275-11e8-84d7-ccc42f3bd5d2.png)
https://www.pixiv.net/ajax/user/7575/profile/all

If you use search by member id and tags or enable R-18 mode, it will uses different API
https://www.pixiv.net/ajax/user/7575/illustmanga/tag/R-18?offset=0&limit=24

**Comment by keeper0m3ga** [comment]
Thanks in advance.

And despite the odd bug i still love the program.

Thank you for making such a neat and useful program.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20180928

**Comment by keeper0m3ga** [comment]
Just got around to testing it.
It works perfectly now.

Thanks you.
