### ISSUE TITLE
pixiv changed its layout again and broke pixivutil

### ISSUE THREAD

**Issue by PixivAddict** [Nandaka/PixivUtil2#419]
I can confirm that download by member id 3057387 is broken, no images found when there are

**Comment by Nandaka** [comment]
You are using latest version? https://github.com/Nandaka/PixivUtil2/releases

I does load for me, give me more details. What is the member urls being resolved?

**Comment by Nandaka** [comment]
both R-18 mode on and off give me the image and I can download succesfully.
- https://www.pixiv.net/ajax/user/3057387/illustmanga/tag/R-18?offset=0&limit=24
![image](https://user-images.githubusercontent.com/836867/46387847-7bbee880-c6fb-11e8-9eaa-b52b08bf0c8b.png)

- https://www.pixiv.net/ajax/user/3057387/profile/all
![image](https://user-images.githubusercontent.com/836867/46387840-72358080-c6fb-11e8-903b-5f090f0bed83.png)

**Comment by PixivAddict** [comment]
aw, updating it fixed my issue
sorry for the needless thread guys
