### ISSUE TITLE
the timestamp is delayed by 9 hours.

### ISSUE THREAD

**Issue by nalvoks** [Nandaka/PixivUtil2#420]
### Prerequisites

* [x] Did you read FAQ section?
* [ ] Did you test with the latest releases or commit?
not yet.
I'm using 20180918.
I'll try after download is completed.

### Description

the timestamp of downloaded file is delayed by 9 hours.
I'm in Japan (UTC+9) and I think that's the reason.

### Steps to Reproduce

using PixivUtil2 with --startaction=4

**Comment by Nandaka** [comment]
It is stored in utc.
for example, https://www.pixiv.net/ajax/illust/69925083
https://github.com/Nandaka/PixivUtil2/blob/master/PixivModelWhiteCube.py#L234

I'm not sure if I should convert to local pc time? maybe can use something like https://stackoverflow.com/a/10854983

**Comment by nalvoks** [comment]
oh ok.
no problem if it's the intended behavior.

thanks.

**Comment by Nandaka** [comment]
I think in the web ui, it will be adjusted to the time zone based on your location in the profile settings?

For example:
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=70995384
Web shows October 3, 2018 6:09 AM
![image](https://user-images.githubusercontent.com/836867/46511590-1ba67e80-c882-11e8-8370-30197abd7778.png)
API shows 2018-10-02T22:09:47+00:00 (9h differences)
![image](https://user-images.githubusercontent.com/836867/46511636-44c70f00-c882-11e8-98cb-3cbe8171d2fe.png)

What is the date shown in your side (assuming your location is not set to tokyo/japan)?

**Comment by nalvoks** [comment]
the date shown in my side is

https://www.pixiv.net/ajax/illust/70850475
"createDate":"2018-09-24T09:36:51+00:00"

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=70850475
September 24, 2018 18:36

downloaded file
20180924 09:36:51

**Comment by nalvoks** [comment]
i forgot this.

70850475.txt
Date          = 09/24/18 09:36

**Comment by Nandaka** [comment]
I assume, you also setting the location to tokyo/japan? if not, then meaning the timestamp in the web page is always use japan as the time zone offset.

**Comment by nalvoks** [comment]
Yes. the location is set to Japan. and the system locale is also Japan.
but the timestamp of downloaded file is in UTC+00:00 time zone.

**Comment by Nandaka** [comment]
Ok, I checked, the web ui will follow based on the location you set for the time adjustment, but I cannot get the configuration.
I think I can set it based on local pc timezone if you want?

**Comment by nalvoks** [comment]
yes please.
