### ISSUE TITLE
[Request]Wish to opt out of certificate verification on a single connection

### ISSUE THREAD

**Issue by NeutronStarT** [Nandaka/PixivUtil2#427]
When I want to log in, the command line shows: 
Error at doLogin(): (<class 'urllib2.URLError'>, URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),), <traceback object at 0x0392A828>)
I think the reason is that I use Nginx Reverse Proxy & self-issued certificate to achieve Internet censorship circumvention.But a new feature was introduced after Python once upgraded.When an https link is opened with urllib.urlopen, an SSL certificate is verified.So could you opt out of certificate verification on a single connection.Thanks!

**Comment by awiebe** [comment]
Instead of bypassing check, you can provide your own certificate authority to requests.
`export REQUESTS_CA_BUNDLE=/path/to/your/certificate.pem`
