### ISSUE TITLE
Pixiv Fanbox not working

### ISSUE THREAD

**Issue by kthrowaway** [Nandaka/PixivUtil2#428]
### Prerequisites

 [*] Did you read FAQ section?
 [*] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

1.  Press F1 nothing happens, Press F2 and you get (Enter Char to Copy Up To) but somehow no matter what you press it doesn't register. Used on the latest release, as is except for typing in username and password in the .ini file

**Comment by NHOrus** [comment]
That's not button `F1`, that's literally you press `f` and then press `1`
Usually problem goes into different direction.

**Comment by kthrowaway** [comment]
oh ok, my bad, thanks that fixed it
