### ISSUE TITLE
SQLite3 Operational Error Disk I/O Error

### ISSUE THREAD

**Issue by JustAQuinn** [Nandaka/PixivUtil2#435]
### Prerequisites

* [ X] Did you read FAQ section?
* [releases/pixivutil20181105.zip] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

My PixivUtil2 is NOT covered by any sync or backup tool I am aware of.

Attempts to download image end in console logs stating the image was downloaded but due to a Disk I/O Error they could not be added to the sqlite3 database.

### Steps to Reproduce

If it matters, my DB is pretty big. It's about 45MB with over 173000 image entries. I know this because I used DB Browser for SQLite and opened my db.sqlite file.

1. Activate PixivUtil2
2. Use the '1' setting to get a new artist or the '2' setting to download a singular image.
3. Image is downloaded and placed in the directory. 
4. The program attempts to write it to the database.
5. An error log appears touting I/O errors.
6. Program fails, asking me to press any key to exit.

**Expected behavior:** [What you expected to happen]

PixivUtil20181105 - INFO -  done.

**Actual behavior:** [What actually happened]

PixivUtil20181105 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 859, in process_image
  File "PixivDBManager.pyc", line 496, in insertImage
OperationalError: disk I/O error

PixivUtil20181105 - ERROR - Error at process_image(): [Image Number]
PixivUtil20181105 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 867, in process_image
  File "PixivDBManager.pyc", line 509, in insertMangaImage
OperationalError: disk I/O error

### Versions
PixivUtil20180918 
PixivUtil20181105

The same thing happens if I try to compact it. When I tried to throw the DB.sqlite file out and start anew (after backing up), it failed with the same errors at file database creation.

Traceback (most recent call last):
  File "PixivUtil2.py", line 2171, in main
  File "PixivDBManager.pyc", line 55, in createDatabase
OperationalError: disk I/O error

**Comment by Nandaka** [comment]
Are you running multiple instance? Can you try to perform chkdsk on your harddisk? Can you try on other pc? Any antivirus blocking the write to db?
I can run it without error.

**Comment by JustAQuinn** [comment]
No.
It's an external, I'll try on another drive and report back.
Not immediately, no.
Nope.
I imagine so, otherwise everyone's databases would all be broken, but thanks for confirming it's just me.

**Comment by JustAQuinn** [comment]
Moved to another drive, it works. Just to be sure, I go back and try on the old drive without changing anything. Everything works fine now. Perhaps I just needed to restart my computer (and unmount and remount the drive).

Thanks for your help anyway, Nandaka. Stellar program.
