### ISSUE TITLE
can't not login 

### ISSUE THREAD

**Issue by sssodldo4404** [Nandaka/PixivUtil2#437]
![k-001](https://user-images.githubusercontent.com/44695906/48480170-ddbb5380-e84c-11e8-843f-18ad97b30fff.png)

> I can't enter my password manually

![k-003](https://user-images.githubusercontent.com/44695906/48480284-34289200-e84d-11e8-8a40-c546a7a45ce0.png)

> I wrote my ID and password on config.ini

![k-004](https://user-images.githubusercontent.com/44695906/48480346-64703080-e84d-11e8-865c-2fab49a0296c.png)

> The password is not applied to the screen and an error is displayed.

My current os is W10 RS5 64bit

The same symptoms occur when the vaccine is turned on or off.

**Comment by Nandaka** [comment]
use the cookie method, see on readme.txt for details

```
  Q3. I cannot login to pixiv!
      - Check your password.
      - Try to login to the Pixiv Website.
      - Try to use the config.ini on the [Authentication] section.
      - Check your date and time setting (e.g.: https://www.timeanddate.com/)
      - Disable Daylight Saving Time and try again.
      - Copy your session values from browser:
        1. Open Firefox.
        2. Go to Pixiv website and login, remember to enable [Remember Me]
           check box.
        3. Right click the page and select View Page Info.
        4. Click the Security tab.
        5. Click the View Cookies button.
        6. Look for Cookie named = PHPSESSID.
        7. Copy the content value.
        8. Open config.ini, go to [Authentication] section, paste the value
           to cookie, set keepsignedin = 1.
```

**Comment by sssodldo4404** [comment]
I've checked all the above, but I can't settle it.

![k-001](https://user-images.githubusercontent.com/44695906/48584633-98427780-e96d-11e8-9feb-ba5f33639797.png)
>(1)
![k-003](https://user-images.githubusercontent.com/44695906/48584647-9ed0ef00-e96d-11e8-8bb9-b14a3ab74e1e.png)
>(2)
![k-004](https://user-images.githubusercontent.com/44695906/48584654-a395a300-e96d-11e8-9349-6c2d08587975.png)
>(3)

**Comment by Nandaka** [comment]
1. If the cookie is given, password will not be used
2. Try to login using your username, not email (It shouldn't matter, just in case)
3. I notice you got the getaddrinfo failed, meaning it cannot resolve the pixiv ip address. Do you have any firewall that blocking the dns resolution?
4. Can you try on other pc?

**Comment by ShiroTora** [comment]
Nandaka , i have a problem, i reinstalled windows today and i use windows 10 enterprise
but i cant log in  pixiv with the prog 

https://cdn.discordapp.com/attachments/465470547476873228/596002597735759889/unknown.png

this is what i get
