### ISSUE TITLE
Fanbox: Unsupported post type: article

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#438]
### Prerequisites

* [ x] Did you read FAQ section?
* [x ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When PixivUtil2 meets fanbox post of a type "article", it shuts down.

### Steps to Reproduce
Start downloading Pixiv Fanbox pages.
Get to https://www.pixiv.net/ajax/fanbox/creator?userId=190026,  see post of a type article

**Expected behavior:** [What you expected to happen]

Either skip post or download images from post

**Actual behavior:** [What actually happened]

PixivUtil2 decides complains and asks for mercy kill

### Versions

20181105

Example ajax of a post of a type "article" attached

[post.txt](https://github.com/Nandaka/PixivUtil2/files/2590173/post.txt)

**Comment by Nandaka** [comment]
I notice there are `fileMap` and `embedMap` included in the sample json, do you know which article post containing those items?

**Comment by Nandaka** [comment]
You can try latest commit, note that `fileMap` and `embedMap` in article are not supported yet (need sample json).

**Comment by NHOrus** [comment]
I will try soon, will report when `fileMap` and `embedMap` appear.

Thank you,

**Comment by Nandaka** [comment]
Try latest commit, forgot to change in the main script

**Comment by NHOrus** [comment]
Solved, thank you very much!
