### ISSUE TITLE
[add info to readme.txt] Info on downloading FFmpeg (3rd party) to create Webm (or Gif)

### ISSUE THREAD

**Issue by tuffkirby** [Nandaka/PixivUtil2#440]
I saw that theres no info on where to get FFmpeg to make "createwebm" work. I know it said things about download FFmpeg in an error message but some people (like me) don't know where to get it. And if said people did get it, they could also not know where to put the file. There should be a guide like this:

Download ffmpeg: https://www.ffmpeg.org/download.html (get which ever version depending on what OS you are running)
Then open up the downloaded archive/zip file and there should be a folder called "ffmpeg-########-#######-win64-static" in the archive you've opened up. (the "#" are version numbers)
Go into that folder, then you should see a folder named "bin".
Now open up the "bin" folder and you should see an Application called, "ffmpeg.exe"
Next find and open up the PixivUtil2 Folder where ever you placed it in another explorer window.
And then lastly drag and drop the ffmpeg file mentioned earlier into the PixivUtil2 Folder.
Now the "createwebm" file should work.

**Comment by Nandaka** [comment]
The library should download it for you, but I'll update it anyway.
