### ISSUE TITLE
PixivUtil cannot find itself

### ISSUE THREAD

**Issue by byjtje** [Nandaka/PixivUtil2#442]
Sorry for the bother, I am not sure whether or not the error is specific to me, considering there are no other reports of it.
### Description
I installed all the required packages from requirements.txt and then used setup.py to install PixivUtil. However upon trying to use the PixivUtil2 command I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/PixivUtil2", line 11, in <module>
    load_entry_point('PixivUtil2==2018.11.0', 'console_scripts', 'PixivUtil2')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named PixivUtil2

```

### Steps to Reproduce

1. Install requirements
2. Install PixivUtil2
3. Try to call PixivUtil2

### Versions
 e079973

**Comment by Nandaka** [comment]
Not sure for non-windows installation, maybe @awiebe or @rachmadaniHaryono can help you?

worst case, try to run the script directly?

**Comment by NHOrus** [comment]
How do you start PixivUtil? I suspect that you start python then try to call it from python interpreter.

This is not intended method to run in, do `python2 PixivUtil2.py`

**Comment by awiebe** [comment]
I've never tried to install PixivUtil2, I just run it from script,it may be that it's not setup properly for the way you're invoking it.  There is a stack exchange post regarding this issue.
https://stackoverflow.com/questions/19718813/module-not-found-during-load-entry-point-in-python

**Comment by byjtje** [comment]
> How do you start PixivUtil? I suspect that you start python then try to call it from python interpreter.
With PixivUtil2 from the shell like it tells you in https://github.com/Nandaka/PixivUtil2/blob/master/setup.py#L43
> This is not intended method to run in, do `python2 PixivUtil2.py`
Yep that one works, thanks!

> I've never tried to install PixivUtil2, I just run it from script,it may be that it's not setup properly for the way you're invoking it. There is a stack exchange post regarding this issue.
> https://stackoverflow.com/questions/19718813/module-not-found-during-load-entry-point-in-python
I am following the setup.py linked above, but looking at the code of it above, it actually tells you to run it instead of installing, if you try to open run it with python3 https://github.com/Nandaka/PixivUtil2/blob/master/setup.py#L39

**Comment by Nandaka** [comment]
Python 3 is not supported btw, that's why it tell you to run using python2

**Comment by byjtje** [comment]
> 
> 
> Python 3 is not supported btw, that's why it tell you to run using python2

Ah yes I know, but I meant it tells you to run it with "python2  PixivUtil2.py" instead of installing + PixivUtil2

**Comment by awiebe** [comment]
> > Python 3 is not supported btw, that's why it tell you to run using python2
> 
> Ah yes I know, but I meant it tells you to run it with `python2 PixivUtil2.py` instead of installing + `PixivUtil2`

Yes, the windows version builds an executable using py2exe, but under *NIX there is no such procedure, thus once you have requirements in your environment or `venv`, you're good to go, but you have to run as you would a normal python script.  That is strictly speaking the only install procedure necessary and indeed currently possible on non windows machines is to get the necessary python packages and run without any fancy wrapping of the environment into a bundle.  

Depending on your configuration the exact location of your python may vary. ` PixivUtil2.py` has a shebang line so you should be able to run with just `./PixivUtil2.py`  provided `/usr/bin/python` is your python2 interpreter, otherwise, provide the interpreter explicitly.

**Comment by Cebtenzzre** [comment]
In a situation like this, it's standard practice to replace the shebang with `#!/usr/bin/python2` if you want to execute the script directly.  This is not an issue with PixivUtil2, as I'm sure the shebang it uses is generally correct.
