### ISSUE TITLE
cant download from pixivfanbox

### ISSUE THREAD

**Issue by kthrowaway** [Nandaka/PixivUtil2#443]
have a "Unsupported post type = article for post =" error

refer to log
![firefox_2018-11-20_04-19-23](https://user-images.githubusercontent.com/44362406/48732778-7f8ed600-ec7b-11e8-8a8b-845a9dac1e30.png)

**Comment by Nandaka** [comment]
Duplicated with https://github.com/Nandaka/PixivUtil2/issues/438.

The source code is updated, I just haven't create the compiled version yet.
