### ISSUE TITLE
Redownload Incomplete Images

### ISSUE THREAD

**Issue by occhep** [Nandaka/PixivUtil2#444]
### Description

Lately pixivutil has left a lot of incomplete images and when I enter the images ids it still won't download them. How should I fix this?

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

20181008

**Comment by Nandaka** [comment]
You can manually delete the image id from databases (enter 'd`, followed by `10`)
or 
You can set `alwaysCheckFileSize = True` and `verifyimage = True` in config.ini and retry the download.

Most likely you have unstable internet connection.

**Comment by occhep** [comment]
Will do that. Thank you.

**Comment by occhep** [comment]
Will do that. Thank you.
