### ISSUE TITLE
about Graphical interface

### ISSUE THREAD

**Issue by toyamarin** [Nandaka/PixivUtil2#446]
Does this program have a graphical interface?

**Comment by Nandaka** [comment]
you mean Pixiv Sketch? currently I don't have the plan to do pixiv sketch. Isn't it only for real time sharing?

**Comment by byjtje** [comment]
>Isn't it only for real time sharing?
Not only, you can also share pictures there

**Comment by Nandaka** [comment]
most likely no, the site is quite different and the artists id also different (no numeric like in pixiv).
