### ISSUE TITLE
Fanbox download suggestions

### ISSUE THREAD

**Issue by bluerthanever** [Nandaka/PixivUtil2#447]
Dear sir, 
First of all, thanks a lot for PixivUtil2, which offered so much convenience.

The version I use is 20181121.
The features are f1 - Download from supported artists (FANBOX) and f2 - Download by artist id (FANBOX), which I have a little problem with.

Not technically bugs but just a few suggestions.
1. While it runs into posts with unsupported article type, the whole program ends, with "press enter to exit", instead of like downloading other posts. Because sometimes there are a whole lot of other posts or artists to be downloaded.
2. Is there ways to like download texts from each post and save them in text files as what "writeimageinfo" does.

That's all. Thank you for your time and dedication in PixivUtil2. Many many thanks.

Rds.
Jacob

**Comment by Nandaka** [comment]
1. This is by design, so I can implement it for other type.
2. Can be done, might have a lot empty data though (esp. for image type post)

**Comment by bluerthanever** [comment]
Sorry for the late response. Do I need to confirm anything or reply to anything? Like saying "Yes, please add those features". Because I just noticed this "issue" is still open.
I personally find it really helpful, because sometimes there are some links or whatever that may matter in the posts' text, if it could be downloaded and saved as txt files, it would save a lot of time to gather the information in order to do some following work.
Thank you very much.

**Comment by Nandaka** [comment]
I means, is it for all kind of post type (so far I know we have "image", "text", "file", and "article").

Currently, it already parse the text data based on [text] or [blocks] node and store it to a variable:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivModelFanbox.py#L137
https://github.com/Nandaka/PixivUtil2/blob/master/PixivModelFanbox.py#L154

[text] node just plain old text (I think it doesn't have html node).
[block] node has html node for linking and embedding.

It should be easy to write those to a txt file or html file.

If you want, just say so 😄

**Comment by bluerthanever** [comment]
Ah, so I have just noticed. 
I am new to python, but I think I'll try to figure it out, to implement that.
Thank you very much.

**Comment by bluerthanever** [comment]
Hey. I just managed to download texts from fanbox posts.
Hmm, Made quite an effort though So happy right now.

**Comment by bluerthanever** [comment]
Do I need to post the varied codes, so maybe you can make some improvements add them to yours?

**Comment by Nandaka** [comment]
no need, I will add this on next releases.
Most likely I will reuse the `writeimageinfo` flag in config.ini to write out the text file.

**Comment by bluerthanever** [comment]
That's exactly what I did. =)
Thanks a lot, again.

**Comment by Nandaka** [comment]
code updated, but compiled program might take a while to upload (I'm travelling and the wifi is suck).

**Comment by Nandaka** [comment]
updated

**Comment by jrdp18** [comment]
Thank you for implementing this. But could you add that it can download posts that have no images?
I downloaded this which is mostly texts (novel) https://www.pixiv.net/fanbox/creator/32244225

**Comment by bluerthanever** [comment]
Hey. Sir.
Thanks for adding this feature. 

While using it, I found a tiiiiiiiiny "thing" I don't know how to call that, not a bug not a malfunction, just that when writing the txt files, there's a "_" at the end of the filename which is not wanted. And I added "appendExtension=False" to where "makefilename" was called and it was fixed. 

Didn't look further into that just good enough that it fixed my problem. Thinking maybe you wanna know.

**Comment by bluerthanever** [comment]
Hey, sorry for posting a lot of replies. Should have submitted once and for all.
I fount another little thing, or maybe it's just me, who might have a thing for sorting files.

In "PixvUtil2.py" at line 190x, where you implement the new feature, the "makefilename" method uses "__config__.filenameMangaFormat" as "nameformat", while at line 181x, where cover images are processed, "makefilename" is called as well, but uses "__config__.filenameFormat" as "nameformat".

Which is not a big deal, but in my case, I would prefer that the image info file save to where ALL the images are, whether they are mangas or not, Or at least, put all the images together, while the info file outside.

By the way, my file formats are as follows:
filenameformat = %member_id%\%image_id% - %title%
filenamemangaformat = %member_id%\%image_id%\%urlFilename% - %title%
filenameinfoformat = %member_id%\%image_id% - %title%

Than you very much. And have a good trip.

**Comment by bluerthanever** [comment]
Hey. Sir.
Thanks for adding this feature. 

While using it, I found 2 little problems for me, not exactly bugs nor malfunction. 
1. When writing the txt files, there's a "_" at the end of the filename which is not wanted. And I added "appendExtension=False" to where "makefilename" was called and it was fixed. 

2. In "PixvUtil2.py" at line 190x, where you implement the new feature, the "makefilename" method uses "config.filenameMangaFormat" as "nameformat", while at line 181x, where cover images are processed, "makefilename" is called as well, but uses "__config__.filenameFormat" as "nameformat".
Which is not a big deal, but in my case, I would prefer that the image info file save to where ALL the images are, whether they are mangas or not, Or at least, put all the images together, while the info file outside, in which case I think "__config__.filenameinfoformat" should be used as "nameformat". at line 190x in PixivUtil2.py.

By the way, my file formats are as follows:
filenameformat = %member_id%\\%image_id% - %title%
filenamemangaformat = %member_id%\\%image_id%\\%urlFilename% - %title%
filenameinfoformat = %member_id%\\%image_id% - %title%

Thank you very much. And have a good trip.

Didn't look further into that just good enough that it fixed my problem. Thinking maybe you wanna know.

**Comment by bluerthanever** [comment]
Hey. Sir.
Thanks for adding this feature. 

While using it, I found 2 little problems for me, not exactly bugs nor malfunction. 
1. When writing the txt files, there's a "_" at the end of the filename which is not wanted. And I added "appendExtension=False" to where "makefilename" was called and it was fixed. 

2. In "PixvUtil2.py" at line 190x, where you implement the new feature, the "makefilename" method uses "config.filenameMangaFormat" as "nameformat", while at line 181x, where cover images are processed, "makefilename" is called as well, but uses "__config__.filenameFormat" as "nameformat".
Which is not a big deal, but in my case, I would prefer that the image info file save to where ALL the images are, whether they are mangas or not, Or at least, put all the images together, while the info file outside, in which case I think "__config__.filenameinfoformat" should be used as "nameformat". at line 190x in PixivUtil2.py.

By the way, my file formats are as follows:
filenameformat = %member_id%\\%image_id% - %title%
filenamemangaformat = %member_id%\\%image_id%\\%urlFilename% - %title%
filenameinfoformat = %member_id%\\%image_id% - %title%

Thank you very much. And have a good trip.

**Comment by Nandaka** [comment]
@jdrp18: can you post me the result of this call, I don't have access to it. Save it as json/text file.
https://www.pixiv.net/ajax/fanbox/creator?userId=32244225
https://www.pixiv.net/ajax/fanbox/post?postId=296073 << replace with the post id.

@bluerthanever:
1. I'm reusing existing logic which require file url from normal image post (e.g. 1234_p0.png) for compatibility, so most likely I will keep it for now :P
2. Will change to filenameformat.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1906

**Comment by jrdp18** [comment]
Is this right? https://www.mediafire.com/?odfbhxfe81afizr

**Comment by bluerthanever** [comment]
Hmm. Ok. I got it. Guess I'll keep using my alteration for some time. 😀

**Comment by jrdp18** [comment]
Works good. I have a question though. Why is the image for [this](https://www.pixiv.net/fanbox/creator/32244225/post/124553) outside the folder?

```
filenameformat = %member_token% (%member_id%)\%image_id% - %title%
filenamemangaformat = %member_token% (%member_id%)\%image_id% - %title%\%page_number%
filenameinfoformat = %member_token% (%member_id%)\%image_id% - %title%
```

**Comment by Nandaka** [comment]
No idea, upload the log file here?

**Comment by jrdp18** [comment]
https://www.pixiv.net/fanbox/creator/32244225/post/124553
```
2019-03-19 17:13:16,003 - PixivUtil20190319 - DEBUG - Sanitized Filename: \inori_narou (32244225)\124553 - 「悪役令嬢が妙に優しい。」について.jpeg
2019-03-19 17:13:16,007 - PixivUtil20190319 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/32244225/post/124553
2019-03-19 17:13:16,351 - PixivUtil20190319 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/32244225/post/124553
2019-03-19 17:13:17,141 - PixivUtil20190319 - INFO -  done.
2019-03-19 17:13:17,141 - PixivUtil20190319 - INFO - No Image available in post: 124553.
2019-03-19 17:13:17,142 - PixivUtil20190319 - DEBUG - Sanitized Filename: \inori_narou (32244225)\124553 - 「悪役令嬢が妙に優しい。」について\_
2019-03-19 17:13:17,144 - PixivUtil20190319 - INFO - Creating directory: \inori_narou (32244225)\124553 - 「悪役令嬢が妙に優しい。」について
```
Compare to https://www.pixiv.net/fanbox/creator/32244225/post/289167 which has an image inside the folder.
```
2019-03-19 15:19:50,721 - PixivUtil20190319 - INFO - No Cover Image for post: 289167.
2019-03-19 15:19:50,723 - PixivUtil20190319 - DEBUG - Sanitized Filename: \inori_narou (32244225)\289167 - 「わたおし。」最終章更新の告知と★書籍化★のご報告。\1.jpeg
2019-03-19 15:19:50,729 - PixivUtil20190319 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/32244225/post/289167
2019-03-19 15:19:51,585 - PixivUtil20190319 - INFO - 	No file size information!
2019-03-19 15:19:51,588 - PixivUtil20190319 - INFO - Using Referer: https://www.pixiv.net/fanbox/creator/32244225/post/289167
2019-03-19 15:19:52,257 - PixivUtil20190319 - INFO - 	No file size information!
2019-03-19 15:19:52,259 - PixivUtil20190319 - INFO - Creating directory: \inori_narou (32244225)\289167 - 「わたおし。」最終章更新の告知と★書籍化★のご報告。
2019-03-19 15:19:55,730 - PixivUtil20190319 - INFO -  done.
2019-03-19 15:19:55,733 - PixivUtil20190319 - DEBUG - Sanitized Filename: \inori_narou (32244225)\289167 - 「わたおし。」最終章更新の告知と★書籍化★のご報告。\_
```
Both are public posts.

**Comment by bluerthanever** [comment]
I guess that's because, as I have mentioned above, when processing cover images, the "makefilename" method uses "filenameformat" as "nameformat"
Post 124553 has only one cover image, which was saved with filenameformat, while the image in post 289167 is not cover image but inside the content.

**Comment by Nandaka** [comment]
and I think I still forgot to change the filenameMangaFormat to filenameformat
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1906

**Comment by Nandaka** [comment]
and I think I still forgot to change the filenameMangaFormat to filenameformat
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1906

**Comment by bluerthanever** [comment]
LOL. Maybe I shouldn't have written too much that you missed the point.

**Comment by usaradark** [comment]
Is there any way to differentiate between normal pixiv images and fanbox images?

**Comment by Nandaka** [comment]
downloaded file? unless you include `%urlFilename%`, then most likely no.

Fanbox  `%urlFilename%` has additional random string like mypic images

**Comment by Nandaka** [comment]
@bluerthanever should use `filenameinfoformat` instead of `filenameformat`. 

I think I need to reorganize the config.ini

**Comment by bluerthanever** [comment]
ah, sorry. because my filenameformat and filenameinfoformat are basically the same...
sorry.
