### ISSUE TITLE
can't find followed users: piviv_master_member empty

### ISSUE THREAD

**Issue by secretuser** [Nandaka/PixivUtil2#453]
I tried finding all users that I followed, but show all members was empty, export list of said members was also empty, so I tried looking into the sqlite db and the pixiv_master_member was also empty. 
Is this the intended behavior or is my member list never updated for some reason?
I am trying to download a list of all users I followed on pixiv.

thank you in advance

**Comment by Nandaka** [comment]
it is populated using based on list.txt

**Comment by whinette** [comment]
You can export list of bookmarked users from pixivutils (option `e`).
You can also just list your download folder if it is structured.
