### ISSUE TITLE
"[Feature request] Dealing with artist name changes"

### ISSUE THREAD

**Issue by sanselon** [Nandaka/PixivUtil2#456]
Is there a way to consolidate the content of an artist into one folder? Somehow after every username change, PixivUtil2 creates a new folder and puts the new content in that folder.

One option would be to use the user number as reference?

Thank you for your feedback and keep up the good work

**Comment by NHOrus** [comment]
Yes. I use

```
[Settings]
filenameformat = %member_id%/%image_id% - %title%
filenamemangaformat = %member_id%/%image_id%_%page_index% - %title%
filenameinfoformat = %member_id%/%image_id% - %title%
```

**Comment by whinette** [comment]
I made a python script that does that, but tailored for my needs.
https://gist.github.com/whinette/a46ccb980d93ee8189c2c6629a7e2e4c

**Comment by JAK0723** [comment]
Is it possible to do it in such a way that the artist's name is still used? I can't really recognise an artist just by their ID number.

@whinette I looked at your script and I'm not completely sure I understand it. Does it still work properly if you don't download files directly to the 'PixivUtil2' folder, such as when you change the `rootdirectory` setting?

@Nandaka I think it might be better if this issue had a more informative title such as "[Feature request] Dealing with artist name changes".

**Comment by Nandaka** [comment]
@JAK0723 changed, also try to use `%member_token%` for the filename format if you still want something readable, it still might changed but unlikely (pixiv id). Check the readme.txt for more details on the filename format.

**Comment by JAK0723** [comment]
@Nandaka the readme does explain how to use it, but what is a member token, exactly?

**Comment by whinette** [comment]
@JAK0723 you only have to run it in your root folder, but your structure have to be exactly like mine (I added a comment on how I setted it up).
If it's not (and it won't), you can't run it as is.

**Comment by Nandaka** [comment]
Pixiv ID
![image](https://user-images.githubusercontent.com/836867/50867700-0c861e00-13e7-11e9-9df9-387c1f77071f.png)
