### ISSUE TITLE
Readable error message for no connection

### ISSUE THREAD

**Issue by photonometric** [Nandaka/PixivUtil2#458]
Latest build v20190108 on Windows 7 Ultimate (but long-standing behavior)

Just a small suggestion, but this issue tricks me once or twice a year, when installing a new version. If internet is down or firewall rule creator is slow, the program returns the following error message (after opening text and config creation:
```
> 1 2 3 4
> 1 2 3 4
> 1 2 3 4
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 2323, in <module>
>   File "PixivUtil2.py", line 2177, in main
>   File "PixivHelper.pyc", line 907, in check_version
>   File "PixivBrowserFactory.pyc", line 152, in open_with_retry
> PixivException.PixivException: 9005 Failed to get page: , hasDumpPage=N
```
Nothing in this suggests a connection error, so I usually come here and start checking issues to see if the build has problems. 

I wonder, if this error (or the presence of the error at startup) is constant, **perhaps it could simply be replaced by a more (non-programming) human-friendly message about connection error**. Or perhaps a sentence with a few "error could be caused by...." suggestions, if this same error can have other causes.

Possibly related to #237, though apparently with a different error message output; I'd suggest that long sting of errors could be replaced by a similar human-readable message, if possible. ^_^

**Comment by Nandaka** [comment]
Maybe I can change message for that specific line became `Failed to get page, check your internet connection/firewall/antivirus`?
https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L152

**Comment by photonometric** [comment]
That would help a bit for clarifying it could be a connection issue (as long as that 9005 exception isn't used for other cases e.g. pixiv API errors). Though in this example of the error on program startup, no "page" has been requested, so even that line is a bit puzzling. If this exception is used elsewhere for loading errors that *might not* be a connection error (and the "failed to get page" message makes sense enough to keep), perhaps the message could be changed just for when this appears directly at startup?

Re-reading the error message I quoted, I think what is much more incongruous is the debug code. Whatever the casual message is, if it's preceded by 5 lines of errors referring to python files and line numbers, **the overall result is the impression "hmm, I guess there's a coding/API error."** Especially for those of us with no/only basic programming skills. And especially since all the other errors I see in the program have been smoothed out, so throwing python errors as soon as the program starts looks much more serious than a mere connection problem.

Perhaps the whole message could simply be streamlined to a single "human readable" (or rather, "non-programmer relevant") message like you suggested?

**Comment by Nandaka** [comment]
the full stack is used for easier troubleshotting, as usually no log file being uploaded. At least I can see the problem from the screenshot 😛 

I will change that specific error, as it is related to the internet connection error.
