### ISSUE TITLE
WebM feature broken

### ISSUE THREAD

**Issue by HydroHydro** [Nandaka/PixivUtil2#459]
### Prerequisites

* [Yes ] Did you read FAQ section?
* [ Yes] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

Webm worked perfectly until the newest version. Now, webm files only show black.

For example, https://www.pixiv.net/member_illust.php?mode=medium&illust_id=72620468

I get this: https://mega.nz/#!2uZCQazD!Py0uWT1GiHavtiFGdXyg8uwYAUGNpZGpkoin5kuT_jY

**Comment by Nandaka** [comment]
what is the configuration?

Ensure the config is correct, as some changes in the config.ini structure (check the release notes).

Sample configuration
`

[FFmpeg]
ffmpeg = ffmpeg
ffmpegcodec = libvpx-vp9
ffmpegparam = -lossless 1 -vsync 2 -r 999
webpcodec = libwebp
webpparam = -lossless 0 -q:v 90 -loop 0 -vsync 2 -r 999

[Ugoira]
writeugoirainfo = False
createugoira = True
deletezipfile = True
creategif = False
createapng = False
deleteugoira = False
createwebm = True
createwebp = True
`

**Comment by HydroHydro** [comment]
This is what I have in my config:

[FFmpeg]
ffmpeg = ffmpeg
ffmpegcodec = libvpx-vp9
ffmpegparam = -lossless 1
webpcodec = libwebp
webpparam = -lossless 0 -q:v 100 -loop 0 -vsync 2 -r 999

[Ugoira]
writeugoirainfo = False
createugoira = True
deletezipfile = False
creategif = False
createapng = False
deleteugoira = False
createwebm = True
createwebp = False

**Comment by Nandaka** [comment]
I can playback the downloaded file from MEGA using MPC-HC, but not using VLC.

**Comment by HydroHydro** [comment]
Strange...

I also tried playing the webm file in Chrome. Still black. Of all things, shouldn't Chrome be able to play it correctly?

**Comment by Nandaka** [comment]
tested with previous version, it produce the same result (black frame in vlc and chrome).

Tested with different ugoira (72165291, **NSFW**) I can play the videos in MPC, VLC and Chrome.

I think it is related to the original ugoira file (resolution/fps)?

**Comment by Nandaka** [comment]
ok, found out the issue. Need to add `-pix_fmt yuv420p` to the ffmpeg parameter.

```[FFmpeg]
ffmpeg = ffmpeg
ffmpegcodec = libvpx-vp9
ffmpegparam = -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p
webpcodec = libwebp
webpparam = -lossless 0 -q:v 90 -loop 0 -vsync 2 -r 999
```

https://stackoverflow.com/a/24468585
