### ISSUE TITLE
Download new illust pages limited?

### ISSUE THREAD

**Issue by occhep** [Nandaka/PixivUtil2#460]
It's occured to me that the download new illustrations from following members (key 8) always ends at page 100. Is this intentional or just a bug? Please help.

**Comment by Nandaka** [comment]
It is limited to 100 pages from pixiv.
![image](https://user-images.githubusercontent.com/836867/51158504-bec65580-18bf-11e9-9328-6b31e521079e.png)

**Comment by occhep** [comment]
I see, thank you.
By the way, is there any way to make PixivUtil remember what it was doing last time and continue next time?

**Comment by occhep** [comment]
Thank you, and please keep up the good work.
