### ISSUE TITLE
When artists update their drawings

### ISSUE THREAD

**Issue by occhep** [Nandaka/PixivUtil2#462]
So I have noticed that if artists update/add more pictures to one they previously uploaded, it will still be treated as downloaded by pixivutil and the new pictures will not be downloaded. Is there a way to fix this?

**Comment by Nandaka** [comment]
set `alwaysCheckFileSize = True` in config.ini

**Comment by Nandaka** [comment]
from readme.txt

```
verifyimage     ==> Do image and zip checking after download. Set the value to
                    True to enable.
alwaysCheckFileSize   ==> Check the file size, if different then it will be
                          downloaded again, set 'False' to disable.
 		          This will override the image_id checking from db
                          (always fetch the image page for checking the size)
```

**Comment by occhep** [comment]
Sorry, should've noticed there is the readme. Thanks a lot.
