### ISSUE TITLE
Download by member_id  cannot retrieve proper member info

### ISSUE THREAD

**Issue by Extremezhazha** [Nandaka/PixivUtil2#463]
Latest build 20190120 running from source code on linux

Download stops after 4th page, while total pages are 36.

After debugging, I found that the ajax retrieval only gets result as if the user didn't log in, with a short illust list (probably excluding r-18 works) and I suspect that it was cookie handling that makes this issue, since accessing the https://www.pixiv.net/ajax/user/{0}/profile/all
with the browser gives the correct illust list.

**Comment by Extremezhazha** [comment]
Currently I made a workaround by forcing retrieving the ajax user profile read from a json file I saved from the actual web browser. So once the cookie handling issue is resolved, everything should work just fine.

**Comment by Nandaka** [comment]
Try this method from readme.txt
```
  Q3. I cannot login to Pixiv!
      - Check your password.
      - Try to login to the Pixiv Website.
      - Try to use the config.ini on the [Authentication] section.
      - Check your date and time setting (e.g.: https://www.timeanddate.com/)
      - Disable Daylight Saving Time and try again.
      - Copy your session values from browser:
        1. Open Firefox.
        2. Go to Pixiv website and login, remember to enable [Remember Me]
           check box.
        3. Right click the page and select View Page Info.
        4. Click the Security tab.
        5. Click the View Cookies button.
        6. Look for Cookie named = PHPSESSID.
        7. Copy the content value.
        8. Open config.ini, go to [Authentication] section, paste the value
           to cookie, set keepsignedin = 1.
```

**Comment by Extremezhazha** [comment]
Turned out it was my mistake. Sorry for the confusion.
