### ISSUE TITLE
Directory changed, need help with database and changing it back

### ISSUE THREAD

**Issue by Reothe** [Nandaka/PixivUtil2#464]
Version: 20190108
I am running from source code on Windows 10 and have been letting the program download by bookmarked artists. All of the folders for each member were going into the pixivutil folder I have which is what i wanted but just recently all the downloads started going to my own User folder. I am not very good with using these types of programs and I want to have the files go back to installing in the folder they were before (pixivutil).

In addition to fixing that, if i change the directory will the pictures that were in the wrong directory reinstall to the folder I want (i want them to reinstall as I deleted the ones in the wrong folder), or do I have to do something to make it think it is the first time it is getting the picture from pixiv?

**Comment by Nandaka** [comment]
You can move the downloaded files to the new folder, ensure `overwrite = False` in config.ini. It should skip the downloaded files, assuming the filename format doesn't change.

Else, you can open the sqlite.db using Sql Lite Browser and change the stored savedpath manually using SQL.

**Comment by Reothe** [comment]
I have opened sqlite.db using Sql Lite Browser but I do not know how to change the stored save path manually using SQL

**Comment by Nandaka** [comment]
You need to use SQL command to issue UPDATE statement.
I think it is easier for you to just relocate the files and let the application to check if there is already downloaded files.

**Comment by Reothe** [comment]
I am still trying to download by bookmarked artist and I am still running version 20190108

I took your advice and just let it download the picture folders into my user folder and relocate them later, it seems like it is trying to change the directory on me again? But this time to system32 and its getting denied (certainly dont want it to start downloading all the pictures there). Is there a way to get it to change the directory to something else again, it seems pretty random, might just have to learn how to work with SQL.

> Creating directory: C:\WINDOWS\system32\むーらん＠2日目あ-35b (9930155)
Traceback (most recent call last):
  File "C:\pixivutil\PixivUtil2.py", line 255, in download_image
    (downloadedSize, filename) = perform_download(url, file_size, filename, overwrite, referer)
  File "C:\pixivutil\PixivUtil2.py", line 359, in perform_download
    (downloadedSize, filename) = PixivHelper.downloadImage(url, filename, res, file_size, overwrite)
  File "C:\pixivutil\PixivHelper.py", line 587, in downloadImage
    makeSubdirs(filename)
  File "C:\pixivutil\PixivHelper.py", line 578, in makeSubdirs
    os.makedirs(directory)
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: u'C:\\WINDOWS\\system32\\\u3080\u30fc\u3089\u3093\uff202\u65e5\u76ee\u3042-35b (9930155)'
Error at download_image(): (<type 'exceptions.WindowsError'>, WindowsError(5, 'Access is denied'), <traceback object at 0x000000000C8428C8>) at https://i.pximg.net/user-profile/img/2018/12/18/19/38/59/15145685_55f2a3e6e594f17e8ec4d9ca793c1699.png (9000)
Retrying [1]... 1 2 3 4

>

**Comment by Nandaka** [comment]
How do you run the script?? What is your config.ini file??

I run the script from it's own folder and it should not resolve to system32 unless you told the script to run there.
