### ISSUE TITLE
Download from list(list.txt). member_id not save into SQLite pixiv_master_member

### ISSUE THREAD

**Issue by yhtojy** [Nandaka/PixivUtil2#465]
v20190120

When using "4. Download from list"
The member_id downloaded won't save into SQLite pixiv_master_member.

The program only save member_id from list.txt at startup like below.
> Creating database... done.
> Importing list... Found 150 items done.
> Updated 150 items.

I need to reopen the program for member_id(those using "4. Download from list") to correctly save into SQLite pixiv_master_member.

**Comment by Nandaka** [comment]
it is by design

**Comment by Nandaka** [comment]
duplicate with https://github.com/Nandaka/PixivUtil2/issues/453
