### ISSUE TITLE
Add sorting order for download by image bookmark

### ISSUE THREAD

**Issue by Latias4Ever** [Nandaka/PixivUtil2#468]
Is it possible to add the downloaded image's number to the filename when downloading? This would be helpful in keeping downloaded bookmarks in the same order as they're downloaded. To explain what I'm asking: "Image # 1" adds "1" to the file name, "Image # 2" adds "2" to the file name, and so forth.

However since the download goes from the last bookmark to the first, I also want to ask if there's a way to do it backwards, so a user with 10 bookmarks has "Image # 1" getting "10" on the file name, "Image # 2" getting "9", and so forth. This would make it so any new bookmarks don't end up having the same number as previously downloaded images. I'm not sure if it's possible to do calculations through the filename, but subtracting a user's number of bookmarks with the image number would work for this second suggestion.

This might sound convoluted, but perhaps some users would prefer to have their downloaded bookmarks appearing in the same order as on the site, instead of having them all mixed around.

**Comment by Nandaka** [comment]
Sort by file creation date/last modified date?

**Comment by Latias4Ever** [comment]
That works but only for the first download, any downloads after that would cause the pictures to lose their order since there's no way to download from the last picture of the last page to the first picture of the first page.

**Comment by Nandaka** [comment]
Use `setlastmodified = True` in config.ini.

This will update the last modified date attribute based on the post works date/time, rather than the download date/time.

**Comment by Latias4Ever** [comment]
Won't that just have the same effect as sorting by name? It still won't allow one to download all their bookmarks and keep them in the same order as shown on the site when sorted by last bookmarked.

Basically, a user bookmarks 10 images, those images are shown in a certain order (from 10th to 1st). Sorting by creation date works for this, but only the first time. If the user bookmarks another 10, the order after the second download (when sorted by creation date) would be 10 to 1, and then 20 to 11, instead of 20 to 1. Having a way to set the number of the image that's being downloaded to the filename would make this easier.

**Comment by Nandaka** [comment]
When I talk about last-modified setting in config.ini, I'm talking about this date:
![image](https://user-images.githubusercontent.com/836867/52914511-309d1f00-3304-11e9-88df-1adcbf8460f2.png)
![image](https://user-images.githubusercontent.com/836867/52914531-73f78d80-3304-11e9-862b-84eabb92144f.png)

If you enable that, isn't it has the same effect with sort by date ascending/descending?
![image](https://user-images.githubusercontent.com/836867/52914541-9f7a7800-3304-11e9-8b98-155be78d25b1.png)

**Comment by Latias4Ever** [comment]
Yes, however the order I'm talking about is the "Sort bookmarks" order. Sorting by date simply sorts by the posts' IDs, and I can order those by the default filename, that one isn't an issue.

**Comment by Latias4Ever** [comment]
I know the issue has been inactive for two months now, but I was hoping that the option I suggested to download the bookmarks in reverse order. Considering the get_image_bookmark function has the bookmark URL already, it'd be simple enough to make a similar function with the "https://www.pixiv.net/bookmark.php?rest=show&order=asc&p=" URL instead. I know it's mostly unnecessary, but I'd like to have my downloaded bookmarks in the same order as in the site.
