### ISSUE TITLE
Program unexpectedly quit right after start.

### ISSUE THREAD

**Issue by b000408** [Nandaka/PixivUtil2#469]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.

**Comment by b000408** [comment]
Open up the files and it shows 

ERROR - Error at loadConfig()

I guess there must be somthing wrong with my environment setting since it crashed after several succeesful run.

**Comment by Nandaka** [comment]
You can try to delete the config.ini file to reset the config, or upload the `pixivutil.log` file here.

**Comment by tyrexforlife** [comment]
I changed directory from Disk E (usb HDD) to Disk C and that worked
