### ISSUE TITLE
Fanbox: embedMap crash

### ISSUE THREAD

**Issue by CtahSaot** [Nandaka/PixivUtil2#470]
Hello,

PixivUtil2 crashes with the following error:

Getting posts from https://www.pixiv.net/ajax/fanbox/creator?userId=68813
Unsupported article node = embedMap for post = 285502
press enter to exit.

I've only found reference about embedMap in this post https://github.com/Nandaka/PixivUtil2/issues/438#issue-381681748 

The problem seems to persist with embedMap, though.

**Comment by Nandaka** [comment]
Can you upload the json file for https://www.pixiv.net/ajax/fanbox/creator?userId=68813 for the embedMap data?

**Comment by CtahSaot** [comment]
[creator.json.txt](https://github.com/Nandaka/PixivUtil2/files/2889492/creator.json.txt)
Here we go. 

Thanks!
