### ISSUE TITLE
UTF-8 BOM in PixivUtil2.py breaks shebang

### ISSUE THREAD

**Issue by Cebtenzzre** [Nandaka/PixivUtil2#473]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

PixivUtil2.py has a shebang and is marked executable, but this does not work very well because it starts with a byte-order mark.  On most Unix-y systems, `#!` must be the first two bytes of a shebang.  Byte-order marks, while technically valid, are not very common in UTF-8 outside of Windows.

```
$ chardetect PixivUtil2.py
PixivUtil2.py: UTF-8-SIG with confidence 1.0
$ xxd PixivUtil2.py | head -1
00000000: efbb bf23 212f 7573 722f 6269 6e2f 7079  ...#!/usr/bin/py
```

Notice that the encoding is not just `UTF-8`, and that the file begins with the bytes `ef bb bf`, followed by its actual content.

This file has started with a BOM since commit b0367ff, as well as a few others.
The ideal fix would be to remove the BOM from all `.py` files, which could be automated with sed.

### Steps to Reproduce

1. Execute `PixivUtil2.py` directly (`./PixivUtil2.py`)

**Expected behavior:** It is executed with the Python interpreter.

**Actual behavior:** At least in bash or zsh, it is executed with the Bourne shell (`/bin/sh`), which fails pretty quickly since it doesn't understand Python.

### Versions
`PixivDownloader2 version 20190301`

**Comment by Nandaka** [comment]
I'm using Win10 + VSCode/PyScripter for the IDE.

Not sure if those editor automatically insert the BOM header.

**Comment by NHOrus** [comment]
Sorry @Cebtenzzre, should have seen the problem, but I usually start pixivutil on linux with python2.7 directly - joys of having a system with python being python3 interpreter.

I will make a PR of a version without BOM a bit later.

**Comment by Cebtenzzre** [comment]
@NHOrus python is the python3 interpreter on my system too. I've just gotten used to changing shebangs when I download python scripts.
