### ISSUE TITLE
[BUG?]About maximum page for fanbox posts.

### ISSUE THREAD

**Issue by bluerthanever** [Nandaka/PixivUtil2#478]
### Prerequisites

* [ yes ] Did you read FAQ section?
* [ yes ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

While downloading fanbox posts, "max page" didn't work

### Steps to Reproduce

1. Input "f1" or "f2" to download fanbox posts
2. input the number for "max page"
3. the program would continue downloading all the posts, ignoring the "max page"

**Expected behavior:** the program stops after reaching "max page"

**Actual behavior:** continues until the very last page

### Versions
20190401

You can get this information from executing `PixivUtil2.py --help`.

I think error happens here:
https://github.com/Nandaka/PixivUtil2/blob/803676c0dd48a2ca9831cb4c55a42fb540eb628f/PixivUtil2.py#L1856
because when I print the "current_page" and "end_page", the output numbers are correct, but the program just doesn't get into the "if" codes. So I add "int()" around the 2 parameters and this very "bug" gets fixed, but throwing other exceptions like if you input characters or letters when "max page" is asked of.
Not sure why nobody else raises this, maybe it's because of the running environment?

**Comment by Nandaka** [comment]
You right, I forgot to cast it to int when asking for the input.
https://github.com/Nandaka/PixivUtil2/blob/803676c0dd48a2ca9831cb4c55a42fb540eb628f/PixivUtil2.py#L1930
https://github.com/Nandaka/PixivUtil2/blob/803676c0dd48a2ca9831cb4c55a42fb540eb628f/PixivUtil2.py#L1790

**Comment by NHOrus** [comment]
Now it panics if you put empty value.  
Maybe empty Max Page should be "Run until no more pages"?

**Comment by Nandaka** [comment]
updating to set the default to 0 if no value given, might need to ask you to test :smile:

**Comment by bluerthanever** [comment]
thanks. noticed the changes in the code.
