### ISSUE TITLE
[Behavior] What happens when app downloads image that already exists?

### ISSUE THREAD

**Issue by maslos** [Nandaka/PixivUtil2#479]
Lets say i set up filename to %artist% - %title%, so what happens when there are multiple images with same name from exact same artist? 
Does app overwrite files with same names, skips it or adds some numeration?
Thank you for this great app and for reply in advance.

**Comment by Nandaka** [comment]
from readme,txt, you can change the overwrite in config.ini, else it just skip it.

`overwrite      ==> Overwrite old files, set 'False' to disable`

**Comment by maslos** [comment]
Thanks
So if i want to download files with similar names its better to use %image_id% to be sure nothing sis skipped right?
So how about an option to specify behavior what to do when encountering already existing file? Like adding a number at the end of filename?

**Comment by Nandaka** [comment]
Yep.

For existing file, you can try to enable this settings.
```backupOldFile   ==> Set to True to backup old file if the file size is different.
                    Old filename will be renamed to filename.unix-time.extension.```

or use add this to the filename format
```%date%
   Current date in YYYYMMMDD format.
-> %date_fmt{format}%
   Current date using custom format.
   Use Python string format notation, refer: https://goo.gl/3UiMAb
   e.g. %date_fmt{%Y-%m-%d}%
```

**Comment by maslos** [comment]
ok, thanks, ill try that
