### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Disposablegloves** [Nandaka/PixivUtil2#482]
Started having errors recently and I can't seem to download any images. I've tried with both member_id and image_id for the same artist, same error. Was working when last used less than a week ago. Doesn't seem to matter if it's a single or multi page.

> Input: 2
Image ids: 69287623
Processing Image Id: 69287623
Member Name  : あづち涼
Member Avatar: https://i.pximg.net/user-profile/img/2018/05/19/20/03/07/14249162_933effdd8cc3f893c165376cc1a2f0ea.jpg
Member Token : komesama
Member Background : no_background
Title: 「ふふっ」漫画　その９
Tags : 漫画
Date : 2018-06-17 23:16:37+00:00
Mode : manga
Page Count : 2
Image URL : https://i.pximg.net/img-original/img/2018/06/18/08/16/37/69287623_p0.jpg
Filename  : D:\Tools\Pixiv Util\Dump\あづち涼 (643275)\69287623_p0 - 「ふふっ」漫画　その９.jpg
Traceback (most recent call last):
  File "PixivUtil2.py", line 768, in process_image
TypeError: 'NoneType' object is not iterable
Error at process_image(): 69287623
Exception: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object is not iterable",), <traceback object at 0x03651AA8>)
Dumping html to: Error medium page for image 69287623.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 2285, in main
  File "PixivUtil2.py", line 2020, in main_loop
  File "PixivUtil2.py", line 1503, in menu_download_by_image_id
  File "PixivUtil2.py", line 768, in process_image
TypeError: 'NoneType' object is not iterable

### Versions

version 20190416

**Comment by Nandaka** [comment]
Can you upload the file: Error medium page for image 69287623.html

**Comment by Disposablegloves** [comment]
I can open the page through my browser, but not through the html file

[Error medium page for image 69287623.zip](https://github.com/Nandaka/PixivUtil2/files/3101215/Error.medium.page.for.image.69287623.zip)

**Comment by Nandaka** [comment]
can you upload the log file too? Try to delete the old one and rerun with the problem image then upload it here. Also upload the config.ini too (remember to remove the Authentication section).

**Comment by Disposablegloves** [comment]
Sorry, it took me a while to reply. I've tried downloading things again today and it seems like I'm not getting the error on the OP anymore, but I am getting the same OAuth on the other issue thread. #483 

I'll close this issue now so you can focus on the other one.
