### ISSUE TITLE
Some configurations have incalid values after every update

### ISSUE THREAD

**Issue by anon1593** [Nandaka/PixivUtil2#486]
### Prerequisites

* [ ] Did you read FAQ section?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.

As the title says, after update files are copied over and the program is started it tells me about invalid configs before resetting several settings.
Settings include:
 DaysLastUpdated
RootDirectory
All Ugoira settings
Has happened on 2 machines running windows 10
Version-v20190429-beta4

Reading C:\Users\jwsteed\Desktop\pixivutil\config.ini ...
Error at loadConfig(): (<class 'ConfigParser.NoSectionError'>, No section: 'Filename', <traceback object at 0x0443F418>)
Some configuration have invalid value, replacing with the default value.
Writing config file... Backing up old config (error exist!) to config.ini.error-1556585889

Computer won't save screenshots

**Comment by Nandaka** [comment]
some config is moved to it's own section, I will update the readme.

![image](https://user-images.githubusercontent.com/836867/56938498-f25a8200-6b34-11e9-97de-e43a3d2859c9.png)

**Comment by bnick23** [comment]
Could you please update the readme with an explanation of the new "refresh_token" option under "Authentication" in the config? Thank you

**Comment by photonometric** [comment]
When upgrading, I load old and new (blank generated) config files side-by-side in notepad++ tabs (could be windows notepad or more advanced textdiff program too). Then PgDwn or scrollbar-click once in each file. Any visual mismatch makes immediately apparent that an element has been added/moved/removed/altered.

Such an alteration happens only every few months, but seems to me a necessary precaution before copying config from a deprecated version.
