### ISSUE TITLE
Infinite loop when no image

### ISSUE THREAD

**Issue by Seeker320** [Nandaka/PixivUtil2#488]
I have many members in my database. Some of them apparently removed their art from pixiv. When I chose to download from list (option nr. 4) and the member in the list has no pictures anymore instead of moving to the next member it gets stuck in an infinite loop. That didn't happen before.
Can that be fixed? I don't want to remove the members from the database, on the off chance that they decide to start uploading art again. And the program won't resume unless I stop it, remove them manually and run it again.
You can test it for instance with user 3157.

**Comment by Nandaka** [comment]
Related to #483 

Can you manually update library.zip to include the cacert.pem in the certifi folder?
You can get it from https://raw.githubusercontent.com/certifi/python-certifi/master/certifi/cacert.pem

**Comment by Seeker320** [comment]
> Related to #483
> 
> Can you manually update library.zip to include the cacert.pem in the certifi folder?
> You can get it from https://raw.githubusercontent.com/certifi/python-certifi/master/certifi/cacert.pem

Of course! Done and it's working. Thanks a lot!
