### ISSUE TITLE
PixivUtil2 closes itself randomly when downloading mangas since update

### ISSUE THREAD

**Issue by elreymu** [Nandaka/PixivUtil2#489]
When i download by bookmarks, the program closes itself at random when downloading a manga/gallery if i try to download again it doesn't close on the same manga and downloads sucessfully but after that it may close by itself again downloading another manga, happens everytime on a different manga each time since i updated pixivutil
The log doesn't show any errors

**Comment by Nandaka** [comment]
Not even in the pixivutil.log? Check your loglevel in config.ini and set it to DEBUG.

If still no error generated, try to run it in from cmd (don't double click it), so at least it will show the last message.

**Comment by elreymu** [comment]
Loglevel is already in DEBUG
when it happens, at the end of the log there's just the ID to the image itself
i just confirmed it happens to either a normal image or a gallery.
i can happen randomly on any image it seems.
This time i ran the program from cmd, it ran for a while, then it stopped with no error and returned to cmd.

These is the last line in the log
2019-05-05 23:31:54,529 - PixivUtil20190501b - INFO -  done.
2019-05-05 23:31:55,538 - PixivUtil20190501b - DEBUG - Getting image page: 64784187
2019-05-05 23:31:56,286 - PixivUtil20190501b - DEBUG - New UI Mode

**Comment by Nandaka** [comment]
do you have antivirus/firewall that might kill the application? Looks like it being killed by external application. 
If it crashing due coding error, it should have the stack trace there as the main loop is wrapped in try-catch: https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L2311

**Comment by elreymu** [comment]
I think that might be unlikely since i have used previous versions of the program with no issue.
I have no firewalls, only thing close to that would be that i changed my ISP and modem recently.
I have avast antivirus, i just deactivated and ran the program to see what happens, i will let you know. 

I updated the program because it stopped working with one of pixiv updates, then i got it working again updating it to the current version, but now i am having this issue.

**Comment by Nandaka** [comment]
It changes one of the API endpoint to use webrpc. I think the firewall/antivirus suspecting it was virus trying to connect?

**Comment by elreymu** [comment]
I turned off the antivirus and ran the program-
Same issue, it closed itself.

**Comment by Nandaka** [comment]
too bad then, I have no idea why if there is no logging or screen shot. Maybe try it on different pc running windows 10?

**Comment by elreymu** [comment]
I think i figured the issue out, i had an hybrid of the old and the current version.
It was a mistake from my part, i had a very old version of the program before, then when i downloaded the newest version i replaced the old files with new ones and that's the mistake. (I didn't realize it because it actually worked)
I should have downloaded the binary one, i noticed the library.zip files are much different in filesize.
For now its working well , it hasn't closed yet.

It seems this was a false alarm but i think it should be noted somewhere because the binary link is pretty easy to miss.
