### ISSUE TITLE
Pixiv crashing when artist removed his/her works

### ISSUE THREAD

**Issue by soli18** [Nandaka/PixivUtil2#491]
### Prerequisites

* [X] Did you read FAQ section?

* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]
Loads of errors when trying to grab pictures from an artist who removed all of them.

**Expected behavior:** [What you expected to happen]
Recognizing the deleted works and just skip the artist

*Actual behavior:** [What actually happened]
Lots of error messages.

### Versions
20190501b

https://i.imgur.com/5szp0ON.png

Artist ID: 206921

**Comment by Nandaka** [comment]
Try repack2 https://github.com/Nandaka/PixivUtil2/issues/483#issuecomment-488590435

**Comment by soli18** [comment]
Do you perhaps got a repacked version for Ubuntu? As the linked one is only for Windows as I'm testing it on my home pc.

**Comment by Nandaka** [comment]
you can get the latest version by clicking clone/download the repo button from github.
![image](https://user-images.githubusercontent.com/836867/57575950-a211e700-7487-11e9-8c51-7b95b6374d85.png)
