### ISSUE TITLE
 Feature Request/Suggestion: database recording relative than absolute directory, and also a input by txt option for member ids. 

### ISSUE THREAD

**Issue by pxssy** [Nandaka/PixivUtil2#492]
Right now the database records saved images by absolute paths (as i recall), so moving the root pixiv folder or even renaming it will cause it to "forget" about all of the images it saved. 

if possible, please change it. 

And also an option to input by member id. because right now a txt with member id list like

1
2
3
4
5
6
7
8
etc

can't be directly copy pasted into the downloader. it'd be great if an option like that exists. 

Thanks again!

**Comment by Nandaka** [comment]
Nope, use Sqlite editor to change the path. Also relative to what? Using relative path to current installation folder also will cause the same issue.

Also, not possible to key in each member id in separate line at the console. Use the list feature or you can do find-replace of the new line in notepad++
