### ISSUE TITLE
cant download pixiv fanbox

### ISSUE THREAD

**Issue by froznkamui** [Nandaka/PixivUtil2#493]
i got this issue when trying to download fanbox, what should i do with this ?
![image](https://user-images.githubusercontent.com/48935710/58149785-4d4c4880-7c9f-11e9-89ca-83529a43e7c0.png)

**Comment by Nandaka** [comment]
can you upload the json file from below:
https://www.pixiv.net/ajax/fanbox/creator?userId=25310139
https://www.pixiv.net/ajax/fanbox/post?postId=377512

**Comment by froznkamui** [comment]
here u go

**Comment by froznkamui** [comment]
[json.zip](https://github.com/Nandaka/PixivUtil2/files/3205908/json.zip)
here u go

**Comment by ee092884** [comment]
Can you test this ID with f2?? ID: 1840591
My version is 20190523...
It will flash directly
The folder will have a "Dump for Unsupported embed provider = vimeo for post = 389719" error file.

**Comment by Nandaka** [comment]
can you upload the json from here:
https://www.pixiv.net/ajax/fanbox/post?postId=389719

**Comment by ee092884** [comment]
[post.zip](https://github.com/Nandaka/PixivUtil2/files/3218203/post.zip)
It's here

**Comment by NHOrus** [comment]
Pass vimeo video to `youtube-dl` if it't installed, log the fact and write it and link when fanbox procedure is over?

**Comment by ee092884** [comment]
[Bandicam.zip](https://github.com/Nandaka/PixivUtil2/files/3220162/Bandicam.zip)
I put the video with the "Dump for Unsupported embed provider = vimeo for post = 389719" error file.
Is it because there is a movie in 389719?
So will exit directly.

**Comment by Nandaka** [comment]
updated: https://github.com/Nandaka/PixivUtil2/releases/tag/v20190526

no plan to integrate with youtube-dl

**Comment by ee092884** [comment]
Can be used
The current solution is skip video , right?

**Comment by Nandaka** [comment]
nah, it just write the url in the info file if you choose to write the post info.

**Comment by ee092884** [comment]
OK~
