### ISSUE TITLE
[pixivFANBOX] f1 option broken, possible URL change (f2 still working apparently)

### ISSUE THREAD

**Issue by AgentThirteen** [Nandaka/PixivUtil2#495]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Failure to retrieve contents from supported artists in a global scope (f1 option). HTTP 404.

Browser interface is online and server works fine but it seems like pixivFANBOX changed something in the home URL again. The method used by the f1 option to retrieve a list of supported artists apparently no longer works.

Browser network trace to ensure server works fine along with XML HTTP requests used:
`GET XHR https://www.pixiv.net/ajax/fanbox/index [HTTP/2.0 200 OK]` (on home load)
`GET XHR https://fanbox.pixiv.net/api/post.listHome [HTTP/2.0 200 OK]` (on home scrolling)
`GET XHR https://www.pixiv.net/ajax/fanbox/creator [HTTP/2.0 200 OK]` (on creator load)
`GET XHR https://fanbox.pixiv.net/api/post.listCreator [HTTP/2.0 200 OK]` (on creator scrolling)

`PixivUtil2.py` error dump (redacted `PixivBrowserFactory.py` work folder in the dump since that was never ever touched or moved). Hopefully this helps.
`Input: f1`
`Max Page = 100`
`Getting supported artists from https://www.pixiv.net/ajax/fanbox/support`
`Traceback (most recent call last):`
`  File "pixivutil2.py", line 2302, in main`
`    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)`
`  File "pixivutil2.py", line 2059, in main_loop`
`    menu_fanbox_download_supported_artist(op_is_valid, args)`
`  File "pixivutil2.py", line 1801, in menu_fanbox_download_supported_artist`
`    result = __br__.fanboxGetSupportedUsers()`
`  File "PixivBrowserFactory.py", line 578, in fanboxGetSupportedUsers`
`    response = self.open_with_retry(url).read()`
`  File "PixivBrowserFactory.py", line 145, in open_with_retry`
`    return self.open(url, data, timeout)`
`  File "build\bdist.win32\egg\mechanize\_mechanize.py", line 203, in open`
`    return self._mech_open(url, data, timeout=timeout)`
`  File "build\bdist.win32\egg\mechanize\_mechanize.py", line 255, in _mech_open`
`    raise response`
`httperror_seek_wrapper: HTTP Error 404: Not Found`
`press enter to exit.`

f2 seems to be working as intended but this will be an issue if you are supporting hundreds of artists.

It's not even been two weeks since last time. Nandaka worked hard to fix this nearly instantly too. Unless people are crawling pictures like mad there is zero reason for this.

If the pixiv administration keeps up with making massive monthly subscribers look like pirates and creating extra work for this community I'll just opt out of supporting all the artists I've been supporting so far and advise everyone I know to do the same so loss-loss for both company and greedy artists.

Sorry for overreacting but the blatant money milking focus on crowdfunding platforms (they keep growing and expanding to more websites too) is quite irritating to say the least.

Meanwhile you're here coding for free and humbly asking for donations for those who can.

But let's keep it at that...

### Steps to Reproduce

1. f1 and set Max Page just in case

**Expected behavior:** Properly connect to pixivFANBOX to retrieve post contents for all supported artists

**Actual behavior:** Fatals with `httperror_seek_wrapper: HTTP Error 404: Not Found` when attempting to connect to `https://www.pixiv.net/ajax/fanbox/support` without listing any artist.

### Versions

`v20190529` was used.

You can get this information from executing `PixivUtil2.py --help`.

**Comment by Nandaka** [comment]
can you give me the contents of https://fanbox.pixiv.net/api/plan.listSupporting ?

**Comment by AgentThirteen** [comment]
Sure, thanks for the quick reply Nandaka.

JSON data returns `general_error` when called directly from the browser so that could be it.

**Comment by NHOrus** [comment]
It's now in `https://www.pixiv.net/ajax/fanbox/index`  
`"body":"supportingPlans"`

**Comment by Nandaka** [comment]
updated in https://github.com/Nandaka/PixivUtil2/releases/tag/v20190606
