### ISSUE TITLE
Having 'Local file exist' problem. I did what FAQ saids but still not working

### ISSUE THREAD

**Issue by kantatacanta** [Nandaka/PixivUtil2#498]
I checked 

overwrite=False
alwayscheckfilesize=False

but my downloader doesn't skip Local files that already exist.
I refreshed database, then compact it. But not working

How do I skip Files that already exist?
I want to see 'already downloaded' status.
 Please help

**Comment by Nandaka** [comment]
which download mode do you use?

**Comment by kantatacanta** [comment]
I use 5. download from bookmarked artists

**Comment by kantatacanta** [comment]
Fixed by downloading all contents! thanks
