### ISSUE TITLE
[Feature Request] Filter images by dimensions

### ISSUE THREAD

**Issue by udw82145** [Nandaka/PixivUtil2#499]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

It's a niche request, but is there a way to skip downloading images that don't meet certain arbitrary size constraints?

I'm not talking about implementing Pixiv's search tools size filter (since it's limited, and only gives 3 options - above 3000, 1000-3000 and <1000), but rather, an after-search option to ignore downloading images that don't fit the criteria.

This is handy if you need an upper/lower bounds for an image's dimensions, e.g. looking for large/small images (wallpapers, thumbnails, icons etc). This is my request.

As an aside, there will inevitably follow a request to do the same, but for image filesize. There is currently a way to filter for all other image metadata but these 2 cases.

**Comment by Nandaka** [comment]
for  FileSize, I can send HEAD request to get the size header.
for Dimension/resolution, I still need to download the whole files, else I
cannot parse the actual resolution...

**Comment by udw82145** [comment]
Ah, that's a shame. My bad!
