### ISSUE TITLE
Pixiv Fanbox Fails to Download

### ISSUE THREAD

**Issue by nomakewan** [Nandaka/PixivUtil2#500]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Attempting to use the F1 to download from all supporting artists results in the error:

Traceback (most recent call last):
  File "PixivUtil2.py", line 2302, in main
  File "PixivUtil2.py", line 2059, in main_loop
  File "PixivUtil2.py", line 1799, in menu_fanbox_download_supported_artist
ValueError: invalid literal for int() with base 10: ''

Attempting to use F2 to download from a particular artist whose latest post is a poll URL causes Pixivutil to force exit with the error, "Unsupported embed provider = google_forms"

### Steps to Reproduce

Use f1 to download all. Use f2 to download from an artist who has a google form URL in a post.

**Expected behavior:**

Pixiv Fanbox content will download successfully, and non-content posts such as polls will be ignored or dumped to a text file.

**Actual behavior:**

Pixivutil force quits with one of the above errors depending on whether f1 or f2 is used.

### Versions

Using Release version of PixivUtil20190606 on Windows 7 x64.

**Comment by Nandaka** [comment]
give me the contents of https://www.pixiv.net/ajax/fanbox/index and https://www.pixiv.net/ajax/fanbox/creator?userId=<the user id with google form>

**Comment by nomakewan** [comment]
Here you go.
[json.zip](https://github.com/Nandaka/PixivUtil2/files/3293682/json.zip)

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/PixivUtil2/releases/tag/v20190617-beta1

**Comment by nomakewan** [comment]
Worked perfectly, both F1 and F2. Thank you very much for the quick fix!
