### ISSUE TITLE
Download from list function can't recognize new images.

### ISSUE THREAD

**Issue by sky112475** [Nandaka/PixivUtil2#502]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

First of all, I am not good at English, so it may be hard for you to understand Please excuse me.

I like the function : 4. Download from list.

But, this function can't recognize new images after the first download process.

When I check from alarms of smartphone, tablePC, etc... I try to numerous times download that new images but It can't like under image.

https://imgur.com/6Sasy3B

As the picture shows, Util2 recognizes the list as normal. However, when I try to download a newly updated images, it will not recognize it with the message "found 0 items."

At first, I thought the tag function was a problem. Because I only collect images that correspond to tags in a particular genre.

But using "Download by Tag and member Id", it can download well with tags what "4.~" couldn't do it.

And this problem occur when I add new member_id in list.txt file same. Adding a new member and reboot Util, the first try can successful even I use Tag.

But second download, if I try to download right away without tag, the download will not proceed at all, printing "found 0 items."

Reading 'readme.txt' several times and leave a question because no workaround was found. 

Thank you for reading.

### Steps to Reproduce

1. Create a list.txt file on root folder 
2. Write a member_id lists you like.
3. Using Download from list function, and waiting to upload new image who written member_id in list.txt file.
4. When a new images of the artist in the list is uploaded, use the "Download from list" to try downloading.
5. If there is no time wating for  new image's upload, try to add a new member id in list.txt files
6. At first, list download is work with Appropriate Tag. This will require an additional download to take place when no tags have been entered in the next process.
7. But the second try without tag, Util2 can't found any image just added members.

### Versions
Latest version based on the time I wrote.

Thanks.

**Comment by Nandaka** [comment]
upload your list.txt and log file?

**Comment by sky112475** [comment]
[list.txt](https://github.com/Nandaka/PixivUtil2/files/3297074/list.txt)

[config.txt](https://github.com/Nandaka/PixivUtil2/files/3297078/config.txt)

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/3297103/pixivutil.log)
 
Yes, here you are. I hope it will help you analyze the problem.

**Comment by Nandaka** [comment]
try to set `daylastupdated = 0` in config.ini?

**Comment by sky112475** [comment]
Oh, change daylastupadted to 0 and it works right. But why? daylastupdate function isn't work?

**Comment by Nandaka** [comment]
depending on how often you run the program, it might not see any member id to download because you run it x day before.

```
daylastupdated ==> Only process member_id which x days from the last check.
````
