### ISSUE TITLE
[Suggestion] Multi-thread download process

### ISSUE THREAD

**Issue by marwanpro** [Nandaka/PixivUtil2#504]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Is there any plans to multi-thread this tool ? 
When I have to download your fav artist, with a gigabit symetric connection, I have to wait at least two weeks for full download of a 80 GB archive.

**Comment by Nandaka** [comment]
nope, but you can split your list and run multiple instance from different folder.

**Comment by maskkulin** [comment]
can't you get banned if you download to fast? I even use a delay

**Comment by marwanpro** [comment]
Never got banned, downloaded over 120 GB without delay
________________________________

**Comment by maskkulin** [comment]
wow :o I last used this program 2 years ago and always used multiple instances. Now I got afraid because I read about people getting suspended, like in this thread https://github.com/Nandaka/PixivUtil2/issues/477

**Comment by bluerthanever** [comment]
wow. i always run just one instance, with no delays or whatsoever, and i have not yet get any warnings yet...
i think the thing with multi-thread here is that the output would be messed up as well, you can't tell what exactly the util is doing. there PROBABLY ARE ways that you could solve the output problem but it's just not worth the effort.
so people tend to use multi-instances or multi-processes, as in split the list and stuff. not sure about the whole "blocking" mechanism, but i think you could probably bypass that by using different accounts and different ips(proxies).
just my opinion.

**Comment by Nandaka** [comment]
#75

**Comment by ForxBase** [comment]
> wow :o I last used this program 2 years ago and always used multiple instances. Now I got afraid because I read about people getting suspended, like in this thread #477

Using VPN can prevent getting banned right?

> ### Prerequisites
> * [x]  Did you read FAQ section?
> * [x]  Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases) or [commit](https://github.com/Nandaka/PixivUtil2/commits/master) ?
> 
> ### Description
> Is there any plans to multi-thread this tool ?
> When I have to download your fav artist, with a gigabit symetric connection, I have to wait at least two weeks for full download of a 80 GB archive.

Can you link me the artist with 80GB archive?
