### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Kattus** [Nandaka/PixivUtil2#506]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
https://pythonclock.org/

Python 2.x is EOL in 6 months (and 2 days), is there any plans to making this application work with Python 3.x? It'd be a great loss to no longer be able to use this fantastic software. :(

### Steps to Reproduce

1. Try to install dependencies for PixivUtil with Python 3
2. Fail
3. Cry

**Expected behavior:** Program working

**Actual behavior:** Not working

### Versions
20190617-beta1

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/tree/python3_switch

**Comment by Kattus** [comment]
Unfortunately it doesn't seem to be working..
I'm using Python 3.8 and the requirements listed in requirements.txt
```
build/PixivUtil2 [python3_switch] » python3 PixivUtil2.py
PixivDownloader2 version 20191116
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading /home/katt/build/PixivUtil2/config.ini ...
done.
New version available: ('20191116', '') 
Using default DB Path: /home/katt/build/PixivUtil2/db.sqlite 
Creating database... done.
Only process members where the last update is >= 7 days ago 
Username ? kattus
Password ? 
Logging in... 
Error at login(): (<class 'TypeError'>, TypeError('find() takes no keyword arguments'), <traceback object at 0x7f25289ffa80>) 
Error at doLogin(): (<class 'TypeError'>, TypeError('find() takes no keyword arguments'), <traceback object at 0x7f2527101d40>) 
Cannot Login! 
press enter to exit.
```

Same also happens when setting login in config.ini:
```
build/PixivUtil2 [python3_switch] » python3 PixivUtil2.py
PixivDownloader2 version 20191116
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading /home/katt/build/PixivUtil2/config.ini ...
done.
New version available: ('20191116', '') 
Using default DB Path: /home/katt/build/PixivUtil2/db.sqlite 
Creating database... done.
Only process members where the last update is >= 7 days ago 
Using Username: kattus
Logging in... 
Error at login(): (<class 'TypeError'>, TypeError('find() takes no keyword arguments'), <traceback object at 0x7f9e0421a9c0>) 
Error at doLogin(): (<class 'TypeError'>, TypeError('find() takes no keyword arguments'), <traceback object at 0x7f9e04113c80>) 
Cannot Login! 
press enter to exit.
```

**Comment by Nandaka** [comment]
ah, yeah, mine is still using the valid cookie values

**Comment by Nandaka** [comment]
updated the code, but it still cannot avoid the reCaptcha validation.
