### ISSUE TITLE
pixivuntill dont connect

### ISSUE THREAD

**Issue by ShiroTora** [Nandaka/PixivUtil2#507]
hello, i have a problem, i dont want to be a bother or something but thing is , i reinstalled windows 2 days ago 
current windows win 10 enterprise
i redownloaded pixiv until 2 and tried a full clean  with no cookies or logins 
but i keep getting same error

https://cdn.discordapp.com/attachments/465470547476873228/596295397279006760/unknown.png

it keeps saying av/fw but  i turned those off but no luck , so what can i do further to slove this ?
i am not knowledge or something i am happy i got to know how it works 

2 weeks ago my old client worked fine still , i dont know where the problem lies

**Comment by ShiroTora** [comment]
what i also tried is a difrent pc with w10 home ,
i copied cookie and login from pixiv in firefox but no luck it wont connect or login, i realy like to have some help wit hthis maby someone have ideas what or how i can find out what the problem is if its on my side or  the bot

**Comment by Nandaka** [comment]
Can you open the website directly in the browser (without proxy/vpn)? I can login just fine from the application.

From the error message, something is preventing the application to connect to the server/internet.

**Comment by test-pixiv** [comment]
Hello, I am having the same problem as Shirotora which happened around the same time.
I tried tweaking the AV, disabling it, try the last version (v20190712 as of today) on another computer with windows just reinstalled for the test.
PixivUtil cannot work, but I can connect on Pixiv with a browser.

**Comment by Nandaka** [comment]
Can you unblock the downloaded archive before extracting? (right click on the file and click properties in windows explorer).

For example (from other zip file):
![image](https://user-images.githubusercontent.com/836867/61092132-a05ca380-a477-11e9-8d25-cc67f800ee22.png)

**Comment by test-pixiv** [comment]
I did, but not working.
I might precise that some time passed between I once updated PixivUtil and it stopped working. It was not due to a new version.

**Comment by Nandaka** [comment]
Try this:
1. Open your browser and go to https://www.whatismybrowser.com/detect/what-is-my-user-agent.
2. Copy the user agent string and save it to config.ini
![image](https://user-images.githubusercontent.com/836867/61178194-86a79180-a61a-11e9-97f9-71e686fcfd95.png)
3. Login to your pixiv account using browser and copy the cookie values to the config.ini.
4. Run the application.

If it still not working, try to run it from source code (you need to install python 2.7.x and the required library, see https://github.com/Nandaka/PixivUtil2/wiki on Useful Tips 2).

**Comment by test-pixiv** [comment]
Hello, I just did the user agent and cookie value modification and installation from source, but sadly there was no change.
Shirotora : are you still here ? Did you tried on your side ?

**Comment by ShiroTora** [comment]
> 
> 
> Can you open the website directly in the browser (without proxy/vpn)? I can login just fine from the application.
> 
> From the error message, something is preventing the application to connect to the server/internet.

yes i tried browsers like chrome/edge/firefox and all log in fine

i notice a 2019/07/12 i tried a clean version of that one  but also that do the same it can not log in, and i dont use proxy/vpn

**Comment by ShiroTora** [comment]
ok i got news, the https://github.com/Nandaka/PixivUtil2 master version py works fine, so its the windows version that is broken 

https://cdn.discordapp.com/attachments/476025212924854272/600408248297717800/unknown.png

i tested it myself now, with my current windows enterprise ltsc with bash/linux w/e stuff and it seems it log in fine Nandaka

**Comment by Nandaka** [comment]
good, most likely something in the windows blocking the compiled version from accessing the internet.

**Comment by ShiroTora** [comment]
ok i have a new problem, since i builded a new pc i reinstalled everything and now i get this 
![unknown](https://user-images.githubusercontent.com/10827947/62569869-6cff1000-b88f-11e9-9582-2198b21ea7a4.png)

**Comment by Nandaka** [comment]
get new cookie from your browser and retry?
https://github.com/Nandaka/PixivUtil2/issues/507#issuecomment-511165934

**Comment by ShiroTora** [comment]
yeah the cookie frome chrome worked, somehow the firefox one not while i  use firefox mainly

**Comment by Nandaka** [comment]
I believe it also check the user agent (also configurable in config.ini).
