### ISSUE TITLE
Background art not being downloaded

### ISSUE THREAD

**Issue by HydroHydro** [Nandaka/PixivUtil2#508]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

Looks like the background image isn't being downloaded anymore.

Here's an example link: https://www.pixiv.net/member.php?id=2982439

The image at the top isn't in the gallery and isn't being downloaded.

**Comment by Nandaka** [comment]
Ah, looks like the logic is tied to the avatar image.
That artist doesn't have any avatar, so it background image is skipped.

Need to enhance the logic.
