### ISSUE TITLE
Download  images with search filter?

### ISSUE THREAD

**Issue by TidusFH** [Nandaka/PixivUtil2#511]
I happen to have pixiv premium is there any way that when i use the program to download it with me filtering my serach? For exmaple download the images by popularity or by bookmarks

**Comment by Nandaka** [comment]
I don't have pixiv premium, so I cannot test it.

**Comment by TidusFH** [comment]
> I don't have pixiv premium, so I cannot test it.

Would you get premium  if i sent you the money to do it so you can check? Unless you dont have paypal, since i don't think pixiv allow to gift premium to others

**Comment by Nandaka** [comment]
nah, maybe I can borrow your account for a while, but not now.

**Comment by Nandaka** [comment]
actually, can you paste the url being used for those search, for example:

sort by oldest date uses this url: https://www.pixiv.net/search.php?s_mode=s_tag&word=konosuba&order=date
