### ISSUE TITLE
How to download more than 2000 images?

### ISSUE THREAD

**Issue by nekoalliancedesign** [Nandaka/PixivUtil2#515]
Hello, i want to ask. How to change the limit of 2000 images download ? I have almost 500 member that i follow on pixiv, but the software just download 2000 images from my following list. How to remove the 2000 images limit?  Thanks before, i'll wait for your answer.

**Comment by Nandaka** [comment]
Get a pixiv premium.

Non-premium member only allowed to get up to 2000 search result from the
new images pages.
Else, you need to get all the member id (use the export function) and then
use the download from list function.

**Comment by nekoalliancedesign** [comment]
> Get a pixiv premium. Non-premium member only allowed to get up to 2000 search result from the new images pages. Else, you need to get all the member id (use the export function) and then use the download from list function.

Alright,  gonna do the export function then. Thanks!

**Comment by nekoalliancedesign** [comment]
Can you tell me how to do it ? Do i need just put all of the number id to the list.txt ?

**Comment by nekoalliancedesign** [comment]
Alright thank you.
