### ISSUE TITLE
Error when downloading fanbox entries

### ISSUE THREAD

**Issue by FujiMakoto** [Nandaka/PixivUtil2#516]
### Prerequisites

* [x] Did you read FAQ section?
Yes
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
Yes

### Description
```
Getting supported artists from https://www.pixiv.net/ajax/fanbox/index
Found 2 supported artist(s)
Processing, page 1
Getting posts from https://www.pixiv.net/ajax/fanbox/creator?userId
Using OAuth to retrieve member info for: 
Writing config file... Backing up old config to config.ini.bak
done.
Traceback (most recent call last):
  File "PixivUtil2.py", line 2334, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 2091, in main_loop
    menu_fanbox_download_supported_artist(op_is_valid, args)
  File "PixivUtil2.py", line 1841, in menu_fanbox_download_supported_artist
    processFanboxArtist(artist_id, end_page)
  File "PixivUtil2.py", line 1850, in processFanboxArtist
    result_artist = __br__.fanboxGetPostsFromArtist(artist_id, next_url)
  File "/mnt/d/Pictures/PixivUtil2/PixivBrowserFactory.py", line 608, in fanboxGetPostsFromArtist
    self.getMemberInfoWhitecube(artist_id, pixivArtist)
  File "/mnt/d/Pictures/PixivUtil2/PixivBrowserFactory.py", line 421, in getMemberInfoWhitecube
    response = self._oauth_manager.get_user_info(member_id)
  File "/mnt/d/Pictures/PixivUtil2/PixivOAuth.py", line 123, in get_user_info
    verify=self._validate_ssl)
TypeError: get() takes exactly 1 argument (5 given)
press enter to exit.^[[A^[[A^CTraceback (most recent call last):
  File "PixivUtil2.py", line 2360, in <module>
    main()
  File "PixivUtil2.py", line 2352, in main
    raw_input('press enter to exit.')
```
[Description of the bug or feature]
Unable to download fanbox images with the latest release. Errors out with the above even on a fresh clone on the latest commit.

### Steps to Reproduce

1. Authenticate to Pixiv; had to copy and paste the cookie manually due to Pixiv requiring captcha input
2. Attempt to download fanbox images

**Expected behavior:** [What you expected to happen]
The images to download

**Actual behavior:** [What actually happened]
Errors

### Versions

You can get this information from executing `PixivUtil2.py --help`.
PixivDownloader2 version 20190712

**Comment by Nandaka** [comment]
can you upload your config.ini? Please remove the values in the authentication section first.

Can you open the fanbox api url, e.g. https://www.pixiv.net/ajax/fanbox/creator?userId=6957790

**Comment by Syampuuh** [comment]
+1.
Here's my config, as far as I can tell everything is default but Ugoira settings: https://hastebin.com/wiwesugadi.ini
That link gives me the following: https://hastebin.com/wagapinase.json

**Comment by Nandaka** [comment]
Can you check your `request` library version? Looks like mismatching version compared what is required in the `requirements.txt`.


https://github.com/Nandaka/PixivUtil2/blob/master/PixivOAuth.py#L119
