### ISSUE TITLE
Old (2017) .exe no longer working.

### ISSUE THREAD

**Issue by ballpointpen099** [Nandaka/PixivUtil2#517]
Hello, I've been using a 2017 version of pixivutil for a while since it always worked and also because it contained a .exe. file. The last time I used it was about 8 months ago, I tried to use it today but ran into an error after entering a tag and extra info (ie partial match, page start) after them. I don't really know what it means, here's a screenshot:

https://i.imgur.com/OXD0DUU.png

"Why am I not using the latest version?"
I'm a VERY tech illiterate person and I honestly don't belong on this site, I just enjoy saving lots of images. With my tech illiteracy comes my ability to only use .exe files, whereas the latest verison is just filled with .py files (I assume python.) I honestly have no clue what I should be doing with them, I tried installing python and using it to open PixivUtil2.py to no avail. I'm probably doing everything wrong and this is a very simply "issue", but is there anything I can do to get it working again? (and preferrably as an .exe?)
Thank you!!

**Comment by Syampuuh** [comment]
[Download the latest release.](https://github.com/Nandaka/PixivUtil2/releases) Pixiv has been continuously changing the website in ways that have affected how the tool gets images and member information.

**Comment by ballpointpen099** [comment]
> 
> 
> [Download the latest release.](https://github.com/Nandaka/PixivUtil2/releases) Pixiv has been continuously changing the website in ways that have affected how the tool gets images and member information.

Thank you, it seems like I was downloading the source code. I really am an idiot haha @_@
