### ISSUE TITLE
pixivutil dont connect 2

### ISSUE THREAD

**Issue by test-pixiv2** [Nandaka/PixivUtil2#523]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Cannot connect Pixivutil.

_Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Failed to get page: , please check your internet connection/firewall/antivirus.',), <traceback object at 0x04986F30>)
Cannot Login!_

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

pixivutil20190907 (last one as of today)

Hello, this is the same as issue 507, but while it seems Shirotora succeeded in making Pixivutil work, I did not.
I put the new cookie value and browser agent in config.ini with no effect.
AV tweaked, disabled, everything is opened in the router. I also tried to install the Python version with no success. I tried on both windows 10 and 7.

**Comment by Nandaka** [comment]
do you able to open the website on the browser? also try on other pc?
I have updated the script, can you pull the latest commit and rerun from script? Ensure you are using python 2.7.x

**Comment by test-pixiv2** [comment]
> do you able to open the website on the browser?

Yes, no problem here

> also try on other pc?

On other PC with windows 10 and 7 : not working. They are clean, by this I mean no AV or anything.

> I have updated the script, can you pull the latest commit and rerun from script? Ensure you are using python 2.7.x

I am using 2.7.16.
It now ask for captcha : Server reply: {u'captcha': u'Please complete the reCAPTCHA verification.'}

Thank you for your time.

**Comment by Nandaka** [comment]
ok, then please follow the cookie login method. Ensure the user agent is the same with the browser you use for login.

**Comment by test-pixiv2** [comment]
I did, still asking for captcha.
Where do you modify cookie and browser agent in python version of pixiv since there is no config.ini ?
Notepad > PixivConfig.py > # Authentication related ?

**Comment by Nandaka** [comment]
no, run the script for the 1st time, it should create a config.ini in the application folder.

For captcha, this one I cannot prevent, as it is from the pixiv server itself.

**Comment by thegreatestminer** [comment]
Using 20190907b and it hangs on "Trying to log in with saved cookie"

It was working just fine yesterday..

**Comment by Nandaka** [comment]
can you redownload the latest zip file, I think I forgot to remove the debugging code (the code will show `[true]` or `[false]` on the screen, it will continue if you press enter.)

**Comment by thegreatestminer** [comment]
Looks like pixiv banned my IP, since resetting my router got it working again.

**Comment by test-pixiv2** [comment]
I modified the config.ini file of the python version of pixiv version 20190907b to just add the web agent and cookie : it worked.
I downloaded the windows package : it worked too !
So I tried again with updating my current install : not working.

config.ini files are the same, except for cookie value.

Any specific port to open in router maybe ?


I remember not installing any windows update during the time pixivutil stopped working, but I guess it may be my system that is preventing it to connect.
It also does not work on another fresh install of windows on a laptop.

**Comment by Nandaka** [comment]
> captcha 

This is based on Pixiv server, most likely they use heuristic similar like other sites implementing Captcha.

> router port

No special port, it just connect to http (80) and https (443) on the pixiv server. If your isp shared the public ip address, then it might be detected as unusual connection at pixiv
