### ISSUE TITLE
PixivUtil2 identified as suspicious by antivirus, cannot execute without exception added

### ISSUE THREAD

**Issue by cglmrfreeman** [Nandaka/PixivUtil2#524]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

In attempting to run the latest release of the program, my antivirus immediately terminates the program after the first input is given at the first prompt. This is the first time in my history of using the program, many years, that it's ever been flagged by my antivirus. The program can function normally if an exception is added.

### Steps to Reproduce

1. Have Avast (Free) Antivirus installed and running all shields
2. Launch PixivUtil2.exe
3. Enter anything at the first input prompt screen and the program will terminate
4. After several re-launches of the program, Avast will prevent the program from executing at all

**Expected behavior:**
The program should function normally

**Actual behavior:**
The program was terminated by antivirus before it could execute any useful functionality.

### Versions

pixivutil20190907b

**Comment by Nandaka** [comment]
nope, check your antivirus, else you can run the program from the source code.

Checked via virustotal the release in here, and it return clear, so maybe false positive?
https://www.virustotal.com/gui/url/f0e36d05115cda2038c59844b789a7df2bece0656c79d53d8d48b4b750806f6e/detection

**Comment by cglmrfreeman** [comment]
I am not saying it was like a virus or that it was even a false positive. I am saying that for the first time, in my years of using your executables, this is the first time my antivirus has flagged the executable from the get-go.

"Nope" is not a solution to this issue and will be concerning if every new build going forward gets flagged.

**Comment by cglmrfreeman** [comment]
Update, upon removing my exception from Avast, the file can not be run. This issue should not be closed until the file can be run without the exception. "Checking my antivirus" is not a solution to this problem. I already proposed a workaround, which is the exception, as indicated in both the title and first post.
![eey3frQtG2](https://user-images.githubusercontent.com/9744201/64493031-c90ed880-d22f-11e9-8bb5-453d234e8969.png)

**Comment by cglmrfreeman** [comment]
Using the steps as seen in the original post, this issue was 100% accurately reproduced in a Virtual Machine. Please see video: https://youtu.be/YkggH-irXDA Note that an older version of PixivUtil2 is also downloaded and ran after the CyberCapture prevented the latest version of the application from running, but did not CyberCapture the older version.

**Comment by Nandaka** [comment]
I don't use Avast. I don't even know where to fix it.

**Comment by cglmrfreeman** [comment]
I would assume some code added since the prior release triggers the heuristic "CyberCapture", deeming the program necessary to send to home base for analysis. In my slightly over two years of using avast with the CyberCapture feature, I've never had it activate with PixivUtil2 before. It's entirely possible this was a one-off, and after removing the exception this morning Avast has okayed the program to be used. It will just suck going forward if all releases must be submitted to Avast for analysis for use without adding exceptions. We will see going forward I guess.

Because Avast has approved the application, this issue truly is closed for this version.

**Comment by Nandaka** [comment]
here are the changes from previous release to master https://github.com/Nandaka/PixivUtil2/compare/v20190712...master and to the current release tag https://github.com/Nandaka/PixivUtil2/compare/v20190712...v20190907b

I don't see big changes, not sure if this cause the error because it doesn't trigger anything in my side.
https://github.com/Nandaka/PixivUtil2/compare/v20190712...v20190907b#diff-7a612caa8f02f7c30e49d68a8c1ab43fR67
