### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by elina7** [Nandaka/PixivUtil2#527]
PixivDownloader2 version 20190907b
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading E:\Non installation Utility\pixivutil\pixivutil20190907b\config.ini ...
done.
Using default DB Path: *
db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: *
Logging in...
Server reply: {u'captcha': u'Please complete the reCAPTCHA verification.'}
press enter to exit.

**Comment by Nandaka** [comment]
see #505
