### ISSUE TITLE
Error at process_tags(): "Failed to login using OAuth"

### ISSUE THREAD

**Issue by dragontamer8740** [Nandaka/PixivUtil2#530]
### Prerequisites

* [x] Did you read FAQ section? – yes
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? – Commit

### Description

Cannot authenticate past OAuth. Probably related to https://github.com/Nandaka/PixivUtil2/issues/529 , but mine is actually following the correct bug submission procedure.

May also be related to https://github.com/upbit/pixivpy/issues/83

### Steps to Reproduce

1. Start PixivUtil2, with username, password, and cookie set in config.ini
2. Login succeeds
3. choose `10` (`Download by tag and member id`)
4. enter member ID and tag.

**Expected behavior:** Downloads a members' works with a certain tag.

**Actual behavior:** [What actually happened]

    Error at process_tags() at page 1: (<class 'PixivException.PixivException'>, PixivException('Failed to login using OAuth',), <traceback object at 0x7fab7fda0eb0>) 
    Failed to login using OAuth

### Versions

    PixivDownloader2 version 20190907b

**Comment by Nandaka** [comment]
delete the refresh token in the config.ini and can you load the log file?

**Comment by feiguizz** [comment]
I have deleted the refresh token but it did not work.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20190917
