### ISSUE TITLE
Certain pixiv usernames images are saved into pixivutil directory

### ISSUE THREAD

**Issue by scottyseng** [Nandaka/PixivUtil2#533]
### Prerequisites

 [x] Did you read FAQ section?
 [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

These two pixiv usernames causes pixivutil to save images into the pixivutil directory. My only guess is that the periods used in the pixiv usernames are causing this.
(1079073) .
(652249) Loading..

### Steps to Reproduce

1. Run download by member id using the two member IDs above
2. I noticed that the images are saved into pixivutil folder instead of artist folder

**Expected behavior:** [What you expected to happen]
Save to directory set in config, but with the periods replaced by spaces (or removed) in folder name.

**Actual behavior:** [What actually happened]
Downloader saves images in pixivutil directory.

### Versions

Current Release, 20190919

**Comment by Nandaka** [comment]
what is your filename format in config.ini?

**Comment by scottyseng** [comment]
Sorry for the late reply, I forgot about this.

[Filename]
filenameformat = (%member_id%) %artist% \%urlFilename% - %title%
filenamemangaformat = (%member_id%) %artist% \%urlFilename% - %title%
filenameinfoformat = (%member_id%) %artist% \%urlFilename% - %title%
avatarnameformat = 
tagsseparator = ,
createmangadir = False
usetagsasdir = False
urldumpfilename = url_list_%Y%m%d

**Comment by photonometric** [comment]
I can't seem to get this to reproduce? I tried user 1079073 using my usual filename and then yours...they both output to the same directory. [Using  v20190919 on Win7 x64]

**Mine**: 
`%member_id% [%member_token%]\%member_token% - %image_id%`
`%member_id% [%member_token%]\%member_token% - %urlFilename%`

**Yours**: 
`%member_id% [%member_token%]\(%member_id%) %artist% %urlFilename% - %title%`

The dir/filenames came out like this respectively:
`<artists>\1079073 [wntame]\wntame - 65306890_p0.png`
`<artists>\1079073 [wntame]\(1079073) . 65306890_p0 - 無題.png`

Seemingly no trouble with inserting a period for the %artist% variable on my NTFS drive. I haven't been able to get any files to go into the program directory. This seems to be the same behavior as #525...perhaps it is a path+filename length issue?

**Comment by scottyseng** [comment]
@photonometric Maybe it is because I'm using a network drive? Or because I have Pixiv Downloader putting folders outside of the program's location?

I have Pixiv Downloader located here:
Z:\Shared\Artist CG\Pixiv\!Pixiv Downloader

And my root directory is here:
Z:\Shared\Artist CG\Pixiv

Any period in the artist name still makes Pixiv Downloader trip up for me, I don't think the path length is an issue (At least I'm not seeing windows kick out any errors due to path length when opening files).

Also running on Windows Server 2016 (Pretty much Windows 10 Build 1607)

**Comment by Nandaka** [comment]
Is it possible to run the application on local drive and set the root dir to local drive too, instead of network drive? This way we can eliminate the issue is due to SMB share or file system issue.

**Comment by scottyseng** [comment]
So I ran Pixiv downloader in my downloads folder locally, and when default config, it makes the folder name to  be:
_ (1079073)

When I change it to my folder naming (Which is just member ID in front then name):
[Filename]
filenameformat = (%member_id%) %artist% %urlFilename% - %title%
filenamemangaformat = (%member_id%) %artist% %urlFilename% - %title%
filenameinfoformat = (%member_id%) %artist% %urlFilename% - %title%

It makes the folder:
(1079073)

Some images did download into the folder, but around 10 images in, it started to save the images inside of the pixiv downloader directory (not in the folder). I also noticed there was an error this time while the downloader was running:

Processing Image Id: 76227208
Title: 【ｃ96】おひっクスPRPR本【無料版】
Tags : R-18
Date : 2019-08-12 17:08:24+00:00
Mode : manga
Page Count : 14
Image URL : https://i.pximg.net/img-original/img/2019/08/13/02/08/24/76227208_p0.jpg
Filename  : C:\Users\Administrator\Downloads\pixivutil20190919\(1079073) .\76227208_p0 - 【ｃ96】おひっクスPRPR本【無料 版】.jpg
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=76227208
Remote filesize = 4.18 MiB (4384496 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=76227208
Error at download_image(): Cannot save https://i.pximg.net/img-original/img/2019/08/13/02/08/24/76227208_p0.jpg to C:\Users\Administrator\Downloads\pixivutil20190919\(1079073) .\76227208_p0 - 【ｃ96】おひっクスPRPR本【無料版】.jpg: (<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x03F20990>)
File is saved to 76227208_p0.jpg
 [||||||||||||||||||||] 4.18 MiB of 4.18 MiB  Completed in 1.995s (2.10 MiB/s)

**Comment by Nandaka** [comment]
what is the value for `rootdirectory` in config.ini?

**Comment by scottyseng** [comment]
rootdirectory = .

Pixiv downloader is just in my downloads folder.

**Comment by Nandaka** [comment]
Try to use `.\`

looks like missing the path separator between rootdir and filename format.

> C:\Users\Administrator\Downloads\pixivutil20190919(1079073) .\76227208_p0 - 【ｃ96】おひっクスPRPR本【無料 版】.jpg

**Comment by scottyseng** [comment]
Image URL : https://i.pximg.net/img-original/img/2019/08/18/00/27/19/76315992_p1.png
Filename  : C:\Users\Administrator\Downloads\pixivutil20190919\1079073 .\76315992_p1 - 無題.png
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=76315992
Remote filesize = 3.31 MiB (3474493 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=76315992
Error at download_image(): Cannot save https://i.pximg.net/img-original/img/2019/08/18/00/27/19/76315992_p1.png to C:\Users\Administrator\Downloads\pixivutil20190919\1079073 .\76315992_p1 - 無題.png: (<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x039A0A80>)
File is saved to 76315992_p1.png
 [||||||||||||||||||||] 3.31 MiB of 3.31 MiB  Completed in 1.603s (2.07 MiB/s)
 done.

Still no luck. Just to make sure, I have it as:
`rootdirectory = .\`

**Comment by Nandaka** [comment]
just to confirm, the problem filename formats are these one, right? (with separator).
```
filenameformat = %member_id% %artist%\%urlFilename% - %title%
filenamemangaformat = %member_id% %artist%\%urlFilename% - %title%
filenameinfoformat = %member_id% %artist%\%urlFilename% - %title%
```

1. It is only create the member id because `.\` is escaped by Windows for folder name.
2. Try to set the root dir to `C:\Pixiv` and see what happen?

Result on my pc
![image](https://user-images.githubusercontent.com/836867/67297887-12d02b80-f51d-11e9-9044-f483fa23cba4.png)
