### ISSUE TITLE
Windows version does not handle UNCs or mapped network drive paths

### ISSUE THREAD

**Issue by tphillip913** [Nandaka/PixivUtil2#534]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

While running the latest version on Windows 10 Pro (1903) when trying specify UNC or a mapped drive as the "rootdirectory" setting in the config.ini pixivutil acts in a bad manner or throws an error complaining about being unable to find the path specified.

### Steps to Reproduce
For a UNC
1. Edit the config.ini file to have a proper UNC (Eg: \\fqdn.domain.com\Share\Dir) to an existing share than can be opened and modified by Windows Explorer specified in the "rootdirectory" field
2. Run pixivutil2

For a mapped network drive
1. Use Windows Explorer to map an existing share (Eg: \\fqdn.domain.com\Share\Dir) to a volume letter like "Z:\"
2. Edit the config.ini file to specify the "rootdirectory" to "Z:\directory"
3. Run pixivutl2
3. [and so on...]

**Expected behavior:**
The files should be downloaded and saved into the "rootdirectory" field and what's specified under "[Filename]"

**Actual behavior:**
For a UNC: The very first "\" is stripped and the hostname is used to create a directory on the root volume and a directory structure is created to match the rest of the UNC. For example if the UNC is "\\fqdn.domain.com\Share\Dir" you will find a directory structure "c:\fqdn.domain.com\Share\Dir\"

For a mapped drive: The following error snippet is written to the log:
2019-09-25 18:54:48,453 - PixivUtil20190919 - INFO - Using Referer: https://www.pixiv.net/
2019-09-25 18:54:49,687 - PixivUtil20190919 - INFO - Using Referer: https://www.pixiv.net/
2019-09-25 18:54:50,864 - PixivUtil20190919 - INFO - Creating directory: Z:\Pics\Rips\pixiv\アヤ(´・ω・｀) (144540)
2019-09-25 18:54:50,864 - PixivUtil20190919 - ERROR - Error at download_image(): (<type 'exceptions.WindowsError'>, WindowsError(3, 'The system cannot find the path specified'), <traceback object at 0x028F1EB8>) at https://i.pximg.net/user-profile/img/2017/05/01/14/52/21/12495663_8dc2ad5a635b7535cb1549bf82ef9d82.jpg (9000)
2019-09-25 18:54:50,864 - PixivUtil20190919 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 238, in download_image
  File "PixivUtil2.py", line 346, in perform_download
  File "PixivHelper.pyc", line 591, in downloadImage
  File "PixivHelper.pyc", line 582, in makeSubdirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 157, in makedirs
WindowsError: [Error 3] The system cannot find the path specified: u'Z:\\'

### Versions
PixivDownloader2 version 20190919

**Comment by Nandaka** [comment]
Weird, root dir shouldn't be sanitized by the helper, only the generated filename format.
Can you use `/` instead of '\'?

also ensure it has the write access to the shared folder.

**Comment by tphillip913** [comment]
There is write access to the share and the directory structure within.

I'm not sure what you want me to swap "/" with """. I don't use quotes to encapsulate the value I'm assigning to rootdirectory but I could if you think that'll help.

**Comment by tphillip913** [comment]
sorry. I see my mistake in the  initial text. **For a UNC: The very first "" ** should read **For a UNC: The very first "\" **

**Comment by Nandaka** [comment]
I mean try to use //hostname/folder rather than \\hostname\folder ?

Also try to use Z:/

**Comment by tphillip913** [comment]
Swapping "\\" for "/" does not change the behavior at all for either case.

**Comment by Nandaka** [comment]
> WindowsError: [Error 3] The system cannot find the path specified: u'Z:\'

Weird, because that error is from the OS level stated either it doesn't have access.

Is it possible to run it from script?

**Comment by tphillip913** [comment]
This is all from a script. :)

 It's a one-liner that just has pixivutil2 pull some artists and shove them in the directory with the default subdir rules.

Would you like me to post the Powershell and config.ini?

**Comment by Nandaka** [comment]
sure, remember to remove the authentication section.

**Comment by tphillip913** [comment]
Here's the files.
[configandpowershell.zip](https://github.com/Nandaka/PixivUtil2/files/3688007/configandpowershell.zip)

**Comment by Nandaka** [comment]
not sure if related: https://github.com/Nandaka/PixivUtil2/issues/533#issuecomment-541403086
