### ISSUE TITLE
Can't login with my account .

### ISSUE THREAD

**Issue by IatnehRevol** [Nandaka/PixivUtil2#535]
Its giving me some kind of error when im trying to log in with my account. I used latest version even then its not working.
![image](https://user-images.githubusercontent.com/41537023/65819390-c5261300-e23d-11e9-9055-91537b1b6c3a.png)

**Comment by Nandaka** [comment]
The application cannot connect to the internet, try to unblock the zip file and extract it again?
 See https://thirtysix.zendesk.com/hc/en-us/articles/202921675-How-to-Unblock-a-File-Downloaded-from-an-Email-or-the-Internet

Else, check the antivirus/firewall, you might need to add an exception to the application.

**Comment by IatnehRevol** [comment]
I tired nothing seems to work. I tried starting new but its giving me this 
![image](https://user-images.githubusercontent.com/41537023/65822373-7b045800-e264-11e9-8139-3f85c2e98d3c.png)

**Comment by Nandaka** [comment]
check #505

**Comment by IatnehRevol** [comment]
ok its worked now thanks.
