### ISSUE TITLE
writeimageinfo without redownloading already downloaded images

### ISSUE THREAD

**Issue by secretuser** [Nandaka/PixivUtil2#538]
for a significant part of my downloads I have not set writeimageinfo  to true.
is there a way to download this metadata info without redownloading all the images?

thank you in advance

**Comment by Nandaka** [comment]
Assuming the downloaded file still in the target location and you are using download from list (opt 4) or member id, or if you have the list of the images, you can try to setup the config ini:
```
daylastupdated = 0
overwrite = True
alwaysCheckFileSize = True
writeimageinfo = True
```

It will go thru the list you provide and will only download if the image have different file size.

**Comment by secretuser** [comment]
i followed your instructions, and it works. then i tried to do it with
overwrite= false and it still works, this was much faster too as the
overwrite=true redownloaded the image it seems, this made it much slower.
thanks for your help! great software.
