### ISSUE TITLE
Issue: Warn that you cant download locked content

### ISSUE THREAD

**Issue by Kimarnic** [Nandaka/PixivUtil2#539]
Thanks for wasting my time, this trash cant download fanbox content, what a waste of my life

**Comment by Evaia** [comment]
Aren't you pleasant. The f1/f2 options work fine for me, are you signed in?

**Comment by Kimarnic** [comment]
it just downloads the previews, not the paid content

**Comment by NHOrus** [comment]
I had six artists to calm down that fanbox is safe to use and that pixivutil won't be used to steal their art. Disclaimer would be good, yes.

Отправлено из Yahoo Почты для Android 
 
  чт, 3 окт. 2019 в 23:55 Kimarnic<notifications@github.com> написал(-а):   
it just downloads the previews, not the paid content

**Comment by Kimarnic** [comment]
Wasted my time trying to download locked images, add a warning or something

**Comment by Hamuko** [comment]
Sounds a lot like your time is worthless anyways.

**Comment by scottyseng** [comment]
I'm not even sure why you would even think the downloader would be able to download locked art.
