### ISSUE TITLE
Cannot Login (Captcha Error)

### ISSUE THREAD

**Issue by Sumea** [Nandaka/PixivUtil2#541]
### Prerequisites
Latest few versions, still an issue.

### Description

Cannot login.
oAuth "PLEASE FILL CAPTCHA" - exit application

### Steps to Reproduce

1. Western account/user (?) (outside Japan, (?) )
2. Login window, enter USERNAME, PASSWORD
3. Logging in...
Server reply: {u'captcha': u'Please complete the reCAPTCHA verification.'}
press enter to exit.

**Expected behavior:** Login

**Actual behavior:** not login

### Versions

PixivDownloader2 version 20190919

**Comment by OniiGokko** [comment]
check #505   and see if it fixes the issue  your having with the program.. //oni 3:)
