### ISSUE TITLE
Windows file paths aren't handeled properly.

### ISSUE THREAD

**Issue by TehNolz** [Nandaka/PixivUtil2#542]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When using an absolute path (eg. `D:\foo\bar`) to save files, the utility seems to assume that its a relative path, and will store files in a subfolder (eg. `.\D_\foo\bar`) instead. The same also happens when using a relative path that contains  `..` somewhere.

From the config.ini section of the readme, reserved/illegal characters are replaced with an underscore. I believe this check is the cause of the problem.

### Steps to Reproduce

Assuming PixivUtil2.exe is in `D:\PixivUtil`, and the destination folder should be `D:\Example\Folder`;

1. In config.ini, set the filename settings as either;
```
filenameformat = D:\Example\Folder\%urlFilename% - %title%
filenamemangaformat = D:\Example\Folder\%urlFilename% - %title%
filenameinfoformat = D:\Example\Folder\%urlFilename% - %title%
```
or
```
filenameformat = ..\Example\Folder\%urlFilename% - %title%
filenamemangaformat = ..\Example\Folder\%urlFilename% - %title%
filenameinfoformat = ..\Example\Folder\%urlFilename% - %title%
```

2. Run the utility and start downloading whatever.

**Expected behavior:**
Using the above example, the files should end up in `D:\Example\Folder`

**Actual behavior:**
The files end up in `D:\PixivUtil\D_\Example\Folder` for the absolute path, and `D:\PixivUtil\_\Example\Folder` for the relative path.

### Versions

Tested on both v20190907 and v20190917.

**Comment by Nandaka** [comment]
configure your root directory in config ini on separate key, not on filenameformat
```
[Settings]
rootdirectory ==> Your root directory for saving the images.
```

**Comment by TehNolz** [comment]
Woops, didn't realize that was a setting. Thanks!
