### ISSUE TITLE
Irfan Viewer and unicode filenames

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#543]
This is more of "What I am doing wrong with file lists" question

Lists of downloaded images open perfectly with Irfan 4.44 with unicode plagin, but modern Irfan 4.53 opens only files without japanese characters in names.
Moveover, when I open files through Irfan 4.44 "Open in editor" functionality, Japanese filenames turn into glibberish.

Any ideas?

**Comment by Nandaka** [comment]
shouldn't be park to irfanview forum? 

The script will write the list using utf-8 encoding (without BOM).
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L282

Anyway, try to save the list with utf-8 + BOM encoding using Notepad++?

**Comment by NHOrus** [comment]
Thank you, this works beautifully.

**Comment by NHOrus** [comment]
Now it should work.
