### ISSUE TITLE
FANBOX failure with 'Unsupported post type'

### ISSUE THREAD

**Issue by notalreadytakenusername** [Nandaka/PixivUtil2#544]
### Prerequisites

* [O] Did you read FAQ section?
* [O] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
Run PixivUtil2.exe and input 'f1' ( Download from supported artists (FANBOX))

**Expected behavior:** [What you expected to happen]
Download all the fanbox posts from artist who I support.

**Actual behavior:** [What actually happened]
Stuck at certain post with error 'Unsupported post type'

### Versions

PixivDownloader2 version 20190919 (latest at 2019/10/23)

**Comment by Nandaka** [comment]
can you upload the log file with the error message? (not the screen shot).
I will recommend to delete the old log and then rerun with the problem post/id.

**Comment by notalreadytakenusername** [comment]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/3761352/pixivutil.log)

I backed up old log and reproduced error with fresh log file.
I think line 740~ have information about the error.

**Comment by Nandaka** [comment]
> 2019-10-23 17:57:27,572 - PixivUtil20190919 - DEBUG - Sanitized Filename: Dump for Unsupported post type = entry for post = 540.html

Can you upload the 540.html file? it should be generated from https://fanbox.pixiv.net/api/post.listCreator?userId=867590&maxPublishedDatetime=2018-01-23%2017%3A00%3A00&maxId=540&limit=10

**Comment by notalreadytakenusername** [comment]
[Dump for Unsupported post type = entry for post = 540.zip](https://github.com/Nandaka/PixivUtil2/files/3767499/Dump.for.Unsupported.post.type.entry.for.post.540.zip)

I found 'Dump for Unsupported post type = entry for post = 540.html' file in folder.
Is it the file you asked for?
I zipped the file because html files are not supported.
