### ISSUE TITLE
Unable to login using most recent version

### ISSUE THREAD

**Issue by Ouxhi** [Nandaka/PixivUtil2#547]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

ERROR - Error at doLogin(): (<class 'mechanize._response.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib2.HTTPError instance) at 0x3a2a9d0 whose wrapped object = <closeable_response at 0x3ad9148 whose fp = <response_seek_wrapper at 0x3ad5c88 whose wrapped object = <closeable_response at 0x3ad5df0 whose fp = <socket._fileobject object at 0x03AD2CB0>>>>>, <traceback object at 0x03A2EFA8>)

ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 2169, in doLogin
  File "PixivBrowserFactory.pyc", line 237, in loginUsingCookie
  File "PixivBrowserFactory.pyc", line 146, in open_with_retry
  File "mechanize\_mechanize.pyc", line 203, in open
  File "mechanize\_mechanize.pyc", line 255, in _mech_open
httperror_seek_wrapper: HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Permanently

ERROR - Cannot Login!

ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 2366, in main
  File "PixivUtil2.py", line 2176, in doLogin
PixivException: 1005 Cannot Login!, hasDumpPage=N

### Steps to Reproduce

1. Open PixivUtil2.exe
2. Try to log in using username/password and cookie in config.ini

**Expected behavior:** Successful login

**Actual behavior:** Received error 1005, can't login

### Versions

v20190917 (pixivutil20190919)

**Comment by OniiGokko** [comment]
try checking ->  #535 and #505 to see if that can help you solve the issue.. //oni 3:)

**Comment by Ouxhi** [comment]
My cookie needed to be updated in the config.ini file. After updating it, pixivutil2 was able to use my login information. Closing ticket. Thanks for the help.
