### ISSUE TITLE
Allow txt file listing links instead of just ID numbers

### ISSUE THREAD

**Issue by brimstone-** [Nandaka/PixivUtil2#55]
##### list.txt should be as simple as just a list of links instead of ID

I think being able to just have a text file full of the links to the members, and maybe even individual images in question should be able to be parsed by the program, since it's a huge hassle to extract all the image ID's by hand and paste them.

* For example, the OneTab Chrome extension can take all your open tabs and convert them into a list of links, if they were all pixiv member/image links it'd be really easy to just copy that into a txt file and tell PixivUtil to us that.

Just a suggestion, hopefully it's possible~

**Comment by sabearcher** [comment]
in the fact, my desire of exit code is the same with this asking -- i've written a python shell to do the work, problems only go to the exit code.

**Comment by chronometric** [comment]
I agree this would be a cool feature when creating a download list, it's fairly easy to make a list of these links as described, and then do one or two simple find/replace operations in a word processor like MS Word or Notepad++ to remove the URL text and leave only the member or illustration ID number.

Not sure what @sabearcher means by exit code...maybe something to do with a python script?

**Comment by NHOrus** [comment]
I am against this enhancement: after having a list of all members as URL, extracting all their IDs are trivial, could be done in WIndows easily, but adds complications and unneeded functions to PixivUtil.

**Comment by chronometric** [comment]
@NHOrus: I think it's a stretch to say that a simple find/replace with two or three possible string combinations is a complication to a program such as this...

**Comment by sabearcher** [comment]
@chronometric yes it is.I do that in a python script for batched download. just like the topic links in txt.

**Comment by Nandaka** [comment]
enhanced to support below urls:
- http://www.pixiv.net/member.php?id=<member_id>
- http://www.pixiv.net/member_illust.php?id=<member_id>

I'm using urlparse to handle the querystring parsing.

**Comment by chronometric** [comment]
Thanks a lot for doing this! The added convenience of being able to use the raw URLs is very nice.

Just to clarify, the only type of page not usable in its raw URL form now is an artists' _Bookmarks_ (**http://www.pixiv.net/bookmark.php?id=**)? I know I download bookmark galleries sometimes for artists that curate them really well. It's not something I do very often, so typing the ID# into the menu works fine, but is there any reason this couldn't be added to the above parsing system (with very little effort)?

**Comment by Nandaka** [comment]
currently there is no support to download artist's bookmarked images from list.txt, I believe? That's why I didn't add bookmark url to the list.txt parsing.
