### ISSUE TITLE
Option 3 (download by tags) no longer works after Halloween revamp

### ISSUE THREAD

**Issue by AgentThirteen** [Nandaka/PixivUtil2#550]
### Prerequisites
* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
Since November 1st, 00:00 JST, unable to download using option 3 (download by tags).
Any request will return:

Error at process_tags() at page 1: (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'",), <traceback object at 0x0449E788>)
Traceback (most recent call last):
  File "pixivutil2.py", line 2369, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "pixivutil2.py", line 2095, in main_loop
    menu_download_by_tags(op_is_valid, args)
  File "pixivutil2.py", line 1608, in menu_download_by_tags
    use_tags_as_dir=__config__.useTagsAsDir, bookmark_count=bookmark_count, oldest_first=oldest_first)
  File "pixivutil2.py", line 978, in process_tags
    page)
  File "PixivBrowserFactory.py", line 563, in getSearchTagPage
    result.parseTags(parse_search_page, tags)
  File "PixivModel.py", line 1020, in parseTags
    items = search_result.findAll('li', attrs={'class': self.__re_imageItemClass})
AttributeError: 'NoneType' object has no attribute 'findAll'

### Steps to Reproduce
1. Use option 3 with any combination of parameters (not even a tag is needed)
2. Query fatals

**Expected behavior:** search.php should be getting results with the query (works in the browser but likely doesn't have the same elements as before in the DOM)

**Actual behavior:** search.php cannot properly get results through PixivUtil because of an interface change and the script fatals

### Versions
Tested on latest version `PixivDownloader2 version 20190919`; older versions also have the same issue.

**Comment by Nandaka** [comment]
yeah, they replace the UI to use REST for getting the image list. This might need big changes...

Endpoint= https://www.pixiv.net/ajax/search/artworks/%tag
Parameter List:
- word=%tag
- mode=safe|r18 or empty for both
- s_mode = s_tag_full|s_tc or empty for partial tag match
- scd = yyyy-mm-dd
- ecd = yyyy-mm-dd

**Comment by Nandaka** [comment]
crap, they remove the bookmark data from search page...

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/PixivUtil2/releases/tag/v20191103-beta1

**Comment by AgentThirteen** [comment]
@Nandaka Thank you for the quick reply and hard work. Unfortunately, that still doesn't work.

From latest commit (`71f5292`):

Using Partial Match (s_tag) and `old`, page 50 to end

Image #1
Image Id: 817
Processing Image Id: 817
Giving up image_id (medium): 817
Image ID (817): 9005 Failed to get page: https://www.pixiv.net//artworks/817 => HTTP Error 404: Not Found, hasDumpPage=N
Stack Trace: (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net//artworks/817 => HTTP Error 404: Not Found',), <traceback object at 0x05DE7C60>)

Using partial match and normal (new), page 5-5 (5 only)

Image #1
Image Id: 77636028
Processing Image Id: 77636028
Giving up image_id (medium): 77636028
Image ID (77636028): 9005 Failed to get page: https://www.pixiv.net//artworks/77636028 => HTTP Error 404: Not Found, hasDumpPage=N
Stack Trace: (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net//artworks/77636028 => HTTP Error 404: Not Found',), <traceback object at 0x06005468>)
Image #2
Image Id: 77635986
Processing Image Id: 77635986
Giving up image_id (medium): 77635986
Image ID (77635986): 9005 Failed to get page: https://www.pixiv.net//artworks/77635986 => HTTP Error 404: Not Found, hasDumpPage=N
Stack Trace: (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net//artworks/77635986 => HTTP Error 404: Not Found',), <traceback object at 0x0608FC88>)

Interesting dump:

Image: 77636028 ==> Failed to get page: https://www.pixiv.net//artworks/77636028 => HTTP Error 404: Not Found
Image: 77635986 ==> Failed to get page: https://www.pixiv.net//artworks/77635986 => HTTP Error 404: Not Found

A simple fix apparently, just an extra slash that needs removed. Almost there!

**Comment by Nandaka** [comment]
I see. It was redirecting to /en/ for me, so I'm trying to set the artwork url directly based on the login redirection.

**Comment by Nandaka** [comment]
updated in latest commit: 53cc4be

Tested using this, and it will loop correctly to the last page
![image](https://user-images.githubusercontent.com/836867/68089679-67bd5b80-fea6-11e9-9068-f7930be653e3.png)

![image](https://user-images.githubusercontent.com/836867/68089694-83286680-fea6-11e9-81e0-6f898564ae52.png)

**Comment by AgentThirteen** [comment]
Thanks for fixing the localization issue.
I've just tested `53cc4be`, still looping on page 1, unfortunately.
Here's a detailed example of what I mean:

Looping... for https://www.pixiv.net/ajax/search/artworks/%28%E3%81%8A%E3%81%AD%E3%83%AD%E3%83%AA%20OR%20%E3%83%AD%E3%83%AA%E3%81%8A%E3%81%AD%29%20-%E3%82%AD%E3%82%B9%E5%94%BE%20-MMD%20-%E3%81%AB%E3%82%87%E3%81%9F%20-%E5%A5%B3%E4%BD%93%E5%8C%96%20-%E8%85%90%E5%90%91%E3%81%91%20-3D%20-poser%20-blender%20-dazstudio%20-%E3%81%B5%E3%81%9F%E3%81%AA%E3%82%8A%20-%E3%83%95%E3%82%BF%E3%83%8A%E3%83%AA%20-%E3%82%B1%E3%83%A2%E3%83%8E%20-%E3%83%A1%E3%82%B9%E3%82%B1%E3%83%A2%20-%E7%94%B7%E3%81%AE%E5%AD%90%20-%E5%B0%91%E5%B9%B4%20-%E8%B5%A4%E3%81%A8%E7%99%BD%20-%E3%82%B7%E3%83%BC%E3%83%A1%E3%83%BC%E3%83%AB%20-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E5%B0%91%E5%A5%B3?word=%28%E3%81%8A%E3%81%AD%E3%83%AD%E3%83%AA%20OR%20%E3%83%AD%E3%83%AA%E3%81%8A%E3%81%AD%29%20-%E3%82%AD%E3%82%B9%E5%94%BE%20-MMD%20-%E3%81%AB%E3%82%87%E3%81%9F%20-%E5%A5%B3%E4%BD%93%E5%8C%96%20-%E8%85%90%E5%90%91%E3%81%91%20-3D%20-poser%20-blender%20-dazstudio%20-%E3%81%B5%E3%81%9F%E3%81%AA%E3%82%8A%20-%E3%83%95%E3%82%BF%E3%83%8A%E3%83%AA%20-%E3%82%B1%E3%83%A2%E3%83%8E%20-%E3%83%A1%E3%82%B9%E3%82%B1%E3%83%A2%20-%E7%94%B7%E3%81%AE%E5%AD%90%20-%E5%B0%91%E5%B9%B4%20-%E8%B5%A4%E3%81%A8%E7%99%BD%20-%E3%82%B7%E3%83%BC%E3%83%A1%E3%83%BC%E3%83%AB%20-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E5%B0%91%E5%A5%B3
Image #1
Image Id: 77636934
Processing Image Id: 77636934
Already downloaded: 77636934
Image #2
Image Id: 77632271
Processing Image Id: 77632271
Already downloaded: 77632271
Image #3
Image Id: 77615236
Processing Image Id: 77615236
Already downloaded: 77615236
Image #4
Image Id: 77604202
Processing Image Id: 77604202
Already downloaded: 77604202
Image #5
Image Id: 77561378
Processing Image Id: 77561378
Already downloaded: 77561378
Image #6
Image Id: 77534586
Processing Image Id: 77534586
Already downloaded: 77534586
Image #7
Image Id: 77530896
Processing Image Id: 77530896
Already downloaded: 77530896
Image #8
Image Id: 77523221
Processing Image Id: 77523221
Already downloaded: 77523221
Image #9
Image Id: 77515108
Processing Image Id: 77515108
Already downloaded: 77515108
Image #10
Image Id: 77511059
Processing Image Id: 77511059
Already downloaded: 77511059
Image #11
Image Id: 77506406
Processing Image Id: 77506406
Already downloaded: 77506406
Image #12
Image Id: 77502022
Processing Image Id: 77502022
Already downloaded: 77502022
Image #13
Image Id: 77501314
Processing Image Id: 77501314
Already downloaded: 77501314
Image #14
Image Id: 77491279
Processing Image Id: 77491279
Already downloaded: 77491279
Image #15
Image Id: 77490434
Processing Image Id: 77490434
Already downloaded: 77490434
Image #16
Image Id: 77481874
Processing Image Id: 77481874
Already downloaded: 77481874
Image #17
Image Id: 77473905
Processing Image Id: 77473905
Already downloaded: 77473905
Image #18
Image Id: 77460760
Processing Image Id: 77460760
Already downloaded: 77460760
Image #19
Image Id: 77429330
Processing Image Id: 77429330
Already downloaded: 77429330
Image #20
Image Id: 77428853
Processing Image Id: 77428853
Already downloaded: 77428853
Image #21
Image Id: 77426309
Processing Image Id: 77426309
Already downloaded: 77426309
Image #22
Image Id: 77417199
Processing Image Id: 77417199
Skipping image_id: 77417199 because contains blacklisted tags: ハニーセレクト
Image #23
Image Id: 77406117
Processing Image Id: 77406117
Already downloaded: 77406117
Image #24
Image Id: 77396227
Processing Image Id: 77396227
Already downloaded: 77396227
Image #25
Image Id: 77359479
Processing Image Id: 77359479
Already downloaded: 77359479
Image #26
Image Id: 77358357
Processing Image Id: 77358357
Already downloaded: 77358357
Image #27
Image Id: 77329435
Processing Image Id: 77329435
Already downloaded: 77329435
Image #28
Image Id: 77327788
Processing Image Id: 77327788
Already downloaded: 77327788
Image #29
Image Id: 77320596
Processing Image Id: 77320596
Already downloaded: 77320596
Image #30
Image Id: 77314510
Processing Image Id: 77314510
Already downloaded: 77314510
Image #31
Image Id: 77307264
Processing Image Id: 77307264
Already downloaded: 77307264
Image #32
Image Id: 77297020
Processing Image Id: 77297020
Skipping image_id: 77297020 because contains blacklisted tags: ハニーセレクト
Image #33
Image Id: 77278688
Processing Image Id: 77278688
Already downloaded: 77278688
Image #34
Image Id: 77238634
Processing Image Id: 77238634
Already downloaded: 77238634
Image #35
Image Id: 77233268
Processing Image Id: 77233268
Already downloaded: 77233268
Image #36
Image Id: 77226782
Processing Image Id: 77226782
Skipping image_id: 77226782 because contains blacklisted tags: HoneySelect
Image #37
Image Id: 77221420
Processing Image Id: 77221420
Already downloaded: 77221420
Image #38
Image Id: 77198677
Processing Image Id: 77198677
Already downloaded: 77198677
Image #39
Image Id: 77197300
Processing Image Id: 77197300
Already downloaded: 77197300
Image #40
Image Id: 77188105
Processing Image Id: 77188105
Already downloaded: 77188105
Image #41
Image Id: 77183394
Processing Image Id: 77183394
Already downloaded: 77183394
Image #42
Image Id: 77181905
Processing Image Id: 77181905
Already downloaded: 77181905
Image #43
Image Id: 77169282
Processing Image Id: 77169282
Already downloaded: 77169282
Image #44
Image Id: 77090132
Processing Image Id: 77090132
Already downloaded: 77090132
Image #45
Image Id: 77070577
Processing Image Id: 77070577
Already downloaded: 77070577
Image #46
Image Id: 77012387
Processing Image Id: 77012387
Already downloaded: 77012387
Image #47
Image Id: 76984741
Processing Image Id: 76984741
Already downloaded: 76984741
Using Partial Match (s_tag)
Looping... for https://www.pixiv.net/ajax/search/artworks/%28%E3%81%8A%E3%81%AD%E3%83%AD%E3%83%AA%20OR%20%E3%83%AD%E3%83%AA%E3%81%8A%E3%81%AD%29%20-%E3%82%AD%E3%82%B9%E5%94%BE%20-MMD%20-%E3%81%AB%E3%82%87%E3%81%9F%20-%E5%A5%B3%E4%BD%93%E5%8C%96%20-%E8%85%90%E5%90%91%E3%81%91%20-3D%20-poser%20-blender%20-dazstudio%20-%E3%81%B5%E3%81%9F%E3%81%AA%E3%82%8A%20-%E3%83%95%E3%82%BF%E3%83%8A%E3%83%AA%20-%E3%82%B1%E3%83%A2%E3%83%8E%20-%E3%83%A1%E3%82%B9%E3%82%B1%E3%83%A2%20-%E7%94%B7%E3%81%AE%E5%AD%90%20-%E5%B0%91%E5%B9%B4%20-%E8%B5%A4%E3%81%A8%E7%99%BD%20-%E3%82%B7%E3%83%BC%E3%83%A1%E3%83%BC%E3%83%AB%20-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E5%B0%91%E5%A5%B3?word=%28%E3%81%8A%E3%81%AD%E3%83%AD%E3%83%AA%20OR%20%E3%83%AD%E3%83%AA%E3%81%8A%E3%81%AD%29%20-%E3%82%AD%E3%82%B9%E5%94%BE%20-MMD%20-%E3%81%AB%E3%82%87%E3%81%9F%20-%E5%A5%B3%E4%BD%93%E5%8C%96%20-%E8%85%90%E5%90%91%E3%81%91%20-3D%20-poser%20-blender%20-dazstudio%20-%E3%81%B5%E3%81%9F%E3%81%AA%E3%82%8A%20-%E3%83%95%E3%82%BF%E3%83%8A%E3%83%AA%20-%E3%82%B1%E3%83%A2%E3%83%8E%20-%E3%83%A1%E3%82%B9%E3%82%B1%E3%83%A2%20-%E7%94%B7%E3%81%AE%E5%AD%90%20-%E5%B0%91%E5%B9%B4%20-%E8%B5%A4%E3%81%A8%E7%99%BD%20-%E3%82%B7%E3%83%BC%E3%83%A1%E3%83%BC%E3%83%AB%20-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E5%B0%91%E5%A5%B3&page=2
Image #48
Image Id: 77636934
Processing Image Id: 77636934
Already downloaded: 77636934
Image #49
Image Id: 77632271
Processing Image Id: 77632271
Already downloaded: 77632271
Image #50
Image Id: 77615236
Processing Image Id: 77615236
Already downloaded: 77615236
Image #51
Image Id: 77604202
Processing Image Id: 77604202
Already downloaded: 77604202
Image #52
Image Id: 77561378
Processing Image Id: 77561378
Already downloaded: 77561378
Image #53
Image Id: 77534586
Processing Image Id: 77534586
Already downloaded: 77534586
Image #54
Image Id: 77530896
Processing Image Id: 77530896
Already downloaded: 77530896
Image #55
Image Id: 77523221
Processing Image Id: 77523221
Already downloaded: 77523221
Image #56
Image Id: 77515108
Processing Image Id: 77515108
Already downloaded: 77515108
Image #57
Image Id: 77511059
Processing Image Id: 77511059
Already downloaded: 77511059
Image #58
Image Id: 77506406
Processing Image Id: 77506406
Already downloaded: 77506406
Image #59
Image Id: 77502022
Processing Image Id: 77502022
Already downloaded: 77502022
Image #60
Image Id: 77501314
Processing Image Id: 77501314
Already downloaded: 77501314
Image #61
Image Id: 77491279
Processing Image Id: 77491279
Already downloaded: 77491279
Image #62
Image Id: 77490434
Processing Image Id: 77490434
Already downloaded: 77490434
Image #63
Image Id: 77481874
Processing Image Id: 77481874
Already downloaded: 77481874
Image #64
Image Id: 77473905
Processing Image Id: 77473905
Already downloaded: 77473905
Image #65
Image Id: 77460760
Processing Image Id: 77460760
Already downloaded: 77460760
Image #66
Image Id: 77429330
Processing Image Id: 77429330
Already downloaded: 77429330
Image #67
Image Id: 77428853
Processing Image Id: 77428853
Already downloaded: 77428853
Image #68
Image Id: 77426309
Processing Image Id: 77426309
Already downloaded: 77426309
Image #69
Image Id: 77417199
Processing Image Id: 77417199
Skipping image_id: 77417199 because contains blacklisted tags: ハニーセレクト
Image #70
Image Id: 77406117
Processing Image Id: 77406117
Already downloaded: 77406117
Image #71
Image Id: 77396227
Processing Image Id: 77396227
Already downloaded: 77396227
Image #72
Image Id: 77359479
Processing Image Id: 77359479
Already downloaded: 77359479
Image #73
Image Id: 77358357
Processing Image Id: 77358357
Already downloaded: 77358357
Image #74
Image Id: 77329435
Processing Image Id: 77329435
Already downloaded: 77329435
Image #75
Image Id: 77327788
Processing Image Id: 77327788
Already downloaded: 77327788
Image #76
Image Id: 77320596
Processing Image Id: 77320596
Already downloaded: 77320596
Image #77
Image Id: 77314510
Processing Image Id: 77314510
Already downloaded: 77314510
Image #78
Image Id: 77307264
Processing Image Id: 77307264
Already downloaded: 77307264
Image #79
Image Id: 77297020
Processing Image Id: 77297020
Skipping image_id: 77297020 because contains blacklisted tags: ハニーセレクト
Image #80
Image Id: 77278688
Processing Image Id: 77278688
Already downloaded: 77278688
Image #81
Image Id: 77238634
Processing Image Id: 77238634
Already downloaded: 77238634
Image #82
Image Id: 77233268
Processing Image Id: 77233268
Already downloaded: 77233268
Image #83
Image Id: 77226782
Processing Image Id: 77226782
Skipping image_id: 77226782 because contains blacklisted tags: HoneySelect
Image #84
Image Id: 77221420
Processing Image Id: 77221420
Already downloaded: 77221420
Image #85
Image Id: 77198677
Processing Image Id: 77198677
Already downloaded: 77198677
Image #86
Image Id: 77197300
Processing Image Id: 77197300
Already downloaded: 77197300
Image #87
Image Id: 77188105
Processing Image Id: 77188105
Already downloaded: 77188105
Image #88
Image Id: 77183394
Processing Image Id: 77183394
Already downloaded: 77183394
Image #89
Image Id: 77181905
Processing Image Id: 77181905
Already downloaded: 77181905
Image #90
Image Id: 77169282
Processing Image Id: 77169282
Already downloaded: 77169282
Image #91
Image Id: 77090132
Processing Image Id: 77090132
Already downloaded: 77090132
Image #92
Image Id: 77070577
Processing Image Id: 77070577
Already downloaded: 77070577
Image #93
Image Id: 77012387
Processing Image Id: 77012387
Already downloaded: 77012387
Image #94
Image Id: 76984741
Processing Image Id: 76984741
Already downloaded: 76984741
Using Partial Match (s_tag)
Looping... for https://www.pixiv.net/ajax/search/artworks/%28%E3%81%8A%E3%81%AD%E3%83%AD%E3%83%AA%20OR%20%E3%83%AD%E3%83%AA%E3%81%8A%E3%81%AD%29%20-%E3%82%AD%E3%82%B9%E5%94%BE%20-MMD%20-%E3%81%AB%E3%82%87%E3%81%9F%20-%E5%A5%B3%E4%BD%93%E5%8C%96%20-%E8%85%90%E5%90%91%E3%81%91%20-3D%20-poser%20-blender%20-dazstudio%20-%E3%81%B5%E3%81%9F%E3%81%AA%E3%82%8A%20-%E3%83%95%E3%82%BF%E3%83%8A%E3%83%AA%20-%E3%82%B1%E3%83%A2%E3%83%8E%20-%E3%83%A1%E3%82%B9%E3%82%B1%E3%83%A2%20-%E7%94%B7%E3%81%AE%E5%AD%90%20-%E5%B0%91%E5%B9%B4%20-%E8%B5%A4%E3%81%A8%E7%99%BD%20-%E3%82%B7%E3%83%BC%E3%83%A1%E3%83%BC%E3%83%AB%20-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E5%B0%91%E5%A5%B3?word=%28%E3%81%8A%E3%81%AD%E3%83%AD%E3%83%AA%20OR%20%E3%83%AD%E3%83%AA%E3%81%8A%E3%81%AD%29%20-%E3%82%AD%E3%82%B9%E5%94%BE%20-MMD%20-%E3%81%AB%E3%82%87%E3%81%9F%20-%E5%A5%B3%E4%BD%93%E5%8C%96%20-%E8%85%90%E5%90%91%E3%81%91%20-3D%20-poser%20-blender%20-dazstudio%20-%E3%81%B5%E3%81%9F%E3%81%AA%E3%82%8A%20-%E3%83%95%E3%82%BF%E3%83%8A%E3%83%AA%20-%E3%82%B1%E3%83%A2%E3%83%8E%20-%E3%83%A1%E3%82%B9%E3%82%B1%E3%83%A2%20-%E7%94%B7%E3%81%AE%E5%AD%90%20-%E5%B0%91%E5%B9%B4%20-%E8%B5%A4%E3%81%A8%E7%99%BD%20-%E3%82%B7%E3%83%BC%E3%83%A1%E3%83%BC%E3%83%AB%20-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E5%B0%91%E5%A5%B3&page=3

Note the recurring image ids (48 is the same as 1, 49 is the same as 2, etc). This is just an example of the first 2 pages as all pages will fetch the same works (the ones on page 1) until they hit expected results/48 so it was useless to loop for longer than that, they will all be the same as 1-47.

**Comment by Nandaka** [comment]
ah, I think pass the wrong param, it should p= instead of page=

**Comment by Nandaka** [comment]
can you try commit: c18f236

**Comment by AgentThirteen** [comment]
I've just tested `c18f236`. That was it, it's working as intended now!
Thank you very much for your quick replies and hard work!

**Comment by AgentThirteen** [comment]
I end up reopening this myself, sorry.

All goes well up to page 1000 then... Well I kinda suspected it would go wrong. To test it, simply start at page 999 or 1000.
This will only realistically happen if you're grabbing 48,000 results or more and a dirty workaround is to have the same query run backwards with `old` to get whatever was left (unless there are more than 96,000 results of course):

```
Hit page 1000, trying to get workdate for last image id: 8014168
Error at process_tags() at page 1001: (<type 'exceptions.TypeError'>, TypeError('this constructor takes no arguments',), <traceback object at 0x03C93CD8>)
Cannot dump page for search tags:
Traceback (most recent call last):
  File "pixivutil2.py", line 2405, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "pixivutil2.py", line 2124, in main_loop
    menu_download_by_tags(op_is_valid, args)
  File "pixivutil2.py", line 1635, in menu_download_by_tags
    use_tags_as_dir=__config__.useTagsAsDir, bookmark_count=bookmark_count, oldest_first=oldest_first)
  File "pixivutil2.py", line 1105, in process_tags
    if search_page is not None:
UnboundLocalError: local variable 'search_page' referenced before assignment
```

**Comment by Nandaka** [comment]
Looks like the infinite looping also doesn't work properly anymore if the range is more than 1 year.

For example:
https://www.pixiv.net/search.php?word=%E3%81%91%E3%81%84%E3%81%8A%E3%82%93%21&order=date&p=1000

I need to loop using this search
https://www.pixiv.net/search.php?word=%E3%81%91%E3%81%84%E3%81%8A%E3%82%93%21&order=date&scd=2013-03-05&ecd=2012-03-06

Removing the scd or exceeding it with more than 1 year range will skew the result

might missed 1 day result:
https://www.pixiv.net/search.php?word=%E3%81%91%E3%81%84%E3%81%8A%E3%82%93%21&order=date&scd=2013-03-06&ecd=2012-03-06

Somehow start at 2011-03-07:
https://www.pixiv.net/search.php?word=%E3%81%91%E3%81%84%E3%81%8A%E3%82%93%21&order=date&ecd=2012-03-06

start at 2018-03-06
https://www.pixiv.net/search.php?word=%E3%81%91%E3%81%84%E3%81%8A%E3%82%93%21&order=date&scd=2019-03-05&ecd=2012-03-06

**Comment by Nandaka** [comment]
scracth that, I forgot that endless loop only for sort by new date first...

**Comment by Nandaka** [comment]
try this commit: aa6b3f6

**Comment by AgentThirteen** [comment]
I've just tried b50a80131b18403197287f6e8f98940d3a87a396 (latest) but unfortunately, it still doesn't work.
Console dump (replaced the large query with `(query)` to make it easier to parse here)
```
Hit page 1000, trying to get workdate for last image id: 8070137
Hit page 1000, looping back to page 1 with ecd: 2010-01-07.
Using Partial Match (s_tag)
Looping... for https://www.pixiv.net/ajax/search/artworks/(query)&ecd=2010-01-07
Using Partial Match (s_tag)
Looping... for https://www.pixiv.net/ajax/search/artworks/(query)&ecd=2010-01-07&p=2
Using Partial Match (s_tag)
Looping... for https://www.pixiv.net/ajax/search/artworks/(query)&ecd=2010-01-07&p=3
```
The upload date is correct for this work but passing it as `ecd` apparently does nothing anymore.
It looks like it just loops without doing anything at all besides incrementing `p`.

**Comment by Nandaka** [comment]
should be working on latest commit

**Comment by AgentThirteen** [comment]
Thanks, I've just launched dcdb0559eb882c19aedcc83dfb644e8736b81294 to check. It's almost fixed but something looks off...

Running from page 1000 to last:
```
Image #1726
Image Id: 2688286
Processing Image Id: 2688286
Already downloaded: 2688286
Last page: 36
done
```
That's 48,726 results and stopping on id 2688286.

Running backwards from page 1:
```
Using Partial Match (s_tag)
Looping... for https://www.pixiv.net/ajax/search/artworks/(query)&order=date
Image #1
Image Id: 4895
Processing Image Id: 4895
Already downloaded: 4895
Image #2
Image Id: 4989
Processing Image Id: 4989
Already downloaded: 4989
Image #3
Image Id: 8361
Processing Image Id: 8361
Already downloaded: 8361
Image #4
Image Id: 8924
Processing Image Id: 8924
Already downloaded: 8924
Image #5
Image Id: 9474
Processing Image Id: 9474
Already downloaded: 9474
Image #6
Image Id: 11271
Processing Image Id: 11271
Already downloaded: 11271
Image #7
Image Id: 13394
Processing Image Id: 13394
Already downloaded: 13394
Image #8
Image Id: 15338
Processing Image Id: 15338
Already downloaded: 15338
Image #9
Image Id: 19430
Processing Image Id: 19430
Already downloaded: 19430
Image #10
Image Id: 22301
Processing Image Id: 22301
Already downloaded: 22301
Image #11
Image Id: 23660
Processing Image Id: 23660
Already downloaded: 23660
Image #12
Image Id: 24862
Processing Image Id: 24862
Already downloaded: 24862
Image #13
Image Id: 28570
Processing Image Id: 28570
Already downloaded: 28570
Image #14
Image Id: 29291
Processing Image Id: 29291
Already downloaded: 29291
Image #15
Image Id: 29740
Processing Image Id: 29740
Already downloaded: 29740
Image #16
Image Id: 31440
Processing Image Id: 31440
Already downloaded: 31440
Image #17
Image Id: 32105
Processing Image Id: 32105
Already downloaded: 32105
Image #18
Image Id: 34629
Processing Image Id: 34629
Already downloaded: 34629
Image #19
Image Id: 35850
Processing Image Id: 35850
Already downloaded: 35850
Image #20
Image Id: 38514
Processing Image Id: 38514
Already downloaded: 38514
Image #21
Image Id: 40339
Processing Image Id: 40339
Already downloaded: 40339
Image #22
Image Id: 40353
Processing Image Id: 40353
Already downloaded: 40353
Image #23
Image Id: 41628
Processing Image Id: 41628
Already downloaded: 41628
Image #24
Image Id: 43822
Processing Image Id: 43822
Already downloaded: 43822
Image #25
Image Id: 44432
Processing Image Id: 44432
Already downloaded: 44432
Image #26
Image Id: 48969
Processing Image Id: 48969
Already downloaded: 48969
Image #27
Image Id: 51176
Processing Image Id: 51176
Already downloaded: 51176
Image #28
Image Id: 51970
Processing Image Id: 51970
Already downloaded: 51970
Image #29
Image Id: 53254
Processing Image Id: 53254
Already downloaded: 53254
Image #30
Image Id: 53385
Processing Image Id: 53385
Already downloaded: 53385
Image #31
Image Id: 57551
Processing Image Id: 57551
Already downloaded: 57551
Image #32
Image Id: 58157
Processing Image Id: 58157
Already downloaded: 58157
Image #33
Image Id: 64137
Processing Image Id: 64137
Already downloaded: 64137
Image #34
Image Id: 69154
Processing Image Id: 69154
Already downloaded: 69154
Image #35
Image Id: 75685
Processing Image Id: 75685
Already downloaded: 75685
Image #36
Image Id: 76979
Processing Image Id: 76979
Already downloaded: 76979
Image #37
Image Id: 76980
Processing Image Id: 76980
Already downloaded: 76980
Image #38
Image Id: 77881
Processing Image Id: 77881
Already downloaded: 77881
Image #39
Image Id: 77902
Processing Image Id: 77902
Already downloaded: 77902
Image #40
Image Id: 80967
Processing Image Id: 80967
Already downloaded: 80967
Image #41
Image Id: 83025
Processing Image Id: 83025
Already downloaded: 83025
Image #42
Image Id: 83171
Processing Image Id: 83171
Already downloaded: 83171
Image #43
Image Id: 84059
Processing Image Id: 84059
Already downloaded: 84059
Image #44
Image Id: 84358
Processing Image Id: 84358
Already downloaded: 84358
Image #45
Image Id: 87070
Processing Image Id: 87070
Already downloaded: 87070
Image #46
Image Id: 87198
Processing Image Id: 87198
Already downloaded: 87198
Image #47
Image Id: 87543
Processing Image Id: 87543
Already downloaded: 87543
End Page reached: 1
done
```
Starts at id 4895 so there must be missing results.
Checking how many results are expected from browser itself: 49,763.
That's a difference of 1,037 results (it more or less matches the amount of pages and there could have been a few more works in the few minutes running this) or so, could it be that you're grabbing 47 instead of 48 works and missing one each time?
API's supposed to be returning 48 results per page, could it be a zero-indexing issue...?

**Comment by Nandaka** [comment]
The api (https://www.pixiv.net/ajax/search/artworks/(query)&order=date) only returning 48 entry, which one of it might be ad container.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivModelWhiteCube.py#L356

I guess need to enhance this part, problem is I cannot detect whether it is the last page or not.
Maybe I can check if it return less than 48 images, then mark it as the last page?
https://github.com/Nandaka/PixivUtil2/blob/master/PixivModelWhiteCube.py#L373

Can you try to modify that line?

**Comment by AgentThirteen** [comment]
Ah, I see. Okay, just tried that with 46 instead and it still stops at the same point. Checking the actual URL in the browser to try and figure out what's going on.
