### ISSUE TITLE
Failed to get image page

### ISSUE THREAD

**Issue by fireattack** [Nandaka/PixivUtil2#554]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I can't seem to get any image page. 

### Steps to Reproduce

```
Input: 2
Image ids: 58696766
Processing Image Id: 58696766
Giving up image_id (medium): 58696766
Image ID (58696766): 9005 Failed to get page: https://www.pixiv.net//artworks/58
696766 => HTTP Error 404: Not Found, hasDumpPage=N
Stack Trace: (<class 'PixivException.PixivException'>, PixivException('Failed to
 get page: https://www.pixiv.net//artworks/58696766 => HTTP Error 404: Not Found
',), <traceback object at 0x03D9A7B0>)
Unknown errors from previous operation
Image: 58696766 ==> Failed to get page: https://www.pixiv.net//artworks/58696766
 => HTTP Error 404: Not Found
PixivDownloader2 version 20191103-beta1
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
```
As you can see, the URL seems to be incorrect. It shouldn't be 

`https://www.pixiv.net//artworks/58696766`

But

`https://www.pixiv.net/artworks/58696766`

### Versions

I use https://github.com/Nandaka/PixivUtil2/releases/tag/v20191103-beta1

**Comment by fireattack** [comment]
It seems this bug doesn't exist in master. But I can't figure out which commit fixed it.

**Comment by Nandaka** [comment]
it was related to locale https://github.com/Nandaka/PixivUtil2/commit/53cc4becd333745098e7d43746a0717155c41b8b

**Comment by fireattack** [comment]
Thanks!
