### ISSUE TITLE
[Question] Confusions about list

### ISSUE THREAD

**Issue by fireattack** [Nandaka/PixivUtil2#555]
Confusion 1:

In help, it says

```
                        4 - Download from list
                            (optional: followed by path to list and optional tag)
```

But I failed to find a way to follow a "path to list":

Tried `py -2 PixivUtil2.py -s 4 list2.txt`, doesn't work. It still will only read hard-coded `list.txt`.

Confusion 2:

It seems that you have to enable "uselist" in Settings to enable *any* list-related functionality.
However, the description in help file:

```
uselist       ==> set to 'True' to parse list.txt.
                  This will update the DB content from the list.txt (member_id
                  and custom folder).
```
gives me the impression that even when it is `False`, you should still be able to manually download from list.txt using `4`, just that it won't be added to database.

**Comment by Nandaka** [comment]
1. It should take the list as the argument. Please note that the list must be in the downloadListDirectory from config.ini

https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L2248
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1704

2. Yep, it just won't import the ids from the list to the db.

**Comment by fireattack** [comment]
> 1. It should take the list as the argument. Please note that the list must be in the downloadListDirectory from config.ini
> 
> https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L2248
> https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1704

I tried it again, it will only parse the list file if `uselist` is set to `False`, and even then, it doesn't seem to work:

```
PixivDownloader2 version 20191105-beta2
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading g:\_temp\PixivUtil2\config.ini ...
done.
Using default DB Path: g:\_temp\PixivUtil2\db.sqlite
Creating database... done.
Using Username: fireattack
Trying to log in with saved cookie
Login successful.
My User Id: 222813.
Premium User: False.
Processing member id from .\list2.txt
Processing from database.
Found 0 items.
PixivDownloader2 version 20191105-beta2
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
```

(My list2.txt file has a single ID of `14438469`, but it doesn't parse it.)

**Comment by Nandaka** [comment]
DB update only parse from list.txt

https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L2334

**Comment by fireattack** [comment]
> DB update only parse from list.txt
> 
> https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L2334

I get that, the problem is if `processFromDb` is set to true and called, it won't parse the list you passed as an argument (because it is in `else`)

**Comment by fireattack** [comment]
Understood that, but I'm just trying to download from a list file, not want to add members to the DB

**Comment by Nandaka** [comment]
will update to skip the list.txt import to db if it doesn't exits.
