### ISSUE TITLE
Unable to download images: Stack Trace: (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'artist'",), <traceback object at 0x04346058>)

### ISSUE THREAD

**Issue by ShuchitaBanthia** [Nandaka/PixivUtil2#557]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]
Getting this error when trying to download images today. Worked fine yesterday.
Stack Trace: (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'artist'",), <traceback object at 0x04346058>)

Referred to https://github.com/Nandaka/PixivUtil2/issues/182 and tried changing language on pixiv to english/japanese. Did not impact anything. Still getting the same error.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions
PixivDownloader2 version 20190919

You can get this information from executing `PixivUtil2.py --help`.

**Comment by ShuchitaBanthia** [comment]
[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
userobots = True
timeout = 60
retry = 3
retrywait = 5
downloaddelay = 2
checknewversion = True
enablesslverification = True

[Debug]
loglevel = DEBUG
enabledump = True
skipdumpfilter = 
dumpmediumpage = False
dumptagsearchpage = False
debughttp = False

[IrfanView]
irfanviewpath = C:\Program Files\IrfanView
startirfanview = False
startirfanslide = False
createdownloadlists = False

[Settings]
downloadlistdirectory = .
uselist = False
processfromdb = True
overwrite = False
daylastupdated = 7
rootdirectory = .\images
alwayscheckfilesize = False
checkupdatedlimit = 0
downloadavatar = True
useblacklisttags = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = False
writeimagejson = False
datediff = 0
backupoldfile = False
enableinfiniteloop = False
verifyimage = False
writeurlindescription = False
urlblacklistregex = 
dbpath = 
useblacklistmembers = False
setlastmodified = True
uselocaltimezone = False

[Filename]
filenameformat = %artist% (%member_id%)\%urlFilename% - %title%
filenamemangaformat = %artist% (%member_id%)\%urlFilename% - %title%
filenameinfoformat = %artist% (%member_id%)\%urlFilename% - %title%
avatarnameformat = 
tagsseparator = , 
createmangadir = False
usetagsasdir = False
urldumpfilename = url_list_%Y%m%d

[Authentication]
username = <USERNAME>
password = <PASSWORD>
cookie = <COOKIE>
refresh_token = None

[Pixiv]
numberofpage = 0
r18mode = False
dateformat = 

[FFmpeg]
ffmpeg = ffmpeg
ffmpegcodec = libvpx-vp9
ffmpegparam = -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p
webpcodec = libwebp
webpparam = -lossless 0 -q:v 90 -loop 0 -vsync 2 -r 999

[Ugoira]
writeugoirainfo = False
createugoira = False
deletezipfile = False
creategif = False
createapng = False
deleteugoira = False
createwebm = False
createwebp = False

**Comment by Nandaka** [comment]
duplicate with https://github.com/Nandaka/PixivUtil2/issues/556

also try the beta2
