### ISSUE TITLE
Side effect: I log everything that happens on my zfs and no files are deleted, but put in a snapshot.

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#560]
Side effect: I log everything that happens on my zfs and no files are deleted, but put in a snapshot.
Could you try at once when the script is loaded and then have a switch between the two branches?
It would mitigate the side effect and still fix the issue.

_Originally posted by @whinette in https://github.com/Nandaka/PixivUtil2/issues/548#issuecomment-549584924_

**Comment by Nandaka** [comment]
not sure on how making branches @github as I don't like remote branches, also it was before the pixiv changes it layout, but I guess it won't have any effect as I put a test section to check it able to create a directory with existing encoding.

https://github.com/Nandaka/PixivUtil2/commit/9363e926aba0334cd2d5912ea6594b2d23b1c326#diff-7a612caa8f02f7c30e49d68a8c1ab43fR171

You can remove the whole try..catch section to simulate previous behaviour before pull request from @DukeValentine

**Comment by whinette** [comment]
About branches I meant between UTF-8 capable FS and uncapable. :)
I will take some time this week-end to look into it deeper

**Comment by whinette** [comment]
I've refactored the test to be run once, but I don't think there should be any problem to just force the string to be encoded in utf-8 all the time.
@Nandaka see PR https://github.com/Nandaka/PixivUtil2/pull/563

**Comment by Nandaka** [comment]
Somehow windows got screwed if the filename is encoded in utf8 last time I try that.

**Comment by whinette** [comment]
Ok I see. Thanks for the merge. :)
