### ISSUE TITLE
'NoneType' object has no attribute 'imageId'

### ISSUE THREAD

**Issue by HydroHydro** [Nandaka/PixivUtil2#561]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Tried downloading this member: https://www.pixiv.net/member.php?id=1129046

Got this error: 
'NoneType' object has no attribute 'imageId'
Dumping html to: Error medium page for image 62079711.html
Stack Trace: (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'imageId'",), <traceback object at 0x0407B170>)

Tested with newest non-beta version of PixivUtil2: v20190917

EDIT: Works with latest beta. I guess it was fixed...

**Comment by Nandaka** [comment]
ya, some changes on the layout from pixiv.
