### ISSUE TITLE
Mojibake in metadata

### ISSUE THREAD

**Issue by zsitvaij** [Nandaka/PixivUtil2#562]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

On some (not all) artworks, title and tags are different and gibberish compared to opening Pixiv page in browser. This is on Linux and locale en_US.utf8, and independent of Pixiv user interface language (tested English and Japanese).

### Steps to Reproduce

1. Download by image_id 
2. 77717834
3. Observe gibberish

**Expected behavior:**
Expected tags to match those on Pixiv page https://www.pixiv.net/en/artworks/77717834
Title = Nah-nah…
Tags = ペルソナ5, P5D, 高巻杏

**Actual behavior:** 
Title = Nah-nahâ&euro;¦
Tags = ã&fnof;&scaron;ã&fnof;«ã&sbquo;½ã&fnof;&Scaron;5, P5D, é«&tilde;å·»æ??

### Versions
20191106-beta3, git HEAD.

**Comment by Nandaka** [comment]
I don't have linux box, so I cannot really test it.
The code itself should be creating the file with utf8 encoding.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivModel.py#L502

**Comment by zsitvaij** [comment]
Same results testing on Windows. From the artist in question, from image_id 77076403 and onward tags are illegible, images older than that download with legible tags.

**Comment by Nandaka** [comment]
should be ok in latest commit (at least in windows)

**Comment by zsitvaij** [comment]
Thanks! I can confirm it's fixed on Linux as well.
