### ISSUE TITLE
Number of images downloaded does not match the number displayed

### ISSUE THREAD

**Issue by puffinkins** [Nandaka/PixivUtil2#564]
Minor error, it seems.

### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

https://imgur.com/a/U6eR3vX

### Steps to Reproduce

1. Download by member id
2. Download 1 pages

**Expected behavior:** Should either show it out of 48 or download 24 

**Actual behavior:** It downloads the 48 images of a page and exceeds the 24 given in the window title

### Versions

20191106-beta3

**Comment by whinette** [comment]
Aren't the +5 manga image (@ from multi images submissions) ?

**Comment by Nandaka** [comment]
maybe need to replace the term 'image' to 'post', as it doesn't count the extra images in the title.

**Comment by puffinkins** [comment]
The +5 are images I've already downloaded, so it skips.

**Comment by cammykitten** [comment]
I'm also experiencing a similar issue in v20191111 released earlier today. When downloading by member id it seems to skip over certain posts randomly and only download, say, 47 out of 136 images when there's no limit set

**Comment by Nandaka** [comment]
any logging for that?
