### ISSUE TITLE
Fanbox Download by artist id issue - access denied

### ISSUE THREAD

**Issue by densetsumeru** [Nandaka/PixivUtil2#565]
Using 20191111 updated version

### Description

Unable to use pixivutil to download from my supported fanbox creators

### Steps to Reproduce

Opened pixivdownloader
entered f2 download by artist id
entered artist ID
Max page = 0 or Max page = 1

**Expected behavior:** [What you expected to happen]

PixivUtil would download the various image posts for me.

**Actual behavior:** [What actually happened]

Following error text popped up:

Using 0Auth to retrieve member info for : [pixivID]
access_denied
Failed to login using 0Auth
press enter to exit.

pixivutil won't go any further.

### Versions
20191111

You can get this information from executing `PixivUtil2.py --help`.

**Comment by yzaoui** [comment]
Been getting the same issue since I first started using PixivUtil2 two weeks ago. I've tried looking into the code to no avail. I feel like the culprit might be that `https://oauth.secure.pixiv.net/auth/token` has been moved? Can anyone else confirm that they don't get a 404 from requesting their token there?

**Comment by Nandaka** [comment]
Weird, tested the PixivOAuth module and it able to login

**Comment by yzaoui** [comment]
It specifically only happens with Fanbox downloads. Looking at it more closely I seem to be getting `{"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}`. No proxies, username/password/cookie present in config.ini.

Searching the web, this error code came up recently when `X-Client-Time` and `X-Client-Hash` were added as requirements, but that's not a problem anymore. Any ideas what else it could be?

**Comment by Syampuuh** [comment]
Also getting the issue, and I am also getting a 404 from `https://oauth.secure.pixiv.net/auth/token`.

**Comment by Nandaka** [comment]
you will get 404 to that page if you supply it without any parameter. Check your PC clock because it quite time sensitive? If you have python 2.7 installed, maybe you can try to run it from sourcecode.

**Comment by yzaoui** [comment]
Right, looks like it returns a 404 but it's not actually missing, that's just their response. But with the provided headers, it returns the 1508 error I mentioned above. I've been running it from sourcecode on python 2.7. I've synced up my time with the internet.

**Comment by Nandaka** [comment]
@yzaoui get the latest commit and can you run the PixivOAuth.py in the console and copy the refresh token to `config.ini`. It should do self test to retrieve the artist info with oAuth header

![image](https://user-images.githubusercontent.com/836867/68997012-90007d80-08dc-11ea-8b5d-fba319701417.png)

**Comment by yzaoui** [comment]
![image](https://user-images.githubusercontent.com/9062006/68997163-5fcfc500-0871-11ea-9b35-08bcbd0f7c13.png)
I don't think I ever get the chance to receive a refresh token because the request is denied every time. My config.ini is the default, except I filled in my `username`, `password`, and `cookie` from my `PHPSESSID`.

**Comment by Nandaka** [comment]
Looks like your ip address is blocked/banned by pixiv? If you are using firewall/antivirus, maybe try to temporarily disable it (maybe it strip some headers value sent to the server). Alternatively, try to use proxy?

**Comment by yzaoui** [comment]
Hmm, I turned off my firewall, I tried a proxy with different IPs, I created a new account, all of these attempts give me the same `access_denied` response. I can access everything on the browser version just fine, I seem to only have an issue with OAuth. I barely use Pixiv and haven't abused its servers, I wonder why I'd be restricted..

The mobile apps use OAuth right? I just tried the Android app for the first time and it works just fine. Although there is no Fanbox on it.. I'm not sure what to try next.

**Comment by Nandaka** [comment]
Can you try the latest commit 501498e? updated the android app version for oAuth and I can login just fine by running `test_OAuth()` method for testing.

**Comment by yzaoui** [comment]
Still the same error sadly. I even tried proxying to another country and creating a new account there, in case they store my sign up IP, and I still get `access_denied`. There must be something in common with me and the two people above with the same issue.

**Comment by Nandaka** [comment]
can you try it on different computer?

**Comment by yzaoui** [comment]
Same issue on my other windows computer, hmm..

**Comment by Nandaka** [comment]
Try to use fiddler and analyze the differences between your PC and android client? I'm using fiddler and as long it sent the same kind of request header during login, it will be accepted.

**Comment by yzaoui** [comment]
Did you manage to analyze the official android app? I'm on Android 9, installed Fiddler's cert, I can sniff browser requests but not apps like Pixiv. I found out that starting with Android 7 apps no longer use user-installed certificates.

**Comment by Nandaka** [comment]
@yzaoui  I'm using nox emulator, which still running on android 4 😄 
anyway, merged the code.

**Comment by yzaoui** [comment]
Ohh yeah that makes sense.

@densetsumeru @Syampuuh can you guys confirm it's been fixed for you with [the latest release](https://github.com/Nandaka/PixivUtil2/releases/latest)? If so this can be closed :)

**Comment by densetsumeru** [comment]
@yzaoui good to go!
