### ISSUE TITLE
Download by Tags (Option 3) always stop after first page downloaded

### ISSUE THREAD

**Issue by polujm9** [Nandaka/PixivUtil2#568]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Download by Tags always stop after downloaded image#60

### Steps to Reproduce

1. Insert 3 for Tags download
2. Insert Tag I want to download (ガールズ&パンツァー)
3. skip bookmark count
4. skip s_Tag
5. Insert n for not oldest first
6. skip start page to start from page 1 (it's same if start from page 2)
7. Insert 100 to set end page (skip for no limit is same)
8. skip start date and end date
9. run and download 

**Expected behavior:** Should run until limit page 100

**Actual behavior:** Stop at first page (last is Image#60)

### Versions

v20191111 - Single Days Edition

**Comment by Twi-Hard** [comment]
Using option 7 (Download from tags list) it downloads the first 60 images of each tag.

**Comment by Twi-Hard** [comment]
I tested the most recent 4 versions and the issue started in version pixivutil20191106-beta3.

**Comment by charnameLipo** [comment]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/3848396/pixivutil.log)

**Comment by polujm9** [comment]
heres my log
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/3849270/pixivutil.log)

**Comment by Nandaka** [comment]
Looks like they increase the returned post count to 60. 
The other ways is just to keep fetching until it didn't return any post.
