### ISSUE TITLE
Need an option "download page delay" !

### ISSUE THREAD

**Issue by crskycode** [Nandaka/PixivUtil2#569]
My network proxy crash because download bookmark pages too fast.
Need an option "download page delay" !

--------------  output -------------
Importing user's bookmarked image from page 1
Source URL: https://www.pixiv.net/bookmark.php?p=1
 found 20 images.
....
Importing user's bookmarked image from page 9
Source URL: https://www.pixiv.net/bookmark.php?p=9
Error at process_image_bookmark(): (<class 'urllib2.URLError'>, ....
--------------  output -------------
!!! MY PROXY CRASHED !!!

**Comment by Nandaka** [comment]
there is a download delay for the actual image download, but it won't apply when retrieving the list.

maybe you need to check your proxy?

**Comment by crskycode** [comment]
> there is a download delay for the actual image download, but it won't apply when retrieving the list.
> 
> maybe you need to check your proxy?

I know, but I want to add a delay for download the image list.
Because this error always occurs when it downloads the image list too fast. ( In an uncertain page )
It cannot re-download the error page.
