### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-35: ordinal not in range(128)

### ISSUE THREAD

**Issue by tempac321** [Nandaka/PixivUtil2#573]
### Prerequisites

* [x] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
when downloading my bookmarked images, at some point on a random image it says there is some error in the encoding. 
here is a pastebin of the output in my terminal (i have replaced some details with <...>)
https://pastebin.com/FSPen0uu
The problem exist when i try to download that image individualy with action 2 and it seems to be the username of the acount with that image because i can't save anything from that user.

### Steps to Reproduce
random but happens on the same image every time. **For example, on image_id=50549969**

### Versions
PixivDownloader2 version 20191118

**Comment by Nandaka** [comment]
closed, dupes with #574
