### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-35: ordinal not in range(128)

### ISSUE THREAD

**Issue by tempac3212** [Nandaka/PixivUtil2#574]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

while downloading my bookmarked images at some point on a random image it stops with an error about encoding, i believe this is due to the username of the account that uploaded the image since i can't download anything from them 
Terminal output (i have replaced some details with <...>) : https://pastebin.com/FSPen0uu

### Steps to Reproduce

it happens randomly but on the same image every thime, **for exampe in image_id=50549969**

### Versions
PixivDownloader2 version 20191118

**Comment by Nandaka** [comment]
latest version require python 3.
