### ISSUE TITLE
filenameinfoformat setting addition. 

### ISSUE THREAD

**Issue by nsater** [Nandaka/PixivUtil2#575]
Hi,

Is it possible add an option to save 'filenameinfoformat' output to the directory that the file is downloaded to? 

For example, in my settings I have manga and illustration download into different folders, but with the current 'filenameinfoformat' setting it only allows one directory. 

"filenameformat = %artist% (%member_id%)\%urlFilename% - %title%"
"filenamemangaformat = %artist% (%member_id%)\Manga\%title%\%urlFilename% - %title%"
"filenameinfoformat = %artist% (%member_id%)\%urlFilename% - %title%"

Thanks

**Comment by Nandaka** [comment]
you can use `\` as the path separator

**Comment by nsater** [comment]
I have `\` In my settings above, they just didn't show up in my post. See picture.
![!2019-11-24 00_33_05-_R__Programs_pixivutil_config (2) ini - Notepad++](https://user-images.githubusercontent.com/30016839/69492064-172d9280-0e95-11ea-8056-62ef3a1cb17e.png)

I'm asking can the illustration json be written to the "filenameformat" directroy and the manga json be written to the "filenamemangaformat" directory?

Maybe adding a "FileNameMangaInfoFormat" setting.

Thanks.

**Comment by bluerthanever** [comment]
I have always been bothered by the formats actually. Thanks to this I don't have to look for manga info.
But, there's still this fanbox filename format pain in the ass... I actually am wondering if there is any possibility that we can have fanboxfilenamefomat, fanboxinfoformat, fanboxmangaformat and fanboxmangainfoformat. Especially that for fanbox posts, if the post contains multiple images it would be considered manga, and the images in the posts will be stored according to filenamemangaformat, while the cover image and post info being stored according to filenameformat.
If needed, I can open another issue for this.

**Comment by Nandaka** [comment]
well, you can create 2 instance and use that for Fanbox?

**Comment by bluerthanever** [comment]
Ok. Point taken.
