### ISSUE TITLE
Do not download images with file size lower or higher than specified

### ISSUE THREAD

**Issue by ItaloKnox** [Nandaka/PixivUtil2#576]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I recently lost a collection of almost 1000 pages of bookmarks downloaded from my account, and even though I can download them all again, unfortunately pixiv is way too slow to handle this many pages even with multiple instances of PixivUtil2 open.

Is there any way I can set PixivUtil2 to skip certain images that won't meet a file size criteria? I've seen the possibility briefly mentioned in issue #499, but I have no idea if it's implemented or not. If I can call it as an argument, even better.

As for examples, I'm looking for something like ``>3m`` or ``<1000k``, but any kind should be okay as long as it matches anything below or higher a certain value (in kilobytes or megabytes).

**Comment by Nandaka** [comment]
can you filter the image size from the website? else I still need to fetch the filesize for each images. also, how to handle multi-images post?

**Comment by ItaloKnox** [comment]
That was fast. 😄 

I want to get the images from my bookmarks, and as far as I'm aware, I can't sort or filter by size. I'm okay with fetching the sizes with a HEAD request for each image, I just want to skip downloading it if it doesn't match the criteria. 

In the ideal world, this would go through each multi-images post and do the work, but I'm okay with skipping the whole post if the first image doesn't match the criteria. Whatever works best and is easier to code.

**Comment by Nandaka** [comment]
it is easier to check for each images in the post, just you will have missing pages there.

HEAD checking for file size:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L202
