### ISSUE TITLE
Invalid syntax on print (PixivUtil2.py)

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#578]
Code up to date (git pull returns Already up to date)

```
  File "PixivUtil2.py", line 59
    print("\b \b", end="")
                      ^
SyntaxError: invalid syntax
```

**Comment by Nandaka** [comment]
using python 3.7?

**Comment by whinette** [comment]
Did not see the update, came back from a work trip, my bad. Nope, still using 2.7!
That's cool :) I will update my env, sorry about that.

**Comment by Nandaka** [comment]
I guess I need to move this statement on the top from the way python interpret the code. 
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L2425

Can you check if it is validated, so it will terminate before run the whole thing?

**Comment by whinette** [comment]
It doesn't, the whole file is parsed before and the validation is triggered before.
https://stackoverflow.com/posts/11277768/revisions

I suggested warpping it up but you would need to rename the whole PixivUtil2.py
