### ISSUE TITLE
Is there any way to turn off the download page delay?

### ISSUE THREAD

**Issue by YTOAA** [Nandaka/PixivUtil2#581]
I want to know how to turn this function on and off.

**Comment by Nandaka** [comment]
from readme.txt
```
downloadDelay  ==> Set random delay up to n seconds for each image post.
                   Set to 0 to disable.```

**Comment by YTOAA** [comment]
Retrieving bookmark information... [59] of [60]
I want to turn off the delay when this message appears.

**Comment by Nandaka** [comment]
I don't get what you meant? Set the downloadDelay to 0 in config.ini to disable delay for each page.
It was requested in #569
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1183
