### ISSUE TITLE
Ugoira config doesn't seem to affect output

### ISSUE THREAD

**Issue by Rongmario** [Nandaka/PixivUtil2#582]
### Description
No gif is outputed when changing configs to create a gif instead of a zip
### Steps to Reproduce

1. Change in config.ini: `creategif = True`
2. Try downloading an ugoira
3. Outputs a zip

**Expected behavior:** a gif is outputted

**Actual behavior:** still a zip just like default

### Versions
- pixivutil20191118

**Comment by whinette** [comment]
Note: webp seems to works just fine

**Comment by Nandaka** [comment]
Ensure `createugoira=True`, from readme.:

```
createugoira    ==> If set to True, it will create .ugoira file.
                    This is Pixiv own format for animated images.
deleteZipFile   ==> If set to True, it will delete the zip files from ugoira.
                    Only active if createUgoira = True.
creategif       ==> Set to True to convert ugoira file to gif.
                    Required createUgoira = True.
```

**Comment by Nandaka** [comment]
updated in latest release: https://github.com/Nandaka/PixivUtil2/releases/tag/v21091218

ensure the config above is set to True
