### ISSUE TITLE
Reseted comp and encountered issue

### ISSUE THREAD

**Issue by connerbanner** [Nandaka/PixivUtil2#583]
![Screenshot (2)](https://user-images.githubusercontent.com/58386443/69912058-4eda9400-13d9-11ea-9bb4-72825ca54400.png)

I reseted my comp to factory settings and when I tried to use PixivUtil2 again, itll just give me the "1234" before showing me this

It cant be my internet because I moved my comp to another house so it must be something else
and I downloaded it many times and did all the usual things, get pyton, set rar to unblock, and it doesn't seem to be a log account issue because even before i put in my username and password on  new extract and itll still give me same error message?

what am I missing here?

**Comment by whinette** [comment]
You need to login in a browser and retrieve the php_session id, then copy it in your conf file.

**Comment by connerbanner** [comment]
> 
> 
> You need to login in a browser and retrieve the php_session id, then copy it in your conf file.
> More info there: #505

exact same error message pops up, Ive done the same as i always used Pixiv but after reseting my comp it just doesn't work anymore.

**Comment by Nandaka** [comment]
It failed to verify the SSL certificate. Are you running from script or from the compiled exe? Are you using firewall/proxy/antivirus that perform man-in-the-middle scan? Are you using updated windows?

**Comment by connerbanner** [comment]
> 
> 
> It failed to verify the SSL certificate. Are you running from script or from the compiled exe? Are you using firewall/proxy/antivirus that perform man-in-the-middle scan? Are you using updated windows?

I run it thru power shell and even turned off my firewall to see  if it would work, nothing. I give permissions for the only 2 programs in there to pass the firewall just in case but I never had to do that before. I should be on windows 10 home since that's what it says when i go to my comps properties. Unless there's a secret update im not getting yet because Ive been checking the "check for updates" over and over again and it says im up to date.

**Comment by connerbanner** [comment]
Um so I was just re downloading stuff and as soon as I updated my flash player I went back to check and it works fine now? It seems updated flash player is a requirement because that and Photoshop are the only things Ive installed in this downtime.

**Comment by Nandaka** [comment]
> It seems updated flash player is a requirement because that and Photoshop are the only things Ive installed in this downtime.

It shouldn't have anything to do with flash player (else those using linux will have issue), but maybe the flash player updates also updates your computer Root Certificate.

Can you check by uninstalling flash player?

**Comment by connerbanner** [comment]
> 
> 
> > It seems updated flash player is a requirement because that and Photoshop are the only things Ive installed in this downtime.
> 
> It shouldn't have anything to do with flash player (else those using linux will have issue), but maybe the flash player updates also updates your computer Root Certificate.
> 
> Can you check by uninstalling flash player?

huh I did uninstall flash and it still works, but that and Photoshop are the only 2 things Ive installed? What could have changed to make it work again? The only other possible thing could be a Microsoft Visual C++ file or some other tiny windows file that got updated. I'm legit confused.

**Comment by Nandaka** [comment]
> The only other possible thing could be a Microsoft Visual C++ file or some other tiny windows file that got updated. I'm legit confused.

Try to uninstall those as see what happen?

**Comment by connerbanner** [comment]
> 
> 
> > The only other possible thing could be a Microsoft Visual C++ file or some other tiny windows file that got updated. I'm legit confused.
> 
> Try to uninstall those as see what happen?

Yup it was that, which means that yeah you have to have updated windows but there's like a delayed effect before you can use PixivUtil2 as you wait for windows to slowly update some miscellaneous files. Cause I finished resetting my comp on like Friday and it took till Monday for these Visual C++ files to get updated. But as I read up on this C++ files, they kinda get added as you install things that need them, so maybe flash player was the thing that I installed that ADDED the C++ file that made Pixiv usable again, or maybe even the photo shop file that could be the culprit. That seems more likely then the delayed effect cause as I see windows updates that got added yesterday, only 2 were installed and they were security intelligence fort windows antivirus. But that's all I got.
