### ISSUE TITLE
Member id is not displayed

### ISSUE THREAD

**Issue by YTOAA** [Nandaka/PixivUtil2#584]
![1](https://user-images.githubusercontent.com/24527825/69923197-550a6680-14e6-11ea-989b-d018b9f53a95.png)
But the image is output.

**Comment by Nandaka** [comment]
what you are trying to do? It is only import the member id from list.txt.

```
uselist       ==> set to 'True' to parse list.txt.
                  This will update the DB content from the list.txt (member_id
                  and custom folder).
daylastupdated ==> Only process member_id which x days from the last check.
processfromdb  ==> Set 'True' to use the member_id from the DB.
```

**Comment by YTOAA** [comment]
I want to copy all member id stored in db and download image again.

**Comment by Nandaka** [comment]
then most likely the member id is not saved if it empty. You also can use https://sqlitebrowser.org/ to open the database in `db.sqlite` file.
