### ISSUE TITLE
Cannot download the pixiv fanbox image when the viemo post appear

### ISSUE THREAD

**Issue by MingLaw30** [Nandaka/PixivUtil2#586]
I am downloading the image from the creator 蜜桃まむ id:532989
The program stop the download when it goes to the viemo post
I see the error here

Processing 532989, page 10
Getting posts from https://fanbox.pixiv.net/api/post.listCreator?userId=532989&maxPublishedDatetime=2019-02-28%2021%3A01%3A54&maxId=302683&limit=10
Empty content_id for embed provider = vimeo for post = 302683, please update content_provider.json.
press enter to exit.

Is there anything that I need to input in the content_id please?

**Comment by Nandaka** [comment]
can you upload the json from https://fanbox.pixiv.net/api/post.listCreator?userId=532989&maxPublishedDatetime=2019-02-28%2021%3A01%3A54&maxId=302683&limit=10 ?

**Comment by MingLaw30** [comment]
> can you upload the json from https://fanbox.pixiv.net/api/post.listCreator?userId=532989&maxPublishedDatetime=2019-02-28%2021%3A01%3A54&maxId=302683&limit=10 ?

I get the following thing on this website only
{"error":"general_error"}

**Comment by Nandaka** [comment]
Hmm, can you upload the log file then? There should be a file named `pixivutil.log` in the pixivutil folder. Compress it if possible.

**Comment by MingLaw30** [comment]
> Hmm, can you upload the log file then? There should be a file named `pixivutil.log` in the pixivutil folder. Compress it if possible.

[pixivutil.zip](https://github.com/Nandaka/PixivUtil2/files/3937240/pixivutil.zip)
Is this one ok?
