### ISSUE TITLE
cant connect again ? it worked previous version

### ISSUE THREAD

**Issue by ShiroTora** [Nandaka/PixivUtil2#587]
cant connect again ? it worked previous version, 

please help 
![11](https://user-images.githubusercontent.com/10827947/70731552-2a4eb800-1d07-11ea-88fc-0b1b0ad32083.png)

**Comment by cghctommyho** [comment]
tried renew the cookies in the config.ini?

**Comment by Nandaka** [comment]
remove the cookies in config.ini and try again? If it is asking for captcha, then you need to get the cookies from browser (check readme.txt).
