### ISSUE TITLE
Failing To Launch

### ISSUE THREAD

**Issue by DeclanEM** [Nandaka/PixivUtil2#588]
### Description

Using latest Windows binary release (pixivutil20191214) the program fails to launch with the following stack trace.

>PixivUtil2.exe
>Traceback (most recent call last):
>  File "PixivUtil2.py", line 20, in <module>
>  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
>  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
>  File "bs4\__init__.pyc", line 34, in <module>
>  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
>  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
>  File "bs4\builder\__init__.pyc", line 388, in <module>
>  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
>  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
>  File "bs4\builder\_lxml.pyc", line 16, in <module>
>  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
>  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
>SystemError: <method 'load_module' of 'zipimport.zipimporter' objects> returned NULL without setting an error

### Steps to Reproduce
1. Attempt to run PixivUtil2.exe

**Expected behavior:**
Program executes

**Actual behavior:**
Program fails to execute

### Versions
20191214 running on Windows 10 Pro x64.

**Comment by gnarf1975** [comment]
Same Problem here. Crashes right after Start. I lack the necessary knowledge about Python.

**Comment by MingLaw30** [comment]
Same here
PixivUtil2 v20191214 with Win 10 x64 Pro

**Comment by Slowbreaker** [comment]
Same problem with windows 7 Ultimate and 8.1

**Comment by Nandaka** [comment]
Updated the packages, can you redownload from https://github.com/Nandaka/PixivUtil2/releases/tag/v20191214
