### ISSUE TITLE
Cannot type password and login

### ISSUE THREAD

**Issue by lambox225** [Nandaka/PixivUtil2#595]
Its giving me some kind of error when i'm trying to log in with my account.
I used latest version (20191214-repack) even then its not working.
![problem](https://user-images.githubusercontent.com/58911486/70864881-e8857200-1f91-11ea-9449-96288b1c8830.jpg)

**Comment by Nandaka** [comment]
Can you try it on different PC? 
From the error message, looks like the server certificate cannot be validated. Either the windows is not updated or you have firewall/antivirus that intercept the ssl connection.

**Comment by lambox225** [comment]
I tried in a different PC with the latest one;
I get this:

PixivDownloader2 version 20191221
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\Users\LIP\Desktop\pixivutil20191221\config.ini ...
done.
Using default DB Path: C:\Users\LIP\Desktop\pixivutil20191221\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: lipaston
Trying to log in with saved cookie
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
Error at open_with_retry(): (<class 'urllib.error.URLError'>, URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')), <traceback object at 0x078C3588>)
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net/, please check your internet connection/firewall/antivirus.'), <traceback object at 0x078AA2E8>)
Cannot Login!
press enter to exit.

**Comment by Nandaka** [comment]
weird, looks like you have something that preventing or performing man-in-middle attact that replacing the ssl validation or simply non-updated windows or some antivirus/firewall that performing local proxy. Can you open the pixiv website without certificate warning?

Try to set `enablesslverification = False` in config.ini to disable SSL check. Please note that this is not recommended.

**Comment by Nandaka** [comment]
alternatively, try to replace the `cacert.pem` in the installation folder from https://curl.haxx.se/docs/caextract.html

**Comment by lambox225** [comment]
Dear developer,
I think it's not non-updated windows since I am using Windows 10 Enterprise with update till 1909
Previously, I was using Windows 10 Home (single language) and there is no problem.
However due to the nature of my work, I have to install the Enterprise edition.
I try and see if the above solution can work

**Comment by lambox225** [comment]
I tried with the first step: set enablesslverification = False 

PixivDownloader2 version 20191221
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\Users\LIP\Desktop\pixivutil20191221\config.ini ...
done.
Using default DB Path: C:\Users\LIP\Desktop\pixivutil20191221\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: lipaston
Trying to log in with saved cookie
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
Error at open_with_retry(): (<class 'urllib.error.URLError'>, URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')), <traceback object at 0x07AE2548>)
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net/, please check your internet connection/firewall/antivirus.'), <traceback object at 0x07AC9DE8>)
Cannot Login!
press enter to exit.

**Comment by lambox225** [comment]
I also tries changing cacert.pem with various ones from the site that you provide but still same results

PixivDownloader2 version 20191221
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\Users\LIP\Desktop\pixivutil20191221\config.ini ...
done.
Using default DB Path: C:\Users\LIP\Desktop\pixivutil20191221\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: lipaston
Trying to log in with saved cookie
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
Error at open_with_retry(): (<class 'urllib.error.URLError'>, URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')), <traceback object at 0x07E92688>)
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net/, please check your internet connection/firewall/antivirus.'), <traceback object at 0x07E78288>)
Cannot Login!
press enter to exit.

By the way, my antivirus is disabled
Pixiv website can be accessed in both firefox and chrome

**Comment by Nandaka** [comment]
this is the cacert.pem used in my pc, try to replace using this? Is the other pc is using the same ISP? 
[cacert.zip](https://github.com/Nandaka/PixivUtil2/files/4000123/cacert.zip)

I don't know if running from source code can fix this issue.

**Comment by lambox225** [comment]
It is still same no matter i set enablesslverification = False or set enablesslverification = True even after changing multiple cacert files
PixivDownloader2 version 20191221
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\Users\LIP\Desktop\pixivutil20191221\config.ini ...
done.
Using default DB Path: C:\Users\LIP\Desktop\pixivutil20191221\db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: lipaston
Trying to log in with saved cookie
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> 1 2 3 4
Error at open_with_retry(): (<class 'urllib.error.URLError'>, URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')), <traceback object at 0x07822608>)
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://www.pixiv.net/, please check your internet connection/firewall/antivirus.'), <traceback object at 0x07809308>)
Cannot Login!
press enter to exit.

**Comment by Nandaka** [comment]
looks like `enablesslverification` only used for OAuth validation, still the error is due to the root certification is either not updated or you have something that takeover the validation (e.g. vpn/antivirus/firewall). This happened to me when I'm using Forticlient, as it will act as proxy and cause the same issue. I need to totally shutdown the service. Other than that I have no clue.

**Comment by Nandaka** [comment]
Try to replace library.zip and set `enablesslverification = False` in config.ini, I have updated to disable ssl validation based on https://stackoverflow.com/a/35960702
[library.zip](https://github.com/Nandaka/PixivUtil2/files/4000440/library.zip)

**Comment by lambox225** [comment]
Now it can pass
![runnable](https://user-images.githubusercontent.com/58911486/71445855-7d3d5c00-2758-11ea-980b-9f04da86c73f.jpg)
