### ISSUE TITLE
Site changed, cannot log in with cookies or password.

### ISSUE THREAD

**Issue by puffinkins** [Nandaka/PixivUtil2#600]
### Prerequisites

* [*] Did you read FAQ section?
* [*] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Attempting to log in with either the username/password method and cookie method fails to work.

### Steps to Reproduce

1. Attempt to log in with username/password
2. Get server reply: 'Please complete the reCAPTCHA verification.'
3. Attempt to log in with cookie
4. Get error "Cookie already expired/invalid"
5. 

Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 301, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subs
criptable"), <traceback object at 0x076BE580>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not su
bscriptable"), <traceback object at 0x082B3580>)
Cannot Login!
press enter to exit.

**Expected behavior:** [What you expected to happen] Log in with the previous password or cookie method.

**Actual behavior:** [What actually happened] Receive errors.

### Versions
20191215 release

You can get this information from executing `PixivUtil2.py --help`.

**Comment by MinichB** [comment]
Q3. I cannot login to Pixiv!
      - Check your password.
      - Try to login to the Pixiv Website.
      - Try to use the config.ini on the [Authentication] section.
      - Check your date and time setting (e.g.: https://www.timeanddate.com/)
      - Disable Daylight Saving Time and try again.
      - Copy your session values from browser:
        1. Open Firefox.
        2. Go to Pixiv website and login, remember to enable [Remember Me]
           check box.
        3. Right click the page and select View Page Info.
        4. Click the Security tab.
        5. Click the View Cookies button.
        6. Look for Cookie named = PHPSESSID.
        7. Copy the content value.
        8. Open config.ini, go to [Authentication] section, paste the value
           to cookie, set keepsignedin = 1.

**Comment by puffinkins** [comment]
That isn't helpful. I've gone through these steps multiple times.

**Comment by RandomErrorkun** [comment]
Unfortunately,I met this problem few hours ago,too.The error message is quite similar.
`Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 305, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x07A2D6C8>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x079A2FA8>)
Cannot Login!
press enter to exit.`

**Comment by mperin** [comment]
I have the same problem. Patiently waiting for a fix. ;-)

**Comment by puffinkins** [comment]
I used a different account, and did not receive this error. Something must be different for some cases.

**Comment by Nandaka** [comment]
most likely they are doing some A/B testing with the login screen. I didn't get the error so far so I cannot really test it.
Also are you running from source or from the zipped archive? Please check the new release from yesterday.

**Comment by Grenaid** [comment]
That right click, page info doesn't even work in my version of FF, 71 64bit.  I can view certs, CLEAR cookies, view saved passwords, and click help.

Better I think to hit F12 for dev console, hit the storage tab and then choose cookies on the left. Look for the value on the right.  Make sure you are on the pixiv page when you do this.

**Comment by Nandaka** [comment]
I guess this is because pixiv remove the logout.php link from the site?

Currently it detect whether the user are logged in successfully using cookies based on the availability of the logout.php. I guess I need to change it to check the string for `pixiv.user.loggedIn = false;`
https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L269

**Comment by RandomErrorkun** [comment]
I created a new account and copied the new cookie to config.ini,and didn't receive this error.

Then I logged in the old acccount and copied the cookie to config.ini,the problem happened again.

PixivDownloader said"Cookie already expired/invalid.",but when I tryed to log in pixiv by changing cookie on Chrome,the old account's cookie worked.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20191220-beta1

**Comment by AdmiralHaddock** [comment]
Hello. I also have had login errors for the last few days. I have just tried the latest v20191220-beta1 version. I've followed the instructions for changing cookies and I get an error with both an old cookie and a new one.

Trying to log in with saved cookie 
Cookie already expired/invalid. 
Logging in... 
Traceback (most recent call last):
  File "/home/pi/PixivUtil2/PixivBrowserFactory.py", line 308, in login
    data['post_key'] = post_key['value']
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x73d1a408>) 
Error at doLogin(): (<class 'TypeError'>, TypeError("a bytes-like object is required, not 'BeautifulSoup'"), <traceback object at 0x73e40a68>) 
Cannot Login! 
press enter to exit.

**Comment by Xenovant** [comment]
Same here. Tried last version ( v20191220-beta1), it still happens :(

**Comment by Nandaka** [comment]
Can you replace the library.zip with the attached file and retry? It should generate `login_error.html` if the `TypeError: 'NoneType' object is not subscriptable` happen, so I can check it.
[library.zip](https://github.com/Nandaka/PixivUtil2/files/3989068/library.zip)

**Comment by Xenovant** [comment]
Tried it and yep, it generates a login_error.html. Do you need the file or you already know if that's the problem just knowing it's generated?

**Comment by Grenaid** [comment]
```Trying to log in with saved cookie
Cookie already expired/invalid.
Logging in...
Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 308, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x0BEF2DC8>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x0BF8C308>)
Cannot Login!
press enter to exit.```

**Comment by Nandaka** [comment]
Try this one?
[library.zip](https://github.com/Nandaka/PixivUtil2/files/3990936/library.zip)

**Comment by Xenovant** [comment]
It works! It still can't login on its own, but if you paste a cookie it works fine.

**Comment by Grenaid** [comment]
Works for me as well off of cookie, didn't test other.

**Comment by userskill** [comment]
how to fix it?
![sshot-001](https://user-images.githubusercontent.com/73518754/178146469-a0a5bea1-ea25-43d1-a44c-4a64588981ef.jpg)

**Comment by Nandaka** [comment]
no issue using cookie for me, check the main thread https://github.com/Nandaka/PixivUtil2/issues/814

![image](https://user-images.githubusercontent.com/836867/178169839-1dc28e35-9e7d-4ded-b843-3e11370e6075.png)
