### ISSUE TITLE
Search filter implementation

### ISSUE THREAD

**Issue by pxssy** [Nandaka/PixivUtil2#605]
This isn't exactly an issue but i'd just like to bring this up since it looks easy to implement.

currently searching by tags, i see this link being loaded and parsed "https://www.pixiv.net/ajax/search/artworks/exampe?word=example"

but there are new filters in the search like by resolution or by ratio or by software etc (resolution looks most useful) and looking at the json for resolution filter (3000x3000) it looks like "https://www.pixiv.net/ajax/search/artworks/example?word=example&wlt=3000&hlt=3000"

Maybe a new filter could be added for dimensions greater than x and y, then just tag on "&wlt=x&hlt=y" to whatever it was doing before. 

I'm not any coder by any standards, so i'm sorry if its actually more difficult than it seems, but i hope this can be added in. Thanks a lot!

**Comment by pxssy** [comment]
On the side note, I'm currently still using v20191118 since i'm not actually sure how to upgrade to python 3.8 (partially also the fear that i may mess with other stuff). Is the upgrade absolutely necessary and are there any prerequisite to upgrade?

**Comment by Nandaka** [comment]
any future update will only support python 3, as python 2 will be EOL by 2020.

Generally, you can install python 3.8.x and install the requirement using `pip install -r requirements.txt`
