### ISSUE TITLE
'checkUpdatedLimit' without using DB

### ISSUE THREAD

**Issue by panhartstuff** [Nandaka/PixivUtil2#609]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Is there a way to make 'checkUpdatedLimit' to work with 'alwaysCheckFileSize'?
Basically I want 'checkUpdatedLimit' to evaluate the number of previously downloaded images through checking filesizes instead of checking image_id in the database.

### Versions

PixivDownloader2 version 20191221

**Comment by panhartstuff** [comment]
Thank you for the commit!

**Comment by panhartstuff** [comment]
It's still not working it seems. With:
```
overwrite = False
alwayscheckfilesize = True
checkupdatedlimit = 1
```
It still continues on to try to download everything, despite having found an already existing file.

**Comment by Nandaka** [comment]
like I said, if you enable 'alwayscheckfilesize = True', it will add the delay/wait, as it actually contact Pixiv server to get the latest filesize. You must disable both overwrite and alwayscheckfilesize.

**Comment by panhartstuff** [comment]
I'm okay with the wait. But it seems there's a bit of miscommunication.

So to clarify, the desired behaviour is for PixivUtil2 to jump to the next member id once it found an 'n' amount of downloaded files in the directory. 
But the problem is that currently 'checkUpdatedLimit' can only check already downloaded images from the DB. 

So say if your DB is empty, but you already have a folder of ~100 files you have downloaded from a user from the past. You don't want to check all of them one by one, so you want the downloader to stop once it found an already downloaded image file in that directory, even if that image is not in the DB. This behaviour is currently impossible.
Even with:
```
overwrite = False
alwayscheckfilesize = False
checkupdatedlimit = 1
```
