### ISSUE TITLE
Can't download all the image from the pixiv fanbox creator

### ISSUE THREAD

**Issue by MingLaw30** [Nandaka/PixivUtil2#611]
Hello
I am going to download the images from the creator さより＠ネコぱらゲーム製作中
Here is the link https://www.pixiv.net/fanbox/creator/104409
The version of software is 20200101

And here is what I get from the software
![Screenshot 2020-01-01 23-41-42](https://user-images.githubusercontent.com/58665916/71643237-ea6d6600-2cf1-11ea-9c68-f17a7359ca4e.png)

Comparing to the fanbox website
It seems that the software can only download the images stop from this post
![Screenshot 2020-01-01 23-42-46](https://user-images.githubusercontent.com/58665916/71643241-fd803600-2cf1-11ea-8f04-78281c66595a.png)

And you can see that there are still about half of the posts not yet downloaded
![Screenshot 2020-01-01 23-43-08](https://user-images.githubusercontent.com/58665916/71643267-5fd93680-2cf2-11ea-9865-8e1c4dc9971c.png)

I believe that my account has enough permission to access to the post
![Screenshot 2020-01-01 23-59-43](https://user-images.githubusercontent.com/58665916/71643295-cfe7bc80-2cf2-11ea-92ee-6cba75fac1d6.png)

And even I use the search function, there is still no any result
![Screenshot 2020-01-01 23-59-27](https://user-images.githubusercontent.com/58665916/71643299-e261f600-2cf2-11ea-8d5b-8340e7759cac.png)

I see the log here and found that the software keep saying that there is no cover image and image available in post
![Screenshot 2020-01-02 00-03-06](https://user-images.githubusercontent.com/58665916/71643328-5dc3a780-2cf3-11ea-8e52-f14e5270ecb2.png)

And here is the log file
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4014238/pixivutil.log)

Hope that you can help me and fix the problem please

**Comment by Nandaka** [comment]
do you have paid access to the Fanbox?

**Comment by MingLaw30** [comment]
> do you have paid access to the Fanbox?

Yes
I have already paid and subscribe for it
![Screenshot 2020-01-02 00-35-27](https://user-images.githubusercontent.com/58665916/71643740-0f64d780-2cf8-11ea-9e92-54eba106b3eb.png)
![Screenshot 2020-01-02 00-38-07](https://user-images.githubusercontent.com/58665916/71643747-33c0b400-2cf8-11ea-88c8-f0d27f17d65b.png)

And I can see the post in the browser too
![Screenshot 2020-01-02 00-36-52](https://user-images.githubusercontent.com/58665916/71643748-3de2b280-2cf8-11ea-9d34-288165b100f1.png)

It seems that the software can only download the posts cost $100 and can't download the posts cost $540 from 2017-09-29

**Comment by Nandaka** [comment]
Looks like the old posts are using non-standard way of showing the images (using custom html, instead of image list).

Can you replace the library.zip with this version: [library.zip](https://github.com/Nandaka/PixivUtil2/files/4014449/library.zip)

Also delete the old log file and reupload it here if there still issues.

**Comment by MingLaw30** [comment]
> Looks like the old posts are using non-standard way of showing the images (using custom html, instead of image list).
> 
> Can you replace the library.zip with this version: [library.zip](https://github.com/Nandaka/PixivUtil2/files/4014449/library.zip)
> 
> Also delete the old log file and reupload it here if there still issues.

Happen the error here
![Screenshot 2020-01-02 03-08-08](https://user-images.githubusercontent.com/58665916/71645055-1ea25000-2d0d-11ea-996a-7c461bfb5373.png)
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4014461/pixivutil.log)

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20200102-beta1

**Comment by MingLaw30** [comment]
> try https://github.com/Nandaka/PixivUtil2/releases/tag/v20200102-beta1

Still the error here
![Screenshot 2020-01-02 13-34-05](https://user-images.githubusercontent.com/58665916/71652948-a1a2c500-2d64-11ea-8954-7cc6fd03d3f2.png)

**Comment by Nandaka** [comment]
ok, can you upload the log file?

**Comment by MingLaw30** [comment]
> ok, can you upload the log file?

Sorry that
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4014996/pixivutil.log)

**Comment by Nandaka** [comment]
try [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015173/library.zip)

**Comment by MingLaw30** [comment]
> try [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015173/library.zip)

Get the error here
![Screenshot 2020-01-02 20-54-05](https://user-images.githubusercontent.com/58665916/71667963-252ed700-2da2-11ea-9f30-21b9e3a1ee15.png)

And it download the same thing like the above
![Screenshot 2020-01-02 20-55-23](https://user-images.githubusercontent.com/58665916/71667984-3546b680-2da2-11ea-918e-79ff48fe0e2c.png)

**Comment by Nandaka** [comment]
updated [library.zip](https://github.com/Nandaka/PixivUtil2/files/4016016/library.zip)

**Comment by MingLaw30** [comment]
It download the same thing and the software say that no cover image and no image available

![Screenshot 2020-01-02 22-23-07](https://user-images.githubusercontent.com/58665916/71671642-85c41100-2dae-11ea-8250-24dd48c42a3c.png)

![Screenshot 2020-01-02 22-23-49](https://user-images.githubusercontent.com/58665916/71671684-a1c7b280-2dae-11ea-9c44-da6231c7e9cc.png)

**Comment by MingLaw30** [comment]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4016138/pixivutil.log)

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20200103-beta2

also delete your old log file before running, so I can get clean log.

**Comment by MingLaw30** [comment]
It seems that it can get all the images at this time
![Screenshot 2020-01-03 02-36-07](https://user-images.githubusercontent.com/58665916/71684942-e6b11080-2dd1-11ea-8819-d4d2f108aa4b.png)

![Screenshot 2020-01-03 02-36-17](https://user-images.githubusercontent.com/58665916/71684949-eadd2e00-2dd1-11ea-8ac3-eb7045dd2226.png)

![Screenshot 2020-01-03 02-36-11](https://user-images.githubusercontent.com/58665916/71684955-ee70b500-2dd1-11ea-8567-5e044daf1c1e.png)

Here is the log if you need it
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4016944/pixivutil.log)

Also thank you for your patient and effort for solving the problem

**Comment by ee092884** [comment]
Attach "pixivutil.log" here
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4017116/pixivutil.log)

**Comment by bluerthanever** [comment]
Hey, Mr. Nandaka.
I found out that the alteration related to this issue caused FanboxPost.parsePost() method being called twice, once in 
https://github.com/Nandaka/PixivUtil2/blob/2f11c09405360158b8615a8ec1ad3ef3476e53a6/PixivModelFanbox.py#L118
another one in 
https://github.com/Nandaka/PixivUtil2/blob/2f11c09405360158b8615a8ec1ad3ef3476e53a6/PixivBrowserFactory.py#L760
and caused that there being one cover image duplicate in post.embeddedFiles.
Not a big deal, but I think you should know.

**Comment by Nandaka** [comment]
It purposefully calling the parsePost twice as the data source comes from different endpoints (https://www.pixiv.net/ajax/fanbox/creator?userId= and https://fanbox.pixiv.net/api/post.info?postId=), need to add check if the post already added or not.

**Comment by bluerthanever** [comment]
Urr. Sorry for assuming you are and calling you a Mister. You are one though, aren't you? If not I am soooo sorry, again.
I noticed that the difference in endpoints actually...
Maybe in parsePost, firstly we check whether the cover image, if it's none or doesn't match the new one, then overwrite and append to embed file list?

**Comment by bluerthanever** [comment]
Happy Lunar New Year!
Is Nandaka-san Chinese? Haha!
Thanks for the update, but I found out that the issue I mentioned kinda still exists. And I think you modified the codes in parseBody instead of parsePost.
For myself I just added:
`if self.coverImageUrl  is not None:`
in front of 
https://github.com/Nandaka/PixivUtil2/blob/f11e39edd3a933f024cc02d0668376f2f2c874b5/PixivModelFanbox.py#L138-L140

**Comment by Nandaka** [comment]
hmm, can you send a pull request? I'm not sure the changes 😛

**Comment by bluerthanever** [comment]
Ok. I'll get to it later.

**Comment by Nandaka** [comment]
merged #629 629
