### ISSUE TITLE
Question: Confusion about image download delay in 20200101

### ISSUE THREAD

**Issue by bnick23** [Nandaka/PixivUtil2#612]
- [x]  Did you read FAQ section?

* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

Hello! Was running the latest release when I noticed the downloaddelay (which is set to 10) was happening not just for new downloads like it used to, but when checking the already downloaded ones as well, adding a lot of extra time. Is this a new intended change? I apologize if its mentioned somewere and I missed it.

Old previous 20191221 version downloaddelay = 10 example:

![PixivDownloader20191221 old](https://user-images.githubusercontent.com/24767475/71644399-00fec780-2cc8-11ea-8645-de551b2fd6cc.jpg)

New 20200101 version downloaddelay = 10 example:

![PixivDownloader20200101 new](https://user-images.githubusercontent.com/24767475/71644409-2a1f5800-2cc8-11ea-9271-3a95ee699ae7.jpg)

**Comment by Nandaka** [comment]
most likely due to #609, might be duplicated with #613.
replace the library.zip from https://github.com/Nandaka/PixivUtil2/releases/tag/v20200102-beta1

**Comment by rogerlhc** [comment]
Tested with v20200102-beta1, issue still exists with https://github.com/Nandaka/PixivUtil2/issues/613#issuecomment-570106587

**Comment by rogerlhc** [comment]
> most likely due to #609, might be duplicated with #613.
> replace the library.zip from https://github.com/Nandaka/PixivUtil2/releases/tag/v20200102-beta1

Tested with v20200102-beta1, issue still exists with https://github.com/Nandaka/PixivUtil2/issues/613#issuecomment-570106587

**Comment by Nandaka** [comment]
try [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015191/library.zip)

**Comment by rogerlhc** [comment]
> try [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015191/library.zip)

Tried. Issue **still exists**.

**Comment by Nandaka** [comment]
updated [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015246/library.zip)

**Comment by rogerlhc** [comment]
> updated [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015246/library.zip)

Tested again, issue **still exists**.

I use v20191221, not have this issue.

**Comment by Nandaka** [comment]
updated again [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015385/library.zip)

**Comment by rogerlhc** [comment]
> updated again [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015385/library.zip)

Tested again again with library.zip (SHA1: 5DDEE56DBEBCAED0406C24415DF12FB94F0436E8), issue **still exists** using "8. Download new illust from bookmarked members (/bookmark_new_illust.php)".

Oh no...

**Comment by Nandaka** [comment]
do you enable `alwaysCheckFileSize` or `overwrite`?

**Comment by s-l-s-l** [comment]
> do you enable `alwaysCheckFileSize` or `overwrite`?

Both of them are set to False.

I'll move my downloaded files to another folder after several day they downloaded.
v20200101 with patch will only check files in the download folder,  if file already downloaded but not in the folder, even if the history exists in DB file, it will still do the downloading.
v20191221 will check download history in DB first, if it is in DB history, it will skip the file, even the file is not exists.
I think that's why cause this issue.

**Comment by Nandaka** [comment]
updated [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015885/library.zip)

**Comment by ee092884** [comment]
Will this string "D: \\ D \\ Desktop \\ Program \\ PixivUtil2 \\\ xe3 \ x83 \ xaa \ xe3 \ x82 \ xb6 \ xe3 \ x83 \ xbc \ xe3 \ x83 \ x89 \ xe3 \ x83 \ x9e \ xe3 \ x83 \ xb3 (804018) \\ 15108387_p0-\ xe3 \ x80 \ x90 \ xe3 \ x83 \ xaa \ xe3 \ x82 \ xaf \ xe3 \ x80 \ x91 \ xe3 \ x83 \ xa9 \ xe3 \ x82 \ xb0 \ xe3 \ x83 \ xa9 \ xe3 \ x83 \ xbc \ xe3 \ x82 \ xb8 \ xe3 \ x82 \ xb9 \ xe3 \ x82 \ xa6 \ xe3 \ x83 \ x84 "Is it normal?

I know this is the path link
But there are \\
Should have been
"Processing Image Id: 73809942
Already downloaded: 73809942
Wait for 0.75s
#1"
It's over

The pictures that run afterwards are all old pictures that have been downloaded
Already using the latest version v20200103-beta2
"db.sqlite" has not been deleted

![image](https://user-images.githubusercontent.com/39590282/71687361-a43f0200-2dd8-11ea-98b9-7b6ab2895418.png)
![image](https://user-images.githubusercontent.com/39590282/71687557-1ca5c300-2dd9-11ea-8363-177e9812e4fe.png)

**Comment by ee092884** [comment]
Attach "pixivutil.log" here
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4017118/pixivutil.log)

**Comment by s-l-s-l** [comment]
> updated [library.zip](https://github.com/Nandaka/PixivUtil2/files/4015885/library.zip)

Tested again again again with library.zip(SHA1: 0DF37F02BCB609E73D45DC2F7381F9DB10295E03) and v20200103-beta2, issue **still exists**.

After v20200101, it seems not check DB history first. I'll roll back to v20191221 without this issue.

**Comment by Nandaka** [comment]
https://github.com/Nandaka/PixivUtil2/issues/613#issuecomment-570280699

Ensure alwayscheckfilesize and overwrite is set to False in config.ini, else it will have some delay enabled as it actually retrieve the image information from pixiv server.

**Comment by s-l-s-l** [comment]
> [#613 (comment)](https://github.com/Nandaka/PixivUtil2/issues/613#issuecomment-570280699)
> 
> Ensure alwayscheckfilesize and overwrite is set to False in config.ini, else it will have some delay enabled as it actually retrieve the image information from pixiv server.

Alwayscheckfilesize and overwrite is set to **False** in config.ini, **issued still exists**.

**Comment by Nandaka** [comment]
Weird, I'm running from the source and it is working as intended..

Try the full release here? https://github.com/Nandaka/PixivUtil2/releases/tag/v20200103-beta2

**Comment by s-l-s-l** [comment]
> Weird, I'm running from the source and it is working as intended..
> 
> Try the full release here? https://github.com/Nandaka/PixivUtil2/releases/tag/v20200103-beta2

Hummmm... Full release **works** for me. Thank you so much.

**Comment by Nandaka** [comment]
got it, look like I cannot release just the library.zip anymore...

**Comment by s-l-s-l** [comment]
> got it, look like I cannot release just the library.zip anymore...

Replaced library.zip step by step, so what went wrong... Orz

**Comment by bnick23** [comment]
Been running the latest release for a bit, and it seems to be working again. Thank you for your hard work!
