### ISSUE TITLE
Unable to use custom list directory

### ISSUE THREAD

**Issue by panhartstuff** [Nandaka/PixivUtil2#614]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
`PixivUtil2.exe -s 4 D:\pixiv-list.txt`
I'm unable to set a custom list txt file using this command. It keeps looking for list.txt in the default directory.
### Versions
PixivDownloader2 version 20200101

**Comment by panhartstuff** [comment]
Never mind, it seems that it only takes the list filename as an argument and list directory must be specified in the config file

**Comment by panhartstuff** [comment]
Never mind again, it still refuses to take custom filenames as argument

**Comment by Nandaka** [comment]
check your config file and the command? 
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1676

**Comment by panhartstuff** [comment]
I'm genuinely preplexed, the exact same command produces inconsistent result controlled by factors I cannot pin down. Sometimes it can find pixiv-list.txt, but in other times it defaults to ./list.txt despite using the same arguments
I cannot find the pattern of why this happens.

**Comment by Nandaka** [comment]
are you running from cmd/ps/vs-code terminal in windows?
I can only think that it fail the os.path.exists() test and it might due to path separator.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1680

**Comment by panhartstuff** [comment]
Yes, I'm running from cmd. My path contains a space, if that matters. It's still bouncing from sometimes working and sometimes not working

**Comment by panhartstuff** [comment]
Alright it works now, I think I idiotically mistyped something somewhere but I don't even know what anymore...
Sorry for the bother
