### ISSUE TITLE
Page index for non-manga files

### ISSUE THREAD

**Issue by panhartstuff** [Nandaka/PixivUtil2#616]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
%page_index% and %page_number% currently only works for manga pages and not single illustrations. In the original filenames you'd still see '_p0' even for single illustrations and I want to mimic that behavior in order to use it build up my own custom filenames.

### Versions

PixivDownloader2 version 20200101

**Comment by Nandaka** [comment]
use `%urlFilename%` or you can just append `_p0` on the filename format?

**Comment by panhartstuff** [comment]
Well I suppose I can live with that, but the format I wanted to do is something like this:
`%member_id%-%image_id%-%works_date_fmt{%Y%m%d_%H%M%S}%-p%page_index%`
where the page number is split off.
Manually adding p0 won't work consistently if a user has both single illustrations and manga works in their profile.

**Comment by panhartstuff** [comment]
I forgot that PixivUtil2 has different filename settings for manga and illustrations...sorry.
Btw, what is "filenameinfoformat" exactly for?

**Comment by Nandaka** [comment]
`filenameinfoformat  ==> Similar like filename format, but for info dumps.`
only if `writeimageinfo  = True`
`writeimageinfo  ==> set to 'True' to export the image information to text file.
                    The filename is following the image filename + .txt.`

**Comment by panhartstuff** [comment]
I see, thanks.
