### ISSUE TITLE
Allow automatic login using cookie only without passing username and password interactively

### ISSUE THREAD

**Issue by Missingmew** [Nandaka/PixivUtil2#619]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I am trying to run PixivUtil unattended using ``python3 PixivUtil2.py -s 5`` with only a cookie stored in ``config.ini``. Doing so requires user input though (pressing enter twice to get past username and password prompt) before the action starts.
I had a quick look at the code and it appears that support for unattended running is there, but only if there is a stored username and password in ``config.ini``. Would it be possible to add support for doing this by cookie only?

### Steps to Reproduce

1. Store cookie in ``config.ini``, ensure no username or password are there
2. Run PixivUtil2.py with ``-s`` option

**Expected behavior:** PixivUtil runs using the cookie without requiring user input

**Actual behavior:** PixivUtil requires user input (press enter twice to pass empty username and password) before running

### Versions
As reported by `PixivUtil2.py --help`: ``PixivDownloader2 version 20200103-beta2``

**Comment by bluerthanever** [comment]
Not sure why you would wanna do that though, my opinion, for current situation:
If you just want to use cookie only to login, you can put some random username/password combination in the config I guess?

**Comment by Nandaka** [comment]
@Missingmew assuming you only want to login using cookie, then you can supply dummy username/password in the config.ini to avoid pressing enter twice.

**Comment by Missingmew** [comment]
Okay, using a dummy user and pass works. You might want to make a note of this somewhere for people using cookies/sessions as primary login method.

**Comment by Nandaka** [comment]
Please note that OAuth still require you to put the actual username/password unless you can supply the refresh token somehow.
