### ISSUE TITLE
Option 5 doesn't work

### ISSUE THREAD

**Issue by whinette** [Nandaka/PixivUtil2#622]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [*] updated requirements from latest requirements.txt

### Description

Downloading from option 5 doesn't work anymore: the app doesn't find any bookmarked user.
Tried with only private / no private / any.

Going on https://www.pixiv.net/bookmark.php?type=user&p=1 url shows that I have bookmarked users.

```
Input: 5
Include Private bookmarks [y/n/o]:
Start Page (default=1):
End Page (default=0, 0 for no limit):
Importing Bookmarks...
Exporting page 1
Source URL: https://www.pixiv.net/bookmark.php?type=user&p=1
Using default DB Path: /mnt/c/PixivUtil2/db.sqlite
No more data
Result:  0 items.
Error at process_bookmark(): (<class 'ZeroDivisionError'>, ZeroDivisionError('float division by zero'), <traceback object at 0x7fa7885a55a0>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 2407, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 2127, in main_loop
    menu_download_from_online_user_bookmark(op_is_valid, args)
  File "PixivUtil2.py", line 1722, in menu_download_from_online_user_bookmark
    process_bookmark(hide, start_page, end_page)
  File "PixivUtil2.py", line 1235, in process_bookmark
    print("%d/%d\t%f %%" % (i, len(total_list), 100.0 * i / float(len(total_list))))
ZeroDivisionError: float division by zero
press enter to exit.
```

**Comment by br5471** [comment]
I am having the same error, so it's not just you. Option 6 doesn't work either.

**Comment by Nandaka** [comment]
might be related to #623

**Comment by Nandaka** [comment]
updated in https://github.com/Nandaka/PixivUtil2/releases/tag/v20200112

**Comment by br5471** [comment]
Option 6 still doesn't seem to work, but 5 is working now.

**Comment by Nandaka** [comment]
what is the error? looks ok in my side.
![image](https://user-images.githubusercontent.com/836867/72250973-d30a7300-3637-11ea-9231-60a5f7a1bb65.png)

**Comment by da3dsoul** [comment]
I can create my own issue if necessary, but it seemed relevant. I run with `-s 6 y 0 9 -x`
and it gives:
```
]2;PixivDownloader 20200112 PixivDownloader2 version 20200112
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading /home/da3dsoul/PixivRipper/PixivUtil2/config.ini ...
Error at loadConfig(): (<class 'configparser.NoSectionError'>, No section: 'DownloadControl', <traceback object at 0x7f24b1c24140>)
Some configuration have invalid value, replacing with the default value.
Writing config file... Backing up old config (error exist!) to config.ini.error-1579041309
done.
done.
Using default DB Path: /home/da3dsoul/PixivRipper/PixivUtil2/db.sqlite 
Creating database... done.
Only process members where the last update is >= 7 days ago 
Using Username: da3dsoul
Trying to log in with saved cookie 
Login successful. 
My User Id: 14369496. 
Premium User: False. 
Start Page = 0
End Page = 8
Importing image bookmarks...
Importing user's bookmarked image from page 0 
Source URL: https://www.pixiv.net/ajax/user/14369496/illusts/bookmarks?tag=&offset=-48&limit=48&rest=show 
Error at process_image_bookmark(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x7f24b17ceb00 whose wrapped object = <HTTPError 500: 'Internal Server Error'>>, <traceback object at 0x7f24b17874b0>) 
Starting Copy 
Traceback (most recent call last):
  File "/home/da3dsoul/PixivRipper/PixivUtil2/PixivUtil2.py", line 2434, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "/home/da3dsoul/PixivRipper/PixivUtil2/PixivUtil2.py", line 2152, in main_loop
    menu_download_from_online_image_bookmark(op_is_valid, args)
  File "/home/da3dsoul/PixivRipper/PixivUtil2/PixivUtil2.py", line 1783, in menu_download_from_online_image_bookmark
    process_image_bookmark(hide, start_page, end_page, tag, sorting)
  File "/home/da3dsoul/PixivRipper/PixivUtil2/PixivUtil2.py", line 1123, in process_image_bookmark
    totalList.extend(get_image_bookmark(False, start_page, end_page, tag, sorting))
  File "/home/da3dsoul/PixivRipper/PixivUtil2/PixivUtil2.py", line 1174, in get_image_bookmark
    page = __br__.open(url)
  File "/usr/local/lib/python3.7/dist-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 500: Internal Server Error
```

**Comment by Nandaka** [comment]
@da3dsoul use starting page = 1

**Comment by br5471** [comment]
I could be doing it wrong but here's what I inputted and the result it gives me:
"Input: 6
Include Private bookmarks [y/n/o]: y
Tag (default=All Images): default
Start Page (default=1): 1
End Page (default=0, 0 for no limit): 0
Importing image bookmarks...
Importing user's bookmarked image from page 1
Source URL: https://www.pixiv.net/ajax/user/12454151/illusts/bookmarks?tag=default&offset=0&limit=48&rest=show
No more images.
Importing user's bookmarked image from page 1
Source URL: https://www.pixiv.net/ajax/user/12454151/illusts/bookmarks?tag=default&offset=0&limit=48&rest=hide
No more images.
Found 0 image(s).
Done."

**Comment by br5471** [comment]
I just finished using Option 5 so idk why Option 6 can't seem to connect to my pixiv profile.

**Comment by Nandaka** [comment]
what is the returned data from https://www.pixiv.net/ajax/user/12454151/illusts/bookmarks?tag=default&offset=0&limit=48&rest=show and https://www.pixiv.net/ajax/user/12454151/illusts/bookmarks?tag=default&offset=0&limit=48&rest=hide

**Comment by da3dsoul** [comment]
0 used to work, but will try it

**Comment by br5471** [comment]
I have no idea what those links mean

**Comment by Nandaka** [comment]
@br5471 those are the API call for your bookmarks data from the logging

**Comment by il1707** [comment]
i need some help.
i am using the latest version(20200112)
i have a similar problem.
when using opition 5.
got the error.
Error at process_bookmark(): (<type 'exceptions.ZeroDivisionError'>, ZeroDivisionError('float division by zero',), <traceback object at 0x04056530>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 2302, in main
  File "PixivUtil2.py", line 2032, in main_loop
  File "PixivUtil2.py", line 1638, in menu_download_from_online_user_bookmark
  File "PixivUtil2.py", line 1167, in process_bookmark
ZeroDivisionError: float division by zero

**Comment by Nandaka** [comment]
@il1707 are you sure you are using the latest version? from the logging, it looks like the old one. 
Can you upload the log file?

**Comment by il1707** [comment]
@Nandaka of course.here are the part of log file.
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4082315/pixivutil.log)

**Comment by Nandaka** [comment]
can you open this page: https://www.pixiv.net/bookmark.php?type=user&p=1&rest=show in browser and check if the page has member ids or is redirected?

**Comment by il1707** [comment]
@Nandaka yes.i can open it. all look like normally.
![Screenshot_2020-01-19_18-31-31](https://user-images.githubusercontent.com/21167956/72679442-0e022000-3aea-11ea-8223-428d577c166a.jpg)

**Comment by Nandaka** [comment]
can you try https://github.com/Nandaka/PixivUtil2/releases/tag/v20200120-beta1

**Comment by aksskl** [comment]
Option 5 is working for me using v20200120-beta1

However, now option 6 is missing the ordering(desc/asc/...). Option 6 is working, I just can't choose the download order anymore.

**Comment by Nandaka** [comment]
> option 6 is missing the ordering(desc/asc/...). Option 6 is working, I just can't choose the download order anymore.

Pixiv removed the ability to sort from the API call.

**Comment by il1707** [comment]
@Nandaka sorry for reply so late.proxy works well with this version,but still got an error when using option 5.
2020-01-25 19:17:51,929 - PixivUtil20200120-beta1 - ERROR - Error at process_bookmark(): (<class 'ZeroDivisionError'>, ZeroDivisionError('float division by zero'), <traceback object at 0x1082CD48>)
2020-01-25 19:17:51,930 - PixivUtil20200120-beta1 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 1258, in process_bookmark
ZeroDivisionError: float division by zero

2020-01-25 19:17:51,933 - PixivUtil20200120-beta1 - ERROR - Unknown Error: float division by zero
Traceback (most recent call last):
  File "PixivUtil2.py", line 2430, in main
  File "PixivUtil2.py", line 2150, in main_loop
  File "PixivUtil2.py", line 1745, in menu_download_from_online_user_bookmark
  File "PixivUtil2.py", line 1258, in process_bookmark
ZeroDivisionError: float division by zero.
here are the full log,only copy config.ini&db.sqlite to the newfloder.
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4111971/pixivutil.log)
