### ISSUE TITLE
"Download from list" not working correctly

### ISSUE THREAD

**Issue by HydroHydro** [Nandaka/PixivUtil2#633]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

I have a list.txt file with 86 member IDs. When I choose option 4 (Download from list), it works correctly for a few members, but then stops and goes back to the menu.

Maybe long lists are an issue?

Could be related to the 7 days thing?

Edit: I changed daylastupdated to 0 and the list was processed again, but still stopped after only a few member IDs...

### Versions
v20200125

**Comment by OniiGokko** [comment]
1.hmm.. have you opened the log to check for any errors? 
2. Open list.txt and check if you have the old or the new format, I know from own experiece that the new format of https://www.pixiv.net/en/users/"usernumber"  <- gives an error when runnig option 4. 
// 3:) Oni

**Comment by HydroHydro** [comment]
I literally have the member ID then press enter.

Example:
12345
67890
54321

**Comment by Nandaka** [comment]
What is the output from the program?

**Comment by HydroHydro** [comment]
Output? Normal... It goes through the images one by one just like using "Download by member_id." But after going through a few member IDs, it just goes back to the menu as if there weren't more IDs in the list... :\

Trying "processfromDb = False" right now. Will report back when (or if) it finishes all 86 IDs.

Also, what *is* processfromDb? The readme file doesn't really make it clear what True/False does exactly...

**Comment by Nandaka** [comment]
`processfromDb` basically tell the script to use the member table in the DB as the source list, rather than the actual list. Originally it was used to keep track all the followed member id and use the list.txt as a kind of temporary list which going to be imported at the runtime.
