### ISSUE TITLE
(Suggestion) Adding GPU  run thread for faster downloading!

### ISSUE THREAD

**Issue by itsmenmd** [Nandaka/PixivUtil2#637]
Hi!, Can u adding GPU thread for faster downloading, hope fully uc an do it so soon <3

**Comment by Hamuko** [comment]
This suggestion doesn't make sense for a myriad of reasons, starting off with the fact that PixivUtil2 is designed to slow down downloads so that Pixiv doesn't IP ban you.

**Comment by Nandaka** [comment]
GPU has nothing to do with download...
