### ISSUE TITLE
Current Version crashes when opens on windows 10 

### ISSUE THREAD

**Issue by IPods-and-spree-candy** [Nandaka/PixivUtil2#638]
### Prerequisites

* [Yes ] Did you read FAQ section?
* [Yes ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

Description

Been having the problem of getting an error on login first saying that the cookie was expired and then an inability to login, Updated to current version when run it crashed the windows closes before I can read any of the error messages, I did copy files to update the version like I ussually do in that I copied db SQLITE file, config configuration setting file, config.ini BAK File and the sqlite3.dll application extension file over to the new version is there a better way to move to new versions. Tried it with a clean unzip and it works fine so it would have to be some thing about coping over the files from the last version that causes this 

### Steps to Reproduce

Open the program on a windows 10 computer 
Copy files from above over to new version 

Program should work 

Program crashes seconds after opening after some text is shown in the window 

Current and unsure been awhile since I updated

**Comment by Nandaka** [comment]
run it from the console/cmd so it wont auto close, also check the log file.

If you running from very old version, maybe you need to update the config.ini manually after 1st run (don't copy the old one).

**Comment by bluerthanever** [comment]
Maybe it's the same issue with this one?
[https://github.com/Nandaka/PixivUtil2/issues/618](url)

**Comment by IPods-and-spree-candy** [comment]
Ok so i did a little more testing I was able to login with a clean unzip of the program I had to get the login cookie to do so since it asked for a captcha but it worked also ran it in cmd and got the following took a snip of it attached
![cmd capture](https://user-images.githubusercontent.com/49982530/75349538-9488ea80-586a-11ea-8768-d9917153f00f.PNG)

**Comment by Nandaka** [comment]
> ran it in cmd and got the following took a snip of it attached

this from not from the clean unzip, right?

**Comment by IPods-and-spree-candy** [comment]
Right it is from the one with the files copied over

**Comment by IPods-and-spree-candy** [comment]
Any luck?

**Comment by Nandaka** [comment]
nothing to check from my side if running clean zip file is working.
