### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by ScottQB4** [Nandaka/PixivUtil2#643]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

(https://user-images.githubusercontent.com/15930271/75496481-43bee200-598f-11ea-961e-8eab8e58fe3d.png)

### Steps to Reproduce

1. Open Program
2. Type F1 and press enter
3. Press enter again

**Expected behavior:** Download from supported FANBOXes

**Actual behavior:** The above

### Versions

You can get this information from executing `PixivUtil2.py --help`.

**Comment by Nandaka** [comment]
see #641 641
