### ISSUE TITLE
Download quality not matching hi-res preview

### ISSUE THREAD

**Issue by molassesdeathbed** [Nandaka/PixivUtil2#644]
### Prerequisites

* [ ] Did you read FAQ section? Yes
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? Yes

### Description

Not sure what to do exactly, because this issue is present in both manual and script-assisted downloads. Basically, the downloaded image does not match the clarity of the hi-res preview (when you click on the image to maximize on pixiv.net itself). https://www.pixiv.net/en/artworks/72829758 <-- this is a good example. When you maximize the image, it shows a very crisp quality, but when you actually download the image it's quite pixelated. 

### Steps to Reproduce

1. First, view preview quality by maximizing image on pixiv's website. 
2. Next, download image either manually or with PixivUtil2.
3. Compare the two (the preview is much nicer). 

**Expected behavior:** Downloaded image would match the preview quality

**Actual behavior:**  Download quality was noticeably worse

### Versions

20200125

**Comment by Nandaka** [comment]
get the latest version, also compare the file size and urls is the same.

![image](https://user-images.githubusercontent.com/836867/75523865-d0c57200-5a47-11ea-9243-bcbd02dfe367.png)

![image](https://user-images.githubusercontent.com/836867/75523781-a2e02d80-5a47-11ea-95ec-43cd327c992b.png)

![image](https://user-images.githubusercontent.com/836867/75523803-af648600-5a47-11ea-8021-98c53a4373f9.png)

![image](https://user-images.githubusercontent.com/836867/75523823-b9868480-5a47-11ea-84e6-3775e2147fe8.png)

**Comment by Gavanr** [comment]
download not match with image on pixiv look here
https://imgur.com/a/mEHPsft

**Comment by molassesdeathbed** [comment]
Perhaps this is a better indicator of what I mean: 

Look at the quality of this screenshot. The lines are crisp and clear, well-defined, etc. This is with the pixiv image expanded and zoomed in on (for some reason the enhanced quality only shows up then). 
![image](https://user-images.githubusercontent.com/60958394/76491269-b1452680-6403-11ea-890c-95c68c6c3815.png)

Now, look at the file that actually gets downloaded. It's easy to see the discrepancy. 
![72829758_p0](https://user-images.githubusercontent.com/60958394/76491411-fa957600-6403-11ea-8795-67afdfb54343.jpg)

**Comment by Nandaka** [comment]
can you tell the image url then? because it doesn't do any conversion or modification.
do you set `downloadResized = True` in the config.ini?

**Comment by Cyberbeing** [comment]
>Look at the quality of this screenshot. The lines are crisp and clear, well-defined, etc. This is with the pixiv image expanded and zoomed in on (for some reason the enhanced quality only shows up then).

By default, Chrome applies color management based on your system ICC profile, which could cause a difference in appearance. If you don't have a standard gamut monitor calibrated to sRGB, something like that could happen.
</br>

>Now, look at the file that actually gets downloaded.

There is no problem with this image, it matches the file size & file hash of the original image. If you view it color managed in the same way, it should look identical.

**Comment by molassesdeathbed** [comment]
Ah, thank you, that makes sense Cyberbeing. I didn't know that was a thing.
