### ISSUE TITLE
Relative path erroneously sanitized

### ISSUE THREAD

**Issue by Butterfly-Dragon** [Nandaka/PixivUtil2#646]
### Prerequisites

* [☑] Did you read FAQ section?
* [☑] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

with the latest version, inserting in `config.ini` a line like this for the naming conventions:
```
filenameformat = ..\files\%artist% (%member_id%) - %urlFilename% - %title%
```
creates a directory called "`_`" then under that it creates a directory called "`files`" and then continues working normally

### Steps to Reproduce

1. open `config.ini`
2. change the filename format on the option intended for testing as described above
3. run pixivutils selecting the option intended for testing which had been changed as described above

**Expected behavior:** [What you expected to happen]

relative path should be followed
`.` = same dir;
`..` = directory above;
`...` = *this* should be sanitized as it expands to current directory and subdirectories at the same time and it can mess up a file system if written to, so consider it as just three dots in a row. Also... it should only be applied to directories that start and end with that name, not other instances.

Therefore i expected that by writing a relative path like this:
```
..\files\%artist% (%member_id%) - %urlFilename% - %title%
```
i would have had PixivUtil2 write a directory called "Files" to the directory above. where it is being hosted.

**Actual behavior:** [What actually happened]

PixivUtil2 sanitizes the directory name and creates a directory called "`_`" where it continues writing the rest of the directory tree.

### Versions

`PixivDownloader2 version 20200228`

**Comment by Nandaka** [comment]
use `rootdirectory` option in config.ini if you want to set relative path.

**Comment by Butterfly-Dragon** [comment]
rootdirectory ?

I have a different version of python installed in my system, it conflicts with PixivUtils2 if i change the root directory is it going to create a problem?

i thought that would move "everything" instead of just where it writes the files... if that is the case... it could create problems.

**Comment by Nandaka** [comment]
I mean there is an option in `config.ini` called `rootdirectory` in the `[Settings]` section, not the actual application/script path.

```
[Settings]
rootdirectory ==> Your root directory for saving the images.
```

**Comment by Butterfly-Dragon** [comment]
i'm an idiot. Thanks.

**Comment by Butterfly-Dragon** [comment]
i swear i thought that option was to tell the program where to find its own files, instead of using the standard python build of the user. 😅
