### ISSUE TITLE
Can't download Ugoiras when "downloadresized" is active

### ISSUE THREAD

**Issue by jonatanm27** [Nandaka/PixivUtil2#648]
### Prerequisites

* [*] Did you read FAQ section?
* [*] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

The option of allowing to download the "master" version of the images works perfectly in normal cases, but when it tries to download an Ugoira while this option is set to True, it can't download it and skip to the next image; provably because the Ugoira don't have "master" versions (I guess). And yes, this don't happen if I desactive the "downloadresized" option.

### Steps to Reproduce

Trying to download an Ugoira while the "downloadresized" option is still active (or True), either individually (by image_id) or by downloading an entire gallery (by member_id), or any other option.

**Expected behavior:** Download the pack of images and then create the Ugoira

**Actual behavior:** The program can't find the URL of the Ugoira, and then fail to download it:
Image URL : https://tc-pximg01.techorus-cdn.com/img-zip-ugoira/img/2020/03/04/02/40/34/79880686_ugoira1920x1080.zip_ugoira600x600.zip
Filename  : C:\Users\Jonatan\Downloads\Programs\pixivutil20200228\ばっさ (3320140)\79880686_ugoira1920x1080 - 歌う栞桜さん.zip_ugoira600x600
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/artworks/79880686
        No file size information!
Remote filesize = -1 B (-1 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/artworks/79880686
[download_image()] HTTP Error: HTTP Error 404: Not Found at https://tc-pximg01.techorus-cdn.com/img-zip-ugoira/img/2020/03/04/02/40/34/79880686_ugoira1920x1080.zip_ugoira600x600.zip
Image url not found/failed to download: 79880686

### Versions

This happen obviously in the latest version (20200228) because this one added the "downloadresized" option

**Comment by Nandaka** [comment]
try the latest releases: https://github.com/Nandaka/PixivUtil2/releases

**Comment by jonatanm27** [comment]
Thank you for fixing it that fast!
Works perfect now
