### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by Pgj1997** [Nandaka/PixivUtil2#650]
The program can already detect if a new build is available.
The next step would be to have the program update automatically.
The best way to go about this is, if the program detects a new build, it will automatically download and replace the necessary files, and ask the user to restart the program afterwards if needed.

Users can toggle this feature in `config.ini`. It would look like this:
```
[Network]
automaticupdate = True
```
Of course `checknewversion` would also need to be set to "True" as well.

**Comment by Nandaka** [comment]
well, I think I can set to automatically load the release page, but I cannot make it auto extract without including additional files for the extractor, which might require different license.

**Comment by Nandaka** [comment]
check latest releases https://github.com/Nandaka/PixivUtil2/releases
