### ISSUE TITLE
Failed to login using OAuth

### ISSUE THREAD

**Issue by Ksdpm** [Nandaka/PixivUtil2#651]
### Prerequisites

* [Yes] Did you read FAQ section?
* [Yes] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

After inputting f1 or f2 and then the subsequent info, the programme was unable to start any download. The error displayed was 'Failed to login using OAuth' which, I have noticed, has been put forward 2 times already. Therefore, I have tried the proposed solution which seems to have worked on the previous questioner, but failed on me. I will quote the exact error message below.

### Steps to Reproduce

1. login as usual i.e. filling in usernames, password and cookies
2. select either f1 or f2 and fill in the subsequent required info as usual - max page (and artist ID if f2 is slected)
3. wait

**Expected behavior:** 
Images are found and download should start shortly which I have already done it on my bookmarked images

**Actual behavior:**
'Using OAuth to retrieve member info for: "artist ID"
103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。'

was displayed before the error message comes up

'1508 Failed to login using OAuth, hasDumpPage=N, pageData=None'

### Versions

v20200307

#####
I have also tried to resolve the issue by downloading version v20190917 where this particular problem was identified and solved. However, this still does not work in my case.

Thank you in advance for any help you can give

**Comment by Nandaka** [comment]
you tried this one: https://github.com/Nandaka/PixivUtil2/issues/631#issuecomment-590486664

**Comment by Ksdpm** [comment]
Hi Nandaka,

Yes, I have tried it. In fact, I have been using my email to sign in since the very start and tried to use different cookies, just like in the thread you mentioned. However, my 'refresh_token' wasn't automatically set after restarting the programme.

**Comment by Ksdpm** [comment]
Hi Nandaka,

It somehow magically works now after several tries and restarting my laptop.

Thanks for the help
