### ISSUE TITLE
Enable filter by bookmark count for Pixiv Premium

### ISSUE THREAD

**Issue by onexoff** [Nandaka/PixivUtil2#652]

**Comment by Nandaka** [comment]
what pro version? for your information, this application cannot bypass the validation from the server side. You still need to pay for Pixiv Premium or Fanbox content.

**Comment by onexoff** [comment]
yes I've the pro version of Pixiv 

I mean how I can filter the search with bookmarks so I don't need to wait more time 
to get image has like 5000 bookmarks

I think the script doesn't support that because when I enter 5000 into bookmarks
the script scrape are checking all the bookmarks image  example  in page 1
so if the image contains 5000 bookmarks that are downloaded if not passed ...

we need to do something like 
something like: https://www.pixiv.net/en/tags/original/illustrations?scd=2019-01-01&ecd=2019-12-31&blt=5000&s_mode=s_tag&type=illust

also how I can turn on the manga image in search I need just illustrations

thank you

**Comment by onexoff** [comment]
is possible ?

**Comment by Nandaka** [comment]
well, I don't have pixiv premium, so I cannot test it. From the url, looks like `&blt=5000` is the bookmark count? 

For the type shouls be ok
- &type=illust_and_ugoira = illust only
- &type=manga = manga only

**Comment by onexoff** [comment]
yes &blt=5000 is for bookmark count pixiv will show you automatically just the images has +5000 bookmark

can you contact me at uchihaclan34x@gmail.com
I will send you my account and you can test that

**Comment by onexoff** [comment]
can you provide me  your email please for can send you the login of my account

**Comment by onexoff** [comment]
I've solved that using Powerful Pixiv Downloader it's a chrome addons

 to scrape the id of images than using PixivUtil2
to download them

**Comment by Nandaka** [comment]
can you upload the result from https://www.pixiv.net/ajax/search/artworks/vocaloid?word=vocaloid&order=date_d&mode=all&p=1&s_mode=s_tag&type=all&blt=1000 here?

**Comment by Nandaka** [comment]
added some logic to add the blt and type parameter. Please note blt only applicable for premium user.
I will upload beta version later.
