### ISSUE TITLE
I cannot run this project on linux

### ISSUE THREAD

**Issue by railannad** [Nandaka/PixivUtil2#653]
I downloaded the [Source code (tar.gz)] and I donnot know if I was right.
All the library listed in requirements.txt are installed already and their version is OK.
My VPS is Ubuntu 18.04 and the commad  is [python3.8 Pixiv]
Here are outputs:
python3.8 PixivUtil2.py

Traceback (most recent call last):
  File "PixivUtil2.py", line 19, in <module>
    import mechanize
ModuleNotFoundError: No module named 'mechanize'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "PixivUtil2.py", line 19, in <module>
    import mechanize
ModuleNotFoundError: No module named 'mechanize'

**Comment by Nandaka** [comment]
see https://github.com/Nandaka/PixivUtil2/issues/176

**Comment by railannad** [comment]
> see #176

From #176 I ran  `pip install -r requirements.txt`. Then I run `python PixivUtil2.py` and output is `  File "PixivUtil2.py", line 56
    print("\b \b", end="")
                      ^
SyntaxError: invalid syntax`
The fileformat is unix.

**Comment by NHOrus** [comment]
Install using pip3 and run using python3

**Comment by railannad** [comment]
> Install using pip3 and run using python3

pip3 install -r requirements.txt:
`Requirement already satisfied: beautifulsoup4>=4.8.1 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line ### 1))
Requirement already satisfied: certifi>=2019.9.11 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: demjson>=2.2.4 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: imageio>=2.5.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: mechanize>=0.4.4 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: numpy>=1.17.2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: Pillow>=6.1.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: PySocks>=1.7.1 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: win_unicode_console>=0.5 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: apng>=0.3.3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python3.6/dist-packages (from beautifulsoup4>=4.8.1->-r requirements.txt (line 1))
Requirement already satisfied: html5lib>=0.999999999 in /usr/local/lib/python3.6/dist-packages (from mechanize>=0.4.4->-r requirements.txt (line 5))
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r requirements.txt (line 10))
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r requirements.txt (line 10))
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r requirements.txt (line 10))
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/dist-packages (from html5lib>=0.999999999->mechanize>=0.4.4->-r requirements.txt (line 5))
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from html5lib>=0.999999999->mechanize>=0.4.4->-r requirements.txt (line 5))`

It said I was already installed all the library.

python3 PixivUtil2.py:

`Require Python 3.7++`

python3.8 PixivUtil2.py:
`Traceback (most recent call last):
  File "PixivUtil2.py", line 19, in <module>
    import mechanize
ModuleNotFoundError: No module named 'mechanize'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "PixivUtil2.py", line 19, in <module>
    import mechanize
ModuleNotFoundError: No module named 'mechanize'
`

**Comment by NHOrus** [comment]
`pip3.8 install -r requirements.txt --user --update` then?

**Comment by railannad** [comment]
I don not know how to get pip3.8

apt-get install python3.8-pip:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3.8-pip
E: Couldn't find any package by glob 'python3.8-pip'
E: Couldn't find any package by regex 'python3.8-pip'
`

System is Ubuntu18.04

**Comment by bluerthanever** [comment]
Do you have both python2 and 3 on your computer?
If so, try explicitly installing requirements on python3 environment and run in python3?

**Comment by RoestVrijStaal** [comment]
You're better off to _not_ use the python version from the official repositories of your distro. That version is often ancient with a few bugfix patches, unless you run Arch, Manjaro, Gentoo or the like.

You want to install and use the latest stable version of python in your own environment. Preferably you do that with a version manager, like [adsf](https://github.com/asdf-vm/asdf) and [various others](https://github.com/search?o=desc&q=python+version+manager+stars%3A%3E10&s=updated&type=Repositories).

Always remember to never ever 4ever run pip (or pip2, pip3) as root (with sudo, su, etc). Use `pip --user <blah>` instead.
