### ISSUE TITLE
"Download from Fanbox" function creates extra config.ini.bak and crashes

### ISSUE THREAD

**Issue by tenyuhuang** [Nandaka/PixivUtil2#654]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When choosing "f1. Download from supported artists (FANBOX)" or "f2. Download by artist id (FANBOX)", PixivUtil will create a config.ini.bak. The bak file will stay until next time an artist is loaded, then PixivUtil will crash and throw out an exception because the bak file is already there.

```Input: f1
Max Page =
Getting supported artists from https://fanbox.pixiv.net/api/plan.listSupporting
Found 13 supported artist(s)
[<REDACTED>]
Processing <REDACTED>, page 1
Getting posts from https://fanbox.pixiv.net/api/post.listCreator?userId=<REDACTED>&limit=10
Using OAuth to retrieve member info for: <REDACTED>
Writing config file... Backing up old config to config.ini.bak
Traceback (most recent call last):
  File "PixivUtil2.py", line 2448, in main
  File "PixivUtil2.py", line 2183, in main_loop
  File "PixivUtil2.py", line 1923, in menu_fanbox_download_supported_artist
  File "PixivUtil2.py", line 1935, in processFanboxArtist
  File "PixivBrowserFactory.pyc", line 745, in fanboxGetPostsFromArtist
  File "PixivBrowserFactory.pyc", line 503, in getMemberInfoWhitecube
  File "PixivConfig.pyc", line 763, in writeConfig
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'F:\\pixivutil\\config.ini.tmp' -> 'F:\\pixivutil\\config.ini'
press enter to exit.
```

While I could manually delete the extra config.ini.bak, it wasn't behaving like this a few versions before.

### Versions

20200307

**Comment by Nandaka** [comment]
no, from the logic, it failed when it try to rename the config.ini.tmp to config.ini. Do you set it as readonly?

**Comment by tenyuhuang** [comment]
> no, from the logic, it failed when it try to rename the config.ini.tmp to config.ini. Do you set it as readonly?

No. I even made a completely new install of PixivUtil, let it create its own config, write the content, made sure it's not read-only and it still gives me this error.

**Comment by tenyuhuang** [comment]
Also I'd like to supplement the issue - it's random. It happens like, 80% of the time; sometimes it will create the bak file successfully, sometimes not.

**Comment by bluerthanever** [comment]
The error says that it's not that it can't create itself, but that it can't rename the newly created itself with a ".temp" to "config.ini".
I would like to ask these questions:
1. Where did you put the whole util? Is it under any system folder or some partition that requires permissions to rename files?
2. Are you running multiple instances at the same time? Or is there any other program running that is using the "config.ini" file?
3. How do you start the whole util? Double-click on the built exe file or running from source code in programs like pycharm or tools like jupyter notebook?
Thank you.

**Comment by bluerthanever** [comment]
Can I ask how do you start the whole util? Double-click on the built exe file or from source code in cmd or pycharm or jupyter notebook?

**Comment by tenyuhuang** [comment]
> Can I ask how do you start the whole util? Double-click on the built exe file or from source code in cmd or pycharm or jupyter notebook?

I extracted the latest release package at `F:\pixivutil`, only one instance running, and launched through `PixivUtil2.exe`.

**Comment by bluerthanever** [comment]
Sorry for the late reply. This is weird. 'Cuz I don't think there's anything wrong with the util. Especially when you are running it from the executive file.
My further questions would be as follows:
1. You mentioned that 80% of the time it fails, does it give the same errors as in your first description of the issue?
2. When the error happens, what are the files whose filename starts with "config" under the folder?
3. What is your OS? When you extract it, do you delete all the old files, except for the config.ini?
4. Have you tried extracting it somewhere else? Does it still give the same error?

**Comment by tenyuhuang** [comment]
> Sorry for the late reply. This is weird. 'Cuz I don't think there's anything wrong with the util. Especially when you are running it from the executive file.
> My further questions would be as follows:
> 
> 1. You mentioned that 80% of the time it fails, does it give the same errors as in your first description of the issue every single time?
> 2. When the error happens, what are the files whose filename starts with "config" under the folder?
> 3. What is your OS? When you extract it, do you delete all the old files, except for the config.ini?
> 4. Have you tried extracting it somewhere else? Does it still give the same error?

```
Writing config file... Backing up old config to config.ini.bak
Traceback (most recent call last):
  File "PixivUtil2.py", line 2448, in main
  File "PixivUtil2.py", line 2183, in main_loop
  File "PixivUtil2.py", line 1923, in menu_fanbox_download_supported_artist
  File "PixivUtil2.py", line 1935, in processFanboxArtist
  File "PixivBrowserFactory.pyc", line 745, in fanboxGetPostsFromArtist
  File "PixivBrowserFactory.pyc", line 503, in getMemberInfoWhitecube
  File "PixivConfig.pyc", line 763, in writeConfig
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'H:\\put\\config.ini.tmp' -> 'H:\\put\\config.ini'
press enter to exit.
```

I made a completely new install of PixivUtil2, let it generate a fresh new config file, fill in the required infos, and it still crashes.

The error happens in this way: it creates a `config.ini.bak`, downloads the Fanbox entries, deletes `config.ini` and creates a `config.ini.tmp`, then crash.

I'm running it on Windows 7 x86-64. And as I said above, even a completely new install of it in another directory doesn't solve the problem.

**Comment by bluerthanever** [comment]
@Nandaka 
Hey Mister. I can only think of this issue happening because of "os.rename" now...
Cuz according to the description, the old "config.ini" could be successfully renamed to "config.ini.bak" with "shutil.move", but  a newly created "config.ini.tmp" could not be renamed to "config.ini" with "os.rename" as in:
https://github.com/Nandaka/PixivUtil2/blob/991f8e051b9950f8cb4b7d3b60fab11d4215d013/PixivConfig.py#L755-L763

Don't really know why yet though. Maybe it's because of Windows 7?
Hopefully this could be helpful or useful to you. Sorry I don't know how to setup py2exe yet so I can't yet provide a pyd file to test.

**Comment by tenyuhuang** [comment]
I intended to test the issue on a Windows 7 (32bit) virtual machine, however for whatever reason it will just crash at launch. I'll try if I could recreate the issue on another Windows 7/10 setup.

**Comment by Nandaka** [comment]
updated in latest commit to put explicit close() after writing the config file. I will upload beta version later.

**Comment by tenyuhuang** [comment]
Thank you very much!

**Comment by tenyuhuang** [comment]
Problems persist in version 202000404-beta2.
Should I try running it from Python?

**Comment by Nandaka** [comment]
you can try., check https://github.com/Nandaka/PixivUtil2/wiki item 2.

**Comment by tenyuhuang** [comment]
> you can try., check https://github.com/Nandaka/PixivUtil2/wiki item 2.

I tried the python version with Python 3.8.2 and **it does not have this issue**. Maybe it's something wrong with the pre-compiled exe version?

It shouldn't be a privilege issue because even if I ran the exe version with admin rights that error is still persistent.

**Comment by Nandaka** [comment]
Hmm, might be. Do you unblock the downloaded zip files before extracting?
![image](https://user-images.githubusercontent.com/836867/79099046-dd9eea80-7d95-11ea-9c7d-7c4ae9cac5b7.png)

**Comment by tenyuhuang** [comment]
There isn't an unblock/trust button in the first place, I might have already disabled that system-wide.

**Comment by Nandaka** [comment]
I'm not sure, I think you can use process monitor from sysinternal https://docs.microsoft.com/en-us/sysinternals/downloads/procmon to check which application that lock the file, but as you already installed from the script, I think you can just run from the source
