### ISSUE TITLE
there a limit using id_image options to download images

### ISSUE THREAD

**Issue by onexoff** [Nandaka/PixivUtil2#655]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.

**Comment by onexoff** [comment]
I can insert more than 24k id of images on time 
the limit is 1800
also is  possible to import id from text file ?

**Comment by Nandaka** [comment]
I don't get what do you mean? Are you trying to download 24k individual image id from console?

**Comment by onexoff** [comment]
yes

**Comment by Nandaka** [comment]
why?

**Comment by AgentThirteen** [comment]
Not a bug, not implemented. As far as I know from the readme file, `list.txt` is meant for artists, not individual pictures. PixivUtil is not really meant for full picture crawling and pixiv administration may also suspend accounts for that without prior notice.

Use a text splitter and run parallel processes for this many individual images (or `wget` them with the proper referrer), also be careful not to download too many or too much data too quickly for the above reason.

**Comment by Nandaka** [comment]
also it is due to limit on the console max character input.

**Comment by Nandaka** [comment]
Should be covered now by #197 to enable batch job from json files, which allow you to supply the image_id from text file as long you follow the format.

**Comment by Nandaka** [comment]
You can check https://github.com/Nandaka/PixivUtil2/releases/tag/v20200501-beta3 for the new batch option.

Json template is in: https://github.com/Nandaka/PixivUtil2/wiki/Using-Batch-Job-(Experimental)
