### ISSUE TITLE
Download fanbox articles in HTML

### ISSUE THREAD

**Issue by rwchunk** [Nandaka/PixivUtil2#656]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I want to store and view the article's text with the pictures embedded.
Downloading article to an HTML file would preserve this.
The formatting is like a list of text lines and images.
I'm not really sure what would be the best way to go about this, but I'd really appreciate it.

**Comment by bluerthanever** [comment]
Hey. I am actually quite interested in this idea.
I think technically it won't be toooooooo difficult. But I wanna ask a few questions.
1. How would you like the html pages to be like?  Exactly as what is shown on fanbox or a really simple html page with no style or whatsoever would do? 
2. What information would like to be shown on the page? Would you have the old txt files replaced by html files? Or do you want to control them in config.ini?

**Comment by bluerthanever** [comment]
And 1 more, this should only apply to article type posts, right?

**Comment by bluerthanever** [comment]
Hey. I am actually quite interested in this idea.
I think technically it won't be toooooooo difficult. Hmm.
I will probably start trying it out tomorrow on my side, and maybe pull a request?

**Comment by bluerthanever** [comment]
#659

**Comment by bluerthanever** [comment]
Hey. I just made it apply to article posts. is that enough for you?

**Comment by bluerthanever** [comment]
Hey. I just made it apply to article posts, is that enough?
And firefox, chrome and edge seem to be working fine though, IE seems to be not so compatible. What browser do you use?

**Comment by Nandaka** [comment]
PR merged
