### ISSUE TITLE
Need to update login detection: "cookie already expired or invalid"

### ISSUE THREAD

**Issue by connerbanner** [Nandaka/PixivUtil2#658]
I just got this issue and cant seem to fix it on my own.

I saw another similar issue that got fixed with updating python and tried that to nothing.

Ive updated python

Ive logged out and re logged in to my pixiv account and it generates a new cookie code but even with that its still says its expired

Ive pasted that new generated code on a new and old version of PixivUtil2 several times to no luck

1st time this has happened in like a year of using this program

I'm at a lost

**Comment by bluerthanever** [comment]
Did you try this one?
https://github.com/Nandaka/PixivUtil2/issues/505#issuecomment-510539272

**Comment by connerbanner** [comment]
yes ive been doing that over and over but each slightly new cookie value is still expired

**Comment by bluerthanever** [comment]
Can you please tell us the version you are using, and the error details?

**Comment by suvelin** [comment]
I'am same situation, too
After updating the Pixiv site
got this error

Trying to log in with saved cookie
Cookie already expired/invalid.
Logging in...
Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 317, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x1507B768>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x14D24A88>)
Cannot Login!

**Comment by connerbanner** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/58386443/78114512-4198da80-73b6-11ea-95dc-0a0b0bc9f1c3.png)

oops thought i adding that in

**Comment by bluerthanever** [comment]
hmm... I think this is maybe because the "https://www.pixiv.net" and "https://accounts.pixiv.net/login" pages are changed.

**Comment by bluerthanever** [comment]
Could anyone please provide the page source of  "https://www.pixiv.net" and "https://accounts.pixiv.net/login" ? I can login or login with saved cookie just fine... and you mentioned that pixiv updated and stuff. so I just wanna have a look into this...

**Comment by Romangelo** [comment]
I guess they made some change to the site. I've been using it just fine, until I close the software and relaunch it today.

**Comment by Shagiakhmetov** [comment]
I have the same problem and PHPSESSID does not help.
But when I created a new account PHPSESSID earned ...

**Comment by EfronC** [comment]
It doesn't work for me either, here is the source for accounts.pixiv.net, hope this is what is needed.

[Login _ pixiv_files.zip](https://github.com/Nandaka/PixivUtil2/files/4418358/Login._.pixiv_files.zip)

**Comment by bluerthanever** [comment]
> 
> 
> It doesn't work for me either, here is the source for accounts.pixiv.net, hope this is what is needed.
> 
> [Login _ pixiv_files.zip](https://github.com/Nandaka/PixivUtil2/files/4418358/Login._.pixiv_files.zip)

Sorry, I should have been more specific on my request. Can you do as follows and tell me the result instead?
1. Go to your browser, and make sure you are logged in, then go to "https://www.pixiv.net/".
2. Get the page source (you can do this by using developer tools or other ways, but try avoiding using save page to local and then open it)
3. Try looking for "logout.php" and "pixiv.user.loggedIn = true", and see if you get any result for each.
This is how the util tells if you are logged in.

**Comment by Shagiakhmetov** [comment]
> 3\. Try looking for "logout.php" and "pixiv.user.loggedIn = true", and see if you get any result for each.

I could not find the lines you specified, but in the page code I see the following lines

`<script>'use strict';var dataLayer = [{login: 'yes',gender: "male",user_id: "9473900",lang: "en",illustup_flg: 'not_uploaded',premium: 'yes',}];</script>`
Perhaps they can show that the authorization was successful

**Comment by Terryble2** [comment]
I've done the same as above, those strings are not present anywhere in the HTML. As Shagiakhmetov mentioned there are 2 script tags which contain some information about the logged in user. I've quoted them both below.

1.
```
<script>
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-1830249-3']);
_gaq.push(['_setDomainName', 'pixiv.net']);
_gaq.push(['_setCustomVar', 1, 'login', 'yes', 3]);
_gaq.push(['_setCustomVar', 3, 'plan', 'normal', 1]);
_gaq.push(['_setCustomVar', 5, 'gender', 'male', 1]);
_gaq.push(['_setCustomVar', 6, 'user_id', "3145410", 1]);
_gaq.push(['_setCustomVar', 11, 'lang', "en", 1]);
_gaq.push(['_setCustomVar', 12, 'illustup_flg', 'not_uploaded', 3]);
_gaq.push(['_setCustomVar', 13, 'user_id_per_pv', "3145410", 3]);
_gaq.push(['_setCustomVar', 27, 'p_ab_d_id', "1828365849", 3]);
</script>
```
2.
```
<script>
'use strict';
var dataLayer = [{ login: 'yes', gender: "male", user_id: "3145410", lang: "en", illustup_flg: 'not_uploaded', premium: 'no', }];
</script>
```

**Comment by bluerthanever** [comment]
To @Shagiakhmetov @Terryble2 
Thank you guys. I can find `pixiv.user.loggedIn = true` and those you have mentioned as well....
That's weird.
@Nandaka, do you have any idea...? Do you think we should update logic to just check for these strings?

**Comment by connerbanner** [comment]
So I don't know what any of the stuff you guys are talking about mean on a program-e level but im guessing form the sounds of it, this is a issue that might get fixed with an update and not something that can be fixed in my desktop? Just want to know whats up.

**Comment by Terryble2** [comment]
@connerbanner Yes, the Pixiv website has been updated so until a fix comes out in a new release it won't work.

**Comment by connerbanner** [comment]
@Terryble2 damn hope it wont take long, its already been like 4 days and lifes already not the same without it. Over 1,176 profiles downloaded that its basically become routine to search the boorus, find the artists and download their profiles. Now without it do I realize that "damn I really don't do much else huh?" Godspeed PixivUtil2.

**Comment by Nandaka** [comment]
> To @Shagiakhmetov @Terryble2
> Thank you guys. I can find `pixiv.user.loggedIn = true` and those you have mentioned as well....
> That's weird.
> @Nandaka, do you have any idea...? Do you think we should update logic to check these strings as well?

it is already checked for that string though
https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L280

**Comment by Nandaka** [comment]
> I've done the same as above, those strings are not present anywhere in the HTML. As Shagiakhmetov mentioned there are 2 script tags which contain some information about the logged in user. I've quoted them both below.
> 
> 
> ```
> <script>
> var _gaq = _gaq || [];
> _gaq.push(['_setAccount', 'UA-1830249-3']);
> _gaq.push(['_setDomainName', 'pixiv.net']);
> _gaq.push(['_setCustomVar', 1, 'login', 'yes', 3]);
> _gaq.push(['_setCustomVar', 3, 'plan', 'normal', 1]);
> _gaq.push(['_setCustomVar', 5, 'gender', 'male', 1]);
> _gaq.push(['_setCustomVar', 6, 'user_id', "3145410", 1]);
> _gaq.push(['_setCustomVar', 11, 'lang', "en", 1]);
> _gaq.push(['_setCustomVar', 12, 'illustup_flg', 'not_uploaded', 3]);
> _gaq.push(['_setCustomVar', 13, 'user_id_per_pv', "3145410", 3]);
> _gaq.push(['_setCustomVar', 27, 'p_ab_d_id', "1828365849", 3]);
> </script>
> ```
> 
> 
> ```
> <script>
> 'use strict';
> var dataLayer = [{ login: 'yes', gender: "male", user_id: "3145410", lang: "en", illustup_flg: 'not_uploaded', premium: 'no', }];
> </script>
> ```

added additional validation on latest commit. I will upload beta version later.

**Comment by Shagiakhmetov** [comment]
> I will upload beta version later.

Добрый день.

К сожалению ошибка сохраняется... Я приложил лог с параметром "loglevel = INFO" и скриншот с параметром "debughttp = True"

![2020-04-04 (2)](https://user-images.githubusercontent.com/63021549/78453551-29b5a500-769b-11ea-8150-df43537fe814.png)
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4431680/pixivutil.log)

**Comment by Nandaka** [comment]
updated in https://github.com/Nandaka/PixivUtil2/releases/tag/v20200404-beta2, can you try it?

**Comment by Shagiakhmetov** [comment]
> can you try it?

Thanks.
Now everything is working.

**Comment by Terryble2** [comment]
@Nandaka Works perfectly, thank you!

**Comment by connerbanner** [comment]
@Nandaka Huzzah, the fog has lifted!
