### ISSUE TITLE
Adding a "Oldest to Newest" option to Download by tags /from tags list.

### ISSUE THREAD

**Issue by purp13** [Nandaka/PixivUtil2#66]
Pixiv allows the regular users to sort the tags results in 2 ways: "Newest" and "Oldest". "Newest" is the default, the results on page 1 are the more recent uploaded. Sorting by "Oldest" has 4 sub-options: "All Time", "Within Last Day", "Within Last Week" and "Within Last Month". When choosing "Oldest: All Time", the oldest pictures will be shown on page 1, newest being on the last page.
Picture of the sorting options: http://i.imgur.com/9LuthVl.png

There is also a 3rd sorting option "Sort by Popularity" which is only available for Premium Accounts.

In the current version on the program you can pick the Start Page and End Page, however, if you try to put Start Page= 5 and End Page = 1, as an (silly) attempt to make it go backwards, it doesn't allow you to do that and takes the # as the # of Max Pages. [It's not a issue.]

Adding an option "Oldest to Newest" in Download by tags(/ from tags list), I don't know, something like:
Sorting: [Newest] [Oldest], Newest being default, so if left blank = default.
or
Download oldest results first?: [Y/N] , N being default, blank = N.

It would be helpful when downloading by tags that are constantly being updated with new art.

Also the change in the url is only at the end:
Newest, page 2: &order=date_d&p=2
Oldest, page 2: &order=date&p=2
I don't know if that helps.

**Comment by Nandaka** [comment]
what is the url if the list is sorted by popularity?

**Comment by Nandaka** [comment]
anyway try this one: http://www.mediafire.com/download/rkdgh511zs47alk/pixivutil20150121.7z

**Comment by purp13** [comment]
I don't have premium so I don't know about the url sorted by popularity.

It works perfectly! Good work and Thank you! :)
