### ISSUE TITLE
IndexError on login

### ISSUE THREAD

**Issue by SimonPilkington** [Nandaka/PixivUtil2#662]
v20200404-beta1 fixed the "cookie already expired or invaild" issue, but now this happens:

```
Only process members where the last update is >= 7 days ago
Using Username: *redacted*
Trying to log in with saved cookie
Login successful.
Error at doLogin(): (<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x1203A0A8>)
Cannot Login!
press enter to exit.
```

Removing config.ini and starting over does not fix the issue.

**Comment by Nandaka** [comment]
can you upload the log file here? 
You can delete the old `pixivutil.log`, rerun the program, and then upload the new log file here.

**Comment by SimonPilkington** [comment]
Here is the log file from the above login attempt: [pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4431634/pixivutil.log)

**Comment by Nandaka** [comment]
looks like related to #658

**Comment by Nandaka** [comment]
updated in https://github.com/Nandaka/PixivUtil2/releases/tag/v20200404-beta2, can you try it?

**Comment by SimonPilkington** [comment]
Looks fixed. Thanks.
