### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '//あいうえお.test'

### ISSUE THREAD

**Issue by EfronC** [Nandaka/PixivUtil2#663]
### Prerequisites

* [*] Did you read FAQ section?
* [*] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I've been using PixivUtil2 to download for some time, and everything has worked perfectly, until it gave the error #658 , i saw that the error was solved a few hours ago, i made a git pull, and it worked to pass the login, but when i tried to download from the option 1, it launched this error from the very first image

```
Member Background : no_background
Processing images from 1 to 16 of 16
Traceback (most recent call last):
  File "PixivUtil2.py", line 492, in process_member
    download_image(artist.artistAvatar,
  File "PixivUtil2.py", line 137, in download_image
    test_utf = open(filename_test + '.test', "wb")
PermissionError: [Errno 13] Permission denied: '//あいうえお.test'
Error at process_member(): (<class 'PermissionError'>, PermissionError(13, 'Permission denied'), <traceback object at 0x74b92488>) 
Dumping html to: Error page for member 31040169 at page 1.html 
Traceback (most recent call last):
  File "PixivUtil2.py", line 2474, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 2172, in main_loop
    menu_download_by_member_id(op_is_valid, args)
  File "PixivUtil2.py", line 1558, in menu_download_by_member_id
    process_member(member_id, page=page, end_page=end_page, title_prefix=prefix)
  File "PixivUtil2.py", line 492, in process_member
    download_image(artist.artistAvatar,
  File "PixivUtil2.py", line 137, in download_image
    test_utf = open(filename_test + '.test', "wb")
PermissionError: [Errno 13] Permission denied: '//あいうえお.test'
press enter to exit.
```

I thought that just using sudo to start the program would solve it, but with `sudo python PixivUtil2.py` then it doesn't even open the program, just launches another error

```
File "PixivUtil2.py", line 56
    print("\b \b", end="")
                      ^
SyntaxError: invalid syntax
```

### Steps to Reproduce

1. Start the program with `python PixivUtil2.py`
2. Select Option 1
3. Add 1 or more IDs
4. Start Download

**Expected behavior:** Start Downloading all images from the gallery

**Actual behavior:** Launched error above pasted

### Versions

PixivDownloader2 version 202000404-beta2

**Comment by Nandaka** [comment]
using python3?

**Comment by EfronC** [comment]
> using python3?

Yes

```
Python 3.8.0 (default, Dec 28 2019, 00:17:22) 
```

**Comment by Nandaka** [comment]
can you get the latest commit? you are using windows?

**Comment by bluerthanever** [comment]
seem to be linux?

**Comment by Nandaka** [comment]
that's the weird thing, https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L56 should be only for windows, also that syntax is correct for python3.

@EfronC  ensure only python3 is installed, maybe the os try to run it as python2? I'm not using linux so I'm not that sure about it.

**Comment by EfronC** [comment]
I pulled the last commit and the error keeps, is the latest commit supposed to not work on Linux? 

And yes, my PixivUtil is running on a RPi with Raspbian, i've Python 2.7.16 as de default Python that came installed with the system, and also have Python 3.8.0 with a venv for the program to run, that's actually the reason why i can't use sudo, since sudo automatically changes to the system Python, instead of using the venv Python.

**Comment by Nandaka** [comment]
Try https://askubuntu.com/a/245921, also check your 'filenameformat' and the 'rootdirectory' in config.ini. 
Check the generated save filename, somehow it try to write to your root dir.

I suspect it might be related to changes on #647 
Try to change https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L123  
to 
```python
name = rootDir + name
```

**Comment by EfronC** [comment]
> I suspect it might be related to changes on #647
> Try to change https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L123
> to
> 
> ```python
> name = rootDir + name
> ```

Yes, seems like that was the problem, changed that line, and for now seems to be working. Thanks, and i hope that a future commit can solve it without local changes.

**Comment by EfronC** [comment]
Ok, quick update: No, the fix didn't really work by itself, first `name = rootDir + name` join them without a separator, fusing the name of the parent folder with the child, then `name` was the root to the child folder using windows separators "\" instead of linux "/", luckily i noted this before a huge number of files were downloaded.

**Comment by Nandaka** [comment]
check your filenameformat in config.ini, is it using '/' or '\' for separating the path?

**Comment by Nandaka** [comment]
also change `name = rootDir + os.sep + name'

**Comment by EfronC** [comment]
Yep, that was the easy to solve, the problem was the second name, which contained the name of the file, an example:

Right:
/home/pi/Pictures/Pixiv/[user] ([Id])/[image_name].jpg

Wrong(The one the program generates):
/home/pi/Pictures/Pixiv[user] ([Id])\[image_name].jpg

Note the inverted Slash before image_name

I solved it with a pair of lines to replace the inverted slash with normal, but i'm not sure this is not causing problems on other parts of the program, that's why i prefer to wait for an official commit that has been tested.

**Comment by RoestVrijStaal** [comment]
I got a similar error when using the current master (at time of writing this) and the newest releases. Somehow the error does not occur at version v20200307.

**Comment by Nandaka** [comment]
@EfronC check your filenameformat in config.ini. By default it will uses windows path separator.
![image](https://user-images.githubusercontent.com/836867/78640125-c8cbde00-78e1-11ea-869e-bec5eabad498.png)

@RoestVrijStaal check latest commit?

**Comment by Nandaka** [comment]
@EfronC can you try again with latest commit? I don't have linux to test :smile:

**Comment by EfronC** [comment]
Tried the last commit, and seems to be working, will keep an eye just in case, also

> I don't have linux to test 😄

I guess you use Windows to develop, and probably Windows 10, so, have you tried WSL? That's what i used some time ago when i launched PixivUtil on my Windows, because of a problem i had with my username that made imposible to use the program on it, and had to run it on a Linux environment.

**Comment by RoestVrijStaal** [comment]
> @EfronC check your filenameformat in config.ini. By default it will uses windows path separator.
> ![image](https://user-images.githubusercontent.com/836867/78640125-c8cbde00-78e1-11ea-869e-bec5eabad498.png)
> 
> @RoestVrijStaal check latest commit?

Okay, so to be sure: I'd need to modify the slashes in my `config.ini` beforehand to get things fixed at all?
```desktop
[Filename]
filenameformat = %R-18%/%image_id%_%title%_by_%artist%
filenamemangaformat = %R-18%/%image_id% - %title% by %artist%/%image_id%-p%page_index%_%title%_by_%artist%
filenameinfoformat = %R-18%/%image_id%_%title%_by_%artist%
filenamemangainfoformat = %R-18%/%image_id% - %title% by %artist%/%image_id%-p%page_index%_%title%_by_%artist%
```

**Comment by Nandaka** [comment]
if you are using windows, use '\`
if you are usin linux, use '/'

**Comment by RoestVrijStaal** [comment]
Ok, so my config.ini has already the proper slashes. 

Today I tried out master at commit _6cd5e4b_ with 3 various postings (1 ugoira, 1 "normal post", and 1 manga). No PermissionError occurred. 

I wonder if @EfronC has also no PermissionErrors anymore?
