### ISSUE TITLE
[Feature Request] use rounded down Bookmark numbers as directory. 

### ISSUE THREAD

**Issue by pxssy** [Nandaka/PixivUtil2#667]
I'm currently downloading with this output scheme to sort out the better artworks. 

`out\%bookmark_count%\%urlFilename%`

But i'm finding out that i'm getting tens of thousands of folders, which in retrospect, is kind of expected as there are anywhere between 1-100,000 possible "bookmark numbers", and at the very high 10k-100k bookmarks there could very well be only 1 image in 1 folder of 88324 bookmark

Is there any way to round down bookmark numbers before being used as a directory? Like Round the bookmark numbers to only 2 significant digit. eg 88324  becomes 88000. 

That should cap out the folders to a more manageable number.

**Comment by rwchunk** [comment]
Why do you want to use this format of folder/image? 
How about using `out\%bookmark_count%_%urlFilename%` ?
