### ISSUE TITLE
Can't Run Newer Versions in Win8.x

### ISSUE THREAD

**Issue by archet-VIII** [Nandaka/PixivUtil2#668]
Haven't had time to follow up on this until now, but as I mentioned on issue #632 I haven't had any luck getting the Python 3.8-based versions of the downloader running. I have 3.8 installed and up to date (currently at 3.8.2) on this Win8.1 machine, but every time I try to run one of the versions of PixivUtil that uses it the command window just displays a few lines of text and then immediately closes itself. I've managed to snap some screenshots as it flashes by, and it's consistently shown the same message with every version of Python and the downloader that I've tried. 

![Screen Shot 04-11-20 at 05 59 AM](https://user-images.githubusercontent.com/35877186/79052718-73a40b00-7c06-11ea-9bb6-b6ac7877a547.PNG)

I'm assuming that I messed something up somewhere, but I can't decipher that to figure out where to start looking. Any assistance would be greatly appreciated.

**Comment by Nandaka** [comment]
you are running from script or from the zip file? You don't need to install python if you want to run from zip file.

also try to do fresh install to another folder?

**Comment by archet-VIII** [comment]
Been running it the same way I've always run it. Download the zip, move it to a folder on the drive I've been archiving stuff on, unpack it, open the resulting folder and run the PixivUtil2.exe file in there as an administrator. So it's basically a fresh install in a new folder every time. Ran the pre-3.8 versions like this for years without any particular problems.

**Comment by Nandaka** [comment]
weird, it is working in my side. Can you upload the log file `pixivutil.log` here?
Delete the old one and rerun to regenerate the issue and upload that one.

**Comment by Nandaka** [comment]
also, try to extract it to C:\temp, maybe the long file path cause an issue (cos I add beta2 there).

**Comment by archet-VIII** [comment]
Unfortunately it doesn't even get to the point of producing a log. The first step I usually do when starting a new version is to run it briefly to generate the config file, and it's not even doing that. It just immediately closes itself after displaying the above message without writing anything to the disk whatsoever.

**Comment by Nandaka** [comment]
even after moving the to shorter path? Can you try on different Windows version? I'm suspecting that because you are using win8.1

**Comment by archet-VIII** [comment]
Even with the shorter path, it outright refuses to run on the 8.1 machine. My home theater PC is on Win10, and I can get the downloader to run on it, although I haven't tested it beyond the log-in prompt yet. Running it there is less than ideal, though, especially since it means I'll have to try and get it to save to the archive drive in the older machine over network.

**Comment by Nandaka** [comment]
hmm I guess it is really because of compatibility issue, considering Win8.1 is not supported anymore by microsoft in general.
Can you try to run it from script? See https://github.com/Nandaka/PixivUtil2/wiki item 2.
