### ISSUE TITLE
Bookmark Images

### ISSUE THREAD

**Issue by vampiricwulf** [Nandaka/PixivUtil2#67]
It'd be nice to have it bookmark the images as you download them.

**Comment by Nandaka** [comment]
Not good, if you do batch then your bookmarks can easily hit thousands (and I don't know if there is a limit on the pixiv website).

**Comment by vampiricwulf** [comment]
Ahh, alright, I saw it on Ank's Pixiv add-on for firefox, thought it might
be something nice for people who wanna give recognition to images and
authors. Thanks anyway~

Also, thank you for all your hard work.
