### ISSUE TITLE
Utility fails to load at all. HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by pxssy** [Nandaka/PixivUtil2#672]
[Screenshot](https://i.imgur.com/5EpQf3P.png)

kept closing upon the error.

Not sure why, the last time i used was 21th 0300hrs GMT+0. worked fine.

AFAIK i changed nothing on my PC.

**Comment by Nandaka** [comment]
That one server side error, cannot do anything I guess? Ensure you can open the website?

Working from my side:
![image](https://user-images.githubusercontent.com/836867/79892509-44c33b80-8435-11ea-95b7-9d71ef538a31.png)

**Comment by pxssy** [comment]
Yeah its working now. Must've been some temporary outage.
