### ISSUE TITLE
[Question] downloaded files goes to outside the PixivUtil2.exe folder

### ISSUE THREAD

**Issue by vola-volant** [Nandaka/PixivUtil2#673]
Why after updatign to the latest beta ver, my downloaded pics are saved outside the PixivUtil2.exe folder?

For example: 

Before updating, the pics went to D:\pixivutil20200404-beta2\tagname
After Updating, the pics now go to D:\ instead

**Comment by bluerthanever** [comment]
Could you post your config.ini?
And just to confirm, does any error occur while it is running? Like filename too long or access denied or anything?

**Comment by vola-volant** [comment]
here is my config.ini

And to answer the questions...no, it doesn't have any error when running.

[config.zip](https://github.com/Nandaka/PixivUtil2/files/4520066/config.zip)

**Comment by bluerthanever** [comment]
err.... maybe you forgot to delete the username and password?

**Comment by vola-volant** [comment]
tried deleting the username and password. the program logs in into my account using the cookie.

but it still download the pics to D:\

**Comment by bluerthanever** [comment]
ah... okay. just in case. I will have a look....

**Comment by vola-volant** [comment]
thanks. 

Dunno if this will be useful or not, but if I change the "filenameformat" to other than "%R-18%\%image_id%", like "%title%", somehow the program will recognize the PixivUtil2.exe folder and store the pics inside it or inside the tag folder within in.

**Comment by bluerthanever** [comment]
hmm... I just tried running from the codes, and running with the latest released beta version with your settings, and they seem to be working fine with regular pixiv images, but somehow not as expected with fanbox posts.
with the codes:  fanbox posts are downloaded to the same directory with the codes.
with the release: downloaded to outside of the directory of the exe file.

is it the same with you? it only happens when you try to download fanbox posts?

**Comment by bluerthanever** [comment]
well, i think because there is no R-18 tag in fanbox posts...?

**Comment by vola-volant** [comment]
umm I usually download things without knowing if it's fanbox posts or not, so I don't really know.

**Comment by vola-volant** [comment]
I tried changing the "filenameformat" to, for example, "a\%R-18%\%image_id%"
Then using "Download by image_id" action with ID from here: https://www.pixiv.net/en/artworks/80895839

The program made a folder named "a" and store the pic inside it.

**Comment by bluerthanever** [comment]
hmm... but they are done from different menu items. like fanbox posts are triggered with selection starts with an "f" while regular images are just numbers.

do you also download fanbox posts?

**Comment by vola-volant** [comment]
Ummm sorry. How do I know if I download a fanbox post(s) or not? is it stored within my config.ini too?

**Comment by bluerthanever** [comment]
did you ever use f1 or f2 to download fanbox posts? it's a different menu item though....
but I think most probably not... by the look of you not even knowing if you are downloading them or not...

could you give the image id of one of the files that were downloaded to outside the folder?

**Comment by vola-volant** [comment]
80961116

and actually, the Id in the previous link I provided above also downloaded to outside the folder if I still use the "%R-18%\%image_id%" as filenameformat

**Comment by bluerthanever** [comment]
okay... thanks. let me have another look.

**Comment by bluerthanever** [comment]
Hmm. I think the issue is fixed already. just that nandaka-sann has not yet released a new zip file version.

**Comment by vola-volant** [comment]
Okay. Sooo I just wait until the next release?

**Comment by bluerthanever** [comment]
I guess so.
btw I think it's better you delete your config.ini with cookie string in it in this thread.... people could use the session id to do stuff.

**Comment by vola-volant** [comment]
okay. deleted the comment with my config.ini. thank you for your help.

**Comment by bluerthanever** [comment]
glad to help.

**Comment by Nandaka** [comment]
new release uploaded.

**Comment by vola-volant** [comment]
Replaced the files in my folder with the new release.
Now the pics are downloaded to their respcetive folders again when I use the usual "Download from tag list". 

Thank you very much.
