### ISSUE TITLE
Unable to download images [Solved]

### ISSUE THREAD

**Issue by FuzenKyubi** [Nandaka/PixivUtil2#674]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Can't seem to download images, sorry I'm not very knowledgeable in this stuff. I'm using the PxivUtil2.exe version
### Steps to Reproduce

1. Download by Member_id
2. Input Member id
3. Start Page = 1
4. End Page = 0

**Expected behavior:** [What you expected to happen]
Images to start downloading as per usual

**Actual behavior:** [What actually happened]
Various Errors instead (attached pixivutil.log)
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4523423/pixivutil.log)

### Versions
202000404-beta2
You can get this information from executing `PixivUtil2.py --help`.

**Comment by Nandaka** [comment]
hmm, looks like it failed when it try to get the json data from https://www.pixiv.net/rpc/get_work.php?id=79118539.

Can you open it on the browser? Can you try with latest releases? Looks fine when I tried to download the member id = 69581.

If it still not working, can you upload the config.ini here (remember to remove your login/cookie/token data in authentication section)

**Comment by FuzenKyubi** [comment]
Hey Nandaka!

I definitely can open the images on my browser. I'm not too sure what you mean by trying with latest releases.

I've attached my config.ini (it won't let me attach .ini file so i converted to TXT
[config.txt](https://github.com/Nandaka/PixivUtil2/files/4527396/config.txt)

**Comment by FuzenKyubi** [comment]
Ah good news! I apparently had the wrong thing in as my cookie id!

Apologies for the trouble... It's a bit weird it still logged me in though.

Thanks for helping Nadaka

**Comment by Nandaka** [comment]
btw, latest releases here: https://github.com/Nandaka/PixivUtil2/releases
