### ISSUE TITLE
[Question?/Discussion?] About PixivConfig

### ISSUE THREAD

**Issue by bluerthanever** [Nandaka/PixivUtil2#675]
Hey, Nandaka san.
I am trying to use multiple config.ini files to deal with regular images and fanbox post images lately. And I found out that:

1. In `loadConfig`, when getting values of each item in `try... except...` clause, it deals with ValueError only, which means, if there are other types of errors, like NoOption something error when there's a new item added in a new version, it can't be catched, and the whole process kinda stops and goes to the end, with the other items overwritten with default values. Is it better to catch all types of errors? Or what is your main concern when you write this part here?
2. In the following section, which is also in `loadConfig`, when the config.ini it tries to load has errors, it calls "writeConfig", but the path is not given, which means if the config.ini is given by -c option from somewhere else, the backup file and new files would be written to script folder, but the `configFileLocation` does not change at all. I myself wanted to change `writeConfig` method to use self.configFileLocation, so that every time it is called. OR simply adding path here will do as well.
https://github.com/Nandaka/PixivUtil2/blob/acba4ec6fe0c6130c2c9a4754e6a3dbb5418bc74/PixivConfig.py#L653-L655
3. With so many items in config, it kinda becomes harder and harder to look for items in `TwitterConfig.py`, I sometimes would fear that I might forget to change somewhere when adding new items in it. Would it be better to like make a dictionary or structure kinda thing, if you need to add new items you just change in that, while the other methods just iterate the dictionary or whatever. I personally have not thought of a good plan yet though.

I would like to know your opinions. =)

**Comment by bluerthanever** [comment]
And another thing, fanbox is going to be transfered to `fanbox.cc`, I guess all the APIs might be changed as well....
If you need help with that, please let me know, I would love to help.

**Comment by bluerthanever** [comment]
I just came up with a plan, I will pull a request now, please have a look if you please, thank you.
=)

**Comment by bluerthanever** [comment]
#676

**Comment by Nandaka** [comment]
0. Twitter Config?
1. That's why new config item need to be put on the last, so it will handle the configuration upgrade automatically and set the default value there when it write back the new config.
2. Originally, it doesn't support to read from custom config file location (and I don't use it) so I think it just overlooked 😄 
3. You need to handle the configuration upgrade so you don't lost the current values from the old config, so far this one is the easiest way

**Comment by bluerthanever** [comment]
0. Sorry, that was a typo.
1. Hmm... never thought about that though.... I think I always put them according to its section
2. Then why would there be a `setup_option_parser` method in `PixivUtil2.py`.... Isn't that supposed to be used for convenience?
3. I think my codes could keep the current values from old config. I will confirm again.

**Comment by Nandaka** [comment]
2. yeah, someone else request that, but because I don't really using it (and no one said anything), so I didn't aware of any issue on it :P

**Comment by bluerthanever** [comment]
Oh. I see. Haha. Actually I think it could be quite convenient, because I sometimes need to delete the whole folder to upgrade, especially before I know how to use python. I will confirm on the old value thingy and order now.
