### ISSUE TITLE
[Question] About FANBOX downloads

### ISSUE THREAD

**Issue by bluerthanever** [Nandaka/PixivUtil2#677]
Hmm. I have a lot of questions lately. Haha. Hope you don't mind. I just got all the time in the world... kinda.

1. Have you thought about keeping records of FANBOX download? A database or data table would help the management a lot. Not so important though. I am using excel so far...
2. Also have you thought about downloading FANBOX posts by post ids? Because sometimes, the author has soooooooooo many posts and they just update a few of them. It feels like years to watch it going through pages... especially that it takes longer now.

**Comment by Nandaka** [comment]
I'm not using FANBOX, so I don't have plan for it.
1. You can duplicate the existing member and image tables to separate table (e.g. fanbox_image and fanbox_member)
2. This should be easy, some adaptation required so it can get the member details for given post id.

**Comment by bluerthanever** [comment]
Okay, I will start working on it then. Haha.

**Comment by bluerthanever** [comment]
https://github.com/Nandaka/PixivUtil2/pull/679
Please confirm
