### ISSUE TITLE
[Feature Request] Download from "following" fanbox user

### ISSUE THREAD

**Issue by MonoS** [Nandaka/PixivUtil2#681]
### Prerequisites

* [X] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? Release

### Description

Ability to download from following users instead of supporting.
Some users allow to see some of the post for free, put action F1 only download posts from supporting user.
The API endpoint to obtain the list seems to be https://api.fanbox.cc/creator.listFollowing that return this json [creator.listFollowing.txt](https://github.com/Nandaka/PixivUtil2/files/4540310/creator.listFollowing.txt)

### Versions
20200424

**Comment by bluerthanever** [comment]
I guess I will just do this

**Comment by MonoS** [comment]
> 
> 
> Actually I think F2 downloads posts which you have access to, not just from those that you are supporting.
> Maybe you meant F1?

Yes, i meant F1, it was a typo. Anyway F1 doesn't work as i say because it looks for "supported" artist, that is a different list from the "following" list.

**Comment by bluerthanever** [comment]
Whew... submitted the changes.... Hopefully it will work.....

**Comment by Nandaka** [comment]
updated in the latest beta release: https://github.com/Nandaka/PixivUtil2/releases/

**Comment by MonoS** [comment]
Tried and it seems to work, thank you, i'd just output a warning in case the user did not fill the fanbox cookie as i struggled a bit to understand why it was not working.

**Comment by bluerthanever** [comment]
hmm. sorry for that. there should be a few lines that's newly added and shows the fanbox login status....
I guess they are buried in the prints and failed to get themselves noticed....?

**Comment by MonoS** [comment]
Probably yes, did they show at startup?

**Comment by bluerthanever** [comment]
I think so, after login into pixiv.net with cookie.
And Nandaka-sann made some optimization, in the next version you should be able to see things like 
"Trying to log in FANBOX with saved cookie", "FANBOX Login successful", "FANBOX login cookie string invalid, please update in config.ini", "Not logged in to FANBOX" kinda information.

**Comment by MonoS** [comment]
Good to know, thank you :)

**Comment by bluerthanever** [comment]
Hmp. Just checked again. They seem to be showing first thing after you use FANBOX functions.

**Comment by MonoS** [comment]
I've removed the fanbox cookie from the config.ini and lauched the application on the latest version and i don't see any warning
![image](https://user-images.githubusercontent.com/801011/80734347-51b7ed00-8b0f-11ea-96a6-3fefb69084c1.png)
I've then tried to use both F1 and F4 function and i've got this
![image](https://user-images.githubusercontent.com/801011/80734484-86c43f80-8b0f-11ea-8a25-a9e574ff9a36.png)

**Comment by Nandaka** [comment]
do you continue the execution or not? from the code, looks like it will write to log file rather than printing to console
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1938

**Comment by bluerthanever** [comment]
I think a few indent adjustment would do....
Should I pull a request? I kinda feel like I am pulling too many...

**Comment by Nandaka** [comment]
@bluerthanever should updated on latest commit, I just remove the check on main script, as it will be checked in the `fanboxGetUsers()`

**Comment by bluerthanever** [comment]
Wow, that was fast....

**Comment by Nandaka** [comment]
nah, just bored because of COVID-19 circuit breaker and today supposed public holiday, but I cannot go anywhere......

Anyway, I don't mind multiple pull request, also only you so far actively updating the FANBOX features 😃

**Comment by bluerthanever** [comment]
Haha. I would love to be helpful. 😀
