### ISSUE TITLE
Fanbox Member-Id Vanished

### ISSUE THREAD

**Issue by gnarf1975** [Nandaka/PixivUtil2#682]
f2 Download by Artist-Id

There´s no Member-Id on Fanboy anymore. 
Example Link: https://www.fanbox.cc/@shimashima
Artist-Name (Id) on Pixiv:  Re_しましま (9935837)

If you know the Pixiv-Id (Number) , it still works.

**Comment by daniels1989** [comment]
Huh, it's also fanbox.cc now instead of pixiv.net/fanbox.

For a future update: It's possible to get the user id from https://api.fanbox.cc/creator.get?creatorId=<creator name as it appears in the url without the leading @>

**Comment by bluerthanever** [comment]
I am working on it though... but it kinda requires new cookie....
I am literally having a headache right now

**Comment by Nandaka** [comment]
updated in latest beta releases: https://github.com/Nandaka/PixivUtil2/releases/

**Comment by daniels1989** [comment]
@bluerthanever I may have a solution for your ever changing fanbox cookie problem.

Rummaged around a bit with Postman and if I send a request to pixiv.net/fanbox with my PHPSESSID cookie, then the response has several Set-Cookie headers, one of which has a fresh FANBOXSESSID that I can then use for requests to fanbox.cc

**Comment by bluerthanever** [comment]
> @bluerthanever I may have a solution for your ever changing fanbox cookie problem.
> 
> Rummaged around a bit with Postman and if I send a request to pixiv.net/fanbox with my PHPSESSID cookie, then the response has several Set-Cookie headers, one of which has a fresh FANBOXSESSID that I can then use for requests to fanbox.cc

Thank you. =). That is really helpful. I will give it a try.

**Comment by Nandaka** [comment]
@bluerthanever 

I think you can handle it by wrapping the fanbox request to a custom method? For example:
```python
def fanbox_request(self, p_url):
        p_req = mechanize.Request(p_url)
        p_req.add_header('Accept', 'application/json, text/plain, */*')
        p_req.add_header('Referer', p_referer)
        p_req.add_header('Origin', 'https://www.fanbox.cc')
        p_req.add_header('User-Agent', self._config.useragent)

        p_res = self.open_with_retry(p_req)
        # check the response header
        new_cookie = p_res.get("Set-Cookie")
        # update the cookie data
        self._config.cookieFanbox = process_the_new_cookie
        self._loadCookie(self._config.cookieFanbox, "fanbox.cc")
        return p_res
```

Of course you need to check if the Set-Cookie header exists or not.

**Comment by bluerthanever** [comment]
Yeah, I think most likely the response status code should be code 302 or redirected.... so need to set `allow_redirects` to False I guess, to catch the cookies....
I will try it out tomorrow.... So maybe the newly added `cookieFanbox` could be refreshed.

**Comment by bluerthanever** [comment]
Turns out I don't need to set allow_redirects. I was thinking about `requests`....
Just added methods to update FANBOX cookie string.
