### ISSUE TITLE
[User related?] pximg.net, fanbox.cc, booth.pm unresponsive after fanbox.cc transition, breaks PixivUtil and browsers

### ISSUE THREAD

**Issue by AgentThirteen** [Nandaka/PixivUtil2#686]
I am making sure this is not on my end because it was not reported between the 27th and the 28th.

If this is confirmed to be a server issue nothing can be done except tell pixiv administration about it.

### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

`pximg.net` shows insane response times (pinging, traces and network analysis in any browser regardless of account, cookie status, IP or even device) and leads to terrible speeds/timeouts, incomplete files. It effectively becomes impossible to use PixivUtil at all... or download any work for that matter.

This happens both on FANBOX and pixiv even though all analysis of `fanbox.cc` shows no networking issues as it still relies on pximg, and effectively started right after the full transitioning to fanbox.cc was done which is no coincidence in my opinion. Not a temporary outage either.

### Steps to Reproduce

1. Any option that involves more than 1 download not yet databased.
2. Check the console and check the dump as soon as something clearly goes wrong.
3. `socket.timeout: The read operation timed out` repeatedly. Downloads will eventually complete but it will take forever even for 10-20 files, which may in turn lead to too many retries triggering a red flag.

**Expected behavior:** Downloads working as intended without any kind of throttling.

**Actual behavior:** Timeouts and file corruption regardless of previous or current usage of the tool or browser for that matter.

### Versions

`v20200226-beta1` 7ba4e38
`v20200428-beta1` b85e4ba

Thanks as always to the github community and Nandaka and thanks in advance for your replies.

**Comment by Nandaka** [comment]
Are you sure this is not because of your ISP issue? I can get 1MB/s for download from my side for pixiv.net

**Comment by bluerthanever** [comment]
Have you tried accessing the images in browsers? Do pictures show normally there?
Or pinging `pximg.net `?

**Comment by Azunyan25** [comment]
Same problem here, it is very slow, mostly during night (japan time)

**Comment by AgentThirteen** [comment]
Thanks for the quick replies everyone. I've tried on the browser and the pages either won't load at all (blank) or pictures display very slowly. Browser networking and pinging as previously said show unusual latency from pximg.net (around 4-5 minutes); pings have a >50% packet loss while pinging fanbox.cc gives 0% packet loss, for n=100 tries.

If it's only for certain people, it's odd, though. 100% sure ISP didn't do anything and it happened just after fanbox.cc completed the migration. Maybe something to do with redirects.

**Comment by Nandaka** [comment]
ping is around 100ms, I guess the routing is not yet updated on your ISP?
![image](https://user-images.githubusercontent.com/836867/80665287-9cb01100-8acb-11ea-8a2e-b4662b62a027.png)

**Comment by AgentThirteen** [comment]
Thank you for testing and reporting back Nandaka. I am quite puzzled here.

Flushing DNS caches is the first thing I have tried though I have not tried things like a VPN. I have tested again today starting with a browser, site is initially smooth then immediately starts to slow down as soon as there is some activity.

Command-line ping returns 300-400ms and >30% packet loss for both pximg.net and fanbox.cc, again over n=100 tries with packet loss rate gradually increasing as more tries happen. What's also interesting is it starts kicking in as soon as something is downloaded, making it almost impossible to even connect to a page after a while. It also only happens with pixiv.

As you said it could just be ISP routing issues after the domain change but I am not quite sure yet.

I will have to keep monitoring this and report back on this matter, thank you for the monitor tag. No warnings have been issued from pixiv administration either by mail or on the site. The timing is too odd to be a coincidence really.

**Comment by Nandaka** [comment]
can you try to use https proxy if vpn is not possible? off course, you can also try on different pc?

**Comment by AgentThirteen** [comment]
You might just have been right on the money... This is mystifying as packet loss still was drastic like 50 minutes ago and there had been zero activity from me since the last time I have posted. It was even getting worse without touching anything.

I have just pinged `pximg.net` and `fanbox.cc` at a very different time than usual (11:00 PM UTC). Latency is back to the usual value and more importantly no loss at all over 100 tries which is the ideal ping scenario and download speed has consistently hit the usual average, even faster, for the sample 200 pictures used. Traceroute still is a bit quirky for both so I am keeping this open in case there are some kind of traffic hours causing a huge packet loss at certain times (as Azunyan25 suggested).

I will try another set of hours later just to make sure before closing this issue. Thank you again.

**Comment by AgentThirteen** [comment]
Yeah Azunyan25 seems to be right. I cannot close this yet unfortunately.

10 hours later, latency doubles, site nearly unbrowsable, ping results show ~20% packet loss and download rates and integrity are catastrophic again. Either some special download hours (premium users might not be affected) or servers are completely overloaded at certain times. I did not record the server IPs before the transition but what I am 100% sure of is that it started to happen right after the migration.

If other people experience significant slowdowns (speed going down to 1KB/s or even cancelling completely), please give feedback as well. Since this only happens to pixiv and regardless of account, IP or ISP, it will probably happen to at least one more user. Thanks.

**Comment by Nandaka** [comment]
>>  IP or ISP, 

only for specific IP/ISP, not all.

**Comment by Azunyan25** [comment]
No problem all the day, and became super laggy right now, there is definitely someting on their end. Perhaps they are limitting the traffic on the server, I have no problem with that, but at this rate, this is completely unusable.

**Comment by Nandaka** [comment]
Then you should ask for pixiv official support? considering this is happens on the server level. I cannot do anything here.

**Comment by Azunyan25** [comment]
I just answer the topic, I know you cannot do anything about that. The topic was created by AgentThirteen to see if there are other people with the same problem and to find if this something that happens client side or not.
I have already contacted pixiv support but I do not expect a lot since their customer support is shit. It happens on booth too, which is the pixiv online shop.
What is strange though is that you do not seem to encounter the problem. Are they limiting some specific range of ip only? I hope no. Btw a japanese vpn do not fix it so not sure about that.

**Comment by Nandaka** [comment]
hmm, I'm not sure. I tried to ping it again and it still return me around 100ms.

**Comment by AgentThirteen** [comment]
Sorry for the lack of feedback, testing and monitoring continued but did not manage to get back in time. Conducted results included casual browsing (one picture every now and then) for a full 24 hours. Site was nearly unusable for the entire time and all related domains returned highly abnormal pings and traces - until again around 11:00 PM UTC and up to around 5:00 AM UTC, which seems to be different between users (giving UTC to make sure timezones don't affect the results). This does not resemble an IP block and is not an account block either, but either throttling, server overload (not sure how many they have, and pixiv usage has become ridiculously high) or random limitations to prevent said overload when something unusual shows up.

If you are going to check latency, how much packet loss do you get over n=100 tries (default ping command n is 4 over Windows) regardless of actual latency? If you get a full 100 success, presumably all is well, but >20% packet loss is not normal at all in my humble opinion.

Latency has always been around 200ms when normal here, and now is around 350ms when overloaded (90% of the time) with on-site responses reaching nearly 5 minutes or timing out. Packet loss is 0% when all is well and between 20-35% when overloaded.

The CloudFlare server(s) used by pixiv always give 10-15ms here without any packet loss on a full 100 ping along with a perfect 8-hop trace even during server overload. This is the one thing that's bugging me the most here, latency doesn't mean much but unless CloudFlare CDN doesn't distribute the pictures even during a partial or suspected server outage (unlikely, it has popped up repeatedly at the same insanely low speeds during the casual tests) this is weird.

Thank you both, especially Azunyan, for the feedback. I'm also aware if it's on pixiv's end Nandaka cannot do anything about it (which is likely since it affects all pixiv-related domains, even their booth service, and outside of the script itself) but I still suspect something might have triggered it.

I have tried another device using another DNS just in case as Nandaka suggested. If it's purely on their end, there is nothing to do but wait but this is honestly getting suspicious if only a handful of users are hit, especially if you did not do anything out of the ordinary (see past issues about account suspensions - it's possible the monitoring is now closer to a shadow ban for stealthy bandwidth control especially if some users managed to get around full bans and increased their malicious activities afterwards which defeats the purpose of a suspension warning and a ban).

I have also tried different VPNs from different regions as well as full proxies over SSL - to no avail, different results but same exact connectivity issues.

In addition, a message has been sent to pixiv administration in Japanese from my main pixiv account which is from the legacy pixiv era and has never touched pixivutil in any way.

Waiting for an answer from pixiv. I will keep you informed if I get any just so we are sure pixivutil itself is not getting randomly flagged but I am not getting my hopes up either, I have had a bad experience with pixiv support as well, even natively.

Many apologies for the very long comment.

**Comment by Nandaka** [comment]
From Singapore, around 11.23pm
```
Ping statistics for 210.140.92.141:
    Packets: Sent = 100, Received = 100, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 84ms, Maximum = 127ms, Average = 91ms
```
[result.txt](https://github.com/Nandaka/PixivUtil2/files/4570851/result.txt)

**Comment by AgentThirteen** [comment]
Really odd. Thanks for the attached log Nandaka.

One thing that also comes to mind and that I did not notice is I have never obtained a new OAuth `refresh_token` in `config.ini` (field remained blank after transitioning from `v20200226-beta1` 7ba4e38) while trying out the latest releases. I don't think this is related since I can log in just fine to both pixiv and fanbox from pixivutil (only browsing and downloading work incorrectly) and don't get any OAuth token error but I am not sure whether this outcome is expected...

The previous `config.ini` file still had a valid authentication set (username, password, single cookie for both pixiv and fanbox and a refresh_token) but logging out and then back in with the previous version obviously caused some confusion for the script, even with fresh cookies, as the cookie structure had changed again and could not be merged back, forcing the transition to a newer version with separate cookies.

I don't think this will help either but here's what keeps popping up most of the time in the console while trying to download even a single work. The given time is UTC.

```
2020-05-03 19:37:57,484
NoneType: None

Error at download_image(): (<class 'PixivException.PixivException'>, PixivException('Incomplete Downloaded for *'), <traceback object at 0x00000232CC35D780>) at * (9000)
Traceback (most recent call last):
  File "pixivutil2.py", line 233, in download_image
    raise PixivException("Incomplete Downloaded for {0}".format(url), PixivException.DOWNLOAD_FAILED_OTHER)
PixivException.PixivException: 9000 Incomplete Downloaded *

Traceback (most recent call last):
  File "pixivutil2.py", line 225, in download_image
    (downloadedSize, filename_save) = perform_download(url, remote_file_size, filename_save, overwrite, referer)
  File "pixivutil2.py", line 346, in perform_download
    (downloadedSize, filename) = PixivHelper.download_image(url, filename, res, file_size, overwrite)
  File "*\PixivHelper.py", line 602, in download_image
    save.write(res.read(PixivConstant.BUFFER_SIZE))
  File "*\lib\site-packages\mechanize\_response.py", line 204, in read
    data = self.wrapped.read(to_read)
  File "*\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "*\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "*\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "*\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "*\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
Error at download_image(): (<class 'socket.timeout'>, timeout('The read operation timed out'), <traceback object at 0x000002219846F540>) * (9001)
```
Usual timeout message so not very helpful.

Maybe this on the other hand. I tested a single work, 17 pictures, without prior activity...
Suspicious speeds are marked with an arrow.
```
Mode : manga
Page Count : 17
Image URL : https://i.pximg.net/img-original/img/*.jpg
Filename  : *_p0.jpg
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/artworks/*
Remote filesize = 168.25 KiB (172286 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/artworks/*
[||||||||||||||||||||] 168.25 KiB of 168.25 KiB
 Completed in 11.216378s (15.00 KiB/s) <--
 done.

Image URL : https://i.pximg.net/img-original/img/*_p1.jpg
Filename  : *_p1.jpg
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/artworks/*
Remote filesize = 127.26 KiB (130314 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/artworks/*
[||||||||||||||||||||] 127.26 KiB of 127.26 KiB
 Completed in 22.852181s (5.57 KiB/s) <--
 done.

Image URL : https://i.pximg.net/img-original/img/*_p2.jpg
Filename  : *_p2.jpg
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/artworks/*
Remote filesize = 177.68 KiB (181947 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/artworks/*
[||||||||||||||||||||] 177.68 KiB of 177.68 KiB
 Completed in 1.427135s (124.50 KiB/s)
 done.

Image URL : https://i.pximg.net/img-original/img/*_p3.jpg
Filename  : *_p3.jpg
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/artworks/*
Remote filesize = 190.47 KiB (195041 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/artworks/*
[||||||||||||||||||||] 190.47 KiB of 190.47 KiB
 Completed in 0.786968s (242.03 KiB/s)
 done.

Image URL : https://i.pximg.net/img-original/img/*_p4.jpg
Filename  : *_p4.jpg
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/artworks/*
Remote filesize = 184.02 KiB (188434 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/artworks/*
[||||||||||||||||||||] 184.02 KiB of 184.02 KiB
 Completed in 0.762359s (241.38 KiB/s)
 done.

Image URL : https://i.pximg.net/img-original/img/*_p5.jpg
Filename  : *_p5.jpg
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/artworks/*
Remote filesize = 182.81 KiB (187196 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/artworks/*
[||||||||||||||||||||] 182.81 KiB of 182.81 KiB
 Completed in 0.774697s (235.97 KiB/s)
 done.

Image URL : https://i.pximg.net/img-original/img/*_p6.jpg
Filename  : *_p6.jpg
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/artworks/*
Remote filesize = 161.74 KiB (165625 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/artworks/*
[||||||||||||||||||||] 161.74 KiB of 161.74 KiB
 Completed in 47.44976s (3.41 KiB/s) <--
 done.

Image URL : https://i.pximg.net/img-original/img/*_p7.jpg
Filename  : *_p7.jpg
Checking local filename... Getting remote filesize...
Using Referer: https://www.pixiv.net/artworks/*
Remote filesize = 163.49 KiB (167412 Bytes)
Start downloading... Using Referer: https://www.pixiv.net/artworks/*
Downloaded file incomplete!      8192 of    167412 Bytes
Filename = *_p7.jpg
URL      = https://i.pximg.net/img-original/img/*_p7.jpg
Traceback (most recent call last):
  File "pixivutil2.py", line 225, in download_image
    (downloadedSize, filename_save) = perform_download(url, remote_file_size, filename_save, overwrite, referer)
  File "pixivutil2.py", line 346, in perform_download
    (downloadedSize, filename) = PixivHelper.download_image(url, filename, res, file_size, overwrite)
  File "*\PixivHelper.py", line 602, in download_image
    save.write(res.read(PixivConstant.BUFFER_SIZE))
  File "*\lib\site-packages\mechanize\_response.py", line 204, in read
    data = self.wrapped.read(to_read)
  File "*\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "*\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "*\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "*\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "*\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
Error at download_image(): (<class 'socket.timeout'>, timeout('The read operation timed out'), <traceback object at 0x000001C34B37A4C0>)
```

**Comment by Nandaka** [comment]
not sure if this help: set the `useragent` to match your browser in config.ini.
OAuth only triggered if it needs additional member/artist information.

**Comment by AgentThirteen** [comment]
> OAuth only triggered if it needs additional member/artist information.

Ah I see. Thanks Nandaka so I guess it did not need that so far.

> not sure if this help: set the `useragent` to match your browser in config.ini.

Hmm I have always been using the default `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36`.
Changing it to match a specific browser doesn't seem to help but that was worth a try.
Thank you for the idea.

**Comment by AgentThirteen** [comment]
No mail reply received but everything is suspiciously back to normal right now. For now... And for how long...

I am still trying to pinpoint whatever might have caused this for @Azunyan25 and myself and whether it is (or was, if it's over) related to pixivutil at all. If servers truly were overloaded, more people would be affected and there would still be low-activity hours... This doesn't add up.

Thank you very much for the help and feedback so far in any case everyone.

**Comment by Azunyan25** [comment]
Yes looks much better now. I have grabbed a lot of artists this night and the previous night and did not get any latency nor any corrupted files.
Hope it stays like this, wait and see ^^

**Comment by AgentThirteen** [comment]
No reply from pixiv administration after a month but I guess they got the message that their servers were being overloaded, download speeds are reasonable now and no issues ever since. Feel free to close whenever you have time unless someone still has issues with this one. Thanks again to everyone who participated in trying to pinpoint the issue here.
