### ISSUE TITLE
Cannot download from fanbox anymore with new beta version

### ISSUE THREAD

**Issue by Azunyan25** [Nandaka/PixivUtil2#687]
Hello there and thank you for your hard work on pixiv util,

Using the lastest version of pixiv util: pixivutil20200428-beta1,

I have a problem that was not there before, if I try to grab a fanbox I am currently supporting (using f2 > artist id ), I get the following message for every post:

"skipping post: [post number] due to restricted post"

I can clearly see those posts and the pics in my browser.

Do you know anything about that? It is working with previous version.

Thank you for your help.

**Comment by Shagiakhmetov** [comment]
Good afternoon.

Maybe your authorization failed?
Check console messages when you first start PixivDownloader. Are there the following lines?

```
Trying to log in FANBOX with saved cookie
Login successful.
```

If not, then check if you have correctly specified **cookiefanbox** for FanBox in _config.ini_

My download from FanBox works fine both in the "f1" mode and in the "f2" mode, and in the "f4" mode.

The problem is only with the "f3" mode:

```
Input: f3
Post ids = 986608
Traceback (most recent call last):
  File "PixivUtil2.py", line 2524, in main
  File "PixivUtil2.py", line 2256, in main_loop
  File "PixivUtil2.py", line 1964, in menu_fanbox_download_by_post_id
  File "PixivBrowserFactory.pyc", line 881, in fanboxGetPost
AttributeError: 'NoneType' object has no attribute 'creatorId'
press enter to exit.
```

**Comment by Nandaka** [comment]
@Shagiakhmetov try latest release https://github.com/Nandaka/PixivUtil2/releases/ for f3 issue.

**Comment by Azunyan25** [comment]
> Good afternoon.
> 
> Maybe your authorization failed?
> Check console messages when you first start PixivDownloader. Are there the following lines?
> 
> ```
> Trying to log in FANBOX with saved cookie
> Login successful.
> ```
> 
> If not, then check if you have correctly specified **cookiefanbox** for FanBox in _config.ini_
> 
> My download from FanBox works fine both in the "f1" mode and in the "f2" mode, and in the "f4" mode.
> 
> The problem is only with the "f3" mode:
> 
> ```
> Input: f3
> Post ids = 986608
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 2524, in main
>   File "PixivUtil2.py", line 2256, in main_loop
>   File "PixivUtil2.py", line 1964, in menu_fanbox_download_by_post_id
>   File "PixivBrowserFactory.pyc", line 881, in fanboxGetPost
> AttributeError: 'NoneType' object has no attribute 'creatorId'
> press enter to exit.
> ```
Thank you mate, worked by setting the pixivfanbox parameter, I did not now about that since it was not in the readme.
