### ISSUE TITLE
It won't even open

### ISSUE THREAD

**Issue by i-am-allergic-to-code-pls-bare-with-me** [Nandaka/PixivUtil2#691]
I'm trying to follow this tutorial on how to use your programme but to no avail https://www.youtube.com/watch?v=tT3c1RuEK9o

Once I extracted the .rar file and clicked PixivUtil2, I noticed that its a .py file so I downloaded Python and restarted my PC. The thing refuses to open, as all what I see is a black tab that disappears as soon as it appears. There is nothing about this on the FAQ. I checked the 'requirements' file, and googled the names, and I have no clue what I am even supposed to be doing. I meet the requirements for the readme file, but I don't know what to do with FFmpeg, another thing I ended up downloading.

Sorry if I sound dumb, I really don't know anything about code.

**Comment by bluerthanever** [comment]
Is it compiled file (the zip file in release page) that you are using or the `.py` files?
If it's the former, you don't need to install python, just run the `.exe` file.

And what version are you using? And did you setup the `config.ini` file?

Can you please run the file in command window if you are using Windows, and please check the error information?

**Comment by Nandaka** [comment]
also, get the latest releases here: https://github.com/Nandaka/PixivUtil2/releases

I don't think I uses .rar for quite some time.

**Comment by i-am-allergic-to-code-pls-bare-with-me** [comment]
> 
> 
> Is it compiled file (the zip file in release page) that you are using or the `.py` files?
> If it's the former, you don't need to install python, just run the `.exe` file.
> 
> And what version are you using? And did you setup the `config.ini` file?
> 
> Can you please run the file in command window if you are using Windows, and please check the error information?

I downloaded the .zip file. When I opened it, there were .py files. In case if you want to know, I did try to open these files without Python installed, but I still suffered the same result.

I am using the newest version of Python (3.8). Well, I couldn't find any information on a config.ini file. I don't even know how to set that up.

What do you mean by 'file command' exactly? I'm guessing I run the file location on the command prompt? 
![image](https://user-images.githubusercontent.com/64588361/80720026-3c819500-8af4-11ea-8123-6806ad5ffad0.png)

I am using Windows 10.

**Comment by i-am-allergic-to-code-pls-bare-with-me** [comment]
> 
> 
> also, get the latest releases here: https://github.com/Nandaka/PixivUtil2/releases
> 
> I don't think I uses .rar for quite some time.

I downloaded it through the link and I still have the same problem, and it is downloaded as a .rar file. So I should install something like 7zip?

**Comment by bluerthanever** [comment]
I think what you downloaded was the Py files, not the compiled ones.
If you are running from the codes.... it should be like:
~\PixivUtil2-master>py PixivUtil2.py

If error says you are missing required components, try run:
~\PixivUtil2-master>py -m pip install -r requirements.txt

then do the previous one....

**Comment by i-am-allergic-to-code-pls-bare-with-me** [comment]
Okay, I did what the upload-er did. It turns out that I don't need 7zip and winrar will work just fine. I finally extracted and opened it.

![image](https://user-images.githubusercontent.com/64588361/80722153-f7129700-8af6-11ea-8b3e-000b1c8d0ebd.png)

**Comment by bluerthanever** [comment]
Okay... good to know. =)
