### ISSUE TITLE
Option 11 [Download Member Bookmark] %artist% and %member_id% tokens are incorrect

### ISSUE THREAD

**Issue by puffinkins** [Nandaka/PixivUtil2#693]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When using Option 11, the %artist% and %member_id% tokens belong to the user whose bookmarks you are downloading, not the artist of the image being downloaded.

### Steps to Reproduce

Example user: https://www.pixiv.net/en/users/14592593/bookmarks/artworks

Currently, the first bookmark is https://www.pixiv.net/en/artworks/79324049

1. Use Option 11
2. Input member id 14592593
3. Downloading to directory %artist% (%member_id%)

**Expected behavior:** The directory should be "長部トム (24268651)".

**Actual behavior:** The directory is "EGK513 (14592593)"

### Versions
20200430-beta2

You can get this information from executing `PixivUtil2.py --help`.

**Comment by Nandaka** [comment]
can you test with additional format:
```
-> %bookmark%
   for bookmark mode, add 'Bookmarks' string.
-> %original_member_id%
   for bookmark mode, put original member id.
-> %original_member_token%
   for bookmark mode, put original member token.
-> %original_artist%
   for bookmark mode, put original artist name.
```

might be related: https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L219

**Comment by puffinkins** [comment]
Ah, I see.
I did not know that %original_artist% and %original_member_id% were equivalent to %artist% and %member_id% when not in bookmark mode.
Thanks, that works.
