### ISSUE TITLE
"because it was downloaded before"

### ISSUE THREAD

**Issue by dkdrdd** [Nandaka/PixivUtil2#698]
### Prerequisites

* [ ] Did you read FAQ section?
>> excuse me,wheres the faq section?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

what is "Skipping post"?
how can i disable it?

**Comment by bluerthanever** [comment]
It meant the post was processed before, and that between the last time it was processed and this time, the post is not updated.
There's no way to disable it now, but I am working on it. There will be a switch to turn this off.

**Comment by bluerthanever** [comment]
> the post is not updated.
which I meant, the post has not been changed by the author/creator.

**Comment by dkdrdd** [comment]
ok.
good luck at your work.
