### ISSUE TITLE
fanbox image download delays

### ISSUE THREAD

**Issue by rwchunk** [Nandaka/PixivUtil2#703]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I'm a bit worried about triggering suspensions again.
Does fanbox downloader use the config delay? It doesn't seem like it. I set a 60 second delay and watching it, it seems to proceed too quickly.
And if there is a delay, then making it visible in the output would help just to be sure.

### Steps to Reproduce

set downloaddelay in config

**Expected behavior:** long delay

**Actual behavior:** short delay?

### Versions

20200503-beta1

**Comment by Nandaka** [comment]
I don't think so.
@bluerthanever you can insert `PixivHelper.wait(result, __config__)` after downloading images to add some delays.

**Comment by bluerthanever** [comment]
Okay. I will add it later.
