### ISSUE TITLE
[Feature Request] Novel Support

### ISSUE THREAD

**Issue by HydroHydro** [Nandaka/PixivUtil2#706]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Example link: https://www.pixiv.net/en/users/37371502

Could we get support for downloading novels? Maybe download as an html file or something?

**Comment by Nandaka** [comment]
Hmm, the api doesn't provide the formatting, looks like it just return the chapter content and somehow it does the pagination.

API endpoints:
- Novel list = https://www.pixiv.net/ajax/user/37371502/profile/all?lang=en
- Novel details = https://www.pixiv.net/ajax/user/37371502/profile/novels?ids%5B%5D=12866416&ids%5B%5D=12810909&ids%5B%5D=12782176&ids%5B%5D=12696211&ids%5B%5D=12652161&ids%5B%5D=12632592&ids%5B%5D=12579432&ids%5B%5D=12452356&ids%5B%5D=12426925&ids%5B%5D=12381276&ids%5B%5D=12327928&ids%5B%5D=12271344&ids%5B%5D=12242646&ids%5B%5D=12213475&ids%5B%5D=12171237&ids%5B%5D=12122817&ids%5B%5D=12108505&ids%5B%5D=12096785&ids%5B%5D=12075822&ids%5B%5D=12052461&ids%5B%5D=12027394&ids%5B%5D=11965956&ids%5B%5D=11945319&ids%5B%5D=11913311&lang=en
- Novel chapters = https://www.pixiv.net/ajax/novel/series_content/1245896?limit=10&last_order=0&order_by=asc&lang=en
- Chapter contents = https://www.pixiv.net/ajax/novel/12027394?lang=en

**Comment by Diamond-Frost** [comment]
The App API that's used throughout this has API support either, and it returns HTML-Text (text + <br />) to get the paragraphs

This here is a response from `/v2/novel/detail`
`{'novel': {'id': 9474935, 'title': '〜もしも西片があの消しゴムの反対を見ていたら〜', 'caption': '皆さん、こんばんはー。<br />このシリーズ忘れてたでしょ？実はねー、
俺も忘れとった（笑）それがね、先週の金曜日『あれ？なんかやってないような気がする』って考えたらこのシリーズ出してなかったわ。すんません。本当に俺って投稿日守らない 
よね、本当にすみません。ってなんかまた守らんような気がするけど(（笑）)<br /><br />それとね！それとね！いやまじでね！嬉しいことがあったんよ！広島でね！<br />25時25 
分毎週水曜、RCCでからかい上手の高木さんが始まったんですよ！！いやー！まじでサイコー！ずっーとアニチューブというサイトで見てたから『いつかリアルタイムで見てみたいな
ぁーって』思っててそれが叶ったんですよ！いやほっ！！！これなら、七月まで耐えられるぞ！！よいしょ！！！<br />でも、七月からまたからかい上手の高木さんのない生活が始 
まるんか、、<br />でもでも、皆様の小説を読んで癒していこうと思っております！今後とも皆様よろしくお願いします！！！<br /><br />それとね、名前考えてもらったんだけど 
さ、一部の人は考えてもらったんだけど、５個なかったけ俺も一応考えたわ（笑）<br />そんな訳で宜しくね！皆さん投票よろしくお願いします！！<br /><br />はい、今日も頑張 
って小説を書いたのでよろしくお願いしますー。', 'restrict': 0, 'x_restrict': 0, 'is_original': True, 'image_urls': {'square_medium': 'https://i.pximg.net/c/128x128/novel-cover-master/img/2018/04/12/23/49/33/9474935_a8a1594654f9313de2ef8c8c25dd5337_square1200.jpg', 'medium': 'https://i.pximg.net/c/176x352/novel-cover-master/img/2018/04/12/23/49/33/9474935_a8a1594654f9313de2ef8c8c25dd5337_master1200.jpg', 'large': 'https://i.pximg.net/c/240x480_80/novel-cover-master/img/2018/04/12/23/49/33/9474935_a8a1594654f9313de2ef8c8c25dd5337_master1200.jpg'}, 'create_date': '2018-04-12T23:49:33+09:00', 'tags': [{'name': 'からかい上手の高木さん', 'translated_name': 'Karakai Jōzu no Takagi-san', 'added_by_uploaded_user': True}, {'name': '恋愛', 'translated_name': 'love', 'added_by_uploaded_user': True}, {'name': '高木さ 
ん', 'translated_name': 'Takagi-san', 'added_by_uploaded_user': True}, {'name': '西片', 'translated_name': 'Nishikata', 'added_by_uploaded_user': True}, {'name': 'if', 'translated_name': None, 'added_by_uploaded_user': True}], 'page_count': 1, 'text_length': 6379, 'user': {'id': 30244223, 'name': 'さんとむ', 'account': 'user_prtj8822', 'profile_image_urls': {'medium': 'https://i.pximg.net/user-profile/img/2018/03/01/19/40/25/13895995_ae8eab856992ad10f0e8344f27ca86ea_170.png'}, 'is_followed': False}, 'series': {'id': 947978, 'title': 'もしも○○が高木さんと西片くんだったら'}, 'is_bookmarked': False, 'total_bookmarks': 146, 'total_view': 3736, 'visible': True, 'total_comments': 4, 'is_muted': False, 'is_mypixiv_only': False, 'is_x_restricted': False}}`

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20210215-beta1

**Comment by HydroHydro** [comment]
Doesn't work. I'm logged in and able to download pictures normally, but novels do not work. This is the error I get:

> Member IDs: ['37371502']
Processing Member Id: 37371502
Page
Member Url: https://www.pixiv.net/ajax/user/37371502/profile/all
Using OAuth to retrieve member info for: 37371502
Invalid grant_type parameter or parameter missing
Member ID (37371502): 0 Failed to login using OAuth, follow instruction in https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362 to get the refresh token., hasDumpPage=N, pageData=None

**Comment by Nandaka** [comment]
Please read the error message and follow the instruction to update the oAuth token.

**Comment by HydroHydro** [comment]
Where is pixiv_auth.py?

**Comment by Nandaka** [comment]
scroll a bit.... ensure you read the instruction given in the article.
![image](https://user-images.githubusercontent.com/836867/112707929-e1197c00-8ee9-11eb-8fe5-f3d7d791326f.png)

**Comment by HydroHydro** [comment]
I followed the guide and now I get this when trying to login with PixivUtil:

> Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x4374418 whose wrapped object = <HTTPError 302: 'The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nFound'>>, <traceback object at 0x0437BAA8>)
Cannot Login!

I put the refresh token in the config file. Not sure what to do with the access token...

**Comment by Nandaka** [comment]
hmm, not sure why as this is the way I get the access. Maybe you also need to update the cookies for the pixiv one?

also related to #914

**Comment by HydroHydro** [comment]
I updated cookies too. That works fine. It's only when I enter the refresh_token that I get that error above.

**Comment by HydroHydro** [comment]
Ok... For some reason, it started working again. But now there's a new problem. PixivUtil gets the bg_folder and folder pictures, but does *not* download the novels...

**Comment by aksskl** [comment]
"novel_template.html" is missing from the latest release. I added it and option 14 works fine now. I might be blind since I can't find an option to download all novels from a member_id. Option 1 only processes images.

**Comment by 524144** [comment]
> "novel_template.html" is missing from the latest release. I added it and option 14 works fine now. I might be blind since I can't find an option to download all novels from a member_id. Option 1 only processes images.
> 
> Also the novel I downloaded had a long description and some of it got chopped off because "max-height" in the template was too low. I set it to 9999px and redownloaded.

I'm having this problem too, how did you add that?

**Comment by Nandaka** [comment]
latest available here: https://raw.githubusercontent.com/Nandaka/PixivUtil2/master/novel_template.html

**Comment by 524144** [comment]
> latest available here: https://raw.githubusercontent.com/Nandaka/PixivUtil2/master/novel_template.html

Thank you! Is working!
