### ISSUE TITLE
Unable to log in with proper cookie or credentials

### ISSUE THREAD

**Issue by tphillip913** [Nandaka/PixivUtil2#712]
### Prerequisites

* [x] Did you read FAQ section?
Yes. This error is not covered.

* [x] Did you test with the latest releases?
I used version 20200503-beta1 and 20200502

### Description
Using proper credentials and updating the cookie value in the config.ini as per the FAQ's instructions I get the following error(s):

Trying to log in with saved cookie
Cookie already expired/invalid.
Logging in...
Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 317, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x077352E8>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x0738DF08>)
Cannot Login!

### Steps to Reproduce

1.  Put in the proper credentials and cookie value in the config.ini (After logging into pixiv.net and having the cookies update)
2. Run the following command: 
Pixivutil2.exe --exitwhendone --startaction=4 .\list

**Expected behavior:** [What you expected to happen]
Process is IDs in list.txt

**Actual behavior:** [What actually happened]
Dies at login with the above error

**Comment by NoneGiven** [comment]
I'm also getting this as of today.

**Comment by Nandaka** [comment]
Weird, it is working on my side. 

Also, the logging point to blank line in the source code: https://github.com/Nandaka/PixivUtil2/blob/8967d76318bea94ef6b2bbc780b519332ec3756c/PixivBrowserFactory.py#L317

**Comment by RoxasShadow** [comment]
Delete your cookie string in the config file and replace with your current PHPSESSID (cfr. https://github.com/Nandaka/PixivUtil2/issues/505).

**Comment by tphillip913** [comment]
Odd. I deleted my cookie string twice and saved he config.ini file and got the above error. After a power outage (And subsequent reboot) I do it again for a third time and it takes.

WTF?

Ok. Either my Windows box doing these pulls is FUBAR or I need Father Karras for a holy ritual. I'll run with the former until the later becomes more apparent. Sigh

**Comment by NoneGiven** [comment]
Still having the same issue. Tried deleting the config, logging in to pixiv in the web browser, and copying over the new cookie.

```
PixivDownloader2 version 20200307
...
Trying to log in with saved cookie
Cookie already expired/invalid.
Logging in...
Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 317, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x0C330368>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x0C068308>)
Cannot Login!
press enter to exit.
```

**Comment by NoneGiven** [comment]
Updated to `20200503-beta1` and now it's working.
