### ISSUE TITLE
[Feature Request] Batch Job Download of Bookmarks

### ISSUE THREAD

**Issue by britefire** [Nandaka/PixivUtil2#713]
### Prerequisites

* [x] Did you read FAQ section?

* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

  At the moment, the new feature to download as a batch from batch_job.json is already fantastic, though seems to lack support for the download via bookmarked images.

  It would be especially useful, if at all possible, at the moment (unless I've missed something), downloading from bookmarks into folders by the user-assigned bookmark tag needs an individual re-run and root directory change for each tag; being able to wrap it all into a batch job for each tag would be fantastic.

  Apologies if this is already on the planning list, even moreso if I'm missing some obvious way to do this with bookmark download mode or filename tags in the utility and making this infinitely more tedious.

**Comment by Nandaka** [comment]
which bookmark option that you want? got option 5/6/8/11. 😛

**Comment by britefire** [comment]
Ah, my apologies, was quite tired when writing that up.
Specifically option 6 from the startup.

At the moment, unless I'v remissed something, there's not a way to include the searched bookmark tag in a filename via % command in the configuration file.
I've just been reassigning the root download directory for each tag to force them to download into a folder with the same name as the tag; not exactly efficient but it's worked best so far for downloading thousands of images across 30-40 tags.

If there were batch job options for operation 6, it could be easy to write up a .json file to have it run in a batch with config overrides so each iteration dowloads to a separate folder.

**Comment by Nandaka** [comment]
So you want to add the search_tag to the filename for option 6?

**Comment by britefire** [comment]
I feel like if I'd thought of that, it would've been much less roundabout to simply suggest as such, my apologies. >.<

Basically yeah.

**Comment by Nandaka** [comment]
updated on the latest release, please check.

**Comment by britefire** [comment]
After attempting a download, using %search_tag% as a format option simply includes the line of text %search_tag% in the file or directory name, as am example:
The config of: 
`filenameformat = %search_tag%\(%member_id%) - %urlFilename% - %title%`
Results in the file being saved as:
`%search_tag%\(4056694) - 75165137_p0 - RKGK.Arknights.jpg`

The same kind of results happen as part of the filename itself as opposed to trying to use it to create a directory.

**Comment by Nandaka** [comment]
weird, do you enter the tag to search when you it ask for the tag?

```
Input: 6
Include Private bookmarks [y/n/o]: y
Tag (press enter for all images): **bikini**
Start Page (default=1):
End Page (default=0, 0 for no limit):
Importing image bookmarks...
Importing user's bookmarked image from page 1
...
Filename  : D:\Temp\Pixiv2\bikini\13557 setunasamidare\R-18 21005736_p0 - オリジナル28　アイスはいかが？.png
```

**Comment by britefire** [comment]
Well, I feel stupid, my mistake.
It's `%searchTags%`, not `%search_tag%`, I should've checked the info more closely.
It now is properly making the folders, even working fine with not only standard Alphanumeric, but even unicode Japanese characters pasted as tags.

Everything seems to work perfectly now, thank you so much!
