### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by GenderOffender** [Nandaka/PixivUtil2#714]
### Prerequisites

 Did you read FAQ section? Yes

 Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? Yes

### Description

I cannot login despite having valid user credentials and cookie.

### Steps to Reproduce

1. I entered my credentials and cookie into config.ini.
2. I opened PixivUtil2.exe.
3. The login failed and the message "Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x612e4a8 whose wrapped object = <HTTPError 302: 'The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nFound'>>, <traceback object at 0x0612CCA8>)
Cannot Login!" appeared.

**Expected behavior:** The program would login to Pixiv.

**Actual behavior:** The login failed.

### Versions
pixivutil20200502

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
try beta? https://github.com/Nandaka/PixivUtil2/releases

**Comment by GenderOffender** [comment]
> try beta? https://github.com/Nandaka/PixivUtil2/releases

It didn't work.

**Comment by bluerthanever** [comment]
looks like your cookie might not be valid?
error happens at doLogin, which I think means, loginwithcookie returned False.
and this tool doesn't do actual logins as in browses, currently.

**Comment by bluerthanever** [comment]
Can you update the cookie string and try again? Please make sure that the cookie string is from a valid login in a browser.

**Comment by GenderOffender** [comment]
> Can you update the cookie string and try again? Please make sure that the cookie string is from a valid login in a browser.

It worked.
