### ISSUE TITLE
unable to generate refresh token

### ISSUE THREAD

**Issue by Ksdpm** [Nandaka/PixivUtil2#717]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

no refresh token is generated

### Steps to Reproduce

1. fill in all the details in config.ini
2. run
3. wait

**Expected behavior:** automatic generation of refresh token

**Actual behavior:** blank

### Versions pixivutil20200524

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

Tried the method suggested earlier where I change my useragent to match my broswer i.e. Chrome/81.0.4044.138 bu this is still not solving the issue

**Comment by bluerthanever** [comment]
I think I've seen a similar issue before.
The answer was pretty much like: if refresh token is not required for the actions you use, then it would not be obtained.

Do you have any problem downloading anything?

**Comment by Ksdpm** [comment]
I am trying to download from my supported artist on Fanbox.
Without the refresh token, I just receive the OAuth failed message.

**Comment by bluerthanever** [comment]
If the tool fails to obtain the token when it's needed, there should be error messages?
Do you mind post them?

**Comment by Ksdpm** [comment]
Hi, sure, here is what's happening:

Trying to log in FANBOX with saved cookie
FANBOX Login successful.
Getting supported artists from https://api.fanbox.cc/plan.listSupporting
Found 5 supported artist(s)
###
displaying supported artist
###
Using OAuth to retrieve member info for: 1657441
103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。
Failed to login using OAuth
press enter to exit.

**Comment by bluerthanever** [comment]
https://github.com/Nandaka/PixivUtil2/issues/631
Might be similar to this one?
What do you have in your config for `username` and `password`? Are they empty or dummies? If so, can you try filling them with your account and password?
If not, and you are using "username" username or "email" username, can you try switching to the other one and try again?

**Comment by Ksdpm** [comment]
Hi,

I have actually tried the method you linked and it used to work, up till fanbox changed their address. This has only become a problem since the change by fanbox.

**Comment by bluerthanever** [comment]
Hmm. I have no problem with using fanbox though so far...
Just tried deleting the token from my config and download from fanbox, it had no problem retrieving refresh token at all.
Do you mind generate a new log file and post it?

(BTW, you didn't delete the artist number in one of your previous posts.)

**Comment by Nandaka** [comment]
Try to use your email address for the username? the error message state something about email/password is not correct.
