### ISSUE TITLE
option 6 does not work.

### ISSUE THREAD

**Issue by sos4848** [Nandaka/PixivUtil2#719]
### Prerequisites

* [v ] Did you read FAQ section?
* [v] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
input : 6
2. [Second Step]
input : y
input : 1
input : 0

3. [and so on...]
i'm logged into Pixiv. 
I entered my cookie in config. 
Other options work fine.

**Expected behavior:** [What you expected to happen]
download bookmarked images

**Actual behavior:** [What actually happened]
Include Private bookmarks [y/n/o]: y
Tag (default=All Images): default
Start Page (default=1): 1
End Page (default=0, 0 for no limit): 0
Importing image bookmarks...
Importing user's bookmarked image from page 1
Source URL: https://www.pixiv.net/ajax/user/54823124/illusts/bookmarks?tag=default&offset=0&limit=48&rest=show
No more images.
Importing user's bookmarked image from page 1
Source URL: https://www.pixiv.net/ajax/user/54823124/illusts/bookmarks?tag=default&offset=0&limit=48&rest=hide
No more images.
Found 0 image(s).
Done.

### Versions 
20200524

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
set the Tag to empty string to get all images... (just press enter).
