### ISSUE TITLE
No images found

### ISSUE THREAD

**Issue by xxsu2543** [Nandaka/PixivUtil2#720]
### Prerequisites

* [ y] Did you read FAQ section?
* [y ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]
No images found for member id specified.

### Steps to Reproduce

1. Sign in successfully with details in config.ini
2. input: 1
3. Member ids: 6662895
4. Start Page (default=1): 1
5. End Page (default=0, 0 for no limit): 0

**Expected behavior:** [What you expected to happen]
Download all images from member id specified

**Actual behavior:** [What actually happened]
Processing images from 1 to 137 of 137
No image found for: 6662895
Member id: 6662895 completed: no images were found

### Versions
version 20200524

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
is your r18mode set to True in config.ini?

**Comment by xxsu2543** [comment]
Yes, I set my r18mode to True in the config.ini file.

**Comment by Nandaka** [comment]
r18mode only download images tagged with R-18 in it, that artist doesn't have any images with R-18 tag. Set to False to download all images.

**Comment by xxsu2543** [comment]
Oh that makes sense. I thought that r18mode would download all images including the non R-18 ones. Thanks for the help!
