### ISSUE TITLE
Can't open the program at all, no config file was generated to edit too.

### ISSUE THREAD

**Issue by kennysly** [Nandaka/PixivUtil2#721]
### Prerequisites

* [Yes ] Did you read FAQ section? 
* [Yes ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Can't open the program]

### Steps to Reproduce

1. Extract the zip file
2. Try to open the program
3. But it's keep quit by itself, and no config file to edit or try to login.

**Expected behavior:** [Try to enter my username and password like usual, or edit cookie in config file]

**Actual behavior:** [Cannot continue]

### Versions pixivutil20200524

[bandicam 2020-06-07 12-13-20-309.zip](https://github.com/Nandaka/PixivUtil2/files/4741396/bandicam.2020-06-07.12-13-20-309.zip)

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

Hi, I just download the latest version, but I couldn't open the program at all, and no config file generated. I try the old version, it's just works fine.

When double click the program, it's shows a black box with some coding, then closed by itself. Repeatedly when I click the program again. Last time the version I use is pixivutil20190606, but also cannot login now.

I attach a video as zip and pictures below.
[bandicam 2020-06-07 12-13-20-309.zip](https://github.com/Nandaka/PixivUtil2/files/4741400/bandicam.2020-06-07.12-13-20-309.zip)

I check FAQ already, but seems like nobody have similar problem with me. Hope somebody can help with this, thank you.
![001](https://user-images.githubusercontent.com/66544057/83960411-21f0c780-a8bb-11ea-9fd9-9ec7d293e341.PNG)
![002](https://user-images.githubusercontent.com/66544057/83960412-25844e80-a8bb-11ea-9fa1-6fc4501ee489.PNG)
![003](https://user-images.githubusercontent.com/66544057/83960413-25844e80-a8bb-11ea-811a-555c251b6139.PNG)

**Comment by Nandaka** [comment]
The new version is using python 3.8.x as the old one is running python 2.7.x which not supported anymore.
Try to do clean install (extract to new folder) and reconfigure?

**Comment by kennysly** [comment]
> The new version is using python 3.8.x as the old one is running python 2.7.x which not supported anymore.
> Try to do clean install (extract to new folder) and reconfigure?

Hi, I try extract to a new folder but still not working, black box came out then gone. Could it be my computer's problem?

**Comment by Nandaka** [comment]
hmm, if that the case, maybe you can try to run from source code instead?
You can follow this step: https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

**Comment by kennysly** [comment]
Thank you, but I can't install Python-3.8.3, maybe my computer system outdated? 
OS using: Windows 7 Service Pack 1 64bit
![001](https://user-images.githubusercontent.com/66544057/84111138-dc6a0100-aa58-11ea-8653-a129e5703c25.PNG)
![002](https://user-images.githubusercontent.com/66544057/84111144-decc5b00-aa58-11ea-9e40-98b47757136c.PNG)


I try open the program by command prompt, get this message.
![003](https://user-images.githubusercontent.com/66544057/84111153-e25fe200-aa58-11ea-9c7c-0842fb2bdf3f.PNG)



Maybe I try on another Windows 10 PC? Anything I let you know again.

Thank you Nandaka.

**Comment by Nandaka** [comment]
got it, I will update the readme too for the minimum system requriements.
