### ISSUE TITLE
Got error when downloading images, pixiv fanbox

### ISSUE THREAD

**Issue by bismarck1815** [Nandaka/PixivUtil2#722]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

error 
Getting posts from https://api.fanbox.cc/post.listCreator?creatorId=gweda&maxPublishedDatetime=2019-11-23%2018%3A34%3A43&maxId=671879&limit=10
Traceback (most recent call last):
  File "PixivUtil2.py", line 1618, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
  File "PixivUtil2.py", line 1359, in main_loop
    menu_fanbox_download_from_artist(op_is_valid, PixivModelFanbox.FanboxArtist.SUPPORTED, args)
  File "PixivUtil2.py", line 1032, in menu_fanbox_download_from_artist
    processFanboxArtist(artist, end_page)
  File "PixivUtil2.py", line 1062, in processFanboxArtist
    posts = __br__.fanboxGetPostsFromArtist(artist, next_url)
  File "PixivBrowserFactory.pyc", line 913, in fanboxGetPostsFromArtist
  File "PixivModelFanbox.pyc", line 82, in parsePosts
  File "PixivModelFanbox.pyc", line 141, in __init__
  File "PixivModelFanbox.pyc", line 249, in parseBody
KeyError: 'qSqOhrGWm6l4fqEVobiaYnlu'

### Steps to Reproduce

1. Use exe build, win 10.
2. Pixiv fanbox, used f1, f2 menus.
3. everything is okay before 13pages, but error occurs on 13page.

### Versions

lastest 2020, 05, 24

**Comment by bismarck1815** [comment]
ADD ) I think problem on getting name, A*(/)*B no space between /

**Comment by bismarck1815** [comment]
https://www.fanbox.cc/@gweda/posts/663320 this thread

**Comment by bluerthanever** [comment]
Hi, there. The error is kinda weird, and I don't think there would be any logs to look into for that.
So do you mind opening in browser the link below and copying then pasting the result or uploading the result as a text file?
https://api.fanbox.cc/post.info?postId=663320

**Comment by bluerthanever** [comment]
Sorry, my bad. I think there would be logs but I am not sure there would be the json string that I want to look for in them...

**Comment by bismarck1815** [comment]
I cannot understand how to read my log files, and your codes, I'm short python user, so I leave all of my logs file.

if you want to another things, please leave MSG, I'll provide. 

have a nice day, and thank you. 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4745404/pixivutil.log)

PS. I tested both system, one is builed exe file,and other is py 3.8 system.
same version of 200524, and.. same result. -same error.

**Comment by bluerthanever** [comment]
Wow. There IS what I needed in the log...
I will have a look.
Thank you

**Comment by bluerthanever** [comment]
How many pictures can you see in the post, in the browser?
According to the log there should be 2, but only 1 is actually valid?
Also, can you please tell me whether you are able to access the link below?
https://downloads.fanbox.cc/files/post/663320/qSqOhrGWm6l4fqEVobiaYnlu.jpeg

**Comment by bismarck1815** [comment]
I cannot access https://downloads.fanbox.cc/files/post/663320/qSqOhrGWm6l4fqEVobiaYnlu.jpeg and https://api.fanbox.cc/post.info?postId=663320 both.

**Comment by bismarck1815** [comment]
and all of pictures in that thread, are not downloaded. in the download folder, I think stuck on loading thread's header or something,

**Comment by bluerthanever** [comment]
Ah... sorry, the first link was not supposed to be accessible from browser....
But how many images/files can you see in the post in browser then?

**Comment by bismarck1815** [comment]
you mean, how many images on that thread, https://www.fanbox.cc/@gweda/posts/663320 in browser? I can fully access and can see the post. only 1 image on that thread. 

and https://downloads.fanbox.cc/files/post/663320/qSqOhrGWm6l4fqEVobiaYnlu.jpeg 404 error

**Comment by bluerthanever** [comment]
Okay... Thank you.
I think maybe something went wrong on fanbox side, because json retreived from them indicates that there are 2 files/images, but there is only one that is given the location to the file.
I will pull a request.

**Comment by bismarck1815** [comment]
oh... okay. I'll find more, thank you
