### ISSUE TITLE
Pixivutil waiting for tag when using a member id list

### ISSUE THREAD

**Issue by tphillip913** [Nandaka/PixivUtil2#725]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest release?

### Description
When downloading from list.txt containing only member IDs the command line waits for manual input for a tag. This stops programmatic running and manual running requires at least a return to continue

### Steps to Reproduce
1 - Put the following in the config.ini
downloadlistdirectory = c:\robosoftware\pixivconfig
uselist = True
processfromdb = False
rootdirectory = c:\robosoftware\pixivartists

2- Run the following command: c:\robosoftware\pixivutil20200524\pixivutil2.exe --exitwhendone --startaction=4

**Expected behavior:**
To process the list of member ids w/o pause

**Actual behavior:**
The member list is read and then pixivutil2 waits for a tag via manual input

Sample output:

PixivDownloader2 version 20200524
https://github.com/Nandaka/Pixivutil20200524/releases
Donate at https://bit.ly/PixivUtilDonation
Reading C:\RoboSoftware\pixivutil20200524\config.ini ...
done.
Using custom DB Path: C:\RoboSoftware\PixivConfig\db.sqlite
Creatiung database... done.
Importing list... Found 133 items done.
Updated 133 items.
Using Username: --redacted--
Trying to log in with saved cookie
Login successful.
My User Id: --redacted--.
Premium User: False.
Tag: <blinking cursor waiting for input>

### Versions
Using 20200524

**Comment by Nandaka** [comment]
woops, readme is wrong, the path to the list is required.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L809

**Comment by tphillip913** [comment]
That was the trick. An absolute path and the filename to the list file and all works.

But then that leaves a question: If I have to specify the path and file name for the list, then what is the downloadlistdirectory path used for if I use the default filename for the list?

**Comment by Nandaka** [comment]
if you provide the relative path, `then downloadlistdirectory` should be appended to the given path list.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L810
