### ISSUE TITLE
[Feature Request] Download from all followed members (Pixiv)

### ISSUE THREAD

**Issue by SaferSky** [Nandaka/PixivUtil2#729]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Requesting feature to get the full list of user's followed members (Pixiv), store all the member_ids in a text file just like the list.txt, then download all images just like using the list.txt feature.

**Expected behavior:** Can get the full list of user's followed member_ids, and download all the images.

**Comment by thegreatestminer** [comment]
This is already implemented.

Use `m. Export online user bookmark`, give a filename then press Enter, then do not input any member ID, then press enter again. It will then export your entire list of followed artists (bookmarked artists) into that filename.

After it finishes, use `i. Import list file`, give the filename you used to export the list, then press Enter.

Once you do that, use `4. Download from list`, and press Enter without inputting anything again.

It will now download your entire list.

---

You can also just download all of your bookmarked artists by using `5. Download from bookmarked artists (/bookmark.php?type=user)` but that will not export a list.
