### ISSUE TITLE
Downloaded local files removed/synced as artist delete their work?

### ISSUE THREAD

**Issue by HeliosDenton** [Nandaka/PixivUtil2#730]
Today I checked one of the artist's folder, and to my shock, it's empty. I clearly recall it had plenty of images in it before.

A visit to the artist's page shows the artist have all his works removed. Did the Pixiv Downloader also synced/deleted the previously downloaded local files?

**Comment by Nandaka** [comment]
nope, it doesn't delete old files. Ensure you are opening the correct folder, especially if you are using the artist name, instead the id.

**Comment by HeliosDenton** [comment]
Okay, maybe the folder in my memory was the one back in the days when I saved the images manually. Thanks for your reply.
