### ISSUE TITLE
Inconsistent config file behavior, unnecessary overwrites

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#731]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Option 4 (and, I presume, other download image options) read config file on each and every new user processed
Option f1 (and other fanbox options, I presume) write to config file on each and every new user processed

### Steps to Reproduce

Start program, run option 4 - download from member list, change config file, e.g. `checkupdatedlimit`, save and close config file, next artists will be processed with new parameters. Config file persists
Start program, run option f1 - download supported artists, change config file, save and close config file, open when next artists began processing, config file will be overwritten to the version at the start of PixivUtil2

**Expected behavior:** [What you expected to happen]

1. For fanbox, PixivUtil2 doesn't overwrite config file with old values, eg. if refresh_token haven't changed, rereads config file at every new artist processed, applies new parameters and doesn't overwrite changes I made in-between.

**Actual behavior:** [What actually happened]

PixivUtil2 overwrites config file with old values from memory.

### Versions

v20200524

**Comment by bluerthanever** [comment]
Isn't there an option to reload configuration?
Also, if you want to use different settings for some different creator, there is this new batch job function. (even though FANBOX doesn't support batch job yet)
Even though I **DO** think that overwrite configuration when no options are changed is not neccessary. 

Do you mind telling me what exactly you want? Like what specific options you would change between creators, and why if possible.

**Comment by NHOrus** [comment]
I just ran the PixivUtil for Fanbox download, tried to set up filtering of URLs in the process for later download from main Pixiv galleries and got very frustrated that my regexp/setting value to true got overwritten without any need for that.

There's an option to reload configuration, but you can't run that in the middle of fanbox download. Also, you can't ctrl-C from fanbox download.

I just want that config for Fanbox downloads behaved like config for Pixiv downloads: 
1. Don't overwrite config with old version every new user in list download
2. If overwrite is needed, read current config, update outdated/invalid values, write new config, not blindly write config from memory.

**Comment by bluerthanever** [comment]
Well, as far as I know, for FANBOX downloads, program needs to retrieve creator information (mostly for filename format I guess) from pixiv using oauth token, and then rewrites it to file in case of changes before proceed. I guess that's the main reason to be causing your problem.

But by how you use it, it doesn't seem really necessary that it has to be done between FANBOX creators?
1. You said it's for later download from main Pixiv galleries, so **the changes doesn't need to be applied to FANBOX**
2. If it is changed to as you wrote in point 2, the program still needs to read/write configuration between creators most likely, so the next creator would use the new configuration, which is different from previous creators, which leads to **changes being applied to FANBOX**

If so, I think it's better that you reload manually after FANBOX before you start main Pixiv download.
And if it doesn't matter that the changes would be applied to FANBOX, then I don't really see the necessity to do it between FANBOX creators, it could be totally done before you run the program.

All I want to say is, even though technically it could be done, I don't really see the necessity to do this.
But if you still think this is needed after the above, please reply.

**Comment by Nandaka** [comment]
@bluerthanever 

move `__br__.fanboxUpdateArtistToken(artist)` https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1029
inside `processFanboxArtist()` https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1056
add `__config__.loadConfig(path=configfile)` before you calling update artist tokent.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivArtistHandler.py#L29

After modification, it should have the same handling as current artist handler 
https://github.com/Nandaka/PixivUtil2/blob/master/PixivArtistHandler.py#L29

**Comment by bluerthanever** [comment]
Yes, I can see it's possible to change the codes like that.
But what I am trying to say is, modification like this may not be solving his problem.

**Comment by NHOrus** [comment]
They look like they solve my problem

**Comment by bluerthanever** [comment]
ok. if you say so.
