### ISSUE TITLE
OAuth Error, cannot download from Fanbox

### ISSUE THREAD

**Issue by itsAvient** [Nandaka/PixivUtil2#738]
### Prerequisites

* [x ] Did you read FAQ section?
* [x ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Failed to login using OAuth While Trying To Download Pixiv Fanbox Supported, Option F1, Using Version 20200524

### Steps to Reproduce

1. Log into Util
2. Login Successful
3. F1
4. Max Page, tried numbers 0,1,2,100 (any of those)

**Expected behavior:** Login Successfully

**Actual behavior:** 

Trying to log in FANBOX with saved cookie
FANBOX Login successful.
Getting supported artists from https://api.fanbox.cc/plan.listSupporting
Found 2 supported artist(s)
[, <, P, i, x, i, v, M, o, d, e, l, F, a, n, b, o, x, ., F, a, n, b, o, x, A, r, t, i, s, t,  , o, b, j, e, c, t,  , a, t,  , 0, x, 0, B, F, 4, 4, F, 4, 0, >, ,,  , <, P, i, x, i, v, M, o, d, e, l, F, a, n, b, o, x, ., F, a, n, b, o, x, A, r, t, i, s, t,  , o, b, j, e, c, t,  , a, t,  , 0, x, 0, B, F, 4, 4, 7, 9, 0, >, ]
Using OAuth to retrieve member info for: 9472577
103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。
Failed to login using OAuth
press enter to exit.

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by itsAvient** [comment]
I also want to note that the refresh token in the config.ini is EMPTY

**Comment by Nandaka** [comment]
can you try latest version in https://github.com/Nandaka/PixivUtil2/releases?

**Comment by itsAvient** [comment]
Tried Version: 20200712

1. Logged in.
2. F1
3. Max Page = 3

Input: f1
Max Page = 3
Trying to log in FANBOX with saved cookie
FANBOX Login successful.
Getting supporting artists from https://api.fanbox.cc/plan.listSupporting
Found 2 artist(s) in supporting list
['9472577', '25310139']
Reading C:\Users\Khoa\Desktop\pixivutil20200712\config.ini ...
done.
Getting artist information from https://api.fanbox.cc/creator.get?userId=9472577
Using OAuth to retrieve member info for: 9472577
103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。
Traceback (most recent call last):
  File "PixivUtil2.py", line 1032, in menu_fanbox_download_from_list
  File "PixivUtil2.py", line 1057, in processFanboxArtistById
  File "PixivBrowserFactory.pyc", line 882, in fanboxGetArtistById
  File "PixivBrowserFactory.pyc", line 613, in getMemberInfoWhitecube
  File "PixivOAuth.pyc", line 123, in login
PixivException.PixivException: 0 Failed to login using OAuth, hasDumpPage=N, pageData=None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1628, in main
  File "PixivUtil2.py", line 1364, in main_loop
  File "PixivUtil2.py", line 1034, in menu_fanbox_download_from_list
NameError: name 'artist' is not defined
press enter to exit.


-------------
I saw that it was one fanbox that displayed wasn't working so I tried F2 as well and manually entered ID, and it also resulted in a OAuth error so i'm not entirely sure what's going on.

**Comment by Nandaka** [comment]
> またはメールアドレス、パスワードが正しいかチェックしてください。

use email address for the username for oauth login in config.ini

**Comment by itsAvient** [comment]
It works fantastic now, thank you so much!
