### ISSUE TITLE
[Problem] Creating duplicates when "alwayscheckfilesize" is enabled

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/PixivUtil2#74]
When alwayscheckfilesize = True, the app seems to ignore the original filename.

Example, I had downloaded these files already (both files are from march 2015):
<pre>44853408 - 18歳の誕生日おめでとう！！.jpg
45238236_big_p1 - C86新刊①『アイドルがしちゃいけない顔』サンプル.jpg</pre>

When I set alwayscheckfilesize = True and run my list again, it did download these:
<pre>44853408_p0 - 18歳の誕生日おめでとう！！.jpg
45238236_p1 - C86新刊①『アイドルがしちゃいけない顔』サンプル.jpg</pre>

Corresponding file pairs are same.

It seems like server-stored filename of some images got changed, now they can include **_p0** for single-image submissions, and manga submissions may not have **_big** part.

Not sure what can be done about this.

**Comment by Nandaka** [comment]
Maybe I can use the stored filename to get the downloaded file, assuming the file is exists in the drive.

**Comment by reyaz006** [comment]
I guess it will work. Not sure if it was always saving filenames in db, but right now I have ~110k files with **_p0** part, and db file contains only ~30k occurrences of that string.

**Comment by Nandaka** [comment]
got issues on the manga mode, as it is only save the last image filename...

**Comment by reyaz006** [comment]
I may be not able to test this fully since I've already re-downloaded all my list. (db got broken at some point so I wiped it)

But thanks. I'll report if there will be more problems with this.
