### ISSUE TITLE
[Feature Request] Download/Update Member Images into a Zip File

### ISSUE THREAD

**Issue by SaferSky** [Nandaka/PixivUtil2#742]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

This is in fact the continuation of Issue #729 , after downloading a large number of images from many members (say 1000+ members), image files and file sizes will be huge, which leads to a great chance slowing down the hard drive and potentially damaging the files. This is happening on my lousy mobile hard drive.

Can we have a feature to zip all the images by member, and push the new member images to the existing zip file, every time we download/update their profile?

This could be a bit tricky as options like verifying the image sizes/ downloaded images could be more difficult than it was simply in a folder.

**Expected behavior:**

For the expected result, I am looking for an option to create a zip package for each member after we download/update their images.

**Comment by Nandaka** [comment]
not useful, you still need to store the file somewhere in the harddisk to be able to store in to zip file.
also, the images already compressed (jpeg/png), so the size reduction won't that big.

If you are using windows with NTFS partition, you can enable folder compression.
![image](https://user-images.githubusercontent.com/836867/88249276-8e425180-ccd6-11ea-81c1-d6d614f4c05d.png)

**Comment by SaferSky** [comment]
> not useful, you still need to store the file somewhere in the harddisk to be able to store in to zip file.
> also, the images already compressed (jpeg/png), so the size reduction won't that big.
> 
> If you are using windows with NTFS partition, you can enable folder compression.
> ![image](https://user-images.githubusercontent.com/836867/88249276-8e425180-ccd6-11ea-81c1-d6d614f4c05d.png)

I get your point and I do notice the harddrive compress option. For me, file size is not really my concern, but now the issue for me having over 1 million image files, that really drags the harddrive speed down. And I am experiencing image files corrupted because of this (my lousy hard drive just doesn't work with so many fragments).
If we zip all images by member, then this is 1000+ files vs 1 million files. And of course, all zipped images can be deleted since they are already in the zip folder.

**Comment by Nandaka** [comment]
then it is better to change your filename format to create subfolder, instead just storing it into single folder.
