### ISSUE TITLE
Inconsistent Fanbox file name allowances?

### ISSUE THREAD

**Issue by photonometric** [Nandaka/PixivUtil2#743]
[Newest release 2020-07-12, Windows 7]

Had to re-do my config from scratch, and came across an error while trying to get Fanbox naming to work. 

It seems that using the `%image_id%` tag in the `filenameformatfanboxcontent` option produces this error:

```
2020-07-24 00:07:32,255 - PixivUtil20200712 - ERROR - Failed to read configuration.
Traceback (most recent call last):
  File "PixivUtil2.py", line 1491, in main
  File "PixivConfig.pyc", line 223, in loadConfig
  File "PixivConfig.pyc", line 34, in process_value
ValueError: ('Illegal value for', 'filenameFormatFanboxContent', ':', '%member_id% [%member_token%]\\%member_token% - %image_id%')
```

This was slightly difficult to figure out, because the `%image_id%` tag is allowed in both the `filenameformatfanboxcover` and `filenameformatfanboxinfo` fields. Perhaps they could be consistent? Or the ValueError output could identify which tag is illegal, in stead of returning the entire file name string.

It was also difficult to start tracking down, because it completely crashes the program, even when not doing anything related to Fanbox. The Failed to read configuration message appears in the init heading, but then this fatal error occurs when doing something like correctly-configured member-id downloading:

```
2020-07-24 00:07:59,878 - PixivUtil20200712 - INFO - Member id mode.
2020-07-24 00:08:04,288 - PixivUtil20200712 - ERROR - Unknown Error: 'NoneType' object has no attribute 'numberOfPage'
Traceback (most recent call last):
  File "PixivUtil2.py", line 1628, in main
  File "PixivUtil2.py", line 1325, in main_loop
  File "PixivUtil2.py", line 621, in menu_download_by_member_id
  File "PixivHelper.pyc", line 1033, in get_start_and_end_number
AttributeError: 'NoneType' object has no attribute 'numberOfPage'
```

I guess it's good to disallow illegal file naming schemes, but perhaps the program could still run its other functions if an error is made in fanbox file naming? 

Anyway, guess all this isn't necessarily even a bug if one knows the peculiarities of Fanbox tag mappings, but there are some ideas about how it presents the errors to users, in any case. ^^

**Comment by Nandaka** [comment]
> filenameformatfanboxcontent

From the code, you need to use `%urlFilename%`, `%page_index%`, or `%page_number%` in the filename format to avoid duplicated filename (in case multiple images in single post). Might need to enhance to add custom error messages in the config parser.

> The Failed to read configuration message appears in the init heading, but then this fatal error occurs when doing something like correctly-configured member-id downloading:

I guess need to change the behaviour to exit if the config is not setup correctly.

**Comment by bluerthanever** [comment]
Hmm.. Sorry when I changed `PixivConfig.py` I should have put 
https://github.com/Nandaka/PixivUtil2/blob/ed9630b0eb9a582a3a1af3a0c68ece749851ecb5/PixivConfig.py#L223
inside the `try...except...` clause above, so the item would be set to default value if it is not "legal".

**Comment by photonometric** [comment]
Aha! So if that is implemented, should %image_id% be usable for Fanbox?

**Comment by Nandaka** [comment]
%image_id% should be ok, it should be the post id for fanbox.

**Comment by photonometric** [comment]
Ah ok! So to circle back to my original problem (and for anyone else looking for answer to this):

`filenameformatfanboxcontent` is like `filenamemangaformat`, and assumes posts have multiple images (even if only have 1 besides the cover/thumb). So `%urlFilename%` works, or `%image_id%` ONLY IF followed by/included with `%page_index%` or `%page_number%`.

`filenameformatfanboxcover` and `filenameformatfanboxinfo` work with `%image_id%` alone, I guess because they can only have a single file per post id. 

> > The Failed to read configuration message appears in the init heading, but then this fatal error occurs when doing something like correctly-configured member-id downloading:
> 
> I guess need to change the behaviour to exit if the config is not setup correctly.

Mm nope! It already does that. When I said "fatal error" I meant that the program gives the same error as in the log, then says 'press any key to exit.' I included that more as a suggestion that an error in the fanbox subsection needn't require a mysterious error when doing something on the main pixiv site. But it sounds like @bluerthanever might have fixed that. Or indeed, more user-readable error messages with regard to config options/filename syntax would be helpful, especially if the program will exit upon any error.



PS. not worth making another issue for, but the readme (which was renamed readme.txt -> readme.md in April) **was not included with the last few releases packages** ^^

**Comment by photonometric** [comment]
Another minor idea might be to highlight error and new version messages in the init headers, with a box of ASCII stars or something. Maybe putting the message last in the init, or even down by the entry cursor. When one runs this program for many years, I don't read every line of the header as it scrolls quickly by ;3

**Comment by Nandaka** [comment]
added colorama packages, so by right it should highlight the error message in red on latest commit 5044008.
![image](https://user-images.githubusercontent.com/836867/88373680-da6ebe00-cdca-11ea-8a1d-d54c52ec1b33.png)

**Comment by photonometric** [comment]
Woooah, very snazzy looking! Looks like some awesome config.ini handling there too! :3 


Also while on the subject (so not to make another tiny new issue #), it appears that every fanbox login re-writes the config.ini file, along with the backup. Primary pixiv login doesn't seem to do this. Maybe it's re-writing the cookie value every time, even if not altered? 

Not a huge problem, but is confusing if trying to determine when I *actually* altered my configuration, as when I compare to every new version.

**Comment by Nandaka** [comment]
I think it need to update oAuth token, not sure the validity for that, but usually oAuth need to be refreshed every 1hour (at least that is the default for Firebase). I don't use Fanbox, so I'm not sure about that 😛 

check the log file for this line `Not logged in to FANBOX, trying to update FANBOX cookie.` ?

**Comment by bluerthanever** [comment]
Well, sometimes FANBOX cookie string would also expire, so it will retrieve a new one with the valid pixiv.net main cookie string, and update configuration.
