### ISSUE TITLE
setlastmodified (Date Created) for Fanbox downloads

### ISSUE THREAD

**Issue by photonometric** [Nandaka/PixivUtil2#745]
[release 2020-07-12, feature request]

I'm very fond of the setlastmodified feature when downloading from the main pixiv site. Viewing **Date Modified** as the 'artist uploaded' time, and **Date Created** as my download time, adds another layer of easily visible and important image/artist info. Great feature!

Fanbox downloads don't follow this rule, when the option is set to true. The Modified/Created times both set to when I download it. 

**Could this option be tied to the Fanbox downloads, as well?** Or perhaps an equivalent option added in the [FANBOX] section, if there's some reason people would want to control fanbox/pixiv separately. 

Would be great to get this implemented while fanbox download function is still fairly new, so we don't have to re-download all our fanboxes to change the date stamps later....(not that I can afford many fanbox subscriptions anyway xp)

Thanks for all the great work!

**Comment by bluerthanever** [comment]
okay... sorry when i was changing this part i ran into this question, like why modified/created date is needed, and kinda just did it my way... will try to make it similar to pixiv.net

**Comment by bluerthanever** [comment]
> The Modified/Created times both set to when I download it.
Here "modified time" refers to "last_updated_date", and "created time" refers to "created_date" which are both in table "fanbox_post_image", right?
And just to be sure, do you by any chance use any of the 3 date columns in table "fanbox_post_master"?

**Comment by bluerthanever** [comment]
Just for your information, here's what all the date columns stand for currently:
table "fanbox_post_master":
- published_date: published date of the post
- updated_date: updated date of the post, sometimes an author doesn't delete a post, instead he modifies it, and after he'd done that, this would be changed
- last_update_date: time you last check the post, which somehow means, this post exists at this time. This does not neccesarily means that the post is visible to you, but just that it is there.

table "fanbox_post_image":
last_updated_date and created_date now both stand for the time when this image is last downloaded

**Comment by bluerthanever** [comment]
I think I will start working on this after your reply. XD

**Comment by Nandaka** [comment]
You can set the last modified datetime to `FanboxPost.worksDateDateTime` attribute, then the download handler will take care the updates.

Refer to https://github.com/Nandaka/PixivUtil2/blob/master/PixivDownloadHandler.py#L139

**Comment by bluerthanever** [comment]
Urr. Sorry that I thought what this option does was simply updating the time recorded in database....
So the whole idea is to set the `created time` of **the file** to user download time, and `modified time` to artist upload time. But should this `artist upload time` be the `published time` or `updated time` of the post?

**Comment by bluerthanever** [comment]
Hmm. Looks like for pixiv published date is used, so I will follow that.

**Comment by bluerthanever** [comment]
This should have been fixed in #747 already.
