### ISSUE TITLE
Pixiv Sketch Support

### ISSUE THREAD

**Issue by HydroHydro** [Nandaka/PixivUtil2#749]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

This has already been requested and denied. #367  But with recent changes, it might be possible now...?

If you scroll down on a user's profile:
https://www.pixiv.net/en/users/711569
You will find their sketch URL:
https://sketch.pixiv.net/@camori

I'm not sure if this was always the case. It might have happened with the new redesign???

Either way, the very popular JDownloader now has support for Pixiv Sketch profiles. I should know because I'm the one who requested they add support for it! ^_^

Would it be possible to add this support to PixivUtil2?

----

A strange thing I noticed. When you click a picture on the Sketch site, it first loads a larger webp image, but if you let it sit there for a few seconds, it eventually loads a higher quality png image. Hope that information helps you!

**Comment by Nandaka** [comment]
check latest releases check latest releases https://github.com/Nandaka/PixivUtil2/releases
