### ISSUE TITLE
can't login?

### ISSUE THREAD

**Issue by mynameisno123** [Nandaka/PixivUtil2#752]
Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 319, in login
TypeError: 'NoneType' object is not subscriptable
Error at login(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x076AD0A8>)
Error at doLogin(): (<class 'TypeError'>, TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x073DDE28>)
Cannot Login!
how to fix it?

**Comment by mynameisno123** [comment]
![Capture](https://user-images.githubusercontent.com/69161186/89266542-3dc8dd80-d660-11ea-9c64-157e43123a79.PNG)

**Comment by bluerthanever** [comment]
Q3. I cannot login to Pixiv!
    - Check your password.
    - Try to login to the Pixiv Website.
    - Try to use the config.ini on the [Authentication] section.
    - Check your date and time setting (e.g.: https://www.timeanddate.com/)
    - Disable Daylight Saving Time and try again.
    - Copy your session values from browser:
      1. Open Firefox.
      2. Go to Pixiv website and login, remember to enable [Remember Me]
          check box.
      3. Right click the page and select View Page Info.
      4. Click the Security tab.
      5. Click the View Cookies button.
      6. Look for Cookie named = PHPSESSID.
      7. Copy the content value.
      8. Open config.ini, go to [Authentication] section, paste the value
          to cookie, set keepsignedin = 1.

**Comment by Nandaka** [comment]
also, use the latest releases https://github.com/Nandaka/PixivUtil2/releases
