### ISSUE TITLE
[Feature Request] Create directory for every post

### ISSUE THREAD

**Issue by railannad** [Nandaka/PixivUtil2#756]
### Prerequisites

* [y ] Did you read FAQ section?
* [ y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

When I download files from fanbox , I find that all the pictures and videos are downloaded to a same path , like the following pictures . 
I hope it can create directory for every post instead of downloading all files to a same directory

![image](https://user-images.githubusercontent.com/36919867/89496416-e1df8f80-d7ec-11ea-89a4-6020edc3c07b.png)

**Comment by bluerthanever** [comment]
You can use `filenameFormatFanboxCover` and `filenameFormatFanboxContent`.
For example, if your OS is Windows, you can set `filenameFormatFanboxContent` to "%artist% (%member_id%)\%image_id% - %title%\%urlFilename%“

**Comment by railannad** [comment]
Thank you very much. I successed create directory for every post.
