### ISSUE TITLE
Failed to login using OAuth

### ISSUE THREAD

**Issue by hwinksy** [Nandaka/PixivUtil2#760]
### Prerequisites

* [ no ] Did you read FAQ section?
* [ yes ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

failed to login using OAuth While Trying To Download Pixiv Fanbox

### Steps to Reproduce

1.Start PixivUtil2, with username, password, and cookie set in config.ini
2.Login succeeds
3.choose f3
4.enter post ID

**Expected behavior:** Downloads a members' fanbox works

**Actual behavior:** 103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。
Failed to login using OAuth

### Versions 20200726

![360截图20200810221916480](https://user-images.githubusercontent.com/32708598/89793599-a2040980-db58-11ea-9133-06aa2d6aff40.png)
![360截图20200810222106355](https://user-images.githubusercontent.com/32708598/89793645-b0eabc00-db58-11ea-8123-de40b8ae7143.png)
![360截图20200810222529205](https://user-images.githubusercontent.com/32708598/89793698-bea04180-db58-11ea-9f6b-585057e3d3cb.png)

I found the solution here but its not working：https://github.com/Nandaka/PixivUtil2/issues/536
the refresh token is blank.

**Comment by bluerthanever** [comment]
The error message says that your id, email address or password is wrong, please check them.
So please make sure the account and password you put in config.ini is correct.
If you are using account id in config and it doesn't work, try email address instead. And vice versa.

**Comment by hwinksy** [comment]
thank you so much，the problem has been solved
