### ISSUE TITLE
Ugoira files are only downloaded as zip

### ISSUE THREAD

**Issue by ForxBase** [Nandaka/PixivUtil2#761]
FFmpeg got downloaded and I have it in the same directory as the application. I've tried all settings with Ugoira and FFmpeg in the config file but instead of generating mp4 or webm files from the ugoira it only creates a zip file with all the pictures. How can I fix this?

**Comment by Nandaka** [comment]
upload your config file and log file?

**Comment by ForxBase** [comment]
[Ugoira]
writeugoirainfo = True		
createugoira = True
deletezipfile = True
creategif = True
createapng = False
deleteugoira = False
createwebm = True
createwebp = False

The rest is like out of the box settings. Also the FFmpeg folder is located on the same drive if that matters.

**Comment by ForxBase** [comment]
Can you help?

**Comment by Nandaka** [comment]
how big is your ffmpeg.exe? mine is about 60mb.

Run `ffmpeg.exe -encoders` in the cmd console and ensure `libvpx-vp9` is in the list.

Also upload `pixivutil.log` here.

**Comment by ForxBase** [comment]
Mine is around 73.000KB. Where should I store the ffmpeg.exe? On the same drive I have the downloader? 

I tried running the command but it says it couldn't find it. 

I checked the log file and there's lots of information in there. Don't know if it's safe to upload here.

**Comment by Nandaka** [comment]
same folder with the downloader.

**Comment by ForxBase** [comment]
Hello,

I did now copy the ffmpeg exe into the same folder as the downloader. But I'm not sure which options to set in the config to download ugoira files as mp4 or gif. Please help. 

Thanks.

**Comment by ForxBase** [comment]
> same folder with the downloader.

I did now copy the ffmpeg exe into the same folder as the downloader. But I'm not sure which options to set in the config to download ugoira files as mp4 or gif. Please help.

**Comment by ForxBase** [comment]
Can anyone help with this?

**Comment by Nandaka** [comment]
> Run ffmpeg.exe -encoders in the cmd console and ensure libvpx-vp9 is in the list.

what is the result? also it creates .webm instead .mp4.

**Comment by ForxBase** [comment]
> > Run ffmpeg.exe -encoders in the cmd console and ensure libvpx-vp9 is in the list.
> 
> what is the result? also it creates .webm instead .mp4.

How do I run the .exe -encoders in cmd? Where do I check for vp9?
