### ISSUE TITLE
[Feature request} Create Fanbox dir?

### ISSUE THREAD

**Issue by Yurihellsing** [Nandaka/PixivUtil2#765]
### Prerequisites

* [X ] Did you read FAQ section?
* [ X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Just a little thing could you add Create Fanbox dir?

Thanks!

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
Edit the config.ini and update the [FANBOX} section?
```
[FANBOX]
filenameformatfanboxcover = %artist% (%member_id%)\%urlFilename% - %title%
filenameformatfanboxcontent = %artist% (%member_id%)\%urlFilename% - %title%
filenameformatfanboxinfo = %artist% (%member_id%)\%urlFilename% - %title%
```

**Comment by Yurihellsing** [comment]
Oh sorry I've been using an older config

**Comment by Yurihellsing** [comment]
Ok I'm still not sure what do I change?

**Comment by Nandaka** [comment]
modify your `filenameformatfanbox*` to include the fanbox folder? e.g. put `FANBOX\%artist% (%member_id%)\....`

**Comment by Yurihellsing** [comment]
Ah thank you got it working!

**Comment by rwchunk** [comment]
so its not just me lol
for reference, this creates a 'fanbox' folder in the artist folder:
`%artist% (%member_id%)\fanbox\%urlFilename% - %title%`
