### ISSUE TITLE
Exporting previous verison download history to avoid redownloading for latest PixivUtil2?

### ISSUE THREAD

**Issue by RighteousAnger** [Nandaka/PixivUtil2#767]
Wasn't able to find this anywhere...If there is a solution for this, I definitely missed it.

Until now, I used pixivutil20200524 for all my downloads and keeping up / downloading new artist's images. Then I decided to use the latest, pixivutil20200726, and realized that the same artist I inputted, the downloader proceeds to re-download all images again. Is there some way to export the previous version download history (?) into the new one and latest one? (To avoid re-downloading images/gifs again?)

**Comment by Nandaka** [comment]
copy the `db.sqlite` from the old version? also check the config.ini

**Comment by RighteousAnger** [comment]
Wow, something simple as that..thank you, Nandaka. I feel like a complete idiot
