### ISSUE TITLE
[Crash] Error at process_bookmark()

### ISSUE THREAD

**Issue by NonaSuomi** [Nandaka/PixivUtil2#768]
### Prerequisites

* [X ] Did you read FAQ section?
* [ X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Downloading from bookmarked artists returns the following error:

Error at process_bookmark(): (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'"), <traceback object at 0x0BC46E48>)

### Steps to Reproduce

1. Run program
2. Select option 5
3. Leave options at default

**Expected behavior:** To download images from bookmarked artists

**Actual behavior:** The program crashes with the error message above

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

Using the latest version downloaded from the github (20200726)

**Comment by bluerthanever** [comment]
I think more detailed information is needed for this... Could you upload your log?

**Comment by NonaSuomi** [comment]
[logfile.txt](https://github.com/Nandaka/PixivUtil2/files/5115368/logfile.txt)
The logfile was a bit unwieldy, nearly two months of data and ten megs in size, so I trimmed it to just the last session, which only consists of opening the program and attempting the steps as described above. If the unabridged log is necessary let me know and I'll upload it.

**Comment by Nandaka** [comment]
try the latest releases: https://github.com/Nandaka/PixivUtil2/releases

**Comment by NonaSuomi** [comment]
Just downloaded that release, same issue. I also tried just extracting to a new folder instead of re-using my existing install, just copied in my config file, and still got that error on option 5. I've attached the full log from that install:
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5118802/pixivutil.log)

**Comment by Nandaka** [comment]
from logging:
`
2020-08-24 08:29:20,383 - PixivUtil20200824 - INFO - Logged in using cookie
2020-08-24 08:29:20,384 - PixivUtil20200824 - INFO - Unable to get User Id
`
looks like the cookie already expired, can you update the cookie and retry?

**Comment by NonaSuomi** [comment]
Ah, sorry I missed that. It said successful login, so I just assumed that user ID thing was an informational message for the fanbox stuff or something. It appears to be working now, thanks for that!

**Comment by Nandaka** [comment]
yes, sometimes the login detection is a bit wonky.
I have updated the error message and it will be displayed in red in the console.
