### ISSUE TITLE
HTTP Error 404: Not Found when trying to download fanbox

### ISSUE THREAD

**Issue by Smokedninja10** [Nandaka/PixivUtil2#771]
### Prerequisites

* [Yes] Did you read FAQ section?
* [Yes] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Traceback (most recent call last):
  File "PixivUtil2.py", line 1476, in main
  File "PixivUtil2.py", line 1214, in main_loop
  File "PixivUtil2.py", line 1092, in menu_fanbox_download_by_id
  File "PixivUtil2.py", line 1067, in processFanboxArtistById
  File "PixivFanboxHandler.pyc", line 19, in process_fanbox_artist_by_id
  File "PixivBrowserFactory.pyc", line 876, in fanboxGetArtistById
  File "PixivBrowserFactory.pyc", line 199, in open_with_retry
  File "mechanize\_mechanize.pyc", line 253, in open
  File "mechanize\_mechanize.pyc", line 309, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found

Also this is with using the creators name as i can not find the creators number id

### Steps to Reproduce

1. Login
2. Option f2
3. Enter for default option

**Expected behavior:** Download of an entire Fanbox

**Actual behavior:** Error above

### Versions 20200726

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
what is the creator name?

**Comment by Smokedninja10** [comment]
Its a NSFW creator i didn't think it would be appropriate to post it here but if its necessary i will comment it.

**Comment by Nandaka** [comment]
well, I need the name, so I can check. Just put it as within the code tag, so it won't be linked direcly, or just remove the https://

**Comment by Smokedninja10** [comment]
www.fanbox.cc/@vodor

**Comment by Nandaka** [comment]
can you try the latest releases https://github.com/Nandaka/PixivUtil2/releases

you might need to copy the `FANBOXSESSID` and update the config.ini manually.
![image](https://user-images.githubusercontent.com/836867/91007548-d8d52780-e60e-11ea-8622-4ecf82090825.png)

**Comment by Smokedninja10** [comment]
ok so now it wont let me log in i get this error "Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0xb983e38 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x0B9AF4E8>)
Cannot Login!" i have tried refreshing my cookies 3 times and doing what the FAQ says with no luck.

**Comment by Nandaka** [comment]
ensure you are logged in to fanbox.cc not pixiv.net, also update `cookiefanbox` from FANBOXSESSID in config.ini

**Comment by bluerthanever** [comment]
Actually cookies tring to pixiv.net is the crucial one, while the one to fanbox.cc would be changed by server sometimes.
If the one to fanbox.cc expires, a new one would be retrieved automatically.

I tried the artist on the latest codes and it works fine with my cookie strings.
Please make sure your cookie string to pixiv.net is valid.

**Comment by Smokedninja10** [comment]
Ok so I no longer have the login error but i'm still getting the same original error as I was before I have done the fanbox cookie both ways and i'm positive its a valid cookie string but still getting the same error.

**Comment by bluerthanever** [comment]
....please leave out the `@`

**Comment by Smokedninja10** [comment]
Welp that's what it was i'm so sorry for wasting your guys time
