### ISSUE TITLE
Pixiv Sketch support not working

### ISSUE THREAD

**Issue by HydroHydro** [Nandaka/PixivUtil2#772]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I get this error when trying to download with the new Pixiv Sketch feature:

Processing Artist Id: camori
Traceback (most recent call last):
  File "PixivSketchHandler.pyc", line 42, in process_sketch_artists
  File "PixivBrowserFactory.pyc", line 986, in sketch_get_posts_by_artist_id
UnboundLocalError: local variable '_tzInfo' referenced before assignment
Error at process_sketch_artists(): camori
Exception: (<class 'UnboundLocalError'>, UnboundLocalError("local variable '_tzInfo' referenced before assignment"), <traceback object at 0x10984CE8>)

**Comment by Nandaka** [comment]
temporarily set `useLocalTimezone` in `config.ini` to True
