### ISSUE TITLE
Auto bookmark image from bookmaked user

### ISSUE THREAD

**Issue by itsmenmd** [Nandaka/PixivUtil2#773]
### Prerequisites

* [ ] Did you read FAQ section?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
Hi can you make a feature about Auto bookmark image from bookmaked user, I think this work make better recommend image without interacting with image from old bookmarked user
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
You want to bookmark all images from the bookmarked/followed user?

**Comment by itsmenmd** [comment]
yes, maybe inheritace from download  image from bookmaked user, i mean new feature do both,  download and bookmark all images from the bookmarked/followed user? or may be just bookmark. thanks

**Comment by Nandaka** [comment]
that action might cause pixiv to ban you due to a lot of changes on bookmarking action. Also, you got limit on the number of bookmarked images. I don't think it is a good idea.
Pixiv already can suggest you based on the followed artist already, no need to purposely bookmark all their image.

**Comment by itsmenmd** [comment]
> that action might cause pixiv to ban you due to a lot of changes on bookmarking action. Also, you got limit on the number of bookmarked images. I don't think it is a good idea.
> Pixiv already can suggest you based on the followed artist already, no need to purposely bookmark all their image.

thansk you for that infomation, idk bout that :P
