### ISSUE TITLE
how to fix the  OAuth problem?

### ISSUE THREAD

**Issue by woodsierpie7** [Nandaka/PixivUtil2#775]
### Prerequisites

* [yes ] Did you read FAQ section?
* [ yes] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

im trying to download some posts from the fanbox and using any method but the program keeps saying 103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。
Error processing FANBOX post: 1339421 ==> Failed to login using OAuth

**Comment by woodsierpie7** [comment]
sorry if i writed anything wrong but im new again im very sorry for that

**Comment by Nandaka** [comment]
using google translate, it said you need to use the correct email address or password to login.
Update you config.ini username/password?

**Comment by woodsierpie7** [comment]
yes

**Comment by bluerthanever** [comment]
are you using id or e-mail address as username? if one of them doesn't work try the other one.

**Comment by woodsierpie7** [comment]
thanks it works now you just need to set your email as your username
