### ISSUE TITLE
Strange pixivutil2 behaviour

### ISSUE THREAD

**Issue by Butterfly-Dragon** [Nandaka/PixivUtil2#776]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

only the latest release i see there have been 5 commits but seem unrelated.

### Description

running `PixivUtil2.exe -s 5 y -x` results in the database shrinking and the whole galleries being re-downloaded.

### Steps to Reproduce

Described above.

**Expected behavior:** download only the new pictures from all the bookmarked artists while checking their galleries for changes/edits.

**Actual behavior:** galleries are being re-downloaded from scratch and *the database is shrinking* in size. I stopped it after only 5 artists and it already shrunk from 149644 kbs (according to my backup) to 140076 kbs after downloading about 6700 pictures.

Re-running pixivutil2 with the parameters `PixivUtil2.exe -s 5 y 1 1 -x` re-downloads the first page of bookmarked artists each time. But the database size has stayed the same size ever since.

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

this happened after i downloaded the 2020/08/24 version 3 days ago

**Comment by Nandaka** [comment]
check your config.ini?

**Comment by Butterfly-Dragon** [comment]
sorry for the late reply... i'm working... here is the config ini with the autentication section removed
[config.txt](https://github.com/Nandaka/PixivUtil2/files/5129093/config.txt)
(also had to change extension to `txt` because github)

**Comment by Nandaka** [comment]
can upload the log file?

**Comment by Butterfly-Dragon** [comment]
okay... tonight i tried again... midway through pixivutils stopped behaving that way and started recognizing it had downloaded images... ran again this morning and aside from very few new images ... nothing changed... i... uh... i have no clue.
