### ISSUE TITLE
Batch job strange behaviour.

### ISSUE THREAD

**Issue by pxssy** [Nandaka/PixivUtil2#777]
The issue is with wildcard and title_caption options. This is what i've observed pixiv does when i experiment with the options with downloading a particular tag:-

wildcard: T, and title_caption: T, i get 85 works. 

I know there is more than 85 works if i enable wildcard on the site, so there's something wrong with enabling both. 

wildcard: T, and title_caption: F, i get 578 works.

As expected, when i disable title_caption, it goes back to wildcard only and gives me the same result i see on the site.

The site doesn't let you enable search of both wildcard and title_caption, so i think this is why its giving me only 85 results with both on, it ignores the wildcard option. 

Now here is where it gets strange. 

Using My batch_job.json

{
    "jobs": {
        "job1": {
            "enabled": true,
            "job_type": "3",
            "tags": "アークナイツ",
            "start_page": 1,
            "end_page": 0,
            "wildcard": true,
            "title_caption": false,
            "start_date": "",
            "end_date": "",
            "bookmark_count": 10000,
            "oldest_first": false,
            "type_mode": "a",
            "option": {
                "filenameFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameMangaFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameInfoFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameMangaInfoFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "avatarNameFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "useTagsAsDir": false,                
                "rootDirectory": "./10000/"
            }
        },
        "job2": {
            "enabled": true,
            "job_type": "3",
            "tags": "アークナイツ",
            "start_page": 1,
            "end_page": 0,
            "wildcard": false,
            "title_caption": true,
            "start_date": "",
            "end_date": "",
            "bookmark_count": 10000,
            "oldest_first": false,
            "type_mode": "a",
            "option": {
                "filenameFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameMangaFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameInfoFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameMangaInfoFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "avatarNameFormat": "%R-18%/%artist% (%member_id%)/%urlFilename% - %title%",
                "useTagsAsDir": false,                
                "rootDirectory": "./10000/"
            }
        }
    }
}

Best of both worlds right? I get both in 1 job. Wrong.

That batch_job.json gives me 85 for the first time it runs (i'm assuming its doing job1 first then job2), very strange. Job1 should give me 578 instead of 85. Either its doing job2 first for some reason, (i added a job3 with a different bookmark requirement and it still downloaded either job1/2 first) or there's some weird thing happening with stacking jobs like that,

Using the most recent pixiv. with premium account.

**Comment by Nandaka** [comment]
I'm don't have premium, but I remember that I cannot search based on title_caption with wildcard. Can you provide the correct ajax call?

references:
&s_mode=s_tc => title&caption
&s_mode=s_tag_full => search full tag
&s_mode=s_tc => partial tag/wildcard, not sure why it missing

https://github.com/Nandaka/PixivUtil2/blob/5a8e48906bee90298e27b889150ea3cdf2ee4589/PixivHelper.py#L725
