### ISSUE TITLE
Error when downloading images by IDs

### ISSUE THREAD

**Issue by hakkai2015** [Nandaka/PixivUtil2#78]
I try to download image by ID and get the next error:

Image ID (50197884): time data '5 4 2015, 22:17' does not match format '%Y-%m-%d %H:%M'
Dumping html to: Error medium page for image 50197884.html
PixivDownloader2 version 20150427
https://nandaka.wordpress.com/tag/pixiv-downloader/

Trying dowload by memder ID give ne the same result.

**Comment by Nandaka** [comment]
what is your settings for language in the pixiv website? currently only english and japanese are supported.

**Comment by hakkai2015** [comment]
Language was set to Russian.
Now I set it to English. Also I remove cookie string from ini file. Program started working. Thanks!

But when I'm downloading files by member ID, I encounter an another error. A part of files downloaded normally but on some files I got the error.
Problem occurs on different files and not every time, so I think it may be caused by pixiv webserver.

#9
Processing Image Id: 47327604
Image ID (47327604): 'NoneType' object has no attribute 'findAll'
Dumping html to: Error medium page for image 47327604.html
Page  2
Member Url: http://www.pixiv.net/member_illust.php?id=143026&p=2
Traceback (most recent call last):
  File "PixivUtil2.py", line 272, in process_member
  File "PixivModel.pyc", line 48, in __init__
  File "PixivModel.pyc", line 96, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
Error at process_member(): (<type 'exceptions.AttributeError'>, AttributeError("
'NoneType' object has no attribute 'findAll'",), <traceback object at 0x02D49120
>)
Dumping html to: Error page for member 143026.html
Traceback (most recent call last):
  File "PixivUtil2.py", line 1758, in main
  File "PixivUtil2.py", line 1543, in main_loop
  File "PixivUtil2.py", line 1211, in menu_download_by_member_id
  File "PixivUtil2.py", line 272, in process_member
  File "PixivModel.pyc", line 48, in __init__
  File "PixivModel.pyc", line 96, in ParseImages
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit.

**Comment by Nandaka** [comment]
hmm, try to delete the ```cookie``` value from config.ini and set ```keepsignedin = 1```?

**Comment by hakkai2015** [comment]
I take several tests with this option and I don't encounter this error so far.
If this (or other) error occurs again, I let you know.
Thanks for quick response.
