### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by macqo004** [Nandaka/PixivUtil2#780]
### Prerequisites

* [ ] Did you read FAQ section? yes
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? tested with latest stable

### Description

see screenshots

### Steps to Reproduce

1. error on starting the program

**Expected behavior:** [What you expected to happen]
program to run

**Actual behavior:** [What actually happened]
it shows the error message
### Versions
24.08.2020

[pixivutil.txt](https://github.com/Nandaka/PixivUtil2/files/5149894/pixivutil.txt)

[config.txt](https://github.com/Nandaka/PixivUtil2/files/5149908/config.txt)

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
update your cookies? no issue from here.
