### ISSUE TITLE
R18 file name tag is being ignored

### ISSUE THREAD

**Issue by TheDuriel** [Nandaka/PixivUtil2#781]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]

It seems the %R-18% tag for filenames is being ignored.

### Steps to Reproduce

1. [First Step]
I've set up my filepaths like this:
```
filenameformat = %member_id%-%artist%\%R-18%\%urlFilename%
filenamemangaformat = %member_id%-%artist%\%R-18%\%urlFilename%
filenameinfoformat = %member_id%-%artist%\%R-18%\%urlFilename%
filenamemangainfoformat = %member_id%-%artist%\%R-18%\%urlFilename%
```

2. [Second Step]
Then download all my bookmarks via mode 6.

3. [and so on...]

**Expected behavior:** [What you expected to happen]
Each Artist folder should contain up to two subfolders based on if the images are R18.

**Actual behavior:** [What actually happened]
Images are placed directly within the artist directory. Completely skipping the %R-18%/.

### Versions
Latest Release

**Comment by Nandaka** [comment]
please upload the log file?

It should only create R-18 directory if the image has tag with R-18 or R-18G.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L225-L230

**Comment by TheDuriel** [comment]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5165087/pixivutil.log)

**Comment by TheDuriel** [comment]
Actually reading your answer again and checking the results. The documentation gave me the impression that a non r18 folder would be created. But I'm guessing the path for that resolves to something//something instead, and windows just ignores redundant slashes.
