### ISSUE TITLE
[Feature Request] Resume download after closing the application

### ISSUE THREAD

**Issue by PiPerson7472** [Nandaka/PixivUtil2#783]
Most tags have too many pictures or image sets to download all in one sitting. I was wondering if there was a way to restart the download where it was left off after the application was closed. Like a "save state" so to speak was made after every x amount of photos that it can resume the download from, instead of going through possibly tens of thousands of photos.

**Comment by Nandaka** [comment]
it should keep track on the db already when you download the image, also you use newest first for the order.

https://github.com/Nandaka/PixivUtil2/blob/d3b432769e0064d2d266cf1cd32d7216b7472a42/PixivImageHandler.py#L309

**Comment by PiPerson7472** [comment]
I use oldest first for the order and they are added to the db but if I restart the download of a tag I have previously downloaded it has to check to see if the file exists on the drive for each individual picture. Instead of checking within the db and going to the next one in the queue.

**Comment by Nandaka** [comment]
Then you can use the starting page or starting date based on the last download.

**Comment by PiPerson7472** [comment]
Fair enough

**Comment by PiPerson7472** [comment]
Considering how the starting date option does not work and there is no real way for a user (like me) who does not know how to read or write code find out the page number of the last downloaded image I am going to reopen this. I may sound like a douche in wanting this feature so I do apologize for that and my lack of coding know how, but a resume feature would be very handy.

**Comment by Nandaka** [comment]
well, you need premium if you want to search more than 1 year ago.
