### ISSUE TITLE
Unable to download from FANBOX

### ISSUE THREAD

**Issue by ReisenII** [Nandaka/PixivUtil2#784]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Unable to download from supported creators on FANBOX (f1) but no problem with downloading from pixiv users.

### Steps to Reproduce

Open latest version of the downloader
Login as usual through email and password set on the config.ini and cookie obtained from PHPSESSID
Select f1 with any number of max pages

**Expected behavior:** Log into FANBOX and download my supported creators

**Actual behavior:** 
Input: f1
Max Page = 0
Not logged in to FANBOX, trying to update FANBOX cookie...
Could not update FANBOX cookie string.
Traceback (most recent call last):
  File "PixivUtil2.py", line 1144, in main
  File "PixivUtil2.py", line 886, in main_loop
  File "PixivUtil2.py", line 642, in menu_fanbox_download_from_list
  File "PixivBrowserFactory.pyc", line 834, in fanboxGetArtistList
  File "PixivBrowserFactory.pyc", line 382, in fanbox_is_logged_in
Exception: Not logged in to FANBOX
press enter to exit.

### Versions

v20200827-beta1

**Comment by Nandaka** [comment]
I guess you need to copy the cookies from fanbox.cc? should be similar method for pixiv, just is uses FANBOXSESSID

**Comment by ReisenII** [comment]
Oh yeah it worked, I should've tried to look for the cookie before posting this, I'm dummy

Thanks a lot!
