### ISSUE TITLE
Question: How to Disable Opening Browser Upon Detecting Newer Version?

### ISSUE THREAD

**Issue by FloatingSunfish** [Nandaka/PixivUtil2#785]
Currently using v20200824.

When it detects that a new version is available, it opens a new tab for PixivUtil2's releases.

Can this behavior be disabled? I like seeing that there is a new version available, but I don't always want to update right away.

**Comment by Nandaka** [comment]
it is already in the master code (https://github.com/Nandaka/PixivUtil2/blame/master/PixivConfig.py#L63) but not yet released.

Try to set `checknewversion = False` for time being.

**Comment by FloatingSunfish** [comment]
Noted, thanks!
