### ISSUE TITLE
Can't Login To fanbox Cmd said

### ISSUE THREAD

**Issue by Tooskill** [Nandaka/PixivUtil2#788]
### Prerequisites

* [x] Did you read FAQ section?
-Yes
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
-Downloaded the Latest that given by the WEbpage

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step] Log in to Pixiv from the util worked by copying the cookies
2. [Second Step] when it login i typed the Fanbox one like f1-f4
3. [and so on...] when i followed the instuction all of them led to Not login to Fanbox but i alrdy log in to fanbox at Google chrome the question is how to login to Fanbox using pixivutil i searched for the answer but still not found.

**Expected behavior:** [What you expected to happen] shpuld download the photo according to step that selected

**Actual behavior:** [What actually happened]
the cmd shows this :
Not logged in to FANBOX, trying to update FANBOX cookie...
Could not update FANBOX cookie string.
Traceback (most recent call last):
  File "PixivUtil2.py", line 1555, in main
  File "PixivUtil2.py", line 1292, in main_loop
  File "PixivUtil2.py", line 1040, in menu_fanbox_download_from_list
  File "PixivBrowserFactory.pyc", line 834, in fanboxGetArtistList
  File "PixivBrowserFactory.pyc", line 382, in fanbox_is_logged_in
Exception: Not logged in to FANBOX

pixivutil20200824 Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by bluerthanever** [comment]
Looks like the old way to obtain fanbox cookie string expired... let me see what I can do.

**Comment by Tooskill** [comment]
> Looks like the old way to obtain fanbox cookie string expired... let me see what I can do.

Do pivivutil able to Used to Download fAnbox pict even we didn't supp ? Or is Pixivutil even support fanbox ?

**Comment by bluerthanever** [comment]
Though your sentence is quite hard to understand, but yes, PixivUtil2 supports FANBOX.

**Comment by Tooskill** [comment]
ma bad ma english very bad but i will try my best express the condition to show u

**Comment by bluerthanever** [comment]
Haha. It's okay. I was just joking. Let me see if there are easy ways to get fanbox cookies.

**Comment by bluerthanever** [comment]
If you need to download from FANBOX right now, you can do the same as when you try to get cookie string of PIXIV.NET. Copy the value to the cookie named `FANBOXSESSID` for FANBOX.CC, and paste it in config as item `cookiefanbox`

**Comment by Tooskill** [comment]
Now it say's "Error processing FANBOX post: 1347945 ==> Failed to login using OAuth"

**Comment by Tooskill** [comment]
it say's failed to login to qauth 3 times already but i logged in to Fanbox

**Comment by bluerthanever** [comment]
if it's oauth, please make sure you have the correct username and password combination filled in in config.ini. oauth needs those to pass.

**Comment by Tooskill** [comment]
U mean the Correct username and password entered in Pixiv account right ?

**Comment by bluerthanever** [comment]
yep.

I updated the code to obtain FANBOX cookie string in #790 .

**Comment by Tooskill** [comment]
I obtain the Cookie to get to Fanbox and i changed the Password of my account but i can't access to that Oauth

**Comment by Tooskill** [comment]
i even try to log out and log in using that username and pw and i can login

**Comment by bluerthanever** [comment]
urr... I didn't mean for you to change passwords...
I meant:
1. if you are not logged in to fanbox.cc, go to fanbox.cc and log in from there directly
2. get the `FANBOXSESSID` cookie string for fanbox.cc and copy then paste it in config.ini
3. do not log out or log in again in fanbox.cc or pixiv.net, and get the `PHPSESSID` for pixiv.net and copy then paste it in config.ini
4. put the correct combination of username and password in config.ini. if you are using id, and oauth doesn't pass, then try the email account.

**Comment by Tooskill** [comment]
when i try to Log in to Pixiv is used my EMail so am i going to Insert Email to my Username at Config.ini ?

**Comment by bluerthanever** [comment]
yes. just try email first, if it doesn't work, try id.

**Comment by Tooskill** [comment]
wait it log in 
i try fanbox first

**Comment by Tooskill** [comment]
Configuration loaded.
Getting artist information from https://api.fanbox.cc/creator.get?userId=21355272
Using OAuth to retrieve member info for: 21355272
103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。
Error gettting FANBOX artist by id: 21355272 ==> Failed to login using OAuth

still getting this 😢

**Comment by Tooskill** [comment]
the Fanbox login is succesfull just that the problem

**Comment by bluerthanever** [comment]
you are using email as username now, right?
can you try using id now? something like john_123

**Comment by Tooskill** [comment]
you are using email as username now, right? YEs
and how to see my ID's ?

**Comment by Tooskill** [comment]
nvm i get it

**Comment by Tooskill** [comment]
HOLY SHIT WORKING!!!!!!!

**Comment by bluerthanever** [comment]
congratulations....

**Comment by Tooskill** [comment]
can we access restricted post like The PLedge one ?

**Comment by bluerthanever** [comment]
hmm... i guess you are asking if this tool grants you permission to all posts, including those you don't actually have access to on page?
the answer is no. just those that are free or you have access to.

**Comment by Tooskill** [comment]
Thanks for the Answer i also download Kawai Pict and lazy to do it one by one so i got introduced this tools

**Comment by bluerthanever** [comment]
enjoy.
