### ISSUE TITLE
[20150427] Saving broken downloads under final names

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/PixivUtil2#79]
Apparently today there are connection and/or speed issues, and a lot of files are getting broken during the download process. Here is what I'm getting:
<pre>Traceback (most recent call last):
  File "PixivUtil2.py", line 115, in download_image
  File "PixivHelper.pyc", line 504, in downloadImage
  File "mechanize\_response.pyc", line 195, in read
  File "socket.pyc", line 380, in read
  File "httplib.pyc", line 573, in read
  File "socket.pyc", line 380, in read
timeout: timed out
Error at download_image(): (<class 'socket.timeout'>, timeout('timed out',), <tr
aceback object at 0x03DE2B48>) at http://... (9001)
Retrying [2]...
1 2 3 4
Start downloading... Using Referer: http://...
        Found file with different file size, backing up to: ...</pre>
It can go like this again and again. For some images I already have 5-10 broken renamed copies.

I mentioned this problem in another issue: https://github.com/Nandaka/PixivUtil2/issues/77

I suggest to not save the file at all in case the download failed, or specifically mark it in its name (e.g. "failed.image.jpg"), or implement an option for it.

**Comment by reyaz006** [comment]
Now that I noticed this, I'm seeing a fair amount of broken files saved in past. Too bad there is no easy way to batch-detect such broken images.

**Comment by Nandaka** [comment]
for reference: https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L530

**Comment by Nandaka** [comment]
Try: http://www.mediafire.com/download/b04irzy1ij2zgmq/pixivutil20150706-beta3.7z

I do major reorg on the config.ini, so you may need to set the value again after running (remember to backup your file).
