### ISSUE TITLE
Open new version

### ISSUE THREAD

**Issue by pxssy** [Nandaka/PixivUtil2#794]
openNewVersion==> Set to 'False' to disable opening new releases in browser.

Doesn't exist by default in the config (even when using the newer versions), and does not work even when added. Is this a oversight?

**Comment by Nandaka** [comment]
It should be in the config file when it is being recreated.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivConfig.py#L63

**Comment by Nandaka** [comment]
I tested by deleting the old config and rerun, the new option is there.
