### ISSUE TITLE
v20200915 downloadavatar Error 

### ISSUE THREAD

**Issue by aksskl** [Nandaka/PixivUtil2#795]
Upgrading to the latest v20200915  member ids result in an error when downloadavatar=True.

Example Member Id 10292

> Processing Member Id: 10292
> Page
> Member Url: https://www.pixiv.net/ajax/user/10292/profile/all
> Member Name  : ふーみ
> Member Avatar: https://i.pximg.net/user-profile/img/2018/12/05/01/15/26/15093709_d317aa489a6bfbf056842c58fbd5e01c.png
> Member Token : tokitoruo
> Member Background : no_background
> Processing images from 1 to 67 of 67
> Traceback (most recent call last):
>   File "PixivArtistHandler.pyc", line 119, in process_member
>   File "PixivHelper.pyc", line 393, in create_avabg_filename
> IndexError: list index out of range
> Error at process_member(): (<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x14B66CA8>)
> Dumping html to: Error page for member 10292 at page 1.html
> Traceback (most recent call last):
>   File "PixivUtil2.py", line 1146, in main
>   File "PixivUtil2.py", line 849, in main_loop
>   File "PixivUtil2.py", line 201, in menu_download_by_member_id
>   File "PixivArtistHandler.pyc", line 119, in process_member
>   File "PixivHelper.pyc", line 393, in create_avabg_filename
> IndexError: list index out of range

however, another example is member id 11.  Even when downloadavatar=True,  member id 11 processes normally for some reason.

**Comment by Nandaka** [comment]
@byjtje related to https://github.com/Nandaka/PixivUtil2/pull/789 ?

**Comment by Nandaka** [comment]
should be updated in 89f6ec8
