### ISSUE TITLE
Feature Request: Reload blacklists

### ISSUE THREAD

**Issue by mugi-jiichan** [Nandaka/PixivUtil2#797]
Hi,

would it be possible to implement a reload feature for the blacklist files in the same manner as the config.ini is able to be reloaded? Optimal would be to reload the blacklists just when a task is started, once one of the download options is selected.

Currently the user has to exit and restart pixivUtil2 in order for the tool to fetch the blacklist updates.

### Steps to Reproduce

1. Start with blacklist.
2. Edit blacklists.
3. Blacklist edits are ignored.

**Wished behavior:** 
Blacklists to be loaded once the download process starts.

**Actual behavior:**
Blacklists are loaded on start and kept in memory.

### Versions

up to 20200915

**Comment by Nandaka** [comment]
hmm, I can make it to reload the blacklist everytime it reload the main menu (so after completing one task)

**Comment by mugi-jiichan** [comment]
That would be great. Thank you. :)
