### ISSUE TITLE
Error getting Fanbox artist by id (f2) 

### ISSUE THREAD

**Issue by pxssy** [Nandaka/PixivUtil2#798]
https://files.catbox.moe/mvno7v.png

I've already given both cookies, pixiv and fanbox. It says my login is successful in the image but empty username/password? strange. 

Do i need to be subscribed to them to get the free content? is this why its not working?

**Comment by Nandaka** [comment]
checked using latest commit, and I can download just fine. 

Do you fill your authentication data in the config.ini?

![image](https://user-images.githubusercontent.com/836867/93951164-2365d300-fd78-11ea-8fcf-a8eff12dbcab.png)

**Comment by bluerthanever** [comment]
Hmm... even though I am not the boss in this repository, there's a template for issues.
You give us your version, describe the error, tell us the steps of how you run into it, then we can have a clue, otherwise we can do nothing but guess.

**Comment by pxssy** [comment]
> checked using latest commit, and I can download just fine.
> 
> Do you fill your authentication data in the config.ini?
> 
> ![image](https://user-images.githubusercontent.com/836867/93951164-2365d300-fd78-11ea-8fcf-a8eff12dbcab.png)

Both cookies, yes. is username/pw also necessary? Dont have refresh token.

**Comment by bluerthanever** [comment]
>is username/pw also necessary?
yes.
