### ISSUE TITLE
Ugoira not downloading from Fanbox

### ISSUE THREAD

**Issue by DevPaws** [Nandaka/PixivUtil2#799]
### Prerequisites

* [ X] Did you read FAQ section?
* [ X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

My intent is to download Ugoira type posts from fanbox.cc. I am able to download images with no issue. However, Ugoira type posts are only being downloaded as a JPEG. No errors are posted in the command window.

### Steps to Reproduce

1. [First Step]
Set Config Settings as follows:
[FFmpeg]
ffmpeg = ffmpeg
ffmpegcodec = libvpx-vp9
ffmpegext = webm
ffmpegparam = -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p
webpcodec = libwebp
webpparam = -lossless 0 -q:v 90 -loop 0 -vsync 2 -r 999

[Ugoira]
writeugoirainfo = True
createugoira = True
deletezipfile = False
creategif = True
createapng = False
deleteugoira = False
createwebm = True
createwebp = False

2. [Second Step]

Select F1 to download from fanbox

3. [Third Step]
Images begin downloading

**Expected behavior:**

Ugoira type posts to be downloaded and converted. 

**Actual behavior:**

No WebM, ZIP, or GIF files are created.

### Versions
v20200915

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by DevPaws** [comment]
Upon further inspection, the .png file downloaded can be converted using ffmpeg manually.

**Comment by bluerthanever** [comment]
there are ugoira type posts now?

**Comment by bluerthanever** [comment]
if possible could you please provide the json for the post?

**Comment by Nandaka** [comment]
@bluerthanever reference from non-fanbox 
https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L293
https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L297

**Comment by bluerthanever** [comment]
> 
> 
> @bluerthanever reference from non-fanbox
> https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L293
> https://github.com/Nandaka/PixivUtil2/blob/master/PixivImageHandler.py#L297

Thanks. That saves a lot of work.... for I have never used this feature before.

**Comment by bluerthanever** [comment]
Hmm. since no json file is provided, I did some research.
There are **only** 5 types of posts so far: article, image, file, text, video.
Not so sure what kind of situation you ran into, but if the situation is that the creator posts ugoira-like posts with "file" post type, unless the files have distinctive filename formats like extensions or anything, I don't really think it should be written into the codes to check all similar files, so to slow down the process.
But please offer more information so we can have a clue.

**Comment by DevPaws** [comment]
"title":
"type":"image",
"body":
{"text":

Is this the correct one?

**Comment by Nandaka** [comment]
can you follow this step:
1. delete the old pixivutil.log in the pixivutil folder.
2. redownload the fanbox post with ugoira
3. upload the pixivutil.log here.

the full response json should be here, maybe there is additional info for the ugoira animation file there.

**Comment by Butterfly-Dragon** [comment]
i am getting a very similar error 

```
Checking local filename... Getting remote filesize...
Remote filesize = 5.98 MiB (6275656 Bytes)
        File exist! (Identical Size) ==> D:\Downloads\Downloader\Manga\Files\キワメ(╯⊙ ⊱ ⊙╰ ) (3270754) - 84876333_ugoira1920x1080 - ニッ！.ugoira.
processing ugoira to animated gif...
Traceback (most recent call last):
  File "PixivDownloadHandler.pyc", line 97, in download_image
  File "PixivDownloadHandler.pyc", line 324, in handle_ugoira
  File "PixivHelper.pyc", line 821, in ugoira2gif
  File "PixivHelper.pyc", line 887, in ugoira2webm
  File "subprocess.pyc", line 854, in __init__
  File "subprocess.pyc", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
Error at download_image(): (<class 'FileNotFoundError'>, FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None), <traceback object at 0x044D21E8>) at https://i.pximg.net/img-zip-ugoira/img/2020/10/08/11/31/36/84876333_ugoira1920x1080.zip (9001)
Retrying [7]... 1 2
```

**Comment by bluerthanever** [comment]
@Butterfly-Dragon your
Do you run into this error when processing fanbox posts? If so could you provide your log?

**Comment by Butterfly-Dragon** [comment]
That comes up from *every* ugoira, no matter the source.

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5346184/pixivutil.log)

i deleted the log and restarted the last operation i did.

**Comment by Nandaka** [comment]
@Butterfly-Dragon  you have ffmpeg.exe in the application folder?

**Comment by Butterfly-Dragon** [comment]
Uh... no but the config file points at it no problem. Always worked before this very last version.
```
[FFmpeg]
ffmpeg = D:\Downloads\Downloader\!Downloader\ffmpeg.exe
ffmpegcodec = libvpx-vp9
ffmpegext = webm
ffmpegparam = -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p
webpcodec = libwebp
webpparam = -lossless 0 -q:v 90 -loop 0 -vsync 2 -r 999
```
PixivUtil2's folder is `D:\Downloads\Downloader\!Downloader\PixivUtil2`

**Comment by Nandaka** [comment]
hmm, you are converting to animated gif. maybe the path is too long.

> ffmpeg = D:\Downloads\Downloader\!Downloader\ffmpeg.exe

can you shorten it? maybe just put it in D:\ffmpeg.exe

**Comment by Nandaka** [comment]
fyi, I'm using `ffmpeg = ffmpeg` as I place ffmpeg.exe in the same folder directly with the script and run it there from cmd.

**Comment by Butterfly-Dragon** [comment]
just tried this morning.... did not work 😓

**Comment by Nandaka** [comment]
try the beta version and upload the new logging. It should log the command passed to the console to run the ffmpeg.  

> [WinError 2] The system cannot find the file specified

The error message stated it cannot find the file (can be either ffmpeg or the temp file), also maybe you can try to enable these config just to check if the ffmpeg can be executed succesfully.

```
creategif = False
createapng = True
createwebm = True
createwebp = True
```

**Comment by Butterfly-Dragon** [comment]
I did try the beta this morning. it was the one that gave me the error.

The config currently has the opposite true/false of what you gave me now.

Also has delete zip and ugoira as true.

But when it fails the ugoira is there.

I am currently going by memory as i am travelling during work. Sorry.

If this is nit enough i will try and provide more info once back at home

**Comment by Butterfly-Dragon** [comment]
Oookay i tried updating to the latest ffmpeg (the one i was using was... a
couple of years old. I walways forgot to update it because normally all
other python programs use the version downloaded by PIP and that gets
updated whenever i run pip... yours... does not get updated via pip...
because i could not find it there) it now works.
