### ISSUE TITLE
Batch Download with Task Scheduler

### ISSUE THREAD

**Issue by Ramzh** [Nandaka/PixivUtil2#801]
### Description

When launching a .bat script with Task Scheduler, with the following:
`PixivUtil2.exe -s b`

The following error shows up: 
`Cannot found ./batch_job.json in the application folder, see https://github.com/Nandaka/PixivUtil2/wiki/Using-Batch-Job-(Experimental) for example.`

However, when double clicking the .bat file it works fine

Are you able to assist?

**Comment by Nandaka** [comment]
you need to create batch.json and place it in the same folder. See https://github.com/Nandaka/PixivUtil2/wiki/Using-Batch-Job-(Experimental) for example.

**Comment by Ramzh** [comment]
It's already there.
![image](https://user-images.githubusercontent.com/20802073/94557289-456ac400-0256-11eb-9f86-502806a72dd9.png)


I am trying to run the bat. script seen above it from a shortcut on the Desktop via Task Scheduler

**Comment by Nandaka** [comment]
make sure your working directory is correct. In your batch file, ensure you `cd` to the correct folder.

**Comment by Ramzh** [comment]
> 
> 
> make sure your working directory is correct. In your batch file, ensure you `cd` to the correct folder.

I am

`D:\Fanart\Tools\PixivUtil2\PixivUtil2.exe -s b`

**Comment by Nandaka** [comment]
I mean the active working directory, when the task scheduler is running, it might not be the same folder. So rather than trigger the exe directly, you create a batch file (e.g. `run_batch.bat`), and inside the batch file, you do `cd` and then run the application.

``` batch
D:
cd D:\Fanart\Tools\PixivUtil2
D:\Fanart\Tools\PixivUtil2\PixivUtil2.exe -s b
```

**Comment by Ramzh** [comment]
> 
> 
> I mean the active working directory, when the task scheduler is running, it might not be the same folder. So rather than trigger the exe directly, you create a batch file (e.g. `run_batch.bat`), and inside the batch file, you do `cd` and then run the application.
> 
> ```batchfile
> D:
> cd D:\Fanart\Tools\PixivUtil2
> D:\Fanart\Tools\PixivUtil2\PixivUtil2.exe -s b
> ```

Unfortunately still having the same issue:
![image](https://user-images.githubusercontent.com/20802073/94560227-3dad1e80-025a-11eb-820e-ae3c950c50dd.png)

Do you personally schedule your downloads?

**Comment by Ramzh** [comment]
nvm got it
missing the D:

Thanks so much for this!
