### ISSUE TITLE
[Suggestion] Use ffmpeg for gif creation

### ISSUE THREAD

**Issue by BinaryMan101** [Nandaka/PixivUtil2#802]
### Prerequisites

* [ Y] Did you read FAQ section?
* [ Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

The gifs currently created by PixivUtil2 are usually bloated and suffer from bad banding. Since the apng conversion now uses ffmpeg, I thought maybe it could be used for the gif conversion as well. Here's the command I use with ffmpeg that gives me consistently good results both in size optimization and color quality:

`ffmpeg -i <input> -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" <output>`

**Comment by Nandaka** [comment]
should be in the latest releases https://github.com/Nandaka/PixivUtil2/releases
