### ISSUE TITLE
[Feature request] Fanbox functionality for multiple IDs. Request for fanboxlist like option 4

### ISSUE THREAD

**Issue by pxssy** [Nandaka/PixivUtil2#804]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

limited fanbox functionality for multiple profile IDs. Not sure if i've exhausted all the possible means, but f2 does not work like 1, where you can dump in  a string of IDs separated by spaces. batch_job doesn't appear to support fanbox options. f4 is possible but manually following every single one on the list is very tedious. 

### Steps to Reproduce

[How option 1 usually works](https://files.catbox.moe/97kl5h.png) Here no artists have ID 1,2,3 so its skipped, nothing wrong here.

[How option f2 is working currently](https://sg.catbox.moe/tgv8mz.png) As you can see, it feeds the input string raw as-is directly into api/url, and not separately as it should in 2. If that's even its intended behavior. 

If possible, can there be a feature that works similarly to option 4, where it takes fanbox ID directly from a fanboxlist.txt?

### Versions

v20200915

**Comment by bluerthanever** [comment]
Doesn't seem too much of a problem. But I have 2 questions:
1. You mentioned option f2, and took option 1 as an example, but you requested a feature like option 4. Just to be clear, do you want a new option like option 4 or want option f2 to be like option 1 or both?
2. I think option 4 is actually more complicated than just "processing from list". If you want a new option like 4, do you want it to be exactly the same, that if you set `processfromdb` to `True`, all processed member ids would be stored in database and be used every time? Also the custom path for each member id, do you also need that?

I think overall making option f2 more like option 1 is easier, and simpler -- no need to add extra options or modify the database.

**Comment by pxssy** [comment]
Option 1 has a parser that first separates the string of IDs into individual job tasks, then sequentially does them. 

It would appear that f2 is missing this parser, f2 only takes in 1 ID and does 1 job. I'm not well versed in coding but it should be able to copy paste the infrastructure from option 1 to first parse the string of IDs? 

In any case, There appears to be a limit of 4096 characters (seems to be bash dependent ) that limits how much IDs can be inputed into option 1. I haven't used option 1 in a long while since option 4 bypasses this character limit.

For me I've never really enabled 'processfromdb'. How i look at option 4 is akin to an option 1 with ability to input from list.txt instead of a string of IDs (with limitations mentioned above). It doesn't really bother me if its not possible to implement 'processfromdb'  

Output can just copy the existing one for fanbox. 

In any case, an analog of option 4 for fanbox more preferable, but i wont oppose to an upgrade of option f2, since right now f2 is a very manual process to just do 1 job one at a time.

**Comment by bluerthanever** [comment]
Hmm. Got your point. I think I will do both, but make the new option simple first... no processing from db and custom path or so.
Please wait for the implementation.

**Comment by pxssy** [comment]
If possible, It'd be great if the path to the list this new fanbox option takes ID from can be configurable from config.ini.

Like so its possible to choose have both option 1 and this new option  input from one list.txt, or have 2 independent txt inputs.

**Comment by bluerthanever** [comment]
Okay. So the two options could share one list file based on the configuration, right?

**Comment by Nandaka** [comment]
any reason not to use `f1 - Download from supporting list (FANBOX)` or `f4 - Download from following list (FANBOX)`?

You need to follow/support to be able to download all available posts, right?

**Comment by bluerthanever** [comment]
like multiple creators that you are not supporting but they post free contents, or that you unsubscribe before the end of the month, which makes you not supporting but still able to view the contents...

**Comment by pxssy** [comment]
>You need to follow/support to be able to download all available posts, right?

I was curious about this as well. I've tested a few IDs and it seems like it works. 

Apparently some artists have been trying to avoid the censorship in the public pixiv gallery by posting what would've been on their profile, onto fanbox but still free. Less traffic = less people reporting i guess?

**Comment by Nandaka** [comment]
should be in the latest releases https://github.com/Nandaka/PixivUtil2/releases
