### ISSUE TITLE
20201009-beta1 Mode 1 download problem

### ISSUE THREAD

**Issue by ee092884** [Nandaka/PixivUtil2#811]
Input: 1
Member ids: 35161227
Start Page (default=1):
End Page (default= 0, 0 for no limit):
Include Pixiv Sketch [y/n]?
Member IDs: [35161227]
Reading D:\D\Downloads\1\config.ini ...
Configuration loaded.
Processing Member Id: 35161227
Page
Member Url: https://www.pixiv.net/ajax/user/35161227/profile/all
Member Name  : 貓介
Member Avatar: https://i.pximg.net/user-profile/img/2018/10/14/20/54/54/14904104_26d864922971cabac46acd75728f69fb.jpg
Member Token : user_gzen3274
Member Background : no_background
Processing images from 1 to 6 of 6
#1
Processing Image Id: 71183250
Already downloaded in DB: 71183250
#1
Processing Image Id: 71183220
Already downloaded in DB: 71183220
#1
Processing Image Id: 71182542
Already downloaded in DB: 71182542
#1
Processing Image Id: 71182425
Already downloaded in DB: 71182425
#1
Processing Image Id: 71182283
Already downloaded in DB: 71182283
#1
Processing Image Id: 71182227
Already downloaded in DB: 71182227
Last Page
Member_id: 35161227 completed: last image_id: 71182227
Member Url: https://www.pixiv.net/ajax/user/35161227/profile/all
Reading D:\D\Downloads\1\config.ini ...
Configuration loaded.
Processing Artist Id: user_gzen3274
Traceback (most recent call last):
  File "PixivBrowserFactory.pyc", line 240, in getPixivPage
  File "PixivBrowserFactory.pyc", line 206, in open_with_retry
  File "mechanize\_mechanize.pyc", line 253, in open
  File "mechanize\_mechanize.pyc", line 309, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PixivSketchHandler.pyc", line 42, in process_sketch_artists
  File "PixivBrowserFactory.pyc", line 998, in sketch_get_posts_by_artist_id
  File "PixivBrowserFactory.pyc", line 249, in getPixivPage
PixivException.PixivException: 9005 Failed to get page: https://sketch.pixiv.net/api/users/@user_gzen3274 => HTTP Error 404: Not Found, hasDumpPage=N, pageData=None
Error at process_sketch_artists(): user_gzen3274
Exception: (<class 'PixivException.PixivException'>, PixivException('Failed to get page: https://sketch.pixiv.net/api/users/@user_gzen3274 => HTTP Error 404: Not Found'), <traceback object at 0x046A1F08>)

Is this normal?
I think there is more than one ID with this problem
The code of traceback object at is different every time
Sketch will be wrong whether it is y or n

[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5361439/pixivutil.log)

**Comment by Nandaka** [comment]
updated the code to parse input parameter.
404 is normal if the artist doesn't have PixivSketch

**Comment by ee092884** [comment]
> 更新了代碼以解析輸入參數。
> 如果美術師沒有PixivSketch，則404正常

OK~

**Comment by ee092884** [comment]
> updated the code to parse input parameter.
> 404 is normal if the artist doesn't have PixivSketch

OK~
