### ISSUE TITLE
Pixiv User ID may differ from Pixiv Sketch User ID

### ISSUE THREAD

**Issue by jwshields** [Nandaka/PixivUtil2#812]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Version: v20201009-beta1

Problem: Pixiv User ID may differ from Pixiv Sketch User ID

I've encountered this issue with a few artists but wasn't able to definitively capture it for more than one of them.
But the essence of it is that the Pixiv UID _MAY_ differ from the Sketch UID.
I'm not sure what would cause this situation, nor how often it would crop up; but it definitely can wreak havoc when somebody is using the `%member_id%` field in filenames.
For the most part, it seems that the IDs are the same for most users, but some seem to differ.

### Steps to Reproduce

1. Run PixivUtil2
2. Option 1
3. Enter UID
4. Select `y` to download sketches

**Expected behavior:** Sketches download into proper places

**Actual behavior:** Sketches download into proper places (Although, logically they are improper)
 
#### Note: I guess what the problem here is sits on defining what "proper place" means for the `%member_id%`

----

Opening this issue because I posted a comment in https://github.com/Nandaka/PixivUtil2/issues/793#issuecomment-706663174 that would have been better off as a new issue. The comment and entire issue thread provide extra context.

----
Example user:
Pixiv ID: 41141316 / Sketch ID: 37963593

![image](https://user-images.githubusercontent.com/7400556/95686801-299be200-0bb5-11eb-9dea-61328fed4ab4.png)

----

### Proposal
I think there may be a few different solutions here, but I may be missing some of the background. Open to thoughts on this. I am willing to take this problem on and submit a PR if wanted.

Ideas:
1. When downloading Sketches, "_always_" override the Sketch UID for what is given as the Pixiv UID if the two differ (such as what is given in option 1 - "download by member_id")
2. Expose a new option in config.ini which breaks out Sketches into its own category, or a new option in the `[Filename]` category to allow for specifying Sketch filename formats
3. Expose new variable for filename syntaxing, (This may be also combined with option 2?) - `%sketch_member_id%` (or `%pixiv_member_id%` in the `[Sketches]` config block?

I am partial to option 2, as it is less obfuscated & hacky.
Thoughts?

**Comment by Nandaka** [comment]
should be in latest beta
