### ISSUE TITLE
[Feature Request] More filters

### ISSUE THREAD

**Issue by Tarried** [Nandaka/PixivUtil2#813]
Hi,

In much the same vein as there are options for maximum and minimum file-size, can we have more options on which files to include/exclude? For example:

A setting to disable downloading ugoira, 
or exclude .jpg file downloading, 
or works before/after a certain cutoff date. 

Please implement these however they make sense to you, or whatever is easiest.

Much love,

**Comment by Nandaka** [comment]
if you uses batch job feature, the filtering by extension is already implemented, see wiki here: https://github.com/Nandaka/PixivUtil2/wiki/Using-Batch-Job-(Experimental)#about-option

**Comment by Tarried** [comment]
Thank you for implementing that! I was not keeping abreast of recent updates. On the other hand, if you allow bug reports on experimental features, I'd like to add one here. 


Regarding the ExtensionFilter, it doesn't seem to work. Even using the example in your link, it returns with:

Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 161, in process_image
  File "PixivHelper.pyc", line 1094, in get_extension_from_url
AttributeError: module 'urllib' has no attribute 'urlparse'
Error at process_image(): 84834644
Exception: (<class 'AttributeError'>, AttributeError("module 'urllib' has no attribute 'urlparse'"), <traceback object at 0x03B74B68>)

I'm not sure what's causing that, maybe a urllib package update broke that line in PixivHelper.pyc


While I have your attention, I want to report another thing finding. It seems like the start_date & end_date name:value pairs don't seem to do anything, regardless of what value I enter. My understanding is that they would restrict the files downloaded by submission date.  Again, this was tested using your example (the last one, after removing the bookmark restriction).

**Comment by bluerthanever** [comment]
![20201015014028](https://user-images.githubusercontent.com/17560146/96025255-74547d00-0e87-11eb-89a5-c1735a63a4d0.png)
I managed to saved the page retrieved in `doLogin()`, and it turned out as the page above shows.
Looks like they put more effort in anti-scraper.

**Comment by Nandaka** [comment]
ah, looks like it was moved to urllib.parse.urlparse.

for start/end date, it is only for specific option, not all. Check the readme.md for which option can uses start/end date.

**Comment by Tarried** [comment]
Thanks for fixing this in the latest release. If it's not too much trouble, can you update the readme/examples for extensionFilter at: https://github.com/Nandaka/PixivUtil2/wiki/Using-Batch-Job-(Experimental)

It is misleading; nowhere is it explained that a regex string is expected. Even the provided example does not work, unless you precede the extensions with .* (and ideally succeeded by $).
