### ISSUE TITLE
[QUESTION] How to download multiple artists at once

### ISSUE THREAD

**Issue by SIREN587** [Nandaka/PixivUtil2#815]
Not a bug but more of a question. Can i put in a txt somehow all the artist id's i like and download all of them at once?

Can something similar happen with tags? 

Thank you

**Comment by pxssy** [comment]
Put all of the artist ids you want to download into a txt, each id separated by a line, name it list.txt 

ensure `uselist = True` and `downloadlistdirectory = <where you want your list to be>`

use option 4.

**Comment by SIREN587** [comment]
Thanks px, can i also put multiple tags in a txt?

**Comment by Nandaka** [comment]
you can refer to https://github.com/Nandaka/PixivUtil2#listtxt-format (or check the readme.md)
