### ISSUE TITLE
Expecting Value Error (getMemberInfoWhitecube using webrpc)

### ISSUE THREAD

**Issue by OwariSync** [Nandaka/PixivUtil2#816]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

" Expecting value: line 1 column 1 (char 0)
Stack Trace: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback object at 0x03EF0648>)
Traceback (most recent call last):
  File "PixivImageHandler.pyc", line 76, in process_image
  File "PixivBrowserFactory.pyc", line 591, in getImagePage
  File "PixivBrowserFactory.pyc", line 620, in getMemberInfoWhitecube
  File "json\__init__.pyc", line 357, in loads
  File "json\decoder.pyc", line 337, in decode
  File "json\decoder.pyc", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

### Steps to Reproduce

1. Updated PixivUtil2 to 20201006
2. Updated cookie/log in.
3. error occurs when trying to download any image.

**Comment by Phenrei** [comment]
Using http debugging, it appears the request to "https://www.pixiv.net/rpc/get_work.php?id={image id}" is first getting a 302 response and sending the browser to "/?return_to=%2Frpc%2Fget_work.php%3Fid%3D{image id}" which appears to be missing a key "__cf_bm" cookie as it returns a 301 to the same URL while adding said cookie, which then returns an empty 200 response. 

The "return_to" page, if loaded in a browser, does send you to the /rpc/ url but notably the cookie there does include the user id prefix which we had to remove to get past the login issue. A request to the /rpc/ url directly in my browser which has the complete session cookie does not redirect at all. It looks like the cookie workaround is causing issues down the pipe. Not sure if the correct solution is reworking the cookie once you get past the first step (as that may continue to cause login problems) or to fix those requests bouncing around somehow.

**Comment by vernaze** [comment]
I have the same problem when trying to download with imageID.

https://github.com/Nandaka/PixivUtil2/issues/505#issuecomment-667497295

`dologin()` returns no error with following this fix and removing userID from my PHPSESSID,
`getMemberInfoWhitecube()` returns the same JSONDecodeError.

As mentioned before the request on `getMemberInfoWhitecube()` is now redirected and the destination requires the complete cookies.
I tried sending some requests to both "https://www.pixiv.net/rpc/get_work.php?id={image id}" and ""http(s)://www.pixiv.net/?return_to=%2Frpc%2Fget_work.php%3Fid%3D{image id}" with complete / incomplete cookies (including userID or not),
or loading config with complete cookies before sending request in `getBrowser()`,
all did not help.

**Comment by Nandaka** [comment]
hmm, weird. I tried with latest commit and I can download just fine. Also ensure you are using latest cookie format (no underscore), see #814

**Comment by vernaze** [comment]
Thanks, now working perfectly.

In my situation, this error came from my poor failure.
I have certainly changed password, re-logined, confirmed to use the latest cookies,
but completely forgotten to add new password on config.ini.
changing password on Chrome again and use both the new cookie and password just go fine.

**Comment by ApoOriel** [comment]
had the same problem, i changed my password and the cookie in ini file multiple times but it seems i screwed up somehow but now it´s woking again.

**Comment by NHOrus** [comment]
Sadly, change of password and cookie didn't do anything for me.

**Comment by Phenrei** [comment]
Per #814, had to use a completely different password format than the old one with more complexity (included a symbol where the old one did not, most notably) and got a working cookie, and downloads are working.

**Comment by John-Titor** [comment]
Seeing the same problem (after adjusting cookie).  Note that I'm also seeing:

```
Unable to get User Id, please check your cookie.
Premium User: False.
```

where I am in fact a Premium user.

**Comment by Nandaka** [comment]
because it cannot verify the login, ensure the session doesn't have `_` (new format). I think pixiv still doing upgrade and expect some breaking changes.

**Comment by John-Titor** [comment]
The "new format" cookie from a regular page works for login, but gives the above problem.

I used the suggestion to get the cookie from the "password changed" page, and that appears to be working - both for login and for image download. I didn't have to change the actual password; put the same value in both "old" and "new" fields.

**Comment by Nandaka** [comment]
I'm not a premium user, but it should be able to parse your user id.
![image](https://user-images.githubusercontent.com/836867/96218747-f04de280-0fb7-11eb-83de-06eba42e4f4d.png)

It works by parsing specific string from the main page.
https://github.com/Nandaka/PixivUtil2/blob/f14ab06342538cf6056763c768fe30f7c1579ad2/PixivBrowserFactory.py#L499
