### ISSUE TITLE
Error at processing Artist Info:

### ISSUE THREAD

**Issue by ApoOriel** [Nandaka/PixivUtil2#817]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

The Error i get when i start downloading from a member (i can log in without problems):

Error at processing Artist Info: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback object at 0x041607A8>)

I tried changing my password and refreshed the cookies in the config.ini file.

**Comment by Nandaka** [comment]
duplicate with #816 ?

**Comment by ApoOriel** [comment]
> 
> 
> duplicate with #816 ?

oh yes, it´s the same error my bad and thanks for your work! I will close this and look at #816
