### ISSUE TITLE
Gif maker Not working [FFMPEG is required now]

### ISSUE THREAD

**Issue by BBandit18** [Nandaka/PixivUtil2#818]
### Prerequisites

* [x] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[I can't seem to create gifs]

### Steps to Reproduce

1. Download from bookmarked images
2. Followed the steps
3. began the process

**Expected behavior:** Convert Zip files to Gifs

**Actual behavior:** 
It keeps giving me this error
![Screenshot 2020-10-14 202915](https://user-images.githubusercontent.com/19337517/96062732-0b0b4480-0e5c-11eb-82c5-b063affe5ada.png)

### Versions
v20201009-beta1
You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by jwshields** [comment]
Could you show the `[FFmpeg]` section of your config.ini file?
First guess is that you do not have ffmpeg installed on your system, in your PATH, set in your configuration file, or a combo of those three.

**Comment by Nandaka** [comment]
also remember to update the ffmpeg to the latest version

**Comment by BBandit18** [comment]
I never had this problem with the previous update

**Comment by Nandaka** [comment]
see the changelog: Implement #802: use ffmpeg for converting to gif.

**Comment by BBandit18** [comment]
How do I implement #802

**Comment by Nandaka** [comment]
it is already in the latest beta releases, you just need to download the ffmpeg.exe and place it inside the pixivutil folder.

get executable files from https://ffmpeg.org/download.html

**Comment by BBandit18** [comment]
I downloaded it but it still won't work, I really don't know what i'm doing
![Screenshot 2020-10-17 224747](https://user-images.githubusercontent.com/19337517/96358260-d650f480-10ca-11eb-96eb-ffd99027db7d.png)

**Comment by Nandaka** [comment]
can you upload the log file? looks like it cannot find the ffmpeg.exe location.

1. delete the old pixivutil.log.
2. rerun and replicate the error.
3. upload the generated log file here.

**Comment by BBandit18** [comment]
Okay I downloaded the newest beta and Gif Maker still doesn't work
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5397724/pixivutil.log)

**Comment by Nandaka** [comment]
uhh, check your `config.ini` in  F:\pixivutil20201018-beta3\config.ini? I don't see the logging for gif conversion, looks like it is not enabled when you run it due to new configuration.

**Comment by BBandit18** [comment]
i'm just not getting this, I can't find no "ffmpeg.exe" I'll just wait till you complete the thing sorry for wasting you time

**Comment by Nandaka** [comment]
> it is already in the latest beta releases, you just need to download the ffmpeg.exe and place it inside the pixivutil folder.
> 
> get executable files from https://ffmpeg.org/download.html

uuuh, you can get the ffmpeg.exe from link above.... I think the instruction quite clear.

**Comment by BBandit18** [comment]
It really wasn't all it gave me was files not an Exe

**Comment by jwshields** [comment]
The problem here isn't a failing of PixivUtil2, it's that you don't have the pre-reqs to run it in the way you're intended.


The link contains the needed executables...
And there are instructions on the web; if you use your favorite search engine to look for "Install FFMPEG on Windows" - it should bring up a few results that show you how to add the downloaded files to your path and enable command line usage of ffmpeg
![image](https://user-images.githubusercontent.com/7400556/96474983-4ef9a300-11e8-11eb-9b3f-2b8bba219a75.png)

**Comment by BBandit18** [comment]
Thank you @jwshields for clarifying that

**Comment by BBandit18** [comment]
Welp that didn't work thanks for the help @jwshields but this is pointless I'll just wait for the final build
