### ISSUE TITLE
Managed to login, unable to download. [JSONDecodeError]

### ISSUE THREAD

**Issue by pxssy** [Nandaka/PixivUtil2#819]
### Prerequisites

* [Y] Did you read FAQ section?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Used the raw string of the cookie without the user_id like #814 , managed to login, but can't download anything. 

`Image Id: 84979506

Processing Image Id: 84979506

Image ID (84979506): Expecting value: line 1 column 1 (char 0)

Stack Trace: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback 
object at 0x010D2788>)

Traceback (most recent call last):

  File "PixivImageHandler.pyc", line 78, in process_image

  File "PixivBrowserFactory.pyc", line 600, in getImagePage

  File "PixivBrowserFactory.pyc", line 629, in getMemberInfoWhitecube

  File "json\__init__.pyc", line 357, in loads

  File "json\decoder.pyc", line 337, in decode

  File "json\decoder.pyc", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Image #98

Image Id: 84979357

Processing Image Id: 84979357

Image ID (84979357): Expecting value: line 1 column 1 (char 0)

Stack Trace: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), <traceback 
object at 0x04358808>)

Traceback (most recent call last):

  File "PixivImageHandler.pyc", line 78, in process_image

  File "PixivBrowserFactory.pyc", line 600, in getImagePage

  File "PixivBrowserFactory.pyc", line 629, in getMemberInfoWhitecube

  File "json\__init__.pyc", line 357, in loads

  File "json\decoder.pyc", line 337, in decode

  File "json\decoder.pyc", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

### Steps to Reproduce

batch job, used to work. 

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

From what i can see, nothing actually was downloaded.

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

v20201009-beta1

**Comment by Nandaka** [comment]
same issue with #816 ? I cannot replicate the issue, as I can call the 'getMemberInfoWhitecube()' call without issue.

also, ensure the username/password is configured in config.ini?

**Comment by MrDonaldoWorking** [comment]
I have also managed to log in, but caught an error when trying to download from image bookmark.

Error at process_image_bookmark(): (<class 'KeyError'>, KeyError('illustId'), <traceback object at 0x7fa71eee0d48>) 
Traceback (most recent call last):
  File "PixivUtil2.py", line 1281, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args, options)
  File "PixivUtil2.py", line 991, in main_loop
    menu_download_from_online_image_bookmark(op_is_valid, args, options)
  File "PixivUtil2.py", line 527, in menu_download_from_online_image_bookmark
    sorting=sorting)
  File "PixivBookmarkHandler.py", line 70, in process_image_bookmark
    totalList.extend(get_image_bookmark(caller, config, False, start_page, end_page, tag, sorting))
  File "PixivBookmarkHandler.py", line 342, in get_image_bookmark
    bookmarks = PixivBookmark.parseImageBookmark(page_str)
  File "PixivBookmark.py", line 64, in parseImageBookmark
    imageList.append(int(work["illustId"]))
KeyError: 'illustId'
press enter to exit.

I'm not sure but Pixiv might change the key `illustId` to `id` at https://www.pixiv.net/ajax/user/<USER_ID>/illusts/bookmarks?tag=&offset=0&limit=48&rest=show
So by changing `imageList.append(int(work["illustId"]))` to `imageList.append(int(work["id"]))` the script started to download successfully from the site.

Please change that in your repository.

**Comment by fireattack** [comment]
> Used the raw string of the cookie without the user_id like #814 , managed to login, but can't download anything.

This doesn't actually work. That's not a "proper" cookie and can only be used to login, any download will error out.

Try to follow other methods mentioned in that thread (change your password and copy the  cookie upon the "password changed" page method works here).

**Comment by Nandaka** [comment]
@MrDonaldoWorking can you provide the sample query/user id, so we can verify it? I think pixiv uses noSql and store the full json document, so it might still have old and new structure mixed in.

**Comment by split-n** [comment]
Same here.  I use new style cookie from password change page.
 
Here's sample json on `GET https://www.pixiv.net/ajax/user/9999999/illusts/bookmarks?tag=&offset=0&limit=48&rest=show`. (other info is truncated, my ID is masked by 9999999)

```json
{
  "error": false,
  "message": "",
  "body": {
    "works": [
      {
        "id": "74487462",
        "title": "唯ちゃん誕生日おめでとう",
        "illustType": 0,
        "xRestrict": 0,
        "restrict": 0,
        "sl": 2,
        "url": "https://i.pximg.net/c/250x250_80_a2/img-master/img/2019/05/01/11/25/06/74487462_p0_square1200.jpg",
        "description": "",
        "tags": [
          "ゆゆ式",
          "櫟井唯",
          "野々原ゆずこ",
          "日向縁",
          "誕生日",
          "ゆゆ式300users入り"
        ],
        "userId": "7057234",
        "userName": "ウミロク",
        "width": 1228,
        "height": 868,
        "pageCount": 1,
        "isBookmarkable": true,
        "bookmarkData": {
          "id": "9999999999",
          "private": false
        },
        "alt": "#ゆゆ式 唯ちゃん誕生日おめでとう - ウミロクのイラスト",
        "isAdContainer": false,
        "titleCaptionTranslation": {
          "workTitle": "",
          "workCaption": ""
        },
        "createDate": "2019-05-01T11:25:06+09:00",
        "updateDate": "2019-05-01T11:25:06+09:00",
        "isUnlisted": false,
        "profileImageUrl": "https://i.pximg.net/user-profile/img/2020/08/14/19/40/25/19179429_4bd3f6c406b3ec16e56247f2f2178a0d_50.png"
      }
    ]
  }
}
```

**Comment by Nandaka** [comment]
for bookmark related, try https://github.com/Nandaka/PixivUtil2/releases/tag/v20201017-beta2

**Comment by Nandaka** [comment]
@pxssy can you try with latest beta release and option 2, ok from my pc.

**Comment by split-n** [comment]
It works for me. thanks.

**Comment by pxssy** [comment]
Managed to get v20201009-beta1 working finally, reading the comments from #814 changing password and not logging out will generate the new format cookie. 

Bit tedious but it works now.
