### ISSUE TITLE
Option to write tags to image metadata?

### ISSUE THREAD

**Issue by Lodottis** [Nandaka/PixivUtil2#82]
Is it possible to get an option to write tags, possibly comments and artist to the image metadata somehow? Possibly through exif or xmp? Maybe write them to a file that can be read and written post-download by [exiftool](http://www.sno.phy.queensu.ca/~phil/exiftool/)

**Comment by Nandaka** [comment]
nope, it will change the filesize and break the duplicated/updated file detection.

It already have the option to write the tags, see readme.txt

```
writeimageinfo  ==> set to 'True' to export the image information to text file.
                    The filename is following the image filename + .txt.
```
