### ISSUE TITLE
Issues with Fanbox commands on 20201006 release, but still works fine in 20200726 release

### ISSUE THREAD

**Issue by Zekira** [Nandaka/PixivUtil2#820]
### Prerequisites

* [y] Did you read FAQ section? **Yes**
* [y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? **Yes**

### Description

I've only tested this using the f2 feature so far, not sure if other commands are also having any issues.

Inputting the artist user ID (e.g. _kemoribbon_ in https://www.fanbox.cc/@kemoribbon/ ) doesn't work anymore, says "ID: *name* is not valid". have to look for the numeric ID and input it.
![image](https://user-images.githubusercontent.com/11051413/96175638-c10a8780-0f5d-11eb-8c71-3d73bf1a41f4.png)

End Page of blank doesn't seem to default to no-limit anymore, program just throws an error.
![image](https://user-images.githubusercontent.com/11051413/96175685-cff13a00-0f5d-11eb-9332-bbe76c6118b5.png)

And even if you put all the fields correctly, you get this strange error instead.
![image](https://user-images.githubusercontent.com/11051413/96175838-0b8c0400-0f5e-11eb-8617-444e2ff10772.png)

This is also still currently working fine in 20200726 release, so I am using that version in the meantime.
![image](https://user-images.githubusercontent.com/11051413/96175937-30807700-0f5e-11eb-9b5b-a86a5f7e2779.png)

### Steps to Reproduce

1. Login properly on pixivutil with fanbox
2. Use f2 option to download with artist ID
3. Try inputting artist user ID name, doesn't work - problem 1
4. Input artist numeric ID instead
5. Don't input anything for max page, error thrown - problem 2
6. Complete the fields normally, error still thrown - problem 3
7. Revert back to 20200726 for it to work again

**Expected behavior:** That these functions work like the 20200726 release

**Actual behavior:** Errors thrown around.

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by ee092884** [comment]
I can download normally
I suggest you to update the cookies
You can find it from here https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-709321016
Or use version 20201009-beta1

![image](https://user-images.githubusercontent.com/39590282/96192932-a3e3b200-0f79-11eb-8a1d-20b85fc59c7e.png)
![image](https://user-images.githubusercontent.com/39590282/96193120-12287480-0f7a-11eb-872d-d75a69a1ec50.png)

**Comment by Zekira** [comment]
> I can download normally
> I suggest you to update the cookies
> You can find it from here [#814 (comment)](https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-709321016)
> Or use version 20201009-beta1
> 
> ![image](https://user-images.githubusercontent.com/39590282/96192932-a3e3b200-0f79-11eb-8a1d-20b85fc59c7e.png)
> ![image](https://user-images.githubusercontent.com/39590282/96193120-12287480-0f7a-11eb-872d-d75a69a1ec50.png)

OK, so it does seem like the 20201009-beta1 is working fine. Changelog only says that it only merged a fix for an End Page bug, but it may also have affected other fanbox stuff in general.

Thanks.
