### ISSUE TITLE
"Include Pixiv Sketch [y/n]? n" not working

### ISSUE THREAD

**Issue by SushYkn** [Nandaka/PixivUtil2#821]
### Description
While downloading from multiple artists (without using a list.txt file) I input "n" when asked "Include pixiv sketch [y/n]?" but it didn't seem to work, as a folder for an artist's pixiv sketch uploads were also downloaded.

### Steps to Reproduce
1. Input member ID(s)
2. Input "n" when asked "Include pixiv sketch [y/n]?"

**Expected behavior:**
Artist's pixiv sketch uploads to not be downloaded.

**Actual behavior:**
Artist's pixiv sketch uploads were downloaded.

### Versions
pixivutil20201006

Is there some way to set "Include pixiv sketch [y/n]?" to false via config or something so I don't have to enter "n" everytime I download an artist's works?

**Comment by Nandaka** [comment]
should be already fixed in #811

**Comment by SushYkn** [comment]
> should be already fixed in #811

I'm sorry but what do I do? Do I download the beta version?

**Comment by Nandaka** [comment]
I'll publish another beta this weekend.

**Comment by Nandaka** [comment]
should be in the latest beta releases
