### ISSUE TITLE
cannot download from bookmarks (KeyError at process_image_bookmark)

### ISSUE THREAD

**Issue by zane49er2** [Nandaka/PixivUtil2#822]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I routinely download my bookmarks list, but today it failed.

### Steps to Reproduce

1. log in using username password and cookie from file
2. use option 6 with all default settings except sort by date
3. obtain error:
4. change password, update pass, cookie, userAgent, update to latest stable release
5. get same error

```
Importing image bookmarks...
Importing user's bookmarked image from page 1
Source URL: https://www.pixiv.net/ajax/user/XXXXXXXX/illusts/bookmarks?tag=&offset=0&limit=48&rest=show
Error at process_image_bookmark(): (<class 'KeyError'>, KeyError('illustId'), <traceback object at 0x044FB988>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1252, in main
  File "PixivUtil2.py", line 964, in main_loop
  File "PixivUtil2.py", line 520, in menu_download_from_online_image_bookmark
  File "PixivBookmarkHandler.pyc", line 73, in process_image_bookmark
  File "PixivBookmarkHandler.pyc", line 342, in get_image_bookmark
  File "PixivBookmark.pyc", line 64, in parseImageBookmark
KeyError: 'illustId'
```

### Versions
20200524
20201006

**Comment by Nandaka** [comment]
I think reported in https://github.com/Nandaka/PixivUtil2/issues/819#issuecomment-709377532.

can you provide the sample id for testing?

**Comment by zane49er2** [comment]
It doesn't seem to matter what image I attempt to download. Also, it fails when reading the list to schedule downloads, not when actually getting images.
