### ISSUE TITLE
Successfully logged in, unable to download

### ISSUE THREAD

**Issue by feiguizz** [Nandaka/PixivUtil2#824]
### Prerequisites

* [ ] Did you read FAQ section?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

I tried to reset my password and update the cookies, though I successfully logged in and I still cannot proceed the downloading.
The following information shown:

Traceback (most recent call last):
  File "PixivUtil2.py", line 1252, in main
  File "PixivUtil2.py", line 993, in main_loop
  File "PixivUtil2.py", line 672, in menu_fanbox_download_from_list
ValueError: invalid literal for int() with base 10: ''
press enter to exit.

**Comment by Nandaka** [comment]
try latest beta releases

**Comment by theChrisliebaer** [comment]
Not sure which is the proper issue, since this appears to be a duplicate but I want to confirm that the issue persists with the current `PixivDownloader2 version 20201017-beta2` release. The line numbers have shifted though, as is expected.

```
pixivutil2.exe -x -c config.ini -s 6 y
PixivDownloader2 version 20201017-beta2
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading config.ini ...
Configuration loaded.
Using custom DB Path: db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: redacted
Trying to log in with saved cookie
Login successful.
My User Id: redacted.
Premium User: False.
Traceback (most recent call last):
  File "PixivUtil2.py", line 1281, in main
  File "PixivUtil2.py", line 991, in main_loop
  File "PixivUtil2.py", line 494, in menu_download_from_online_image_bookmark
IndexError: list index out of range
```

**Comment by Nandaka** [comment]
It is because the command line parameter is changed (see readme.md), use `-p [y|n|o]` switch for the private bookmark, but it does have bug for the tag parsing.

```
                        6 - Download from image bookmark
                            (required: -p BOOKMARK_FLAG [y/n/o] for private bookmark
                             optional: --sp=START_PAGE, and --ep=END_PAGE, and followed with tag)
```

**Comment by theChrisliebaer** [comment]
Thanks,

I can confirm that that using the CLI menu does indeed slove the problem. However the `-p` or ``--bookmark_flag` option don't appear to work, which actually appears to be a new issue. Regardless of where I place the flag, it always get the prompt.

```
pixivutil2.exe -x -c config.ini -s 6 -p y
pixivutil2.exe -x -c config.ini --bookmark_flag=y -s 6
pixivutil2.exe -x -c config.ini -p y -s 6
pixivutil2.exe -x -c config.ini -s 6 --bookmark_flag=y
```
Always results in the interactive menu asking about private bookmarks.
```
pixivutil2.exe -x -c config.ini -s 6 -p y
PixivDownloader2 version 20201018-beta3
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
Reading config.ini ...
Configuration loaded.
Using custom DB Path: db.sqlite
Creating database... done.
Only process members where the last update is >= 7 days ago
Using Username: 
Trying to log in with saved cookie
Login successful.
My User Id: 
Premium User: False.
Include Private bookmarks [y/n/o]:
```

I should probably post this in an new issue though..
