### ISSUE TITLE
Different artist tried, still getting errors.  Unable to download.

### ISSUE THREAD

**Issue by Osprey-Hawk** [Nandaka/PixivUtil2#825]
Okay.  I tried it with a different artist I never downloaded with this software, Edmol (23746), and I get this error now (using latest beta) that loops forever.

![Screenshot 2020-10-16 22 51 24](https://user-images.githubusercontent.com/45588123/96327815-ae965980-1002-11eb-8971-f02daa7af4a7.png)

Is there a setting I'm missing?

_Originally posted by @Osprey-Hawk in https://github.com/Nandaka/PixivUtil2/issue_comments/710742051_

**Comment by Nandaka** [comment]
looks like it doesn't return the correct json (empty response), check your cookies again? ensure no `_` in it.

**Comment by Osprey-Hawk** [comment]
This is the PHPSESSID cookie "292554_wfwH6H5kxfs4pHTeAVlXsja49GBRsnW5"
And I only have "wfwH6H5kxfs4pHTeAVlXsja49GBRsnW5" in the config.  Is it supposed to be "292554 wfwH6H5kxfs4pHTeAVlXsja49GBRsnW5"?

**Comment by Nandaka** [comment]
should not have `_` from the browser. see #814

**Comment by Osprey-Hawk** [comment]
Alright.  I figured it out.  I had been getting the "Unable to get User Id, please check your cookie" error, then I did the "get session cookie from password reset page after resetting with same password" trick and I am now downloading like before.
