### ISSUE TITLE
Error Logging in

### ISSUE THREAD

**Issue by PerseusRex** [Nandaka/PixivUtil2#826]
### Prerequisites

* [x ] Did you read FAQ section?
* [x ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
Tried to login, but getting this back:

Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x3891898 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x038B51E8>)
Cannot Login!

I did try getting a new PHPSESSID, but still getting the same thing. I might have missed something

### Steps to Reproduce

1. Open PixivUtil2.exe
2. Log in using username/password and cookie in config.ini

**Expected behavior:** Login Successfully

**Actual behavior:** Getting the above error message

### Versions
pixivutil20201006
You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
see #814
