### ISSUE TITLE
Fanbox - %member_token% in filenameformat now defaults to "self"

### ISSUE THREAD

**Issue by daniels1989** [Nandaka/PixivUtil2#827]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Using `%member_token%` as part of the filename format for fanbox downloads, it now defaults to "self" instead of the artist's username.

### Steps to Reproduce

1. Use `%member_token%` in one of the filename formats in the fanbox section
2. Download something from fanbox
3. ???
4. No profit

Using `(%member_id%) %artist% [%member_token%]\%urlFilename%` as format, and user `@abndnrnk`/`1472125` as example:
**Expected behavior:**
`(1472125) アバンドン蘭花@FANBOX [amu224]`

**Actual behavior:**
`(1472125) アバンドン蘭花@FANBOX [self]`

### Versions

Tested with lastest release and prerelease.

**Comment by bluerthanever** [comment]
Wired that when I try using fiddler to grab the package, everything seems fine, but when I cancel fiddler, the OAuth results are wrong.
`PixivOAuth.login_with_username_and_password()` got html page instead of json object.
The response's status code is 403 and it's not caught.

**Comment by bluerthanever** [comment]
The returned page says `Verification required to access pixiv`

**Comment by daniels1989** [comment]
Deleted the logs and tried running it again to see what happens. It tries this twice and gets the captcha page both times, then just proceeds to download from fanbox anyway.

`2020-10-17 17:37:55,200 - PixivUtil20201017-beta2 - INFO - Login to OAuth using refresh token.`
`2020-10-17 17:37:55,341 - PixivUtil20201017-beta2 - INFO - OAuth Refresh Token invalid, Relogin needed.`
`2020-10-17 17:37:55,341 - PixivUtil20201017-beta2 - INFO - Login to OAuth using username and password.`
`2020-10-17 17:37:55,452 - PixivUtil20201017-beta2 - DEBUG - 403:`
[fanbox 403.html.txt](https://github.com/Nandaka/PixivUtil2/files/5397297/fanbox.403.html.txt)

Could this have anything to do with the recent login problems? I updated my pixiv cookie by removing my userId from it, and downloading from Pixiv works again for the most part.

**Comment by daniels1989** [comment]
On a side note, it can also no longer update the fanbox cookie anymore:

`2020-10-18 11:42:00,014 - PixivUtil20201017-beta2 - INFO - Not logged in to FANBOX, trying to update FANBOX cookie...`
`2020-10-18 11:42:02,651 - PixivUtil20201017-beta2 - INFO - Could not update FANBOX cookie string.`
`2020-10-18 11:42:02,652 - PixivUtil20201017-beta2 - ERROR - Unknown Error: Not logged in to FANBOX`
`Traceback (most recent call last):`
`  File "PixivUtil2.py", line 1281, in main`
`  File "PixivUtil2.py", line 1022, in main_loop`
`  File "PixivUtil2.py", line 704, in menu_fanbox_download_from_list`
`  File "PixivBrowserFactory.pyc", line 842, in fanboxGetArtistList`
`  File "PixivBrowserFactory.pyc", line 383, in fanbox_is_logged_in`
`Exception: Not logged in to FANBOX`

**Comment by bluerthanever** [comment]
> Could this have anything to do with the recent login problems? 
Probably.
> On a side note, it can also no longer update the fanbox cookie anymore:
I just tried and it worked fine from here. Which version are you using? I am running from latest code.
```
Configuration loaded.
Not logged in to FANBOX, trying to update FANBOX cookie...
New FANBOX cookie value: 645970_0OwASmUtKA6vHizwkxon14np1VFWeN7T
Writing config file... Backing up old config to config.ini.bak
Configuration saved.
```

**Comment by daniels1989** [comment]
Running the latest prerelease, 1017.

I just updated my cookie again and it seems to now update the fanbox cookie again, so at least that's no longer a problem.

But the original issue still persists, `%member_token%` still defaults to self :P

**Comment by Nandaka** [comment]
@bluerthanever I'll modify the fanboxGetArtistById() to call the getMemberPage() rather than calling getMemberInfoWhitecube() directly, so it can avoid the oAuth issue.

**Comment by bluerthanever** [comment]
okay. thanks!

**Comment by Nandaka** [comment]
should be fixed in the latest commit

**Comment by Nandaka** [comment]
released as beta3: https://github.com/Nandaka/PixivUtil2/releases/tag/v20201018-beta3

**Comment by daniels1989** [comment]
Confirmed as working. Thanks guys.
