### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by NCRZMA** [Nandaka/PixivUtil2#828]
Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x3df5070 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x03B46A08>)
Cannot Login!
press enter to exit.

I put in username and password and cookie from both chrome and firefox but non worked.

**Comment by nProtect** [comment]
Looks like pixiv moved their service behind Cloudflare.

pixivUtil try to login but got "Please wait while we checking your browser" and return 403 error.
![image](https://user-images.githubusercontent.com/5462517/96359722-2ddd7780-1140-11eb-8dee-e1dc9adec106.png)

**Comment by RecklessJames** [comment]
Same error on my end as well. Just recently updated.

**Comment by Nandaka** [comment]
see #814 ensure the new cookie doesn't have `_`. maybe need to change the password multiple time to get the new cookie format.
