### ISSUE TITLE
Pixiv Option #5 not working

### ISSUE THREAD

**Issue by AlexFiala** [Nandaka/PixivUtil2#830]
### Prerequisites

* [Yes] Did you read FAQ section?
* [Yes] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
I am using 20201018-beta3 version released Oct 18th.

I've had this issue for a while now and even the latest release does not resolve this issue.  Using Pixiv option #5 does not work and shows the below error(s)

[Description of the bug or feature]

When attempting to use Pixiv Option #5, the app fails.

1. Execute pixivutil2.exe
2. Cookie/username and password logs me in
3. Selection option #5
4. Select y to include private bookmarks.
5. Error below is presented:

_Input: 5
Include Private bookmarks [y/n/o]: n
Start Page (default=1):
End Page (default= 0, 0 for no limit):
My Member Id = 0
Importing Bookmarks...
Exporting page 1
Source URL: https://www.pixiv.net/bookmark.php?type=user&p=1&rest=show
Using default DB Path: K:\Rips\Pixiv_1\db.sqlite
Error at process_bookmark(): (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'"), <traceback object at 0x0429C908>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1281, in main
  File "PixivUtil2.py", line 989, in main_loop
  File "PixivUtil2.py", line 481, in menu_download_from_online_user_bookmark
  File "PixivBookmarkHandler.pyc", line 28, in process_bookmark
  File "PixivBookmarkHandler.pyc", line 290, in get_bookmarks
  File "PixivBookmark.pyc", line 37, in parseBookmark
AttributeError: 'NoneType' object has no attribute 'findAll'
press enter to exit._

### Versions
20201018-beta3

**Comment by Nandaka** [comment]
well, it is working for me. Can you provide me the html page generated from https://www.pixiv.net/bookmark.php?type=user&p=1&rest=show 

Also ensure the cookie doesn't have `_` because looks like it cannot parse your member Id

**Comment by AlexFiala** [comment]
Interesting.  It appears that the other cookie issue has also remedied this, as the bookmark pages are now loading without error.

Stupid of me not to follow the instructions after spending an hour or so in those other cases :)
