### ISSUE TITLE
Clarification on Cookie Configuration (Feel free to close when answered as this is purely informational)

### ISSUE THREAD

**Issue by AlexFiala** [Nandaka/PixivUtil2#831]
This is a two part question so forgive me :)

Part 1:
I understand well enough that one needs to grab the session cookie to bypass the captcha etc., however, am I grabbing my cookie correctly?  I use the Brave browser (chromium-based), so I usually just click the lock next to the URL to grab the PHPSESSID cookie.  One thing I noticed, however, is that this cookie is prepended with what I believe is my user ID.  First off, is that correct?  And second, Pixivutil2.exe throws an error for this cookie if I don't first remove that prepended string.  So, for example, if my cookie is 

23423345_thisisasamplecookie, I need to remove "23423345_" in the config.ini for the cookie to work.

Is this expected?

Part 2:
In the latest version, 20201018-beta3, I'm now seeing the following when logging in:

Trying to log in with saved cookie
Login successful.
Unable to get User Id, please check your cookie.
Premium User: False.
PixivDownloader2 version 20201018-beta3

So after going through that work for the cookie, I'm seeing a cookie error now and I'm also seeing that Pixivutil2.exe is not recognizing that I am indeed a premium user.  

Is this expected behavior and/or can anyone provide guidance on if this will cause other nuanced issues?

**Comment by Nandaka** [comment]
it means the cookie still deemed invalid, see for login related issues, see https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-711182644

From the description, you need to copy the cookie value directly after changing the password, so it will return the correct session cookie

**Comment by AlexFiala** [comment]
@Nandaka, thanks I had seen that in the other threads but had navigated away from the "password changed" screen and must've grabbed my cookie after.  Now that I have the cookie while still on that page, everything in this case appears working :).
