### ISSUE TITLE
[Question] How do I change the directory for downloads to a certain folder?

### ISSUE THREAD

**Issue by kody180** [Nandaka/PixivUtil2#833]
### Prerequisites

* [ ] Did you read FAQ section?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
check the readme.md and update the config.ini

rootdirectory ==> Your root directory for saving the images.
filenameFormat and other format ==> the format for saving, use '\' to create folder in windows.
