### ISSUE TITLE
Download most popular images from tag search (when logged in premium account)

### ISSUE THREAD

**Issue by fireattack** [Nandaka/PixivUtil2#834]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Is it possible to have such feature?
Basically option 3 but with the images ordered by popularity.

**Comment by Nandaka** [comment]
only if you have premium/paid account and I need the search parameter (e.g. &order=something) as I don't have premium.

**Comment by fireattack** [comment]
It is `order=popular_d` (overall), `popular_male_d` (popular among male users) and `popular_female_d`.

**Comment by Nandaka** [comment]
should be in the latest commit, I cannot test it as I don't have premium, but it should ask the sorting order, rather than oldest first [y/n] question from interactive console.

**Comment by fireattack** [comment]
It works to me, thanks.
