### ISSUE TITLE
[request] option to avoid re-downloading files with unknown size

### ISSUE THREAD

**Issue by John-Titor** [Nandaka/PixivUtil2#837]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Many images seem to be missing a remote file size, which results in a file size mis-compare when a local file exists. This results in a re-download of the remote image, even if it hasn't changed.

It would be nice to avoid this re-downloading.

### Steps to Reproduce

1) set: 

    [DownloadControl]
    alwayscheckfilesize = True

2) Download an image for which a remote file size is not reported (shows up as -1).
3) Download the image again. Note that the image is re-downloaded due to the file size comparison failing. e.g.

    Getting remote filesize...
    	No file size information!
    Remote filesize = -1 B (-1 Bytes)
    	Found file with different file size ==> example.jpg, removing old file (old: 2502334 vs new: -1)
    [███.................] 2.39 MiB     Completed in 3.953075s (618.17 KiB/s)

Note that the two file sizes are the same.

### Versions

PixivDownloader2 version 20201009-beta1, db880a2

**Comment by John-Titor** [comment]
I'm at 3f7f3cc010c8fbd516a766127a607b9200f146f9 which (per git log) has that change; I have:

```
[DownloadControl]
minfilesize = 0
maxfilesize = 0
overwrite = False
backupoldfile = False
daylastupdated = 1
alwayscheckfilesize = True
checkupdatedlimit = 0
useblacklisttags = False
useblacklisttitles = False
useblacklisttitlesregex = False
datediff = 0
enableinfiniteloop = False
useblacklistmembers = True
downloadresized = False
checklastmodified = True
skipunknownsize = True
```

and I am still seeing:

```
Image URL : https://i.pximg.net/img-original/img/../example.jpg
Filename  : example.jpg
Getting remote filesize...
	No file size information!
Remote filesize = -1 B (-1 Bytes)
	Found file with different file size ==> example.jpg, removing old file (old: 530011 vs new: -1)
```

Do I have wrong config options?

**Comment by Nandaka** [comment]
can get the latest commit and run a debug and check if this line being check?
https://github.com/Nandaka/PixivUtil2/blob/master/PixivDownloadHandler.py#L81

I cannot check as I don't have the id that will trigger remote size == -1
