### ISSUE TITLE
Creating GIFs from Ugoira fails when deletezipfile = True

### ISSUE THREAD

**Issue by Rocky-sama** [Nandaka/PixivUtil2#838]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I ran the 20200525 release until now so I had to start using ffmpeg with the latest release.
This however gives me an error that it couldn't find the zip file that contains all the single images.
To me it seems like a problem with the workflow, meaning that the zip file is deleted before ffmpeg is done with the conversion to GIF.

My workaround is setting deletezipfile = False but I don't want to have the zip files of all animations lying around.

Maybe the issues #799 and #818 are related.

### Steps to Reproduce

1. Set config.ini settings to

[FFmpeg]
ffmpeg = ffmpeg
ffmpegcodec = libvpx-vp9
ffmpegext = webm
ffmpegparam = -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p
webpcodec = libwebp
webpparam = -lossless 0 -q:v 90 -loop 0 -vsync 2 -r 999

[Ugoira]
writeugoirainfo = False
createugoira = True
deletezipfile = True
creategif = True
createapng = False
deleteugoira = True
createwebm = False
createwebp = False

2. Download an Ugoira file

**Expected behavior:** 
Successfully download the Ugoira and only have an animated GIF remaining

**Actual behavior:** 
Error message FileNotFoundError: [Errno 2] No such file or directory: 'E:\\[...]\\pixivutil20201019-beta4\\[user] ([user_id])\\[img_id]_ugoira1920x1080 [...].zip' leaving me only with the choice of closing the application.
The .ugoira file isn't deleted.

### Versions
v20201019-beta4

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
can you upload the log file? also no option to delete the ugoira, only the zip file.

**Comment by Rocky-sama** [comment]
For some reason it works now. I tried it again with multiple situations (downloading directing with image_id or from bookmarked artists) and it doesn't fail anymore. 

The whole log file is bloated and contains my email address so I hope an excerpt is enough: [logfile.txt](https://github.com/Nandaka/PixivUtil2/files/5432920/logfile.txt)

I can't reproduce it so if that's good enough for you, you can close the issue...

**Comment by Nandaka** [comment]
added some changes to avoid deletion order, should be fixed edge cases now.
