### ISSUE TITLE
Release 20201024 causes unknown error

### ISSUE THREAD

**Issue by esotericer1** [Nandaka/PixivUtil2#843]
When trying to open 20201024, with pasting new cookie in the config and everything, all it shows is this : 

Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x4863268 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x0424C208>)
Cannot Login!

**Comment by jwshields** [comment]
Take a look at this issue, there are instructions in there on how to fix it, https://github.com/Nandaka/PixivUtil2/issues/814

**Comment by fengberd** [comment]
Go [change password](https://accounts.pixiv.net/password/change) page, open devtools and fill in your current password 3 times (or pick a new one) then submit.
On the `You have changed your password` page, copy the PHPSESSID **without _** now and it should work.
