### ISSUE TITLE
ffmpeg install

### ISSUE THREAD

**Issue by ShiroTora** [Nandaka/PixivUtil2#847]
he ppl

how do i install this for ugoria? 
https://ffmpeg.org/download.html#get-packages
it always worked fine untill this update of pixiv until 
i dont get it how this works with pixivuntil , 
i copied those files to pixivuntil folder but it dont work,
i know i do it work but i dont know how

**Comment by Nandaka** [comment]
download the exe files (ffmpeg.exe) and place it to your pixivutil2 folder.

**Comment by ShiroTora** [comment]
thanks pal
