### ISSUE TITLE
A question about making my own tool based on your code

### ISSUE THREAD

**Issue by bluerthanever** [Nandaka/PixivUtil2#848]
Hey. Thank you for this tool.
This is not really a issue of the program. But I think I should ask.
I am recently making a `util` to download from twitter, and the name and the whole structural thing are inspired by Pixivutil2.
**I actually even used some code from PixivUtil2 as well....**
Is it OK if I upload it to github when I think it's ready?

And also have you considered to make PixivUtil2 multi-language? I am making my own so.

**Comment by Nandaka** [comment]
sure, it is open source 👍 

> PixivUtil2 multi-language
too lazy to do that 👅

**Comment by bluerthanever** [comment]
Haha. Thanks.
>too lazy to do that 👅

Same here at first.
