### ISSUE TITLE
Files are not being downloaded to relative path in config

### ISSUE THREAD

**Issue by charzho** [Nandaka/PixivUtil2#849]
### Prerequisites

* [X ] Did you read FAQ section?
* [X ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Downloading to a file path with ".." should go to the folder above.

### Steps to Reproduce

Using "filenameformat = ..\\Artists\\%original_member_id% %original_artist%\\%urlFilename% - %title%" as my config option.

**Expected behavior:** Files should be going to an "Artists" folder in the same level as the "pixivutil" folder, above the PixivUtil2.exe
**Actual behavior:** Files are going to an "Artists" folder on the same level as PixivUtil2.exe

### Versions

20201025

**Comment by Nandaka** [comment]
set the root directory using 'rootdirectory' in config.ini
