### ISSUE TITLE
Using the starting date does not work

### ISSUE THREAD

**Issue by PiPerson7472** [Nandaka/PixivUtil2#852]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

When using the start date 2009-12-31 with the correct format given by the prompt (YYYY-MM-DD) it downloads starting from 2019-10-31

### Steps to Reproduce

1. Option 3 (download by tag) ロリ
2. Bookmark count (no change)
3. Use partial match (n)
4. Oldest first (y)
5. Start page (no change)
6. End page (no change)
7. Start date (2009-12-31)
8. End date (no change)
9. Search type (i)
10. Downloaded images are from 2019-10-31

**Expected behavior:** [What you expected to happen]

The images downloaded would start from 2009-12-31 and continue to download to present day.

**Actual behavior:** [What actually happened]

The images downloaded started from 2019-10-31.

### Versions

20201025

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
what is the generated search url? can you upload the log file?

**Comment by PiPerson7472** [comment]
I dont know where the generated search url is but here is the log file.
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5460869/pixivutil.log)

**Comment by Nandaka** [comment]
it does pass the correct date to pixiv server: https://www.pixiv.net/ajax/search/artworks/%E3%83%AD%E3%83%AA?word=%E3%83%AD%E3%83%AA&scd=2009-12-31&s_mode=s_tag_full&type=illust_and_ugoira&mode=r18&order=date

If you try to search from the website, looks like pixiv limit the searchable date to 2019-10-30. Maybe you need premium?

**Comment by PiPerson7472** [comment]
That may be possible but the only big things premium lets you do (as a veiwer) for searching is the popular by gender and the bookmarks. I dont know how that would really affect the dating system.

**Comment by Nandaka** [comment]
> But maybe it does. I wouldnt know how to find ou

just do the search from pixiv website? The UI allow you to select date older than that, but when you submit, it will change the scd parameter in the url to that date (max. 1 year ago).

**Comment by Nandaka** [comment]
alternatively, try to search from oldest works first?
