### ISSUE TITLE
Can't login using a cookie

### ISSUE THREAD

**Issue by WhiteSp1rit** [Nandaka/PixivUtil2#854]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Getting the following error while trying to login with a cookie:

```
Trying to log in with saved cookie
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <ht
tperror_seek_wrapper (urllib.error.HTTPError instance) at 0x3250418 whose wrapped object = <HTTPError 403: 'Fo
rbidden'>>, <traceback object at 0x03256248>)
Cannot Login!
```
version tested: 20201025, however it was the same on previous versions

PHPSESSID was copied right after logging to the website through browser, and pasted into the config file.

Also tested the password - can't login with it either, getting the captcha error.  
Can login on the website itself just fine.

**Comment by OniiGokko** [comment]
Step 1. go to pixiv website.
Step 2. change password or type current password in all 3 fields, press change password
step 3. on the new page with the text "your password has been changed", press F12 in browser and go to "application tab" (chrome) or "storage tab" (Firefox) and search for your new phpsessid -> should be in the new format.
step 4. paste the new format cookie in config.ini
hope this will help u...
//Onii

**Comment by temporelus** [comment]
I'm experiencing the same issue, I tried Onii's method to no avail, I'm also on 20201025.

**Comment by Nandaka** [comment]
try the latest version, if still not working then better post on #814
