### ISSUE TITLE
[Feature Request] Ability to Download Image Details for Already-Downloaded Images

### ISSUE THREAD

**Issue by britefire** [Nandaka/PixivUtil2#856]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

It would be a lovely feature, if there was some way or another, to have the ability to go through and download image info .txt files for images that had already been downloaded, maybe an option for the DB to go through and download image info, or a config setting that would allow already-downloaded images to download image info instead of being skipped over?

Apologies if there's already a way to do this I'm missing, still learning the program somewhat. ^^\;

**Comment by Nandaka** [comment]
Assuming you set `setLastModified = True`, then you can try to set `alwaysCheckFileSize = True` and `checkLastModified = True`.

**Comment by britefire** [comment]
Well that worked, now I feel silly, sorry >.<
