### ISSUE TITLE
Program won't start - Fatal Python error

### ISSUE THREAD

**Issue by hopto-dot** [Nandaka/PixivUtil2#858]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000009f0 (most recent call first):
<no Python frame>

**Comment by Nandaka** [comment]
which OS you running with? older os is not supported, else you can try to run directly from the source code.
See https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

**Comment by hopto-dot** [comment]
I am running windows 10
Python is installed
I unzipped with WinRar and then tried to run the exe. I also tried to run the exe inside of the cmd and powershell - neither worked

**Comment by hopto-dot** [comment]
### When running in Powershell:
```
$  ./PixivUtil2.exe
Traceback (most recent call last):
  File "PixivUtil2.py", line 1910, in <module>
  File "PixivUtil2.py", line 1731, in main
  File "PixivUtil2.py", line 1604, in set_console_title
  File "PixivHelper.pyc", line 250, in setConsoleTitle
  File "subprocess.pyc", line 168, in call
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by Nandaka** [comment]
Are you running the latest version from: https://github.com/Nandaka/PixivUtil2/releases
Looks like it is the older version.

> Python is installed

don't run the exe if you want to run from source code.

> windows 10

32-bit or 64-bit?

**Comment by hopto-dot** [comment]
I am running 64 bit Windows 10.
I updated to Python 3.9 (64 bit)

The exe still opens and closes immediately, or trying to open it in the cmd returns this error:
```
$ PixivUtil2.exe
Traceback (most recent call last):
  File "PixivUtil2.py", line 1358, in <module>
  File "PixivUtil2.py", line 1162, in main
  File "PixivUtil2.py", line 878, in set_console_title
  File "PixivHelper.pyc", line 316, in set_console_title
  File "subprocess.pyc", line 340, in call
  File "subprocess.pyc", line 854, in __init__
  File "subprocess.pyc", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Aren't I right in saying I have to download the [latest release](https://github.com/Nandaka/PixivUtil2/releases/tag/v20201031), unzip, then run the exe? As mentioned above, I have python installed as well. I even tried temporarily disabling my anti-virus.

**Comment by Nandaka** [comment]
> Aren't I right in saying I have to download the latest release, unzip, then run the exe?

If you running from the zip with exe inside, you don't need to install python.

> Is FFMPEG needed inside the folder perhaps

It should be in the same folder.

From the error message, the application failed when it try to set the console title by running `title xxxx` in from the console.
https://github.com/Nandaka/PixivUtil2/blob/v20201031/PixivHelper.py#L314-L316

Can you check on the zip file properties and unblock it from windows explorer. Image for references.
![image](https://user-images.githubusercontent.com/836867/98227168-eb19fd00-1f91-11eb-88ac-eb55b0aa60a0.png)

**Comment by hopto-dot** [comment]
Ok, I already have FFMPEG installed and it's in my C drive:
![c drive](https://i.imgur.com/uXnTO1S.png)

I have already tried dragging the 'ffmpeg' folder into the pixivutil20201031 folder. Am I doing it wrong?![ffmpeg](https://i.imgur.com/k9navT2.png)
Do I have to install a new instance of FFMPEG?

**Comment by Nandaka** [comment]
no, just paste the ffmpeg.exe in the same folder.

From the logging, it has nothing to do with ffmpeg. It fails when it try to call `title` command from the console.
![image](https://user-images.githubusercontent.com/836867/98241075-5caf7680-1fa5-11eb-96ee-5507ac3f9781.png)

**Can you check on the zip file properties and unblock it from windows explorer.**

**Comment by hopto-dot** [comment]
$ PixivUtil2.exe
Traceback (most recent call last):
  File "PixivUtil2.py", line 1358, in <module>
  File "PixivUtil2.py", line 1162, in main
  File "PixivUtil2.py", line 878, in set_console_title
  File "PixivHelper.pyc", line 316, in set_console_title
  File "subprocess.pyc", line 340, in call
  File "subprocess.pyc", line 854, in __init__
  File "subprocess.pyc", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified


PixivUtil2.exe
Traceback (most recent call last):
  File "PixivUtil2.py", line 1358, in <module>
  File "PixivUtil2.py", line 1162, in main
  File "PixivUtil2.py", line 878, in set_console_title
  File "PixivHelper.pyc", line 316, in set_console_title
  File "subprocess.pyc", line 340, in call
  File "subprocess.pyc", line 854, in __init__
  File "subprocess.pyc", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by hopto-dot** [comment]
Yes I checked 'unblocked' in the zip folder properties. Then unzipped the folder, then copied 'ffmpeg.exe' into the folder and ran the exe but it doesn't work. I got the exact same error as above when I try in to in the command prompt.

Just to be clear, this is the correct exe right?
![image](https://user-images.githubusercontent.com/66906618/98244641-a9745c80-1f67-11eb-81a1-0257db5ca79e.png)

**Comment by Nandaka** [comment]
> Just to be clear, this is the correct exe right?

yes. if it failed to load the ffmpeg, it will show this error.
![image](https://user-images.githubusercontent.com/836867/98258114-7065d780-1fbb-11eb-82c4-b446db868463.png)

Looks like something preventing it to call `title` command in the console. Can you open an console window and run `title "test title hahaha"` and what is the result. If it is working, then somehow the pixivutil.exe cannot access that command. Check your antivirus/firewall/etc.

**Comment by hopto-dot** [comment]
### It brings up an error
![image](https://user-images.githubusercontent.com/66906618/98258975-6ae79d80-1f79-11eb-8aaf-844cfc5f84ee.png)

**Comment by Nandaka** [comment]
run it using `cmd`?

**Comment by hopto-dot** [comment]
### Nothing happens when I type the command in cmd:
![image](https://user-images.githubusercontent.com/66906618/98269508-b86a0780-1f85-11eb-9e34-b5d86bc0aece.png)

**Comment by Nandaka** [comment]
your console title should be changed. 
![image](https://user-images.githubusercontent.com/836867/98270191-972b0a80-1fc9-11eb-9901-361775ea698a.png)

Try to run pixivutil2.exe from `cmd`, rather than powershell?

**Comment by hopto-dot** [comment]
Oh silly me. Yes that works.
![image](https://user-images.githubusercontent.com/66906618/98279563-0127bd80-1f92-11eb-9c7d-55d14c0035d8.png)

**Comment by Nandaka** [comment]
If it is working, then the application also should work in `cmd` mode. If it is not, then most likely something in your pc preventing it to call `title` command.

**Comment by hopto-dot** [comment]
### Have I done anything wrong here?
![image](https://user-images.githubusercontent.com/66906618/98333462-b2f9d500-1ff8-11eb-95e4-783152514676.png)

**Comment by Nandaka** [comment]
no, check your antivirus/firewall, or try to use different pc.
Your current pc doesn't allow to run the pixivutil2.exe for whatever reason.

or run from source code, not exe/zip file, read https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

**Comment by hopto-dot** [comment]
Update: I recently wiped my whole PC and ran the program and it works
