### ISSUE TITLE
Attempt to interpret error code as correct file size

### ISSUE THREAD

**Issue by NHOrus** [Nandaka/PixivUtil2#86]
So, I just saw this. File names edited out.
```
Start downloading... Using Referer: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=

        No file size information!
        Found file with different file size, backing up to:
         0 of        -1 Bytes  Completed in 0.0s ( тИЮ B/s)
 done.
```
I think there is a missing check for error returned from WinAPI?
Windows, PixivUtil2 20150605

**Comment by Nandaka** [comment]
-1 Bytes? This is from the server reply.

For some reason, your isp/firewall/antivirus/etc doesn't return the Content-Length header.

refer to: https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L78

**Comment by NHOrus** [comment]
Problem is two-fold.  
First, it got file size correctly and downloaded image at third attempt.  
Second, when it got -1, it downloaded the file incorrectly. As in, created wile without content. 

So, I am moslty dislike existence of "images" of 0 bytes of length.

Oh, I see! PixivUtil iterates until downloaded image is of the file_size it got. And I got no idea what's happening in those libraries.

**Comment by Nandaka** [comment]
If the filesize is known (the application get the Content-Length header), it will iterates until it matched with the filesize.
Refer to: https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L513

If the filesize is not known, it will iterates until it receive no more. 
Refer to: https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L518

Maybe I can add a check if the downloaded size == 0, I'll make it as fail and delete the downloaded file.

**Comment by NHOrus** [comment]
Good idea.  
Possibly check that size on disk is equal the expected size and if not - do the same? In case of sudden network problems, so if file transfer gets cut off, mangled file remains, and currently PixivUtil2 happily leaves it as it is.

**Comment by Nandaka** [comment]
It do that already. If the file size is known and the downloaded size is not the same, it will raise an exception. Usually this is happen when the connection is timed-out.

refer to https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L526

some enhacement need to be added to delete the incomplete file.
refer to https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L538
related to #79

**Comment by Nandaka** [comment]
Try: http://www.mediafire.com/download/b04irzy1ij2zgmq/pixivutil20150706-beta3.7z

I do major reorg on the config.ini, so you may need to set the value again after running (remember to backup your file).

I changed the logic:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L539
