### ISSUE TITLE
Pixiv ignores numberofpage setting in config

### ISSUE THREAD

**Issue by ikkion** [Nandaka/PixivUtil2#860]
### Prerequisites

* [ ] Did you read FAQ section?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

The last 4-5 versions of PixivUtil2 ignores numberofpage setting in config. I run a large list file, older versions of PixivUtil2 reads the numberofpage setting, which I limited to 2 pages and stopped att page two. The last few versions shows the page limit when PixivUtil2 starts but when processing the list it does all pages as if the numberofpage setting didnt exist at all.

### Steps to Reproduce

1. Set numberofpage = 2 in config file
2. run large list.txt using option 4

**Expected behavior:** PixivUtil2 goes to page 2 and goes to next artist in list.txt

**Actual behavior:** ignores numberofpage setting and does all pages for every artist in list.txt

### Versions

Last version that worked for me was pixivutil20200926-beta1 which I used a long as possible, basically until two days ago. Any newer version I tried including the newest ignores the setting.

**Comment by keizzet** [comment]
Same problem. I try to edit numberOfpage= 0, 1, 2, in the config.ini etc without results
![pixivut](https://user-images.githubusercontent.com/73966427/98166217-b3855500-1eac-11eb-833a-def493b73b68.PNG)

**Comment by Nandaka** [comment]
@ikkion do you run from interactive console or start using command line parameter?

@keizzet delete/backup the old config file, and rerun to regenerate the new config?

**Comment by keizzet** [comment]
Ok, I try that but the 'no capcha' error appear and no new config.ini was created, so I just Copy a new config.ini from a fresh instalation with the correct authentication info and works. Thanks.

**Comment by ikkion** [comment]
@Nandaka 
Interactive console I think. I start the exe in Windows, it opens up a command promt like window, in the window it says "Limit up to: 2 page(s).", when I run option 4 what it did before was that it ran 2 pages and went to the next one on the list, but now it does all pages as if the settting numberofpage was set to 0 but it is set to 2. The older versions behaved correctly, the newer versions do not.
