### ISSUE TITLE
PixivUtil2 ignores rootdirectory setting when encountering "Invalid Argument" OSError

### ISSUE THREAD

**Issue by cglmrfreeman** [Nandaka/PixivUtil2#861]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
PixivUtil2 ignores "rootdirectory" setting when encountering "OSError" "Invalid Argument" (usually hit if an invalid character is tried to save in the file name) and downloads the file to the running pixivutil2 directory.

### Steps to Reproduce

1. Include %title% in filenameformat setting.
2. Download by image id: 83574746 (image id listed here as example only).

**Expected behavior:**
PixivUtil2 should sanitize filename and (attempt to) save in the "rootdirectory" setting with proper parsing of any additional directory information parsed from "filenameformat".

**Actual behavior:**
PixivUtil2 saves the sanitized filename in the PixivUtil2 executing directory.

### Versions
"PixivDownloader2 version 20201031"

**Comment by Nandaka** [comment]
its by design: https://github.com/Nandaka/PixivUtil2/blob/9f706909e97d67f5c6a7ca9652528aa4236c58b4/PixivHelper.py#L675

**Comment by cglmrfreeman** [comment]
Unfortunate.

**Comment by cglmrfreeman** [comment]
Can I at least ask why this is by design?

**Comment by Nandaka** [comment]
because the current folder usually always writable by the application, and the url filename is only consists of the image id and _p<some number>

**Comment by cglmrfreeman** [comment]
I've got a bunch of images floating in my application folder that I don't know who they belong to now. I suppose the only work around would be to delete the images, cleanup the database, then redownload my batches with the filenameformat not using %title%. Seems like a lot of work though.

**Comment by Nandaka** [comment]
you got the image id in the filename, so just open the browser and check the 
 url here: https://www.pixiv.net/en/artworks/<image_id>

**Comment by cglmrfreeman** [comment]
Just wanted to add to this that I just discovered that the sqlite database does not add these images to the database. Should that _also_ happen?
