### ISSUE TITLE
Some pixiv user can't download photos full album

### ISSUE THREAD

**Issue by bubbee23** [Nandaka/PixivUtil2#863]
### Prerequisites

* [/] Did you read FAQ section?
* [/] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I have been able to download pictures from some pixiv user's all of them. But now only some images can be downloaded, although there are many images in pixiv user who used to download them. What is the cause?. 

Thank you.

**Comment by Nandaka** [comment]
any example? what is in the logging? what is your config? Please give more information.

**Comment by bubbee23** [comment]
Example :  I've downloaded images them all in this pixiv user
https://www.pixiv.net/en/users/1859092 
and program and in pixiv user show like this in screen soht

![Screenshot (8)](https://user-images.githubusercontent.com/74089129/98434206-35b98780-2100-11eb-8bb4-b0afb62e45ae.png)

ืีnumber of images in downloader and pixiv profile is not related

and program is work correctly. no error no bug.
then program working finished. I go to download directory. This is result

![Screenshot 2020-11-07 140050](https://user-images.githubusercontent.com/74089129/98434395-b0cf6d80-2101-11eb-9aa5-0abb30fb69d3.png)

This log and my config (I've remove ID/Password and session setting only)
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/5504411/pixivutil.log)

[my config .zip](https://github.com/Nandaka/PixivUtil2/files/5504412/my.config.zip)

Thanks for making nice program ^_^

**Comment by bubbee23** [comment]
And I don't know who have been like this or just me only

**Comment by Nandaka** [comment]
> Local file timestamp match with remote: D:\Pixiv\ぐらんで@FANBOX更新中 (1859092)\18562997_p0 - 裸エリオ.png => 2011-05-01 17:27:26+00:00

means you already downloaded the file before and it has the same timestamp with the post timestamp.

> https://www.pixiv.net/ajax/user/1859092/illustmanga/tag?tag=R-18&offset=0&limit=48

Looks like you enable R-18 mode only, so it wont download SFW images. Set `r18mode = False` if you want to download all images. Please read the readme.md.
![image](https://user-images.githubusercontent.com/836867/98434564-e5482700-210b-11eb-8d9a-dfc7d142dfab.png)

**Comment by bubbee23** [comment]
Thank for help
Solved : I change setting in config in r18 mode to false (before I set True)

I have a question : If I set r18 mode to false in config. I can download R-18 Image like normally?

**Comment by Nandaka** [comment]
yes if you enable from the pixiv website.
![image](https://user-images.githubusercontent.com/836867/98434759-78359100-210d-11eb-93a8-6516ecb0ec8c.png)

**Comment by bubbee23** [comment]
Thank you so much. ^_^
