### ISSUE TITLE
Demjson dependency not compatible with Python 3.8 under unix

### ISSUE THREAD

**Issue by mousesama** [Nandaka/PixivUtil2#866]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Running from source under unix with python 3.8 does not work because demjson module has python 2 code, not compatible with 3.8.

### Steps to Reproduce

1. Clone pixiv utils on to unix environment
2. Install requirements with python 3.8
3. Run PixivUtil2.py using python3 command

**Expected behavior:** PixivUtil starts normally

**Actual behavior:** 
![chrome_2020-11-12_15-48-04](https://user-images.githubusercontent.com/68248807/98955201-eb207c80-24fe-11eb-85e1-8fe9021182c6.png)

### Versions
PixivUtil2 commit 8167f901f072e5726e374128bb04b1c1d0c19163
Python 3.8
Synology DMS Unix OS running on AArch64 architecture

**Comment by Nandaka** [comment]
well, I'm running windows, so I cannot test it. Maybe raise an issue to demjson?

**Comment by mousesama** [comment]
Demjson does not seem to be maintained anymore as the last commit was 5 years ago. I would recommend switching over to a more modern json library if possible.

**Comment by Nandaka** [comment]
hmm, got any recommendation? I used demjson because last time pixiv return json with integer as the key, which throw an error for built-in json parser.

**Comment by mousesama** [comment]
I believe python natively can handle and decode integer keys into string keys without throwing an error. It's possible that past versions could not handle it so an external library was needed but as of 3.8 at least, there seems to be no issue parsing integer keys from JSON, so I would recommend using that to cut down on extra dependencies.

**Comment by Nandaka** [comment]
sure, pull request is appreciated.

**Comment by byjtje** [comment]
For what it's worth, there are no problems here with Python 3.8.6 running on Arch
