### ISSUE TITLE
Wrong "is_deleted" flagging

### ISSUE THREAD

**Issue by byjtje** [Nandaka/PixivUtil2#869]
### Prerequisites

* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
Latest commit and before

### Description

Going through my database I noticed that some artists had the "is_deleted" flag set, even though they weren't deleted. All of these flagging must've happened during "4. Download from list", and one artist never downloaded anything before being flagged, with "name" still being "member_id". Also some have the "last_image" value -1 even though they downloaded after being added, however that seems to be something common with unflagged images.

### Steps to Reproduce

No idea. ¯\_(ツ)_/¯

### Versions
I don't know in which version it got introduced in, but if "last_update_date"s are anything to go by, the earliest is 2020-09-19, with the latest occurrence being 2020-11-05.

**Comment by byjtje** [comment]
Needless to say, they work fine after changing it back to 0.

**Comment by Nandaka** [comment]
check the log file? it is set if the artist being suspended or actually already deleted.

https://github.com/Nandaka/PixivUtil2/blob/master/PixivArtistHandler.py#L87-L88

**Comment by byjtje** [comment]
> check the log file? it is set if the artist being suspended or actually already deleted.
> 
> https://github.com/Nandaka/PixivUtil2/blob/master/PixivArtistHandler.py#L87-L88

I no longer have the log files dating back to there, however neither is the case, so somehow it must've gotten set without it being the case – maybe someone else having the same issue can chime in with logs.

On an unrelated sidenote, is what is the Pixiv API for which we can artwork pages one by one as opposed to /profile/all?

**Comment by Nandaka** [comment]
by page for specific artist? No such thing I believe. Using F12, I can see it just calling `/ajax/user/92448/profile/illusts` with image ids from `profile/all` to get the details when I press the pagination.

![image](https://user-images.githubusercontent.com/836867/100430025-2f9c4280-30d1-11eb-9da0-e139436a2a03.png)
