### ISSUE TITLE
Fanbox download cover set to true without reading "config.ini"

### ISSUE THREAD

**Issue by jinan-tw** [Nandaka/PixivUtil2#870]
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

I don't want to download cover images in Fanbox, so I traced the code and found this statement: 
[https://github.com/Nandaka/PixivUtil2/blob/f7be7f33ddf610158ce3e919e063e0295d4c6c61/PixivFanboxHandler.py#L90](https://github.com/Nandaka/PixivUtil2/blob/f7be7f33ddf610158ce3e919e063e0295d4c6c61/PixivFanboxHandler.py#L90)
So I thought there was a [variable](https://github.com/Nandaka/PixivUtil2/blob/f7be7f33ddf610158ce3e919e063e0295d4c6c61/PixivConfig.py#L155), `downloadCover` (which default value is True) that I can control it by config.ini, but the [document](https://github.com/Nandaka/PixivUtil2#fanbox) didn't mention about it.
And even I changed the text in config.ini, by adding the line `downloadCover = False` or `downloadcover = False`
under [FANBOX] section, the program still set the value to `True`
How do I download Fanbox images exclude cover without building the code by myself?

### Steps to Reproduce

1. Set the config.ini correctly, and add `downloadcover = False` or `downloadCover = False` under [FANBOX] section

2. Open PixivUtil2.exe or run command

3. Download with input f2 and key the creator ID

4. Inspect the files downloaded in your folder, and go to menu, key "p" to print the config

**Expected behavior:** Download images without cover, the variable `downloadCover` is `False` in output
**Actual behavior:** Still download cover, program didn't print downloadCover in the terminal

### Versions
20201031

**Comment by Nandaka** [comment]
set these flags to false?
```
[FANBOX]
downloadcoverwhenrestricted = False
downloadcover = False
```

**Comment by jinan-tw** [comment]
> set these flags to false?
> 
> ```
> [FANBOX]
> downloadcoverwhenrestricted = False
> downloadcover = False
> ```

Yes, I have set these flags to false

**Comment by Nandaka** [comment]
ah, the version 20201031 don't have that line of code yet.
https://github.com/Nandaka/PixivUtil2/blob/v20201031/PixivFanboxHandler.py#L90

**Comment by Nandaka** [comment]
should be in the latest releases now https://github.com/Nandaka/PixivUtil2/releases/

**Comment by jinan-tw** [comment]
Works with the latest version (20201131) thanks!
