### ISSUE TITLE
Artist with no works fails to endless loop

### ISSUE THREAD

**Issue by GerhardSauer** [Nandaka/PixivUtil2#872]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
Bug
With a certain artist (has no more works published, member id 25505263), when using option 1 ( download by member_id), I get an endless loop of error messages.
Option 8 works without problems.

![20201201_001](https://user-images.githubusercontent.com/15160045/100758904-52d83200-33f0-11eb-92f0-2c5e40f0dd29.jpg)

settings:
[Network]
useproxy = False
proxyaddress = 
useragent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.47
userobots = True
timeout = 60
retry = 3
retrywait = 5
downloaddelay = 3
checknewversion = True
opennewversion = False
enablesslverification = False

[Settings]
downloadlistdirectory = X:\S_Pixiv_Download
uselist = True
processfromdb = True
rootdirectory = .
downloadavatar = False
usesuppresstags = False
tagslimit = -1
writeimageinfo = False
writeimagejson = False
verifyimage = False
writeurlindescription = False
urlblacklistregex = 
dbpath = C:\Users\XXX\Pixiv\db.sqlite
setlastmodified = True
uselocaltimezone = False

[DownloadControl]
minfilesize = 0
maxfilesize = 0
overwrite = False
backupoldfile = False
daylastupdated = 1
alwayscheckfilesize = False
checkupdatedlimit = 0
useblacklisttags = False
useblacklisttitles = False
useblacklisttitlesregex = False
datediff = 0
enableinfiniteloop = False
useblacklistmembers = False
downloadresized = False
checklastmodified = True
skipunknownsize = False

### Steps to Reproduce

1. using command line option -s 1 25505263 or with command line gui option 1 with member_id 25505263 (independent of Pixiv sketch option)
2. endless error loop

**Expected behavior:** [What you expected to happen]
Images of the specified artist get downloaded.

**Actual behavior:** [What actually happened]
endless loop of error messages

### Versions
20201031

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
That's because it cannot the page, the error message related to HTTPS/SSL hostname verification.

Can you open pixiv website directly in browser without using proxy?

**Comment by GerhardSauer** [comment]
yes, I have no problem in opening the page in the browser.
Other member ids (with pictures) work fine.

**Comment by Nandaka** [comment]
well, it is working from my side.
![image](https://user-images.githubusercontent.com/836867/100870496-a96d6b00-34d9-11eb-844e-4675533e5f7c.png)

Are you saying you can download other artist using the program?

From the error messages, it failed to validate the certificate when it try to authenticate to oAuth (that is why it throw SSL error), which means you have network/dns error.
You can try to change your DNS to use DNS Crypt or update the config and set `enablesslverification = False`.

**Comment by GerhardSauer** [comment]
Hm, interesting...
yes I can download other artist using the tool, download by member_id is working, just tested it with 4 other IDs.
Download new illust from bookmark (option 8) works fine too.
enablesslverification = False  is set to False, see also above in the config I posted.

I have seen, that you download the avatar, so I tried to change the option to see if this is the reason, but I get the same error.

For whatever reason, it fails for exactly this member id.

**Comment by GerhardSauer** [comment]
I have seen, that I didn't use the newest version, but now I have it. (was 20201030 and newest 20201131)
Nevertheless, same error.
So I tried it on another machine, with a new pixiv util install (default config, only added username, pw and cookie)
Then I get this:

`Processing` Member Id: 25505263
Page
Member Url: https://www.pixiv.net/ajax/user/25505263/profile/all
Using OAuth to retrieve member info for: 25505263
103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。
Member ID (25505263): 0 Failed to login using OAuth, hasDumpPage=N, `pageData=None`

Other IDs work...

**Comment by Nandaka** [comment]
> またはメールアドレス、パスワードが正しいかチェックしてください 

That one said you entered wrong email address or password. Try to key in the full email address for the username in config.ini?

**Comment by GerhardSauer** [comment]
that's it.
I had to change the username to my email address.
Thank you.
