### ISSUE TITLE
Stop browser from opening for update notification

### ISSUE THREAD

**Issue by 0mijd9gjfk4fgd** [Nandaka/PixivUtil2#875]
### Prerequisites

* [x] Did you read FAQ section?
* [not applicable] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

PixivUtil2 recently started nagging me by opening a browser window that shows me the newest release that's available every time I start.
Is there any official way to stop that? I don't  want to immediately upgrade every time an update is available and these "browser popups" are getting very annoying..

### Steps to Reproduce

1. start PixivUtil2
2. wait for browser to popup

**Expected behavior:** no browser to popup

**Actual behavior:** a new browser window opens

### Versions
20201031

**Comment by byjtje** [comment]
Change `openNewVersion` to False in your config.ini

**Comment by 0mijd9gjfk4fgd** [comment]
Thank you! :)

**Comment by byjtje** [comment]
You're welcome :)
