### ISSUE TITLE
PixivUtil saving files to System32

### ISSUE THREAD

**Issue by HotelNo1234** [Nandaka/PixivUtil2#876]
### Prerequisites

* [✓] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [✓] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [✓] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

I'm not very good with computers so forgive me if I'm not very good at the lingo. But essentially I was downloading some files with the tool, but instead of going to the specific folder with the app, I just searched it up and used the app that came up in the search. This then started to save files in my System32 directory. 

After the files were all saved to System32, I couldn't find them anymore. They don't exit on my PC. Although, when trying to download them again PixivUtil simply tells me that the files are already downloaded. 

I use Windows 10 if that helps. I've also added some screenshots below if that helps. 
![Capture](https://user-images.githubusercontent.com/75468597/101130925-80bfaf80-3658-11eb-9061-d0164118924d.PNG)
![Capture2](https://user-images.githubusercontent.com/75468597/101130931-82897300-3658-11eb-80b1-123f7dc449eb.PNG)

**Comment by Nandaka** [comment]
Please read the https://github.com/Nandaka/PixivUtil2/blob/master/readme.md

Are you running the executables from shortcut? You need to set `Start In` to the location of the application, else it will follow the `cmd.exe` location
![image](https://user-images.githubusercontent.com/836867/101148905-2a06a580-3659-11eb-9e69-50d57786f2ce.png)

Also you can set `rootdirectory` to a specific folder to set the download directory.

**Comment by HotelNo1234** [comment]
Thanks for the help @Nandaka. Sorry for bothering you I'm just really stupid when it comes to code and stuff.
