### ISSUE TITLE
[Feature Request] Create folders for multi image works

### ISSUE THREAD

**Issue by As4shi** [Nandaka/PixivUtil2#879]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Not sure if this is implemented or not, I'm trying to find a way to create a folder for works that have multiple images.

To elaborate a bit, when there is only one image by work it would be saved to the "%artist% (%member_id%)" directory, but when there are multiple images by work it would create a folder named as "%urlFilename% - %title%" and save the files from this work inside.

**Expected behavior:** [What you expected to happen]
I want files to be saved like that:
40原 (554102)\86133813 - きなこ衣替え\86133813_p0.jpg <-- multiple images by work id
40原 (554102)\86133813 - きなこ衣替え\86133813_p1.jpg
40原 (554102)\76091634_p0.png <-- only 1 image by work id

**Actual behavior:** [What actually happened]
FIles are saved as:
40原 (554102)\86133813_p0.jpg
40原 (554102)\86133813_p1.jpg
40原 (554102)\76091634_p0.png

### Versions
v20201130

**Comment by Nandaka** [comment]
check https://github.com/Nandaka/PixivUtil2#filename and use different `filenamemangaformat` for manga.

**Comment by As4shi** [comment]
Thank you, that worked. I thought filenamemangaformat was only for content under the Manga tab.
