### ISSUE TITLE
20150715 login error

### ISSUE THREAD

**Issue by Ouxhi** [Nandaka/PixivUtil2#88]
On your blog you requested that I create a ticket here: 
I’m getting this error in the 20150715 version: 
Error at doLogin(): (< type 'exceptions.NameError' >, NameError("global name 'res_url' is not defined",), < traceback object at 0x02C4CDF0 >)

edit: I had to put spaces between < and > because it would not display it in my ticket.

**Comment by BluABK** [comment]
It seems to be a badly handled authentication error. 

I got mine working by deleting the 'cookie' item in the authentication section of config.ini. The script will recreate it.

**Comment by Ouxhi** [comment]
Deleting the numbers in the 'cookie' line and saving the the config.ini file seemed to work. Thanks. I'm not sure what caused this to happen though, it happened in an older version also, so I got this new version and it happened again.

**Comment by Nandaka** [comment]
I'm not so sure why it failed to log in.

As for ``` 'res_url' is not defined`` is programming error, I forgot to initialize the variable before use.

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/PixivUtil2/releases/tag/pixivutil20150725-beta1

**Comment by Ouxhi** [comment]
The 20150725-beta1 seems to have fixed the issue, I no longer see that error and I can login just fine now. Thank you.
