### ISSUE TITLE
batch download fails when trying to download an image with series information

### ISSUE THREAD

**Issue by riQwn** [Nandaka/PixivUtil2#880]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

The batch job runs normally until it encounters an image with series information. When it tries to write series information to a json file, the following error occurs: "AttributeError: 'JobOption' object has no attribute 'filenameSeriesJSON'"

### Steps to Reproduce

1. Enable includeseriesjson in config.ini
2. Start a batch job that includes an image with series information, e.g. in a single image id batch job.

**Expected behavior:**

Images are downloaded and a json file containing series information is written to the location assigned in config.ini

**Actual behavior:**

Images are downloaded, but when trying to write the series json the following error occurs:

"AttributeError: 'JobOption' object has no attribute 'filenameSeriesJSON'"

### Versions

v20201207-beta1

**Comment by byjtje** [comment]
Will be fixed in https://github.com/Nandaka/PixivUtil2/pull/874
