### ISSUE TITLE
Missing content_provider.json

### ISSUE THREAD

**Issue by GerhardSauer** [Nandaka/PixivUtil2#881]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
Enhancement
Please make it independent of workind directory for content_provider.json (like in #846).
Thank you.

### Steps to Reproduce

1. not use pixiv tool binary directory as working directory
2. e.g. fanbox download
3. Error getting FANBOX posts of artist: FanboxArtist(xxx, xxx, xxx) ==> Missing content_provider.json, please redownload application!

**Expected behavior:** [What you expected to happen]
should work independent of working directory

**Actual behavior:** [What actually happened]
requires working directory for content_provider.json to be found.

### Versions
tested with november and december (beta) release

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
you can always get it from https://github.com/Nandaka/PixivUtil2/blob/master/content_provider.json

**Comment by GerhardSauer** [comment]
I have the file and it is in the same folder as the PixivUtil2.exe.
But I'm not in this directory (working directory) with the command line.
Therefore I would like to have the behavior, that it works independent of my working directory, that the file is searched in the same location as the PixivUtil2.exe is.

**Comment by Nandaka** [comment]
how do you access it? are you using windows shortcut?

**Comment by GerhardSauer** [comment]
I'm on a network folder and use the absolute path to PixivUtil2.exe, which resides on c:\users\... within the command line.
It's the same issue only with a different file like #846 
If I would copy the content_provider.json to the network folder ( working directory) it would work, but I want all application files in the pixiv util folder.

**Comment by Nandaka** [comment]
try latest beta? It will try to resolve based on the executeable location first.

**Comment by GerhardSauer** [comment]
works, thank you!

**Comment by Nandaka** [comment]
same to you, also Merry Christmas 🎄 and Happy New Year 🥳 (soon) to you too.
