### ISSUE TITLE
After KeyError('isAdContainer') is solved, Error at process_tag_list:() occurs.

### ISSUE THREAD

**Issue by sky112475** [Nandaka/PixivUtil2#882]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
When I attempt to download an image using a tag, the error below occurs.

Unknown Error: (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'loadConfig'",), <traceback object at 0x036DE868>)

This error occurs only in commands that use tags (like input 3, 7).

If I enter more than 2 tags separated by spaces, an additional line of error message will be added.

Error at process_tag_list(): (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'loadConfig'",), <traceback object at 0x03743708>)
Unknown Error: (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'loadConfig'",), <traceback object at 0x036DE868>)

### Steps to Reproduce

1. Input 3 or 7(If input 7, you will prepare taglist.txt file.)
2. I input 3
3. Input 'tags'
4. Input 'Bookmark Count'. I left it blank.
5. Input 'Use Partial Match'. I input 'y'.
6. Input 'Oldest first'. I input 'y'.
7. Input 'Start Page'. I letf it default.
8. Input 'End Page'. I letf it default.
9. Input 'Start Date'. I input '2020-12-12'.
10. Input 'End Date'. I input '2020-12-05'.
11. Input 'Search type'. I input 'a'.

12. Unknown Error: (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'loadConfig'",), <traceback object at 0x036DE868>)
traceback object's hexcode is change every attempt. 

### Versions
pixivutil20201211-beta2

I would like to attach a log file when an error occurs, but this error simply shuts down the program without leaving any logs. (pixivutil.log.n file contains only information about the download history. )
What action should I take?

**Comment by mugi-jiichan** [comment]
Hi,

that happens as well if you're using option 7 to work on a tag list which worked perfectly fine with 20201207-beta1.

Input: 7
Tags list filename [tags.txt]:
Use Wildcard[y/n]: y
Oldest first [y/n]: y
Bookmark Count:
Start Page (default=1):
End Page (default= 0, 0 for no limit):
Start Date [YYYY-MM-DD]: 2020-12-01
End Date [YYYY-MM-DD]: 2020-12-12
Reading: ./tags.txt
Error at process_tags_list(): (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'loadConfig'"), <traceback object at 0x03D9F628>)
Unknown Error: (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'loadConfig'"), <traceback object at 0x03D9F528>)
press enter to exit.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/PixivUtil2/releases/tag/v20201212-beta3

**Comment by sky112475** [comment]
Oh, it's clearly solved! Thank you for you fast feedback.
