### ISSUE TITLE
Avatar download not working for some members

### ISSUE THREAD

**Issue by byjtje** [Nandaka/PixivUtil2#883]
### Description

Avatar download failing for some members. Background download still works.

### Steps to Reproduce

It seems to depend on the member/ their avatar, can consistently reproduce it once you find one.
E.g. https://www.pixiv.net/users/4991959/

**Comment by Nandaka** [comment]
Got HTTP Error 404 for `HTTP Error 404: Not Found at https://i.pximg.net/user-profile/img/2015/12/05/15/34/54/10204330f289e914351e9d84b475bbd68df137.png`
![image](https://user-images.githubusercontent.com/836867/102363075-08f66b00-3ff0-11eb-9e65-7c6942824e8c.png)

It does some string replacement to get the full avatar images frpm `https://www.pixiv.net/ajax/user/4991959`
![image](https://user-images.githubusercontent.com/836867/102364653-aa31f100-3ff1-11eb-846d-a6933a823a9c.png)

Should I keep the original avatar url, and do some handling if it is not available or just use the original url?

**Comment by byjtje** [comment]
I was hoping that there might be a way to get the original avatar file, but looking closer into it, `curl 'https://i.pximg.net/user-profile/img/2015/12/05/15/34/54/10204330_50f289e914351e9d84b475bbd68df137.png' -H 'Referer: https://www.pixiv.net/' --output test.png` returns the same output as _170. So I guess the original files are just gone?

Although I am not sure why we are getting a 404 then.

**Comment by byjtje** [comment]
Fixed with https://github.com/Nandaka/PixivUtil2/pull/874/commits/e90254f7ef609ffc62bbfcc1e2cc350a0b63191a , although it could likely be done more elegantly.
On a sidenote, is there any need to do replacing of _50 and _170? Aren't `imagebig` guaranteed to be _170 and `image` _50?

Interestingly enough the 2 images I've encountered so far were both "max size" at _170, guess I just got unlucky

**Comment by Nandaka** [comment]
previously, the avatar images doesn't have those size attached to get the full size.

**Comment by byjtje** [comment]
> previously, the avatar images doesn't have those size attached to get the full size.

Sorry to ask, but what do you mean?

**Comment by Nandaka** [comment]
some times ago, the url to the avatar image doesn't have _170 or _50 on it

**Comment by Nandaka** [comment]
Here is the sample url with `_170` and without with different size and notice the background transparancies
`https://i.pximg.net/user-profile/img/2018/02/01/23/55/46/13768317_dc1474fef3dc982ade71c1b2dbf32d9e_170.png`
`https://i.pximg.net/user-profile/img/2018/02/01/23/55/46/13768317_dc1474fef3dc982ade71c1b2dbf32d9e.png`

side by side 
![image](https://user-images.githubusercontent.com/836867/102562901-00e31c00-4113-11eb-8ba8-cb370e95ca48.png)

**Comment by byjtje** [comment]
> Here is the sample url with `_170` and without with different size and notice the background transparancies

Ah yes I know that, and that's what I did to fix it ^^
I meant what the point of https://github.com/Nandaka/PixivUtil2/blob/f546645be580dd2eb618f143f4b73a36f7addd22/PixivArtist.py#L144 is, since `imagebig` is guaranteed to be _170 and `image` _50? Are there any exceptions?

**Comment by Nandaka** [comment]
not sure if there is another source that can have the avatar images, maybe in the mobile client api? It is marked as medium.

`https://app-api.pixiv.net/v1/user/detail?user_id={member_id}`
![image](https://user-images.githubusercontent.com/836867/102615966-bd6bca80-4171-11eb-8211-6de3c23e7b87.png)

**Comment by byjtje** [comment]
Hm, looking into it, normally pixiv changes the _170 even when the original image is already small enough, making the _170 bigger. However https://www.pixiv.net/users/4991959/ has an identical file for the _170.

https://github.com/Nandaka/PixivUtil2/blob/f546645be580dd2eb618f143f4b73a36f7addd22/PixivArtist.py#L67 there is not a single fromImage=True call, I guess we can remove that too then
