### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pm175** [Nandaka/PixivUtil2#884]

**Comment by pm175** [comment]
hi, i just keep getting this error (FANBOX also have) and i can't download 
![error](https://user-images.githubusercontent.com/76242150/102685853-0a08e180-4216-11eb-9baf-fbaad88ae17e.png)

**Comment by Nandaka** [comment]
change where you extract the zip file. don't put it in `C:\Users\...`, also check the readme first.

**Comment by pm175** [comment]
> change where you extract the zip file. don't put it in `C:\Users\...`, also check the readme first.

hmm, i don't really understand

**Comment by pm175** [comment]
> change where you extract the zip file. don't put it in `C:\Users\...`, also check the readme first.

ok, i understand, thank you

**Comment by pm175** [comment]
> change where you extract the zip file. don't put it in `C:\Users\...`, also check the readme first.

uhm may i ask can this code download paid content on FANBOX, i've tried for some but it's just keep saying error
i guess no ???

**Comment by pm175** [comment]
> > change where you extract the zip file. don't put it in `C:\Users\...`, also check the readme first.
> 
> uhm may i ask can this code download paid content on FANBOX, i've tried for some (for paid posts) but it's just keep saying error
> i guess no ???

**Comment by Nandaka** [comment]
also, you need to subscribe to the fanbox user if you want to download the files.

There is no way to download the paid contents unless you are subscribed.
