### ISSUE TITLE
GIF only created from second half of Ugoira

### ISSUE THREAD

**Issue by charzho** [Nandaka/PixivUtil2#885]
### Prerequisites

* [x ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Ugoira is composed of two halves (120 frames total)
PixivUtil2 with default settings seems to only create a GIF from the second half

### Steps to Reproduce

1. Download individual gallery (NSFW) https://www.pixiv.net/en/artworks/86401819
2. View zip (120 frames)
3. View gif (60 frames, the second half)

**Expected behavior:** The GIF should contain the full 120 frames, or if it's specified in the ugoira (not sure if Pixiv did something like this), 2 GIFs of 60 frames

**Actual behavior:** The GIF only has the second half of the ugoira

### Versions
v20201207-beta1

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
I'm not sure why, somehow the ffmpeg command didn't process the whole images.
`ffmpeg.exe -y -i "./i.ffconcat" -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" "./temp.gif"`

[i.ffconcat.txt](https://github.com/Nandaka/PixivUtil2/files/5720947/i.ffconcat.txt)

You can use webp or webm, which produce the full images.

**Comment by Nandaka** [comment]
Related to #802

Checked the ugoira file, looks like the one of the image has error inside and it throw warning in the console when I run the ffmpeg command manually.
![image](https://user-images.githubusercontent.com/836867/102715045-977b2d00-430d-11eb-9353-281b153778af.png)

I can somehow avoid this by converting the images to mp4 first then to gif, but this will increase the processing time.

I recommend you to use webp instead.

**Comment by byjtje** [comment]
> I'm not sure why, somehow the ffmpeg command didn't process the whole images.
> `ffmpeg.exe -y -i "./i.ffconcat" -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" "./temp.gif"`

It's the -filter_complex part causing that, though no clue about ffmpeg filters and how to fix them. Could just make them optional for the config file I guess, with some working standard set

**Comment by Nandaka** [comment]
Not really, I tried to convert it to mp4/webm using `./ffmpeg.exe -y -i "./input/i.ffconcat" -c:v libvpx-vp9 -lossless 1 -vsync 2 -r 999 -pix_fmt yuv420p "output.mp4"` and it able to fully process the whole frames.
![image](https://user-images.githubusercontent.com/836867/102788732-117ae700-43de-11eb-8935-160a452f506d.png)

Then I'm using `./ffmpeg.exe -y -i "output.mp4" -filter_complex "[0:v]split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" -loop 0 "output.gif"` to convert it to gif and it works.
![image](https://user-images.githubusercontent.com/836867/102788793-29526b00-43de-11eb-8d6d-89d8ba6bfaf7.png)

I think the combination of `ffconcat` with gif conversion that cause the problem (ffmpeg bug?)

**Comment by byjtje** [comment]
@Nandaka Try using `./ffmpeg.exe -y -i "./input/i.ffconcat" output.gif`. That produces a full .gif

**Comment by Nandaka** [comment]
filesize is bigger by 10mb and not optimized btw.

**Comment by byjtje** [comment]
> filesize is bigger by 10mb and not optimized btw.

I know, just saying what the cause is, not what the best way to fix it is (although it's even bigger here).
