### ISSUE TITLE
Error when using with CLI arguments

### ISSUE THREAD

**Issue by bakatrouble** [Nandaka/PixivUtil2#886]
When I try to launch the util with cli arguments (`./PixivUtil2.py -s f3 XXXXXXXX`), it errors with
`Unknown Error: (<class 'TypeError'>, TypeError('expected string or bytes-like object'), <traceback object at 0x7f120c7a8ac0>)`

Fixed locally by replacing https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L767 with `post_ids = ' '.join(args)`, but I'm sure the issue is more global and requires a proper fix in other places, so I'm not creating a pull request

Version 20201212-beta3

**Comment by byjtje** [comment]
Should be fixed with the changes to PixivHelper.py in https://github.com/Nandaka/PixivUtil2/pull/874/commits/9c3caf9de0f1956d177820601083dd45a34a3809 , could also extend it to more stuff in PixivUtil2.py if wanted

**Comment by bluerthanever** [comment]
ah... hmm. i should have realized this bug.... sorry.
actually i think i would just add an indent in the front of the following line:
https://github.com/Nandaka/PixivUtil2/blob/f546645be580dd2eb618f143f4b73a36f7addd22/PixivUtil2.py#L771
sorry about that.
