### ISSUE TITLE
Permanent damage to file 'db.sqlite' will occur when program operation is performed with real-time synchronization on.

### ISSUE THREAD

**Issue by sky112475** [Nandaka/PixivUtil2#887]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Operating PixivUtil2 while operating real-time synchronization programs such as Google Backup and Sync, Synology Drive, and Mega Sync will result in permanent db.sqlite file corruption.
This damage is irreversible, and once a DB has been compromised, the program cannot run due to db.sqlite file's damage.

### Steps to Reproduce

1. Include the PixivUtil2 folder in the backup program's real-time backup category.
2. Run the download in the usual way.
3. During the download, the following message is output and the DB file is permanently corrupted.
<img src="https://1.bp.blogspot.com/-X_eSyoO-Y48/X-NQwIrhLDI/AAAAAAAAGXc/HphMjyV6c3IPz9NeIx_84sSfjKH1RME_wCLcBGAsYHQ/s16000/%25EC%258A%25A4%25ED%2581%25AC%25EB%25A6%25B0%25EC%2583%25B7%25281804%2529.png">

<img src="https://1.bp.blogspot.com/-sIZ5KRFjzEc/X-NQwKcBHZI/AAAAAAAAGXg/qBE3pM0CSEsIW4YeCPkt3IYKyXW-Z8WSgCLcBGAsYHQ/s16000/%25EC%258A%25A4%25ED%2581%25AC%25EB%25A6%25B0%25EC%2583%25B7%25281805%2529.png">
    (I suspect that the cause of this lies in conflicts that occur during the process of temporarily disabling and uploading DB files by real-time synchronization programs that detect changes in DB files.)

**Expected behavior :** If the same problem occurred in beta2 version, the program would simply shut down, and if the same operation was repeated after restarting, the download could be resumed from where the error occurred. 

**Actual behavior :** However, from version 3 of beta, the program cannot run without a pre-backup DB due to permanent damage.

### Versions
beta3

Is there anything else I can do but pause my sync program at download time?

**Comment by Nandaka** [comment]
No DB handling changes between beta2 and beta3, see https://github.com/Nandaka/PixivUtil2/compare/v20201211-beta2...v20201212-beta3

I guess you just unlucky? I'm backing up my db using dropbox and I have no issue.

**Comment by sky112475** [comment]
Well... I guess I was just really unlucky. Today, I ran the download by running the sink program habitually, but there was no problem.
