### ISSUE TITLE
Images Not Found On Windows 10

### ISSUE THREAD

**Issue by danthonywalker** [Nandaka/PixivUtil2#89]
I have upgraded to Windows 10 and the script seemed to have been working just normally right until it kept hitting pages around the 800 mark for me. Ran it two times with debug and it was always stopped on the 800 mark saying there's no more images. Note, this tag has well over 2 million entries so it's not possible there's only 800 pages and it worked just fine before I upgraded.

Here are the HTML dumps: https://drive.google.com/folderview?id=0B9sysGP4FUlyfjZlM196bmZBcXBfQk91ZjkyTmhVUmVhYkxoY3NOcFN3Rk1FNGY1LVVkV00&usp=drive_web

Doing my own little bit of investigating I'm wondering if it's an issue with Edge/IE? I haven't downloaded Chrome yet (because honestly I really like Edge), but when visiting these pages on Pixiv through Edge there are no images on these pages. What's even more peculiar is that going back a few pages before it ends each page only shows about 3/4 entires. Which is interesting, I have no idea why. So would possibly installing Chrome fix this issue?

**Comment by NHOrus** [comment]
This sounds like Pixiv issue, not downloader issue.

**Comment by Nandaka** [comment]
It should have nothing to do with windows, as it doesn't use any browser component.

For some reason, Pixiv server return image list without illust_id values in it.

**Comment by vampiricwulf** [comment]
Worksforme and I'm on Windows 10.

**Comment by danthonywalker** [comment]
Looks like it was the Pixiv server. Strangely enough it lasted for quite a while, so I thought otherwise, but it suddenly works again. False alarm.
