### ISSUE TITLE
[Feature Request] Support Grouping by Bookmark Count

### ISSUE THREAD

**Issue by YukihoAA** [Nandaka/PixivUtil2#891]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

If there is grouping option at filename format like ~~100users入り, it would be great.

like..

illust          bookmarks           %bookmarks_group%
A has    150 bookmarks    =>    100
B has    234 bookmarks    =>    100
C has    280 bookmarks    =>    250
D has    516 bookmarks    =>    500
E has    1300 bookmarks  =>    1000

https://dic.pixiv.net/a/users%E5%85%A5%E3%82%8A

**Comment by YukihoAA** [comment]
@Nandaka it works fine with images has more than 100.

I want to group image by folder with bookmarks_group, but when it has less than 100, image saved root dir of drive not even root dir of pixivutil.

it will be cool if %bookmarks_group%/ handled as %R-18%/, to saved in current working dir rather than root dir. thank you.

**Comment by Nandaka** [comment]
@YukihoAA  yes, only 100+, as it is defined in the rule.

Refer to https://github.com/Nandaka/PixivUtil2/commit/74dc2c8ab46a033a77c675526241c824884262cb#diff-b88d4c905c089498282cfd5e3e597bae2328a3110693e67aa8cc536e7612b8a6R297-R314

Should I return `no_bookmark_group` or `no_group` if it is less than 100 bookmarks?

**Comment by YukihoAA** [comment]
No, If bookmark_count is less than 100,

`%bookmarks_group%` will be ` `  same as now,

`%bookmarks_group%/` will be ` `  too, rather than  `/`, works as `%R-18%/`

**Comment by YukihoAA** [comment]
Previously, if I use `%R-18%\%bookmarks_group%\%image_id%_p0` for filename, it worked as below.

return value of make_filename():
No R-18, bookmarks 54   was `\\123124_p0.png`
R-18, bookmarks 54         was `R-18\\123124_p0.png`
No R-18, bookmarks 154 was `\100\123124_p0.png`
R-18, bookmarks 154       was `R-18\100\123124_p0.png`

`\\` means root dir of disk drive so I replaced `\\` to `\` to works properly, PR #894

now:
`\123124_p0.png` `R-18\123124_p0.png` `\100\123124_p0.png` `R-18\100\123124_p0.png`

**Comment by YukihoAA** [comment]
I have more idea related to this function.

It will be cool that if i can set custom grouping factor.

For example
If you set `bookmark_group_unit = 100/250/500/1000/5000/10000` (defualt) than` %bookmark_group%` will be set by separator 
`/`: ~100
`/100`: 100~249
`/250`: 250~499
`/500`: 500~999
`/1000`: 1000~4999
`/5000`: 5000~9999
`/10000`: 10000~

you can slice like `100/500/5000`, than grouping` /%bookmark_group%` will be
`/`: ~100
`/100`: 100~499
`/500`: 500~4999
`/5000`: 5000~

**Comment by YukihoAA** [comment]
@Nandaka I hope this option can used in work 5 and 11 too
