### ISSUE TITLE
Pixiv sketch load only non R-18 pictures

### ISSUE THREAD

**Issue by hatabbich** [Nandaka/PixivUtil2#892]
Description

Hello, so.. all issue in the title ^^

### Steps  
(for example)
1. input [s1]
2. input [https://sketch.pixiv.net/@ex_rumia_project]
3. [done]

**Expected behavior:** [download all sketch pictures from artist page]

**Actual behavior:** [download only All ages, non R15/R18 works]

P.S Happy new year ^^

**Comment by Nandaka** [comment]
check your settings in https://sketch.pixiv.net/settings

**Comment by hatabbich** [comment]
> check your settings in https://sketch.pixiv.net/settings

Ok, that's my setting on Sketch and Pixiv
![22222](https://user-images.githubusercontent.com/9683560/103769855-1d99b200-5036-11eb-9fd8-76b9db7ec626.PNG)
![111](https://user-images.githubusercontent.com/9683560/103769858-1e324880-5036-11eb-912d-c069352bea7e.PNG)

**Comment by Nandaka** [comment]
ok, looks like pixiv sketch has additional custom header similar like pixiv fanbox. I'm looking on it.
