### ISSUE TITLE
"usertagasdir" option in Filename section does not work correctly

### ISSUE THREAD

**Issue by YukihoAA** [Nandaka/PixivUtil2#893]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

"usertagasdir" option in Filename section does not work correctly.
it creates folders under previous tag folder which should created at root dir.

### Steps to Reproduce

1. set "usetagsasdir" option to "True" in "Filename" section, "config.ini" 
2. create tags.txt, multiple tags separated by new line,

ex>
白上フブキ
チノ
ユニ

3. run PixivUtil2 as 7. tags list mode.

**Expected behavior:** tag named folders should created at root dir.
![image](https://user-images.githubusercontent.com/20253131/103768244-83e9f900-5065-11eb-8a7a-879ea3927135.png)

**Actual behavior:** tag named folders created under previous tag folders
![image](https://user-images.githubusercontent.com/20253131/103768313-9a905000-5065-11eb-9739-9c03aa2a1d71.png)

### Versions

20201211-beta-3

**Comment by bluerthanever** [comment]
Seems to  be caused by these codes:
https://github.com/Nandaka/PixivUtil2/blob/bb97a4df7b1184cd431610837e122d8795638409/PixivTagsHandler.py#L40-L42
`rootDirectory` of config  instance was changed directly with `+=`
