### ISSUE TITLE
download from bookmarked artists doesn't seem to add to artist db?

### ISSUE THREAD

**Issue by somebody1234** [Nandaka/PixivUtil2#895]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

as title says. "show all member" gives nothing, "show all images" gives 10k+ row count.
as a side effect, this makes day last updated useless

### Steps to Reproduce

1. use pixivutil (i'm on arch linux, however since image table works fine i doubt that's the problem)
2. select 'manage database'
3. select 'show all member'

**Expected behavior:** [What you expected to happen]
shows all members that have currently been processed

**Actual behavior:** [What actually happened]
shows 0 members

### Versions
20210108-beta4

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by bluerthanever** [comment]
is the `autoAddMember` option in config set to True?

**Comment by somebody1234** [comment]
no it isn't, i guess that was it...

**Comment by bluerthanever** [comment]
try to set it to True and download from bookmarked artist again?

**Comment by somebody1234** [comment]
they're in the db now, however when i cancel in the middle and download from bookmarked artists again, it doesn't skip artists already in db, is this normal? (are they just pushed to the end of the list?)

**Comment by bluerthanever** [comment]
hmm. can you tell me what the values of the options in your config are, and what you expect to happen? for some lately updated artists to be skipped obviously though.
for example, your `dayLastUpdated` is 3 or your `checkUpdatedLimit` is 5 and you expect those who match the criteria to be skipped. and somehow it's not happening.

and when you cancel in the middle, do you do it by ctrl+c, or close the program?

**Comment by somebody1234** [comment]
- `daylastupdated` is 7
- `checkupdatedlimit` is 0
- 0 artists are being removed from the "download from bookmarked artists"
- cancel by ctrl+c

**Comment by bluerthanever** [comment]
hmm. just checked the codes, and it seems that when you use download from bookmarked artist, it doesn't check those options.

`dayLastUpdated` seems to work only with `download by list` so far, and `checkUpdateLimit` seems to be a image check option, and since it's set to 0 it's skipped.

i guess you could export your bookmarked artists and import them first, then download from db with menu 4. or you could go though the whole bookmarked artist for once, and then use menu 4.

**Comment by somebody1234** [comment]
i *could* but, well, let's just say the reason i don't is because it's not practical for me

**Comment by somebody1234** [comment]
kinda sorta related issue... seems like fanbox posts aren't added to db at all? they all say "local file exists" rather than "exists in db"

**Comment by bluerthanever** [comment]
for fanbox there is an option called `checkDBProcessHistory`, i think the description should be in readme file. if it's set to false, db download history would not be checked before each download.

**Comment by cglmrfreeman** [comment]
Can I ask why both `autoAddMember` and `checkDBProcessHistory` are defaulted to `False`? Serious question. I rely on the database to keep my archive consolidated and reference the database directly when I need something specific. Knowing now that once these features became added to PixivUtil2 that already was keeping a database that _won't_ add items downloaded to my database is frustrating.

**Comment by bluerthanever** [comment]
As I remembered, `checkDBProcessHistory` is just an option for skipping fanbox posts which have been downloaded before and not changed since. Fanbox contents will be recorded in db by default. But `autoAddmember` doesn't seem to add fanbox creators into db yet.

And speaking of consolidated db.... my db file was mysteriously deleted a couple of days ago.... ;(
