### ISSUE TITLE
Suspended Fanbox artist causing Fanbox download functionalities to stop; artist also isn't actually suspended

### ISSUE THREAD

**Issue by Zekira** [Nandaka/PixivUtil2#896]
### Prerequisites

* [Y] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [Y] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [Y] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Related, maybe even same as https://github.com/Nandaka/PixivUtil2/issues/873

Artist ID is 43189578. Their fanbox is working fine. (nsfw warning).

Should also be noted that their non-fanbox has a different ID for some reason(58633620).

### Steps to Reproduce

1. Use any of the f# functions. f2 should be fine.
2. In Artist ID, input 43189578.
3. Error shown:
Error getting FANBOX artist by id: 43189578 ==> 該当ユーザーのアカウントは停止されています。
Unknown Error: (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'artist' referenced before assignment"), <traceback object at 0x03F03408>)

**Expected behavior:** Should get the artist successfully, or if the user really is suspended, they shouldn't be included in the retrieval of the following list, or skip over it instead and don't close the program so that batch functions like f1, f4, and f5 don't break in between.

**Actual behavior:** Error causes program to exit despite user existing

### Versions

20210108-beta4

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by bluerthanever** [comment]
it was somehow changed in #873 to: if you have downloaded from their pixiv and their information is restored in DB before, PixivUtil2 would use the stored information in db to generate filenames. otherwise the error would be thrown as before

the reason for keeping throwing such error is because if some filename format might contain placeholders whose information could only be retrieved from pixiv.net, namely artist name and token, filenames could be wrong.

i would change it to continuing processing next artist instead of stopping the whole program though. that was not though out.

**Comment by Zekira** [comment]
> it was somehow changed in #873 to: if you have downloaded from their pixiv and their information is restored in DB before, PixivUtil2 would use the stored information in db to generate filenames. otherwise the error would be thrown as before
> 
> the reason for keeping throwing such error is because if some filename format might contain placeholders whose information could only be retrieved from pixiv.net, namely artist name and token, filenames could be wrong.
> 
> i would change it to continuing processing next artist instead of stopping the whole program though. that was not though out.

Is this a local db or something? I was wondering if something good would happen if that database could be rebuilt

**Comment by bluerthanever** [comment]
yes, it's a local db. filename should be `db.sqlite` by default.

**Comment by Zekira** [comment]
Just confirming that renaming/deleting the db.sqlite to do a fresh start didn't really do anything and I'm still encountering the same error and behavior.

**Comment by bluerthanever** [comment]
...well, a brand-new db certainly doesn't contain the information for the suspended artist, so it's not going to pass

**Comment by bluerthanever** [comment]
sorry that i found a bug that's causing the program to fail in the middle... will fix that.

**Comment by bluerthanever** [comment]
okay, I pulled a new request, hopefully it would reach your expectation.
when the artist is suspended on pixiv, if in your fanbox filename formats, there is either `%artist%` or `%artistToken%`, you would be required to provide those for that artist, otherwise, the procedure would continue.
