### ISSUE TITLE
Improve FANBOX HTML output

### ISSUE THREAD

**Issue by LizeHelesta** [Nandaka/PixivUtil2#899]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

0. The sample post: [726146](https://www.fanbox.cc/@mataro/posts/726146)

1. FANBOX HTML output doesn't process the styles of block p.

    Post Info:

    ![Snipaste_2021-01-26_18-10-00](https://user-images.githubusercontent.com/61379118/105831486-bc944700-6001-11eb-841a-a34583320ef0.png)

    Original Post Appearance:

    ![Snipaste_2021-01-26_18-08-57](https://user-images.githubusercontent.com/61379118/105831420-a8e8e080-6001-11eb-93b6-36d56d937085.png)

    HTML output:

    ![Snipaste_2021-01-26_18-29-28](https://user-images.githubusercontent.com/61379118/105833719-8dcba000-6004-11eb-973c-0fdb566c4c3d.png)

    I had try to solve it by myself:
    ```python
                        else:
                            block_text = block["text"]
                        ### Start
                        if "styles" in block:
                            for i in reversed(range(0, len(block["styles"]))):
                                style = block["styles"][i]
                                if style["type"] == "bold":
                                    style_offset = style["offset"]
                                    style_length = style["length"]
                                    block_text = block_text[:style_offset+style_length] + "</b>" + block_text[style_offset+style_length:]
                                    block_text = block_text[:style_offset] + "<b>" + block_text[style_offset:]
                                else:
                                    raise PixivException(f"Unknown style", errorCode=PixivException.OTHER_ERROR)
                        ### End
                        self.body_text = f"{self.body_text}<p>{block_text}</p>"
                    elif block["type"] == "image":
    ```

2. `BeautifulSoup.prettify()` will remove ideographic space `\u3000` which is important to keep the post layout neat in some japanese post.

    Original Post Appearance:

    ![Snipaste_2021-01-26_18-14-11](https://user-images.githubusercontent.com/61379118/105832513-0598cb00-6003-11eb-8751-b67a26291eaf.png)

    HTML output:

    ![Snipaste_2021-01-26_18-29-43](https://user-images.githubusercontent.com/61379118/105833753-9c19bc00-6004-11eb-85f7-a57a17eb9304.png)

    I also had try to solve it with dirty code:
    ```python
            page = page.replace("%text(non-article)%", token_text)

            page = page.replace("\u3000", "👩🏽‍🍳")
            page = BeautifulSoup(page, features="html5lib")
            imageATags = page.find_all("a", attrs={"href": True})
            for imageATag in imageATags:
                tag = imageATag.img
                if tag:
                    tag["src"] = imageATag["href"]
            root = page.find("div", attrs={"class": "root"})
            if root:
                root["class"].append("non-article" if self.type != "article" else "article")
            page = page.prettify()
            page = page.replace("👩🏽‍🍳", "\u3000")
            html_dir = os.path.dirname(filename)
    ```

### Versions

**20210108-beta4**

**Comment by bluerthanever** [comment]
Gee, style seems to be a tricky problem.
I guess I will try to find out the js script for that and take a look. Let's hope it's not too complicated.

I have to admit that even though I implemented this feature, I rarely take a close look that those html files, let alone compare them with the original post.

**Comment by LizeHelesta** [comment]
@bluerthanever I had take a look at js script, it is just one style `"BOLD"` nowadays.
Also I have another two suggestions after testing many post.

0. The sample post: [1337088](https://kamishimosou.fanbox.cc/posts/1337088)

1. Implement the block type `header`

    Post Info:

    ![Snipaste_2021-01-28_11-27-51](https://user-images.githubusercontent.com/61379118/106085905-0c872100-615c-11eb-9e7a-20b954a9f99c.png)

    Original Post Appearance:

    ![Snipaste_2021-01-28_11-28-03](https://user-images.githubusercontent.com/61379118/106085919-127d0200-615c-11eb-9dd0-a6db604c46e5.png)

    HTML output:

    ![Snipaste_2021-01-28_11-28-12](https://user-images.githubusercontent.com/61379118/106085930-1a3ca680-615c-11eb-80cc-c8d18685b0f8.png)

    I think `<h3>` is the right size header element in HTML output.

2. Replace empty `<p>` with `<br>`, because empty `<p>` has no line height.

    ![Snipaste_2021-01-28_11-33-14](https://user-images.githubusercontent.com/61379118/106086292-d1392200-615c-11eb-93a6-eb90fcd2e607.png)

    After replacing with `<br>`, we can shorten the default margin top and margin bottom of `<p>` to make output compact.

**Comment by bluerthanever** [comment]
Thanks, haha. It was late yesterday so I decided to do it today.
Okay, I will see what I can do here.

**Comment by Nandaka** [comment]
based on the css style for the header
```
cssText: ".iIbsJw .article__header-block { font-size: 24px; line-height: 30px; margin: 40px 0px 16px; }"
```

**Comment by bluerthanever** [comment]
i thin i will just use `<h2>` tags for headers as shown on page....? don't wanna write too many css styles.

**Comment by bluerthanever** [comment]
for the full-width space issue, i just changed from `prettify` to `decode`....
don't wanna study how it works for now.
