### ISSUE TITLE
Unkown error when download from fanbox (CloudflareCaptchaProvider)

### ISSUE THREAD

**Issue by feiguizz** [Nandaka/PixivUtil2#901]
I got an error when tried to download fanbox images, it has worked fine by yesterday,

Unknown Error: (<class 'cloudscraper.exceptions.CloudflareCaptchaProvider'>, CloudflareCaptchaProvider("Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter."), <traceback object at 0x03ACB2C8>)

**Comment by Nandaka** [comment]
can you try new release https://github.com/Nandaka/PixivUtil2/releases/tag/20210128

I have updated the library

**Comment by feiguizz** [comment]
sorry, I just took a try but seems the error still occurs.

`Unknown Error: (<class 'cloudscraper.exceptions.CloudflareCaptchaProvider'>, CloudflareCaptchaProvider("Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter."), <traceback object at 0x0445E2A8>)`

**Comment by Nandaka** [comment]
Looks like your ip address is marked by Cloudflare, you can try to manually login to fanbox and copy the cookie value to the config.ini.
```
    - Copy your session values from browser:
      1. Open Firefox.
      2. Go to https://www.fanbox.cc/ and login
      3. Right click the page and select View Page Info.
      4. Click the Security tab.
      5. Click the View Cookies button.
      6. Look for Cookie named = FANBOXSESSID.
      7. Copy the content value to config.ini to cookiefanbox.
```

**Comment by feiguizz** [comment]
It seems does not work for me, still working on change my ip with proxy
