### ISSUE TITLE
Is there a way to configure the folder name?

### ISSUE THREAD

**Issue by krax11** [Nandaka/PixivUtil2#904]
### Prerequisites

* [ ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I want to know if there is a way to configure the folder name when I download by member_id. I have configured [Filename] section in Config, so the files downloaded are like XXXXXXXX_pX.png , without "%title%" at the end of the filename. I want to have the username of the folder removed, so I just have the id number of the artist; the problem is that when I download after some time the files of a certain folder, as I remove manually the username of the artist, a new folder is created again, but with the username once again and I don't know if there is some way to avoid that using the Config.ini file...

**Expected behavior:** The new pictures are saved in the folder that corresponds to the artist (for example, the folder name is 44444444).

**Actual behavior:** A new folder of the same artist is created, but with the username, not just the artist id number (instead of downloading into 44444444 folder, it downloads files into a folder named, for example, Goodartist (44444444)).

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
see https://github.com/Nandaka/PixivUtil2#filename and https://github.com/Nandaka/PixivUtil2#filename-format-syntax

use '\' for folder separator.

**Comment by krax11** [comment]
Ok, I just figured out how to fix it like I wanted: _%member_id%\%urlFilename%_ THANKS!
