### ISSUE TITLE
[Help] FANBOX downloading error

### ISSUE THREAD

**Issue by asdf916** [Nandaka/PixivUtil2#909]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)? YES. I read it.
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? YES. I did.
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)? YES. I search and read a lot.

### Description

Failed to login using OAuth While Trying To Download Pixiv Fanbox. 

### Steps to Reproduce

1. Start PixivUtil2, with username, password, and cookie set in config.ini
2. Login succeeds, and it works well in pixiv image downloading.
3. choose f1 or f2 or f3 (Only FANBOX downloading, same error.)
4. max page set 0

**Expected behavior:** Downloads a members' fanbox works that I supported.

**Actual behavior:**  Failed to login using OAuth
[Example: it's on PixivUtil2.exe]
Input: f1
End Page =
Trying to log in FANBOX with saved cookie
FANBOX Login successful.
Getting supporting artists from https://api.fanbox.cc/plan.listSupporting
Found 1 artist(s) in supporting list
['59155222']
Reading C:\Users\(CENSORED)\(CENSORED)\pixivutil20210128\config.ini ...
Configuration loaded.
Getting artist information from https://api.fanbox.cc/creator.get?userId=59155222
Using OAuth to retrieve member info for: 59155222
Invalid grant_type parameter or parameter missing
Error getting FANBOX artist by id: 59155222 ==> Failed to login using OAuth

### Versions
pixivutil20210128

and I don't use proxy.
I can login PIXIV and FANBOX with Chrome normally.
'refresh_token' was always blanked.

今気付きましたが、コードから出てきた 'https://api.fanbox.cc/creator.get?userId=59155222'をChromeアドレスバーに入力して入ると、画面に{"error":"general_error"}だけが出てきます。 もしかしてこれが問題と関連したのではないでしょうか?

Plz help me, broooooooo

**Comment by bluerthanever** [comment]
this should be the same with #907, and should have been fixed in the latest commit.
no exe release yet.... are you running from compiled executive files?

**Comment by asdf916** [comment]
> this should be the same with #907, and should have been fixed in the latest commit.
> no exe release yet.... are you running from compiled executive files?

Umm...no, I just test with the latest releases. without commit.

But I checked that #907, and I've just tested with 201130ver, It work very well.

Thanks a lot, dear bluerthanever. I love you.

**Comment by bluerthanever** [comment]
>Umm...no, I just test with the latest releases. without commit.

you are using the released zip file instead of running from scripts, right? if so, maybe you need to wait for the next release.

>But I checked that #907, and I tested with 20201130ver, It works very well.

yes, because that version uses another method to get artist information... and i changed it to a way before that in #888.
but now pixiv is changing the API, which caused the issue you are encountering now,so i changed it again to what works.

**Comment by asdf916** [comment]
> yes, because that version uses another method to get artist information... and i changed it to a way before that in #888.
> but now pixiv is changing the API, which caused the issue you are encountering now,so i changed it again to what works.

OK, I understood. Thanks a lot.  I am grateful for your support. Have a nice day.

**Comment by bluerthanever** [comment]
you are very welcome.  φ(゜▽゜*)♪
