### ISSUE TITLE
Multiple Images at once

### ISSUE THREAD

**Issue by vampiricwulf** [Nandaka/PixivUtil2#91]
Maybe make an option so you can set how many images you want to download at once?
The slowest part of using this tool (for me) is that it goes meticulously one at a time, I blaze though each image, but there's a huge delay when an image ends and another begins.

**Comment by NHOrus** [comment]
Sadly, it appears that it can't be done easily. See GIL. And that's a pity.

It would be great if even downloading and checking for new images in other pixiv members could happen concurrently, so when one image gets downloaded, another is ready to get done.

**Comment by Nandaka** [comment]
Yap, no plan for multithreading for this app.

Your best plan is by running multiple instances on separate folder.

as for delay, maybe due to parsing or db access (not sure, need to check the logging).

**Comment by vampiricwulf** [comment]
I'll look into making multiple instances, thank you.
