### ISSUE TITLE
Feature Request: JSON Only Mode

### ISSUE THREAD

**Issue by Lachee** [Nandaka/PixivUtil2#911]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I would like the ability to save the image urls to the image json instead of downloading them.

I am developing a service for personal use that integrates a generic scrapper that can collect images from numerous sites. Recently Pixiv has stopped working because of their authentication changes and I found your utility tool. This seems to work and gets the information i am after: json of the tags, artists, title etc and the image files.

However, my scrapper handles image downloading itself. With the previous Pixiv implementation, it was able to download the images as it mimicked the correct referrer details. I cannot find a way however to disable image downloading and just save the urls.

The ability to save the image urls and not download the images would make this tool a perfect replacement. This could be done as a CLI argument, or perhaps even a config.

**Comment by byjtje** [comment]
Whilst I don't disagree with the idea, it seems like you'd be better off just scraping the JSON alongside your scrapper. The URLs for image JSONs are https://www.pixiv.net/ajax/illust/87416293 and so on

I wouldn't mind implementing something like this once I get my current stuff sorted out (which might take some time ^^)

**Comment by Lachee** [comment]
> Whilst I don't disagree with the idea, it seems like you'd be better off just scraping the JSON alongside your scrapper. The URLs for image JSONs are https://www.pixiv.net/ajax/illust/87416293 and so on
> 
> I wouldn't mind implementing something like this once I sort my current stuff out (which might take some time ^^)

Oh you are right. This is perfect for my needs and doesn't seem to require auth for nsfw images.

**Comment by Nandaka** [comment]
as mentioned by @byjtje, you can use the APIendpoint directly. This application is more for downloading directly.

You can also check https://github.com/Nandaka/PixivUtil2/wiki/WEB-RPC for the current API that I know of.
