### ISSUE TITLE
Long tags may cause problems

### ISSUE THREAD

**Issue by FGRemastered** [Nandaka/PixivUtil2#915]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ? (Latest non-beta was used)
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Long tags (that are created by translating Japanese characters into URL) cause the following error when used in conjunction with the member id (option 10 in main menu):

    Invalid grant_type parameter or parameter missing
    Error at process_tags() at page 1: (<class 'PixivException.PixivException'>, PixivException('Failed to login using OAuth'), <traceback object at 0x03F4E128>)
    Failed to login using OAuth

### Steps to Reproduce

1. Input: 10
2. Enter member id (ex. 160254)
3. Enter a long tag (ex. %E3%82%AC%E3%83%BC%E3%83%AB%E3%82%BA%2526%E3%83%91%E3%83%B3%E3%83%84%E3%82%A1%E3%83%BC)

**Expected behaviour:** The download should start after checking whether it's a valid member id

**Actual behaviour:** the program crashes with the above error

### Version
Latest stable as of 20.02.2021

**Comment by Nandaka** [comment]
from the error message, it looks like got nothing to do with long tags.

See #914
