### ISSUE TITLE
Existing db.sqlite overwritten by new release

### ISSUE THREAD

**Issue by Dezaimasu** [Nandaka/PixivUtil2#916]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

v20210221-beta2 release zip archive includes db.sqlite file. When extracting it to PixivUtil folder it overwrites it alongside with other existing files. This file shouldn't be overwritten. I had ~500mb db.sqlite file and now it's gone forever.

### Steps to Reproduce

1. Download v20210221-beta2 release archive file.
2. Extract its content to existing PixivUtil directory.

**Expected behavior:** No db.sqlite file in archive, existing db.sqlite is not overwritten.

**Actual behavior:** db.sqlite file from downloaded zip file overwrites existing file

### Versions
v20210221-beta2

**Comment by Nandaka** [comment]
Updated the zip file, sorry about that.
It is always recommended to backup your files before upgrading.
