### ISSUE TITLE
i cant login and it said i need captcha but on issue 500 said i need to copy new phpsession to config.ini file, the problem is that the config file is not in the file directory

### ISSUE THREAD

**Issue by SteveJohnson888** [Nandaka/PixivUtil2#917]
### Prerequisites

* [/ ] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ /] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ /] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

i dont have a config.ini file and cant
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/6028804/pixivutil.log)
 login

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
how do you run the executables? looks like the log file is not updated (it is my old log file).

You need to extract the zip file to a folder. Don't just run it from zip file directly as Windows's Compressed Folder feature will not extract the supporing files.
