### ISSUE TITLE
Downloading images without sending them into their own folder

### ISSUE THREAD

**Issue by Exonent-blast** [Nandaka/PixivUtil2#918]
This tool is really useful but I'd like to know if it's possible to download images into a folder without creating a new folder?
What I mean by this is, When an image is downloaded; A new folder with the artists name and ID is created. Would it be possible to somehow skip that and just stick the images into the folder?

**Comment by Nandaka** [comment]
see #833

**Comment by Exonent-blast** [comment]
> see #833

I see, Thank you! I missed this issue when I was looking around to see if a similar question was asked
