### ISSUE TITLE
Escape sequence doesn't always stop process

### ISSUE THREAD

**Issue by chronometric** [Nandaka/PixivUtil2#92]
Hi! This is a brief one....since installing pixivutil20150923, I've stopped the download process half a dozen times, like usual, using CTRL+C. Once or twice it worked ok, but the other times I've had to repeat myself. 

**1st interrupt**: prints <code>Aborted by user request => Ctrl-C</code> but does not slow down
**2nd interrupt**: prompts whether to contintue with the next image, but typing N/enter causes it to continue regardless
**3rd interrupt**: finally responds as it used to and quits, sometimes without confirming with the N at all.

[Example Log](http://pastebin.com/4KnNaScr): Probably not much to see, but on lines 27 and 273 there are both escape sequences that should have ended the process.

Sometimes it only does the two prompts, and sometimes it even behaves as normal, so I won't hazard a guess as to the cause. I was downloading either member_id folders or list.txt artists when I discovered this today.

**Comment by Nandaka** [comment]
do you prefer to always exit to the prompt or back to the main menu?

**Comment by chronometric** [comment]
The (y/n) prompt is nice, so you don't mess up a project, but also because it lets you "pause" your downloads if you desire. After that, exiting to the main menu is usually where I'd be headed.

Tonight I downloaded an artist that ended up being something like 4,000 images...I wanted to take a break and download something else, but it continued downloading after the interrupt prompt something like 10 times, before I just quit the program.

If there is some kind of protection against downloading partial images on sudden closure, then this issue is obviously extremely minor ^^

**Comment by chronometric** [comment]
Just an update: I seem to have better luck when spamming CTRL+C, only occasionally being "ignored" and needing to force close the DOS box. 

However, moreso than the convenience, I'm wondering about the image-saving behavior under these circumstances. @Nandaka: Could you tell me if the program throws out the incomplete image on a successful CTRL+C exit (or even thread termination), or does it write the image "as it goes," which would result in a corrupted partial image under some of these exit procedures? Thanks! x3

**Comment by Nandaka** [comment]
it will save incomplete image.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L521

but it should have .pixiv suffix
https://github.com/Nandaka/PixivUtil2/blob/master/PixivHelper.py#L549

**Comment by chronometric** [comment]
Great, as long as it doesn't leave incomplete images with regular filenames lying around, it's not really a problem ^^

**Comment by Nandaka** [comment]
update ctrl+c handler in 2c0424e61fd3f590f7300b6b5b614d154fa64ff7

pressing ctrl+c when downloading will abort current download and ask whether to continue to next image or not.

**Comment by chronometric** [comment]
> pressing ctrl+c when downloading will abort current download and ask whether to continue to next image or not.

Just FYI this is still an issue. CTRL+C stops the downloads and asks to quit Y/N, but pressing Y continues with the downloads. The only way to exit seems to be to hit CTRL+C rapidly twice. In other words, the prompt does nothing.

This is a bug, but an unimportant one. :+1:
