### ISSUE TITLE
images are downloaded outside the artist folder

### ISSUE THREAD

**Issue by zTohka** [Nandaka/PixivUtil2#921]
hey guys some of the images almost the half are downloaded in pixivunit2 directory and some in the artist folder, how can I set all images to download in the artist folder ?

**Comment by Nandaka** [comment]
check the filename formats in the config.ini?

**Comment by zTohka** [comment]
here http://prntscr.com/10pdmyo is it good ?

**Comment by Nandaka** [comment]
That one will not create a folder at all.... Use at least `%member_id%\%image_id%` (`\` is the path separator in windows).

refer to https://github.com/Nandaka/PixivUtil2#filename-format-syntax

**Comment by zTohka** [comment]
it worked but it stopped writing the name of the artist in the folder it's just the artist id can I fix that too ?

**Comment by Nandaka** [comment]
please read  https://github.com/Nandaka/PixivUtil2#filename-format-syntax
