### ISSUE TITLE
Invalid grant_type parameter or parameter missing Failed to login using OAuth

### ISSUE THREAD

**Issue by Crazycolors1248** [Nandaka/PixivUtil2#922]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [ ] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I don't know what to do. I try to make this thing work but every time I try to do anything it gives me this stupid Error.

**Expected behavior:** I will cooperate.

**Actual behavior:** I refuse

**Comment by Nandaka** [comment]
see https://github.com/Nandaka/PixivUtil2/issues/914
