### ISSUE TITLE
How to know total pages of fanbox creator?

### ISSUE THREAD

**Issue by KhilyatulAkbar** [Nandaka/PixivUtil2#924]
hello, i just use this program yesterday and still don't know much about this program, i've searched in issue and didn't find either (or maybe i miss it), in pixiv there is page button after clicking see all, and how can i know the total number of pages in fanbox creator? cause there is no page in fanbox? thank you!

**Comment by bluerthanever** [comment]
i don't think currently there are ways to know that?

I checked the api `https://api.fanbox.cc/creator.get?creatorId=<creatorId>`, there is no field like total posts or anything. Unless you need to pass some other parameters.
Another api `https://api.fanbox.cc/tag.getFeatured?creatorId=<creatorId>` gives post count of different tags, but maybe that api doesn't exclude those that contains multiple tags?

Anyway currently that seems to be unable to be solved straight-forwardly, to me.

**Comment by KhilyatulAkbar** [comment]
> i don't think currently there are ways to know that?
> 
> I checked the api `https://api.fanbox.cc/creator.get?creatorId=<creatorId>`, there is no field like total posts or anything. Unless you need to pass some other parameters.
> Another api `https://api.fanbox.cc/tag.getFeatured?creatorId=<creatorId>` gives post count of different tags, but maybe that api doesn't exclude those that contains multiple tags?
> 
> Anyway currently that seems to be unable to be solved straight-forwardly, to me.

oke then, thank you so much!

**Comment by bluerthanever** [comment]
you are welcome.
i think one way to know that is to load all posts first then divide the count of them by posts per page... but that seems low-efficient.

**Comment by KhilyatulAkbar** [comment]
yep already tried that, when calling get posts api there is limit param, which is set as 10(for me, idk if it's the same for the other), count of all post / 10, but yea as you said, that's really not efficient if the creator have so many posts
