### ISSUE TITLE
[Feature request] Distinct folder for Manga section of pixiv

### ISSUE THREAD

**Issue by sakkamade** [Nandaka/PixivUtil2#926]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

When downloading a pictures by `member_id` the artworks which are _Illustrations_ treating as though being a _Manga_ 
and availing themselves of `filenamemangaformat` property, whereas these are just >1 Illustrations' gathering.
If there is a way to distinguish an actual  _Manga_ (the one which under the section _Manga_ on  _pixiv_), 
I would like to see the ability to store it  in a separate sub-folder.

### Versions

PixivDownloader2 version 20210221-beta2  
(from source)

**Comment by Nandaka** [comment]
You can try to use these format in filename manga format as folder separator:
```
-> %manga_series_order%
   the order in the manga series.
-> %manga_series_id%
   original manga series id.
-> %manga_series_title%
   original manga series title, different from work title.
```

**Comment by sakkamade** [comment]
How come? on pixiv _Manga_ is not always series, I should say comparatively small amount. 

To make it more clear, I fancy to sort it in this fashion:—
```
filenameformat =          %member_id%_%artist%/%urlFilename%_%title%        <!--all the pictures of the "Illustrations" pixiv section-->
filenamemangaformat =     %member_id%_%artist%/マンガ/%urlFilename%_%title%  <!--where "filenamemangaformat" would not concern the "Illustrations" pixiv section-->
```

**Comment by Nandaka** [comment]
Well that's how it works, for multi-images post, then it will be treated as manga as that is the current implementation.

No plan to change it, but you can send me a pull request.

**Comment by sakkamade** [comment]
Sadly, it seems only I need such feature.

**Comment by darkred3** [comment]
@Nandaka 
I've actually been slightly perplexed by the use of _filenamemangaformat_ for a while now. I had thought it would be referring to manga series like this:
https://www.pixiv.net/user/28180175/series/127417 (NSFW)
https://www.pixiv.net/user/28180175/series/113070 (NSFW)
The way it works right now, the filename format syntaxes like _%manga_series_id%_ and _%manga_series_title%_ don't make much sense since most galleries (entries with more than one image) usually don't have either a series ID nor a series title.
Would it be possible to create a new filename format for these manga series entries? Something like _filenamemangaseriesformat_ for example.

**Comment by Nandaka** [comment]
Not really, it still point to the usual url if you click the image, e.g. `https://www.pixiv.net/en/artworks/92511418` and inside the page it does have the information to the series info (if available).

![image](https://user-images.githubusercontent.com/836867/136166798-1b8eaa9d-aea4-4cf0-aa90-fb6abeae1175.png)

no need separate filename format.

**Comment by darkred3** [comment]
But amongst the galleries that have more than one image, which are all recognized as "manga" by pixivutil, most are not part of a series and therefore do not have a `series id` or `series title`. And that is where my problem lies. I want manga series to be downloaded to their own folders like so:

```
%member_id% (%artist%) PIXIV\%manga_series_id% (%manga_series_title%)\%manga_series_order%. %works_date_fmt{%Y-%m-%d}% - %title%\%image_id%_%page_number%
```
But doing it like this, "normal" manga galleries that are not part of a series are downloaded into a `()` subfolder instead.

See also here:
https://www.pixiv.net/user/56767397/series/92056
This series includes a gallery with only 1 page so I'd have to edit the `filenameformat` too.

Small sidenote:
Can you add padded numbering to `%manga_series_order%`?
