### ISSUE TITLE
"Already downloaded files"

### ISSUE THREAD

**Issue by sammymiyauchi** [Nandaka/PixivUtil2#927]
I am trying to download all of an artist's images. I did it once but it only downloaded 2 of them, and whenever i try again it says the other ones are "already downloaded" and skips them even though they aren't
I tried doing the alwayscheckfilesize/verifyimage thing but it didn't work, it says the archives are already downloaded in system32\artist folder
Sorry if bad english

I'm using the latest beta version (20210221) but this same error happened on this other version (20210128)

**Comment by Nandaka** [comment]
How do you run the application? Looks like it save the file to the `C:\Windows\System32` folder...
Ensure you extract the zip file to a folder, then only run it from there.

Else update `rootdirectory` in the config.ini to specific folder (e.g. 'rootdirectory = C:\your_folder\Pixiv2')

**Comment by sammymiyauchi** [comment]
> How do you run the application? Looks like it save the file to the `C:\Windows\System32` folder...
> Ensure you extract the zip file to a folder, then only run it from there.
> 
> Else update `rootdirectory` in the config.ini to specific folder (e.g. 'rootdirectory = C:\your_folder\Pixiv2')

I just double click it, also when i check system32 folder the images also aren't there
I extracted it to a folder just like you said, i'll try to update the rootdirectory right now

**Comment by sammymiyauchi** [comment]
> I extracted it to a folder just like you said, i'll try to update the rootdirectory right now

I just did that and it did not work, the same problem is still happening
![image](https://user-images.githubusercontent.com/80842081/111502923-0efe0400-8725-11eb-8033-d452122b0ff5.png)

**Comment by Nandaka** [comment]
Well, delete the old files first in your the system32 as it is already recorded as the save location for that image, else you can just delete the sqlite.db to clear every tracking.

**Comment by cglmrfreeman** [comment]
Have you run a database cleanup since you deleted the files?
