### ISSUE TITLE
Cannot download specific tags with Option 6

### ISSUE THREAD

**Issue by laonglaan100** [Nandaka/PixivUtil2#928]
### Prerequisites

* [*] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [*] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [*] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

When I attempt to download a specific tag with Option 6 (specifically レム(リゼロ), using all 3 options outlined in the FAQ), it returns No more images. Found 0 image(s).

### Steps to Reproduce

1. Login via cookie.
2. 6
3. y
4. レム(リゼロ)
5. Enter
6. Enter
7. Enter

**Expected behavior:** Downloads all bookmarked images with that specific tag.

**Actual behavior:** 

Importing image bookmarks...
Importing user's bookmarked image from page 1
Source URL: https://www.pixiv.net/ajax/user/35817180/illusts/bookmarks?tag=%E3%83%AC%E3%83%A0%28%E3%83%AA%E3%82%BC%E3%83%AD%29&offset=0&limit=48&rest=show
No more images.
Importing user's bookmarked image from page 1
Source URL: https://www.pixiv.net/ajax/user/35817180/illusts/bookmarks?tag=%E3%83%AC%E3%83%A0%28%E3%83%AA%E3%82%BC%E3%83%AD%29&offset=0&limit=48&rest=hide
No more images.
Found 0 image(s).
Done.

### Versions 20210221-beta2

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
user bookmark is based on what you have been tagging in by the user, not based on the post itself.

The ajax request doesn't return anything because not tag has been added to the images.
Your request
https://www.pixiv.net/ajax/user/35817180/illusts/bookmarks?tag=%E3%83%AC%E3%83%A0%28%E3%83%AA%E3%82%BC%E3%83%AD%29&offset=0&limit=48&rest=show
No tagging by the user
![image](https://user-images.githubusercontent.com/836867/112558161-0e422d80-8e09-11eb-83b4-d3802ab388ef.png)

Compare with this
https://www.pixiv.net/ajax/user/189816/illusts/bookmarks?tag=bikini&offset=0&limit=48&rest=show
With tagging
![image](https://user-images.githubusercontent.com/836867/112558210-2b76fc00-8e09-11eb-8929-7de201c63921.png)

**Comment by laonglaan100** [comment]
Oh wow, I totally misunderstood that. Thanks for clearing it up! Is there any way to filter images based by the the tags in their post?

**Comment by Nandaka** [comment]
I don't think pixiv provide an API that I can use directly, need some post-processing enhancement on client side.

Internally, I can check for all images in the bookmark and then filter based on the tag input. E.g.
1. Pull all the images from `https://www.pixiv.net/ajax/user/35817180/illusts/bookmarks?tag=&offset=0&limit=48&rest=show` (no tags).
2. then perform internal filter based on your input.
   ![image](https://user-images.githubusercontent.com/836867/112565244-b232d580-8e17-11eb-9c38-d9b6bf3d375c.png)

Just need to know how to design the input to tell the application to tell what kind of tag need to be used ("bookmarkTags") or ("tags" from each image)

**Comment by laonglaan100** [comment]
I'm really a total noob at all this, but to do this I would need to set writeimagejson = True, right?

**Comment by laonglaan100** [comment]
Gotcha! I'm really a total noob at all this, but to do this I would need to set writeimagejson = True, right?

**Comment by Nandaka** [comment]
Add the option to use image tags, instead of bookmark tags
![image](https://user-images.githubusercontent.com/836867/112572281-d1842f80-8e24-11eb-9134-ca5f69ef5562.png)

**Comment by Nandaka** [comment]
https://github.com/Nandaka/PixivUtil2/releases/tag/v20210326

**Comment by Nandaka** [comment]
It will ask if you want to use the image tag for filtering if you provide a tag.
