### ISSUE TITLE
Date Jumping On Infinite Loop

### ISSUE THREAD

**Issue by danthonywalker** [Nandaka/PixivUtil2#93]
When passing page 1000 on enableinfiniteloop the date jump is completely random.

Page 1000: https://drive.google.com/open?id=0B9sysGP4FUlyRVdWZldfblZLU0U
Page it returns: https://drive.google.com/open?id=0B9sysGP4FUlycGZPV3lrekFYS2M

After letting it pass through another 1000 pages it just continues jumping to random dates (goes forward to 2013, 2009, 2015, it's just really random) until it just eventually ends usually through some variable error. It does however go through 1000 pages of those dates normally, it's just always grabbing a random date to start on.

When just going to Pixiv's site and testing what is the last image is on page 1000 it's just the normal date and adding on the date using ecd works normally.

I have only just now turned on debug so when other dates appear and eventually the error appears I will post that specifically.

Edit: Page 1000 of 2010: https://drive.google.com/open?id=0B9sysGP4FUlyUHVwVzVFWFI2LUE
Page it returns: https://drive.google.com/open?id=0B9sysGP4FUlyNzZfX0E4eXllTjg
Page 1000 of 2011: https://drive.google.com/open?id=0B9sysGP4FUlyWWg2SFZFXzlfV28
Page it returns: https://drive.google.com/open?id=0B9sysGP4FUlyYUE2eHpQT0xhVk0
Page 1000 of 2015: https://drive.google.com/open?id=0B9sysGP4FUlyUnlvYTJqMGJaMlU
Page it returns: https://drive.google.com/open?id=0B9sysGP4FUlyQ20tdTZMYTlTM0U
(I think the idea is set)

**Comment by Nandaka** [comment]
are you using version 20150923 or 20150924?

**Comment by danthonywalker** [comment]
pixivutil20150725-beta1

**Comment by Nandaka** [comment]
try the latest one first? you can get it here: https://github.com/Nandaka/PixivUtil2/releases

**Comment by danthonywalker** [comment]
Still happening

**Comment by Nandaka** [comment]
ah, I think because they added the pixiv popular advertisement, so it pick the promoted image...

**Comment by danthonywalker** [comment]
Sounds very plausible and would account for why the dates were random

**Comment by Nandaka** [comment]
Can you try this one: https://github.com/Nandaka/PixivUtil2/releases/tag/v20151001

**Comment by danthonywalker** [comment]
It appears to be working properly now.
