### ISSUE TITLE
Fanbox covers in original size

### ISSUE THREAD

**Issue by Psyho7** [Nandaka/PixivUtil2#930]
### Description

Amm, what about download covers in original size?
I mean, at now, downloaded covers are resized
But you can find url to original size
For example:

Post
https://www.fanbox.cc/@dsmile/posts/2080664
Resized cover
https://pixiv.pximg.net/c/1200x630_90_a2_g5/fanbox/public/images/post/2080664/cover/LuzFC8NEE9HcZQTAsUEH5zvI.jpeg
Original size
https://pixiv.pximg.net/fanbox/public/images/post/2080664/cover/LuzFC8NEE9HcZQTAsUEH5zvI.jpeg 

Post
https://www.fanbox.cc/@grande/posts/2071859
Resized cover
https://pixiv.pximg.net/c/1200x630_90_a2_g5/fanbox/public/images/post/2071859/cover/hyHgOfZ1tbMCftdGRukHqnHi.jpeg
Original size
https://pixiv.pximg.net/fanbox/public/images/post/2071859/cover/hyHgOfZ1tbMCftdGRukHqnHi.jpeg

URLs to original size are written without "c/1200x630_90_a2_g5/"

Found it by browser extension [Image Max Url](https://github.com/qsniyg/maxurl)
And generated links you can see by [this site](https://qsniyg.github.io/maxurl/)

### Versions

20210326

**Comment by Nandaka** [comment]
updated to download both resized and full size.
Add regex to replace the `c/1200x630_90_a2_g5/` or similar variation, also update the html generator.
