### ISSUE TITLE
Not getting Pixiv Sketch content with blank input

### ISSUE THREAD

**Issue by curya** [Nandaka/PixivUtil2#932]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I remember a few versions ago, I could press 1 for memberid, type the id number, and then press Enter a bunch of times and PixivUtil2 would get everything everything on the member's Pixiv page *and* Sketch page.

Now, it only gets the Pixiv page unless I specifically type Y on the Sketch prompt.

### Steps to Reproduce

1. Type 1. Press Enter.
2. Input member ID. Press Enter.
3. Do not input anything for Start Page. Press Enter.
4. Do not input anything for End page. Press Enter.
5. Do not input anything for "Include Pixiv Sketch [y/n]?" Press Enter.

**Expected behavior:** [What you expected to happen]

PixivUtil2 should get all images on both the Pixiv profile *and* the Pixiv Sketch profile.

**Actual behavior:** [What actually happened]

PixivUtil2 only gets the Pixiv Profile images and completely skips Pixiv Sketch images unless you specifically type Y on the Sketch prompt.

### Versions

v20210326

**Comment by Nandaka** [comment]
default is not to include pixiv sketch, so it is by design

https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L217

**Comment by curya** [comment]
Can we get an option in config to make it default?

**Comment by Nandaka** [comment]
no, but you can run with option `--include_sketch` to include sketch, e.g. `pixivutil2.exe -s1 --include_sketch <member_id>'
