### ISSUE TITLE
Can't get auth and refresh tokens

### ISSUE THREAD

**Issue by georgegeorgeson47** [Nandaka/PixivUtil2#933]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)? 
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?
![casacscsa](https://user-images.githubusercontent.com/82040176/115074004-c68f5d00-9f01-11eb-937a-c3f430afe9ea.PNG)

I visited this link provided in PixivUtil2:
https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362
I might have missed something but I followed the steps and couldn't find the "callback?" request in the request list, no request comes up.
I don't know Python, is it necessary for the process? 
Any help would be appreciated,
Thanks in advance.

**Comment by Nandaka** [comment]
try to do it in private mode/incognito mode? ensure you open the Network tab before submitting the login

**Comment by georgegeorgeson47** [comment]
> try to do it in private mode/incognito mode? ensure you open the Network tab before submitting the login

I did both of these from the start, it might be that I don't launch pixiv like in the first step and just use a browser regularly?

**Comment by Nandaka** [comment]
you can try that. It should not have anything to do with the script, as it is handled by the server side.
