### ISSUE TITLE
[Feature request] More Fileformat Options

### ISSUE THREAD

**Issue by TypeSakura** [Nandaka/PixivUtil2#934]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Can you add support for filename format options of %like_count% and %views_count%, they are exsiting showing numbers on web pages, should be easy to add support for them? Thank you very much!

### Versions

PixivDownloader2 version 20210326

**Comment by Nandaka** [comment]
`%like_count% and %views_count%` this one will change quite often you know? does it make sense to include in the filename?

**Comment by TypeSakura** [comment]
For those new popular works, maybe. But for those old ones, they may not change a lot. Actually I'm planning to use these these numbers to do some data research, if you can add this feature, I believe it can greatly help! Thank you!

**Comment by TypeSakura** [comment]
> `%like_count% and %views_count%` this one will change quite often you know? does it make sense to include in the filename?

For those new popular works, maybe. But for those old ones, they may not change a lot. Actually I'm planning to use these these numbers to do some data research, if you can add this feature, I believe it can greatly help! Thank you!

**Comment by Nandaka** [comment]
I think if you enable `writerawjson = True` in config.ini, you can get more information from the server if your purpose is for research.
