### ISSUE TITLE
History of Download jobs [Feature]

### ISSUE THREAD

**Issue by EfronC** [Nandaka/PixivUtil2#936]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Just a little thing that i haven't been able to find in the program, but might be very useful under some circumstances: A History of the searches you do, for the case when you need to remember the ids of your last search. For example, yesterday i made a download of 10 members id, but half in the process there was a blackout, and i wasn't able to remember the left 5 members id that weren't downloaded(My browser history had a lot of pixiv pages, so couldn't find them). The nearer i've found is making a batch job every time i want to download more than one, but that's probably a little unnecesary(Not like copy and pasting the whole member ids line would not work either).

**Comment by Nandaka** [comment]
it should be available in the log file.

**Comment by EfronC** [comment]
> it should be available in the log file.

Sorry for the late answer, very hard days at work.

I don't believe that the log file is an answer... Or at least, unless there is a log that only prints when is an input and i don't know about it, the logs are basically imposible to read, the 7 log files print for everything that appears on screen, so if you want an specific log, you won't be able to find it after maybe 5 minutes of downloads.

I see that in the config.ini are different log levels, but if they work similar that in CI, then i don't think any of them will stop from filling the log files(Not like i've tried all of them to be sure). If there is a setting that drastically reduces the log to a user readable history, then that would be the answer.
