### ISSUE TITLE
[Feature request] adding a monitoring system

### ISSUE THREAD

**Issue by aymanA123** [Nandaka/PixivUtil2#937]
### Description
can you add a monitoring system or is it already implemented and I'm just dumb.

[Description of the bug or feature]
add in a new number in the tool just for monitoring . where we can enter a pixiv id  and from the date when we entered the number it downloads anything new of that pixiv id.
### Versions

v20210421

**Comment by Nandaka** [comment]
well, it already track the downloaded image id in the db, also you can try to set `checkupdatedlimit = 7` (check readme for more details).

**Comment by aymanA123** [comment]
> well, it already track the downloaded image id in the db, also you can try to set `checkupdatedlimit = 7` (check readme for more details).

don't you think it would be better if it was a bit automated for convenience sake . instead of putting in a bunch of member ids manually for pixivutil to download the new images. wouldn't it be better if we enter them just one time in some bookmark type feature and every time you chose the feature they would automatically download new images of the artist that you already put there once.

something like the monitoring system from imgbrd-grabber: https://github.com/Bionus/imgbrd-grabber/issues/1620

that's the only thing that i feel like this app is laking. besides that it's perfect.

**Comment by Hamuko** [comment]
>instead of putting in a bunch of member ids manually for pixivutil to download the new images. wouldn't it be better if we enter them just one time in some bookmark type feature and every time you chose the feature they would automatically download new images of the artist that you already put there once.

Follow the artists on Pixiv and then smash option 8.

**Comment by aymanA123** [comment]
> > instead of putting in a bunch of member ids manually for pixivutil to download the new images. wouldn't it be better if we enter them just one time in some bookmark type feature and every time you chose the feature they would automatically download new images of the artist that you already put there once.
> 
> Follow the artists on Pixiv and then smash option 8.

thx . i'll give it a try

**Comment by Lenoyr** [comment]
> 
> 
> > instead of putting in a bunch of member ids manually for pixivutil to download the new images. wouldn't it be better if we enter them just one time in some bookmark type feature and every time you chose the feature they would automatically download new images of the artist that you already put there once.
> 
> Follow the artists on Pixiv and then smash option 8.

Would it work with tags?
