### ISSUE TITLE
No file size information!

### ISSUE THREAD

**Issue by Leucocoryne** [Nandaka/PixivUtil2#938]
Occasionally, when downloading a file, the file size is not displayed normally and is displayed in the same format as -1 Bytes.
It doesn't seem to be a problem with the actual downloaded file, but... I wonder why this problem is happening.

![스크린샷(283)](https://user-images.githubusercontent.com/68358620/115637233-9e14c200-a34a-11eb-9804-d18df3b61ddd.png)
![스크린샷(282)](https://user-images.githubusercontent.com/68358620/115637243-a2d97600-a34a-11eb-8084-c48324dd3dfe.png)

**Comment by Nandaka** [comment]
well, the server doesn't send provide the remote file size via Content-Length header, that's why.

https://github.com/Nandaka/PixivUtil2/blob/master/PixivDownloadHandler.py#L268-L275
