### ISSUE TITLE
Download Fanbox Cover as a folder.jpg

### ISSUE THREAD

**Issue by joshboston723** [Nandaka/PixivUtil2#940]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I am suggesting a way to download the cover of a fanbox post as a folder.jpg in case we choose to separate fanbox posts into folders.

### Steps to Reproduce

1. go to config and set filenameformatfanboxcover = %artist% (%member_id%)\fanbox\%title%\folder.jpg
2. Option f3

**Expected behavior:** Downloads cover image of specified post as folder.jpg

**Actual behavior:** Downloaded cover image of specified post as folder.jpg.jpeg

**Comment by Nandaka** [comment]
remove the extension?

**Comment by joshboston723** [comment]
When I remove the extension it downloads the cover as folder.jpeg, which Windows 10 seems to not recognize as a folder display image.

**Comment by Nandaka** [comment]
add new nameformat = `%force_extension{ext_here}%` in the latest commit. To use, you can add it to the filenameformat at the end, e.g. `%artist% (%member_id%)\fanbox%title%\folder%force_extension{jpg}%`
