### ISSUE TITLE
Download resume after disk space error skips download in progress rather than retrying

### ISSUE THREAD

**Issue by nomakewan** [Nandaka/PixivUtil2#941]
### Prerequisites

* [✔] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [✔] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [✔] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

If in the process of downloading from Fanbox the destination disk runs out of space, PixivUtil2 will correctly stop attempting to write to the disk and will display a "Press enter to retry" button waiting for the user to correct the low space condition. However, upon pressing enter, PixivUtil2 will skip over the file it was attempting to write rather than reattempt the download, thus causing a missed image. I only (accidentally) tested this while downloading from Fanbox and do not know if it applies to regular Pixiv as well.

### Steps to Reproduce

1. Have remaining hard drive space less than required to download entire Fanbox contents.
2. Attempt to download Fanbox contents.
3. When remaining space hits the limit, PixivUtil2 will pause awaiting user input in the middle of a download.
4. Correct the space issue, then press enter to retry.

**Expected behavior:**
PixivUtil2 will redownload the image it was in the process of downloading before the destination disk ran out of space.

**Actual behavior:**
PixivUtil2 skips the image it was in the process of downloading and downloads the next image in the list.

### Versions
20210421

**Comment by bluerthanever** [comment]
https://github.com/Nandaka/PixivUtil2/blob/24503c404269bb47528b26093bd72c69d6f5fcf9/PixivDownloadHandler.py#L228
change here to `continue`?

**Comment by Nandaka** [comment]
should be working, as it still within the while-loop:
https://github.com/Nandaka/PixivUtil2/blob/24503c404269bb47528b26093bd72c69d6f5fcf9/PixivDownloadHandler.py#L59

**Comment by nomakewan** [comment]
I have attached the log output from the particular section (and scrubbed the filenames). The issue was that I left PixivUtil2 running and went to sleep. When I woke up it was waiting for my input, and it appears that it broke out of that while-loop waiting for my input. The issue is that if it's waiting for user input, it shouldn't be able to break from that loop (or should at least go back to the start of the loop after user input).

[pixivutil_spaceerror_skip_sanitized.txt](https://github.com/Nandaka/PixivUtil2/files/6397803/pixivutil_spaceerror_skip_sanitized.txt)

**Comment by bluerthanever** [comment]
> 
> 
> I have attached the log output from the particular section (and scrubbed the filenames). The issue was that I left PixivUtil2 running and went to sleep. When I woke up it was waiting for my input, and it appears that it broke out of that while-loop waiting for my input. The issue is that if it's waiting for user input, it shouldn't be able to break from that loop (or should at least go back to the start of the loop after user input since the result of the previous action was -1).
> 
> [pixivutil_spaceerror_skip_sanitized.txt](https://github.com/Nandaka/PixivUtil2/files/6397803/pixivutil_spaceerror_skip_sanitized.txt)

i am not quite getting the idea that the loop was broken?
`PixivDownloadHandler.download_image` calls `PixivDownloadHandler.perform_download` which calls `PixivHelper.download_image`, it just so happens that when the error happened at `File "PixivHelper.pyc", line 718, in download_image`, the `finally ` part did some logging, then the error got raised to `PixivHelper.download_image`, where the util asked for inputs.

**Comment by bluerthanever** [comment]
speaking of which, i sometimes found quite a lot of redundant information in the logging... like in this logging, the `print_and_log` gets called 3 times continuously, and the stack track information also gets written into logs 3 times.. and again when the exception was caught inside `PixivDownloadHandler.download_image`....

**Comment by nomakewan** [comment]
> i am not quite getting the idea that the loop was broken?
> `PixivDownloadHandler.download_image` calls `PixivDownloadHandler.perform_download` which calls `PixivHelper.download_image`, it just so happens that when the error happened at `File "PixivHelper.pyc", line 718, in download_image`, the `finally ` part did some logging, then the error got raised to `PixivDownloadHandler.download_image`, where the util asked for inputs, inside the loop.

I'm afraid I'm just guessing. All I can tell you is that I left the program alone for several hours, during which the destination hard disk ran out of space, and pixivutil ended up on a screen telling me to press enter to continue. When I did, it skipped the file it had been trying to download (p2) and started downloading the next image in the sequence (p3). The log also shows that it did retry three times and failed due to the insufficient disk space at 1:59 AM. Then at 6:28 AM when I woke up and hit enter, it skipped to the next file.

The actual "waiting for user input" is apparently not logged.

**Comment by bluerthanever** [comment]
> I'm afraid I'm just guessing. All I can tell you is that I left the program alone for several hours, during which the destination hard disk ran out of space, and pixivutil ended up on a screen telling me to press enter to continue. When I did, it skipped the file it had been trying to download (p2) and started downloading the next image in the sequence (p3). The log also shows that it did retry three times and failed due to the insufficient disk space at 1:59 AM. Then at 6:28 AM when I woke up and hit enter, it skipped to the next file.
> 
> The actual "waiting for user input" is apparently not logged.

well, the thing is, instead of retrying 3 times, all it did was just logging the same error 3 times continuously.
and true that the "waiting for user's input` was indeed not logged.
and the reason it didn't retry is because the logic was to return the download result of current image, which would be fixed.
