### ISSUE TITLE
 AttributeError when picking "e. Export online bookmark"

### ISSUE THREAD

**Issue by PatrickL546** [Nandaka/PixivUtil2#942]
### Prerequisites

* [✔] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [✔] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [✔] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Error when exporting online bookmark. I tried using my old backup's and they too started showing this error. I'm using the same python version and windows version, and I have no idea how this popped up.

### Steps to Reproduce

1. Input e. Export online bookmark
2. Add filename
3. Include Private bookmarks [y/n/o]. I've tried all options

**Expected behavior:** Export member_id to a text file

**Actual behavior:** 

```
Exporting page 1
Source URL: https://www.pixiv.net/bookmark.php?type=user&p=1&rest=show
Using default DB Path: C:\Users\redacted\Downloads\PixivUtil2\db.sqlite
Error at export_bookmark(): (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'"), <traceback object at 0x04F8C048>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1385, in main
  File "PixivUtil2.py", line 1110, in main_loop
  File "PixivUtil2.py", line 713, in menu_export_online_bookmark
  File "PixivBookmarkHandler.pyc", line 260, in export_bookmark
  File "PixivBookmarkHandler.pyc", line 305, in get_bookmarks
  File "PixivBookmark.pyc", line 37, in parseBookmark
AttributeError: 'NoneType' object has no attribute 'findAll'
Unknown Error, please check the log file: (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'findAll'"), <traceback object at 0x04F8C0A8>)
press enter to exit.
```

### Versions

PixivDownloader2 version 20210421

**Comment by bluerthanever** [comment]
Looks like `https://www.pixiv.net/users/%userId%/following?rest=show&p=1` returns some invalid html page now...

**Comment by bluerthanever** [comment]
but when i open that page in browser, js calls `https://www.pixiv.net/ajax/user/%userId%/following?offset=0&limit=24&rest=show&tag=&lang=ja` this api to retrieve an json object.
