### ISSUE TITLE
Strange Typo "ixivDownloader" before constant PIXIVUTIL_VERSION

### ISSUE THREAD

**Issue by cglmrfreeman** [Nandaka/PixivUtil2#947]
### Prerequisites

* [X] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Each time the program is launched and for each image downloaded, the line is prefixed with `ixivDownloader 20210421` in the console.

### Steps to Reproduce

1. Launch the script
2. The first printf of `header()` will have the prefix `ixivDownloader 20210421`
3. Each Member ID page processed will also have this invalid prefix `ixivDownloader 20210421 [1 of 1] MemberId: 988539 Page: 1Member Url: https://www.pixiv.net/ajax/user/988539/profile/all ` (There is also improper spacing here between "Page" and "Member Url")
4. Each Image ID processed which is not already downloaded will have this invalid prefix `ixivDownloader 20210421 [1 of 1] MemberId: 474309 Page: 1 Post 2+0 of 460 ImageId: 89236210Title: あー？何上から目線で見てんだタココラッ！` (More improper spacing between "ImageId" and "Title")

**Expected behavior:**
The name of the program and version would not be displayed in all these circumstances, much less with a typo.

**Actual behavior:**
An incorrect name of the program as well as the version of the program is printed extremely frequently.

### Versions
PixivDownloader2 version 20210421 (if it wasn't obvious already)

**Comment by Nandaka** [comment]
> header

I don't use linux, but ensure your consoles support ANSI escape sequence as it uses [colorama](https://pypi.org/project/colorama/)

https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L91-L97

> console title

Same case here, maybe you need to play around here? Most likely same issue with #948
https://github.com/Nandaka/PixivUtil2/blob/a9f6e4545ba70a528f0c1aeb8c53f52731042f83/PixivHelper.py#L348

**Comment by cglmrfreeman** [comment]
> I don't use linux, but ensure your consoles support ANSI escape sequence as it uses colorama

I mean it always has in the past. I've had colorama installed since it first began requiring it. Both these issues have never been an issue until the most recent commits. Been using PixivUtil2 in Konsole without these issues for over a year now.

Perhaps python or Konsole updated recently and caused a change.

**Comment by cglmrfreeman** [comment]
I did what I should have done and gone through each commit and found that commit 480545bc87c034e7f5339a2e82ac1a179ec86171 did in fact break my PixivUtil2.

Downloading an Unbuntu virtual machine to test if it also experiences this error... and yes, it does occur in Ubuntu:

![Screenshot_20210509_005425](https://user-images.githubusercontent.com/9744201/117564531-55a31700-b061-11eb-8c0f-b082e5004b0d.png)

And is fixed by checking out commit 4423bb6668eeb294a0aa44fc138603f4aecf95c2

![Screenshot_20210509_005529](https://user-images.githubusercontent.com/9744201/117564548-66538d00-b061-11eb-9477-ca329082a2de.png)

I suggest that commit 480545bc87c034e7f5339a2e82ac1a179ec86171 be reverted and the docker escape code issue be looked at a little closer and ensure compatibility outside of docker prior to a commit.

**Comment by cglmrfreeman** [comment]
> can you modify and test using this: https://stackoverflow.com/a/47262154

Changing https://github.com/Nandaka/PixivUtil2/blob/a9f6e4545ba70a528f0c1aeb8c53f52731042f83/PixivHelper.py#L348 to `print(f'\33]0;{title}\a', end='', flush=True)` seemingly resolved my issue. I can also confirm that the title with that new code _did_ change the terminal's title in my Xterm program. Apparently the terminal program I use, Konsole, does not change titles no matter what. I also confirmed the old code `sys.stdout.write(f"\x1b]2;{title}\x07")` also changed the console's title correctly in Xterm.

We just need to test this code in docker to see if it works there.

**Comment by Nandaka** [comment]
can you do pull request just in case?

**Comment by whinette** [comment]
Just saw the comment and proposed solution. I did the same on my end, PR is open @Nandaka

**Comment by Nandaka** [comment]
merged 😄
