### ISSUE TITLE
MEGA link @Fanbox

### ISSUE THREAD

**Issue by ProfessorDocJP** [Nandaka/PixivUtil2#949]
Trying to download posts that has mega links in it. Is there any way to do that?

**Comment by cglmrfreeman** [comment]
I supported a Fanbox member that would only post thumbnails and links to their google drive for the actual content. They would then remove the google drive links after a certain timeframe in their fanbox to "be fair" to the fans who have been supporting them longer. It's essentially content gatekeeping. I am guessing that's the case with your mega links?

**Comment by Nandaka** [comment]
@bluerthanever got any idea? I don't really subscribe fanbox, so I don't know

**Comment by ProfessorDocJP** [comment]
No it is literally a link that they add to the end of the post but never remove. There is a preview of what the image is like and then they have the mega link for the full image and of course it would take forever to go to each mega link for each image.

**Comment by Nandaka** [comment]
no plan for that, but you can create pull request.

**Comment by ProfessorDocJP** [comment]
Thank you.

**Comment by bluerthanever** [comment]
hmm... as far as i know, mega.nz seems to be quite complicated. files from drive.google.com is easy, but not folders.
usually i just go to fanbox and check for new posts, then download with PixivUtil2. so if there are links i would download them manually.
sorry i didn't use my laptop yesterday.

**Comment by Nandaka** [comment]
maybe just trigger an external application and pass the url name? e.g. call jdownloader when it found a link?
No need to create specific handler directly in the script.

**Comment by bluerthanever** [comment]
i found this but it doesn't seem to be working here...
https://jdownloader.org/knowledge/wiki/terminal/index
maybe it requires java?

**Comment by Nandaka** [comment]
yeah, jDownloader uses java. I'm just using that for example.

No need to use that specifically if you can trigger it from cli.

**Comment by bluerthanever** [comment]
hmm... i found this.
https://board.jdownloader.org/showthread.php?t=62651
someone recommended using an extension though.

also in another thread, someone recommended using APIs of `MyJDownloader`.
https://my.jdownloader.org/developers/

looks like a lot of work either way....

didn't find anything that uses some simple commands to accomplish this.

**Comment by NHOrus** [comment]
Simpliest way is to add links to url_list.txt, same as with links in pixiv posts.

**Comment by NHOrus** [comment]
And let user know/deal with it themselves

**Comment by bluerthanever** [comment]
> Simpliest way is to add links to url_list.txt, same as with links in pixiv posts.

yeah, that would be the easiest.
