### ISSUE TITLE
[Feature request/Question] Insert Pixiv tags into images metadata IPTC/XMP

### ISSUE THREAD

**Issue by Parexy** [Nandaka/PixivUtil2#952]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I have been trying to figure out a way to to insert the tags from either the txt or json files that can be generated into the actual metadata for the images, but haven't really been able to figure out how i would do this in mass/automated, since it wouldn't really be possible to do this manually with thousands of images.

I know that i could probably use the ExifTool to do this, but haven't really been able to figure out how to use this together with the provided output files generated for singular or groups of images and how i would do that for all the images or at least the first one in a group/series of them.

So would it be possible to integrate this feature into this tool (i know that the %tags% feature exists for the image titles) or maybe just some sort of explanation on how to do this, if possible.

**Comment by Nandaka** [comment]
no, as it will modify the file size/timestamp and break duplicate file detection.
You can set `writeimagejson = True` to export the full image information and maybe write your own script to update the exif?

**Comment by Parexy** [comment]
Figured it out.

By using this command with ExifTool it will apply the tags to to the keyword metadata for all p1 images.
`exiftool -charset iptc=utf8 -m -P -r -overwrite_original -ext jpg -tagsfromfile %d%f.json "-keywords<tags" "Download path"`

This also preserves the timestamp so it shouldn't interfere with duplicate file detection, unless you have to use both size and timestamp for that. If so another way around that could be to compare Image.tostring() outputs since that doesn't include the images metadata and would not change due to this (It should not at least).

Seems like it would be a decently useful feature to add to this program, since you could easily also add all the image links, captions, and such into the metadata if you want to.
I don't have the knowledge to code this so i wouldn't be able to do it.

**Comment by Baa14453** [comment]
This would be quite useful even if it was just sidecar .xmp files
This library can do the work I believe https://launchpad.net/py3exiv2

I could then use the data in professional photo software like DigiKam

**Comment by Nandaka** [comment]
merged #980
