### ISSUE TITLE
FANBOX posts without cover image now completely break downloader (only on master)

### ISSUE THREAD

**Issue by somebody1234** [Nandaka/PixivUtil2#953]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
See title.

this is the line creating the issue.
https://github.com/Nandaka/PixivUtil2/blob/7feb27da289157a02c6f730f20161b43f52f4e72/PixivModelFanbox.py#L167
i'd advise changing the default to `None` here:
https://github.com/Nandaka/PixivUtil2/blob/7feb27da289157a02c6f730f20161b43f52f4e72/PixivModelFanbox.py#L96

### Steps to Reproduce

1. Try to download FANBOX artist with a post without cover iamge

**Expected behavior:** No error

**Actual behavior:** Error

### Versions
Master (7feb27d) and newer

**Comment by bluerthanever** [comment]
sorry i wanted to test with posts without cover but i didn't find any... i will have a look at it

**Comment by somebody1234** [comment]
[this](https://frankenstyle.fanbox.cc/posts/2243878) one maybe? as sample post

**Comment by somebody1234** [comment]
error message:
```
Traceback (most recent call last):
  File "/mnt/ntfs/MEGA/pixivutil20200827-beta1/PixivUtil2/PixivDownloadHandler.py", line 78, in download_image
    remote_file_size = get_remote_filesize(url, referer, config, notifier)
  File "/mnt/ntfs/MEGA/pixivutil20200827-beta1/PixivUtil2/PixivDownloadHandler.py", line 294, in get_remote_filesize
    res = br.open_novisit(req)
  File "/home/me/.local/lib/python3.9/site-packages/mechanize/_mechanize.py", line 241, in open_novisit
    return self._mech_open(
  File "/home/me/.local/lib/python3.9/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/home/me/.local/lib/python3.9/site-packages/mechanize/_opener.py", line 173, in open
    req_scheme = req.get_type()
  File "/home/me/.local/lib/python3.9/site-packages/mechanize/_urllib2_fork.py", line 260, in get_type
    raise ValueError("unknown url type: %s" % self.__original)
ValueError: unknown url type:
Error at download_image(): (<class 'ValueError'>, ValueError('unknown url type: '), <traceback object at 0x7f79154d2a40>) at  (9000)
```

**Comment by somebody1234** [comment]
> most likely due to changes in #951

@Nandaka yes, the blame says so as well

**Comment by Nandaka** [comment]
changes merged
