### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by ShiroTora** [Nandaka/PixivUtil2#955]
hello nandaka, i updated to last version just now but i keep ketting 

Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x3b6fdf0 whose wrapped object = <HTTPError 302: 'The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nFound'>>, <traceback object at 0x042AD408>)
Cannot Login!

what i tried 
i tried relogon web pixiv on chrome and copied cookie
i tried relog with firefox and copy the cookie again

i re entered my loginin in the pixivuntil settings, but no luck  

![image](https://user-images.githubusercontent.com/10827947/119090177-914bc280-ba0b-11eb-9250-06f72b64bbfb.png)

**Comment by Nandaka** [comment]
1. delete the old log file `pixivutil.log`
2. re-run the application
3. upload the log file here (zip it if required).

**Comment by bluerthanever** [comment]
upload cookie string?

**Comment by bluerthanever** [comment]
update cookie string?

**Comment by ShiroTora** [comment]
> 
> 
>     1. delete the old log file `pixivutil.log`
> 
>     2. re-run the application
> 
>     3. upload the log file here (zip it if required).

it don't re-create log, 
i also tried a clean pixivuntil extracted from zip but same reaction, and i run as admin

im not handy with cmd/powershell, 
last time when this happends i could run it trough a powershell version, 
but i cant find out how i did that

i also tried a virtual machine on the nas and i get same error , and no log file

**Comment by ShiroTora** [comment]
> 
> 
> update cookie string?
by cookies you you mean the PHPSESSID ? if so yes, i logged out, and relogged, copied the cookie and pasted it in the config of pixiv until

**Comment by bluerthanever** [comment]
hmm. did you get the cookie from the logging in action? or from a valid request to pixiv.net after you logged in?
i think sometimes they might be different, but not so sure...

and as for logs, is the `loglevel` in your config set to `DEBUG`? if not try setting it to`DEBUG`.
also the log files are usually in the same folder of the `PixivUtil2.exe`, try looking for it there?

**Comment by Nandaka** [comment]
see https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows) for running from source code.

**Comment by NonaSuomi** [comment]
I'm getting the same error on startup, here's my own logfile of the error:
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/6568072/pixivutil.log)

**Comment by Nandaka** [comment]
Hmm, try to set your pixiv language to english?
![image](https://user-images.githubusercontent.com/836867/120182422-f475fa00-c240-11eb-971a-602b3e598858.png)

**Comment by NonaSuomi** [comment]
No dice, still get the same error after updating my language setting.

**Comment by Nandaka** [comment]
btw, do you update the user agent too when updating the cookie? both must be matching with the browser that you get the cookie from.

**Comment by NonaSuomi** [comment]
Useragent was still identical when I checked my browser, but it looks like maybe something was jacked with the session- just to see if it did anything I manually logged out of pixiv and then logged in, then put the new session ID into my config file and it's back working again. Perhaps it needed some kind of session refresh after changing the language setting? Either way, thanks for the help!
