### ISSUE TITLE
[Feature request] Allow using MD5 hashes when formatting filenames

### ISSUE THREAD

**Issue by Darayavaush** [Nandaka/PixivUtil2#956]
### Prerequisites

* [+] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [+] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Most (all?) boorus identify images by their MD5 hash, so it would be very convenient to allow using it when picking the filename format.

**Comment by Nandaka** [comment]
It won't work for all filename format, because the hash can be only calculated after the file is downloaded.
Also it will screw up file-exists detection due to the same reason. 
And of course it will add additional delay to calculate the md5 after the file is fully downloaded.

**Comment by Darayavaush** [comment]
Thanks. :)
