### ISSUE TITLE
 getaddrinfo failed

### ISSUE THREAD

**Issue by j2hsaco91** [Nandaka/PixivUtil2#959]
Hello,

I have problems suddenly

Reading E:\pixivutil20210421\config.ini ...
Configuration loaded.
<urlopen error [Errno 11001] getaddrinfo failed> 1 2 3 4
<urlopen error [Errno 11001] getaddrinfo failed> 1 2 3 4

and shutdown

**Comment by Nandaka** [comment]
you got problem with your internet, basically it cannot resolve the dns of pixiv website for whatever reason.

**Comment by j2hsaco91** [comment]
So this is my problem, not the program?

**Comment by Nandaka** [comment]
yes, it uses the os call to resolve the dns, errno 11001 is the code returned by windows.

Check you firewall/anti virus? maybe try on different pc/network?

**Comment by j2hsaco91** [comment]
I tried turning off the firewall and resetting the internet, but that didn't work.

**Comment by Nandaka** [comment]
you can access the pixiv website from browser without proxy, right? else try to run from source code? see https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)
