### ISSUE TITLE
new illust from bookmark - Page 100 is ignored

### ISSUE THREAD

**Issue by Gimlao** [Nandaka/PixivUtil2#96]
When using command 8, start page 1, end page 0 (no limit) : page 100 is ignored.

**Comment by Nandaka** [comment]
Hi, can you provide more details, including the log file?

**Comment by Gimlao** [comment]
It says « Limit or last page reached. » but this line is missing in the console :
« Source URL: http://www.pixiv.net/bookmark_new_illust_r18.php?p=100 »
We have to download page 100 manually. :3
