### ISSUE TITLE
How about this change?

### ISSUE THREAD

**Issue by L4Ph** [Nandaka/PixivUtil2#960]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

`FANBOX` in `config.ini` which is generated by default

### Desired changes
I think it would be even easier to understand if they were separated by Fanbox and Pixiv like this.

>filenameformatfanboxcover = %artist% (%member_id%)\%urlFilename% - %title%
>filenameformatfanboxcontent = %artist% (%member_id%)\%urlFilename% - %title%
>filenameformatfanboxinfo = %artist% (%member_id%)\%urlFilename% - %title%

↓

>filenameformatfanboxcover = FANBOX \%artist% (%member_id%)\%urlFilename% - %title%
>filenameformatfanboxcontent = FANBOX \%artist% (%member_id%)\%urlFilename% - %title%
>filenameformatfanboxinfo = FANBOX \%artist% (%member_id%)\%urlFilename% - %title%

**Comment by bluerthanever** [comment]
you meant default values of FANBOX configuration items?

**Comment by L4Ph** [comment]
yes
