### ISSUE TITLE
Posting the code for artist ID is not working.

### ISSUE THREAD

**Issue by Deejay85** [Nandaka/PixivUtil2#965]
I'm using the 20210421 version of PixivDownloader. Downloading goes fine most of the time, but every now I got some artist IDs that need me to do the usual hit F12 and paste the code into the browser. Well I've been trying that, and it won't work at all. I've tried copying just the stuff after the code=, I've even tried copying the code= bit in as well, with no luck. No matter what I paste into the field it's not working, and no, I am not in incognito mode either, because I rather like the idea of my FBI agent that's been charged with monitoring me having to suffer from Freudian-like night terrors when he/she sleeps. Anyway below is a log of the errors I get after a failed copy/paste.

```
Traceback (most recent call last):
  File "PixivArtistHandler.pyc", line 68, in process_member
  File "PixivBrowserFactory.pyc", line 737, in getMemberPage
  File "PixivBrowserFactory.pyc", line 643, in getMemberInfoWhitecube
  File "PixivOAuth.pyc", line 224, in login
  File "PixivOAuthBrowser.pyc", line 82, in login
  File "requests\api.pyc", line 119, in post
  File "requests\api.pyc", line 61, in request
  File "requests\sessions.pyc", line 530, in request
  File "requests\sessions.pyc", line 643, in send
  File "requests\adapters.pyc", line 416, in send
  File "requests\adapters.pyc", line 227, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\Ande\AppData\Local\Temp\cacert.pem
Error at processing Artist Info: (<class 'OSError'>, OSError('Could not find a suitable TLS CA certificate bundle, invalid path: C:\\Users\\Ande\\AppData\\Local\\Temp\\cacert.pem'), <traceback object at 0x0474B648>)
Member Url: https://www.pixiv.net/ajax/user/3470105/illustmanga/tag?tag=R-18&offset=0&limit=48
Using OAuth to retrieve member info for: 3470105
```

**Comment by Nandaka** [comment]
>> OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\Ande\AppData\Local\Temp\cacert.pem

somehow it try to load the cacert.pem from the temp dir. Do you extract the zip file (pixivutil20210421.zip) to a folder before executing PixivUtil2.exe?

**Comment by Deejay85** [comment]
Well that's the rub right there...you see I already know running this from a winrar archive is basically a bad idea, especially when I plan to use it on a regular basis, so of course I extracted it to it's own folder at W:\Apps\Pixiv - Artists (the other, of course, is for Tags, so I only have to monkey with the config file when downloading by tags). So the fact it's going to a temp directory on a completely different drive isn't really making any sense to me.

**Comment by Nandaka** [comment]
try to copy the cacert.pem to the temp folder? alternatively, try to run from source code (see https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows))

**Comment by Deejay85** [comment]
To my surprise copying/pasting the cacert.pem file worked. It's a pain I got to do every time with certain images, but at least it works. Not sure if there is anything I can do about this on my side as far as the config file goes, so if not, you may want to mark this as a bug that needs updated on your next release.

**Comment by Nandaka** [comment]
I can't replicate from my side, so I cannot fix it...

**Comment by gummykage** [comment]
I just started having this exact error also... I have multiple instances of 20210421 installed in its own folders on a completely different drive... It keeps trying to load cacert from a temp folder insides windows... I recently installed all visual C++ to solve some other issues... might this be related?
