### ISSUE TITLE
Some images skipped utilizing option 6

### ISSUE THREAD

**Issue by ImRingo** [Nandaka/PixivUtil2#967]
I recently left the program run overnight as it backed up all my current bookmarks on my profile onto my local drive. I went into the config file and made sure to turn R18 mode to "true" so that nothing would be skipped. After going through a couple folders though, I've noticed that the program skipped over some images from some artists. For some artists, it was maybe 2 or so images. For others, it was close to 10-15 images missing that I have bookmarked. Also I do have the premium membership to Pixiv so there is no limit there. 

Sorry if this is not in-depth or technical enough, let me know if there is any other information you need. 

E1: I just saw this bit in the readme file:
"Setting it to True will only download R-18 images."

Does this mean that, leaving it on false will download _both_ NSFW and SFW images? Or just SFW? Essentially I want to download all my bookmarks regardless if they are SFW or NSFW.

**Comment by Nandaka** [comment]
check the readme?
![image](https://user-images.githubusercontent.com/836867/121792493-0f287580-cc28-11eb-80e3-8ea166a54eab.png)

**Comment by ImRingo** [comment]
Yes as I put in my edit (which was edited about 5 minutes after my original post), I did read that in the readme/on the main code page of this github project. However, as I put in my edit, I am a little confused about the wording. If you leave that value "False", will it download BOTH SFW and NSFW images? Or just SFW?

**Comment by bluerthanever** [comment]
~~~if `r18mode` is set to true, PixivUtil2 would use `https://www.pixiv.net/bookmark_new_illust_r18.php?p={page_index}` to get all bookmarked images/mangas. otherwise `https://www.pixiv.net/bookmark_new_illust.php?p={page_index}` would be used.
open these two urls and you will see the difference... in short the answer to your question is `BOTH SFW and NSFW`.

i think you could just change the value of this option item to see the difference...

**Comment by ImRingo** [comment]
> if `r18mode` is set to true, PixivUtil2 would use `https://www.pixiv.net/bookmark_new_illust_r18.php?p={page_index}` to get all bookmarked images/mangas. otherwise `https://www.pixiv.net/bookmark_new_illust.php?p={page_index}` would be used.
> open these two urls and you will see the difference... in short the answer to your question is `BOTH SFW and NSFW`.
> 
> i think you could just change the value of this option item to see the difference...

Hello and thanks for the response! I was trying to download all my bookmarks all in one go (around 400 pages of them) so I wanted to double check before running it again. It does appear to be as you say, leaving it to "false" will download everything. My "issue" is resolved, thanks!
