### ISSUE TITLE
Possible to change download order of bookmarks? (ascending, descending, etc)

### ISSUE THREAD

**Issue by bananapi761** [Nandaka/PixivUtil2#968]
I believe this issue was questioned before (https://github.com/Nandaka/PixivUtil2/issues/468), but there still doesn't seem to be any way to modify the download order of bookmarks. I think a feature similar to this was in earlier versions at some point, they would ask for the sort order (asc,desc,date,date_d) but it doesn't work and was removed at some point. It downloads based on bookmark order by default, so is there any way to reverse the order (download oldest bookmarks first) so subsequent bookmark downloads can remain in the same order as the site?

**Comment by Nandaka** [comment]
Pixiv remove the sorting feature from the ajax API.
