### ISSUE TITLE
getting SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by akaigua** [Nandaka/PixivUtil2#969]
### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Open your proxy
2. run the program
3. getting SSL: CERTIFICATE_VERIFY_FAILED

**Expected behavior:** [What you expected to happen]
it should successfully connect

**Actual behavior:** [What actually happened]

SSL: CERTIFICATE_VERIFY_FAILED

### Versions
PixivDownloader2 version 20210421

You can fix it by adding 

`import ssl`
`ssl._create_default_https_context = ssl._create_unverified_context`
to the file `PixivBrowserFactory.py`

**Comment by akaigua** [comment]
i didnt do it cos i am not familiar with git :O

**Comment by Nandaka** [comment]
you can set `enableSSLVerification=False` in config.ini already. Please check the readme.

https://github.com/Nandaka/PixivUtil2/blob/master/PixivBrowserFactory.py#L167-L176

**Comment by beterhans** [comment]
on MacOS getting this issue.
you need to install certificate on MacOS

by run 
Install Certificates.command
Update Shell Profile.command
under
Python installed folder mine is /Application/Python3.12
