### ISSUE TITLE
How to redownload deleted folders?

### ISSUE THREAD

**Issue by oluapris** [Nandaka/PixivUtil2#97]
I accidentally deleted a folder I recently downloaded. Is there any way to download it again?

**Comment by cglmrfreeman** [comment]
What was in it? Did you download based on tag artist favcount?

**Comment by oluapris** [comment]
It was from http://pixiv.net/member_illust.php?id=14657 and I downloaded by member ID.

**Comment by cglmrfreeman** [comment]
Try "pixiv.exe -s 1 14657 -x"

**Comment by Nandaka** [comment]
or try to set ```alwayscheckfilesize = True``` in config.ini.

remember to reset back to False after complete.
