### ISSUE TITLE
Feature Request: Compressing images after downloading

### ISSUE THREAD

**Issue by somebody1234** [Nandaka/PixivUtil2#970]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description
An option to use imagemagick (?) or other custom command to compress and/or resize images - a lot of the images can take up to 20+MB which is kinda unfortunate

**Comment by Nandaka** [comment]
set 'downloadresized = True' in config.ini?

**Comment by somebody1234** [comment]
ahwait

**Comment by somebody1234** [comment]
i don't think so? i'd rather have something that's as high quality as possible (so webp, downscaled to a certain resolution)

**Comment by Terryble2** [comment]
Looking at this issue and would be inclined to implement. Curious what @Nandaka thoughts are on including a new dependence? (most likely Pillow)

**Comment by Nandaka** [comment]
add a logic to call external program to do some post processing. You can use this to call any program to do the compression, e.g. imagemagick or others

```
Add config in [DownloadControl] section:
- enablePostProcessing = default False. Set to true to enabled post processing cmd for every downloaded files
- postProcessingCmd = command to execute. add %filename% to pass the downloaded filename.

NO ERROR HANDLING AT ALL, use on your own risk.
```

**Comment by Terryble2** [comment]
In looking at the code base I'm noticing the enablePostProcessing config option which seems to be never used. Could this be a location to hook into instead of adding a new option?

Also I don't see any reason we can't use ffmpeg to do simple image resizing operations.

I think I can have this feature in pretty quickly.

**Comment by somebody1234** [comment]
ok... ran into a problem. if the format is different, i think it makes clean up db no longer work properly (since the original file is no longer there)?

**Comment by Nandaka** [comment]
you need to update the `db.sqlite` from your own script if you want to change the filename
