### ISSUE TITLE
No longer runs on Windows 7

### ISSUE THREAD

**Issue by Nanoka** [Nandaka/PixivUtil2#971]
Latest release doesn't run on Windows 7.
When launched this error is shown:
![2021-07-02_02-38-04](https://user-images.githubusercontent.com/59450043/124225945-a9b8fd80-dade-11eb-8eca-88f517369720.png)
After clicking OK it crashes with the message "FATAL ERROR: Could not load python library", probably because Python 3.9 does not support Windows 7.
I don't know if this can be worked around or I have to keep using the older version until I can upgrade the OS.

**Comment by gummykage** [comment]
Try installing this: https://github.com/abbodi1406/vcredist/releases/download/v0.50.0/VisualCppRedist_AIO_x86_x64_50.zip

**Comment by Nandaka** [comment]
alternatively you can run from source code directly.
See: https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

**Comment by gummykage** [comment]
Thank you Nandaka, this works perfectly. Appreciate the update.

**Comment by Nanoka** [comment]
Thanks, didn't think that would work without python 3.9.

**Comment by gummykage** [comment]
@Nandaka Just curiosity what did you change in the config file that it says its going to reset to default value when its invalid when I copied the config from the older folder?

**Comment by Nandaka** [comment]
from the release page:
![image](https://user-images.githubusercontent.com/836867/124313472-7be9bc80-dba3-11eb-9f0e-12df076fc997.png)

**Comment by WhiteSp1rit** [comment]
Same problem. Will versions run from source on python 3.8 continue to work, or at some point those will stop working too?

**Comment by Nandaka** [comment]
> python 3.8

From the python website, it is considered as legacy.
![image](https://user-images.githubusercontent.com/836867/124531917-12d3a480-de42-11eb-9c19-30ba810ce40d.png)

> new install

db.sqlite, config.ini are the minimum. 

optional if you modify the file:

- novel_template.html
- template.html
- batch_job.json
- content_provider.json
- blacklist_members.txt
- blacklist_tags.txt
- ignore_list.txt
- list.txt

**Comment by MeiHouwang** [comment]
Will there be Win7 support? I don't think I'll move over to w10 in the next 3-5 years.

**Comment by Nandaka** [comment]
nope as python 3.8 is considered legacy and doesn't have binary update anymore, but you can run from source code, See: https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

**Comment by MeiHouwang** [comment]
Sigh, and I have a work environment in Python 2.7, having additional 3.x install is super inconvenient to me :(

**Comment by Nandaka** [comment]
use docker? https://github.com/Nandaka/PixivUtil2/pull/740

**Comment by fireattack** [comment]
I wish we can at least keep the source code itself compatible with Python 3.8, since it's still widely used. 

I assume it is the case for now?

**Comment by Nandaka** [comment]
source code still able to run on older 3.8 version, but I don't know how long for the supporting library.

**Comment by outlaw420** [comment]
Sad day for windows 7 users.
Guess I'll have to move on to gallery-dl, though it's not as good as this downloader for pixiv
):

**Comment by gummykage** [comment]
Run win10 in vmware workstation if it really becomes inconvenient.

**Comment by Nandaka** [comment]
> nope as python 3.8 is considered legacy and doesn't have binary update anymore, but you can run from source code, See: https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)
