### ISSUE TITLE
Windows security recognizes pixivutil2 as Zpevdo.B

### ISSUE THREAD

**Issue by Butterfly-Dragon** [Nandaka/PixivUtil2#972]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Windows security recognizes pixivutil2 as Zpevdo.B

### Steps to Reproduce

1. execute Pixuvutil2
2. Windows security takes action

**Expected behavior:** 

normal execution

**Actual behavior:** 

windows security blocked internet access and i had to "unquarantine" the "severe" threat

### Versions

2021-07-02

**Comment by Nandaka** [comment]
pls run from source code if you are not sure, no changes will be provided on the exe (or rather I cannot do anything).

**Comment by Butterfly-Dragon** [comment]
Oh, i know you did nothing and that your program does nothing wrong.

I am just warning you that as of this morning it gets recognized as such, so you can take steps to avoid it.

**Comment by Nandaka** [comment]
Fyi, I tried to scan locally and it didn't detect anything.
![image](https://user-images.githubusercontent.com/836867/124431619-254ad100-dda3-11eb-8535-31c8fa5deb81.png)
![image](https://user-images.githubusercontent.com/836867/124431654-3267c000-dda3-11eb-9f02-4164833d3821.png)

Also I tried to download the file in https://github.com/Nandaka/PixivUtil2/releases/tag/v20210702 = it didn't detect anything.
![image](https://user-images.githubusercontent.com/836867/124431781-66db7c00-dda3-11eb-8569-b2122037a648.png)

**Comment by Butterfly-Dragon** [comment]
that contrasts my experience this morning (a couple of hours ago)
![image](https://user-images.githubusercontent.com/33538906/124434685-742d4200-dd74-11eb-99f6-ff4e84b1ee0d.png)

![image](https://user-images.githubusercontent.com/33538906/124434734-83ac8b00-dd74-11eb-8667-2b7a1c513733.png)

**Comment by GoAwayNow** [comment]
Virus Total confirms Microsoft detects it, along with eight other antiviruses.

https://www.virustotal.com/gui/file/fd67f71e83e00d5baf325ba983da38a4787f38602e90e58e5b85e79cf4dffcb4/detection

**Comment by Nandaka** [comment]
Weird, what is the SHA256?
![image](https://user-images.githubusercontent.com/836867/124440823-a27b4380-ddad-11eb-9f10-0cea71d5847b.png)

10FAB3245175FCE17D6D15C6E766AD6027F74F49BC9FEF78FB2AA5AAF0C28F58

**Comment by Nandaka** [comment]
Here is the result from virus total, but I don't see Zpevdo.B
![image](https://user-images.githubusercontent.com/836867/124440995-cf2f5b00-ddad-11eb-82bf-6988fff65211.png)

**Comment by GoAwayNow** [comment]
The scan I linked was of PixivUtil.exe, not the release zip.

Also the SHA256 of the zip is the same as yours.

![Screenshot 2021-07-05 033033](https://user-images.githubusercontent.com/56808771/124441635-7cb85500-dd41-11eb-873d-0e9b754617bb.png)
10fab3245175fce17d6d15c6e766ad6027f74f49bc9fef78fb2aa5aaf0c28f58

**Comment by Nandaka** [comment]
I guess if you want to avoid this, you can run it from source code, which have better compat, see https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

**Comment by ShiroTora** [comment]
![image](https://user-images.githubusercontent.com/10827947/124494168-cee78d80-ddb6-11eb-9904-cdd8b1bee29f.png)

 i get a virus sresult from MSE

**Comment by gnarf1975** [comment]
Same problem. Switched to previous version.

**Comment by Nandaka** [comment]
run from source is recommended: https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

**Comment by Butterfly-Dragon** [comment]
it says you need to "download the required library:" but does not say which. Will try later if there actually is anything to add or if it is all handled by the "requirements.txt" once i have time to exist.

**Comment by Nandaka** [comment]
> pip install -r c:\pixivutil\requirements.txt

This will add the required library.

**Comment by Butterfly-Dragon** [comment]
i tried that... all i got was to get pixivutil2.py removed by windows as "being remotely controlled by an agent"

**Comment by Nandaka** [comment]
the heck, then I have no idea anymore...

**Comment by Butterfly-Dragon** [comment]
probably misidentifies some component as a "remote agent" and actions are taken to prevent it taking control.

That said for now i went under:

`settings>update and security>windows security>virus and threat protection>virus and threat protection settings>exclusions>add exclusions`

and added PixivUtil2.exe and .py as exclusions

**Comment by FriedGenera** [comment]
Was PyInstaller used for the exe? Apparently it causes a bunch of false positives

**Comment by Nandaka** [comment]
it uses `py2exe            0.10.4.0` from https://pypi.org/project/py2exe/

**Comment by FriedGenera** [comment]
Do you use the precompiled bootloader?

**Comment by FriedGenera** [comment]
I went ahead and submitted it to microsoft, so hopefully they'll clear it and windows defender doesn't keep quarantining it.

**Comment by Nandaka** [comment]
> 
> 
> Do you use the precompiled bootloader? If you do, recompiling your own might get the false positive detections to go down, but after that there's not much else to do other than reporting it to the companies.

I'm using pip to install/update the library, so I don't think it re-compile anything. I assume it just use the packaged `whl` file.

> I went ahead and submitted it to microsoft, so hopefully they'll clear it and windows defender doesn't keep quarantining it.

Thanks 😄

**Comment by FriedGenera** [comment]
Alright Microsoft got back and said it was cleared, just checked virustotal, it's no longer showing it as detected under Microsoft-

https://www.virustotal.com/gui/file/fd67f71e83e00d5baf325ba983da38a4787f38602e90e58e5b85e79cf4dffcb4/detection

If someone can test if defender still quarantining that'd be great

**Comment by Revemohl** [comment]
@Nandaka 
Looks like this is happening again with v20210822, but it's detecting Trojan:Win32/Wacatac.B!ml instead. Didn't want to open a new issue because it's basically the same thing as this one.

**Comment by shinji257** [comment]
It seems to flag the zip but nothing inside the zip.  I unpacked it and had no further detections from it.

**Comment by Nandaka** [comment]
weird. I also try to compress it as 7z and it still show as virus in virustotal...
![image](https://user-images.githubusercontent.com/836867/130408473-311226c8-784c-44e9-a00c-68fb3cf7d861.png)

**Comment by Nandaka** [comment]
recompile with py3.8.10 got slightly different result.
![image](https://user-images.githubusercontent.com/836867/130410891-e42bd0f6-bccb-4078-a7c6-59d9a38e4700.png)

**Comment by densetsumeru** [comment]
Windows Defender decided it's something new today.
![image](https://user-images.githubusercontent.com/57646076/131928536-75929158-7b3d-4519-8981-0e9bcffecfd1.png)

**Comment by shiinjii** [comment]
3 detections in 1 day
![Capture](https://user-images.githubusercontent.com/90084254/132084919-1d6b875a-8982-4904-bafc-841f23b9072d.PNG)

**Comment by yul-oh895** [comment]
> 
> 
> run from source is recommended: https://github.com/Nandaka/PixivUtil2/wiki/IDE-Enviroment-(Windows)

This is my first time I'm running it from source. Is this going to detect the old database file, settings, etc. or do I need to do something to else to restore them?

**Comment by kial0218** [comment]
Avast recognizes 'PixivUtil2.exe' in 'pixivutil20220924-64bit.zip' as malware.
Even if an exception is handled, the command prompt window is immediately closed.
