### ISSUE TITLE
Error with ffmpeg ( creating gif )

### ISSUE THREAD

**Issue by Samapoke** [Nandaka/PixivUtil2#974]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

[This seem to happen when I turned creategif = True]

### Steps to Reproduce

1. Change creategif from False to True
2. Turn on PixivUtil2
3. Wait for loading

**Expected behavior:** The program worked

**Actual behavior:** It's give me this error
![Screenshot (50)](https://user-images.githubusercontent.com/77906482/124778744-668ddd00-df6b-11eb-91a0-087c83364471.png)

### Versions
v20210702 - lastest version

You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
you need to download https://www.ffmpeg.org/ see #847 and #818

**Comment by Samapoke** [comment]
Nandaka can you make tutorial about donwload ffmpeg and install it
?

**Comment by Samapoke** [comment]
> you need to download https://www.ffmpeg.org/ see #847 and #818

Nandaka can you make tutorial about donwload ffmpeg and install it

**Comment by Nandaka** [comment]
no, just google it.
