### ISSUE TITLE
v20210702 - Virus Found

### ISSUE THREAD

**Issue by matsumotokenji** [Nandaka/PixivUtil2#975]
Since 5th July windows defender decided that PixivUtil2 v20210702 is a threat Trojan:Win32/Zpevdo.B.

https://www.virustotal.com/gui/file/fd67f71e83e00d5baf325ba983da38a4787f38602e90e58e5b85e79cf4dffcb4/detection

Anyone same issue?

**Comment by densetsumeru** [comment]
Yeah I noticed I was getting a warning from Windows Defender for the latest version.

**Comment by Nandaka** [comment]
see #972
