### ISSUE TITLE
[Question] download list of artists already in db ?

### ISSUE THREAD

**Issue by baraa272** [Nandaka/PixivUtil2#976]
how to download a list of artist_id already included in db ??? and no option 4 doesnt work 
i want to download newer images of artists

**Comment by Nandaka** [comment]
`d` -> `3` ?

**Comment by baraa272** [comment]
wait a second this export a list ? then what now ?

**Comment by Nandaka** [comment]
use it and use option 4 from main menu?

**Comment by baraa272** [comment]
thanks this solved it
