### ISSUE TITLE
Trailing . left on image name but not info file.

### ISSUE THREAD

**Issue by Baa14453** [Nandaka/PixivUtil2#982]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

#627 removes the trailing `.` from filenames for info files.
If the title is a `.` this seems to only apply to the downloaded info files and not the image file itself. So they end up with different names.

![image](https://user-images.githubusercontent.com/9057997/125501517-e11f923f-710f-496e-af77-a9cdb5618a57.png)

### Steps to Reproduce

1. Enable Info file downloading
2. Download image `91226078`
3. Observe naming discrepancy.

**Expected behavior:**
Both files with have the same names, different extensions.

**Actual behavior:**
One file ommits the additional `.` the other doesn't.

### Versions

20210702

**Comment by Nandaka** [comment]
Are you using windows?
just for reference for me https://stackoverflow.com/a/16203594

**Comment by Baa14453** [comment]
no, using Ubuntu 20.04
The files create OK but because the filenames are different between the info file and image file, my software doesn't associate them

-------- Original Message --------

**Comment by Nandaka** [comment]
Oo, then it might be a bit difficult for me to test, as windows will automatically truncate the ending period... and I don't put special handling with `\\?\` in windows (i only have windows box)

**Comment by Baa14453** [comment]
I'll see what I can do
