### ISSUE TITLE
[question] The filename-setting can not work as my wish.

### ISSUE THREAD

**Issue by railannad** [Nandaka/PixivUtil2#987]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [ ] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

[Description of the bug or feature]
I edited `config.ini` as `FANBOX %artist% (%member_id%)\%title%\%urlFilename% - %title%`

![image](https://user-images.githubusercontent.com/36919867/126097698-0fed290e-f970-4dc4-a1e1-4c62b05398d1.png)

Then I hope the script can put all images into a same folder because this images in the same post (they have the same title). 
But the actual situation is that only the first image in the folder and the rest of images all in root dir

![image](https://user-images.githubusercontent.com/36919867/126098631-8ce623da-f8fc-47c6-bf88-3c6883f625fc.png)

### Versions
20210702
You can get this information from executing `PixivUtil2.py --help`.
Latest version available in https://github.com/Nandaka/PixivUtil2/releases

**Comment by Nandaka** [comment]
change the other fanbox file format too??
