### ISSUE TITLE
[Feature Request] Safe-only search?

### ISSUE THREAD

**Issue by Syampuuh** [Nandaka/PixivUtil2#988]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I'm surprised that this does not appear to be an existing feature or one suggested yet, but would it be possible to add an option for a safe-only search? At a glance, the ajax being used seems to have no issue with `&mode=safe`.

**Comment by Nandaka** [comment]
You can configure that from pixiv website.
![image](https://user-images.githubusercontent.com/836867/126135153-ff569a16-a6f1-4305-b907-706db37d6759.png)

**Comment by Syampuuh** [comment]
Oh, strange, the last time I tried that it didn't seem to affect the downloader, but I guess that was a while ago. Thank you.

**Comment by Nandaka** [comment]
you need to update the cookie to take effect
