### ISSUE TITLE
Error when downloading by Tag and member ID

### ISSUE THREAD

**Issue by oluapris** [Nandaka/PixivUtil2#99]
Looping... for http://www.pixiv.net/member_illust.php?id=889142&tag=R-18&p=1&ord
er=date_d
Image #1
Image Id: 53493000
Bookmark Count: 0
Processing Image Id: 53493000
Image ID (53493000): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53493000.html
Image #2
Image Id: 53500048
Bookmark Count: 0
Processing Image Id: 53500048
Image ID (53500048): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53500048.html
Image #3
Image Id: 53496246
Bookmark Count: 0
Processing Image Id: 53496246
Image ID (53496246): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53496246.html
Image #4
Image Id: 53501802
Bookmark Count: 0
Processing Image Id: 53501802
Image ID (53501802): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53501802.html
Image #5
Image Id: 53488982
Bookmark Count: 0
Processing Image Id: 53488982
Image ID (53488982): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53488982.html
Image #6
Image Id: 53489561
Bookmark Count: 0
Processing Image Id: 53489561
Image ID (53489561): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53489561.html
Image #7
Image Id: 53508977
Bookmark Count: 0
Processing Image Id: 53508977
Image ID (53508977): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53508977.html
Image #8
Image Id: 53500745
Bookmark Count: 0
Processing Image Id: 53500745
Image ID (53500745): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53500745.html
Image #9
Image Id: 53495177
Bookmark Count: 0
Processing Image Id: 53495177
Image ID (53495177): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53495177.html
Image #10
Image Id: 53515457
Bookmark Count: 0
Processing Image Id: 53515457
Image ID (53515457): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53515457.html
Image #11
Image Id: 53488161
Bookmark Count: 0
Processing Image Id: 53488161
Image ID (53488161): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53488161.html
Image #12
Image Id: 53490784
Bookmark Count: 0
Processing Image Id: 53490784
Image ID (53490784): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53490784.html
Image #13
Image Id: 53491754
Bookmark Count: 0
Processing Image Id: 53491754
Image ID (53491754): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53491754.html
Image #14
Image Id: 53489440
Bookmark Count: 0
Processing Image Id: 53489440
Image ID (53489440): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53489440.html
Image #15
Image Id: 53494784
Bookmark Count: 0
Processing Image Id: 53494784
Image ID (53494784): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53494784.html
Image #16
Image Id: 53496885
Bookmark Count: 0
Processing Image Id: 53496885
Image ID (53496885): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53496885.html
Image #17
Image Id: 53489936
Bookmark Count: 0
Processing Image Id: 53489936
Image ID (53489936): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53489936.html
Image #18
Image Id: 53488459
Bookmark Count: 0
Processing Image Id: 53488459
Image ID (53488459): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53488459.html
Image #19
Image Id: 53508377
Bookmark Count: 0
Processing Image Id: 53508377
Image ID (53508377): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53508377.html
Image #20
Image Id: 53515948
Bookmark Count: 0
Processing Image Id: 53515948
Image ID (53515948): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53515948.html
Image #21
Image Id: 53488027
Bookmark Count: 0
Processing Image Id: 53488027
Image ID (53488027): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53488027.html
Image #22
Image Id: 53501776
Bookmark Count: 0
Processing Image Id: 53501776
Image ID (53501776): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53501776.html
Image #23
Image Id: 53512731
Bookmark Count: 0
Processing Image Id: 53512731
Image ID (53512731): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53512731.html
Image #24
Image Id: 53493596
Bookmark Count: 0
Processing Image Id: 53493596
Image ID (53493596): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53493596.html
Image #25
Image Id: 53520108
Bookmark Count: 0
Processing Image Id: 53520108
Image ID (53520108): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53520108.html
Image #26
Image Id: 53512133
Bookmark Count: 0
Processing Image Id: 53512133
Image ID (53512133): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53512133.html
Image #27
Image Id: 53499597
Bookmark Count: 0
Processing Image Id: 53499597
Image ID (53499597): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53499597.html
Image #28
Image Id: 53488142
Bookmark Count: 0
Processing Image Id: 53488142
Image ID (53488142): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53488142.html
Image #29
Image Id: 53500988
Bookmark Count: 0
Processing Image Id: 53500988
Image ID (53500988): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53500988.html
Image #30
Image Id: 53514898
Bookmark Count: 0
Processing Image Id: 53514898
Image ID (53514898): 'NoneType' object has no attribute 'find'
Dumping html to: Error medium page for image 53514898.html
Last page: 1
done

Instead of downloading what I input, it downloads html files called "Error medium page for image ###########.html" which lead to images by different artists.

**Comment by Nandaka** [comment]
can you upload the pages? Cos I tried to use in my PC (option 10) and it downloads ok.

Looks like you have issue with login, try to use cookie method (check the readme.txt).
