### ISSUE TITLE
Has the latest build's exe been submitted to Microsoft?

### ISSUE THREAD

**Issue by FriedGenera** [Nandaka/PixivUtil2#990]
It's still getting flagged on virustotal, so I was wondering if anyone has actually submitted it to microsoft yet? Sometimes it might get flagged by other antivirus because they're ai based and rely on detection from other sources like microsoft, so it might get rid of the false flag from windows defender.

**Comment by Nandaka** [comment]
I don;t have plan for that.

Related to #972
