### ISSUE TITLE
[Feature Request/ Question] Move already downloaded images to a new location

### ISSUE THREAD

**Issue by user4302** [Nandaka/PixivUtil2#991]
### Prerequisites

* [✔] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [✔] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [✔] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

I have images (and some zips) downloaded to a root folder, and they are organized into folders for the user ["%artist% (%member_id%)] and each file in the folder is saved with [%urlFilename% - %title%"]

**Expected behavior:** [What you expected to happen]

Is it possible when I run a batch job (I always use batch jobs), or another option in the menu, to for example download all with the tag "sky" for certain member IDs to download any new images, as well as move any existing images that match the criteria to the specified folder?

for example image01 is in images/username/image01.jpg
and when Im downloading images with the tag "sky" i want to move the existing image to
images/tagName/username/image01.jpg
as well as download any new images

**Comment by Nandaka** [comment]
I think it should be possible as it store the saved filename in the table and it can check if it was previously downloaded and the saved filename still exists.
There is a risk where the images have tags that referenced in different jobs, so it will only available in the last matching job.

related line https://github.com/Nandaka/PixivUtil2/blob/master/PixivDownloadHandler.py#L134
