### ISSUE TITLE
Not logged in to Fanbox, could not update cookie string

### ISSUE THREAD

**Issue by shuaboo** [Nandaka/PixivUtil2#993]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [X] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

When trying to download from fanbox, I get the following error:
Trying to log in FANBOX with saved cookie
Not logged in to FANBOX, trying to update FANBOX cookie...
Could not update FANBOX cookie string.

I have login information set with the pixiv cookie, and I also tried inputting the fanbox.cc sessid in the fanbox cookie field and could not get it to download from fanbox

### Versions

version 20210702

**Comment by bluerthanever** [comment]
Looks like the method needs to be updated.
I'll have a look at it.

**Comment by bluerthanever** [comment]
hmm... i just tried again. and it seems fine.
is your cookie string for pixiv valid? even though that's kinda obvious otherwise you would not be able to hit the option to see the error.
or do you have the log file to share?

**Comment by shuaboo** [comment]
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/6948522/pixivutil.log)

**Comment by bluerthanever** [comment]
should be updated in #995
