### ISSUE TITLE
Using list.txt: getting inclusive R-18 or R-18G, but not SFW

### ISSUE THREAD

**Issue by lowercase-donkey** [Nandaka/PixivUtil2#998]
My goal: downloading from `list.txt` all images either R-18 or R-18G, but not SFW. `(R-18 || R-18G) && !SFW`

I don't mind running the program twice if required, just wondering what the best setup would be.  Is it:

1. R-18 on, no tag
2. R-18 off, R-18G tag on

Secondarily, is there a way to set R-18G on for some artists but off for others?  Unfortunately, it's a very broad tag.

 IIRC there was some discussion in my last issue on moving list.txt to JSON, but I don't think that's happened and I cannot find my original issue.  Thank you very much.

**Comment by Nandaka** [comment]
use https://github.com/Nandaka/PixivUtil2/wiki/Using-Batch-Job-(Experimental) and follow `"job-1-member-id-with-tags"` sample?

**Comment by lowercase-donkey** [comment]
Hmm, no matter how I structure things I get

```
2021-08-16 23:32:52,035 - PixivUtil20210702 - INFO - Batch Mode from json (b).
2021-08-16 23:32:52,045 - PixivUtil20210702 - ERROR - Unknown Error: Expecting property name enclosed in double quotes: line 7 column 9 (char 147)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1388, in main
  File "PixivUtil2.py", line 1108, in main_loop
  File "PixivBatchHandler.pyc", line 180, in process_batch_job
  File "json\__init__.pyc", line 293, in load
  File "json\__init__.pyc", line 346, in loads
  File "json\decoder.pyc", line 337, in decode
  File "json\decoder.pyc", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 9 (char 147)
2021-08-16 23:32:52,049 - PixivUtil20210702 - ERROR - Unknown Error, please check the log file: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting property name enclosed in double quotes: line 7 column 9 (char 147)'), <traceback object at 0x04B76328>)
2021-08-16 23:32:52,049 - PixivUtil20210702 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 1388, in main
  File "PixivUtil2.py", line 1108, in main_loop
  File "PixivBatchHandler.pyc", line 180, in process_batch_job
  File "json\__init__.pyc", line 293, in load
  File "json\__init__.pyc", line 346, in loads
  File "json\decoder.pyc", line 337, in decode
  File "json\decoder.pyc", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 9 (char 147)
```

**Comment by Nandaka** [comment]
try this one (member nsfw)

``` json
{
    "jobs": {
        "job-1-member-id-with-tags": {
            "enabled": true,
            "job_type": "1",
            "member_id": 5375435,
            "start_page": 1,
            "end_page": 0,
            "tags": "R-18",
            "option": {
                "rootDirectory": "d:/test/"
            }
        }
    }
}

```

**Comment by lowercase-donkey** [comment]
As long as I switch to a valid rootDirectory, that works fine.

Is there a version that would work with 4/list.txt?

**Comment by Nandaka** [comment]
nope, list.txt is limited to custom folder only https://github.com/Nandaka/PixivUtil2#listtxt-format

**Comment by lowercase-donkey** [comment]
Ok, so I don't use dynamic folders for artists, since some of my artists keep changing their names and the ids, though static, aren't helpful for organizing.  So I was using list to make bespoke folders for each artist.

In this new system, is there a simpler way to get `(R-18 || R-18G) && !SFW` other than making two `job-1-member-id-with-tags`, each with the same bespoke folder?

Basically, what's the best way to get `(R-18 || R-18G) && !SFW` for a series of artists, but put each artist in a unique static folder.

**Comment by Nandaka** [comment]
try this?

''' json
{
    "jobs": {
        "job-1-member-id-with-tags": {
            "enabled": true,
            "job_type": "1",
            "member_ids": [73988118, 57959650, 78942244, 80247847, 81157603],
            "start_page": 1,
            "end_page": 0,
            "tags": "R-18",
            "option": {
                "filenameFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameMangaFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameInfoFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameMangaInfoFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "avatarNameFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "rootDirectory": "d:/test/"
            }
        },
        "job-2-member-id-with-tags": {
            "enabled": true,
            "job_type": "1",
            "member_ids": [73988118, 57959650, 78942244, 80247847, 81157603],
            "start_page": 1,
            "end_page": 0,
            "tags": "R-18G",
            "option": {
                "filenameFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameMangaFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameInfoFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "filenameMangaInfoFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "avatarNameFormat": "%artist% (%member_id%)/%urlFilename% - %title%",
                "rootDirectory": "d:/test/"
            }
        }
    }
}

```

**Comment by lowercase-donkey** [comment]
That's not quite what I'm looking for.  There's no sole source of truth for the IDs (you had to copy paste them in the sample), and you can't map the IDs to unique folders.

**Comment by Nandaka** [comment]
or you can just set the `r18mode = True` in config.ini
```
r18mode

Only list images tagged R18, for member, member's bookmark, and search by tag. Set to True to enable.
```

**Comment by lowercase-donkey** [comment]
I believe R-18 and R-18G are exclusive tags, no?

**Comment by Nandaka** [comment]
Also you cannot get 2 tags in one request if you want to do by member id, the pixiv api doesn't allow that (need separate call for each tag).

**Comment by lowercase-donkey** [comment]
I think that's fine with that data structure, no?  It's just a different way of writing it down.  It has to make two calls to do what I'm asking no matter what.

**Comment by Nandaka** [comment]
no plan to extend list.txt, use the method described https://github.com/Nandaka/PixivUtil2/issues/998#issuecomment-903023515 

You can map to unique folder by setting the root dir or map using member id
